### ISSUE TITLE
TypeError: Too few parameters for typing.Generator; actual 1, expected 3

### ISSUE THREAD

**Issue by gpanouts** [microsoft/nni#1060]
**Short summary about the issue/question**:
I'm trying to use SMAC tuner but it fails with error:
TypeError: Too few parameters for typing.Generator; actual 1, expected 3

Is there any example using SMAC tuner?

**Brief what process you are following**: 
After installing nni and smac (nnictl package install --name=SMAC), i try to start an experiment through examples/trials/mnist. I changed the tuner TPE to SMAC in config.yml and runned:
nnictl create --config ~/nni/examples/trials/mnist/config.yml --port 7083

**nni Environment**:
- nni version: 0.7
- nni mode(local|pai|remote): local
- OS: Ubuntu 18.04.1 LTS
- python version: 3.6.7
- is conda or virtualenv used?: virtualenv is used
- is running in docker?: No

**need to update document(yes/no)**:

**Anything else we need to know**:
- smac version: 0.8.0
- Full output:
`
INFO: expand searchSpacePath: search_space.json to /home/gpanou/nni/examples/trials/mnist/search_space.json 
INFO: expand codeDir: . to /home/gpanou/nni/examples/trials/mnist/. 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gpanou/nni/env/lib/python3.6/site-packages/nni/smac_tuner/smac_tuner.py", line 35, in <module>
    from smac.scenario.scenario import Scenario
  File "/home/gpanou/nni/env/lib/python3.6/site-packages/smac/scenario/scenario.py", line 12, in <module>
    from smac.utils.io.input_reader import InputReader
  File "/home/gpanou/nni/env/lib/python3.6/site-packages/smac/utils/io/input_reader.py", line 2, in <module>
    from smac.configspace import pcs
  File "/home/gpanou/nni/env/lib/python3.6/site-packages/smac/configspace/__init__.py", line 3, in <module>
    from ConfigSpaceNNI.util import get_one_exchange_neighbourhood
  File "ConfigSpaceNNI/util.py", line 84, in init ConfigSpaceNNI.util
  File "/usr/lib/python3.6/typing.py", line 682, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.6/typing.py", line 1131, in __getitem__
    _check_generic(self, params)
  File "/usr/lib/python3.6/typing.py", line 662, in _check_generic
    ("many" if alen > elen else "few", repr(cls), alen, elen))
TypeError: Too few parameters for typing.Generator; actual 1, expected 3
Traceback (most recent call last):
  File "/home/gpanou/nni/env/bin/nnictl", line 10, in <module>
    sys.exit(parse_args())
  File "/home/gpanou/nni/env/lib/python3.6/site-packages/nni_cmd/nnictl.py", line 198, in parse_args
    args.func(args)
  File "/home/gpanou/nni/env/lib/python3.6/site-packages/nni_cmd/launcher.py", line 535, in create_experiment
    launch_experiment(args, experiment_config, 'new', config_file_name)
  File "/home/gpanou/nni/env/lib/python3.6/site-packages/nni_cmd/launcher.py", line 351, in launch_experiment
    check_call([sys.executable, '-c', 'import %s'%(module_name)])
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
`

**Comment by scarlett2018** [comment]
@gpanouts thanks for reporting the issue, all the examples in https://github.com/microsoft/nni/tree/master/examples/trials folder should be apply to use SMAC. 

@QuanluZhang is looking into your issue now, stay tuned.

**Comment by QuanluZhang** [comment]
Hi @gpanouts , the reason of this problem is that python 3.6.7 has more strict type check on Generator (https://docs.python.org/3.6/library/typing.html#typing.Generator). This pr (https://github.com/QuanluZhang/ConfigSpace/pull/4) would fix this bug.

Please using the following commands to uninstall SMAC:
```
python3 -m pip uninstall smac
python3 -m pip uninstall ConfigSpaceNNI
```
Then install SMAC through `nnictl package install --name=SMAC`

**Comment by gpanouts** [comment]
Great! Thank you!
