### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by SunYanCN** [microsoft/nni#1080]
```
[root@gpu-4 keras]# nnictl create --config config.yml 
INFO: expand searchSpacePath: search_space.json to /home/sunyan/ULM/transfomer/keras/search_space.json 
INFO: expand codeDir: . to /home/sunyan/ULM/transfomer/keras/. 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nni.hyperopt_tuner'; 'nni' is not a package
Traceback (most recent call last):
  File "/root/anaconda3/bin/nnictl", line 10, in <module>
    sys.exit(parse_args())
  File "/root/anaconda3/lib/python3.6/site-packages/nni_cmd/nnictl.py", line 198, in parse_args
    args.func(args)
  File "/root/anaconda3/lib/python3.6/site-packages/nni_cmd/launcher.py", line 535, in create_experiment
    launch_experiment(args, experiment_config, 'new', config_file_name)
  File "/root/anaconda3/lib/python3.6/site-packages/nni_cmd/launcher.py", line 351, in launch_experiment
    check_call([sys.executable, '-c', 'import %s'%(module_name)])
  File "/root/anaconda3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/anaconda3/bin/python', '-c', 'import nni.hyperopt_tuner.hyperopt_tuner']' returned non-zero exit status 1.
[root@gpu-4 keras]# pip show nni
Name: nni
Version: 0.7
Summary: Neural Network Intelligence package
Home-page: https://github.com/Microsoft/nni
Author: Microsoft NNI team
Author-email: nni@microsoft.com
License: MIT
Location: /root/anaconda3/lib/python3.6/site-packages
Requires: requests, PythonWebHDFS, json-tricks, colorama, schema, astor, numpy, hyperopt, coverage, ruamel.yaml, scipy, psutil
Required-by: 

```

**Comment by SunYanCN** [comment]
pip installed nni but not found

**Comment by SunYanCN** [comment]
![image](https://user-images.githubusercontent.com/42198591/57749767-0e078000-7712-11e9-8a26-ce6ff500042d.png)

**Comment by SunYanCN** [comment]
![image](https://user-images.githubusercontent.com/42198591/57752573-36947780-771c-11e9-9967-60a318649121.png)

**Comment by leelaylay** [comment]
@SunYanCN  It seems that you did not install NNI in right way.

```bash
# uninstall NNI first
pip uninstall nni 
# if you install nni from the source code, Makefile can help you to uninstall NNI
make uninstall && make clean

# make sure your pip is in your conda environment [e.g. /root/anaconda3/bin/pip ]
which pip

# install NNI from source code or pip source

# pip source
pip uninstall nni 

# source code
make easy-install
```


It seems that you install conda in your server, so you have to specific the command path in your config file.
```yaml
trial:
  command: /root/anaconda3/bin/python3 FileName.py
  codeDir: .
  gpuNum: 1
```

**Comment by scarlett2018** [comment]
@SunYanCN - had you tried to config your command path as @leelaylay suggested? does it work for you know?

**Comment by scarlett2018** [comment]
closing it for now. @SunYanCN - feel free to reopen the issue if you are still having the problem on your side.
