### ISSUE TITLE
GridSearch tuner incorrectly parses parameters of quniform type

### ISSUE THREAD

**Issue by AntonP84** [microsoft/nni#1091]
**Short summary about the issue/question**: GridSearch tuner incorrectly parses parameters of quniform type. As if it treats *q* in *{“_type”:”quniform”,”_value”:[low, high, q]}* as count, not interval.

**Brief what process you are following**: 

**How to reproduce it**: 
```bash
cd nni/examples/trials/mnist
echo '{"dropout_rate":{"_type":"quniform","_value":[0.5, 0.9, 0.1]}}' > search_space.json
sed -i 's/builtinTunerName: TPE/builtinTunerName: GridSearch/g' config.yml
sed -i 's/classArgs:/# classArgs:/g' config.yml
sed -i 's/optimize_mode:/# optimize_mode:/g' config.yml
nnictl create --config config.yml
```

checked the log:
```
user@bbf49569313d:~/.../OfO214QO/log$ cat dispatcher.log
[05/20/2019, 05:42:28 PM] INFO (nni.msg_dispatcher_base/MainThread) Start dispatcher
[05/20/2019, 05:42:28 PM] ERROR (nni.msg_dispatcher_base/Thread-1) The number of values sampled (q) should be at least 2
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/nni/msg_dispatcher_base.py", line 102, in command_queue_worker
    self.process_command(command, data)
  File "/home/user/.local/lib/python3.7/site-packages/nni/msg_dispatcher_base.py", line 160, in process_command
    command_handlers[command](data)
  File "/home/user/.local/lib/python3.7/site-packages/nni/msg_dispatcher.py", line 94, in handle_initialize
    self.tuner.update_search_space(data)
  File "/home/user/.local/lib/python3.7/site-packages/nni/gridsearch_tuner/gridsearch_tuner.py", line 138, in update_search_space
    self.expanded_search_space = self.json2paramater(search_space)
  File "/home/user/.local/lib/python3.7/site-packages/nni/gridsearch_tuner/gridsearch_tuner.py", line 81, in json2paramater
    chosen_params[key] = self.json2paramater(ss_spec[key])
  File "/home/user/.local/lib/python3.7/site-packages/nni/gridsearch_tuner/gridsearch_tuner.py", line 77, in json2paramater
    chosen_params = self.parse_qtype(_type, _value)
  File "/home/user/.local/lib/python3.7/site-packages/nni/gridsearch_tuner/gridsearch_tuner.py", line 107, in parse_qtype
    return self._parse_quniform(param_value)
  File "/home/user/.local/lib/python3.7/site-packages/nni/gridsearch_tuner/gridsearch_tuner.py", line 99, in _parse_quniform
    raise RuntimeError("The number of values sampled (q) should be at least 2")
```

**nni Environment**:
- nni version: 0.7
- nni mode(local|pai|remote): local
- OS: ubuntu
- python version: 3.7.3
- is conda or virtualenv used?: no
- is running in docker?: yes

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by Crysple** [comment]
Hi. Sorry to cause confusion to you.
GridSearch tuner is some kind of different from others. Q does mean count according to our design because of convenience. [Here is the doc](https://nni.readthedocs.io/en/latest/BuiltinTuner.html#GridSearch)

**Comment by AntonP84** [comment]
Thanks @Crysple for pointing this out. I am closing the issue.
