### ISSUE TITLE
BOHB experiment - scipy version

### ISSUE THREAD

**Issue by VincentMatthys** [microsoft/nni#1098]
Issue : 

BOHB experiment started (so says `nnictl` ) but no experiment runs

```
INFO: Successfully started experiment!
-----------------------------------------------------------------------
The experiment id is JhglNJSn
The Web UI urls are: http://172.17.0.2:8080   http://127.0.0.1:8080
```

Looking for logs in `nni/experiments/JhglNJSn/log/nnimanager.log`:
```
[5/22/2019, 10:24:56 AM] ERROR [ 'Read GPU summary failed with error: ',
  { ChildProcessError: Command failed: tail -n 1 /tmp/nni/script/gpu_metrics
  tail: cannot open '/tmp/nni/script/gpu_metrics' for reading: No such file or directory
   `tail -n 1 /tmp/nni/script/gpu_metrics` (exited with error code 1)
      at callback (/home/appuser/.local/nni/node_modules/child-process-promise/lib/index.js:33:27)
      at ChildProcess.exithandler (child_process.js:296:5)
      at ChildProcess.emit (events.js:182:13)
      at maybeClose (internal/child_process.js:962:16)
      at Socket.stream.socket.on (internal/child_process.js:381:11)
      at Socket.emit (events.js:182:13)
      at Pipe._handle.close (net.js:606:12)
    name: 'ChildProcessError',
    code: 1,
    childProcess:
     { ChildProcess: [Function],
       fork: [Function: fork],
       _forkChild: [Function: _forkChild],
       exec: [Function: exec],
       execFile: [Function: execFile],
       spawn: [Function: spawn],
       spawnSync: [Function: spawnSync],
       execFileSync: [Function: execFileSync],
       execSync: [Function: execSync] },
    stdout: '',
    stderr:
     'tail: cannot open \'/tmp/nni/script/gpu_metrics\' for reading: No such file or directory\n' } ]
```

But the real problem lies in `nni/experiments/JhglNJSn/log/dispatcher.log`
```
[05/22/2019, 10:24:57 AM] DEBUG (nni.main/MainThread) START
[05/22/2019, 10:24:57 AM] ERROR (nni.main/MainThread) cannot import name 'factorial'
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.5/site-packages/nni/__main__.py", line 202, in <module>
    main()
  File "/home/appuser/.local/lib/python3.5/site-packages/nni/__main__.py", line 137, in main
    args.advisor_args, True)
  File "/home/appuser/.local/lib/python3.5/site-packages/nni/__main__.py", line 53, in create_builtin_class_instance
    class_module = importlib.import_module(AdvisorModuleName[classname])
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/appuser/.local/lib/python3.5/site-packages/nni/bohb_advisor/bohb_advisor.py", line 37, in <module>
    from .config_generator import CG_BOHB
  File "/home/appuser/.local/lib/python3.5/site-packages/nni/bohb_advisor/config_generator.py", line 38, in <module>
    import statsmodels.api as sm
  File "/home/appuser/.local/lib/python3.5/site-packages/statsmodels/api.py", line 16, in <module>
    from .discrete.discrete_model import (Poisson, Logit, Probit,
  File "/home/appuser/.local/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py", line 45, in <module>
    from statsmodels.distributions import genpoisson_p
  File "/home/appuser/.local/lib/python3.5/site-packages/statsmodels/distributions/__init__.py", line 2, in <module>
    from .edgeworth import ExpandedNormal
  File "/home/appuser/.local/lib/python3.5/site-packages/statsmodels/distributions/edgeworth.py", line 7, in <module>
    from scipy.misc import factorial
ImportError: cannot import name 'factorial'
```

**How to reproduce it**: 

Runs the `mnist-advisor` example with BOHB experiment, using `scipy 1.13`

`nnictl create --config nni/blob/master/examples/trials/mnist-advisor/config_bohb.yml --debug`

**nni Environment**:
- nni version: 0.7
- nni mode(local|pai|remote): local
- OS: ubuntu
- python version: 3.5
- is running in docker?: yes (based on `tensorflow/tensorflow:2.0.0a0-gpu-py3`)

**How to fix it**:

- Downgrade scipy  [Statsmodels 0.9/Scipy 1.3.0 incompatibility](https://github.com/statsmodels/statsmodels/issues/5759) to 1.2.1 for example
- `nnictl` Error handler ?

**Comment by Crysple** [comment]
It seems that the current version of `statsmodel` (v0.9) installed by nni is incompatible with scipy(v1.1 or v1.3).
There is an [issue](https://github.com/statsmodels/statsmodels/issues/5759) pointing out this.
Ner version of statsmodel(v1.0) is ready but not released. So currently you could choose to upgrade it from github by `python3 -m pip install --upgrade git+https://github.com/statsmodels/statsmodels`. Or you could upgrade `scipy` to 1.2 if you prefer.

**Comment by xuehui1991** [comment]
@Crysple  Seems I met the same problem before.

**Comment by QuanluZhang** [comment]
@VincentMatthys Thanks a lot for reporting this issue and providing the solution. We will keep this issue opened until `statsmodel` releases its new version.
