### ISSUE TITLE
loguniform with negative lower bound causes error

### ISSUE THREAD

**Issue by FerusAndBeyond** [microsoft/nni#1135]
I'm trying to use nni with lightgbm and when setting ```lambda_l1``` or ```lambda_l2``` with loguniform it crashes when the lower bound is set below 0.  Here is the json:
```
     ...
"lambda_l1": {
        "_type": "loguniform",
        "_value": [-3, 1]
    },
    ...
```

Setting ``` "_value": [2, 5]```makes it work but for negative values it doesn't for some reason.

Here is the dispatcher log:

```
Traceback (most recent call last):
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/nni/msg_dispatcher_base.py", line 102, in command_queue_worker
    self.process_command(command, data)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/nni/msg_dispatcher_base.py", line 160, in process_command
    command_handlers[command](data)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/nni/msg_dispatcher.py", line 101, in handle_request_trial_jobs
    params_list = self.tuner.generate_multiple_parameters(ids)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/nni/tuner.py", line 52, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/nni/hyperopt_tuner/hyperopt_tuner.py", line 256, in generate_parameters
    total_params = self.get_suggestion(random_search=False)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/nni/hyperopt_tuner/hyperopt_tuner.py", line 375, in get_suggestion
    new_trials = algorithm(new_ids, rval.domain, trials, random_state)
  File "/usr/local/lib/python3.7/site-packages/hyperopt/tpe.py", line 870, in suggest
    return rand.suggest(new_ids, domain, trials, seed)
  File "/usr/local/lib/python3.7/site-packages/hyperopt/rand.py", line 24, in suggest
    domain.s_rng: rng,
  File "/usr/local/lib/python3.7/site-packages/hyperopt/pyll/base.py", line 913, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hyperopt/pyll/stochastic.py", line 44, in loguniform
    draw = rng.uniform(low, high, size=size)
  File "mtrand.pyx", line 1307, in mtrand.RandomState.uniform
```

When looking at the input arguments to rng.uniform I get low=nan and high=0.0

**Comment by xuehui1991** [comment]
Hello @FerusAndBeyond.  The loguniform definition is [here](https://github.com/microsoft/nni/blob/master/docs/en_US/SearchSpaceSpec.md).

You could see a vairiable in "loguniform" distribution means "the variable value is a value drawn from a range [low, high] according to a loguniform distribution like exp(uniform(log(low), log(high)))".
The log function doesn't support negative input, so as the "loguniform".

**Comment by FerusAndBeyond** [comment]
@xuehui1991 You're right, thanks. I read it from this [page](https://github.com/Microsoft/nni/wiki/How-to-Define-Search-Space) where it says differently: "Which means the variable value is a value drawn according to exp(uniform(low, high)) so that the logarithm of the return value is uniformly distributed". Those two pages should be synced.

**Comment by xuehui1991** [comment]
@FerusAndBeyond  Thank you for your suggestion. We may need to update our wiki recently~
