### ISSUE TITLE
Using TPE tuning, the NNI will report an error in the 21st parameter.

### ISSUE THREAD

**Issue by LongzeSong** [microsoft/nni#1496]
**Short summary about the issue/question**:
Using TPE tuning, the NNI will report an error in the 21st parameter.

When my Tuner is set to TPE and the searchable parameters include the uniform type, the program will report an error when searching for the 21st Trial.

The follow is dispatcher.log 

> [08/26/2019, 04:23:34 PM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.006593 seconds
[08/26/2019, 04:23:34 PM] INFO (hyperopt.tpe/Thread-1) TPE using 20/20 trials with best loss 164.972519
[08/26/2019, 04:23:34 PM] ERROR (nni.msg_dispatcher_base/Thread-1) 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/nni/msg_dispatcher_base.py", line 102, in command_queue_worker
    self.process_command(command, data)
  File "/opt/conda/lib/python3.7/site-packages/nni/msg_dispatcher_base.py", line 160, in process_command
    command_handlers[command](data)
  File "/opt/conda/lib/python3.7/site-packages/nni/msg_dispatcher.py", line 106, in handle_request_trial_jobs
    params_list = self.tuner.generate_multiple_parameters(ids)
  File "/opt/conda/lib/python3.7/site-packages/nni/tuner.py", line 52, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/nni/hyperopt_tuner/hyperopt_tuner.py", line 263, in generate_parameters
    total_params = self.get_suggestion(random_search=False)
  File "/opt/conda/lib/python3.7/site-packages/nni/hyperopt_tuner/hyperopt_tuner.py", line 389, in get_suggestion
    new_trials = algorithm(new_ids, rval.domain, trials, random_state)
  File "/opt/conda/lib/python3.7/site-packages/hyperopt/tpe.py", line 900, in suggest
    print_node_on_error=False)
  File "/opt/conda/lib/python3.7/site-packages/hyperopt/pyll/base.py", line 913, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/hyperopt/tpe.py", line 465, in adaptive_parzen_normal
    assert prior_sigma > 0
AssertionError
[08/26/2019, 04:23:37 PM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...
[08/26/2019, 04:23:37 PM] INFO (nni.msg_dispatcher_base/MainThread) Terminated by NNI manager

**nni Environment**: 
- nni version: 0.9.1.1
- nni mode(local|pai|remote): local
- OS: ubuntu18.04
- python version: Python 3.7.3  Anaconda, Inc. on linux
- is conda or virtualenv used?: No 
- is running in docker?: Yes

**Anything else we need to know**:
I did some comparison tests and found that this problem does not occur when Tuner is set to Random, or does not occur when the search parameter type is set to choice. This problem only occurs when Tuner is TPE and the search parameter type is uniform.

I want to konw how to fix it or advoid it.
Thanks.

**Comment by xuehui1991** [comment]
Hello @LongzeSong. Could you post your trial code,  search_space.json, config.yml and the dispatcher.log here? For now, we don't have enough information to guess the reason.

**Comment by LongzeSong** [comment]
The original code is relatively long, so I put a test code that will show the error I described in my current environment.

**trial code**
```python
import nni

params = nni.get_next_parameter()
lr = params['learning_rate']
nni.report_final_result(lr)
```
**search_space.json**
```json
{
  "learning_rate": {"_type":"uniform","_value":[1e-3,1e-5]}
}
```
**config.yml**
```yaml
authorName: SongLongze
experimentName: test
trialConcurrency: 1
maxExecDuration: 19h
logDir: /workdir/TAXIOrderDecision/saved/nni/experiment

trainingServicePlatform: local

searchSpacePath: nni_search_space.json
useAnnotation: false
# Tuner
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: minimize

trial:
  command: python3 nni_train_test.py
  codeDir: ../
  gpuNum: 1
```

**dispatcher.log**
```
[08/27/2019, 10:47:36 AM] INFO (hyperopt.utils/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[08/27/2019, 10:47:36 AM] INFO (hyperopt.fmin/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[08/27/2019, 10:47:36 AM] INFO (nni.msg_dispatcher_base/MainThread) Start dispatcher
[08/27/2019, 10:47:36 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000696 seconds
[08/27/2019, 10:47:36 AM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[08/27/2019, 10:47:51 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000692 seconds
[08/27/2019, 10:47:51 AM] INFO (hyperopt.tpe/Thread-1) TPE using 1/1 trials with best loss 0.000839
[08/27/2019, 10:48:01 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002162 seconds
[08/27/2019, 10:48:01 AM] INFO (hyperopt.tpe/Thread-1) TPE using 2/2 trials with best loss 0.000180
[08/27/2019, 10:48:11 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002201 seconds
[08/27/2019, 10:48:11 AM] INFO (hyperopt.tpe/Thread-1) TPE using 3/3 trials with best loss 0.000180
[08/27/2019, 10:48:22 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002188 seconds
[08/27/2019, 10:48:22 AM] INFO (hyperopt.tpe/Thread-1) TPE using 4/4 trials with best loss 0.000180
[08/27/2019, 10:48:32 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002200 seconds
[08/27/2019, 10:48:32 AM] INFO (hyperopt.tpe/Thread-1) TPE using 5/5 trials with best loss 0.000180
[08/27/2019, 10:48:42 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002092 seconds
[08/27/2019, 10:48:42 AM] INFO (hyperopt.tpe/Thread-1) TPE using 6/6 trials with best loss 0.000180
[08/27/2019, 10:48:53 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002200 seconds
[08/27/2019, 10:48:53 AM] INFO (hyperopt.tpe/Thread-1) TPE using 7/7 trials with best loss 0.000180
[08/27/2019, 10:49:04 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002169 seconds
[08/27/2019, 10:49:04 AM] INFO (hyperopt.tpe/Thread-1) TPE using 8/8 trials with best loss 0.000180
[08/27/2019, 10:49:14 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002205 seconds
[08/27/2019, 10:49:14 AM] INFO (hyperopt.tpe/Thread-1) TPE using 9/9 trials with best loss 0.000180
[08/27/2019, 10:49:24 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002164 seconds
[08/27/2019, 10:49:24 AM] INFO (hyperopt.tpe/Thread-1) TPE using 10/10 trials with best loss 0.000180
[08/27/2019, 10:49:35 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000413 seconds
[08/27/2019, 10:49:35 AM] INFO (hyperopt.tpe/Thread-1) TPE using 11/11 trials with best loss 0.000056
[08/27/2019, 10:49:45 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002845 seconds
[08/27/2019, 10:49:45 AM] INFO (hyperopt.tpe/Thread-1) TPE using 12/12 trials with best loss 0.000056
[08/27/2019, 10:49:55 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002781 seconds
[08/27/2019, 10:49:55 AM] INFO (hyperopt.tpe/Thread-1) TPE using 13/13 trials with best loss 0.000056
[08/27/2019, 10:50:06 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002224 seconds
[08/27/2019, 10:50:06 AM] INFO (hyperopt.tpe/Thread-1) TPE using 14/14 trials with best loss 0.000056
[08/27/2019, 10:50:16 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002263 seconds
[08/27/2019, 10:50:16 AM] INFO (hyperopt.tpe/Thread-1) TPE using 15/15 trials with best loss 0.000056
[08/27/2019, 10:50:27 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002236 seconds
[08/27/2019, 10:50:27 AM] INFO (hyperopt.tpe/Thread-1) TPE using 16/16 trials with best loss 0.000056
[08/27/2019, 10:50:37 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002186 seconds
[08/27/2019, 10:50:37 AM] INFO (hyperopt.tpe/Thread-1) TPE using 17/17 trials with best loss 0.000056
[08/27/2019, 10:50:47 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000537 seconds
[08/27/2019, 10:50:47 AM] INFO (hyperopt.tpe/Thread-1) TPE using 18/18 trials with best loss 0.000056
[08/27/2019, 10:50:58 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001626 seconds
[08/27/2019, 10:50:58 AM] INFO (hyperopt.tpe/Thread-1) TPE using 19/19 trials with best loss 0.000056
[08/27/2019, 10:51:08 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002944 seconds
[08/27/2019, 10:51:08 AM] INFO (hyperopt.tpe/Thread-1) TPE using 20/20 trials with best loss 0.000056
[08/27/2019, 10:51:08 AM] ERROR (nni.msg_dispatcher_base/Thread-1) 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/nni/msg_dispatcher_base.py", line 102, in command_queue_worker
    self.process_command(command, data)
  File "/opt/conda/lib/python3.7/site-packages/nni/msg_dispatcher_base.py", line 160, in process_command
    command_handlers[command](data)
  File "/opt/conda/lib/python3.7/site-packages/nni/msg_dispatcher.py", line 106, in handle_request_trial_jobs
    params_list = self.tuner.generate_multiple_parameters(ids)
  File "/opt/conda/lib/python3.7/site-packages/nni/tuner.py", line 52, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/nni/hyperopt_tuner/hyperopt_tuner.py", line 263, in generate_parameters
    total_params = self.get_suggestion(random_search=False)
  File "/opt/conda/lib/python3.7/site-packages/nni/hyperopt_tuner/hyperopt_tuner.py", line 389, in get_suggestion
    new_trials = algorithm(new_ids, rval.domain, trials, random_state)
  File "/opt/conda/lib/python3.7/site-packages/hyperopt/tpe.py", line 900, in suggest
    print_node_on_error=False)
  File "/opt/conda/lib/python3.7/site-packages/hyperopt/pyll/base.py", line 913, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/hyperopt/tpe.py", line 465, in adaptive_parzen_normal
    assert prior_sigma > 0
AssertionError
[08/27/2019, 10:51:10 AM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...
[08/27/2019, 10:51:11 AM] INFO (nni.msg_dispatcher_base/MainThread) Terminated by NNI manager
```

Thank you~

**Comment by scarlett2018** [comment]
@LongzeSong @xuehui1991 - you guys can have quick IM chat in the nni gitter channel as well: https://gitter.im/Microsoft/nni

**Comment by leelaylay** [comment]
@LongzeSong I check your config and find there is one mistake. According to [SearchSpaceSpec.md](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/SearchSpaceSpec.md), the range in `uniform` should be `[low, high]` instead of  `[high, low]`.
**search_space.json**
```diff
{
-  "learning_rate": {"_type":"uniform","_value":[1e-3,1e-5]}
+  "learning_rate": {"_type":"uniform","_value":[1e-5,1e-3]}
}
```

Hope this might help you.

**Comment by xuehui1991** [comment]
I think we should add some component to validate the search space here. The error will confuse users.

**Comment by LongzeSong** [comment]
@leelaylay  Thank you very much,I am too careless.

**Comment by scarlett2018** [comment]
Closing the issue as user's problem had resolved. created #1511 to track the validation effort proposed by @xuehui1991.
