### ISSUE TITLE
example mnist-pytorch fails

### ISSUE THREAD

**Issue by chicm-ms** [microsoft/nni#1595]
example mnist-pytorch failed with following errors:
config file: https://github.com/microsoft/nni/blob/master/test/config_test/examples/mnist-pytorch.test.yml

```
Traceback (most recent call last):
  File "mnist.py", line 157, in <module>
    main(params)
  File "mnist.py", line 91, in main
    transforms.Normalize((0.1307,), (0.3081,))
  File "/home/chec/anaconda3/envs/nni/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 46, in __init__
    self.download()
  File "/home/chec/anaconda3/envs/nni/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 120, in download
    gzip.GzipFile(file_path) as zip_f:
  File "/home/chec/anaconda3/envs/nni/lib/python3.7/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tensorflow/mnist/input_data/raw/train-images-idx3-ubyte.gz'
```

Then change maxTrialNum from 4 to 2, trialConcurrency from 2 to 1, got following errors:

```
Traceback (most recent call last):
  File "mnist.py", line 157, in <module>
    main(params)
  File "mnist.py", line 91, in main
    transforms.Normalize((0.1307,), (0.3081,))
  File "/home/chec/anaconda3/envs/nni/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 46, in __init__
    self.download()
  File "/home/chec/anaconda3/envs/nni/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 128, in download
    read_image_file(os.path.join(self.root, self.raw_folder, 'train-images-idx3-ubyte')),
  File "/home/chec/anaconda3/envs/nni/lib/python3.7/site-packages/torchvision/datasets/mnist.py", line 299, in read_image_file
    return torch.from_numpy(parsed).view(length, num_rows, num_cols)
RuntimeError: PyTorch was compiled without NumPy support
```

**Comment by chicm-ms** [comment]
Manully upgrade pytorch from 0.4.1 to 1.2.0,  second problem solved.

**Comment by chicm-ms** [comment]
problem fixed.
