### ISSUE TITLE
ERROR: HTTPConnectionPool(host='localhost', port=8080): Read timed out. (read timeout=20)

### ISSUE THREAD

**Issue by apatsekin** [microsoft/nni#1658]
**Short summary about the issue/question**: Trying to resume experiment which failed due to out-of-disk-space error. Please see log attached.

**Brief what process you are following**: Running remote experiment. Start experiment on one machine, which uses 2 other worker machines.

**How to reproduce it**: nni daemon that controls remote experiment should run into out-of-disk-space error. Than try to resume same experiment.

**nni Environment**:
nni version: 1.0 (Upgrade to 1.1 didn't solve the problem)
nni mode(local|pai|remote): remote
OS: Ubuntu 16.04.6 LTS
python version: 3.6.8
is conda or virtualenv used?: no
is running in docker?: yes

**need to update document(yes/no)**:

**Anything else we need to know**:

Log:
```
root@gpu2-ru7 /# nnictl resume cJd6Fzn0 --port 8085
INFO: resume experiment cJd6Fzn0...
INFO: Starting restful server...
INFO: Successfully started Restful server!
INFO: Setting remote config...
INFO: Successfully set remote config!
INFO: Starting experiment...
ERROR: HTTPConnectionPool(host='localhost', port=8085): Read timed out. (read timeout=20)
ERROR: Start experiment failed!
INFO:  Stdout:
-----------------------------------------------------------------------
                Experiment start time 2019-10-28 20:27:20
-----------------------------------------------------------------------




INFO:  Stderr:
-----------------------------------------------------------------------
                Experiment start time 2019-10-28 20:27:20
-----------------------------------------------------------------------
(node:18680) ExperimentalWarning: The fs.promises API is experimental
(node:18680) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at AnonymousObserver.disposable.timer.subscribe [as _onNext] (/root/.pyenv/versions/3.6.8/nni/training_service/remote_machine/remoteMachineTrainingService.js:315:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18680) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at AnonymousObserver.disposable.timer.subscribe [as _onNext] (/root/.pyenv/versions/3.6.8/nni/training_service/remote_machine/remoteMachineTrainingService.js:315:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18680) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at AnonymousObserver.disposable.timer.subscribe [as _onNext] (/root/.pyenv/versions/3.6.8/nni/training_service/remote_machine/remoteMachineTrainingService.js:315:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:18680) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at AnonymousObserver.disposable.timer.subscribe [as _onNext] (/root/.pyenv/versions/3.6.8/nni/training_service/remote_machine/remoteMachineTrainingService.js:315:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

nnimanager.log:
```
[10/28/2019, 8:54:31 PM] INFO [ 'Resuming experiment: cJd6Fzn0' ]
[10/28/2019, 8:54:32 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:32 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:33 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:33 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:41 PM] DEBUG [ 'dispatcher command: python3 -m nni --tuner_class_name TPE --tuner_args "{\\"optimize_mode\\":\\"minimize\\"}" --assessor_class_name Medianstop --assessor_args "{\\"optimize_mode\\":\\"minimize\\",\\"start_step\\":1}"' ]
[10/28/2019, 8:54:41 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:41 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:41 PM] DEBUG [ 'getTrialJobsByReplayEvents begin' ]
[10/28/2019, 8:54:41 PM] DEBUG [ 'getTrialJobsByReplayEvents done' ]
[10/28/2019, 8:54:42 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:42 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:43 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:43 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:51 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:51 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:51 PM] DEBUG [ 'getTrialJobsByReplayEvents begin' ]
[10/28/2019, 8:54:51 PM] DEBUG [ 'getTrialJobsByReplayEvents done' ]
[10/28/2019, 8:54:51 PM] INFO [ 'Change NNIManager status from: INITIALIZED to: STOPPING' ]
[10/28/2019, 8:54:51 PM] DEBUG [ 'ipcInterface command type: [TE], content:[]' ]
[10/28/2019, 8:54:51 PM] INFO [ 'Stopping experiment, cleaning up ...' ]
[10/28/2019, 8:54:52 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:52 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:53 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:53 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:54:53 PM] INFO [ 'Stopping remote machine training service...' ]
[10/28/2019, 8:54:53 PM] DEBUG [ 'remoteExeCommand: command: [pkill -P `cat /tmp/root/nni/scripts/pid`]' ]
[10/28/2019, 8:54:53 PM] DEBUG [ 'remoteExeCommand: command: [rm -rf /tmp/root/nni/scripts]' ]
[10/28/2019, 8:54:53 PM] DEBUG [ 'remoteExeCommand: command: [pkill -P `cat /tmp/root/nni/scripts/pid`]' ]
[10/28/2019, 8:54:53 PM] DEBUG [ 'remoteExeCommand: command: [rm -rf /tmp/root/nni/scripts]' ]
[10/28/2019, 8:55:01 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:55:01 PM] DEBUG [ 'remoteExeCommand: command: [tail -n 1 /tmp/root/nni/scripts/gpu_metrics]' ]
[10/28/2019, 8:55:01 PM] INFO [ 'Change NNIManager status from: STOPPING to: STOPPED' ]
[10/28/2019, 8:55:01 PM] DEBUG [ 'ipcInterface command type: [IN], content:[tuner params here ]
[10/28/2019, 8:55:01 PM] INFO [ 'Experiment stopped.' ]
[10/28/2019, 8:55:01 PM] INFO [ 'Change NNIManager status from: STOPPED to: RUNNING' ]
[10/28/2019, 8:55:01 PM] INFO [ 'Add event listeners' ]
[10/28/2019, 8:55:01 PM] DEBUG [ 'Send tuner command: INITIALIZE: {[tuner params here]}
[10/28/2019, 8:55:01 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/root/.pyenv/versions/3.6.8/nni/core/ipcInterface.js:47:38)\n    at NNIManager.sendInitTunerCommands (/root/.pyenv/versions/3.6.8/nni/core/nnimanager.js:515:25)\n    at NNIManager.run (/root/.pyenv/versions/3.6.8/nni/core/nnimanager.js:484:14)\n    at NNIManager.resumeExperiment (/root/.pyenv/versions/3.6.8/nni/core/nnimanager.js:155:14)' ]
[10/28/2019, 8:55:01 PM] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]
```

**Comment by chicm-ms** [comment]
@apatsekin   Hi, would you please attach the dispatcher.log and nnimanager.log under `~/nni/experiments/cJd6Fzn0/log` ?

**Comment by SparkSnail** [comment]
Hi @apatsekin , how do you know that this is a `out-of-disk-space error`, I didn't find related information in the log content. If you clean up your disk and release some space, will this issue be resolved?

**Comment by apatsekin** [comment]
@SparkSnail out-of-disk happened on that machine because of causes not related to NNI. But I saw it in `stderr`. Unfortunately I don't have dump of stderr after initial crash. The whole case probably is not super common thing. However, it would be great to know ways of recovering from this situation: you have a folder with experiment, you try to restore it, and get this HttpTimeout error.

**Comment by SparkSnail** [comment]
@apatsekin Do you mean that NNI should provide more meaningful error information when restarting an experiment? This is a good suggestion, we will give some time to investigate the case and give some improvement for NNI according to your advice, thanks.

**Comment by scarlett2018** [comment]
Closing the issue as it has no updates for 8 months, @apatsekin - feel free to reopen the issue if it is still a problem on your side.

**Comment by youngzi1004** [comment]
I have met the same problem. It happens when the code tar file is too large. log:[8/20/2020, 3:01:42 PM] DEBUG [ 'copyFileToRemote(5992): localFilePath: /tmp/nni_tmp_local_FAwcf.tar.gz, remoteFilePath: /tmp/nni_tmp_remote_FAwcf.tar.gz' ]
I solved it by reducing file, but how to increase the request_time ??

**Comment by lukelu312** [comment]
+1 got the same issue..hope to hear your expertise.

nnimanger shows:

[2023-07-06 15:04:44] INFO (NNIManager) Trial job Tl9tk status changed from WAITING to RUNNING
[2023-07-06 15:12:40] INFO (ShutdownManager) Initiate shutdown: REST request
[2023-07-06 15:12:40] INFO (RestServer) Stopping REST server.
[2023-07-06 15:12:40] INFO (NNIManager) Change NNIManager status from: RUNNING to: STOPPING
[2023-07-06 15:12:40] INFO (NNIManager) Stopping experiment, cleaning up ...
[2023-07-06 15:12:43] INFO (RestServer) REST server stopped.
