### ISSUE TITLE
EvolutionTuner fails when population size is less than concurrency

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#1666]
Reproducible with `population_size=20` and `concurrency=50`.

**Comment by xuehui1991** [comment]
```population_size``` should be larger than ```concurrency``` based on the understanding of evolution algorithm.

**Comment by ultmaster** [comment]
@xuehui1991 So won't fix? Should we put a note in our documentation?

**Comment by xuehui1991** [comment]
I don't think we should fix it because it's not a bug.   We could mention it in the docs.

**Comment by ultmaster** [comment]
The failure message under my tests.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/zhangyuge/projects/nni/src/sdk/pynni/tests/test_tuner.py", line 162, in test_evolution
    self.search_space_test_all(lambda: EvolutionTuner(population_size=10))
  File "/home/zhangyuge/projects/nni/src/sdk/pynni/tests/test_tuner.py", line 127, in search_space_test_all
    self.search_space_test_one(tuner_factory, single_search_space)
  File "/home/zhangyuge/projects/nni/src/sdk/pynni/tests/test_tuner.py", line 59, in search_space_test_one
    parameters = tuner.generate_multiple_parameters(list(range(0, 50)))
  File "/home/zhangyuge/projects/nni/build/nni/tuner.py", line 51, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id, **kwargs)
  File "/home/zhangyuge/projects/nni/build/nni/evolution_tuner/evolution_tuner.py", line 204, in generate_parameters
    raise RuntimeError('The population is empty')
RuntimeError: The population is empty
```

Also had an integrated example, in case you question my tests:

```
[10/30/2019, 05:00:37 PM] ERROR (nni.msg_dispatcher_base/Thread-1) The population is empty
Traceback (most recent call last):
  File "/home/zhangyuge/projects/nni/build/nni/msg_dispatcher_base.py", line 108, in command_queue_worker
    self.process_command(command, data)
  File "/home/zhangyuge/projects/nni/build/nni/msg_dispatcher_base.py", line 167, in process_command
    command_handlers[command](data)
  File "/home/zhangyuge/projects/nni/build/nni/msg_dispatcher.py", line 118, in handle_request_trial_jobs
    params_list = self.tuner.generate_multiple_parameters(ids, st_callback=self.send_trial_callback)
  File "/home/zhangyuge/projects/nni/build/nni/tuner.py", line 51, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id, **kwargs)
  File "/home/zhangyuge/projects/nni/build/nni/evolution_tuner/evolution_tuner.py", line 204, in generate_parameters
    raise RuntimeError('The population is empty')
RuntimeError: The population is empty
[10/30/2019, 05:00:42 PM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...
[10/30/2019, 05:00:43 PM] INFO (nni.msg_dispatcher_base/MainThread) Terminated by NNI manager
```
