### ISSUE TITLE
Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by martsalz** [microsoft/nni#1747]
**Short summary about the issue/question**:

The following error message appears during execution of NNI:

"Error: This socket has been ended by the other party"

The status then changes from RUNNING to ERROR. Why does this message appear "sporadically"?

**nni Environment**:
- nni version: 1.1
- nni mode(local|pai|remote): local
- OS: CentOS 7
- python version: python 3.6
- is conda or virtualenv used?: virtualenv 
- is running in docker?: no

**Anything else we need to know**:

nnimanager.log:

`[11/18/2019, 4:43:14 PM] INFO [ 'Datastore initialization done' ]
[11/18/2019, 4:43:14 PM] INFO [ 'Rest server listening on: http://0.0.0.0:8081' ]
[11/18/2019, 4:43:14 PM] INFO [ 'RestServer start' ]
[11/18/2019, 4:43:14 PM] INFO [ 'Construct local machine training service.' ]
[11/18/2019, 4:43:14 PM] INFO [ 'RestServer base port is 8081' ]
[11/18/2019, 4:43:15 PM] INFO [ 'NNIManager setClusterMetadata, key: local_config, value: {"useActiveGpu":true,"maxTrialNumPerGpu":3}' ]
[11/18/2019, 4:43:15 PM] INFO [ 'Specified GPU indices: undefined' ]
[11/18/2019, 4:43:15 PM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python3 test.py","codeDir":"/home/msalz/nni/examples/trials/mnist-keras-experimente/.","gpuNum":1}' ]
[11/18/2019, 4:43:15 PM] INFO [ 'required GPU number is 1' ]
[11/18/2019, 4:43:15 PM] INFO [ 'Starting experiment: sGuLTkfC' ]
[11/18/2019, 4:43:15 PM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[11/18/2019, 4:43:15 PM] INFO [ 'Add event listeners' ]
[11/18/2019, 4:43:15 PM] INFO [ 'Run local machine training service.' ]
[11/18/2019, 4:43:17 PM] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[11/18/2019, 4:43:17 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"recurrent_dropout": 0.263399687465929, "learning_rate": 0.1, "dropout": 0.7284442058681319, "n_neurons": 119, "units_D_1": 780, "units_D_2": 840}, "parameter_index": 0}' ]
[11/18/2019, 4:43:17 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"recurrent_dropout": 0.8266361080090527, "learning_rate": 0.01, "dropout": 0.5650023320203775, "n_neurons": 124, "units_D_1": 82, "units_D_2": 911}, "parameter_index": 0}' ]
[11/18/2019, 4:43:17 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 2, "parameter_source": "algorithm", "parameters": {"recurrent_dropout": 0.4569633218370608, "learning_rate": 0.1, "dropout": 0.3643484522644743, "n_neurons": 177, "units_D_1": 643, "units_D_2": 214}, "parameter_index": 0}' ]
[11/18/2019, 4:43:17 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 3, "parameter_source": "algorithm", "parameters": {"recurrent_dropout": 0.24121762572213587, "learning_rate": 0.001, "dropout": 0.4089268956129042, "n_neurons": 83, "units_D_1": 26, "units_D_2": 730}, "parameter_index": 0}' ]
[11/18/2019, 4:43:17 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 4, "parameter_source": "algorithm", "parameters": {"recurrent_dropout": 0.8049852612882534, "learning_rate": 0.1, "dropout": 0.11530082535638764, "n_neurons": 153, "units_D_1": 43, "units_D_2": 137}, "parameter_index": 0}' ]
[11/18/2019, 4:43:20 PM] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"recurrent_dropout\\": 0.263399687465929, \\"learning_rate\\": 0.1, \\"dropout\\": 0.7284442058681319, \\"n_neurons\\": 119, \\"units_D_1\\": 780, \\"units_D_2\\": 840}, \\"parameter_index\\": 0}","index":0}}' ]
[11/18/2019, 4:43:20 PM] INFO [ 'submitTrialJob: form: {"sequenceId":1,"hyperParameters":{"value":"{\\"parameter_id\\": 1, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"recurrent_dropout\\": 0.8266361080090527, \\"learning_rate\\": 0.01, \\"dropout\\": 0.5650023320203775, \\"n_neurons\\": 124, \\"units_D_1\\": 82, \\"units_D_2\\": 911}, \\"parameter_index\\": 0}","index":0}}' ]
[11/18/2019, 4:43:20 PM] INFO [ 'submitTrialJob: form: {"sequenceId":2,"hyperParameters":{"value":"{\\"parameter_id\\": 2, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"recurrent_dropout\\": 0.4569633218370608, \\"learning_rate\\": 0.1, \\"dropout\\": 0.3643484522644743, \\"n_neurons\\": 177, \\"units_D_1\\": 643, \\"units_D_2\\": 214}, \\"parameter_index\\": 0}","index":0}}' ]
[11/18/2019, 4:43:20 PM] INFO [ 'submitTrialJob: form: {"sequenceId":3,"hyperParameters":{"value":"{\\"parameter_id\\": 3, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"recurrent_dropout\\": 0.24121762572213587, \\"learning_rate\\": 0.001, \\"dropout\\": 0.4089268956129042, \\"n_neurons\\": 83, \\"units_D_1\\": 26, \\"units_D_2\\": 730}, \\"parameter_index\\": 0}","index":0}}' ]
[11/18/2019, 4:43:20 PM] INFO [ 'submitTrialJob: form: {"sequenceId":4,"hyperParameters":{"value":"{\\"parameter_id\\": 4, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"recurrent_dropout\\": 0.8049852612882534, \\"learning_rate\\": 0.1, \\"dropout\\": 0.11530082535638764, \\"n_neurons\\": 153, \\"units_D_1\\": 43, \\"units_D_2\\": 137}, \\"parameter_index\\": 0}","index":0}}' ]
[11/18/2019, 4:43:25 PM] INFO [ 'Trial job ucehw status changed from WAITING to RUNNING' ]
[11/18/2019, 4:43:30 PM] INFO [ 'Trial job wnFTF status changed from WAITING to RUNNING' ]
[11/18/2019, 4:43:30 PM] INFO [ 'Trial job EI0Rc status changed from WAITING to RUNNING' ]
[11/18/2019, 4:43:31 PM] INFO [ 'Trial job zt32v status changed from WAITING to RUNNING' ]
[11/18/2019, 4:43:31 PM] INFO [ 'Trial job bQlKq status changed from WAITING to RUNNING' ]
[11/18/2019, 5:41:23 PM] INFO [ 'Trial job EI0Rc status changed from RUNNING to SUCCEEDED' ]
[11/18/2019, 5:41:32 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.pingDispatcher (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:341:29)' ]
[11/18/2019, 5:41:32 PM] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]
[11/18/2019, 5:41:37 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:42:41 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:43:12 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:43:16 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:43:44 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:44:48 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:45:19 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:45:23 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:45:52 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:46:54 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:47:26 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:47:31 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:48:02 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:49:01 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:49:34 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:49:38 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:49:53 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:50:03 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:50:44 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:51:11 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:51:39 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:52:18 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:52:47 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:53:19 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:53:30 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:53:47 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:54:08 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:54:16 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:54:35 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:55:07 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:55:42 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:56:17 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:56:52 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:57:27 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
[11/18/2019, 5:57:29 PM] ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/msalz/venv_nni_dev/nni/core/ipcInterface.js:47:38)\n    at NNIManager.onTrialJobMetrics (/home/msalz/venv_nni_dev/nni/core/nnimanager.js:523:25)' ]
`

**Comment by chicm-ms** [comment]
Looks like this was caused by dispatcher error,  would you please paste dispatcher.log and the config yml file?

**Comment by martsalz** [comment]
dispatcher.log:

`[11/18/2019, 04:43:17 PM] INFO (hyperopt.utils/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[11/18/2019, 04:43:17 PM] INFO (hyperopt.fmin/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[11/18/2019, 04:43:17 PM] INFO (nni.msg_dispatcher_base/MainThread) Start dispatcher
[11/18/2019, 05:41:23 PM] ERROR (nni.msg_dispatcher_base/Thread-1) sum(pvals[:-1]) > 1.0
Traceback (most recent call last):
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/nni/msg_dispatcher_base.py", line 108, in command_queue_worker
    self.process_command(command, data)
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/nni/msg_dispatcher_base.py", line 167, in process_command
    command_handlers[command](data)
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/nni/msg_dispatcher.py", line 118, in handle_request_trial_jobs
    params_list = self.tuner.generate_multiple_parameters(ids, st_callback=self.send_trial_callback)
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/nni/tuner.py", line 51, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id, **kwargs)
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/nni/hyperopt_tuner/hyperopt_tuner.py", line 284, in generate_parameters
    total_params = self.get_suggestion(random_search=False)
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/nni/hyperopt_tuner/hyperopt_tuner.py", line 460, in get_suggestion
    new_trials = algorithm(new_ids, rval.domain, trials, random_state)
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/hyperopt/anneal.py", line 410, in suggest
    return AnnealingAlgo(domain, trials, seed, *args, **kwargs)(new_id)
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/hyperopt/algobase.py", line 239, in __call__
    self.domain.s_rng: self.rng,
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/hyperopt/algobase.py", line 112, in eval_nodes
    rval = self.on_node(memo, node)
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/hyperopt/algobase.py", line 255, in on_node
    return self.on_node_hyperparameter(memo, node, label)
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/hyperopt/anneal.py", line 224, in on_node_hyperparameter
    return handler(memo, node, label, tid, val)
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/hyperopt/anneal.py", line 327, in hp_randint
    size=memo[node.arg['size']])
  File "/home/msalz/venv_nni_dev/lib/python3.6/site-packages/hyperopt/pyll/stochastic.py", line 132, in categorical
    sample = rng.multinomial(n=1, pvals=p, size=int(n_draws))
  File "mtrand.pyx", line 4643, in mtrand.RandomState.multinomial
ValueError: sum(pvals[:-1]) > 1.0
[11/18/2019, 05:41:27 PM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...
[11/18/2019, 05:41:29 PM] INFO (nni.msg_dispatcher_base/MainThread) Terminated by NNI manager
`

config.yml:

> authorName: default
> experimentName: example_mnist
> maxExecDuration: 2h
> maxTrialNum: 10000
> trialConcurrency: 5
> localConfig:
>     useActiveGpu: true
>     maxTrialNumPerGpu: 3
> #choice: local, remote, pai
> trainingServicePlatform: local
> searchSpacePath: search_space.json
> #choice: true, false
> useAnnotation: false
> tuner:
>   builtinTunerName: Anneal
>   classArgs:
>     optimize_mode: minimize
> trial:
>   command: python3 test.py
>   codeDir: .
>   gpuNum: 1

**Comment by chicm-ms** [comment]
what is the version of the hyperopt in your environment?   can this problem be reproduced?  I can not reproduce this problem with nni 1.1

**Comment by martsalz** [comment]
OK, if you don't get the error message without hyperopt, I'll try it as well. Which numpy version do you have?

numpy==1.16.4
hyperopt==0.1.2

**Comment by chicm-ms** [comment]
My numpy version is 1.17.2,   I can not reproduce this problem on both hyperopt 0.1.2  and 0.2.2.
The error stack  is in numpy and hyperopt

**Comment by Markus92** [comment]
Are you using default search space?

We’ve gotten this error message when search space is set invalid (for example, switch min/max in loguniform]. It doesn’t tend to fail right away so, but only after some iterations.

**Comment by leckie-chn** [comment]
@martsalz - any feedback on @chicm-ms and @Markus92 's suggestions? has the problem been addressed somehow? thanks.

**Comment by chicm-ms** [comment]
@martsalz Closing since no response.  You can reopen this issue if you still have the problem.
