### ISSUE TITLE
Error: This socket has been ended by the other party\n at Socket.writeAfterFin

### ISSUE THREAD

**Issue by vivounicorn** [microsoft/nni#1870]
Hi, I met the issue when i using nni framework, error message as following:

# 1、nnimanager.log

[2019-12-23 15:26:21] INFO [ 'Datastore initialization done' ]
[2019-12-23 15:26:21] INFO [ 'RestServer start' ]
[2019-12-23 15:26:21] INFO [ 'Construct local machine training service.' ]
[2019-12-23 15:26:21] INFO [ 'RestServer base port is 8080' ]
[2019-12-23 15:26:21] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[2019-12-23 15:26:23] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python3 main.py","codeDir":"/home/liyiran/PycharmProjects/DeepRisk/feature_engineering/auto_feature_engineering/test_large/.","gpuNum":0}' ]
[2019-12-23 15:26:23] INFO [ 'required GPU number is 0' ]
[2019-12-23 15:26:23] INFO [ 'Starting experiment: ioXQaoId' ]
[2019-12-23 15:26:23] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[2019-12-23 15:26:23] INFO [ 'Add event listeners' ]
[2019-12-23 15:26:23] INFO [ 'Run local machine training service.' ]
[2019-12-23 15:26:23] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[2019-12-23 15:26:23] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"sample_feature": []}, "parameter_index": 0}' ]
[2019-12-23 15:26:28] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"sample_feature\\": []}, \\"parameter_index\\": 0}","index":0}}' ]
[2019-12-23 15:26:33] INFO [ 'Trial job rR2km status changed from WAITING to RUNNING' ]
[2019-12-23 15:26:37] WARNING [ 'Commands jammed in buffer!' ]
[2019-12-23 15:26:39] INFO [ 'Trial job rR2km status changed from RUNNING to SUCCEEDED' ]
[2019-12-23 15:26:48] **ERROR [ 'Error: This socket has been ended by the other party\n    at Socket.writeAfterFIN [as write] (net.js:402:12)\n    at IpcInterface.sendCommand (/home/liyiran/.local/nni/core/ipcInterface.js:47:38)\n    at NNIManager.pingDispatcher (/home/liyiran/.local/nni/core/nnimanager.js:353:29)' ]**
[2019-12-23 15:26:48] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]

# 2、dispatcher.log
[12/23/2019, 03:26:37 PM] WARNING (root/MainThread) Pandas loading support in json-tricks is experimental and may change in future versions.
[12/23/2019, 03:26:37 PM] INFO (autofe-tuner/Thread-1) receive trial result is:

[12/23/2019, 03:26:37 PM] INFO (autofe-tuner/Thread-1) {'sample_feature': []}
[12/23/2019, 03:26:37 PM] INFO (autofe-tuner/Thread-1) 0.8194625188490219

# 3、nni Environment:

nni version: 1.2
nni mode(local|pai|remote): local
OS: Ubuntu 19.04
python version: python 3.6
is conda or virtualenv used?: no
is running in docker?: no
training data set size：1.6G

**Comment by chicm-ms** [comment]
Thansk for reporting this problem.
Please run `nnictl log stderr`  and `nnctl log stdout`, and paste the output.

**Comment by xuehui1991** [comment]
Hello @vivounicorn ,  I noticed that you run the code `feature_engineering/auto_feature_engineering/test_large`, is it the example link in our repo? have you changed the code? 

It seems the trial  rR2km run successfully, but the socket been killed. Also, I noticed that `sample_feature` are null in the first trial, I not sure you expect that.

**Comment by vivounicorn** [comment]
@chicm-ms @xuehui1991 Thank you.
I test this project: https://github.com/SpongebBob/tabular_automl_NNI
I have found the problem and i make a mistake, the solution as follows:
1. fe_util.py has function name2feature, and the code like this:
`  for key in feature_space:
        temp = key.split('_')
        assert len(temp) > 1`

2. search_space.json:
my original features like this:
`summ_gualoannum, summ_gualoanamount,summ_gualoanprincipalamount,........`
but the features name must not contain  `_`  ,so i maped features to new name without `_`.
