### ISSUE TITLE
Failed quickstart: ERROR: Restful server start failed!

### ISSUE THREAD

**Issue by forhonourlx** [microsoft/nni#1885]
**nni Environment**: 
- nni version: 1.2
- nni mode(local|pai|remote): local
- OS: ubuntu 18
- python version: 3.6
- is conda or virtualenv used?: no 
- is running in docker?: no

After `pip install nni`, trying quickstart and got:
nnictl create --config mnist-tfv1/config.yml
INFO: expand searchSpacePath: search_space.json to /home/simon/Desktop/nni-master/examples/trials/mnist-tfv1/search_space.json 
INFO: expand codeDir: . to /home/simon/Desktop/nni-master/examples/trials/mnist-tfv1/. 
INFO: Starting restful server...
ERROR: Restful server start failed!
INFO:  Stdout:
-----------------------------------------------------------------------
                Experiment start time 2019-12-28 18:12:34
-----------------------------------------------------------------------

INFO:  Stderr:
-----------------------------------------------------------------------
                Experiment start time 2019-12-28 18:12:34
-----------------------------------------------------------------------

Could somebody help? Thanks in advance.

**Comment by scarlett2018** [comment]
@ultmaster - similar to #1223 ?

**Comment by forhonourlx** [comment]
Not really.
It was running locally without docker.

**Comment by ultmaster** [comment]
A FAQ is related to this issue: https://nni.readthedocs.io/en/latest/Tutorial/FAQ.html. Please check before proceeds.

Use `which node` and `node -v` to check which node you are using. It should be a node installed in your user directory or virtualenv (not a global one).

**Comment by scarlett2018** [comment]
> A FAQ is related to this issue: https://nni.readthedocs.io/en/latest/Tutorial/FAQ.html. Please check before proceeds.
> 
> Use `which node` and `node -v` to check which node you are using. It should be a node installed in your user directory or virtualenv (not a global one).

@forhonourlx - let us know whether the FAQ works for you, thanks.

**Comment by forhonourlx** [comment]
It works when I `unset http_proxy && https_proxy`, then reset.
Thank you for your help.

**Comment by silverlining21** [comment]
> It works when I `unset http_proxy && https_proxy`, then reset.
> Thank you for your help.

Amazing， works for me.

**Comment by Cathy-t** [comment]
I checked /etc/hosts, the link "127.0.0.1 localhost" existed.
And I also tried to use the command "unset http_proxy && https_proxy", then restart my network.
But the error still here:
INFO:  Starting restful server...
ERROR: Restful server start failed!

Here is the log information in "nnimanager.log":
[2020-10-27 6:47:04 PM] INFO [ 'Datastore initialization done' ]
[2020-10-27 6:47:05 PM] INFO [ 'RestServer start' ]
[2020-10-27 6:47:05 PM] INFO [ 'Construct local machine training service.' ]
[2020-10-27 6:47:05 PM] INFO [ 'RestServer base port is 8080' ]
[2020-10-27 6:47:05 PM] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[2020-10-27 6:47:22 PM] INFO [ 'Change NNIManager status from: INITIALIZED to: STOPPING' ]

**Comment by hamideh-h** [comment]
I also received this error and I don't know what to do
INFO:  expand codeDir: . to C:\kit\code\Mnist-annotation-autoML\.
INFO:  Starting restful server...
ERROR: Restful server start failed!
INFO:   Stdout:
-----------------------------------------------------------------------
                Experiment start time 2020-11-09 14:14:30
-----------------------------------------------------------------------




INFO:   Stderr:
-----------------------------------------------------------------------
                Experiment start time 2020-11-09 14:14:30
-----------------------------------------------------------------------
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'typescript-ioc'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (c:\users\hamideh\appdata\local\programs\python\python37\nni\main.js:3:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

Traceback (most recent call last):
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\_pswindows.py", line 933, in create_time
    user, system, created = cext.proc_times(self.pid)
ProcessLookupError: [Errno 3] No such process (originated from GetExitCodeProcess != STILL_ACTIVE)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\__init__.py", line 352, in _init
    self.create_time()
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\__init__.py", line 708, in create_time
    self._create_time = self._proc.create_time()
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=9256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\nni_cmd\launcher.py", line 484, in launch_experiment
    kill_command(rest_process.pid)
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\nni_cmd\command_utils.py", line 37, in kill_command
    process = psutil.Process(pid=pid)
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\__init__.py", line 324, in __init__
    self._init(pid)
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\__init__.py", line 365, in _init
    raise NoSuchProcess(pid, None, msg)
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 9256

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\nni_cmd\launcher.py", line 551, in create_experiment
    launch_experiment(args, experiment_config, 'new', config_file_name)
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\nni_cmd\launcher.py", line 486, in launch_experiment
    raise Exception(ERROR_INFO % 'Rest server stopped!')
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\_pswindows.py", line 933, in create_time
    user, system, created = cext.proc_times(self.pid)
ProcessLookupError: [Errno 3] No such process (originated from GetExitCodeProcess != STILL_ACTIVE)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\__init__.py", line 352, in _init
    self.create_time()
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\__init__.py", line 708, in create_time
    self._create_time = self._proc.create_time()
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=9256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hamideh\AppData\Local\Programs\Python\Python37\Scripts\nnictl.exe\__main__.py", line 7, in <module>
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\nni_cmd\nnictl.py", line 255, in parse_args
    args.func(args)
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\nni_cmd\launcher.py", line 556, in create_experiment
    kill_command(restServerPid)
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\nni_cmd\command_utils.py", line 37, in kill_command
    process = psutil.Process(pid=pid)
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\__init__.py", line 324, in __init__
    self._init(pid)
  File "c:\users\hamideh\appdata\local\programs\python\python37\lib\site-packages\psutil\__init__.py", line 365, in _init
    raise NoSuchProcess(pid, None, msg)
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 9256

**Comment by Benjamin15122** [comment]
> It works when I `unset http_proxy && https_proxy`, then reset.
> Thank you for your help.

works for me too on ubuntu 20.04, but why...?
