### ISSUE TITLE
Tuner failed when updating searchSpace 

### ISSUE THREAD

**Issue by Crysple** [Microsoft/nni#193]
- Start a new experiment using TPE or Evolution
- then update the searchsapce
- tuner will failed when it receive trial result

[2018-10-10 17:06:49] ERROR (nni.main) list index out of range
Traceback (most recent call last):
  File "/mnt/d/git/nni/src/sdk/pynni/nni/__main__.py", line 142, in main
    dispatcher.run()
  File "/mnt/d/git/nni/src/sdk/pynni/nni/msg_dispatcher_base.py", line 42, in run
    while self.handle_request():
  File "/mnt/d/git/nni/src/sdk/pynni/nni/msg_dispatcher_base.py", line 75, in handle_request
    return command_handlers[command](data)
  File "/mnt/d/git/nni/src/sdk/pynni/nni/msg_dispatcher.py", line 131, in handle_report_metric_data
    self.tuner.receive_trial_result(id_, _trial_params[id_], value)
  File "/mnt/d/git/nni/src/sdk/pynni/nni/hyperopt_tuner/hyperopt_tuner.py", line 238, in receive_trial_result
    json2vals(self.json, vals, out_y)
  File "/mnt/d/git/nni/src/sdk/pynni/nni/hyperopt_tuner/hyperopt_tuner.py", line 127, in json2vals
    json2vals(in_x[key], vals[key], out_y, name + '[%s]' % str(key))
  File "/mnt/d/git/nni/src/sdk/pynni/nni/hyperopt_tuner/hyperopt_tuner.py", line 123, in json2vals
    json2vals(in_x[VALUE][_index], vals[VALUE],
IndexError: list index out of range
[2018-10-10 17:06:49] ERROR (nni.main) list index out of range
Traceback (most recent call last):
  File "/mnt/d/git/nni/src/sdk/pynni/nni/__main__.py", line 155, in <module>
    main()
  File "/mnt/d/git/nni/src/sdk/pynni/nni/__main__.py", line 142, in main
    dispatcher.run()
  File "/mnt/d/git/nni/src/sdk/pynni/nni/msg_dispatcher_base.py", line 42, in run
    while self.handle_request():
  File "/mnt/d/git/nni/src/sdk/pynni/nni/msg_dispatcher_base.py", line 75, in handle_request
    return command_handlers[command](data)
  File "/mnt/d/git/nni/src/sdk/pynni/nni/msg_dispatcher.py", line 131, in handle_report_metric_data
    self.tuner.receive_trial_result(id_, _trial_params[id_], value)
  File "/mnt/d/git/nni/src/sdk/pynni/nni/hyperopt_tuner/hyperopt_tuner.py", line 238, in receive_trial_result
    json2vals(self.json, vals, out_y)
  File "/mnt/d/git/nni/src/sdk/pynni/nni/hyperopt_tuner/hyperopt_tuner.py", line 127, in json2vals
    json2vals(in_x[key], vals[key], out_y, name + '[%s]' % str(key))
  File "/mnt/d/git/nni/src/sdk/pynni/nni/hyperopt_tuner/hyperopt_tuner.py", line 123, in json2vals
    json2vals(in_x[VALUE][_index], vals[VALUE],
IndexError: list index out of range

**Comment by QuanluZhang** [comment]
this error is from nni master branch, while v0.2 correctly works. so the error might be introduced by muti-phase support. could @xuehui1991 and @chicm-ms take a look?

**Comment by chicm-ms** [comment]
I will investigate it.

**Comment by chicm-ms** [comment]
Fixed,  verified.
