### ISSUE TITLE
HTTP Error when downloading a pretrained model for TGS Salt 

### ISSUE THREAD

**Issue by dumaaan** [microsoft/nni#2036]
**Short summary about the issue/question**:
I was attempting to reproduce the Kaggle TGS Salt challenge solution at [https://github.com/microsoft/nni/tree/master/examples/trials/kaggle-tgs-salt](https://github.com/microsoft/nni/tree/master/examples/trials/kaggle-tgs-salt), and the training process was going well until today when I was fine-tuning stage 2 models with depths channel for UNetResNetV6.

Here's the error traceback:

`Namespace(adamw=False, batch_size=32, depths=True, dev_mode=False, epochs=300, exp_name=None, factor=0.5, ifolds='3', init_ckp=None, layers=34, lr=0.001, lrs='cosine', meta_version=2, min_lr=0.0001, model_name='UNetResNetV6', nf=32, optim='SGD', pad_mode='edge', patience=6, pseudo=False, start_epoch=0, store_loss_model=False, t_max=15, train_cls=False, val=False)
[3]
start training...
Downloading: "https://download.pytorch.org/models/resnet34-333f7ec4.pth" to /home/work/.cache/torch/checkpoints/resnet34-333f7ec4.pth
Traceback (most recent call last):
  File "train.py", line 258, in <module>
    train(args)
  File "train.py", line 64, in train
    model = eval(model_name)(args.layers, num_filters=args.nf)
  File "/home/work/salt/models.py", line 342, in __init__
    self.resnet, bottom_channel_nr = create_resnet(encoder_depth)
  File "/home/work/salt/models.py", line 133, in create_resnet
    return resnet34(pretrained=True), 512
  File "/usr/local/lib/python3.6/site-packages/torchvision/models/resnet.py", line 243, in resnet34
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torchvision/models/resnet.py", line 217, in _resnet
    progress=progress)
  File "/usr/local/lib/python3.6/site-packages/torch/hub.py", line 462, in load_state_dict_from_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/usr/local/lib/python3.6/site-packages/torch/hub.py", line 372, in _download_url_to_file
    u = urlopen(url)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

I don't think that's an issue on my side, as I managed to fine-tune previous folds for UNetResNetV6 without any problems.

**How to reproduce it**: 
Simply follow the instructions at [https://github.com/microsoft/nni/tree/master/examples/trials/kaggle-tgs-salt](https://github.com/microsoft/nni/tree/master/examples/trials/kaggle-tgs-salt). The error had occurred once I reached stage 3, but it might appear earlier.

**nni Environment**:
- nni version: 1.0
- nni mode(local|pai|remote): local
- OS: Ubuntu
- python version: 3.6
- is conda or virtualenv used?: no 
- is running in docker?: no

**need to update document(yes/no)**: yes

**Anything else we need to know**: probably the TGS Salt challenge repo might need to be updated.

**Comment by chicm-ms** [comment]
Hi @dumaaan The error occurs while downloading pretrained weight https://download.pytorch.org/models/resnet34-333f7ec4.pth from pytorch website, could be a temporary issue with network or the download service,  you can retry it.
