### ISSUE TITLE
Running MNIST example in kubeflow mode reports 404 error

### ISSUE THREAD

**Issue by qtz93** [microsoft/nni#2158]
**Short summary about the issue/question**:
After installing and deploying the 0.6 version of kubeflow on a private kubenetes cluster, I was unable to successfully run the example in kubeflow mode under mnist-tfv1. 

**Brief what process you are following**: 
The running status of pod is as follows:
```shell
(base) [root@master ~]# kubectl get pod -n kubeflow
NAME                                                        READY   STATUS    RESTARTS   AGE
admission-webhook-bootstrap-stateful-set-0                  1/1     Running   5          11d
admission-webhook-deployment-5597c76f74-c6gvq               1/1     Running   0          6d3h
application-controller-stateful-set-0                       1/1     Running   1          11d
argo-ui-5dcf5d8b4f-gtfqw                                    1/1     Running   1          11d
centraldashboard-84c4fb57ff-vgp8g                           1/1     Running   1          11d
jupyter-web-app-deployment-5b4668f-r92q4                    1/1     Running   1          11d
katib-controller-697746fb4c-kwlzf                           1/1     Running   2          11d
katib-db-8598468fd8-gsqhz                                   1/1     Running   1          11d
katib-manager-6f5f4bdfb5-r5tl9                              1/1     Running   15         11d
katib-manager-rest-7d4d8d9ff-w7tdm                          1/1     Running   1          11d
katib-suggestion-bayesianoptimization-89f9f85cd-5xrh2       1/1     Running   1          11d
katib-suggestion-grid-f4895b4d7-fjj6k                       1/1     Running   1          11d
katib-suggestion-hyperband-54d8985859-sxmdf                 1/1     Running   1          11d
katib-suggestion-nasrl-76bb86c9d9-gt5h8                     1/1     Running   1          11d
katib-suggestion-random-5454c8ccc-nlhpr                     1/1     Running   1          11d
katib-ui-78d5b65fcc-55zt2                                   1/1     Running   1          11d
metacontroller-0                                            1/1     Running   1          11d
metadata-db-5dd459cc-zjc28                                  1/1     Running   1          11d
metadata-deployment-57fc569986-q6bgr                        1/1     Running   20         11d
metadata-deployment-57fc569986-vdkv7                        1/1     Running   18         11d
metadata-deployment-57fc569986-zcnff                        1/1     Running   19         11d
metadata-ui-64c7998f9b-tpftn                                1/1     Running   1          11d
minio-758b769d67-h578l                                      1/1     Running   1          11d
ml-pipeline-75f48866d9-f5xcd                                1/1     Running   9          11d
ml-pipeline-persistenceagent-6944bcfb68-w5kxc               1/1     Running   11         11d
ml-pipeline-scheduledworkflow-6fd8588578-jgw5k              1/1     Running   1          11d
ml-pipeline-ui-8665c5fdb-fnbn9                              1/1     Running   1          11d
ml-pipeline-viewer-controller-deployment-54b84c99c8-4dbbv   1/1     Running   1          11d
mysql-657f87857d-k29tn                                      1/1     Running   1          11d
notebook-controller-deployment-86f5d77f47-89vtp             1/1     Running   1          11d
profiles-deployment-5d4bcf6bdc-rw8mg                        2/2     Running   2          11d
pytorch-operator-685896c59f-np9xl                           1/1     Running   3          11d
seldon-operator-controller-manager-0                        1/1     Running   2          11d
spartakus-volunteer-5b4d7f88bf-wkdsh                        1/1     Running   1          11d
tensorboard-6544748d94-kq79w                                1/1     Running   1          11d
tf-job-dashboard-7c6fcd4784-5pr7z                           1/1     Running   1          11d
tf-job-operator-6b4d4fff9f-f7wwv                            1/1     Running   3          11d
workflow-controller-db644d554-456rk                         1/1     Running   1          11d
```
and the details of log error are as follows:
```shell
[3/17/2020, 1:06:51 PM] INFO [ 'Datastore initialization done' ]
[3/17/2020, 1:06:51 PM] INFO [ 'RestServer start' ]
[3/17/2020, 1:06:51 PM] INFO [ 'Construct Kubeflow training service.' ]
[3/17/2020, 1:06:51 PM] INFO [ 'RestServer base port is 46001' ]
[3/17/2020, 1:06:51 PM] INFO [ 'Rest server listening on: http://0.0.0.0:46001' ]
[3/17/2020, 1:06:53 PM] INFO [ 'NNIManager setClusterMetadata, key: kubeflow_config, value: {"operator":"tf-operator","apiVersion":"v1alpha2","storage":"nfs","nfs":{"server":"172.16.xx.xx","path":"/opt/data2/nfs_nni_share"}}' ]
[3/17/2020, 1:06:53 PM] INFO [ 'NNIManager setClusterMetadata, key: nni_manager_ip, value: {"nniManagerIp":"enp6s0f0"}' ]
[3/17/2020, 1:06:53 PM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"codeDir":"/home/xxx/Programs/xxx/trials/mnist-tfv1/.","worker":{"replicas":1,"command":"python3 mnist.py","gpuNum":0,"cpuNum":1,"memoryMB":8192,"image":"msranni/nni:latest"}}' ]
[3/17/2020, 1:06:53 PM] INFO [ 'Starting experiment: c7J9TZR9' ]
[3/17/2020, 1:06:53 PM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[3/17/2020, 1:06:53 PM] INFO [ 'Add event listeners' ]
[3/17/2020, 1:06:53 PM] INFO [ 'Run Kubeflow training service.' ]
[3/17/2020, 1:06:53 PM] INFO [ 'RestServer start' ]
[3/17/2020, 1:06:53 PM] INFO [ 'RestServer base port is 46002' ]
[3/17/2020, 1:06:53 PM] INFO [ 'Kubeflow Training service rest server listening on: http://0.0.0.0:46002' ]
[3/17/2020, 1:06:54 PM] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[3/17/2020, 1:06:54 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"dropout_rate": 0.7787252946116108, "conv_size": 3, "hidden_size": 64, "batch_size": 16, "learning_rate": 0.01}, "parameter_index": 0}' ]
[3/17/2020, 1:06:58 PM] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"dropout_rate\\": 0.7787252946116108, \\"conv_size\\": 3, \\"hidden_size\\": 64, \\"batch_size\\": 16, \\"learning_rate\\": 0.01}, \\"parameter_index\\": 0}","index":0}}' ]
[3/17/2020, 1:06:58 PM] ERROR [ 'Error: 404 page not found\n\n    at _request (/soft/anaconda3/envs/automl/nni/node_modules/kubernetes-client/lib/backends/request.js:189:25)\n    at Request.request [as _callback] (/soft/anaconda3/envs/automl/nni/node_modules/kubernetes-client/lib/backends/request.js:148:14)\n    at Request.self.callback (/soft/anaconda3/envs/automl/nni/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:182:13)\n    at Request.<anonymous> (/soft/anaconda3/envs/automl/nni/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:182:13)\n    at IncomingMessage.<anonymous> (/soft/anaconda3/envs/automl/nni/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:273:13)\n    at IncomingMessage.emit (events.js:187:15)\n    at endReadableNT (_stream_readable.js:1094:12)' ]
[3/17/2020, 1:06:58 PM] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]
```

**How to reproduce it**: 

**nni Environment**:
- nni version: 1.3
- nni mode(local|pai|remote): remote[kubeflow mode]
- OS: CentOS7.5
- python version: 3.6.7
- is conda or virtualenv used?: conda
- is running in docker?: yes

**need to update document(yes/no)**:

**Anything else we need to know**:

**Comment by SparkSnail** [comment]
Hi @qtz93 , seems that you are using v1alpha2 tf-operator, did you checked that if your kubeflow environment support using v1alpha2 operator?

**Comment by qtz93** [comment]
@SparkSnail ，Hello, according to your suggestion, I pulled the version 1.3 NNI image to the kubenetes cluster today (https://hub.docker.com/r/msranni/nni), then changed the image in the file config_kubeflow.yml to msranni / NNI: v1.3, and changed the apiversion to v1. Finally, after the experiment was started, it was found that the visual interface of NNI always displayed WAITING and NO_MORE_TRIAL. The NNI experiment didn't seem to be running.

Tips: I can successfully run the tensorflow program on the kubenetes cluster, where the tf-operator version I use is v1.

The contents of config_kubeflow.yml file are as follows:
```shell
authorName: default
experimentName: example_dist
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 1
#choice: local, remote, pai, kubeflow
trainingServicePlatform: kubeflow
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
nniManagerIp: "enp6s0f0"
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  codeDir: .
  worker:
    replicas: 1
    command: python3 mnist.py
    gpuNum: 0
    cpuNum: 1
    memoryMB: 8192
    image: msranni/nni:v1.3
kubeflowConfig:
  operator: tf-operator
  apiVersion: v1
  storage: nfs
  nfs:
    server: 172.16.xx.xx
    path: /opt/data2/nfs_nni_share
```

nnimanager.log:
```shell
[3/30/2020, 2:00:16 PM] INFO [ 'Datastore initialization done' ]
[3/30/2020, 2:00:16 PM] INFO [ 'RestServer start' ]
[3/30/2020, 2:00:16 PM] INFO [ 'Construct Kubeflow training service.' ]
[3/30/2020, 2:00:16 PM] INFO [ 'RestServer base port is 46001' ]
[3/30/2020, 2:00:16 PM] INFO [ 'Rest server listening on: http://0.0.0.0:46001' ]
[3/30/2020, 2:00:17 PM] INFO [ 'NNIManager setClusterMetadata, key: kubeflow_config, value: {"operator":"tf-operator","apiVersion":"v1","storage":"nfs","nfs":{"server":"172.16.2.60","path":"/opt/data2/nfs_nni_share"}}' ]
[3/30/2020, 2:00:18 PM] INFO [ 'NNIManager setClusterMetadata, key: nni_manager_ip, value: {"nniManagerIp":"enp6s0f0"}' ]
[3/30/2020, 2:00:18 PM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"codeDir":"/home/xxx/Programs/xxx/trials/mnist-tfv1/.","worker":{"replicas":1,"command":"python3 mnist.py","gpuNum":0,"cpuNum":1,"memoryMB":8192,"image":"msranni/nni:v1.3"}}' ]
[3/30/2020, 2:00:18 PM] INFO [ 'Starting experiment: gPJi8ybs' ]
[3/30/2020, 2:00:18 PM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[3/30/2020, 2:00:18 PM] INFO [ 'Add event listeners' ]
[3/30/2020, 2:00:18 PM] INFO [ 'Run Kubeflow training service.' ]
[3/30/2020, 2:00:18 PM] INFO [ 'RestServer start' ]
[3/30/2020, 2:00:18 PM] INFO [ 'RestServer base port is 46002' ]
[3/30/2020, 2:00:18 PM] INFO [ 'Kubeflow Training service rest server listening on: http://0.0.0.0:46002' ]
[3/30/2020, 2:00:19 PM] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[3/30/2020, 2:00:19 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"dropout_rate": 0.8905487464712047, "conv_size": 3, "hidden_size": 64, "batch_size": 16, "learning_rate": 0.001}, "parameter_index": 0}' ]
[3/30/2020, 2:00:23 PM] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"dropout_rate\\": 0.8905487464712047, \\"conv_size\\": 3, \\"hidden_size\\": 64, \\"batch_size\\": 16, \\"learning_rate\\": 0.001}, \\"parameter_index\\": 0}","index":0}}' ]
[3/30/2020, 2:00:28 PM] INFO [ 'Change NNIManager status from: RUNNING to: NO_MORE_TRIAL' ]
```

Any tips will be appreciate!

**Comment by qtz93** [comment]
@SparkSnail Note: The cluster environment I am using does not have nvidia-driver.
I found that the config_kubeflow.yml file specifies: gpuNum: 0 and cpuNum: 1. Do I have to install the nvidia driver on the kubenetes cluster to run the mnist example in kubeflow mode?

**Comment by qtz93** [comment]
@ultmaster @SparkSnail There is no error in the log and no more prompt. The experimental status shows waiting and no more trial all the time. Which link is the problem?

**Comment by SparkSnail** [comment]
Seems this issue is tracked in https://github.com/microsoft/nni/issues/2248#issuecomment-606767948

**Comment by qtz93** [comment]
@SparkSnail Yes, i have solved the 404 error. ^_^
