### ISSUE TITLE
Tuner error occurs when running 4 nas examples under mnist-nas directory

### ISSUE THREAD

**Issue by qiutzh** [microsoft/nni#2328]
**Short summary about the issue/question**:
The iteration speed of the NNI version is particularly fast. I tested the NAS algorithm version 0.8.1 a few months ago, and the examples in the mnist-nas directory can be executed normally. The new version has many more NAS series algorithm examples (examples/nas, using pytorch), it seems that these algorithms have not added WebUI interface. Will the examples under mnist-nas be discarded?

**Brief what process you are following**: 
I found that the new version of NNI's random_nas_tuner.py has been slightly modified, resulting in these examples not working properly.

```shell
# NNI WebUI
Dispatcher stream error, tuner may have crashed.

## dispatcher.log
[04/16/2020, 03:33:04 PM] INFO (nni.msg_dispatcher_base/MainThread) Start dispatcher
[04/16/2020, 03:33:04 PM] ERROR (nni.msg_dispatcher_base/Thread-1) Random NAS Tuner only receives NAS search space whose _type is 'layer_choice' or 'input_choice'
Traceback (most recent call last):
  File "/soft/anaconda3/envs/automl/lib/python3.6/site-packages/nni/msg_dispatcher_base.py", line 90, in command_queue_worker
    self.process_command(command, data)
  File "/soft/anaconda3/envs/automl/lib/python3.6/site-packages/nni/msg_dispatcher_base.py", line 149, in process_command
    command_handlers[command](data)
  File "/soft/anaconda3/envs/automl/lib/python3.6/site-packages/nni/msg_dispatcher.py", line 101, in handle_request_trial_jobs
    params_list = self.tuner.generate_multiple_parameters(ids, st_callback=self.send_trial_callback)
  File "/soft/anaconda3/envs/automl/lib/python3.6/site-packages/nni/tuner.py", line 132, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id, **kwargs)
  File "/home/junan/Programs/Sources/nni_v13_official/examples/trials/mnist-nas/classic_mode/../../../tuners/random_nas_tuner/random_nas_tuner.py", line 49, in generate_parameters
    return random_archi_generator(self.searchspace_json, self.random_state)
  File "/home/junan/Programs/Sources/nni_v13_official/examples/trials/mnist-nas/classic_mode/../../../tuners/random_nas_tuner/random_nas_tuner.py", line 12, in random_archi_generator
    "Random NAS Tuner only receives NAS search space whose _type is 'layer_choice' or 'input_choice'"
AssertionError: Random NAS Tuner only receives NAS search space whose _type is 'layer_choice' or 'input_choice'
[04/16/2020, 03:33:09 PM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...
[04/16/2020, 03:33:10 PM] INFO (nni.msg_dispatcher_base/MainThread) Terminated by NNI manager

## nnimanager.log
[4/16/2020, 3:33:01 PM] INFO [ 'Datastore initialization done' ]
[4/16/2020, 3:33:01 PM] INFO [ 'RestServer start' ]
[4/16/2020, 3:33:01 PM] INFO [ 'Construct local machine training service.' ]
[4/16/2020, 3:33:01 PM] INFO [ 'RestServer base port is 23333' ]
[4/16/2020, 3:33:01 PM] INFO [ 'Rest server listening on: http://0.0.0.0:23333' ]
[4/16/2020, 3:33:04 PM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python3 mnist.py","codeDir":"/tmp/root/nni/annotation/tmpjelpe_al","gpuNum":0,"nasMode":"classic_mode"}' ]
[4/16/2020, 3:33:04 PM] INFO [ 'required GPU number is 0' ]
[4/16/2020, 3:33:04 PM] INFO [ 'Starting experiment: F861B1ZL' ]
[4/16/2020, 3:33:04 PM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[4/16/2020, 3:33:04 PM] INFO [ 'Add event listeners' ]
[4/16/2020, 3:33:04 PM] INFO [ 'Run local machine training service.' ]
[4/16/2020, 3:33:04 PM] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[4/16/2020, 3:33:14 PM] ERROR [ 'Dispatcher error: This socket has been ended by the other party' ]
[4/16/2020, 3:33:14 PM] ERROR [ 'Error: Dispatcher stream error, tuner may have crashed.\n    at EventEmitter.dispatcher.onError (/soft/anaconda3/envs/automl/nni/core/nnimanager.js:505:32)\n    at EventEmitter.emit (events.js:182:13)\n    at Socket.IpcInterface.outgoingStream.on (/soft/anaconda3/envs/automl/nni/core/ipcInterface.js:42:72)\n    at Socket.emit (events.js:182:13)\n    at Socket.writeAfterFIN [as write] (net.js:405:8)\n    at IpcInterface.sendCommand (/soft/anaconda3/envs/automl/nni/core/ipcInterface.js:49:38)\n    at NNIManager.pingDispatcher (/soft/anaconda3/envs/automl/nni/core/nnimanager.js:354:29)' ]
[4/16/2020, 3:33:14 PM] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]
[4/16/2020, 3:33:14 PM] WARNING [ 'Commands jammed in buffer!' ]
```

**How to reproduce it**: 

**nni Environment**:
- nni version: 1.3 | 1.5
- nni mode(local|pai|remote): local
- OS: CentOS7.5
- python version: 3.6.7
- is conda or virtualenv used?: conda
- is running in docker?: no

**need to update document(yes/no)**: yes

**Anything else we need to know**:
Does the NAS series algorithm plan to add WebUI in the future? Thanks!

**Comment by QuanluZhang** [comment]
@qiutzh the mnist-nas example you tried is deprecated. We will provide the refactored ones soon. 

Please refer to [here](https://github.com/microsoft/nni/tree/master/examples/nas) for nas examples. The one that is similar to mnist-nas is [classic_nas](https://github.com/microsoft/nni/tree/master/examples/nas/classic_nas).

For webui, the classic_nas example is natively supported by NNI webui. Visualization of some one-shot NAS algorithms has been supported in v1.5, please refer to [here](https://nni.readthedocs.io/en/latest/NAS/Visualization.html) for the usage.

**Comment by qiutzh** [comment]
@QuanluZhang thanks~

**Comment by kvartet** [comment]
hello @qiutzh, NAS on NNI had migrated to Retiarii Framework, please try it and update the status of your issue, refer [here](https://nni.readthedocs.io/en/latest/nas.html). Thanks!
