### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sname' in model_speedup.py

### ISSUE THREAD

**Issue by chenbong** [microsoft/nni#2329]
**Short summary about the issue/question**:
```
Traceback (most recent call last):
  File "/home/cbh/one/nni/examples/model_compress/model_speedup.py", line 93, in <module>
    model_inference(config[args.example_name])
  File "/home/cbh/one/nni/examples/model_compress/model_speedup.py", line 68, in model_inference
    'cpu' if config['device'] == 'cpu' else None)
  File "/home/cbh/.local/lib/python3.6/site-packages/nni/compression/speedup/torch/compressor.py", line 99, in __init__
    self.name_to_gnode, self.input_to_gnode, self.output_to_gnode = self._build_graph()
  File "/home/cbh/.local/lib/python3.6/site-packages/nni/compression/speedup/torch/compressor.py", line 305, in _build_graph
    leaf_modules = self._extract_leaf_modules(graph)
  File "/home/cbh/.local/lib/python3.6/site-packages/nni/compression/speedup/torch/compressor.py", line 263, in _extract_leaf_modules
    traverse_tree(root, '')
  File "/home/cbh/.local/lib/python3.6/site-packages/nni/compression/speedup/torch/compressor.py", line 254, in traverse_tree
    sn = node.sname
AttributeError: 'NoneType' object has no attribute 'sname'
```
**Brief what process you are following**: 

run
```
python nni/examples/model_compression/model_speedup.py
```

**How to reproduce it**: 
run
```
python nni/examples/model_compression/model_speedup.py
```

**nni Environment**:
- nni version:1.5
- nni mode(local|pai|remote):local
- OS:ubuntu 16.04
- python version: 3.6.7
- is conda or virtualenv used?: use conda
- is running in docker?: no

**need to update document(yes/no)**:
no
**Anything else we need to know**:
nothing

**Comment by chenbong** [comment]
@QuanluZhang

**Comment by QuanluZhang** [comment]
@chenbong thanks for reporting this issue. Could you check your pytorch version? Currently, ModelSpeedup only supports torch 1.3.1. Please refer to [doc](https://nni.readthedocs.io/en/latest/Compressor/ModelSpeedup.html) for more details.

**Comment by chenbong** [comment]
@QuanluZhang Thanks for your reply, my pytorch version is 1.4.0, after I downgrade my pytorch version to 1.3.1, it works well. 
But I still hope ModelSpeedup can support the latest pytorch version in later nni version, thanks for your reply again!

**Comment by QuanluZhang** [comment]
@chenbong yes, it will be supported in v1.6
