### ISSUE TITLE
KeyError when using hyperband advisor

### ISSUE THREAD

**Issue by colorjam** [microsoft/nni#2467]
After several successful trials,  the experiment becomes error, dispatcher log:
```python
[05/20/2020, 04:57:27 PM] INFO (nni.msg_dispatcher_base/MainThread) Start dispatcher
[05/20/2020, 05:01:25 PM] ERROR (nni.msg_dispatcher_base/Thread-2) '1_0_27'
Traceback (most recent call last):
  File "/home/v-chenqy/.pyenv/versions/py37/lib/python3.7/site-packages/nni/msg_dispatcher_base.py", line 90, in command_queue_worker
    self.process_command(command, data)
  File "/home/v-chenqy/.pyenv/versions/py37/lib/python3.7/site-packages/nni/msg_dispatcher_base.py", line 149, in process_command
    command_handlers[command](data)
  File "/home/v-chenqy/.pyenv/versions/py37/lib/python3.7/site-packages/nni/hyperband_advisor/hyperband_advisor.py", line 367, in handle_trial_end
    self._handle_trial_end(hyper_params['parameter_id'])
  File "/home/v-chenqy/.pyenv/versions/py37/lib/python3.7/site-packages/nni/hyperband_advisor/hyperband_advisor.py", line 351, in _handle_trial_end
    hyper_configs = self.brackets[int(bracket_id)].inform_trial_end(int(i))
  File "/home/v-chenqy/.pyenv/versions/py37/lib/python3.7/site-packages/nni/hyperband_advisor/hyperband_advisor.py", line 202, in inform_trial_end
    params = self.hyper_configs[i][params_id]
KeyError: '1_0_27'
[05/20/2020, 05:01:27 PM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...
[05/20/2020, 05:01:30 PM] INFO (nni.msg_dispatcher_base/MainThread) Terminated by NNI manager

```

**Comment by J-shang** [comment]
The latest version has fixed this problem, so close this issue.
