### ISSUE TITLE
issues about nni classic nas tuner

### ISSUE THREAD

**Issue by JunweiSUN** [microsoft/nni#2577]
**Environment**:
- NNI version: 1.6
- NNI mode (local|remote|pai): local
- Client OS: ubuntu
- Server OS (for remote mode only):
- Python version:  3.6.10
- PyTorch/TensorFlow version: pytorch 1.5
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
[06/18/2020, 09:06:29 AM] INFO (nni.msg_dispatcher_base/MainThread) Start dispatcher
[06/18/2020, 09:06:29 AM] ERROR (nni.msg_dispatcher_base/Thread-1) 'NoneType' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/home/sjw/anaconda3/envs/test/lib/python3.6/site-packages/nni/msg_dispatcher_base.py", line 90, in command_queue_worker
    self.process_command(command, data)
  File "/home/sjw/anaconda3/envs/test/lib/python3.6/site-packages/nni/msg_dispatcher_base.py", line 149, in process_command
    command_handlers[command](data)
  File "/home/sjw/anaconda3/envs/test/lib/python3.6/site-packages/nni/msg_dispatcher.py", line 101, in handle_request_trial_jobs
    params_list = self.tuner.generate_multiple_parameters(ids, st_callback=self.send_trial_callback)
  File "/home/sjw/anaconda3/envs/test/lib/python3.6/site-packages/nni/tuner.py", line 132, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id, **kwargs)
  File "/home/sjw/nni_tutorial/nas/./random_nas_tuner.py", line 49, in generate_parameters
    return random_archi_generator(self.searchspace_json, self.random_state)
  File "/home/sjw/nni_tutorial/nas/./random_nas_tuner.py", line 22, in random_archi_generator
    for _ in range(n_chosen):
TypeError: 'NoneType' object cannot be interpreted as an integer
[06/18/2020, 09:06:34 AM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...
[06/18/2020, 09:06:35 AM] INFO (nni.msg_dispatcher_base/MainThread) Terminated by NNI manager

 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
When using the [classic nas tuner](https://github.com/microsoft/nni/blob/97f9d8a992749584455fa76822956190a75c64f3/examples/tuners/random_nas_tuner/random_nas_tuner.py), if there is an InputChoice in the trial codes and its n_chosen is not specificed (remain None), the search space generated by ```nnictl ss_gen``` will assgin null to this InputChoice's ```n_chosen``` parameter. This will lead to experiment error since this tuner will not check if this parameter is null before using it.

Also, I found that package ```gym``` is a requirement of [PPOTuner](https://github.com/microsoft/nni/blob/926c42dec29c9a70db5f8669aa0ed3ce4d22978c/src/sdk/pynni/nni/ppo_tuner/ppo_tuner.py), but this requirement will not be installed when nni is installed. Users need to install this package manually by ```nnictl package install --name=PPOTuner``` before using it, which seems not very friendly.

What's more, there seems to have a typo [here](https://github.com/microsoft/nni/blob/master/src/sdk/pynni/nni/nas/pytorch/classic_nas/mutator.py)
line 101-111:
```python
    def _sample_input_choice(self, mutable, idx, value, search_space_item):
        """
        Convert input choice to tensor representation.
        Parameters
        ----------
        mutable : Mutable
        idx : int
            Number `idx` of list will be selected.
        value : str
            The verbose representation of the selected value.
```
the type of idx and value should be list of int and list of str.

**Comment by kvartet** [comment]
closed this issue because classic NAS had been refactored.
