### ISSUE TITLE
Failed to generate nni_auto_gen_search_space.json

### ISSUE THREAD

**Issue by kingaza** [microsoft/nni#2613]
**Environment**: Win10
- NNI version: 1.5
- NNI mode (local|remote|pai): Local
- Client OS:Win10
- Server OS (for remote mode only):
- Python version:3.7
- PyTorch/TensorFlow version:1.5
- Is conda/virtualenv/venv used?:conda
- Is running in Docker?:no

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
I try to generate search space file, but failed

**How to reproduce it?**: 
(base) D:\3_Dev\nni\examples\nas\classic_nas>nnictl ss_gen --trial_command="python mnist.py"
INFO: Dry run to generate search space...
ERROR:mnist_AutoML:str is not a Module subclass
Traceback (most recent call last):
  File "mnist.py", line 181, in <module>
    main(params)
  File "mnist.py", line 131, in main
    model = Net(hidden_size=hidden_size).to(device)
  File "mnist.py", line 34, in __init__
    ]), key='first_conv')
  File "C:\ProgramData\Anaconda3\lib\site-packages\nni\nas\pytorch\mutables.py", line 154, in __init__
    self.choices = nn.ModuleList(op_candidates)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 131, in __init__
    self += modules
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 172, in __iadd__
    return self.extend(modules)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 211, in extend
    self.add_module(str(offset + i), module)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 189, in add_module
    torch.typename(module)))
TypeError: str is not a Module subclass
Traceback (most recent call last):
  File "mnist.py", line 181, in <module>
    main(params)
  File "mnist.py", line 131, in main
    model = Net(hidden_size=hidden_size).to(device)
  File "mnist.py", line 34, in __init__
    ]), key='first_conv')
  File "C:\ProgramData\Anaconda3\lib\site-packages\nni\nas\pytorch\mutables.py", line 154, in __init__
    self.choices = nn.ModuleList(op_candidates)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 131, in __init__
    self += modules
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 172, in __iadd__
    return self.extend(modules)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 211, in extend
    self.add_module(str(offset + i), module)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 189, in add_module
    torch.typename(module)))
TypeError: str is not a Module subclass
WARNING: Expected search space file 'D:\3_Dev\nni\examples\nas\classic_nas\nni_auto_gen_search_space.json' generated, but not found.

**Additional information**:

**Comment by kingaza** [comment]
but it works in Ubuntu 1604...
