### ISSUE TITLE
TextNAS error.    AssertionError: Invalid mask, expected tensor([ True, False]) to be of length 1.

### ISSUE THREAD

**Issue by yongzhuo** [microsoft/nni#2625]
**Environment**:
- NNI version: 999.0.0-developing
- NNI mode (local|remote|pai): local
- Client OS: win10
- Server OS (for remote mode only): 
- Python version: 3.6
- PyTorch/TensorFlow version: PyTorch=1.5.0
- Is conda/virtualenv/venv used?:  conda
- Is running in Docker?: no

**Log message**:
```
Traceback (most recent call last):
  File "nni-master/examples/nas/textnas/retrain.py", line 537, in <module>
    main()
  File "nni-master/examples/nas/textnas/retrain.py", line 533, in main
    train(device, FLAGS.data_path, FLAGS.output_dir, FLAGS.child_num_layers)
  File "nni-master/examples/nas/textnas/retrain.py", line 461, in train
    logits = child_model((sent_ids, mask))  # run
  File "anaconda3\envs\tf115\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\workspace\pythonGithubCode\AutoML\nni_20200629\nni-master\examples\nas\textnas\model.py", line 101, in forward
    x = layer(x, prev_layers, mask)
  File "anaconda3\envs\tf115\lib\site-packages\nni-999.0.0_developing-py3.6.egg\nni\nas\pytorch\mutables.py", line 90, in __call__
    return super().__call__(*args, **kwargs)
  File "anaconda3\envs\tf115\lib\site-packages\nni-999.0.0_developing-py3.6.egg\nni\nas\pytorch\mutables.py", line 41, in __call__
    return super().__call__(*args, **kwargs)
  File "anaconda3\envs\tf115\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "nni-master\examples\nas\textnas\model.py", line 47, in forward
    prec = self.prec(prev_layers[-self.prec.n_candidates:])  # skip first
  File "anaconda3\envs\tf115\lib\site-packages\nni-999.0.0_developing-py3.6.egg\nni\nas\pytorch\mutables.py", line 41, in __call__
    return super().__call__(*args, **kwargs)
  File "anaconda3\envs\tf115\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "anaconda3\envs\tf115\lib\site-packages\nni-999.0.0_developing-py3.6.egg\nni\nas\pytorch\mutables.py", line 189, in forward
    out, mask = self.mutator.on_forward_input_choice(self, optional_input_list)
  File "anaconda3\envs\tf115\lib\site-packages\nni-999.0.0_developing-py3.6.egg\nni\nas\pytorch\mutator.py", line 107, in on_forward_input_choice
    "Invalid mask, expected {} to be of length {}.".format(mask, mutable.n_candidates)
AssertionError: Invalid mask, expected tensor([ True, False]) to be of length 1.
```
 
** Where can you find the log files**: 
    no

**What issue meet, what's expected?**:
a little like [#1796](https://github.com/microsoft/nni/issues/1796)

**How to reproduce it?**: 
When I run “python examples/nas/textnas/search.py” ,soon after I get 20 child_fixed_arc, then I select one child_fixed_arc of "checkpoints/architecture_00.json" and run "python examples/nas/textnas/retrain.py"; I met an error above.
How can I solve this problem? Can you give me favor?

**Comment by pkuyym** [comment]
@yongzhuo Hi, could you upload the 'architecture_00.json' file for the reproduction?

**Comment by yongzhuo** [comment]
@pkuyym 
```
{
  "InputChoice10": [
    false,
    false,
    true
  ],
  "InputChoice11": [
    false,
    false,
    true,
    false
  ],
  "InputChoice13": [
    true,
    true,
    false,
    true
  ],
  "InputChoice14": [
    false,
    false,
    false,
    true,
    false
  ],
  "InputChoice16": [
    true,
    false,
    false,
    false,
    false
  ],
  "InputChoice17": [
    false,
    false,
    true,
    false,
    false
  ],
  "InputChoice19": [
    false,
    false,
    false,
    false,
    false,
    true
  ],
  "InputChoice2": [
    true
  ],
  "InputChoice20": [
    false,
    false,
    false,
    false,
    true
  ],
  "InputChoice22": [
    true,
    false,
    false,
    false,
    true,
    false,
    false
  ],
  "InputChoice23": [
    false,
    false,
    false,
    true,
    false
  ],
  "InputChoice25": [
    false,
    false,
    true,
    false,
    true,
    true,
    true,
    false
  ],
  "InputChoice26": [
    false,
    false,
    false,
    true,
    false
  ],
  "InputChoice28": [
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    true,
    false
  ],
  "InputChoice29": [
    false,
    false,
    true,
    false,
    false
  ],
  "InputChoice31": [
    false,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    false
  ],
  "InputChoice32": [
    false,
    false,
    false,
    false,
    true
  ],
  "InputChoice34": [
    false,
    false,
    true,
    true,
    false,
    false,
    true,
    false,
    false,
    true,
    false
  ],
  "InputChoice35": [
    false,
    false,
    false,
    true,
    false
  ],
  "InputChoice37": [
    false,
    false,
    false,
    true,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    false
  ],
  "InputChoice38": [
    false,
    true,
    false,
    false,
    false
  ],
  "InputChoice4": [
    false
  ],
  "InputChoice40": [
    false,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "InputChoice41": [
    false,
    true,
    false,
    false,
    false
  ],
  "InputChoice43": [
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "InputChoice44": [
    false,
    false,
    false,
    false,
    true
  ],
  "InputChoice46": [
    true,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    true
  ],
  "InputChoice47": [
    false,
    true,
    false,
    false,
    false
  ],
  "InputChoice49": [
    false,
    true,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "InputChoice5": [
    true,
    false
  ],
  "InputChoice50": [
    true,
    false,
    false,
    false,
    false
  ],
  "InputChoice52": [
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "InputChoice53": [
    true,
    false,
    false,
    false,
    false
  ],
  "InputChoice55": [
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    true,
    false
  ],
  "InputChoice56": [
    false,
    false,
    true,
    false,
    false
  ],
  "InputChoice58": [
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    false
  ],
  "InputChoice59": [
    false,
    true,
    false,
    false,
    false
  ],
  "InputChoice61": [
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "InputChoice62": [
    false,
    false,
    false,
    false,
    true
  ],
  "InputChoice64": [
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "InputChoice65": [
    false,
    false,
    false,
    false,
    true
  ],
  "InputChoice67": [
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "InputChoice68": [
    true,
    false,
    false,
    false,
    false
  ],
  "InputChoice7": [
    false,
    true
  ],
  "InputChoice70": [
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false
  ],
  "InputChoice8": [
    false,
    true,
    false
  ],
  "LayerChoice1": [
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false
  ],
  "LayerChoice12": [
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false
  ],
  "LayerChoice15": [
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false
  ],
  "LayerChoice18": [
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "LayerChoice21": [
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "LayerChoice24": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice27": [
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true
  ],
  "LayerChoice3": [
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false
  ],
  "LayerChoice30": [
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false
  ],
  "LayerChoice33": [
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false
  ],
  "LayerChoice36": [
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false
  ],
  "LayerChoice39": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice42": [
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "LayerChoice45": [
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true
  ],
  "LayerChoice48": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice51": [
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false
  ],
  "LayerChoice54": [
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true
  ],
  "LayerChoice57": [
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false
  ],
  "LayerChoice6": [
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false
  ],
  "LayerChoice60": [
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false
  ],
  "LayerChoice63": [
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "LayerChoice66": [
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "LayerChoice69": [
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false
  ],
  "LayerChoice9": [
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false
  ]
}
```

**Comment by pkuyym** [comment]
@yongzhuo hi, I tried the architecture you provided by executing `python retrain.py --child_fixed_arc arc/arc_00.json`, where arc_00.json is the architecture you pasted above. However, I didn't reproduce the error, btw the log is as follows: 

```
[07/13/2020, 03:33:22 AM] INFO (nni.textnas) Path output exists. Remove and remake.
[07/13/2020, 03:33:22 AM] INFO (nni.textnas)
--------------------------------------------------------------------------------
attention_keep_prob..........................................................0.8
batch_size...................................................................128
checkpoint_dir...................................................best_checkpoint
child_fixed_arc..................................................arc/arc_01.json
child_grad_bound.............................................................5.0
child_l2_reg...............................................................3e-06
child_lr....................................................................0.02
child_lr_T_0..................................................................10
child_lr_T_mul.................................................................2
child_lr_decay_scheme.....................................................cosine
child_lr_max...............................................................0.002
child_lr_min...............................................................0.001
child_num_layers..............................................................24
child_optim_algo............................................................adam
child_out_filters............................................................256
child_out_filters_scale........................................................1
class_num......................................................................5
cnn_keep_prob................................................................0.8
data_path...................................................................data
embed_keep_prob..............................................................0.8
eval_batch_size..............................................................128
eval_every_epochs..............................................................1
final_output_keep_prob.......................................................1.0
fixed_seed..................................................................True
global_seed.................................................................1234
is_binary..................................................................False
is_cuda.....................................................................True
is_mask.....................................................................True
load_checkpoint............................................................False
log_every.....................................................................50
lstm_out_keep_prob...........................................................0.8
max_input_length..............................................................64
min_count......................................................................1
multi_path.................................................................False
num_epochs....................................................................10
output_dir................................................................output
output_type..................................................................avg
reset_output_dir............................................................True
train_ratio..................................................................1.0
valid_ratio..................................................................1.0
--------------------------------------------------------------------------------
[07/13/2020, 03:33:22 AM] INFO (nni.textnas) set random seed for data reading: 1234
[07/13/2020, 03:33:22 AM] INFO (nni.textnas) Build dataloader
[07/13/2020, 03:33:22 AM] INFO (nni.textnas) Reading SST data...
[07/13/2020, 03:33:27 AM] INFO (nni.textnas) Finish load train phrases.
[07/13/2020, 03:33:28 AM] INFO (nni.textnas) Finish load valid phrases.
[07/13/2020, 03:33:29 AM] INFO (nni.textnas) Finish load test phrases.
[07/13/2020, 03:33:30 AM] INFO (nni.textnas) Finish load train words: 18280.
[07/13/2020, 03:33:30 AM] INFO (nni.textnas) Finish load valid+test words: 21701.
[07/13/2020, 03:33:30 AM] INFO (nni.textnas) After trim vocab length: 21703.
[07/13/2020, 03:33:30 AM] INFO (nni.textnas) Loading embedding...
[07/13/2020, 03:33:30 AM] INFO (nni.textnas) Finish initialize word embedding.
[07/13/2020, 03:33:35 AM] INFO (nni.textnas) Loaded 327126 training samples.
[07/13/2020, 03:33:36 AM] INFO (nni.textnas) Loaded 42548 validation samples.
[07/13/2020, 03:33:36 AM] INFO (nni.textnas) Loaded 2210 test samples.
[07/13/2020, 03:33:36 AM] INFO (nni.textnas) Build model
[07/13/2020, 03:33:36 AM] INFO (nni.textnas) num layers: 24
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.0.op with candidate number 2.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.1.op with candidate number 2.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.2.op with candidate number 5.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.3.op with candidate number 2.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.4.op with candidate number 4.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.5.op with candidate number 6.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.6.op with candidate number 1.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.7.op with candidate number 0.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.8.op with candidate number 3.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.9.op with candidate number 7.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.10.op with candidate number 2.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.11.op with candidate number 5.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.12.op with candidate number 4.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.13.op with candidate number 3.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.14.op with candidate number 1.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.15.op with candidate number 7.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.16.op with candidate number 3.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.17.op with candidate number 4.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.18.op with candidate number 7.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.19.op with candidate number 3.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.20.op with candidate number 4.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.21.op with candidate number 1.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.22.op with candidate number 1.
[07/13/2020, 03:33:36 AM] INFO (nni.nas.pytorch.fixed) Replacing layers.23.op with candidate number 4.
[07/13/2020, 03:33:36 AM] INFO (nni.textnas) Finish build model
[07/13/2020, 03:33:36 AM] INFO (nni.textnas) Model has 11992913 params
[07/13/2020, 03:33:39 AM] INFO (nni.textnas) Start training
[07/13/2020, 03:33:48 AM] INFO (nni.textnas) epoch=0     ch_step=50     loss=0.958259 lr=0.0020   |g|=3.1824   tr_acc=84 /128 mins=0.16
[07/13/2020, 03:33:58 AM] INFO (nni.textnas) epoch=0     ch_step=100    loss=0.837673 lr=0.0020   |g|=4.0137   tr_acc=82 /128 mins=0.32
[07/13/2020, 03:34:08 AM] INFO (nni.textnas) epoch=0     ch_step=150    loss=0.838366 lr=0.0020   |g|=4.4499   tr_acc=85 /128 mins=0.48
[07/13/2020, 03:34:17 AM] INFO (nni.textnas) epoch=0     ch_step=200    loss=0.897538 lr=0.0020   |g|=3.3077   tr_acc=86 /128 mins=0.64
[07/13/2020, 03:34:27 AM] INFO (nni.textnas) epoch=0     ch_step=250    loss=0.838138 lr=0.0020   |g|=2.3970   tr_acc=85 /128 mins=0.80
[07/13/2020, 03:34:37 AM] INFO (nni.textnas) epoch=0     ch_step=300    loss=0.827482 lr=0.0020   |g|=4.7255   tr_acc=86 /128 mins=0.97
[07/13/2020, 03:34:46 AM] INFO (nni.textnas) epoch=0     ch_step=350    loss=0.604737 lr=0.0020   |g|=3.0094   tr_acc=99 /128 mins=1.13
[07/13/2020, 03:34:56 AM] INFO (nni.textnas) epoch=0     ch_step=400    loss=0.707767 lr=0.0020   |g|=2.7852   tr_acc=96 /128 mins=1.29
[07/13/2020, 03:35:06 AM] INFO (nni.textnas) epoch=0     ch_step=450    loss=0.711635 lr=0.0020   |g|=2.4690   tr_acc=95 /128 mins=1.45
[07/13/2020, 03:35:16 AM] INFO (nni.textnas) epoch=0     ch_step=500    loss=0.679852 lr=0.0020   |g|=1.8701   tr_acc=94 /128 mins=1.62
[07/13/2020, 03:35:25 AM] INFO (nni.textnas) epoch=0     ch_step=550    loss=0.709413 lr=0.0020   |g|=2.8134   tr_acc=86 /128 mins=1.78
```

**Comment by yongzhuo** [comment]
thanks, I will try again.

**Comment by yongzhuo** [comment]
every thing is ok.
