### ISSUE TITLE
[NNI Pai Mode] No module named nni_trial_tool.trial_runner

### ISSUE THREAD

**Issue by colorjam** [microsoft/nni#2680]
**Environment**:
- NNI version: 1.6
- NNI mode (local|remote|pai): pai
- Client OS:
- Server OS (for remote mode only):
- Python version: 3.7
- PyTorch/TensorFlow version: 1.4.0
- Is conda/virtualenv/venv used?:
- Is running in Docker?: yes

**Log message**:
 - nnimanager.log: 
[nnimanager.log](https://github.com/microsoft/nni/files/4906546/nnimanager.log)
 - dispatcher.log:

 - nnictl stdout and stderr:
`nnictl log stdout:`
`
 (node:14304) ExperimentalWarning: The fs.promises API is experimental
{ Error: error on request environment nni_exp_LDdR0vsv_env_BDb8m, please check log for more details.
    at TrialDispatcher.requestEnvironment (/home/v-chenqy/miniconda3/envs/py37/nni/training_service/reusable/trialDispatcher.js:381:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: '',
  cause:
   Error: error on request environment nni_exp_LDdR0vsv_env_BDb8m, please check log for more details.
       at TrialDispatcher.requestEnvironment (/home/v-chenqy/miniconda3/envs/py37/nni/training_service/reusable/trialDispatcher.js:381:19)
       at process._tickCallback (internal/process/next_tick.js:68:7) }
`

**What issue meet, what's expected?**:
 NNI pai mode can start an experiment. But the pai stderr shows:
`/usr/bin/python3: No module named nni_trial_tool.trial_runner`

**How to reproduce it?**: 

**Additional information**:
The experiment shows error while the trials are waiting
![image](https://user-images.githubusercontent.com/23700012/87221123-42211400-c39c-11ea-87de-afbeb545b538.png)

![image](https://user-images.githubusercontent.com/23700012/87221168-7694d000-c39c-11ea-8893-7e1af2f8cf85.png)

**Comment by colorjam** [comment]
update nni in docker to the latest version can solve this problem. 
close the issue.
