### ISSUE TITLE
TextNAS ERROR:  RuntimeError: Unexpected keys found in fixed architecture: {'InputChoice10', 'InputChoice13'......

### ISSUE THREAD

**Issue by yongzhuo** [microsoft/nni#2726]
**Environment**:
- NNI version:  1.5
- NNI mode (local|remote|pai): local
- Client OS: win10
- Server OS (for remote mode only):
- Python version: 3.6
- PyTorch/TensorFlow version: pytorch==1.5
- Is conda/virtualenv/venv used?:conda
- Is running in Docker?:no

**Log message**:
```
Traceback (most recent call last):
  File "nni/nas/textnas/trainer.py", line 71, in <module>
    tra.trainer()
  File "nni/nas/textnas/trainer.py", line 64, in trainer
    self.best_acc_global = tnr.fit()
  File "nni\nas\textnas\retrain.py", line 322, in fit
    self.best_acc_global = self.train(self.device, self.config.child_num_layers)
  File "nni\nas\textnas\retrain.py", line 199, in train
    child_model = self.create_model_from_architecture(embedding=torch.tensor(embedding).float(), num_layers=num_layers)
  File "nni\nas\textnas\retrain.py", line 72, in create_model_from_architecture
    apply_fixed_architecture(child_model, self.config.child_fixed_arc)
  File "nni\nas\pytorch\fixed.py", line 81, in apply_fixed_architecture
    architecture = FixedArchitecture(model, fixed_arc)
  File "nni\nas\pytorch\fixed.py", line 39, in __init__
    raise RuntimeError("Unexpected keys found in fixed architecture: {}.".format(fixed_arc_keys - mutable_keys))
RuntimeError: Unexpected keys found in fixed architecture: {'InputChoice40', 'InputChoice35', 'InputChoice26', 'InputChoice59', 'LayerChoice24', 'LayerChoice18', 'InputChoice43', 'LayerChoice1', 'LayerChoice66', 'InputChoice2', 'LayerChoice30', 'InputChoice53', 'InputChoice50', 'LayerChoice33', 'LayerChoice36', 'InputChoice13', 'InputChoice68', 'InputChoice11', 'LayerChoice45', 'LayerChoice21', 'LayerChoice60', 'LayerChoice3', 'LayerChoice51', 'InputChoice55', 'InputChoice17', 'InputChoice52', 'LayerChoice57', 'InputChoice28', 'LayerChoice48', 'InputChoice37', 'InputChoice14', 'InputChoice46', 'InputChoice58', 'LayerChoice6', 'InputChoice49', 'InputChoice32', 'InputChoice38', 'LayerChoice9', 'InputChoice5', 'InputChoice70', 'InputChoice31', 'InputChoice41', 'LayerChoice42', 'InputChoice16', 'InputChoice56', 'InputChoice19', 'InputChoice47', 'LayerChoice69', 'InputChoice10', 'InputChoice62', 'InputChoice7', 'InputChoice23', 'InputChoice25', 'InputChoice20', 'LayerChoice54', 'InputChoice61', 'LayerChoice27', 'LayerChoice39', 'InputChoice22', 'InputChoice4', 'InputChoice8', 'LayerChoice15', 'InputChoice34', 'LayerChoice63', 'InputChoice29', 'InputChoice64', 'InputChoice65', 'InputChoice67', 'LayerChoice12', 'InputChoice44'}.

```

** Where can you find the log files**: 
        no

**What issue meet, what's expected?**:
       no

**How to reproduce it?**: 
When I run “python examples/nas/textnas/search.py” ,soon after I get 20 child_fixed_arc, then I get all child_fixed_arc in "checkpoints" and run all;  the first is true, but when I get the file of "checkpoints/architecture_01.json", I met an error above.
How can I solve this problem? Can you give me favor?
       my main code is:
 ```       
        self.best_acc_global = 0
        path_architectures = get_all_dirs_files(self.config.architectures_dir)
        for pa in path_architectures:
            if ".json" in pa:
                tnr = TextNasRetrain(params_retrain)
                tnr.config.child_fixed_arc = pa
                tnr.best_acc_global = self.best_acc_global
                self.best_acc_global = tnr.fit()
                # del tnr
                # gc.collect()
 ```
       
when I debug, the error  occurs in "nni.nas.pytorch.fixed.apply_fixed_architecture", the class of "FixedArchitecture", "mutable_keys" and "fixed_arc_keys" are not same. I donot know why the second mutable_keys changes.

the first architecture of "architecture_00.json" in FixedArchitecture:
```
mutable_keys: ['InputChoice10', 'InputChoice11', 'InputChoice13', 'InputChoice14', 'InputChoice16', 'InputChoice17', 'InputChoice19', 'InputChoice2', 'InputChoice20', 'InputChoice22', 'InputChoice23', 'InputChoice25', 'InputChoice26', 'InputChoice28', 'InputChoice29', 'InputChoice31', 'InputChoice32', 'InputChoice34', 'InputChoice35', 'InputChoice37', 'InputChoice38', 'InputChoice4', 'InputChoice40', 'InputChoice41', 'InputChoice43', 'InputChoice44', 'InputChoice46', 'InputChoice47', 'InputChoice49', 'InputChoice5', 'InputChoice50', 'InputChoice52', 'InputChoice53', 'InputChoice55', 'InputChoice56', 'InputChoice58', 'InputChoice59', 'InputChoice61', 'InputChoice62', 'InputChoice64', 'InputChoice65', 'InputChoice67', 'InputChoice68', 'InputChoice7', 'InputChoice70', 'InputChoice8', 'LayerChoice1', 'LayerChoice12', 'LayerChoice15', 'LayerChoice18', 'LayerChoice21', 'LayerChoice24', 'LayerChoice27', 'LayerChoice3', 'LayerChoice30', 'LayerChoice33', 'LayerChoice36', 'LayerChoice39', 'LayerChoice42', 'LayerChoice45', 'LayerChoice48', 'LayerChoice51', 'LayerChoice54', 'LayerChoice57', 'LayerChoice6', 'LayerChoice60', 'LayerChoice63', 'LayerChoice66', 'LayerChoice69', 'LayerChoice9']

fixed_arc_keys: ['InputChoice10', 'InputChoice11', 'InputChoice13', 'InputChoice14', 'InputChoice16', 'InputChoice17', 'InputChoice19', 'InputChoice2', 'InputChoice20', 'InputChoice22', 'InputChoice23', 'InputChoice25', 'InputChoice26', 'InputChoice28', 'InputChoice29', 'InputChoice31', 'InputChoice32', 'InputChoice34', 'InputChoice35', 'InputChoice37', 'InputChoice38', 'InputChoice4', 'InputChoice40', 'InputChoice41', 'InputChoice43', 'InputChoice44', 'InputChoice46', 'InputChoice47', 'InputChoice49', 'InputChoice5', 'InputChoice50', 'InputChoice52', 'InputChoice53', 'InputChoice55', 'InputChoice56', 'InputChoice58', 'InputChoice59', 'InputChoice61', 'InputChoice62', 'InputChoice64', 'InputChoice65', 'InputChoice67', 'InputChoice68', 'InputChoice7', 'InputChoice70', 'InputChoice8', 'LayerChoice1', 'LayerChoice12', 'LayerChoice15', 'LayerChoice18', 'LayerChoice21', 'LayerChoice24', 'LayerChoice27', 'LayerChoice3', 'LayerChoice30', 'LayerChoice33', 'LayerChoice36', 'LayerChoice39', 'LayerChoice42', 'LayerChoice45', 'LayerChoice48', 'LayerChoice51', 'LayerChoice54', 'LayerChoice57', 'LayerChoice6', 'LayerChoice60', 'LayerChoice63', 'LayerChoice66', 'LayerChoice69', 'LayerChoice9']
 ```

the second architecture of "architecture_01.json" in FixedArchitecture:

```
mutable_keys: ['InputChoice101', 'InputChoice102', 'InputChoice104', 'InputChoice105', 'InputChoice107', 'InputChoice108', 'InputChoice110', 'InputChoice111', 'InputChoice113', 'InputChoice114', 'InputChoice116', 'InputChoice117', 'InputChoice119', 'InputChoice120', 'InputChoice122', 'InputChoice123', 'InputChoice125', 'InputChoice126', 'InputChoice128', 'InputChoice129', 'InputChoice131', 'InputChoice132', 'InputChoice134', 'InputChoice135', 'InputChoice137', 'InputChoice138', 'InputChoice140', 'InputChoice72', 'InputChoice74', 'InputChoice75', 'InputChoice77', 'InputChoice78', 'InputChoice80', 'InputChoice81', 'InputChoice83', 'InputChoice84', 'InputChoice86', 'InputChoice87', 'InputChoice89', 'InputChoice90', 'InputChoice92', 'InputChoice93', 'InputChoice95', 'InputChoice96', 'InputChoice98', 'InputChoice99', 'LayerChoice100', 'LayerChoice103', 'LayerChoice106', 'LayerChoice109', 'LayerChoice112', 'LayerChoice115', 'LayerChoice118', 'LayerChoice121', 'LayerChoice124', 'LayerChoice127', 'LayerChoice130', 'LayerChoice133', 'LayerChoice136', 'LayerChoice139', 'LayerChoice71', 'LayerChoice73', 'LayerChoice76', 'LayerChoice79', 'LayerChoice82', 'LayerChoice85', 'LayerChoice88', 'LayerChoice91', 'LayerChoice94', 'LayerChoice97']


fixed_arc_keys: ['InputChoice10', 'InputChoice11', 'InputChoice13', 'InputChoice14', 'InputChoice16', 'InputChoice17', 'InputChoice19', 'InputChoice2', 'InputChoice20', 'InputChoice22', 'InputChoice23', 'InputChoice25', 'InputChoice26', 'InputChoice28', 'InputChoice29', 'InputChoice31', 'InputChoice32', 'InputChoice34', 'InputChoice35', 'InputChoice37', 'InputChoice38', 'InputChoice4', 'InputChoice40', 'InputChoice41', 'InputChoice43', 'InputChoice44', 'InputChoice46', 'InputChoice47', 'InputChoice49', 'InputChoice5', 'InputChoice50', 'InputChoice52', 'InputChoice53', 'InputChoice55', 'InputChoice56', 'InputChoice58', 'InputChoice59', 'InputChoice61', 'InputChoice62', 'InputChoice64', 'InputChoice65', 'InputChoice67', 'InputChoice68', 'InputChoice7', 'InputChoice70', 'InputChoice8', 'LayerChoice1', 'LayerChoice12', 'LayerChoice15', 'LayerChoice18', 'LayerChoice21', 'LayerChoice24', 'LayerChoice27', 'LayerChoice3', 'LayerChoice30', 'LayerChoice33', 'LayerChoice36', 'LayerChoice39', 'LayerChoice42', 'LayerChoice45', 'LayerChoice48', 'LayerChoice51', 'LayerChoice54', 'LayerChoice57', 'LayerChoice6', 'LayerChoice60', 'LayerChoice63', 'LayerChoice66', 'LayerChoice69', 'LayerChoice9']

 ```

**Comment by ultmaster** [comment]
Hi there. Thanks for raising this issue.

It's currently a known issue in NNI (and that's why we encourage users to specify their own keys to LayerChoice and InputChoice rather than use auto-generated keys). To workaround, make sure to call `nni.nas.pytorch.utils._reset_global_mutable_counting()` each time you instantiate a new model. This will force the LayerChoice and InputChoice to re-count from 0.

**Comment by yongzhuo** [comment]
thanks, I will make a try.
