### ISSUE TITLE
Install error: DEPRECATION: Could not build wheels for scikit-learn which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these

### ISSUE THREAD

**Issue by Orocker** [microsoft/nni#2784]
**Environment**:
- NNI version:（master） 999.0.0-developing
- NNI mode (local|remote|pai):local
- Client OS:Centos 7
- Server OS (for remote mode only):
- Python version:3.8.0 (5.1.9-1.el7.elrepo.x86_64)
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:No
- Is running in Docker?:No
-/usr/local/bin/pip --version : `pip 20.2.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)` 

**Log message**:
 - nnimanager.log: No
 - dispatcher.log:No
 - nnictl stdout and stderr:
``` 
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.8/site-packages (from networkx->hyperopt==0.1.2->nni==0.0.0) (4.4.2)
Building wheels for collected packages: nni, scikit-learn
  Building wheel for nni (setup.py) ... done
  Created wheel for nni: filename=nni-0.0.0-py3-none-any.whl size=420966 sha256=5caeebf88638b284027f6006eaebc9edf30e7ea4d816c1d8eed37c2e811e41bf
  Stored in directory: /tmp/pip-ephem-wheel-cache-fmfm_fhe/wheels/d5/3b/a7/4443ae744f4dc4ecb1c673999276273842a446bf8128b2d971
  Building wheel for scikit-learn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4ml03yc9/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4ml03yc9/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-kja3d5dd
       cwd: /tmp/pip-install-4ml03yc9/scikit-learn/
  Complete output (28 lines):
  Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-4ml03yc9/scikit-learn/setup.py", line 290, in <module>
      setup_package()
    File "/tmp/pip-install-4ml03yc9/scikit-learn/setup.py", line 286, in setup_package
      setup(**metadata)
    File "/usr/local/lib/python3.8/site-packages/numpy/distutils/core.py", line 135, in setup
      config = configuration()
    File "/tmp/pip-install-4ml03yc9/scikit-learn/setup.py", line 174, in configuration
      config.add_subpackage('sklearn')
    File "/usr/local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1018, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/usr/local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 984, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/usr/local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "sklearn/setup.py", line 62, in configuration
      config.add_subpackage('utils')
    File "/usr/local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1018, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/usr/local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 984, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/usr/local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "sklearn/utils/setup.py", line 8, in configuration
      from Cython import Tempita
  ModuleNotFoundError: No module named 'Cython'
  ----------------------------------------
  ERROR: Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Successfully built nni
Failed to build scikit-learn
DEPRECATION: Could not build wheels for scikit-learn which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: scikit-learn, nni
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.23.2
    Uninstalling scikit-learn-0.23.2:
      Successfully uninstalled scikit-learn-0.23.2
    Running setup.py install for scikit-learn ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4ml03yc9/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4ml03yc9/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sycfr0an/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/scikit-learn
         cwd: /tmp/pip-install-4ml03yc9/scikit-learn/
    Complete output (28 lines):
    Partial import of sklearn during the build process.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4ml03yc9/scikit-learn/setup.py", line 290, in <module>
        setup_package()
      File "/tmp/pip-install-4ml03yc9/scikit-learn/setup.py", line 286, in setup_package
        setup(**metadata)
      File "/usr/local/lib/python3.8/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-install-4ml03yc9/scikit-learn/setup.py", line 174, in configuration
        config.add_subpackage('sklearn')
      File "/usr/local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1018, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/usr/local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 984, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/usr/local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/setup.py", line 62, in configuration
        config.add_subpackage('utils')
      File "/usr/local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 1018, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/usr/local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 984, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/usr/local/lib/python3.8/site-packages/numpy/distutils/misc_util.py", line 926, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "sklearn/utils/setup.py", line 8, in configuration
        from Cython import Tempita
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
  Rolling back uninstall of scikit-learn
  Moving to /usr/local/lib/python3.8/site-packages/scikit_learn-0.23.2.dist-info/
   from /usr/local/lib/python3.8/site-packages/~cikit_learn-0.23.2.dist-info
  Moving to /usr/local/lib/python3.8/site-packages/scikit_learn.libs/
   from /usr/local/lib/python3.8/site-packages/~cikit_learn.libs
  Moving to /usr/local/lib/python3.8/site-packages/sklearn/
   from /usr/local/lib/python3.8/site-packages/~klearn
ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4ml03yc9/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4ml03yc9/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sycfr0an/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/scikit-learn Check the logs for full command output.
make: *** [install-python-modules] Error 1


```
 

**What issue meet, what's expected?**:

**How to reproduce it?**: 

**Additional information**:

**Comment by chicm-ms** [comment]
Hi @Orocker ,
Thanks for reporting this issue, can you install scikit-learn successfully?
How did you install nni ( what command did you run exactly) ?

I tried with python 3.8.0 on my ubuntu system, I can install scikit-learn 0.23.2 and nni successfully.

**Comment by Orocker** [comment]
> Hi @Orocker ,
> Thanks for reporting this issue, can you install scikit-learn successfully?
> How did you install nni ( what command did you run exactly) ?
> 
> I tried with python 3.8.0 on my ubuntu system, I can install scikit-learn 0.23.2 and nni successfully.

I got the same error using pip and source code installation

**Comment by chicm-ms** [comment]
Looks like scikit-learn (which is a dependency of nni) install failed on your system.
Would you please check whether you can install scikit-learn directly?

**Comment by Orocker** [comment]
> Looks like scikit-learn (which is a dependency of nni) install failed on your system.
> Would you please check whether you can install scikit-learn alone?

I have tried this method yesterday，the command is `python3 -m pip  install --index https://pypi.mirrors.ustc.edu.cn/simple scikit-learn`, And it shows that the installation is successful.Now I have downgrade the python version to 3.7, ready to try again

**Comment by Orocker** [comment]
I have installed it with pip. `python3 -m pip install --upgrade nni`
