### ISSUE TITLE
AML mode running issue with mnist-pytorch

### ISSUE THREAD

**Issue by JunweiSUN** [microsoft/nni#2831]
When running the mnist-pytorch example on aml mode, the trial will fail and the error message is:
```
frame #37: python3() [0x634dd2]
frame #42: __libc_start_main + 0xe7 (0x7ff1d866ab97 in /lib/x86_64-linux-gnu/libc.so.6)
Traceback (most recent call last):
  File "mnist.py", line 135, in <module>
    main(params)
  File "mnist.py", line 83, in main
    .ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])),
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py", line 80, in __init__
    self.data, self.targets = torch.load(os.path.join(self.processed_folder, data_file))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
```
Seems like the pytorch version in the image caused this issue. However, if I pull this image to my local machine and run in local mode, it seems normal. The docker image is `nnidev/nni-test:v1.8.2008140305`
The mnist-tfv1 example can run normally.

**Comment by Lijiaoa** [comment]
Hi, @JunweiSUN 
Has this issue been resolved please?

**Comment by JunweiSUN** [comment]
Seems like an out-of-date issue ... The docker image of nni should have been updated and this issue should not occur again. Close this issue for now.
