### ISSUE TITLE
remote mode

### ISSUE THREAD

**Issue by Jie-Yuan** [microsoft/nni#2851]
!nnictl log stderr
-----------------------------------------------------------------------
                Experiment start time 2020-09-01 11:26:39
-----------------------------------------------------------------------
{ Error: Timed out while waiting for handshake
    at Client.sshClient.on.on (/usr/local/nni/training_service/remote_machine/shellExecutor.js:74:29)
    at Client.emit (events.js:182:13)
    at Timeout._onTimeout (/usr/local/nni/node_modules/ssh2/lib/client.js:697:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: '',
  cause:
   Error: Timed out while waiting for handshake
       at Client.sshClient.on.on (/usr/local/nni/training_service/remote_machine/shellExecutor.js:74:29)
       at Client.emit (events.js:182:13)
       at Timeout._onTimeout (/usr/local/nni/node_modules/ssh2/lib/client.js:697:14)
       at ontimeout (timers.js:436:11)
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10)

**Comment by scarlett2018** [comment]
@Jie-Yuan - which version are you using?

**Comment by Jie-Yuan** [comment]
> @Jie-Yuan - which version are you using?

1.8

**Comment by SparkSnail** [comment]
@Jie-Yuan Could you please provide more information about the experiment? Is experiment running in remote mode? When did the experiment throw the exception?  Does nniManagr.log has any error message?

**Comment by kvartet** [comment]
> @Jie-Yuan Could you please provide more information about the experiment? When did the experiment throw the exception? Does nniManagr.log has any error message? Did you tried using `ssh` command to connect the remote machine directly?

@Jie-Yuan Any updates? Thank you.
