### ISSUE TITLE
1.8 error

### ISSUE THREAD

**Issue by Jie-Yuan** [microsoft/nni#2860]
[9/3/2020, 1:39:46 PM] ERROR [ 'copyFileToRemote(917): Error: Unexpected packet before version' ]

[9/3/2020, 1:39:46 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"num_leaves": 26, "bagging_freq": 4, "min_child_samples": 89, "learning_rate": 0.07, "bagging_fraction": 0.5300358277035984, "feature_fraction": 0.8288285262608374, "lambda_l1": 4.216681308341677, "lambda_l2": 3.476772324906062e-08, "min_split_gain": 0.7402732208566103, "min_child_weight": 0.6096687763710968}, "parameter_index": 0}' ]

[9/3/2020, 1:39:51 PM] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"num_leaves\\": 26, \\"bagging_freq\\": 4, \\"min_child_samples\\": 89, \\"learning_rate\\": 0.07, \\"bagging_fraction\\": 0.5300358277035984, \\"feature_fraction\\": 0.8288285262608374, \\"lambda_l1\\": 4.216681308341677, \\"lambda_l2\\": 3.476772324906062e-08, \\"min_split_gain\\": 0.7402732208566103, \\"min_child_weight\\": 0.6096687763710968}, \\"parameter_index\\": 0}","index":0}}' ]

[9/3/2020, 1:39:52 PM] ERROR [ 'Error: Unexpected packet before version\n    at SFTPStream._transform (/usr/local/nni/node_modules/ssh2-streams/lib/sftp.js:306:27)\n    at SFTPStream.Transform._read (_stream_transform.js:190:10)\n    at SFTPStream._read (/usr/local/nni/node_modules/ssh2-streams/lib/sftp.js:183:15)\n    at SFTPStream.Transform._write (_stream_transform.js:178:12)\n    at doWrite (_stream_writable.js:410:12)\n    at writeOrBuffer (_stream_writable.js:394:5)\n    at SFTPStream.Writable.write (_stream_writable.js:294:11)\n    at Channel.ondata (_stream_readable.js:666:20)\n    at Channel.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)' ]

**Comment by JunweiSUN** [comment]
Hi @Jie-Yuan , could you please provide more detailed information? Like the training platform, your OS, when this error happened, etc.

**Comment by kvartet** [comment]
@Jie-Yuan I’m closing this issue as it has no updates from user for 3 months, please feel free to reopen if you are still seeing it an active issue.
