### ISSUE TITLE
cuda runtime error (38) : no CUDA-capable device is detected at ..\aten\src\THC\THCGeneral.cpp:50

### ISSUE THREAD

**Issue by Yggdrasilshh** [microsoft/nni#2916]
**Environment**:
- NNI version:1.7.1
- NNI mode (local|remote|pai):local
- Client OS: Windows 10
- Server OS (for remote mode only):
- Python version: 3.7
- PyTorch/TensorFlow version: Pytorch 1.2.1
- Is conda/virtualenv/venv used?: Yes
- Is running in Docker?: No

**Log message**:
 - nnimanager.log: 
[2020-9-22 15:10:28] INFO [ 'Datastore initialization done' ]
[2020-9-22 15:10:28] INFO [ 'RestServer start' ]
[2020-9-22 15:10:28] INFO [ 'Construct local machine training service.' ]
[2020-9-22 15:10:28] INFO [ 'RestServer base port is 8080' ]
[2020-9-22 15:10:28] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[2020-9-22 15:10:31] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python main.py","codeDir":"D:\\\\Desktop\\\\COVID-19andLSTM\\\\program\\\\COVID19-LSTM+nni\\\\.","gpuNum":0}' ]
[2020-9-22 15:10:31] INFO [ 'required GPU number is 0' ]
[2020-9-22 15:10:33] INFO [ 'Starting experiment: NClmy6tw' ]
[2020-9-22 15:10:33] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[2020-9-22 15:10:33] INFO [ 'Add event listeners' ]
[2020-9-22 15:10:33] INFO [ 'Run local machine training service.' ]
[2020-9-22 15:10:34] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[2020-9-22 15:10:34] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"learning_rate": 0.064917987188779, "hidden_size": 256, "hidden_size_linear1": 128, "hidden_size_linear2": 128, "lstm_layers": 1, "epochs": 10, "dropout_rate": 0.23914751122609257}, "parameter_index": 0}' ]
[2020-9-22 15:10:38] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"learning_rate\\": 0.064917987188779, \\"hidden_size\\": 256, \\"hidden_size_linear1\\": 128, \\"hidden_size_linear2\\": 128, \\"lstm_layers\\": 1, \\"epochs\\": 10, \\"dropout_rate\\": 0.23914751122609257}, \\"parameter_index\\": 0}","index":0}}' ]
[2020-9-22 15:10:48] INFO [ 'Trial job v2EVw status changed from WAITING to FAILED' ]
[2020-9-22 15:10:48] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"learning_rate": 0.07791436808228155, "hidden_size": 256, "hidden_size_linear1": 1280, "hidden_size_linear2": 64, "lstm_layers": 2, "epochs": 10, "dropout_rate": 0.737187742981508}, "parameter_index": 0}' ]
[2020-9-22 15:10:53] INFO [ 'submitTrialJob: form: {"sequenceId":1,"hyperParameters":{"value":"{\\"parameter_id\\": 1, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"learning_rate\\": 0.07791436808228155, \\"hidden_size\\": 256, \\"hidden_size_linear1\\": 1280, \\"hidden_size_linear2\\": 64, \\"lstm_layers\\": 2, \\"epochs\\": 10, \\"dropout_rate\\": 0.737187742981508}, \\"parameter_index\\": 0}","index":0}}' ]
[2020-9-22 15:10:59] INFO [ 'Trial job pYa1T status changed from WAITING to FAILED' ]
[2020-9-22 15:10:59] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 2, "parameter_source": "algorithm", "parameters": {"learning_rate": 0.02861150528153203, "hidden_size": 128, "hidden_size_linear1": 128, "hidden_size_linear2": 128, "lstm_layers": 2, "epochs": 10, "dropout_rate": 0.8934782480878113}, "parameter_index": 0}' ]
[2020-9-22 15:11:04] INFO [ 'submitTrialJob: form: {"sequenceId":2,"hyperParameters":{"value":"{\\"parameter_id\\": 2, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"learning_rate\\": 0.02861150528153203, \\"hidden_size\\": 128, \\"hidden_size_linear1\\": 128, \\"hidden_size_linear2\\": 128, \\"lstm_layers\\": 2, \\"epochs\\": 10, \\"dropout_rate\\": 0.8934782480878113}, \\"parameter_index\\": 0}","index":0}}' ]
[2020-9-22 15:11:09] INFO [ 'Trial job AWxL9 status changed from WAITING to FAILED' ]
[2020-9-22 15:11:09] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 3, "parameter_source": "algorithm", "parameters": {"learning_rate": 0.08745856725458606, "hidden_size": 64, "hidden_size_linear1": 64, "hidden_size_linear2": 32, "lstm_layers": 1, "epochs": 10, "dropout_rate": 0.30960622874884475}, "parameter_index": 0}' ]
[2020-9-22 15:11:14] INFO [ 'submitTrialJob: form: {"sequenceId":3,"hyperParameters":{"value":"{\\"parameter_id\\": 3, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"learning_rate\\": 0.08745856725458606, \\"hidden_size\\": 64, \\"hidden_size_linear1\\": 64, \\"hidden_size_linear2\\": 32, \\"lstm_layers\\": 1, \\"epochs\\": 10, \\"dropout_rate\\": 0.30960622874884475}, \\"parameter_index\\": 0}","index":0}}' ]
[2020-9-22 15:11:19] INFO [ 'Trial job xMbXB status changed from WAITING to FAILED' ]
[2020-9-22 15:11:19] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 4, "parameter_source": "algorithm", "parameters": {"learning_rate": 0.07183954594775774, "hidden_size": 128, "hidden_size_linear1": 512, "hidden_size_linear2": 64, "lstm_layers": 2, "epochs": 10, "dropout_rate": 0.6915165315313325}, "parameter_index": 0}' ]
[2020-9-22 15:11:24] INFO [ 'submitTrialJob: form: {"sequenceId":4,"hyperParameters":{"value":"{\\"parameter_id\\": 4, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"learning_rate\\": 0.07183954594775774, \\"hidden_size\\": 128, \\"hidden_size_linear1\\": 512, \\"hidden_size_linear2\\": 64, \\"lstm_layers\\": 2, \\"epochs\\": 10, \\"dropout_rate\\": 0.6915165315313325}, \\"parameter_index\\": 0}","index":0}}' ]
[2020-9-22 15:11:29] INFO [ 'Trial job sfruj status changed from WAITING to RUNNING' ]
[2020-9-22 15:11:35] INFO [ 'Trial job sfruj status changed from RUNNING to FAILED' ]
[2020-9-22 15:11:35] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 5, "parameter_source": "algorithm", "parameters": {"learning_rate": 0.05729026933978657, "hidden_size": 256, "hidden_size_linear1": 1024, "hidden_size_linear2": 256, "lstm_layers": 1, "epochs": 10000, "dropout_rate": 0.8743344280752859}, "parameter_index": 0}' ]
[2020-9-22 15:11:40] INFO [ 'submitTrialJob: form: {"sequenceId":5,"hyperParameters":{"value":"{\\"parameter_id\\": 5, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"learning_rate\\": 0.05729026933978657, \\"hidden_size\\": 256, \\"hidden_size_linear1\\": 1024, \\"hidden_size_linear2\\": 256, \\"lstm_layers\\": 1, \\"epochs\\": 10000, \\"dropout_rate\\": 0.8743344280752859}, \\"parameter_index\\": 0}","index":0}}' ]
[2020-9-22 15:11:45] INFO [ 'Trial job rnNvl status changed from WAITING to RUNNING' ]
[2020-9-22 15:11:50] INFO [ 'Trial job rnNvl status changed from RUNNING to FAILED' ]
[2020-9-22 15:11:50] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 6, "parameter_source": "algorithm", "parameters": {"learning_rate": 0.0753235271051405, "hidden_size": 256, "hidden_size_linear1": 1280, "hidden_size_linear2": 128, "lstm_layers": 1, "epochs": 10, "dropout_rate": 0.5414426288534424}, "parameter_index": 0}' ]
[2020-9-22 15:11:50] INFO [ 'Change NNIManager status from: RUNNING to: STOPPING' ]
[2020-9-22 15:11:50] INFO [ 'Stopping experiment, cleaning up ...' ]
[2020-9-22 15:11:53] INFO [ 'Stopping local machine training service...' ]
 - dispatcher.log:
[09/22/2020, 03:10:34 PM] INFO (hyperopt.utils/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[09/22/2020, 03:10:34 PM] INFO (hyperopt.fmin/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[09/22/2020, 03:10:34 PM] INFO (nni.msg_dispatcher_base/MainThread) Start dispatcher
[09/22/2020, 03:10:34 PM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001000 seconds
[09/22/2020, 03:10:34 PM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[09/22/2020, 03:10:48 PM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000996 seconds
[09/22/2020, 03:10:48 PM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[09/22/2020, 03:10:59 PM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002072 seconds
[09/22/2020, 03:10:59 PM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[09/22/2020, 03:11:09 PM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001995 seconds
[09/22/2020, 03:11:09 PM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[09/22/2020, 03:11:19 PM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002036 seconds
[09/22/2020, 03:11:19 PM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[09/22/2020, 03:11:35 PM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001994 seconds
[09/22/2020, 03:11:35 PM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[09/22/2020, 03:11:50 PM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001994 seconds
[09/22/2020, 03:11:50 PM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[09/22/2020, 03:11:50 PM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...

 - nnictl stdout and stderr:
 cmd.exe : THCudaCheck FAIL file=..\aten\src\THC\THCGeneral.cpp line=50 error=38 : no CUDA-capable device is detected
所在位置 C:\Users\86156\nni\experiments\NClmy6tw\trials\AWxL9\run.ps1:11 字符: 1
+ cmd.exe /c python main.py 2>"C:\Users\86156\nni\experiments\NClmy6tw\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (THCudaCheck FAI...ice is detected:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Traceback (most recent call last):
  File "main.py", line 169, in <module>
    main(params,con)
  File "main.py", line 156, in main
    train(args,config,[data_gainer.train_x, data_gainer.train_y, data_gainer.valid_x, data_gainer.valid_y],data_gainer.
std,data_gainer.mean,logger)
  File "D:\Desktop\COVID-19andLSTM\program\COVID19-LSTM+nni\LSTMModelPytorch.py", line 67, in train
    model=Net(arg,config).to(device)
  File "D:\Application\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 432, in to
    return self._apply(convert)
  File "D:\Application\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 208, in _apply
    module._apply(fn)
  File "D:\Application\anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 123, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "D:\Application\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 230, in _apply
    param_applied = fn(param)
  File "D:\Application\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 430, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "D:\Application\anaconda3\lib\site-packages\torch\cuda\__init__.py", line 179, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at ..\aten\src\THC\THCGeneral.cpp:50

**What issue meet, what's expected?**:
When I test the program without nni, this program doesn't report this error, But when I write this program with nni, the program report the error "RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at ..\aten\src\THC\THCGeneral.cpp:50"
**How to reproduce it?**: 

**Additional information**:

**Comment by J-shang** [comment]
Can you show the config? It seems like you set `gpuNum: 0`, try `gpuNum: 1` or the number of GPUs you want to use.
```yaml
trial:
  command: python main.py
  codeDir: .
  gpuNum: 1
```

**Comment by Yggdrasilshh** [comment]
@J-shang Thank you for your time, I am a novice in deep learning and learn deep learning without guidance, I hope you'll forgive me for asking such a naive question

**Comment by J-shang** [comment]
That's alright and please feel free to contact us if you have any questions.

**Comment by scarlett2018** [comment]
closing the issue as the issue has been answered. @Yggdrasilshh feel free to reopen the issue if there are still questions around the issue.
