### ISSUE TITLE
ERROR 'ChildProcessError: Command failed - Need Help

### ISSUE THREAD

**Issue by TakiGuan** [microsoft/nni#3036]
**Environment**:
- NNI version: 1.9
- NNI mode (local|remote|pai): local
- Client OS: Windows Server 2012
- Server OS (for remote mode only):
- Python version: 3.8.3
- PyTorch/TensorFlow version: 
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: No

**Log message**:
 - nnimanager.log: 
[10/27/2020, 11:34:47 PM] INFO [ 'Datastore initialization done' ]
[10/27/2020, 11:34:47 PM] INFO [ 'RestServer start' ]
[10/27/2020, 11:34:47 PM] INFO [ 'Construct local machine training service.' ]
[10/27/2020, 11:34:47 PM] INFO [ 'RestServer base port is 8080' ]
[10/27/2020, 11:34:47 PM] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[10/27/2020, 11:34:48 PM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python mnist.py","codeDir":"E:\\\\AI\\\\AutoML\\\\NII\\\\nni\\\\examples\\\\trials\\\\mnist-tfv1\\\\.","gpuNum":0}' ]
[10/27/2020, 11:34:48 PM] INFO [ 'required GPU number is 0' ]
[10/27/2020, 11:34:49 PM] INFO [ 'Starting experiment: ifj1yQ1e' ]
[10/27/2020, 11:34:49 PM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[10/27/2020, 11:34:49 PM] INFO [ 'Add event listeners' ]
[10/27/2020, 11:34:49 PM] INFO [ 'Run local machine training service.' ]
[10/27/2020, 11:34:51 PM] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[10/27/2020, 11:34:51 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"dropout_rate": 0.5180495855216245, "conv_size": 2, "hidden_size": 512, "batch_size": 32, "learning_rate": 0.0001}, "parameter_index": 0}' ]
[10/27/2020, 11:34:54 PM] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"dropout_rate\\": 0.5180495855216245, \\"conv_size\\": 2, \\"hidden_size\\": 512, \\"batch_size\\": 32, \\"learning_rate\\": 0.0001}, \\"parameter_index\\": 0}","index":0}}' ]
[10/27/2020, 11:35:00 PM] ERROR [ 'ChildProcessError: Command failed: powershell.exe New-Item -Path "C:\\Users\\Taki Guan\\nni-experiments\\ifj1yQ1e\\trials\\pCRyN" -ItemType "directory" -Force\nNew-Item : A positional parameter cannot be found that accepts argument \'Guan\\nni-experiments\\ifj1yQ1e\\trials\\pCRyN\'.\r\nAt line:1 char:1\r\n+ New-Item -Path C:\\Users\\Taki Guan\\nni-experiments\\ifj1yQ1e\\trials\\pCR ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidArgument: (:) [New-Item], ParameterBindingException\r\n    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.NewItemCommand\r\n \r\n `powershell.exe New-Item -Path "C:\\Users\\Taki Guan\\nni-experiments\\ifj1yQ1e\\trials\\pCRyN" -ItemType "directory" -Force` (exited with error code 1)\n    at callback (e:\\software\\anaconda3\\nni\\node_modules\\child-process-promise\\lib\\index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:301:5)\n    at ChildProcess.emit (events.js:198:13)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)' ]
[10/27/2020, 11:35:00 PM] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]
 - dispatcher.log:
[10/27/2020, 11:34:51 PM] INFO (nni.msg_dispatcher_base/MainThread) Start dispatcher
[10/27/2020, 11:34:51 PM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.006001 seconds
[10/27/2020, 11:34:51 PM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
How to solve the PositionalParameterNotFound issue? I suppose it's related to my user name. It has space inside them. But I can't find a way to change the checkpoint directory.

**How to reproduce it?**: 
Everytime start a experiment.

**Additional information**:

**Comment by SparkSnail** [comment]
Set logDir to change the log directory in your config file, refer https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.md#logdir

**Comment by TakiGuan** [comment]
Thanks. This is exactly what I need. The blank between user name is the root cause. After redirect to a new directory. It works. Thanks. @SparkSnail
