### ISSUE TITLE
trail files were not created during nni experimentation starting 

### ISSUE THREAD

**Issue by ALI7861111** [microsoft/nni#3078]
**i started the hpo with nnictl create --config config.yml all the files that are created in C:\Users\NAME\nni-experiments\ 
 the trail files were not created and hence that later let to error stating that stated : no such directory found 'C:\\Users\\Ali Arsalan\\nni-experiments\\PbKowobQ\\trials\\pqJqm\\stderr . Please respond to this problem i need solution for my research completion**
[11/9/2020, 5:41:01 PM] INFO [ 'Datastore initialization done' ]
[11/9/2020, 5:41:01 PM] INFO [ 'RestServer start' ]
[11/9/2020, 5:41:01 PM] INFO [ 'Construct local machine training service.' ]
[11/9/2020, 5:41:01 PM] INFO [ 'RestServer base port is 8080' ]
[11/9/2020, 5:41:01 PM] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[11/9/2020, 5:41:03 PM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python main.py","codeDir":"C:\\\\HYPER_1\\\\."}' ]
[11/9/2020, 5:41:05 PM] INFO [ 'Starting experiment: PbKowobQ' ]
[11/9/2020, 5:41:05 PM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[11/9/2020, 5:41:05 PM] INFO [ 'Add event listeners' ]
[11/9/2020, 5:41:05 PM] INFO [ 'Run local machine training service.' ]
[11/9/2020, 5:41:07 PM] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[11/9/2020, 5:41:07 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"dropout_rate": 0.7843957138444932, "num_unit1": 1024, "num_unit2": 2048, "num_unit3": 4096, "num_unit4": 4096, "num_unit5": 2048, "learning_rate": 0.25071828860880535}, "parameter_index": 0}' ]
[11/9/2020, 5:41:07 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"dropout_rate": 0.38008169779167233, "num_unit1": 2048, "num_unit2": 1024, "num_unit3": 1024, "num_unit4": 4096, "num_unit5": 4096, "learning_rate": 0.016328488473831095}, "parameter_index": 0}' ]
[11/9/2020, 5:41:10 PM] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"dropout_rate\\": 0.7843957138444932, \\"num_unit1\\": 1024, \\"num_unit2\\": 2048, \\"num_unit3\\": 4096, \\"num_unit4\\": 4096, \\"num_unit5\\": 2048, \\"learning_rate\\": 0.25071828860880535}, \\"parameter_index\\": 0}","index":0}}' ]
[11/9/2020, 5:41:11 PM] INFO [ 'submitTrialJob: form: {"sequenceId":1,"hyperParameters":{"value":"{\\"parameter_id\\": 1, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"dropout_rate\\": 0.38008169779167233, \\"num_unit1\\": 2048, \\"num_unit2\\": 1024, \\"num_unit3\\": 1024, \\"num_unit4\\": 4096, \\"num_unit5\\": 4096, \\"learning_rate\\": 0.016328488473831095}, \\"parameter_index\\": 0}","index":0}}' ]
[11/9/2020, 5:41:16 PM] ERROR [ 'ChildProcessError: Command failed: powershell.exe New-Item -Path "C:\\Users\\Ali Arsalan\\nni-experiments\\PbKowobQ\\trials\\pqJqm" -ItemType "directory" -Force\nNew-Item : A positional parameter cannot be found that accepts argument \r\n\'Arsalan\\nni-experiments\\PbKowobQ\\trials\\pqJqm\'.\r\nAt line:1 char:1\r\n+ New-Item -Path C:\\Users\\Ali Arsalan\\nni-experiments\\PbKowobQ\\trials\\p ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidArgument: (:) [New-Item], ParameterBindingException\r\n    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.NewItemCommand\r\n \r\n `powershell.exe New-Item -Path "C:\\Users\\Ali Arsalan\\nni-experiments\\PbKowobQ\\trials\\pqJqm" -ItemType "directory" -Force` (exited with error code 1)\n    at callback (c:\\programdata\\anaconda3\\nni\\node_modules\\child-process-promise\\lib\\index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:301:5)\n    at ChildProcess.emit (events.js:198:13)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)' ]
[11/9/2020, 5:41:16 PM] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]
[11/9/2020, 5:41:38 PM] ERROR [ { Error: ENOENT: no such file or directory, open 'C:\Users\Ali Arsalan\nni-experiments\PbKowobQ\trials\pqJqm\stderr'
    errno: -4058,
    code: 'ENOENT',
    syscall: 'open',
    path:
     'C:\\Users\\Ali Arsalan\\nni-experiments\\PbKowobQ\\trials\\pqJqm\\stderr' } ]
[11/9/2020, 5:45:20 PM] INFO [ 'Change NNIManager status from: ERROR to: STOPPING' ]
[11/9/2020, 5:45:20 PM] INFO [ 'Stopping experiment, cleaning up ...' ]
[11/9/2020, 5:45:23 PM] INFO [ 'cancelTrialJob: pqJqm' ]
[11/9/2020, 5:45:23 PM] INFO [ 'cancelTrialJob: mSQGb' ]
[11/9/2020, 5:45:23 PM] INFO [ 'Stopping local machine training service...' ]
[11/9/2020, 5:45:23 PM] INFO [ 'Change NNIManager status from: STOPPING to: STOPPED' ]
[11/9/2020, 5:45:23 PM] INFO [ 'Experiment stopped.' ]

**Comment by SparkSnail** [comment]
There is a space in your user path "C:\\Users\\Ali Arsalan\\nni-experiments\\PbKowobQ\\trials\\pqJqm", you could try using `logDir`(https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.md#logdir) to set a valid log path.

**Comment by ALI7861111** [comment]
Could their not be some efficient solution rather then making a whole new user name without spaces !

**Comment by SparkSnail** [comment]
> Could their not be some efficient solution rather then making a whole new user name without spaces !

By default, NNI use `${home}` path to store log files, while `${home}` path contains user name. If you do not want to use `${home}` path, you could set your logDir path to another path, like `C:\data`. You don't need to create a new user name, just change logDir to a new folder path without spaces.
