### ISSUE TITLE
Fail to start nni experiment

### ISSUE THREAD

**Issue by gungui98** [microsoft/nni#3080]
**Environment**:
- NNI version: 1.9
- NNI mode (local|remote|pai): local
- Client OS: Ubuntu 18.04
- Server OS (for remote mode only):
- Python version: 3.6
- PyTorch/TensorFlow version: Pytorch 1.7
- Is conda/virtualenv/venv used?: Anconda
- Is running in Docker?: No

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.dispatcher.onError (/home/cotai/anaconda3/nni/core/nnimanager.js:512:32)
    at EventEmitter.emit (events.js:198:13)
    at Socket.IpcInterface.outgoingStream.on (/home/cotai/anaconda3/nni/core/ipcInterface.js:41:72)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

 - nnictl stdout and stderr:
   -----------------------------------------------------------------------
                Experiment start time 2020-11-10 08:33:07
-----------------------------------------------------------------------
internal/modules/cjs/loader.js:1088
  throw err;
  ^

Error: Cannot find module '/home/cotai/anaconda3/envs/NLP/nni/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node'
Require stack:
- /home/cotai/anaconda3/envs/NLP/nni/node_modules/sqlite3/lib/sqlite3-binding.js
- /home/cotai/anaconda3/envs/NLP/nni/node_modules/sqlite3/lib/sqlite3.js
- /home/cotai/anaconda3/envs/NLP/nni/core/sqlDatabase.js
- /home/cotai/anaconda3/envs/NLP/nni/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.Module._load (internal/modules/cjs/loader.js:928:27)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/cotai/anaconda3/envs/NLP/nni/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/cotai/anaconda3/envs/NLP/nni/node_modules/sqlite3/lib/sqlite3-binding.js',
    '/home/cotai/anaconda3/envs/NLP/nni/node_modules/sqlite3/lib/sqlite3.js',
    '/home/cotai/anaconda3/envs/NLP/nni/core/sqlDatabase.js',
    '/home/cotai/anaconda3/envs/NLP/nni/main.js'
  ]
}

**What issue meet, what's expected?**:
This error throws when I try to run the experiment with command 

``` nnictl create --config config_ner.yml --port 9000 ```

I have already reinstall with pip, even with different conda environments but the error still there.

**Comment by gungui98** [comment]
HI, this problem turns out to be an incorrect nodejs version on my machine, I already fix this problem by switching to node 10 using nvm. But I have another problem,  the dispatcher seems to use /usr/bin/python3 rather than conda python, which case the error when I run the experiment. this is the log from stderrr 

/usr/bin/python3: No module named nni
Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.dispatcher.onError (/home/cotai/anaconda3/envs/NLP/nni/core/nnimanager.js:512:32)
    at EventEmitter.emit (events.js:198:13)
    at Socket.IpcInterface.outgoingStream.on (/home/cotai/anaconda3/envs/NLP/nni/core/ipcInterface.js:41:72)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by gungui98** [comment]
I fix that by remove /usr/bin from PATH
