### ISSUE TITLE
 I perform QAT on the mobilenetv2 with CIFAR10 but training accuracy is very low (about 10%)

### ISSUE THREAD

**Issue by Lycan1003** [microsoft/nni#3084]
I perform QAT on the mobilenetv2 with CIFAR10 but training accuracy is very low (**about 10%**).
```
configure_list = [{
            'quant_types': ['weight'],
            'quant_bits': {
                'weight': 8,
            },
            # you can just use `int` here because all `quan_types` share same bits length, see config for `ReLu6` below.
            'op_types': ['default']
        }, {
            'quant_types': ['output'],
            'quant_bits': 8,
            'quant_start_step': 1000,
            'op_types': ['default']
        }]
```

```
    optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9, weight_decay=5e-4)
    criterion = nn.CrossEntropyLoss() 
```

I wonder if it is because batch normalization folding is not supported currently?
or maybe my configure_list has some unreasonable configuration?

I am a rookie of PyTorch and wish for your reply (✺ω✺).

**Comment by linbinskn** [comment]
I am not sure whether you have using the QAT properly. Can you show me the code of your experiment or describe the detail of your experiment?

**Comment by Lycan1003** [comment]
> I am not sure whether you have using the QAT properly. Can you show me the code of your experiment or describe the detail of your experiment?

Thanks for your reply! 
I wanna run one time and get results of 1 to 8 quantization bits, and make sure each time model will train from the same init state.
Here is the code:
```
def main(args):

    torch.manual_seed(0)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Data Loader
    transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))])
    transform_train = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
    ])

    transform_test = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
    ])
    if args.dataset == "mnist":
        traindataset = datasets.MNIST('./data', train=True, download=True, transform=transform)
        testdataset = datasets.MNIST('./data', train=False, transform=transform)
        from models.mnist import AlexNet, LeNet5, fc1, vgg, resnet, shufflenetv2, mobilenet

    elif args.dataset == "cifar10":
        traindataset = datasets.CIFAR10('./data', train=True, download=True, transform=transform_train)
        testdataset = datasets.CIFAR10('./data', train=False, transform=transform_test)
        from models.cifar10 import AlexNet, LeNet5, fc1, vgg, resnet, densenet, shufflenetv2, mobilenetv2


    # If you want to add extra datasets paste here

    else:
        print("\nWrong Dataset choice \n")
        exit()

    train_loader = torch.utils.data.DataLoader(traindataset, batch_size=args.batch_size, shuffle=True, num_workers=32,
                                               drop_last=False)
    # train_loader = cycle(train_loader)
    test_loader = torch.utils.data.DataLoader(testdataset, batch_size=args.batch_size, shuffle=False, num_workers=32,
                                              drop_last=True)

    # Importing Network Architecture
    global model
    
    if args.arch_type == "fc1":
        model = fc1.fc1().to(device)
    elif args.arch_type == "lenet5":
        model = LeNet5.LeNet5().to(device)
    elif args.arch_type == "alexnet":
        model = AlexNet.AlexNet().to(device)
    elif args.arch_type == "vgg16":
        model = vgg.vgg16().to(device)
    elif args.arch_type == "resnet18":
        if args.dataset == "mnist":
            model = resnet.resnet18().to(device)
        else:
            model = resnet.ResNet18().to(device)
    elif args.arch_type == "densenet121":
        model = densenet.densenet121().to(device)
    elif args.arch_type == "shufflenet":
        if args.dataset == "mnist":
            model = shufflenetv2.shufflenet_v2_x1_0().to(device)
        else:
            model = shufflenetv2.ShuffleNetV2(net_size=1.0).to(device)
    elif args.arch_type == "mobilenetv2":
        if args.dataset == "mnist":
            model = mobilenet.mobilenet_v2().to(device)
        else:
            model = mobilenetv2.MobileNetV2().to(device)
    # If you want to add extra model paste here
    else:
        print("\nWrong Model choice\n")
        exit()

    # Get train epochs
    train_epochs = 100
    quantization_bits = 8

    # Weight Initialization
    model.apply(weight_init)

    # Print and save log

    utils.checkdir(f"{os.getcwd()}/log/{args.arch_type}/{args.dataset}/")
    log = open(f"{os.getcwd()}/log/{args.arch_type}/{args.dataset}/log_{args.prune_type}.txt", 'w')

    # Copying and Saving Initial State
    initial_state_dict = copy.deepcopy(model.state_dict())
    utils.checkdir(f"{os.getcwd()}/saves/{args.arch_type}/{args.dataset}/")
    torch.save(model,
               f"{os.getcwd()}/saves/{args.arch_type}/{args.dataset}/initial_state_dict.pth")

    criterion = nn.CrossEntropyLoss()  # Default was F.nll_loss



    comp = np.zeros(quantization_bits, float)
    bestacc = np.zeros(quantization_bits, float)

    for i in range(1, quantization_bits + 1):
        # utils.checkdir(f"{os.getcwd()}/saves/{args.arch_type}/{args.dataset}/")
        model = torch.load(f"{os.getcwd()}/saves/{args.arch_type}/{args.dataset}/initial_state_dict.pth")

        configure_list = [{
            'quant_types': ['weight'],
            'quant_bits': {
                'weight': i,
            },
            # you can just use `int` here because all `quan_types` share same bits length, see config for `ReLu6` below.
            'op_types': ['default']
        }, {
            'quant_types': ['output'],
            'quant_bits': i,
            'quant_start_step': 100,
            'op_types': ['default']
        }]
        # optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
        optimizer = torch.optim.Adam(model.parameters(), lr=1.2e-3)
        quantizer = QAT_Quantizer(model, configure_list, optimizer)
        quant_start_step_temp = configure_list[-1]["quant_start_step"]
        quantizer.compress()
        model = torch.nn.DataParallel(model, device_ids=[0, 1, 2])
        cudnn.benchmark = True
        model.to(device)

        all_loss = np.zeros(args.end_iter, float)
        all_accuracy = np.zeros(args.end_iter, float)
        best_accuracy = 0
        best_state_dict = None

        utils.print_log(f"\n--- quantization level [{i}/{quantization_bits}]: ---", log)
        loss = 0
        accuracy = 0

        for epoch in train_epochs:
            # Frequency for Testing
            loss = train(model, train_loader, optimizer, criterion)
            if epoch % args.valid_freq == 0:
                accuracy = test(model, test_loader, criterion)
            all_loss[epoch] = loss
            all_accuracy[epoch] = accuracy

            # Frequency for Printing Accuracy and Loss
            if epoch % args.print_freq == 0:
                # pbar.set_description(f'Train Epoch: {iter_}/{args.end_iter} Loss: {loss:.6f} Accuracy: {accuracy:.2f}% Best Accuracy: {best_accuracy:.2f}%')
                utils.print_log(
                    f'Train Epoch: {epoch}/{args.end_iter} Loss: {loss:.6f} Accuracy: {accuracy:.2f}% Best Accuracy: {best_accuracy:.2f}%',
                    log)
```

when starting to QAT, the loss will be **nan**.
The resnet18 is fine, but shufflenet or mobilenetv2 have this problem.
```
 ---
Train Epoch: 0/100 Loss: 1.390553 Accuracy: 10.00% Best Accuracy: 0.00%
Train Epoch: 1/100 Loss: 2.302163 Accuracy: 10.00% Best Accuracy: 0.00%
Train Epoch: 2/100 Loss: nan Accuracy: 10.00% Best Accuracy: 10.00%
Train Epoch: 3/100 Loss: nan Accuracy: 10.00% Best Accuracy: 10.00%
Train Epoch: 4/100 Loss: nan Accuracy: 10.00% Best Accuracy: 10.00%
```

Wish for your reply and thanks a lot.

**Comment by linbinskn** [comment]
If you quantize the whole model to 1bit using QAT, it may will cause the problem that model failed to converge. You can set the bit to 3 or 4 and observe the loss again.

**Comment by Lycan1003** [comment]
> If you quantize the whole model to 1bit using QAT, it may cause the problem that model fails to converge. You can set the bit to 3 or 4 and observe the loss again.

Exactly, the loss will be unstable with low bits quantization, but I have quantized the shufflenet to 8 bits using QAT, it still has this problem.

**Comment by linbinskn** [comment]
You mean that mobilenetv2 can converge finally by increasing the bits but shufflenet will always be unstable even in the bits > 8?

**Comment by Lycan1003** [comment]
> You mean that mobilenetv2 can converge finally by increasing the bits but shufflenet will always be unstable even in the bits > 8?

I mean that resnet18 can converge in the bits >=4, but mobilenetv2 and shufflenet are always unstable even in the bits > 8.

**Comment by linbinskn** [comment]
I have tested the mobilenetv2 in QAT. If only quantize weight, the training process is normal. If quantize activation, the loss will be nan.  I think this phenomenon occurred  because folding of batchnorm has not been supported yet. And it will always exists in the QAT method without folding.

**Comment by Lycan1003** [comment]
> I have tested the mobilenetv2 in QAT. If only quantize weight, the training process is stable and the model can converge normally. If quantize activation, the loss will be nan. I think this phenomenon occurred because folding of batchnorm has not been supported yet. And it will always exists in the QAT method without folding.

Thanks for your reply. I test shufflenet and mobilenetv2 with the following config and the training process is stable.
```
configure_list = [{
            'quant_types': ['weight'],
            'quant_bits': {
                'weight': i,
            },
            'op_types': ['default']
        }]
```
By the way, does the **quant_start_step** only affect the **output quant_types**? 
Or can I put **quant_start_step** in the configure_list with **weight quant_types** ? like this:
```
configure_list = [{
            'quant_types': ['weight'],
            'quant_bits': {
                'weight': i,
            },
            'quant_start_step': 1000,
            'op_types': ['default']
        }]
```

**Comment by linbinskn** [comment]
You can use **quant_start_step** with weight.

**Comment by Lycan1003** [comment]
> You can use **quant_start_step** with weight.

Thanks for your reply! Thanks for nni team! 

However, I found another problem that when I **only quantize weight with multi GPU**, it will cause an error.
Base on the original example of QAT, I only changed the configure_list and added a line of code (model = torch.nn.DataParallel(model, device_ids=[0, 1]))

This error only appears in this situation. And for other situations,
configure_list contains output: **no error**
Use a single GPU: **no error**

I put the test code in the attachment, you can try☺
[QAT_pytorch_multiGPU.zip](https://github.com/microsoft/nni/files/5570963/QAT_pytorch_multiGPU.zip)



```
Traceback (most recent call last):
  File "QAT_pytorch_multiGPU.py", line 96, in <module>
    main()
  File "QAT_pytorch_multiGPU.py", line 92, in main
    test(model, device, test_loader)
  File "QAT_pytorch_multiGPU.py", line 48, in test
    output = model(data)
  File "/root/anaconda3/envs/pytorch_nni_shanghai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch_nni_shanghai/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/root/anaconda3/envs/pytorch_nni_shanghai/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/root/anaconda3/envs/pytorch_nni_shanghai/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/root/anaconda3/envs/pytorch_nni_shanghai/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
**TypeError: Caught TypeError in replica 0 on device 0.**
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch_nni_shanghai/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch_nni_shanghai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "QAT_pytorch_multiGPU.py", line 19, in forward
    x = self.relu1(self.conv1(x))
  File "/root/anaconda3/envs/pytorch_nni_shanghai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch_nni_shanghai/lib/python3.6/site-packages/nni/compression/torch/compressor.py", line 487, in forward
    self)
  File "/root/anaconda3/envs/pytorch_nni_shanghai/lib/python3.6/site-packages/nni/compression/torch/compressor.py", line 619, in forward
    return wrapper.quantizer.quantize_weight(wrapper, **kwargs)
  File "/root/anaconda3/envs/pytorch_nni_shanghai/lib/python3.6/site-packages/nni/compression/torch/quantization/quantizers.py", line 251, in quantize_weight
    wrapper.module.weight = weight
  File "/root/anaconda3/envs/pytorch_nni_shanghai/lib/python3.6/site-packages/torch/nn/modules/module.py", line 801, in __setattr__
    .format(torch.typename(value), name))
**TypeError: cannot assign 'torch.cuda.FloatTensor' as parameter 'weight' (torch.nn.Parameter or None expected)**
```

**Comment by linbinskn** [comment]
We have tested your code and this problem exactly exists. The problem only happens during using multiGPU. We will try to find the problem and fix it.

**Comment by Lycan1003** [comment]
Thanks for nni team! It is my pleasure!
