### ISSUE TITLE
Error during model speedup process with SimulatedAnnealingPruner

### ISSUE THREAD

**Issue by abuvaneswari** [microsoft/nni#3090]
**Environment**:
- NNI version: 1.9
- NNI mode (local|remote|pai): local
- Client OS: Centos 7
- Server OS (for remote mode only):
- Python version: 3.6
- PyTorch/TensorFlow version: Pytorch 1.5.1
- Is conda/virtualenv/venv used?: virtualenv
- Is running in Docker?: No

**Log message**:
Attaching a text file containing the stdout and stderr from running the command below. A dump of the last several lines of stderr:
[11/12/2020, 03:03:24 PM] INFO (nni.compression.torch.utils.mask_conflict) detected conv prune dim: 0
Traceback (most recent call last):
  File "auto_pruners_torch.py", line 481, in <module>
    main(args)
  File "auto_pruners_torch.py", line 340, in main
    m_speedup.speedup_model()
  File "/home/tfs/venv_nni/lib/python3.6/site-packages/nni/compression/torch/speedup/compressor.py", line 179, in speedup_model
    _, conv_prune_dim = fix_mask_conflict(self.masks, self.bound_model, self.dummy_input)
  File "/home/tfs/venv_nni/lib/python3.6/site-packages/nni/compression/torch/utils/mask_conflict.py", line 46, in fix_mask_conflict
    masks = fix_channel_mask.fix_mask()
  File "/home/tfs/venv_nni/lib/python3.6/site-packages/nni/compression/torch/utils/mask_conflict.py", line 285, in fix_mask
    merged_channel_mask = ((merged_channel_mask + channel_masks[i]) != 0).int()
RuntimeError: expected device cpu but got device cuda:0

**What issue meet, what's expected?**:
Error while speedup step is executed.

**How to reproduce it?**: 
python auto_pruners_torch.py --speed-up True --model resnet50 --pretrain-epochs 5 --pruner SimulatedAnnealingPruner --sparsity 0.7 --experiment-data-dir ./resnet50.SimulatedAnnealingPruner.0.7 --fine-tune-epochs 40

**Additional information**:

- The above command when run with L1FilterPruner/L2FilterPruner/FPGMPruner pruner works fine. 
- Also, the command when run with the speed-up set to False runs fine.
- When run with vgg16 model, the speedup with SimulatedAnnealingPruner runs fine.

[
[log.SimulatedAnnealingPruner.speedup.txt](https://github.com/microsoft/nni/files/5540262/log.SimulatedAnnealingPruner.speedup.txt)
]

**Comment by suiguoxin** [comment]
@abuvaneswari Hi, it seems that you have modified the example code. Could you please check if `model` and `dummy_input` are loaded to the same device type ? Pay attention to the use of `.to(device)`.

**Comment by kvartet** [comment]
hello @abuvaneswari, I will close this issue as it has not been updated for more than three months, feel free to reopen it if you still think it an active issue.
