### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by mak-rayate** [microsoft/nni#3186]
**Environment**:
- NNI version:1.9
- NNI mode (local|remote|pai):local
- Client OS:Windows 10
- Python version:Python 3.7.6
- PyTorch/TensorFlow version:2.3.0
- Is conda/virtualenv/venv used?:JupyterNotebook

**Log message**:
`! nnictl create --config nni\examples\trials\mnist-tfv1\config_windows.yml`
```
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\makar\AppData\Roaming\Python\Python37\Scripts\nnictl.exe\__main__.py", line 4, in <module>
  File "C:\Users\makar\AppData\Roaming\Python\Python37\site-packages\nni_cmd\nnictl.py", line 9, in <module>
    from .launcher import create_experiment, resume_experiment, view_experiment
  File "C:\Users\makar\AppData\Roaming\Python\Python37\site-packages\nni_cmd\launcher.py", line 14, in <module>
    from .launcher_utils import validate_all_content
  File "C:\Users\makar\AppData\Roaming\Python\Python37\site-packages\nni_cmd\launcher_utils.py", line 6, in <module>
    from .config_schema import NNIConfigSchema
  File "C:\Users\makar\AppData\Roaming\Python\Python37\site-packages\nni_cmd\config_schema.py", line 138, in <module>
    Optional('tuner'): AlgoSchema('tuner'),
  File "C:\Users\makar\AppData\Roaming\Python\Python37\site-packages\nni_cmd\config_schema.py", line 71, in __init__
    self.builtin_name_schema[k] = {Optional(n): setChoice(n, *get_all_builtin_names(k+'s'))}
  File "C:\Users\makar\AppData\Roaming\Python\Python37\site-packages\nni\package_utils.py", line 32, in get_all_builtin_names
    merged_dict = _get_merged_builtin_dict()
  File "C:\Users\makar\AppData\Roaming\Python\Python37\site-packages\nni\package_utils.py", line 361, in _get_merged_builtin_dict
    return merge_meta_dict(BuiltinAlgorithms, read_installed_package_meta())
  File "C:\Users\makar\AppData\Roaming\Python\Python37\site-packages\nni\package_utils.py", line 338, in read_installed_package_meta
    config_file = get_package_config_path()
  File "C:\Users\makar\AppData\Roaming\Python\Python37\site-packages\nni\package_utils.py", line 332, in get_package_config_path
    config_dir = get_nni_config_dir()
  File "C:\Users\makar\AppData\Roaming\Python\Python37\site-packages\nni\package_utils.py", line 329, in get_nni_config_dir
    return os.path.join(get_nni_installation_path(), 'config')
  File "c:\programdata\anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
 ```

**Additional information**:
Running in JupyterNotebook and getting same error on AnacodaPrompt. Searched a lot but no solution found. Anyone have any idea ?

**Comment by J-shang** [comment]
It seems you use `base` env of `anaconda` and use `pip install --user nni`? Use `pip install --user <pkg>` in anaconda may cause some problems.

Please check:
- the result of `python -c "import os; print(os.getenv('VIRTUAL_ENV'))"` and `python -c "import site; print(site.getsitepackages())"`
- If you have the file `C:\programdata\anaconda3\nni\main.js` or where is `**\nni\main.js`?

Try to create a new vitural env and reinstall nni may solve the problem. 
Here is an example.
```
conda create -n nni python=3.7
conda activate nni
python -m pip install nni
```
And maybe you need install other dependents, like `tensorflow`.

**Comment by mak-rayate** [comment]
@J-shang ,Thanks for reply. Yes, I have used `base` env of conda . I will create virtual env ,may will solve the issue .
