### ISSUE TITLE
How about mask out whole convolution layer?

### ISSUE THREAD

**Issue by twmht** [microsoft/nni#3200]
**Environment**:
- NNI version:3.0
- NNI mode (local|remote|pai)local
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Log message**:

```
elapsed time when use mask:  0.21371126174926758
[2020-12-16 13:30:37] INFO (nni.compression.pytorch.speedup.compressor/MainThread) start to speed up the model
[2020-12-16 13:30:37] INFO (nni.compression.pytorch.speedup.compressor/MainThread) fix the mask conflict of the interdependent layers
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) {'stem.0': 1, 'stem.3': 1, 'stem.6': 1, 'stage2.OSA2_1.layers.0.0': 1, 'stage2.OSA2_1.layers.1.0': 1, 'stage2.OSA2_1.layers.2.0': 1, 'stage2.OSA2_1.concat.0': 1, 'stage2.OSA2_1.ese.fc': 1, 'stage3.OSA3_1.layers.0.0': 1, 'stage3.OSA3_1.layers.1.0': 1, 'stage3.OSA3_1.layers.2.0': 1, 'stage3.OSA3_1.concat.0': 1, 'stage3.OSA3_1.ese.fc': 1, 'stage4.OSA4_1.layers.0.0': 1, 'stage4.OSA4_1.layers.1.0': 1, 'stage4.OSA4_1.layers.2.0': 1, 'stage4.OSA4_1.concat.0': 1, 'stage4.OSA4_1.ese.fc': 1}
[2020-12-16 13:30:38] WARNING (nni.compression.pytorch.utils.mask_conflict/MainThread) no multi-dimension masks found.
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) detected conv prune dim: 0
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) infer module masks...
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace compressed modules...
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stem.1, op_type: BatchNorm2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stem.0, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stem.2, op_type: ReLU)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stem.3, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stem.4, op_type: BatchNorm2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stem.5, op_type: ReLU)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stem.6, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stem.7, op_type: BatchNorm2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stem.8, op_type: ReLU)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.layers.0.0, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) Warning: cannot replace (name: stage2.OSA2_1.aten::cat.64, op_type: aten::cat) which is func type
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.concat.0, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.layers.0.1, op_type: BatchNorm2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.layers.0.2, op_type: ReLU)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.layers.1.0, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.layers.1.1, op_type: BatchNorm2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.layers.1.2, op_type: ReLU)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.layers.2.0, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.layers.2.1, op_type: BatchNorm2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.layers.2.2, op_type: ReLU)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.concat.1, op_type: BatchNorm2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.concat.2, op_type: ReLU)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.ese.avg_pool, op_type: AdaptiveAvgPool2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage2.OSA2_1.ese.fc, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) Warning: cannot replace (name: stage2.OSA2_1.ese.aten::mul.65, op_type: aten::mul) which is func type
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.Pooling, op_type: MaxPool2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.layers.0.0, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) Warning: cannot replace (name: stage3.OSA3_1.aten::cat.66, op_type: aten::cat) which is func type
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.concat.0, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.layers.0.1, op_type: BatchNorm2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.layers.0.2, op_type: ReLU)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.layers.1.0, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.layers.1.1, op_type: BatchNorm2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.layers.1.2, op_type: ReLU)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.layers.2.0, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.layers.2.1, op_type: BatchNorm2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.layers.2.2, op_type: ReLU)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.concat.1, op_type: BatchNorm2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.concat.2, op_type: ReLU)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.ese.avg_pool, op_type: AdaptiveAvgPool2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage3.OSA3_1.ese.fc, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) Warning: cannot replace (name: stage3.OSA3_1.ese.aten::mul.67, op_type: aten::mul) which is func type
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage4.Pooling, op_type: MaxPool2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage4.OSA4_1.layers.0.0, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) Warning: cannot replace (name: stage4.OSA4_1.aten::cat.68, op_type: aten::cat) which is func type
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage4.OSA4_1.concat.0, op_type: Conv2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage4.OSA4_1.layers.0.1, op_type: BatchNorm2d)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage4.OSA4_1.layers.0.2, op_type: ReLU)
[2020-12-16 13:30:38] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: stage4.OSA4_1.layers.1.0, op_type: Conv2d)
Traceback (most recent call last):
  File "model_speedup.py", line 94, in <module>
    model_inference(config[args.example_name])
  File "model_speedup.py", line 70, in model_inference
    m_speedup.speedup_model()
  File "/home/shared/nfs/acer-share/nni/nni/compression/pytorch/speedup/compressor.py", line 185, in speedup_model
    self.replace_compressed_modules()
  File "/home/shared/nfs/acer-share/nni/nni/compression/pytorch/speedup/compressor.py", line 161, in replace_compressed_modules
    compressed_module = replace_module[m_type](leaf_module, self.inferred_masks[module_name])
  File "/home/shared/nfs/acer-share/nni/nni/compression/pytorch/speedup/compress_modules.py", line 12, in <lambda>
    'Conv2d': lambda module, mask: replace_conv2d(module, mask),
  File "/home/shared/nfs/acer-share/nni/nni/compression/pytorch/speedup/compress_modules.py", line 142, in replace_conv2d
    padding_mode=conv.padding_mode)
  File "/home/acer/.pyenv/versions/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 332, in __init__
    False, _pair(0), groups, bias, padding_mode)
  File "/home/acer/.pyenv/versions/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 46, in __init__
    self.reset_parameters()
  File "/home/acer/.pyenv/versions/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 49, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/home/acer/.pyenv/versions/pytorch/lib/python3.7/site-packages/torch/nn/init.py", line 310, in kaiming_uniform_
    fan = _calculate_correct_fan(tensor, mode)
  File "/home/acer/.pyenv/versions/pytorch/lib/python3.7/site-packages/torch/nn/init.py", line 279, in _calculate_correct_fan
    fan_in, fan_out = _calculate_fan_in_and_fan_out(tensor)
  File "/home/acer/.pyenv/versions/pytorch/lib/python3.7/site-packages/torch/nn/init.py", line 211, in _calculate_fan_in_and_fan_out
    receptive_field_size = tensor[0][0].numel()
IndexError: index 0 is out of bounds for dimension 0 with size 0
```
**What issue meet, what's expected?**:

when running `model_speedup.py`, it throws the exception.

the root cause is whole output channels of the convolution are masked to zero.

it seems like nni does not handle such situations.

**How to reproduce it?**: 

I would provide the network and the checkpoint file.
https://drive.google.com/drive/folders/1IebklNoylXww7Wj0CpK9w52LZcpVyqPe?usp=sharing

**Additional information**:

**Comment by zheng-ningxin** [comment]
Hi ~ Thanks for the feedback.
In the current NNI, you cannot prune all the output channels of a conv layer. 
May I ask what kind of scenario you will have such a demand?

**Comment by twmht** [comment]
@zheng-ningxin 

Well, I just apply slim pruner to vovnet, and found the mask have zero channel-out layer. Can I prevent the pruner from pruning whole layer?

**Comment by zheng-ningxin** [comment]
Would you please show us the config you give to slim pruner?

**Comment by twmht** [comment]
sure. 

Here is my config

```
configure_list=[
'sparsity': 0.5,
'op_types': ['Batchnorm2d']
]
```

you can try to replicate the exceptions by running `slim_torch_cifar10.py` and `model_speeup.py`.

by the way, I have provided the network and mask, you can also feed them into `model_speeup.py`.

**Comment by twmht** [comment]
@zheng-ningxin 

sorry my bad, i just granted the access permission of my drive to you.

**Comment by scarlett2018** [comment]
@zheng-ningxin / @twmht - may I know the latest status of this issue? thanks.

**Comment by twmht** [comment]
@scarlett2018 

I replace the the convolution layer with `nn.Identity` if the whole layer is masked out. But I did not submit the PR yet.

**Comment by zheng-ningxin** [comment]
@twmht  Thanks for the reminding, we should replace the `conv` with `identity` when the whole conv layer is masked out. Due to the speedup is under refactoring, you can submit you PR when this [PR](https://github.com/microsoft/nni/pull/3462) is merged. Thanks.

**Comment by scarlett2018** [comment]
@zheng-ningxin - may we close this issue and #3193?
