### ISSUE TITLE
Send a experiment to a self signed certificate OpenPAI 1.0.1

### ISSUE THREAD

**Issue by benchuang11046** [microsoft/nni#3227]
**Environment**:
- NNI version: 1.9
- NNI mode (local|remote|pai): pai 1.0.1
- Client OS: ubuntu
- Server OS (for remote mode only): ubuntu
- Python version: 3.6
- PyTorch/TensorFlow version: TensorFlow 
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: Yes

**Log message**:
 - nnimanager.log: 
```
[12/23/2020, 9:13:21 AM] INFO [ 'Datastore initialization done' ]
[12/23/2020, 9:13:21 AM] INFO [ 'RestServer start' ]
[12/23/2020, 9:13:21 AM] INFO [ 'RestServer base port is 8084' ]
[12/23/2020, 9:13:21 AM] INFO [ 'Rest server listening on: http://0.0.0.0:8084' ]
[12/23/2020, 9:13:22 AM] INFO [ 'NNIManager setClusterMetadata, key: pai_config, value: {"userName":"admin","token":"{mask}","host":"{mask}"}' ]
[12/23/2020, 9:13:22 AM] INFO [ 'Construct paiBase training service.' ]
[12/23/2020, 9:13:22 AM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python3 mnist-keras.py","codeDir":"/app/nni/examples/trials/mnist-keras/.","gpuNum":0,"cpuNum":1,"memoryMB":8196,"image":"msranni/nni:latest","nniManagerNFSMountPath":"/home/","containerNFSMountPath":"/mnt/","paiStorageConfigName":"team_wise"}' ]
[12/23/2020, 9:13:22 AM] INFO [ 'Starting copy codeDir data from /app/nni/examples/trials/mnist-keras/. to /home/MfQXlcfR/nni-code' ]
[12/23/2020, 9:13:22 AM] INFO [ 'Starting experiment: MfQXlcfR' ]
[12/23/2020, 9:13:22 AM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[12/23/2020, 9:13:22 AM] INFO [ 'Add event listeners' ]
[12/23/2020, 9:13:22 AM] INFO [ 'Run PAI training service.' ]
[12/23/2020, 9:13:22 AM] INFO [ 'RestServer start' ]
[12/23/2020, 9:13:22 AM] INFO [ 'RestServer base port is 8085' ]
[12/23/2020, 9:13:22 AM] INFO [ 'PAI Training service rest server listening on: http://0.0.0.0:8085' ]
[12/23/2020, 9:13:23 AM] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[12/23/2020, 9:13:23 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"optimizer": "SGD", "learning_rate": 0.0001}, "parameter_index": 0}' ]
[12/23/2020, 9:13:27 AM] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"optimizer\\": \\"SGD\\", \\"learning_rate\\": 0.0001}, \\"parameter_index\\": 0}","index":0}}' ]
[12/23/2020, 9:13:27 AM] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"optimizer\\": \\"SGD\\", \\"learning_rate\\": 0.0001}, \\"parameter_index\\": 0}","index":0}}' ]
[12/23/2020, 9:13:28 AM] INFO [ 'Copy codeDir data finished.' ]
[12/23/2020, 9:13:28 AM] ERROR [ 'self signed certificate' ]
[12/23/2020, 9:13:28 AM] ERROR [ 'Training service error: self signed certificate\n    at Function.FromError (/usr/local/nni/common/errors.js:27:20)\n    at Promise.all.trainingService.run.catch (/usr/local/nni/core/nnimanager.js:492:41)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' ]
[12/23/2020, 9:13:28 AM] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]
```
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

```
[12/23/2020, 9:13:28 AM] ERROR [ 'Training service error: self signed certificate\n    at Function.FromError (/usr/local/nni/common/errors.js:27:20)\n    at Promise.all.trainingService.run.catch (/usr/local/nni/core/nnimanager.js:492:41)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' ]

```
How can I pass through self signed certificate without modify nni source code?

**How to reproduce it?**: 
Send a experiment to a self signed certificate OpenPAI 1.0.1

**Additional information**:

**Comment by SparkSnail** [comment]
NNI use `request` client to send http request to PAI, refer https://github.com/microsoft/nni/blob/master/ts/nni_manager/training_service/pai/paiK8S/paiK8STrainingService.ts#L284. From the log content you pasted, seems NNI get error when call the pai API to submit jobs. NNI does not support setting certificate, please make sure your PAI host is valid and available from http request. PAI host in NNI support setting `https://` or `http://` format.

**Comment by Tudor33** [comment]
We wish you a Merry Christmas and thank you for the beautiful year 2020 for
your creativity and ability to cooperate. And they thank you for what is
most important to our people, and that is cooperation worldwide.
For 2021 I hope you are ready
: P, the real fun is just beginning, it's already with rewards [image: 🙂]
first of all they need 5000 IT People from every capital city on earth,
5000 IT people x 10 CITIES each city will be from another country =
50.000IT people 1 team.
Isou 5 largest leaders 1Africa 2Asia 3America 4Australia and Oceania 5Europa
Every leader as a sign of prosperity and cooperation is a must to give
10,000IT of the best people to form 1team by unity.
Normal teams have the task of creating the levels of schools kindergarten,
primary, secondary, high,
They must strictly contain all the languages of the world and the best
methods for learning, I mean grabbing cloth by 4 times faster.
IT team JEDNOTA will have the task of creating an extra school, the most
difficult school, which even exists, even the best one, so that it cannot
pass.
AND MAINLY DON'T FORGET THE MOST IMPORTANT THING IN THE WORLD THAT IS
......... [image: 🙂] YOU HAVE TO FIND OUT FOR YOURSELF
I'm just waiting for your answer yes / no, YES = I CAN,
NO = I CANNOT DO IT.
I am waiting for your answer, with the teams ready for 3 weeks
Merry Christmas and wish you creativity for the future


čt 24. 12. 2020 v 13:12 odesílatel SparkSnail <notifications@github.com>
napsal:

**Comment by benchuang11046** [comment]
I got it. Thank your reply. @SparkSnail 


> NNI use `request` client to send http request to PAI, refer https://github.com/microsoft/nni/blob/master/ts/nni_manager/training_service/pai/paiK8S/paiK8STrainingService.ts#L284. From the log content you pasted, seems NNI get error when call the pai API to submit jobs. NNI does not support setting certificate, please make sure your PAI host is valid and available from http request. PAI host in NNI support setting `https://` or `http://` format.

**Comment by kvartet** [comment]
It seems the problem had been solved, so I will close this issue, feel free to reopen it.
