### ISSUE TITLE
NNI view AttributeError when trying to view any experiment.

### ISSUE THREAD

**Issue by OliverGrein** [microsoft/nni#3343]
**Environment**:
- NNI version: 2.0
- NNI mode (local|remote|pai):local
- Client OS: Windows 10
- Server OS (for remote mode only):
- Python version: 3.6.6
- PyTorch/TensorFlow version: TensorFlow 2.4.0
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: no

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr: 
```
 INFO:  view experiment 0h49zbj2...
Traceback (most recent call last):
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\nni\tools\nnictl\launcher.py", line 648, in manage_stopped_experiment
    launch_experiment(args, experiment_config, mode, experiment_id)
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\nni\tools\nnictl\launcher.py", line 485, in launch_experiment
    if experiment_config.get('tuner') and experiment_config['tuner'].get('builtinTunerName'):
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\psutil\_pswindows.py", line 933, in create_time
    user, system, created = cext.proc_times(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from OpenProcess -> ERROR_INVALID_PARAMETER)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\psutil\__init__.py", line 354, in _init
    self.create_time()
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\psutil\__init__.py", line 710, in create_time
    self._create_time = self._proc.create_time()
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=19384)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts\nnictl-script.py", line 11, in <module>
    load_entry_point('nni', 'console_scripts', 'nnictl')()
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\nni\tools\nnictl\nnictl.py", line 272, in parse_args
    args.func(args)
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\nni\tools\nnictl\launcher.py", line 658, in view_experiment
    manage_stopped_experiment(args, 'view')
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\nni\tools\nnictl\launcher.py", line 652, in manage_stopped_experiment
    kill_command(restServerPid)
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\nni\tools\nnictl\command_utils.py", line 37, in kill_command
    process = psutil.Process(pid=pid)
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\psutil\__init__.py", line 326, in __init__
    self._init(pid)
  File "C:\Users\XCGGV\AppData\Roaming\Python\Python36\site-packages\psutil\__init__.py", line 367, in _init
    raise NoSuchProcess(pid, None, msg)
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 19384
```

**What issue meet, what's expected?**:
When Running nnictl view ID on any experiment I get the Error i posted above. The Experiments ran fine and the website was working while they were still running.

**How to reproduce it?**: 
Just try to run an experiment and try to view it after it stopped 

**Additional information**:
 I tried to launch the rest server "manually" from my own python script, but i didn't want to build a workaround that's too complicated. If there is any way to launch the Web Ui (In view mode) via Python properly i would be very interested as well, as the nnictl stuff seems to be legacy. 

Started the server with this line:
`process,startTime = launcher.start_rest_server(8010,'local','view',self.experimentID)`

**Comment by SparkSnail** [comment]
Didn't reproduce this issue in NNI v2.0 to view v2.0 stopped experiments. NNI2.0 has refactored experiment data structure, might cause some backward compatibility issue when view old experiments. Please ensure the experiment you want to view is started from NNI v2.0.

**Comment by OliverGrein** [comment]
After Trying spending some more time trying to fix the issue i have found out the Following things (might be helpful for anyone who also has this issue):

The Exception is caused by a missing .config file in the experiments folder (.../nni-experiments/<exp.ID>/)
At this moment i am not sure why this file is missing, since there arent any exceptions when running or stopping the experiment, but this is how i set up my test experiment: 
After trying it on 4 different machines i am pretty sure that it doesnt have anything to do with my nni version
I saved the search_space.JSON because 

```
        tuner = HyperoptTuner('tpe')

        with open('search_space.JSON', 'w') as outfile:
            json.dump(nniJson,outfile)

        experiment = Experiment(tuner = tuner, training_service='local')
        experiment.config.experiment_name = 'test2'
        experiment.config.trial_concurrency = 1
        experiment.config.max_trial_number = 2
        experiment.config.search_space_file = 'search_space.JSON'
        experiment.config.trial_command = 'python nniStarter.py'
        experiment.config.trial_code_directory = Path(__file__).parent

        experiment.start(8010)
        try:
            while True:
                time.sleep(10)
                status = experiment.get_status()
                if status == 'DONE' or status == 'STOPPED':
                    return True
                if status == 'ERROR':
                    return False
        finally:
            self.experimentID = experiment.id
            
            experiment.stop()
```

I managed to get nnictl view running by creating the .config file myself. I got the structure from an older nni 1.X experiment: 

```
            config = {
                "experimentId": "Zc9iasH4",
                "experimentConfig": {
                    "authorName": "default",
                    "experimentName": "test2",
                    "trialConcurrency": 1,
                    "maxExecDuration": 3600,
                    "maxTrialNum": 10,
                    "trainingServicePlatform": "local",
                    "searchSpacePath": "C:/Users/XCGGV/Backend/search_space.json",
                    "useAnnotation": False,
                    "tuner": {
                        "builtinTunerName": "TPE",
                        "classArgs": {
                            "optimize_mode": "maximize"
                        }
                    },
                    "trial": {
                        "command": "python main.py",
                        "codeDir": "C:/Users/XCGGV/Backend/.",
                        "gpuNum": 0
                    }
                },
                "restServerPort": 8082,
                "restServerPid": 11656,
                "webuiUrl": [
                    "http://130.83.137.44:8082",
                    "http://127.0.0.1:8082"
                ]
            }
            with open('C:/Users/XCGGV/nni-experiments/'+ self.experimentID + '/.config', 'w') as outfile:
                json.dump(config,outfile)
            print(self.experimentID)
            os.system("nnictl view "+self.experimentID+  " --port 8082")
```

Had to add the Port to the nni view command, since it would just start on port 8080 otherwise which was blocked
 
i am sorry for the bad/messy code. I used this file to fix my issues with nni so i just tried out lots of stuff, which left the code in this state.

**Comment by kvartet** [comment]
@SparkSnail, could you help update this issue? Thanks~

**Comment by SparkSnail** [comment]
`nnictl view` command is already fixed in latest version of NNI, please upgrade to latest version and try again.

**Comment by kvartet** [comment]
hello @OliverGrein, could you follow this and try again? Thank you!

> `nnictl view` command is already fixed in the latest version of NNI, please upgrade to the latest version and try again.

**Comment by scarlett2018** [comment]
> hello @OliverGrein, could you follow this and try again? Thank you!
> 
> > `nnictl view` command is already fixed in the latest version of NNI, please upgrade to the latest version and try again.

as there are no responds so far, closing the issue as overdued. feel free to reopen if it is still an issue.
