### ISSUE TITLE
ModelSpeedup fails with `RecursiveScriptModule` in PyTorch

### ISSUE THREAD

**Issue by xDuck** [microsoft/nni#3384]
Attempting to use ModelSpeedup with https://github.com/eublefar/flowtron/tree/feature/onnx_export gives an error that `RecursiveScriptModule` has no attribute `._name`. Using a `LevelPruner`, code snippet below:

```
        config_list = [{"sparsity": 0.8, "op_types": ["default"]}]
        pruner = LevelPruner(model, config_list)
        pruner.compress()

        pruner.export_model(
            model_path="pruned_flowtron.pth", mask_path="pruned_flowtron.mask.pth"
        )

        # Fails on this line v
        m_speedup = ModelSpeedup(
            model, [residual, speaker_vecs, text], "pruned_flowtron.mask.pth"
        )

        m_speedup.speedup_model()
        start = time.time()
        out = model(residual, speaker_vecs, text)
        print("elapsed time: ", time.time() - start)
```

**Environment**:
- NNI version: master
- NNI mode (local|remote|pai): local
- Client OS: Centos7
- Server OS (for remote mode only):
- Python version: 3.6.5
- PyTorch/TensorFlow version: PyTorch 1.7
- Is conda/virtualenv/venv used?: venv
- Is running in Docker?: No

**Log message**:
```
[2021-02-16 13:51:32] INFO (nni.compression.pytorch.compressor/MainThread) Model state_dict saved to pruned_model.pth
[2021-02-16 13:51:32] INFO (nni.compression.pytorch.compressor/MainThread) Mask dict saved to pruned_model.mask.pth
Traceback (most recent call last):
  File "nni_compress.py", line 173, in <module>
    args.no_export,
  File "nni_compress.py", line 114, in export
    model, [residual, speaker_vecs, text], "pruned_flowtron.mask.pth"
  File "/root/git/flowtron/env/lib64/python3.6/site-packages/nni/compression/pytorch/speedup/compressor.py", line 38, in __init__
    self.torch_graph = build_module_graph(model, dummy_input)
  File "/root/git/flowtron/env/lib64/python3.6/site-packages/nni/common/graph_utils.py", line 25, in build_module_graph
    return TorchModuleGraph(model, dummy_input)
  File "/root/git/flowtron/env/lib64/python3.6/site-packages/nni/common/graph_utils.py", line 273, in __init__
    self.name_to_node, self.input_to_node, self.output_to_node = self._build_graph()
  File "/root/git/flowtron/env/lib64/python3.6/site-packages/nni/common/graph_utils.py", line 767, in _build_graph
    for name, module in self.trace.named_modules()
  File "/root/git/flowtron/env/lib64/python3.6/site-packages/nni/common/graph_utils.py", line 767, in <dictcomp>
    for name, module in self.trace.named_modules()
  File "/root/git/flowtron/env/lib64/python3.6/site-packages/torch/jit/_script.py", line 558, in __getattr__
    return super(RecursiveScriptModule, self).__getattr__(attr)
  File "/root/git/flowtron/env/lib64/python3.6/site-packages/torch/jit/_script.py", line 288, in __getattr__
    return super(ScriptModule, self).__getattr__(attr)
  File "/root/git/flowtron/env/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'RecursiveScriptModule' object has no attribute '_name'
```

**Comment by zheng-ningxin** [comment]
Hi~ thanks for the feedback. Looks like it fails in the `jit.trace`.  NNI ModelSpeedup is based on [torch.jit.trace](https://pytorch.org/docs/stable/generated/torch.jit.trace.html) which does not support the value-dependent models. You can try whether jit.trace supports your model. Thanks~

**Comment by kvartet** [comment]
hello @xDuck, could you follow this and update the status of this issue? Thank you!

> Hi~ thanks for the feedback. Looks like it fails in the `jit.trace`. NNI ModelSpeedup is based on [torch.jit.trace](https://pytorch.org/docs/stable/generated/torch.jit.trace.html) which does not support the value-dependent models. You can try whether jit.trace supports your model. Thanks~

**Comment by xDuck** [comment]
> hello @xDuck, could you follow this and update the status of this issue? Thank you!
> 
> > Hi~ thanks for the feedback. Looks like it fails in the `jit.trace`. NNI ModelSpeedup is based on [torch.jit.trace](https://pytorch.org/docs/stable/generated/torch.jit.trace.html) which does not support the value-dependent models. You can try whether jit.trace supports your model. Thanks~

Sorry did not see response - we ended up solving the problem by re-structuring the model, I forget the specifics.
