### ISSUE TITLE
Dispatcher exiting...

### ISSUE THREAD

**Issue by codergh** [microsoft/nni#3401]
**Environment**: 
- NNI version: 1.5
- NNI mode (local|remote|pai): local
- Client OS: ubuntu
- Server OS (for remote mode only):
- Python version: 3.7
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?: yes

**Log message**:
 - nnimanager.log:
 ```
 [2/24/2021, 8:22:14 AM] DEBUG [ 'Database directory: /root/nni/experiments/nhFkblX6/db' ]
[2/24/2021, 8:22:14 AM] INFO [ 'Datastore initialization done' ]
[2/24/2021, 8:22:14 AM] INFO [ 'RestServer start' ]
[2/24/2021, 8:22:14 AM] INFO [ 'Construct local machine training service.' ]
[2/24/2021, 8:22:14 AM] INFO [ 'RestServer base port is 8080' ]
[2/24/2021, 8:22:14 AM] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[2/24/2021, 8:22:16 AM] DEBUG [ 'GET: /check-status: body:\n{}' ]
[2/24/2021, 8:22:16 AM] DEBUG [ 'PUT: /experiment/cluster-metadata: body:\n{\n    "trial_config": {\n        "codeDir": "/nni_manager/.",\n        "command": "python /algorithm-api/src/michi/algorithm/v1/builder/plsr_builder.py /nni_manager/60337da638e94b00019f0a49_6035e4f548f8a600018bb096_payload.json",\n        "gpuNum": 0\n    }\n}' ]
[2/24/2021, 8:22:16 AM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"codeDir":"/nni_manager/.","command":"python /algorithm-api/src/michi/algorithm/v1/builder/plsr_builder.py /nni_manager/60337da638e94b00019f0a49_6035e4f548f8a600018bb096_payload.json","gpuNum":0}' ]
[2/24/2021, 8:22:16 AM] INFO [ 'required GPU number is 0' ]
[2/24/2021, 8:22:16 AM] DEBUG [ 'POST: /experiment: body:\n{\n    "authorName": "MC",\n    "experimentName": "MCNNI",\n    "trialConcurrency": 1,\n    "maxExecDuration": 3600,\n    "maxTrialNum": 10,\n    "searchSpace": "{\\"scale\\": {\\"_value\\": [\\"True\\", \\"False\\"], \\"_type\\": \\"choice\\"}, \\"max_iter\\": {\\"_value\\": [5, 1000], \\"_type\\": \\"randint\\"}, \\"tol\\": {\\"_value\\": [1e-08, 0.1], \\"_type\\": \\"uniform\\"}}",\n    "trainingServicePlatform": "local",\n    "tuner": {\n        "builtinTunerName": "TPE",\n        "classArgs": {\n            "optimize_mode": "maximize"\n        }\n    },\n    "versionCheck": false,\n    "clusterMetaData": [\n        {\n            "key": "codeDir",\n            "value": "/nni_manager/."\n        },\n        {\n            "key": "command",\n            "value": "python /algorithm-api/src/michi/algorithm/v1/builder/plsr_builder.py /nni_manager/60337da638e94b00019f0a49_6035e4f548f8a600018bb096_payload.json"\n        }\n    ]\n}' ]
[2/24/2021, 8:22:16 AM] INFO [ 'Starting experiment: nhFkblX6' ]
[2/24/2021, 8:22:16 AM] DEBUG [ 'Setup tuner...' ]
[2/24/2021, 8:22:16 AM] DEBUG [ 'dispatcher command: python3 -m nni --exp_params eyJhdXRob3JOYW1lIjoiTUMiLCJleHBlcmltZW50TmFtZSI6Ik1DTk5JIiwidHJpYWxDb25jdXJyZW5jeSI6MSwibWF4RXhlY0R1cmF0aW9uIjozNjAwLCJtYXhUcmlhbE51bSI6MTAsInRyYWluaW5nU2VydmljZVBsYXRmb3JtIjoibG9jYWwiLCJ0dW5lciI6eyJidWlsdGluVHVuZXJOYW1lIjoiVFBFIiwiY2xhc3NBcmdzIjp7Im9wdGltaXplX21vZGUiOiJtYXhpbWl6ZSJ9fSwidmVyc2lvbkNoZWNrIjpmYWxzZSwiY2x1c3Rlck1ldGFEYXRhIjpbeyJrZXkiOiJjb2RlRGlyIiwidmFsdWUiOiIvbm5pX21hbmFnZXIvLiJ9LHsia2V5IjoiY29tbWFuZCIsInZhbHVlIjoicHl0aG9uIC9hbGdvcml0aG0tYXBpL3NyYy9taWNoaS9hbGdvcml0aG0vdjEvYnVpbGRlci9wbHNyX2J1aWxkZXIucHkgL25uaV9tYW5hZ2VyLzYwMzM3ZGE2MzhlOTRiMDAwMTlmMGE0OV82MDM1ZTRmNTQ4ZjhhNjAwMDE4YmIwOTZfcGF5bG9hZC5qc29uIn1dfQ==' ]
[2/24/2021, 8:22:16 AM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[2/24/2021, 8:22:16 AM] INFO [ 'Add event listeners' ]
[2/24/2021, 8:22:16 AM] DEBUG [ 'Send tuner command: INITIALIZE: {"scale": {"_value": ["True", "False"], "_type": "choice"}, "max_iter": {"_value": [5, 1000], "_type": "randint"}, "tol": {"_value": [1e-08, 0.1], "_type": "uniform"}}' ]
[2/24/2021, 8:22:16 AM] DEBUG [ 'ipcInterface command type: [IN], content:[{"scale": {"_value": ["True", "False"], "_type": "choice"}, "max_iter": {"_value": [5, 1000], "_type": "randint"}, "tol": {"_value": [1e-08, 0.1], "_type": "uniform"}}]' ]
[2/24/2021, 8:22:16 AM] DEBUG [ 'ipcInterface command type: [PI], content:[]' ]
[2/24/2021, 8:22:16 AM] INFO [ 'Run local machine training service.' ]
[2/24/2021, 8:22:17 AM] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[2/24/2021, 8:22:17 AM] DEBUG [ 'ipcInterface command type: [GE], content:[1]' ]
[2/24/2021, 8:22:17 AM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"scale": "False", "max_iter": 901, "tol": 0.04879341970589441}, "parameter_index": 0}' ]
[2/24/2021, 8:22:21 AM] DEBUG [ 'ipcInterface command type: [PI], content:[]' ]
[2/24/2021, 8:22:21 AM] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"scale\\": \\"False\\", \\"max_iter\\": 901, \\"tol\\": 0.04879341970589441}, \\"parameter_index\\": 0}","index":0}}' ]
[2/24/2021, 8:22:21 AM] DEBUG [ 'submitTrialJob: return: {"id":"JcD4J","status":"WAITING","submitTime":1614154941266,"workingDirectory":"/root/nni/experiments/nhFkblX6/trials/JcD4J","form":{"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"scale\\": \\"False\\", \\"max_iter\\": 901, \\"tol\\": 0.04879341970589441}, \\"parameter_index\\": 0}","index":0}},"url":"file://localhost:/root/nni/experiments/nhFkblX6/trials/JcD4J","gpuIndices":[]} ' ]
[2/24/2021, 8:22:21 AM] DEBUG [ 'storeTrialJobEvent: event: WAITING, data: {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"scale": "False", "max_iter": 901, "tol": 0.04879341970589441}, "parameter_index": 0}, jobDetail: {"id":"JcD4J","status":"WAITING","submitTime":1614154941266,"workingDirectory":"/root/nni/experiments/nhFkblX6/trials/JcD4J","form":{"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"scale\\": \\"False\\", \\"max_iter\\": 901, \\"tol\\": 0.04879341970589441}, \\"parameter_index\\": 0}","index":0}},"url":"file://localhost:/root/nni/experiments/nhFkblX6/trials/JcD4J","gpuIndices":[]}' ]
[2/24/2021, 8:22:26 AM] DEBUG [ 'ipcInterface command type: [PI], content:[]' ]
```

 - dispatcher.log:
 ```
[02/24/2021, 08:22:16 AM] DEBUG (nni.main/MainThread) START
[02/24/2021, 08:22:16 AM] DEBUG (nni.main/MainThread) decoded exp_params: [{"authorName":"MC","experimentName":"MCNNI","trialConcurrency":1,"maxExecDuration":3600,"maxTrialNum":10,"trainingServicePlatform":"local","tuner":{"builtinTunerName":"TPE","classArgs":{"optimize_mode":"maximize"}},"versionCheck":false,"clusterMetaData":[{"key":"codeDir","value":"/nni_manager/."},{"key":"command","value":"python /algorithm-api/src/michi/algorithm/v1/builder/plsr_builder.py /nni_manager/60337da638e94b00019f0a49_6035e4f548f8a600018bb096_payload.json"}]}]
[02/24/2021, 08:22:16 AM] DEBUG (nni.main/MainThread) exp_params json obj: [{
    "authorName": "MC",
    "experimentName": "MCNNI",
    "trialConcurrency": 1,
    "maxExecDuration": 3600,
    "maxTrialNum": 10,
    "trainingServicePlatform": "local",
    "tuner": {
        "builtinTunerName": "TPE",
        "classArgs": {
            "optimize_mode": "maximize"
        }
    },
    "versionCheck": false,
    "clusterMetaData": [
        {
            "key": "codeDir",
            "value": "/nni_manager/."
        },
        {
            "key": "command",
            "value": "python /algorithm-api/src/michi/algorithm/v1/builder/plsr_builder.py /nni_manager/60337da638e94b00019f0a49_6035e4f548f8a600018bb096_payload.json"
        }
    ]
}]
[02/24/2021, 08:22:17 AM] DEBUG (nni.msg_dispatcher/MainThread) Assessor is not configured
[02/24/2021, 08:22:17 AM] INFO (nni.msg_dispatcher_base/MainThread) Start dispatcher
[02/24/2021, 08:22:17 AM] DEBUG (nni.protocol/MainThread) Received command, header: [b'IN000167']
[02/24/2021, 08:22:17 AM] DEBUG (nni.protocol/MainThread) Received command, data: [{"scale": {"_value": ["True", "False"], "_type": "choice"}, "max_iter": {"_value": [5, 1000], "_type": "randint"}, "tol": {"_value": [1e-08, 0.1], "_type": "uniform"}}]
[02/24/2021, 08:22:17 AM] DEBUG (nni.protocol/MainThread) Received command, header: [b'PI000000']
[02/24/2021, 08:22:17 AM] DEBUG (nni.msg_dispatcher_base/Thread-1) process_command: command: [CommandType.Initialize], data: [OrderedDict([('scale', OrderedDict([('_value', ['True', 'False']), ('_type', 'choice')])), ('max_iter', OrderedDict([('_value', [5, 1000]), ('_type', 'randint')])), ('tol', OrderedDict([('_value', [1e-08, 0.1]), ('_type', 'uniform')]))])]
[02/24/2021, 08:22:17 AM] DEBUG (nni.protocol/MainThread) Received command, data: []
[02/24/2021, 08:22:17 AM] DEBUG (nni.protocol/Thread-1) Sending command, data: [b'ID000000']
[02/24/2021, 08:22:17 AM] DEBUG (nni.msg_dispatcher_base/Thread-1) process_command: command: [CommandType.Ping], data: []
[02/24/2021, 08:22:17 AM] DEBUG (nni.protocol/MainThread) Received command, header: [b'GE000001']
[02/24/2021, 08:22:17 AM] DEBUG (nni.protocol/MainThread) Received command, data: [1]
[02/24/2021, 08:22:17 AM] DEBUG (nni.msg_dispatcher_base/Thread-1) process_command: command: [CommandType.RequestTrialJobs], data: [1]
[02/24/2021, 08:22:17 AM] DEBUG (nni.msg_dispatcher/Thread-1) requesting for generating params of [0]
[02/24/2021, 08:22:17 AM] DEBUG (nni.tuner/Thread-1) generating param for 0
[02/24/2021, 08:22:17 AM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001147 seconds
[02/24/2021, 08:22:17 AM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[02/24/2021, 08:22:17 AM] DEBUG (nni.protocol/Thread-1) Sending command, data: [b'TR000153{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"scale": "False", "max_iter": 901, "tol": 0.04879341970589441}, "parameter_index": 0}']
[02/24/2021, 08:22:21 AM] DEBUG (nni.protocol/MainThread) Received command, header: [b'PI000000']
[02/24/2021, 08:22:21 AM] DEBUG (nni.protocol/MainThread) Received command, data: []
[02/24/2021, 08:22:21 AM] DEBUG (nni.msg_dispatcher_base/Thread-1) process_command: command: [CommandType.Ping], data: []
[02/24/2021, 08:22:26 AM] DEBUG (nni.protocol/MainThread) Received command, header: [b'PI000000']
[02/24/2021, 08:22:26 AM] DEBUG (nni.protocol/MainThread) Received command, data: []
[02/24/2021, 08:22:26 AM] DEBUG (nni.msg_dispatcher_base/Thread-1) process_command: command: [CommandType.Ping], data: []
[02/24/2021, 08:22:26 AM] DEBUG (nni.protocol/MainThread) Received command, header: [b'']
[02/24/2021, 08:22:26 AM] DEBUG (nni.protocol/MainThread) Pipe EOF encountered
[02/24/2021, 08:22:26 AM] INFO (nni.msg_dispatcher_base/MainThread) Dispatcher exiting...
[02/24/2021, 08:22:29 AM] INFO (nni.msg_dispatcher_base/MainThread) Terminated by NNI manager
```
 - nnictl stdout and stderr:
 ```
ERROR: There are multiple experiments, please set the experiment id...
----------------------------------------------------------------------------------------
                Experiment information
Id: ya5WJbiC    Name: MCNNI    Status: INITIALIZED    Port: 8080    Platform: local    StartTime: 2021-02-24 08:11:46    EndTime: N/A
Id: nhFkblX6    Name: MCNNI    Status: INITIALIZED    Port: 8080    Platform: local    StartTime: 2021-02-24 08:22:13    EndTime: N/A

----------------------------------------------------------------------------------------
```

 

**What issue meet, what's expected?**:

**How to reproduce it?**: 

**Additional information**:

**Comment by SparkSnail** [comment]
You have multiple experiments, use `nnictl log stdout nhFkblX6` to get specific experiment log.

**Comment by codergh** [comment]
> You have multiple experiments, use `nnictl log stdout nhFkblX6` and `nnictl log stderr nhFkblX6` to get specific experiment log.
I execute commend `nnictl create --config {file} --debug` in terminal, the log is same

**Comment by SparkSnail** [comment]
Yes, we need to see the log content of `nnictl`. Please execute command `nnictl log stderr nhFkblX6` and `nnictl log stdout nhFkblX6`

**Comment by codergh** [comment]
> Yes, we need to see the log content of `nnictl`. Please execute command `nnictl log stderr nhFkblX6` and `nnictl log stdout nhFkblX6`
I got the error below after execute ```nnictl log stderr nhFkblX6```
```
-----------------------------------------------------------------------
                Experiment start time 2021-02-24 08:22:13
-----------------------------------------------------------------------
(node:259) ExperimentalWarning: The fs.promises API is experimental
internal/fs/watchers.js:173
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/root/nni/experiments/nhFkblX6/trials/JcD4J/.nni/metrics'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1251:11)
    at TailStream.waitForMoreData (/usr/local/nni/node_modules/tail-stream/index.js:123:31)
    at TailStream.<anonymous> (/usr/local/nni/node_modules/tail-stream/index.js:275:22)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:460:17)
```

**Comment by SparkSnail** [comment]
This issue caused because NNI hit the your computer's file watchers limit. Use `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p` to increase watcher max number.

**Comment by codergh** [comment]
> This issue caused because NNI hit the your computer's file watchers limit. Use `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p` to increase watcher max number.

Done it, Thank you very much.
