### ISSUE TITLE
'_SingleProcessDataLoaderIter' object has no attribute '_num_workers'

### ISSUE THREAD

**Issue by tiaotiaosong** [microsoft/nni#3402]
**Environment**:
- NNI version:2.0
- NNI mode (local|remote|pai):local
- Client OS:MAC
- Server OS (for remote mode only):
- Python version:3.7
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:
- 

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 /Users/admin/anaconda3/lib/python3.7/site-packages/nni/algorithms/feature_engineering/gradient_selector/learnability.py:118: RuntimeWarning: divide by zero encountered in true_divide
  a = coeff / scipy.special.binom(Nminibatch, np.arange(coeff.size) + 2)
Traceback (most recent call last):
  File "/Users/admin/PycharmProjects/sd/first_breach_case/test.py", line 37, in <module>
    fgs.fit(X_train, y_train)
  File "/Users/admin/anaconda3/lib/python3.7/site-packages/nni/algorithms/feature_engineering/gradient_selector/gradient_selector.py", line 260, in fit
    self._fit(X, y, groups=groups)
  File "/Users/admin/anaconda3/lib/python3.7/site-packages/nni/algorithms/feature_engineering/gradient_selector/gradient_selector.py", line 318, in _fit
    soft_groups=groups if self.soft_grouping else None)
  File "/Users/admin/anaconda3/lib/python3.7/site-packages/nni/algorithms/feature_engineering/gradient_selector/fgtrain.py", line 202, in _train
    S.train(f_stop=f_stop, f_callback=f_callback)
  File "/Users/admin/anaconda3/lib/python3.7/site-packages/nni/algorithms/feature_engineering/gradient_selector/learnability.py", line 468, in train
    xsub, ysub = next(dataloader_iterator)
  File "/Users/admin/anaconda3/lib/python3.7/site-packages/nni/algorithms/feature_engineering/gradient_selector/fginitialize.py", line 600, in __next__
    if self.iter._num_workers == 0:  # same-process loading
AttributeError: '_SingleProcessDataLoaderIter' object has no attribute '_num_workers'

**What issue meet, what's expected?**:

**How to reproduce it?**: 

**Additional information**:

**Comment by tiaotiaosong** [comment]
`from sklearn.model_selection import train_test_split

from nni.algorithms.feature_engineering.gradient_selector import FeatureGradientSelector

x, y = [[1, 0.4], [1, 1], [2, 2], [2, 3], [1, 2], [1, 3]], [0, 1, 0, 1, 1, 1]


X_train, X_test, y_train, y_test = train_test_split(
    np.array(x), np.array(y), test_size=0.33, random_state=42
)
fgs = FeatureGradientSelector(n_features=1)
fgs.fit(X_train, y_train)
print(fgs.get_selected_features())`

**Comment by scarlett2018** [comment]
@tiaotiaosong - are you still facing the issue with latest nni release? thanks.
