### ISSUE TITLE
L1FilterPruning failed on shufflenet

### ISSUE THREAD

**Issue by YuyaKobayashi** [microsoft/nni#3453]
**Environment**:
- NNI version: 2.1
- NNI mode (local|remote|pai): local
- Client OS: Ubuntu 18.04.3
- Server OS (for remote mode only):
- Python version: 3.7.4
- PyTorch/TensorFlow version: 1.4.0
- Is conda/virtualenv/venv used?: No
- Is running in Docker?: Yes

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:
When I run the below code, the below error is shown:
```python
#!/usr/bin/env python3

from pathlib import Path
import numpy as np
import torch
import torchvision

from nni.algorithms.compression.pytorch.pruning import L1FilterPruner
from nni.compression.pytorch import ModelSpeedup,  apply_compression_results

from shufflenet import ShuffleNetG2


def create_model():
    return torchvision.models.shufflenet_v2_x1_0(pretrained=True)


def create_dummy_input():
    return torch.zeros((1, 3, 224, 224))


def main():
    MODEL_PATH = "model.pth"
    MASK_PATH = "mask.pth"

    model = create_model()
    device = "cpu"

    dummy_input   = create_dummy_input().to(device)
    pruner_config = [{"sparsity": 0.2, "op_types": ["Conv2d"]}]
    pruner        = L1FilterPruner(model, pruner_config, dependency_aware=True, dummy_input=dummy_input)
    model         = pruner.compress()
    pruner.export_model(MODEL_PATH, MASK_PATH)

    new_model = create_model
    new_model.load_state_dict(torch.load(MODEL_PATH))
    m_speedup = ModelSpeedup(new_model, dummy_input, MASK_PATH)
    m_speedup.speedup_model()

    Path(MODEL_PATH).unlink()
    Path(MASK_PATH).unlink()

if __name__ == '__main__':
    main()
```

```shell
[2021-03-16 02:33:54] INFO (nni.algorithms.compression.pytorch.pruning.one_shot/MainThread) Pruning the dependent layers: conv1.0
[2021-03-16 02:33:54] INFO (torch filter pruners/MainThread) Prune the  channels for all dependent
[2021-03-16 02:33:54] INFO (nni.algorithms.compression.pytorch.pruning.one_shot/MainThread) Pruning the dependent layers: stage2.0.branch1.0
[2021-03-16 02:33:54] INFO (torch filter pruners/MainThread) Prune the  channels for all dependent
[2021-03-16 02:33:54] INFO (nni.algorithms.compression.pytorch.pruning.one_shot/MainThread) Pruning the dependent layers: stage2.0.branch1.2
[2021-03-16 02:33:54] INFO (torch filter pruners/MainThread) Prune the  channels for all dependent
Traceback (most recent call last):
  File "simple.py", line 44, in <module>
    main()
  File "simple.py", line 32, in main
    model         = pruner.compress()
  File "/my_python_lib/nni/compression/pytorch/compressor.py", line 327, in compress
    self.update_mask()
  File "/my_python_lib/nni/algorithms/compression/pytorch/pruning/one_shot.py", line 185, in update_mask
    self._dependency_update_mask()
  File "/my_python_lib/nni/algorithms/compression/pytorch/pruning/one_shot.py", line 256, in _dependency_update_mask
    _wrappers, _names, wrappers_idx=_wrapper_idxes)
  File "/my_python_lib/nni/algorithms/compression/pytorch/pruning/one_shot.py", line 225, in _dependency_calc_mask
    sparsities, wrappers, wrappers_idx, channel_dsets=channel_dsets, groups=groups)
  File "/my_python_lib/nni/algorithms/compression/pytorch/pruning/structured_pruning.py", line 70, in calc_mask
    return self._dependency_calc_mask(sparsity, wrapper, wrapper_idx, **depen_kwargs)
  File "/my_python_lib/nni/algorithms/compression/pytorch/pruning/structured_pruning.py", line 285, in _dependency_calc_mask
    base_mask, current_weight, num_prune, _w, _w_idx, channel_masks)
  File "/my_python_lib/nni/algorithms/compression/pytorch/pruning/structured_pruning.py", line 357, in get_mask
    w_abs_structured = w_abs_structured * channel_masks
RuntimeError: The size of tensor a (58) must match the size of tensor b (0) at non-singleton dimension 0
```

**How to reproduce it?**: 
Run the code.

**Additional information**:

**Comment by J-shang** [comment]
Hi @YuyaKobayashi , set `dependency_aware=False` should work for `compress`. And nni doesn't support speedup shufflenet now. We will try to support shufflenet on `speedup` and `dependency_aware`, thanks for your issue.

**Comment by YuyaKobayashi** [comment]
Thank you, J-shang-san.
I will try it.

**Comment by kvartet** [comment]
hello @YuyaKobayashi, could you update the status of this issue? Thank you!

**Comment by YuyaKobayashi** [comment]
Sorry, I have forgotten close this issue.
