### ISSUE TITLE
Dispatcher stream error, tuner may have crashed (Error on first time)

### ISSUE THREAD

**Issue by koklimabc** [microsoft/nni#3475]
**Environment**: Ubuntu 20.04
- NNI version: 2.1
- NNI mode (local|remote|pai):
- Client OS: Desbian
- Server OS (for remote mode only): N\A
- Python version: 3.7
- PyTorch/TensorFlow version: 1.8.0 & 2.4.1
- Is conda/virtualenv/venv used?: N\A
- Is running in Docker?: N\A

**Log message**:
 - nnimanager.log: 

[2021-03-25 12:07:53] INFO [ 'Datastore initialization done' ]
[2021-03-25 12:07:53] INFO [ 'RestServer start' ]
[2021-03-25 12:07:53] INFO [ 'Construct local machine training service.' ]
[2021-03-25 12:07:53] INFO [ 'RestServer base port is 8080' ]
[2021-03-25 12:07:53] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[2021-03-25 12:07:53] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python3 mnist-keras.py","codeDir":"/home/pi/Downloads/nni_sample/nni/examples/trials/mnist-keras/.","gpuNum":0}' ]
[2021-03-25 12:07:53] INFO [ 'required GPU number is 0' ]
[2021-03-25 12:07:53] INFO [ 'Starting experiment: 236L9qwk' ]
[2021-03-25 12:07:53] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[2021-03-25 12:07:53] INFO [ 'Add event listeners' ]
[2021-03-25 12:07:53] ERROR [ 'Dispatcher error: This socket has been ended by the other party' ]
[2021-03-25 12:07:53] ERROR [ 'Error: Dispatcher stream error, tuner may have crashed.\n    at EventEmitter.dispatcher.onError (/usr/local/lib/python3.7/dist-packages/nni_node/core/nnimanager.js:550:32)\n    at EventEmitter.emit (events.js:198:13)\n    at Socket.IpcInterface.outgoingStream.on (/usr/local/lib/python3.7/dist-packages/nni_node/core/ipcInterface.js:42:72)\n    at Socket.emit (events.js:198:13)\n    at Socket.writeAfterFIN [as write] (net.js:399:8)\n    at IpcInterface.sendCommand (/usr/local/lib/python3.7/dist-packages/nni_node/core/ipcInterface.js:49:38)\n    at NNIManager.sendInitTunerCommands (/usr/local/lib/python3.7/dist-packages/nni_node/core/nnimanager.js:558:25)\n    at NNIManager.run (/usr/local/lib/python3.7/dist-packages/nni_node/core/nnimanager.js:523:14)\n    at NNIManager.startExperiment (/usr/local/lib/python3.7/dist-packages/nni_node/core/nnimanager.js:135:14)' ]
[2021-03-25 12:07:53] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]
[2021-03-25 12:07:53] WARNING [ 'Commands jammed in buffer!' ]
[2021-03-25 12:07:53] INFO [ 'Run local machine training service.' ]

 - dispatcher.log:
 - <!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="shortcut icon" href="/icon.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><link rel="manifest" href="/manifest.json"/><title>Neural Network Intelligence</title><link href="/static/css/4.5aeae972.chunk.css" rel="stylesheet"><link href="/static/css/main.82004897.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(i){function e(e){for(var t,r,n=e[0],o=e[1],a=e[2],u=0,c=[];u<n.length;u++)r=n[u],d[r]&&c.push(d[r][0]),d[r]=0;for(t in o)Object.prototype.hasOwnProperty.call(o,t)&&(i[t]=o[t]);for(h&&h(e);c.length;)c.shift()();return l.push.apply(l,a||[]),f()}function f(){for(var e,t=0;t<l.length;t++){for(var r=l[t],n=!0,o=1;o<r.length;o++){var a=r[o];0!==d[a]&&(n=!1)}n&&(l.splice(t--,1),e=p(p.s=r[0]))}return e}var r={},s={3:0},d={3:0},l=[];function p(e){if(r[e])return r[e].exports;var t=r[e]={i:e,l:!1,exports:{}};return i[e].call(t.exports,t,t.exports,p),t.l=!0,t.exports}p.e=function(l){var e=[];s[l]?e.push(s[l]):0!==s[l]&&{5:1,6:1,7:1,8:1}[l]&&e.push(s[l]=new Promise(function(e,n){for(var t="static/css/"+({}[l]||l)+"."+{0:"31d6cfe0",1:"31d6cfe0",5:"5c750b80",6:"05141231",7:"50f571cc",8:"3106bf50",9:"31d6cfe0",10:"31d6cfe0",11:"31d6cfe0"}[l]+".chunk.css",o=p.p+t,r=document.getElementsByTagName("link"),a=0;a<r.length;a++){var u=(i=r[a]).getAttribute("data-href")||i.getAttribute("href");if("stylesheet"===i.rel&&(u===t||u===o))return e()}var c=document.getElementsByTagName("style");for(a=0;a<c.length;a++){var i;if((u=(i=c[a]).getAttribute("data-href"))===t||u===o)return e()}var f=document.createElement("link");f.rel="stylesheet",f.type="text/css",f.onload=e,f.onerror=function(e){var t=e&&e.target&&e.target.src||o,r=new Error("Loading CSS chunk "+l+" failed.\n("+t+")");r.request=t,delete s[l],f.parentNode.removeChild(f),n(r)},f.href=o,document.getElementsByTagName("head")[0].appendChild(f)}).then(function(){s[l]=0}));var r=d[l];if(0!==r)if(r)e.push(r[2]);else{var t=new Promise(function(e,t){r=d[l]=[e,t]});e.push(r[2]=t);var n,a=document.createElement("script");a.charset="utf-8",a.timeout=120,p.nc&&a.setAttribute("nonce",p.nc),a.src=p.p+"static/js/"+({}[l]||l)+"."+{0:"a6fc6d39",1:"33e11246",5:"dd14e50b",6:"639b8f9b",7:"b867d835",8:"919728e5",9:"be12774e",10:"9ae5ecb9",11:"ce3b39f5"}[l]+".chunk.js",n=function(e){a.onerror=a.onload=null,clearTimeout(u);var t=d[l];if(0!==t){if(t){var r=e&&("load"===e.type?"missing":e.type),n=e&&e.target&&e.target.src,o=new Error("Loading chunk "+l+" failed.\n("+r+": "+n+")");o.type=r,o.request=n,t[1](o)}d[l]=void 0}};var u=setTimeout(function(){n({type:"timeout",target:a})},12e4);a.onerror=a.onload=n,document.head.appendChild(a)}return Promise.all(e)},p.m=i,p.c=r,p.d=function(e,t,r){p.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},p.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},p.t=function(t,e){if(1&e&&(t=p(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var r=Object.create(null);if(p.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var n in t)p.d(r,n,function(e){return t[e]}.bind(null,n));return r},p.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return p.d(t,"a",t),t},p.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},p.p="/",p.oe=function(e){throw console.error(e),e};var t=window.webpackJsonp=window.webpackJsonp||[],n=t.push.bind(t);t.push=e,t=t.slice();for(var o=0;o<t.length;o++)e(t[o]);var h=n;f()}([])</script><script src="/static/js/4.426d9949.chunk.js"></script><script src="/static/js/main.6ab965e0.chunk.js"></script></body></html>
 - nnictl stdout and stderr:

cd /home/User/Downloads/nni_sample/nni/examples/trials/mnist-keras
 nnictl create --config config.yml

**Problem**
How Should I able to fix this issues since I'm working to learn the basic of NNI.
TQ.

**Comment by liuzhe-lz** [comment]
Do you mean `dispatcher.log` contains `<!doctype html><title>...` stuff?

**Comment by kvartet** [comment]
hello @koklimabc, could upgrade the version of NNI and try again? If this issue still exists, please upload `dispatcher.log` as an attachment? Thank you!

**Comment by Chenwf1025** [comment]
i'm using the latest version of NNI, but encounterd the similar error.
`[2021-11-29 09:43:54] INFO (NNIDataStore) Datastore initialization done
[2021-11-29 09:43:54] INFO (RestServer) RestServer start
[2021-11-29 09:43:54] WARNING (NNITensorboardManager) Tensorboard may not installed, if you want to use tensorboard, please check if tensorboard installed.
[2021-11-29 09:43:54] INFO (RestServer) RestServer base port is 8080
[2021-11-29 09:43:54] INFO (main) Rest server listening on: http://0.0.0.0:8080
[2021-11-29 09:43:55] INFO (NNIManager) Starting experiment: 3mZT9tIn
[2021-11-29 09:43:55] INFO (NNIManager) Setup training service...
[2021-11-29 09:43:55] INFO (LocalTrainingService) Construct local machine training service.
[2021-11-29 09:43:55] INFO (NNIManager) Setup tuner...
[2021-11-29 09:43:55] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-11-29 09:43:55] INFO (NNIManager) Add event listeners
[2021-11-29 09:43:55] INFO (LocalTrainingService) Run local machine training service.
[2021-11-29 09:43:55] ERROR (NNIManager) Dispatcher error: read ECONNRESET
[2021-11-29 09:43:55] ERROR (NNIManager) Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.<anonymous> (/home/biopharm/llf/anaconda3/envs/pytorch/lib/python3.8/site-packages/nni_node/core/nnimanager.js:650:32)
    at EventEmitter.emit (node:events:394:28)
    at Socket.<anonymous> (/home/biopharm/llf/anaconda3/envs/pytorch/lib/python3.8/site-packages/nni_node/core/ipcInterface.js:70:72)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2021-11-29 09:43:55] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR`

Here is the dispatcher.log file.
[dispatcher.log](https://github.com/microsoft/nni/files/7614965/dispatcher.log)

**Comment by scarlett2018** [comment]
> i'm using the latest version of NNI, but encounterd the similar error. `[2021-11-29 09:43:54] INFO (NNIDataStore) Datastore initialization done [2021-11-29 09:43:54] INFO (RestServer) RestServer start [2021-11-29 09:43:54] WARNING (NNITensorboardManager) Tensorboard may not installed, if you want to use tensorboard, please check if tensorboard installed. [2021-11-29 09:43:54] INFO (RestServer) RestServer base port is 8080 [2021-11-29 09:43:54] INFO (main) Rest server listening on: http://0.0.0.0:8080 [2021-11-29 09:43:55] INFO (NNIManager) Starting experiment: 3mZT9tIn [2021-11-29 09:43:55] INFO (NNIManager) Setup training service... [2021-11-29 09:43:55] INFO (LocalTrainingService) Construct local machine training service. [2021-11-29 09:43:55] INFO (NNIManager) Setup tuner... [2021-11-29 09:43:55] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING [2021-11-29 09:43:55] INFO (NNIManager) Add event listeners [2021-11-29 09:43:55] INFO (LocalTrainingService) Run local machine training service. [2021-11-29 09:43:55] ERROR (NNIManager) Dispatcher error: read ECONNRESET [2021-11-29 09:43:55] ERROR (NNIManager) Error: Dispatcher stream error, tuner may have crashed. at EventEmitter.<anonymous> (/home/biopharm/llf/anaconda3/envs/pytorch/lib/python3.8/site-packages/nni_node/core/nnimanager.js:650:32) at EventEmitter.emit (node:events:394:28) at Socket.<anonymous> (/home/biopharm/llf/anaconda3/envs/pytorch/lib/python3.8/site-packages/nni_node/core/ipcInterface.js:70:72) at Socket.emit (node:events:394:28) at emitErrorNT (node:internal/streams/destroy:193:8) at emitErrorCloseNT (node:internal/streams/destroy:158:3) at processTicksAndRejections (node:internal/process/task_queues:83:21) [2021-11-29 09:43:55] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR`
> 
> Here is the dispatcher.log file. [dispatcher.log](https://github.com/microsoft/nni/files/7614965/dispatcher.log)
> 
> @kvartet @liuzhe-lz

@Chenwf1025 @koklimabc - are you still facing the issue with the latest release of nni?
