### ISSUE TITLE
Bug on GradientFeatureSelection

### ISSUE THREAD

**Issue by EternalConfession** [microsoft/nni#3505]
**Environment**:
- NNI version: 2.1 
- NNI mode (local|remote|pai): local
- Client OS: Ubuntu 20.10 
- Server OS (for remote mode only):
- Python version: 3.7.10
- PyTorch/TensorFlow version: 1.8.0+cu111
- Is conda/virtualenv/venv used?: Yes
- Is running in Docker?: No

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**What issue meet, what's expected?**:

When I use the GradientFeatureSelection to fit some data, I meet the error below.

Traceback (most recent call last):
  File "FeatureEngineering/GradientSelect.py", line 43, in <module>
    fgs.fit(train_X, train_Y, groups=None)
  File "/home/jianhui/miniconda3/lib/python3.7/site-packages/nni/algorithms/feature_engineering/gradient_selector/gradient_selector.py", line 260, in fit
    self._fit(X, y, groups=groups)
  File "/home/jianhui/miniconda3/lib/python3.7/site-packages/nni/algorithms/feature_engineering/gradient_selector/gradient_selector.py", line 318, in _fit
    soft_groups=groups if self.soft_grouping else None)
  File "/home/jianhui/miniconda3/lib/python3.7/site-packages/nni/algorithms/feature_engineering/gradient_selector/fgtrain.py", line 202, in _train
    S.train(f_stop=f_stop, f_callback=f_callback)
  File "/home/jianhui/miniconda3/lib/python3.7/site-packages/nni/algorithms/feature_engineering/gradient_selector/learnability.py", line 507, in train
    if torch.isnan(h):
TypeError: isnan(): argument 'input' (position 1) must be Tensor, not int

**How to reproduce it?**: 

train_X = some_data
train_Y = some_data

fgs = FeatureGradientSelector(preprocess='center', device='cuda')
fgs.fit(train_X, train_Y, groups=None)

**Additional information**:

It is a problem due to the pytorch version, I guess. 

The variable h is changed into a number instead of a tensor during the fit process, which is not allowed by the pytorch.isnan() function.

**Comment by EternalConfession** [comment]
I just found that I used the different version of DOC. There's no problem if I specified the right task type, which is regression.
