### ISSUE TITLE
Ran the nas examples and got CUDA run of memory

### ISSUE THREAD

**Issue by rapirent** [microsoft/nni#3521]
**Environment**:
- NNI version: 2.1
- NNI mode (local|remote|pai): local
- Client OS: ubuntu 18.04.5 which is create by docker image pytorch/pytorch:latest 
- Server OS (for remote mode only):
- Python version: python 3.7.10
- PyTorch/TensorFlow version: torch 1.8 / tensorflow 2.4.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: yes

root@4c5e1ee96e55:/work/examples/nas/darts# python search.py
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "search.py", line 70, in <module>
    trainer.fit()
  File "/work/nni/retiarii/oneshot/pytorch/darts.py", line 277, in fit
    self._train_one_epoch(i)
  File "/work/nni/retiarii/oneshot/pytorch/darts.py", line 171, in _train_one_epoch
    self._backward(val_X, val_y)
  File "/work/nni/retiarii/oneshot/pytorch/darts.py", line 198, in _backward
    _, loss = self._logits_and_loss(val_X, val_y)
  File "/work/nni/retiarii/oneshot/pytorch/darts.py", line 190, in _logits_and_loss
    logits = self.model(X)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/work/examples/nas/darts/model.py", line 145, in forward
    s0, s1 = s1, cell(s0, s1)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/work/examples/nas/darts/model.py", line 92, in forward
    cur_tensor = node(tensors)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/work/examples/nas/darts/model.py", line 62, in forward
    out = [op(node) for op, node in zip(self.ops, prev_nodes)]
  File "/work/examples/nas/darts/model.py", line 62, in <listcomp>
    out = [op(node) for op, node in zip(self.ops, prev_nodes)]
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/work/nni/retiarii/oneshot/pytorch/darts.py", line 28, in forward
    return torch.sum(op_results * F.softmax(self.alpha, -1).view(*alpha_shape), 0)
RuntimeError: CUDA out of memory. Tried to allocate 28.00 MiB (GPU 0; 4.94 GiB total capacity; 3.95 GiB already allocated; 54.38 MiB free; 3.96 GiB reserved in total by PyTorch)

**What issue meet, what's expected?**: I tried to use nni module to run the darts examples (`search.py` in /examples/nas/darts) but got the error of CUDA out of memory

**How to reproduce it?**:
```sh
# enter the docker
docker run -idt -v nni:/work --name test pytorch/pytorch
docker exec -it test bash
# in docker container process
apt-get update && apt-get install build-essential
cd /work
python3 setup.py develop
cd example/nas/darts && python search.py
```sh
**Additional information**:
docker host enviroments: cuda_11.0 / nvidia-driver 460.32.03 / computation card Quadro P2200 / OS ubuntu 18.04.5 / linux kernel 4.15.0-136-generic

**Comment by ultmaster** [comment]
Your GPU memory is not enough. Please decrease the batch size or use a larger GPU!

**Comment by kvartet** [comment]
hello @rapirent, could you try to decrease the batch size or use a larger GPU and update the status of this issue? Thank you!

**Comment by ultmaster** [comment]
Closing it as there has been no response for a long time.
