### ISSUE TITLE
Resuming TPE experiment crashes tuner

### ISSUE THREAD

**Issue by arvoelke** [microsoft/nni#3534]
**Environment**:
- NNI version: 2.1
- NNI mode (local|remote|pai): local
- Client OS: Ubuntu 20.04.2 LTS 
- Python version: 3.8.8
- PyTorch/TensorFlow version: `tensorflow==2.4.1`
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Log message**:
 - dispatcher.log:
 ```
[2021-04-13 20:15:24] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002890 seconds
[2021-04-13 20:15:24] INFO (hyperopt.tpe/Thread-1) TPE using 164/164 trials with best loss 0.029564
[2021-04-14 08:25:02] INFO (hyperopt.utils/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2021-04-14 08:25:02] INFO (hyperopt.fmin/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2021-04-14 08:25:02] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2021-04-14 08:25:02] INFO (nni.tuner/MainThread) Load checkpoint ignored by tuner, checkpoint path: /home/arvoelke/nni-experiments/vYc2JOFN/checkpoint
[2021-04-14 08:25:02] INFO (nni.assessor/MainThread) Load checkpoint ignored by assessor, checkpoint path: /home/arvoelke/nni-experiments/vYc2JOFN/checkpoin
[2021-04-14 08:25:02] INFO (hyperopt_AutoML/Thread-1) Importing data, current processing progress 0 / 93
[2021-04-14 08:25:02] ERROR (nni.runtime.msg_dispatcher_base/Thread-1) 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/arvoelke/anaconda3/envs/*/lib/python3.8/site-packages/nni/runtime/msg_dispatcher_base.py", line 88, in command_queue_worker
    self.process_command(command, data)
  File "/home/arvoelke/anaconda3/envs/*/lib/python3.8/site-packages/nni/runtime/msg_dispatcher_base.py", line 147, in process_command
    command_handlers[command](data)
  File "/home/arvoelke/anaconda3/envs/*/lib/python3.8/site-packages/nni/runtime/msg_dispatcher.py", line 119, in handle_import_data
    self.tuner.import_data(data)
  File "/home/arvoelke/anaconda3/envs/*/lib/python3.8/site-packages/nni/algorithms/hpo/hyperopt_tuner.py", line 496, in import_data
    self.receive_trial_result(parameter_id=_parameter_id,
  File "/home/arvoelke/anaconda3/envs/*/lib/python3.8/site-packages/nni/algorithms/hpo/hyperopt_tuner.py", line 359, in receive_trial_result
    json2vals(self.json, vals, out_y)
  File "/home/arvoelke/anaconda3/envs/*/lib/python3.8/site-packages/nni/algorithms/hpo/hyperopt_tuner.py", line 127, in json2vals
    json2vals(in_x[key], vals[key], out_y,
  File "/home/arvoelke/anaconda3/envs/*/lib/python3.8/site-packages/nni/algorithms/hpo/hyperopt_tuner.py", line 118, in json2vals
    _index = vals[NodeType.INDEX]
TypeError: 'NoneType' object is not subscriptable
[2021-04-14 08:25:07] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2021-04-14 08:25:08] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated
```

**What issue meet, what's expected?**:

Expected to be able to resume an experiment that had been stopped. Instead it crashes the tuner.

**How to reproduce it?**: 

```
nnictl create ...
<restart the computer after a number of trials have completed>
nnictl resume <expID>
```

**Additional information**:

Using the TPE tuner and the medianstop assessor.

Computer was forcefully shutdown after trial 164 (see time gap in above log). It is unknown whether this issue also occurs when the experiment is stopped manually. The nnimanager.log includes some more information around the time of the shutdown:
```
[2021-04-13 20:15:35] INFO [ 'Trial job peyrP status changed from WAITING to RUNNING' ]
[2021-04-13 20:15:35] INFO [ 'Trial job im1GH status changed from WAITING to RUNNING' ]
[2021-04-13 20:15:35] INFO [ 'Trial job j7qc2 status changed from WAITING to RUNNING' ]
[2021-04-13 20:15:35] INFO [ 'Trial job jAM2J status changed from WAITING to RUNNING' ]
[2021-04-13 20:17:25] INFO [ 'Change NNIManager status from: RUNNING to: STOPPING' ]
[2021-04-13 20:17:25] INFO [ 'Stopping experiment, cleaning up ...' ]
[2021-04-13 20:17:25] ERROR [ 'Dispatcher error: write EPIPE' ]
[2021-04-13 20:17:25] ERROR [ 'Error: Dispatcher stream error, tuner may have crashed.\n    at EventEmitter.dispatcher.onError (/home/arvoelke/anaconda3/envs/*/lib/python3.8/site-packages/nni_node/core/nnimanager.js:550:32)\n    at EventEmitter.emit (events.js:198:13)\n    at Socket.IpcInterface.outgoingStream.on (/home/arvoelke/anaconda3/envs/*/lib/python3.8/site-packages/nni_node/core/ipcInterface.js:42:72)\n    at Socket.emit (events.js:198:13)\n    at errorOrDestroy (internal/streams/destroy.js:107:12)\n    at onwriteError (_stream_writable.js:430:5)\n    at onwrite (_stream_writable.js:461:5)\n    at _destroy (internal/streams/destroy.js:49:7)\n    at Socket._destroy (net.js:614:3)\n    at Socket.destroy (internal/streams/destroy.js:37:8)' ]
[2021-04-13 20:17:25] INFO [ 'Change NNIManager status from: STOPPING to: ERROR' ]
[2021-04-14 08:25:01] INFO [ 'Datastore initialization done' ]
[2021-04-14 08:25:01] INFO [ 'RestServer start' ]
[2021-04-14 08:25:01] INFO [ 'Construct local machine training service.' ]
[2021-04-14 08:25:01] INFO [ 'RestServer base port is 8080' ]
[2021-04-14 08:25:01] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[2021-04-14 08:25:02] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"srun -G1 -pGPU1,GPU2 --mem=16G python *.py","codeDir":"/home/arvoelke/git/*/nni/."}' ]
[2021-04-14 08:25:02] INFO [ 'Resuming experiment: vYc2JOFN' ]
[2021-04-14 08:25:02] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
```

I've left out the other parts of the logs as they don't appear to include any additional information.

**Comment by arvoelke** [comment]
I tried this again with `nnictl stop` (instead of a sudden restart) and encountered the exact same issue.

I also tried `pip install dill` as recommended in the logs, but that did not help.

I took a brief look at the code where the error is being reported, and I'm wondering if it maybe the tuner reloading does not support nested search spaces? Or perhaps choices with only one option? My search space JSON file looks like:

```
  "batch_size": {"_type": "choice", "_value": [500]},
  "activation": {"_type": "choice", "_value": ["relu"]},  
  ...,
  "layer_params2": {
    "_type": "choice",
    "_value": [
      { "_name": "None" },
      {
        "_name": "LMU",
        "units": {"_type": "quniform", "_value": [16, 1024, 1]},
        "memory_d": {"_type": "quniform", "_value": [1, 64, 1]},
        "order": {"_type": "quniform", "_value": [3, 64, 1]},
        "theta": {"_type": "uniform", "_value": [1, 1280]}
      }
    ]
  },
  ...
```

**Comment by liuzhe-lz** [comment]
Can you provide full experiment config? I have tried following config and the issue did not reproduce.
```yaml
searchSpace: {
    "batch_size": {"_type": "choice", "_value": [500]},
    "activation": {"_type": "choice", "_value": ["relu"]},
    "layer_params2": {
        "_type": "choice",
        "_value": [
            { "_name": "None" },
            {
                "_name": "LMU",
                "units": {"_type": "quniform", "_value": [16, 1024, 1]},
                "memory_d": {"_type": "quniform", "_value": [1, 64, 1]},
                "order": {"_type": "quniform", "_value": [3, 64, 1]},
                "theta": {"_type": "uniform", "_value": [1, 1280]}
            }
        ]
    }
}
trialConcurrency: 3
maxTrialNumber: 10
trialCommand: echo hello
tuner:
    name: 'TPE'
    classArgs:
        optimize_mode: maximize
trainingService:
    platform: local
```

**Comment by arvoelke** [comment]
I was able to reproduce it with the following setup.

**test.json**
```
{
    "layer_params": {
        "_type": "choice",
        "_value": [
            { "_name": "None" },
            {
                "_name": "LMU",
                "units": {"_type": "quniform", "_value": [16, 1024, 1]},
                "memory_d": {"_type": "quniform", "_value": [1, 64, 1]},
                "order": {"_type": "quniform", "_value": [3, 64, 1]},
                "theta": {"_type": "uniform", "_value": [1, 1280]}
            }
        ]
    }
}
```

**test.py**
```
import time

import nni

time.sleep(10)

params = nni.get_next_parameter()
nni.report_final_result(1)
```

**test.yml**
```
authorName: ABR
experimentName: test
trialConcurrency: 1
trainingServicePlatform: local
searchSpacePath: ./test.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: minimize
  includeIntermediateResults: true
trial:
  command: python test.py
  codeDir: .
```

Steps to reproduce:
1. `nnictl create --config test.yml`
2. Wait for one trial to successfully complete, and the next one to start running.
3. `nnictl stop` 
4. `nnictl resume <expID>`
5. Wait for dispatcher to enter error state.

For step 2, it seems important that the next trial has to have started running when `nnictl stop` is issued. If the stop is issued at the perfect moment between trials then the bug does not appear to occur. I've only tested it 2-3 times in each condition though, so not 100% sure.

**Comment by kvartet** [comment]
@liuzhe-lz ^ ^

**Comment by liuzhe-lz** [comment]
TPE tuner has been rewritten.
