### ISSUE TITLE
Unable to run example mnist-annotation

### ISSUE THREAD

**Issue by Ivanfangsc** [microsoft/nni#3591]
**Environment**:
- NNI version: 2.2
- NNI mode (local|remote|pai): local
- Client OS: Windows 10
- Python version: 3.8.5
- PyTorch/TensorFlow version: PyTorch 1.8.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 ```
Traceback (most recent call last):
  File "c:\users\veraku\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\veraku\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\veraku\anaconda3\Scripts\nnictl.exe\__main__.py", line 7, in <module>
  File "c:\users\veraku\anaconda3\lib\site-packages\nni\tools\nnictl\nnictl.py", line 272, in parse_args
    args.func(args)
  File "c:\users\veraku\anaconda3\lib\site-packages\nni\tools\nnictl\launcher.py", line 497, in create_experiment
    config_v2 = convert.to_v2(config_yml).json()
  File "c:\users\veraku\anaconda3\lib\site-packages\nni\experiment\config\common.py", line 119, in json
    obj = super().json()
  File "c:\users\veraku\anaconda3\lib\site-packages\nni\experiment\config\base.py", line 85, in json
    self.validate()
  File "c:\users\veraku\anaconda3\lib\site-packages\nni\experiment\config\common.py", line 113, in validate
    _validate_for_nnictl(self.canonical())
  File "c:\users\veraku\anaconda3\lib\site-packages\nni\experiment\config\common.py", line 176, in _validate_for_nnictl
    raise ValueError('ExperimentConfig: search_space and search_space_file must be set one')
ValueError: ExperimentConfig: search_space and search_space_file must be set one
```
 

**What issue meet, what's expected?**:
The example is expected to run.

**How to reproduce it?**: 
Download the example and run it with `nnictl create -c config.yml`

**Additional information**:
I believe that the problem is with v2 configuration. On line 39 of `nni/experiment/config/convert.py`
```
v1.pop('useAnnotation', None)  # TODO: how to handle annotation in nni.Experiment?
```
it seems that the `useAnnotation` attribute is poped and therefore cannot pass validation in `nni/experiment/config/common.py`

**Comment by songqiqqq** [comment]
Any Update?

**Comment by JoyFYan** [comment]
My code can run without error on version 2.1. But raise the same ValueError when use annotation.

**Comment by liuzhe-lz** [comment]
Expected to be fixed in v2.3 release next week.

**Comment by kvartet** [comment]
@Ivanfangsc @songqiqqq @JoyFYan I'm closing this issue as it had been fixed, free feel to reopen it if you still think it an active issue.

**Comment by jianliu-ml** [comment]
> @Ivanfangsc @songqiqqq @JoyFYan I'm closing this issue as it had been fixed, free feel to reopen it if you still think it an active issue.

Hi, this still produces an error!!

Traceback (most recent call last):
  File "/home/jliu/venv3/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
  File "/home/jliu/venv3/lib/python3.6/site-packages/nni/tools/nnictl/nnictl.py", line 272, in parse_args
    args.func(args)
  File "/home/jliu/venv3/lib/python3.6/site-packages/nni/tools/nnictl/launcher.py", line 553, in view_experiment
    manage_stopped_experiment(args, 'view')
  File "/home/jliu/venv3/lib/python3.6/site-packages/nni/tools/nnictl/launcher.py", line 534, in manage_stopped_experiment
    experiment_config = Config(experiment_id, experiments_dict[args.id]['logDir']).get_config()
  File "/home/jliu/venv3/lib/python3.6/site-packages/nni/tools/nnictl/config_utils.py", line 89, in __init__
    self.conn = sqlite3.connect(os.path.join(log_dir, experiment_id, 'db', 'nni.sqlite'))
sqlite3.OperationalError: unable to open database file
