### ISSUE TITLE
Running NNI with Kubeflow Plugin Without of "default" namespace

### ISSUE THREAD

**Issue by rohin-dasari** [microsoft/nni#3596]
**Environment**:
- NNI version: 2.2
- NNI mode (local|remote|pai): kubeflow
- Client OS: Ubuntu 20.04.1 LTS
- Server OS (for remote mode only):Ubuntu 16.04.7 LTS
- Python version: 3.8.3
- PyTorch/TensorFlow version: 2.2.0
- Is conda/virtualenv/venv used?: Conda
- Is running in Docker?: No

**Log message**:
 - nnimanager.log:
 [2021-04-29 16:17:14] INFO [ 'Datastore initialization done' ]
[2021-04-29 16:17:14] INFO [ 'RestServer start' ]
[2021-04-29 16:17:14] WARNING [ 'Tensorboard may not installed, if you want to use tensorboard, please check if tensorboard installed.' ]
[2021-04-29 16:17:14] INFO [ 'RestServer base port is 9090' ]
[2021-04-29 16:17:14] INFO [ 'Rest server listening on: http://0.0.0.0:9090' ]
[2021-04-29 16:17:15] INFO [ 'Setup training service...' ]
[2021-04-29 16:17:15] INFO [ 'Construct Kubeflow training service.' ]
[2021-04-29 16:17:19] INFO [ 'Starting experiment: KweM4UDa' ]
[2021-04-29 16:17:19] INFO [ 'Setup tuner...' ]
[2021-04-29 16:17:19] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[2021-04-29 16:17:19] INFO [ 'Add event listeners' ]
[2021-04-29 16:17:19] INFO [ 'Run Kubeflow training service.' ]
[2021-04-29 16:17:19] INFO [ 'RestServer start' ]
[2021-04-29 16:17:19] INFO [ 'RestServer base port is 9091' ]
[2021-04-29 16:17:19] INFO [ 'Kubeflow Training service rest server listening on: http://0.0.0.0:9091' ]
[2021-04-29 16:17:20] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[2021-04-29 16:17:20] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"batch_size": 32, "hidden_size": 32}, "parameter_index": 0}' ]
[2021-04-29 16:17:20] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"batch_size": 16, "hidden_size": 32}, "parameter_index": 0}' ]
[2021-04-29 16:17:24] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"batch_size\\": 32, \\"hidden_size\\": 32}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-04-29 16:17:24] INFO [ 'Construct Kubeflow training service.' ]
[2021-04-29 16:17:24] ERROR [ 'Error: tfjobs.kubeflow.org is forbidden: User "system:serviceaccount:nni:default" cannot create resource "tfjobs" in API group "kubeflow.org" in the namespace "default"\n    at _request (/home/local/TECHNICALABS/rdasari/miniconda3/envs/nni/lib/python3.7/site-packages/nni_node/node_modules/kubernetes-client/lib/backends/request.js:189:25)\n    at Request.request [as _callback] (/home/local/TECHNICALABS/rdasari/miniconda3/envs/nni/lib/python3.7/site-packages/nni_node/node_modules/kubernetes-client/lib/backends/request.js:148:14)\n    at Request.self.callback (/home/local/TECHNICALABS/rdasari/miniconda3/envs/nni/lib/python3.7/site-packages/nni_node/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:198:13)\n    at Request.<anonymous> (/home/local/TECHNICALABS/rdasari/miniconda3/envs/nni/lib/python3.7/site-packages/nni_node/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:198:13)\n    at IncomingMessage.<anonymous> (/home/local/TECHNICALABS/rdasari/miniconda3/envs/nni/lib/python3.7/site-packages/nni_node/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:286:20)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)' ]
[2021-04-29 16:17:24] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]

**What issue meet, what's expected?**:
NNI can't start a Kubeflow training service in our Kubernetes cluster without belonging in the "default" namespace. We would like to avoid giving NNI "default" permissions since we have other tasks and jobs running in our Kubernetes cluster and would like to keep the NNI optimization tasks as independent of our other jobs as possible. Is it possible to specify the namespace NNI uses when it runs using the Kubeflow plugin?

**Comment by SparkSnail** [comment]
NNI does not support setting namespace in configuration yet, but you could change NNI source code for your requirement, and build NNI manually. 
change code here:
https://github.com/microsoft/nni/blob/02eab99b9bb280e385a7af71b4c6c4a73bae1f04/ts/nni_manager/training_service/kubernetes/kubeflow/kubeflowTrainingService.ts#L373
Build and install NNI locally:
https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/InstallationLinux.rst#build-wheel-package-from-nni-source-code

**Comment by rohin-dasari** [comment]
Thanks for the response.

I made the change and rebuilt from source, but the error still persists. Is there another specific place where a code change is required? I looked around the ```nni/ts/nni_manager/training_service/kubernetes/kubeflow/``` directory and found some other references to the ```default``` namespace in ```kubeflowApiClient.ts```. I swapped those values out with our namespace, but that raised a new issue:

[2021-04-30 14:06:13] ERROR [ 'Error: 404 page not found\n\n    at _request (/home/local/TECHNICALABS/rdasari/miniconda3/lib/python3.8/site-packages/nni_node/node_modules/kubernetes-client/lib/backends/request.js:189:25)\n    at Request.request [as _callback] (/home/local/TECHNICALABS/rdasari/miniconda3/lib/python3.8/site-packages/nni_node/node_modules/kubernetes-client/lib/backends/request.js:148:14)\n    at Request.self.callback (/home/local/TECHNICALABS/rdasari/miniconda3/lib/python3.8/site-packages/nni_node/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:198:13)\n    at Request.<anonymous> (/home/local/TECHNICALABS/rdasari/miniconda3/lib/python3.8/site-packages/nni_node/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:198:13)\n    at IncomingMessage.<anonymous> (/home/local/TECHNICALABS/rdasari/miniconda3/lib/python3.8/site-packages/nni_node/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:286:20)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)' ]

**Comment by SparkSnail** [comment]
@rohin-dasari  did you fixed the issue? `Error: 404 page not found` this error seems caused by kubernetes environment, could you double check if you could run kubeflow job successfully without NNI?

**Comment by rohin-dasari** [comment]
I was able to confirm that the namespace I am pointing NNI to does in fact exist. I will work on getting a Kubeflow job to run successfully on the namespace and get back to you.

**Comment by kvartet** [comment]
@rohin-dasari Any updates? Thank you!
