### ISSUE TITLE
When using gpu to accelerate the calculation of mnist example, an error is reported.

### ISSUE THREAD

**Issue by 1575018690** [microsoft/nni#3609]
**Describe the issue**:

**Environment**:
- NNI version: v2.0
- Training service (local|remote|pai|aml|etc):local
- Client OS:window 10
- Server OS (for remote mode only):
- Python version:python 3.8
- PyTorch/TensorFlow version:pytorch v1.8
- Is conda/virtualenv/venv used?:conda
- Is running in Docker?:no

**Configuration**:
 - Experiment config (remember to remove secrets!):
authorName: default
experimentName: example_mnist_pytorch
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python mnist.py
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true
logDir: D:\nni\logdir

 - Search space:
{
    "batch_size": {"_type":"choice", "_value": [16, 32, 64, 128]},
    "hidden_size":{"_type":"choice","_value":[128, 256, 512, 1024]},
    "lr":{"_type":"choice","_value":[0.0001, 0.001, 0.01, 0.1]},
    "momentum":{"_type":"uniform","_value":[0, 1]}
}

**Log message**:
 - nnimanager.log:
 [2021-05-07 13:10:12] DEBUG [ 'Database directory: D:\\nni\\logdir\\GmgXYDWB\\db' ]
[2021-05-07 13:10:13] INFO [ 'Datastore initialization done' ]
[2021-05-07 13:10:13] INFO [ 'RestServer start' ]
[2021-05-07 13:10:13] INFO [ 'Construct local machine training service.' ]
[2021-05-07 13:10:13] INFO [ 'RestServer base port is 8080' ]
[2021-05-07 13:10:13] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[2021-05-07 13:10:13] DEBUG [ 'GET: /check-status: body:\n{}' ]
[2021-05-07 13:10:15] DEBUG [ 'PUT: /experiment/cluster-metadata: body:\n{\n    "local_config": {\n        "useActiveGpu": true\n    }\n}' ]
[2021-05-07 13:10:15] INFO [ 'NNIManager setClusterMetadata, key: local_config, value: {"useActiveGpu":true}' ]
[2021-05-07 13:10:15] INFO [ 'Specified GPU indices: undefined' ]
[2021-05-07 13:10:17] DEBUG [ 'PUT: /experiment/cluster-metadata: body:\n{\n    "trial_config": {\n        "command": "python mnist.py",\n        "codeDir": "C:\\\\Users\\\\Liao ShengJun\\\\nni\\\\examples\\\\trials\\\\mnist-pytorch\\\\.",\n        "gpuNum": 1\n    }\n}' ]
[2021-05-07 13:10:17] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"command":"python mnist.py","codeDir":"C:\\\\Users\\\\Liao ShengJun\\\\nni\\\\examples\\\\trials\\\\mnist-pytorch\\\\.","gpuNum":1}' ]
[2021-05-07 13:10:17] INFO [ 'required GPU number is 1' ]
[2021-05-07 13:10:19] DEBUG [ 'POST: /experiment: body:\n{\n    "authorName": "default",\n    "experimentName": "example_mnist_pytorch",\n    "trialConcurrency": 1,\n    "maxExecDuration": 3600,\n    "maxTrialNum": 10,\n    "searchSpace": "{\\"batch_size\\": {\\"_type\\": \\"choice\\", \\"_value\\": [16, 32, 64, 128]}, \\"hidden_size\\": {\\"_type\\": \\"choice\\", \\"_value\\": [128, 256, 512, 1024]}, \\"lr\\": {\\"_type\\": \\"choice\\", \\"_value\\": [0.0001, 0.001, 0.01, 0.1]}, \\"momentum\\": {\\"_type\\": \\"uniform\\", \\"_value\\": [0, 1]}}",\n    "trainingServicePlatform": "local",\n    "tuner": {\n        "builtinTunerName": "TPE",\n        "classArgs": {\n            "optimize_mode": "maximize"\n        }\n    },\n    "versionCheck": false,\n    "clusterMetaData": [\n        {\n            "key": "local_config",\n            "value": {\n                "useActiveGpu": true\n            }\n        },\n        {\n            "key": "trial_config",\n            "value": {\n                "command": "python mnist.py",\n                "codeDir": "C:\\\\Users\\\\Liao ShengJun\\\\nni\\\\examples\\\\trials\\\\mnist-pytorch\\\\.",\n                "gpuNum": 1\n            }\n        }\n    ]\n}' ]
[2021-05-07 13:10:19] INFO [ 'Starting experiment: GmgXYDWB' ]
[2021-05-07 13:10:19] DEBUG [ 'Setup tuner...' ]
[2021-05-07 13:10:19] DEBUG [ 'dispatcher command: python -m nni --exp_params eyJhdXRob3JOYW1lIjoiZGVmYXVsdCIsImV4cGVyaW1lbnROYW1lIjoiZXhhbXBsZV9tbmlzdF9weXRvcmNoIiwidHJpYWxDb25jdXJyZW5jeSI6MSwibWF4RXhlY0R1cmF0aW9uIjozNjAwLCJtYXhUcmlhbE51bSI6MTAsInRyYWluaW5nU2VydmljZVBsYXRmb3JtIjoibG9jYWwiLCJ0dW5lciI6eyJidWlsdGluVHVuZXJOYW1lIjoiVFBFIiwiY2xhc3NBcmdzIjp7Im9wdGltaXplX21vZGUiOiJtYXhpbWl6ZSJ9fSwidmVyc2lvbkNoZWNrIjpmYWxzZSwiY2x1c3Rlck1ldGFEYXRhIjpbeyJrZXkiOiJsb2NhbF9jb25maWciLCJ2YWx1ZSI6eyJ1c2VBY3RpdmVHcHUiOnRydWV9fSx7ImtleSI6InRyaWFsX2NvbmZpZyIsInZhbHVlIjp7ImNvbW1hbmQiOiJweXRob24gbW5pc3QucHkiLCJjb2RlRGlyIjoiQzpcXFVzZXJzXFxMaWFvIFNoZW5nSnVuXFxubmlcXGV4YW1wbGVzXFx0cmlhbHNcXG1uaXN0LXB5dG9yY2hcXC4iLCJncHVOdW0iOjF9fV19' ]
[2021-05-07 13:10:19] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[2021-05-07 13:10:19] INFO [ 'Add event listeners' ]
[2021-05-07 13:10:19] DEBUG [ 'Send tuner command: INITIALIZE: {"batch_size": {"_type": "choice", "_value": [16, 32, 64, 128]}, "hidden_size": {"_type": "choice", "_value": [128, 256, 512, 1024]}, "lr": {"_type": "choice", "_value": [0.0001, 0.001, 0.01, 0.1]}, "momentum": {"_type": "uniform", "_value": [0, 1]}}' ]
[2021-05-07 13:10:19] DEBUG [ 'ipcInterface command type: [IN], content:[{"batch_size": {"_type": "choice", "_value": [16, 32, 64, 128]}, "hidden_size": {"_type": "choice", "_value": [128, 256, 512, 1024]}, "lr": {"_type": "choice", "_value": [0.0001, 0.001, 0.01, 0.1]}, "momentum": {"_type": "uniform", "_value": [0, 1]}}]' ]
[2021-05-07 13:10:19] DEBUG [ 'ipcInterface command type: [PI], content:[]' ]
[2021-05-07 13:10:19] INFO [ 'Run local machine training service.' ]
[2021-05-07 13:10:20] ERROR [ 'ChildProcessError: Command failed: powershell.exe New-Item -Path "C:\\Users\\LIAOSH~1\\AppData\\Local\\Temp/Liao ShengJun/nni/script" -ItemType "directory" -Force\nNew-Item : �Ҳ�������ʵ�ʲ�����ShengJun/nni/script����λ����ʽ������\r\n����λ�� ��:1 �ַ�: 1\r\n+ New-Item -Path C:\\Users\\LIAOSH~1\\AppData\\Local\\Temp/Liao ShengJun/nni ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidArgument: (:) [New-Item]��ParameterBindingException\r\n    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.NewItemCommand\r\n \r\n `powershell.exe New-Item -Path "C:\\Users\\LIAOSH~1\\AppData\\Local\\Temp/Liao ShengJun/nni/script" -ItemType "directory" -Force` (exited with error code 1)\n    at callback (c:\\users\\liao shengjun\\nni\\nni_node\\node_modules\\child-process-promise\\lib\\index.js:33:27)\n    at ChildProcess.exithandler (child_process.js:301:5)\n    at ChildProcess.emit (events.js:198:13)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)' ]
[2021-05-07 13:10:20] INFO [ 'Change NNIManager status from: RUNNING to: ERROR' ]
[2021-05-07 13:10:21] DEBUG [ 'GET: /experiment: body:\n{}' ]
[2021-05-07 13:10:21] DEBUG [ 'GET: /trial-jobs: body:\n{}' ]
[2021-05-07 13:10:21] DEBUG [ 'GET: /metric-data: body:\n{}' ]
[2021-05-07 13:10:21] DEBUG [ 'getTrialJobsByReplayEvents begin' ]
[2021-05-07 13:10:21] DEBUG [ 'getTrialJobsByReplayEvents done' ]
[2021-05-07 13:10:21] DEBUG [ 'GET: /check-status: body:\n{}' ]
[2021-05-07 13:10:21] DEBUG [ 'GET: /trial-jobs: body:\n{}' ]
[2021-05-07 13:10:21] DEBUG [ 'GET: /metric-data: body:\n{}' ]
[2021-05-07 13:10:21] DEBUG [ 'getTrialJobsByReplayEvents begin' ]
[2021-05-07 13:10:21] DEBUG [ 'getTrialJobsByReplayEvents done' ]
[2021-05-07 13:10:21] DEBUG [ 'GET: /version: body:\n{}' ]
[2021-05-07 13:10:22] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[2021-05-07 13:10:22] DEBUG [ 'ipcInterface command type: [GE], content:[1]' ]
[2021-05-07 13:10:22] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "hidden_size": 512, "lr": 0.0001, "momentum": 0.6273923033073219}, "parameter_index": 0}' ]
[2021-05-07 13:10:22] DEBUG [ 'GET: /experiment: body:\n{}' ]
[2021-05-07 13:10:22] DEBUG [ 'GET: /trial-jobs: body:\n{}' ]
[2021-05-07 13:10:22] DEBUG [ 'GET: /metric-data: body:\n{}' ]
[2021-05-07 13:10:22] DEBUG [ 'getTrialJobsByReplayEvents begin' ]
[2021-05-07 13:10:22] DEBUG [ 'getTrialJobsByReplayEvents done' ]
[2021-05-07 13:10:22] DEBUG [ 'GET: /check-status: body:\n{}' ]

 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by kvartet** [comment]
hello @J-shang, it is a duplicated issue with #3610, if it is, I will close it...

**Comment by J-shang** [comment]
@kvartet yes, this seems can be closed.
