### ISSUE TITLE
AssertionError when runing amc pruner following the README.md.

### ISSUE THREAD

**Issue by ichejun** [microsoft/nni#3635]
**Describe the issue**:
Run the AMCPruner Example following the guide: https://github.com/microsoft/nni/blob/25dea8f5528be7f3f74ca2c2fa42f528f6cdd4eb/examples/model_compress/pruning/amc/README.md
But when I run the last step, an AssertionError showed up. 
The logs were show at the bottom.
It seems that speed up does not support group?

**Environment**:
- NNI version: 2.2
- Training service (local|remote|pai|aml|etc): local
- Client OS:
- Server OS (for remote mode only):
- Python version: 3.7.5
- PyTorch/TensorFlow version:PyTorch 1.7.1
- Is conda/virtualenv/venv used?:no
- Is running in Docker?:no

**Log message**:
```
[cj@pytorch /ProjectRoot/nni_0512/nni/examples/model_compress/pruning/amc]
$python3 amc_train.py --model_type mobilenetv2 --ckpt logs/mobilenetv2_cifar10_r0.5_search-run3/best_model.pth --mask logs/mobilenetv2_cifar10_r0.5_search-run3/best_mask.pth --n_epoch 100
=> Preparing data..
=> Preparing data..
Files already downloaded and verified
Files already downloaded and verified
=> Building model..
=> Loading checkpoint logs/mobilenetv2_cifar10_r0.5_search-run3/best_model.pth ..
[2021-05-12 18:48:08] INFO (nni.compression.pytorch.speedup.compressor/MainThread) start to speed up the model
[2021-05-12 18:48:08] INFO (nni.compression.pytorch.speedup.compressor/MainThread) fix the mask conflict of the interdependent layers
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) {'features.0.0': 32, 'features.1.conv.0': 32, 'features.1.conv.3': 1, 'features.2.conv.0': 96, 'features.2.conv.3': 96, 'features.2.conv.6': 1, 'features.3.conv.0': 144, 'features.3.conv.3': 144, 'features.3.conv.6': 1, 'features.4.conv.0': 144, 'features.4.conv.3': 144, 'features.4.conv.6': 1, 'features.5.conv.0': 192, 'features.5.conv.3': 192, 'features.5.conv.6': 1, 'features.6.conv.0': 192, 'features.6.conv.3': 192, 'features.6.conv.6': 1, 'features.7.conv.0': 192, 'features.7.conv.3': 192, 'features.7.conv.6': 1, 'features.8.conv.0': 384, 'features.8.conv.3': 384, 'features.8.conv.6': 1, 'features.9.conv.0': 384, 'features.9.conv.3': 384, 'features.9.conv.6': 1, 'features.10.conv.0': 384, 'features.10.conv.3': 384, 'features.10.conv.6': 1, 'features.11.conv.0': 384, 'features.11.conv.3': 384, 'features.11.conv.6': 1, 'features.12.conv.0': 576, 'features.12.conv.3': 576, 'features.12.conv.6': 1, 'features.13.conv.0': 576, 'features.13.conv.3': 576, 'features.13.conv.6': 1, 'features.14.conv.0': 576, 'features.14.conv.3': 576, 'features.14.conv.6': 1, 'features.15.conv.0': 960, 'features.15.conv.3': 960, 'features.15.conv.6': 1, 'features.16.conv.0': 960, 'features.16.conv.3': 960, 'features.16.conv.6': 1, 'features.17.conv.0': 960, 'features.17.conv.3': 960, 'features.17.conv.6': 1, 'features.18.0': 1}
/home/admin/work_dir/.local/lib/python3.7/site-packages/nni/compression/pytorch/utils/mask_conflict.py:185: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  count).nonzero().squeeze(1).tolist()
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.1.conv.3 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.2.conv.6 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.3.conv.0 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.3.conv.6 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.4.conv.0 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.4.conv.6 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.5.conv.6 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.6.conv.6 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.7.conv.6 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.8.conv.0 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.8.conv.6 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.9.conv.0 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.9.conv.6 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.10.conv.0 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.10.conv.6 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.11.conv.0 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.11.conv.6 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.12.conv.0 using fine-grained pruning
[2021-05-12 18:48:49] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.12.conv.6 using fine-grained pruning
[2021-05-12 18:48:50] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.13.conv.0 using fine-grained pruning
[2021-05-12 18:48:50] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.13.conv.6 using fine-grained pruning
[2021-05-12 18:48:50] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.14.conv.0 using fine-grained pruning
[2021-05-12 18:48:50] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.14.conv.6 using fine-grained pruning
[2021-05-12 18:48:50] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.15.conv.0 using fine-grained pruning
[2021-05-12 18:48:50] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.15.conv.6 using fine-grained pruning
[2021-05-12 18:48:50] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.16.conv.0 using fine-grained pruning
[2021-05-12 18:48:50] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.16.conv.6 using fine-grained pruning
[2021-05-12 18:48:50] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.17.conv.0 using fine-grained pruning
[2021-05-12 18:48:50] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.17.conv.6 using fine-grained pruning
[2021-05-12 18:48:50] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) Layers features.18.0 using fine-grained pruning
[2021-05-12 18:48:56] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) dim0 sparsity: 0.000000
[2021-05-12 18:48:56] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) dim1 sparsity: 0.373210
[2021-05-12 18:48:56] INFO (nni.compression.pytorch.utils.mask_conflict/MainThread) detected conv prune dim: 1
[2021-05-12 18:48:58] INFO (nni.compression.pytorch.speedup.compressor/MainThread) infer module masks...
Traceback (most recent call last):
  File "amc_train.py", line 214, in <module>
    net = get_model(args)  # for measure
  File "amc_train.py", line 83, in get_model
    ms.speedup_model()
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/nni/compression/pytorch/speedup/compressor.py", line 183, in speedup_model
    self.infer_modules_masks()
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/nni/compression/pytorch/speedup/compressor.py", line 140, in infer_modules_masks
    self.infer_module_mask(module_name, None, mask=mask)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/nni/compression/pytorch/speedup/compressor.py", line 120, in infer_module_mask
    self.infer_module_mask(_module_name, module_name, out_shape=input_cmask)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/nni/compression/pytorch/speedup/compressor.py", line 120, in infer_module_mask
    self.infer_module_mask(_module_name, module_name, out_shape=input_cmask)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/nni/compression/pytorch/speedup/compressor.py", line 120, in infer_module_mask
    self.infer_module_mask(_module_name, module_name, out_shape=input_cmask)
  [Previous line repeated 1 more time]
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/nni/compression/pytorch/speedup/compressor.py", line 115, in infer_module_mask
    input_cmask = infer_from_outshape[m_type](module_masks, out_shape)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/nni/compression/pytorch/speedup/infer_shape.py", line 296, in <lambda>
    'ReLU6': lambda module_masks, mask: relu_outshape(module_masks, mask),
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/nni/compression/pytorch/speedup/infer_shape.py", line 780, in relu_outshape
    module_masks.output_mask.mask_index[1] == mask.mask_index[1])
AssertionError
```

**Comment by zheng-ningxin** [comment]
Hi, thanks for the valuable feedback! I tested this example on the refactored speedup(https://github.com/microsoft/nni/pull/3462) and it works fine. Please have a try when this PR merged. Thanks.

**Comment by ichejun** [comment]
@zheng-ningxin OK, really look forward to the refactored speedup. BTW, when will it be released? :)

**Comment by kvartet** [comment]
It seems this feature will release in NNI v2.4 in July. Maybe you can pull the master branch and install nni from the source code when this pr is merged.
