### ISSUE TITLE
AMC issues happened when fine-tuning the model

### ISSUE THREAD

**Issue by MagicPF** [microsoft/nni#3831]
[2021-06-15 16:18:56] INFO (nni.compression.pytorch.speedup.compressor/MainThread) infer module masks...
Traceback (most recent call last):
  File "amc_train.py", line 214, in <module>
    net = get_model(args)  # for measure
  File "amc_train.py", line 83, in get_model
    ms.speedup_model()
  File "/home/comp/e9205945/.local/lib/python3.6/site-packages/nni/compression/pytorch/speedup/compressor.py", line 183, in speedup_model
    self.infer_modules_masks()
  File "/home/comp/e9205945/.local/lib/python3.6/site-packages/nni/compression/pytorch/speedup/compressor.py", line 140, in infer_modules_masks
    self.infer_module_mask(module_name, None, mask=mask)
  File "/home/comp/e9205945/.local/lib/python3.6/site-packages/nni/compression/pytorch/speedup/compressor.py", line 120, in infer_module_mask
    self.infer_module_mask(_module_name, module_name, out_shape=input_cmask)
  File "/home/comp/e9205945/.local/lib/python3.6/site-packages/nni/compression/pytorch/speedup/compressor.py", line 120, in infer_module_mask
    self.infer_module_mask(_module_name, module_name, out_shape=input_cmask)
  File "/home/comp/e9205945/.local/lib/python3.6/site-packages/nni/compression/pytorch/speedup/compressor.py", line 120, in infer_module_mask
    self.infer_module_mask(_module_name, module_name, out_shape=input_cmask)
  [Previous line repeated 1 more time]
  File "/home/comp/e9205945/.local/lib/python3.6/site-packages/nni/compression/pytorch/speedup/compressor.py", line 115, in infer_module_mask
    input_cmask = infer_from_outshape[m_type](module_masks, out_shape)
  File "/home/comp/e9205945/.local/lib/python3.6/site-packages/nni/compression/pytorch/speedup/infer_shape.py", line 296, in <lambda>
    'ReLU6': lambda module_masks, mask: relu_outshape(module_masks, mask),
  File "/home/comp/e9205945/.local/lib/python3.6/site-packages/nni/compression/pytorch/speedup/infer_shape.py", line 780, in relu_outshape
    module_masks.output_mask.mask_index[1] == mask.mask_index[1])
AssertionError

**Comment by zheng-ningxin** [comment]
Hi, thanks for the valuable feedback! This is a same issue with https://github.com/microsoft/nni/issues/3635. I tested this example on the refactored speedup(https://github.com/microsoft/nni/pull/3462) and it works fine. Please have a try when this PR merged, or you can clone this branch and install the NNI from source code. Thanks~~
