### ISSUE TITLE
Cannot install NNI

### ISSUE THREAD

**Issue by CommandoHuan** [microsoft/nni#3858]
I've followed the guide here: https://nni.readthedocs.io/en/stable/Tutorial/InstallationLinux.html#installation  in Ubuntu 18.04 LTS on Jetson Nano
But when execute the command 'python3 setup.py develop' it raise error:

# Downloading node.js from https://nodejs.org/dist/v10.23.0/node-v10.23.0-linux-x64.tar.xz 
# Extracting node.js 
# Downloading yarn from https://github.com/yarnpkg/yarn/releases/download/v1.22.10/yarn-v1.22.10.tar.gz 
# Extracting yarn 
# Building NNI manager 
/home/huan/nni/toolchain/yarn/bin/yarn: 20: exec: node: Exec format error
Traceback (most recent call last):
  File "setup.py", line 243, in <module>
    _setup()
  File "setup.py", line 106, in _setup
    'develop': Develop,
  File "/home/huan/.virtualenvs/facerecog/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 207, in run
    setup_ts.build(release=None)
  File "/home/huan/nni/setup_ts.py", line 42, in build
    compile_ts()
  File "/home/huan/nni/setup_ts.py", line 142, in compile_ts
    _yarn('ts/nni_manager')
  File "/home/huan/nni/setup_ts.py", line 218, in _yarn
    subprocess.run([str(_yarn_path), *args], cwd=path, check=True, env=_yarn_env)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/huan/nni/toolchain/yarn/bin/yarn']' returned non-zero exit status 2.

Can anyone help me?

**Comment by liuzhe-lz** [comment]
NNI does not support ARM CPUs.
If you want to have a try anyway, you can change download URL of [node.js](https://github.com/microsoft/nni/blob/master/setup_ts.py#L68) and [yarn](https://github.com/microsoft/nni/blob/master/setup_ts.py#L74) in `setp_ts.py`.

**Comment by CommandoHuan** [comment]
> NNI does not support ARM CPUs.
> If you want to have a try anyway, you can change `x64` in [this line](https://github.com/microsoft/nni/blob/master/setup_ts.py#L68) to `arm64`.

Thank for your help.
