### ISSUE TITLE
AttributeError: 'HyperoptTuner' object has no attribute 'name' in python api mode

### ISSUE THREAD

**Issue by KersyTom** [microsoft/nni#3889]
**Describe the issue**:
when i wan start an experiment by using python api,ihave met some questions,i configured 'ExperimentConfig' class,add a 'tpe' tuner,a local train service 
- code
```python
from nni.algorithms.hpo.hyperopt_tuner import HyperoptTuner
from nni.experiment import ExperimentConfig, Experiment

tpe_tuner = HyperoptTuner(algorithm_name='tpe')
train_service_conf = dict()
train_service_conf['max_trial_number_per_gpu'] = 0
train_service_conf['platform'] = 'local'
exp_config = ExperimentConfig(trainingservice=train_service_conf)
exp_config.name = 'sklearn_example'
exp_config.experiment_name = 'api_exp'
exp_config.trial_concurrency = 2
exp_config.max_trial_number = 2
exp_config.tuner = tpe_tuner
search_space = {
    "model_name": {"_type": "choice", "_value": ["LinerRegression", "Lars", "Ridge", "ARDRegression"]},
    "normalize": {"_type": "choice", "_value": ["true", "false"]}
}
exp_config.search_space = search_space
exp_config.trial_command = 'E:\\pythonProject\\nni-example\\venv\\Script\\python mani.py'
exp_config.rial_code_directory = '.'
exp = Experiment(config=exp_config)
exp.start(port=8081, debug=True)
```
-  questions
https://github.com/microsoft/nni/blob/749a463aeeab98d08a428f1a7c2494982da23515/nni/experiment/config/base.py#L91
https://github.com/microsoft/nni/blob/749a463aeeab98d08a428f1a7c2494982da23515/nni/experiment/config/common.py#L137
```python
def canonical(self: T) -> T:
        """
        Returns a deep copy, where the fields supporting multiple formats are converted to the canonical format.
        Noticeably, relative path may be converted to absolute path.
        """
        ret = copy.deepcopy(self)
        for field in dataclasses.fields(ret):
            key, value = field.name, getattr(ret, field.name)
            rule = ret._canonical_rules.get(key)
            if rule is not None:
                setattr(ret, key, rule(value))
            elif isinstance(value, ConfigBase):
                setattr(ret, key, value.canonical())
                # value will be copied twice, should not be a performance issue anyway
            elif isinstance(value, Path):
                setattr(ret, key, str(value))
        return ret
```
```python
_canonical_rules = {
    'search_space_file': util.canonical_path,
    'trial_code_directory': util.canonical_path,
    'max_experiment_duration': lambda value: f'{util.parse_time(value)}s' if value is not None else None,
    'experiment_working_directory': util.canonical_path,
    'tuner_gpu_indices': util.canonical_gpu_indices,
    'tuner': lambda config: None if config is None or config.name == '_none_' else config.canonical(),
    'assessor': lambda config: None if config is None or config.name == '_none_' else config.canonical(),
    'advisor': lambda config: None if config is None or config.name == '_none_' else config.canonical(),
}
```
1. experimentConfig
> class “TrainService” inherits "ConfigBase",when "isinstance(value, ConfigBase)" is ture,can **"setattr(ret, key, value.canonical())"** be excuted?
2. Tuner Config
> in "_canonical_rules",the lamda fuc of "tuner",class Tuner rasie an AttributeError
```txt
E:\pythonProject\nni-example\venv2.3\Scripts\python.exe "D:\python_tool\pycharm\PyCharm Community Edition 2021.1.2\plugins\python-ce\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 57816 --file E:/pythonProject/nni-example/mnist_demo/sklearn/regression23/experimentsApi.py
Connected to pydev debugger (build 211.7442.45)
[2021-06-30 15:16:21] INFO (hyperopt.utils/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2021-06-30 15:16:21] INFO (hyperopt.fmin/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
Traceback (most recent call last):
  File "D:\python_tool\pycharm\PyCharm Community Edition 2021.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\python_tool\pycharm\PyCharm Community Edition 2021.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/pythonProject/nni-example/mnist_demo/sklearn/regression23/experimentsApi.py", line 26, in <module>
    exp.start(port=8081, debug=True)
  File "E:\pythonProject\nni-example\venv2.3\lib\site-packages\nni\experiment\experiment.py", line 117, in start
    self._proc = launcher.start_experiment(self.id, self.config, port, debug, mode=self.mode)
  File "E:\pythonProject\nni-example\venv2.3\lib\site-packages\nni\experiment\launcher.py", line 30, in start_experiment
    config.validate(initialized_tuner=False)
  File "E:\pythonProject\nni-example\venv2.3\lib\site-packages\nni\experiment\config\common.py", line 111, in validate
    super().validate()
  File "E:\pythonProject\nni-example\venv2.3\lib\site-packages\nni\experiment\config\base.py", line 114, in validate
    config = self.canonical()
  File "E:\pythonProject\nni-example\venv2.3\lib\site-packages\nni\experiment\config\common.py", line 104, in canonical
    ret = super().canonical()
  File "E:\pythonProject\nni-example\venv2.3\lib\site-packages\nni\experiment\config\base.py", line 101, in canonical
    setattr(ret, key, rule(value))
  File "E:\pythonProject\nni-example\venv2.3\lib\site-packages\nni\experiment\config\common.py", line 143, in <lambda>
    'tuner': lambda config: None if config is None or config.name == '_none_' else config.canonical(),
AttributeError: 'HyperoptTuner' object has no attribute 'name'
python-BaseException
[2021-06-30 15:16:26] Stopping experiment, please wait...
[2021-06-30 15:16:26] Experiment stopped

Process finished with exit code 1
```
**Environment**:
- NNI version:2.3
- Training service (local|remote|pai|aml|etc):local
- Client OS:windows
- Server OS (for remote mode only):
- Python version:3.6.4
- PyTorch/TensorFlow version:None
- Is conda/virtualenv/venv used?:virtualenv
- Is running in Docker?:no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by KersyTom** [comment]
i was mix up some api function between 2.3 and 2.0,now i have changed to 2.0,my code can run success.
- code
```python
from nni.algorithms.hpo.hyperopt_tuner import HyperoptTuner
from nni.experiment import ExperimentConfig, Experiment

tpe_tuner = HyperoptTuner(algorithm_name='tpe')
train_service_conf = dict()
# train_service_conf['max_trial_number_per_gpu'] = 0
train_service_conf['platform'] = 'local'
exp_config = ExperimentConfig(trainingservice=train_service_conf)
exp_config.name = 'sklearn_example'
exp_config.experiment_name = 'api_exp'
exp_config.trial_concurrency = 2
exp_config.max_trial_number = 2
# exp_config.tuner = tpe_tuner
search_space = {
    "model_name": {"_type": "choice", "_value": ["LinerRegression", "Lars", "Ridge", "ARDRegression"]},
    "normalize": {"_type": "choice", "_value": ["true", "false"]}
}

exp_config.search_space = search_space
exp_config.trial_command = 'python main.py'
exp_config.rial_code_directory = '.'
exp = Experiment(tuner=tpe_tuner, config=exp_config)
exp.start(port=8081, debug=True)
```
