### ISSUE TITLE
Dependency Aware (L1/L2FilterPruner) not working for SSD Object Detection Model

### ISSUE THREAD

**Issue by shenoynikhil98** [microsoft/nni#3932]
I am trying to prune my object detection model (SSD) using the L1 or L2 filter pruner. Currently parameters, FLOPS are as follows.

```
+-------+------------------------------------------------------+--------+-------------------+-----------+---------+
| Index |                         Name                         |  Type  |    Weight Shape   |   FLOPs   | #Params |
+-------+------------------------------------------------------+--------+-------------------+-----------+---------+
|   0   |        feature_extractor.feature_extractor.0         | Conv2d |   (20, 3, 7, 7)   |  66150000 |   2940  |
|   1   |    feature_extractor.feature_extractor.4.0.conv1     | Conv2d |   (64, 20, 1, 1)  |  7200000  |   1280  |
|   2   |    feature_extractor.feature_extractor.4.0.conv2     | Conv2d |   (64, 64, 3, 3)  | 207360000 |  36864  |
|   3   |    feature_extractor.feature_extractor.4.0.conv3     | Conv2d |  (256, 64, 1, 1)  |  92160000 |  16384  |
|   4   | feature_extractor.feature_extractor.4.0.downsample.0 | Conv2d |  (256, 20, 1, 1)  |  28800000 |   5120  |
|   5   |    feature_extractor.feature_extractor.4.1.conv1     | Conv2d |  (64, 256, 1, 1)  |  92160000 |  16384  |
|   6   |    feature_extractor.feature_extractor.4.1.conv2     | Conv2d |   (64, 64, 3, 3)  | 207360000 |  36864  |
|   7   |    feature_extractor.feature_extractor.4.1.conv3     | Conv2d |  (256, 64, 1, 1)  |  92160000 |  16384  |
|   8   |    feature_extractor.feature_extractor.4.2.conv1     | Conv2d |  (64, 256, 1, 1)  |  92160000 |  16384  |
|   9   |    feature_extractor.feature_extractor.4.2.conv2     | Conv2d |   (64, 64, 3, 3)  | 207360000 |  36864  |
|   10  |    feature_extractor.feature_extractor.4.2.conv3     | Conv2d |  (256, 64, 1, 1)  |  92160000 |  16384  |
|   11  |    feature_extractor.feature_extractor.5.0.conv1     | Conv2d |  (39, 256, 1, 1)  |  56160000 |   9984  |
|   12  |    feature_extractor.feature_extractor.5.0.conv2     | Conv2d |   (39, 39, 3, 3)  |  19766916 |  13689  |
|   13  |    feature_extractor.feature_extractor.5.0.conv3     | Conv2d |  (512, 39, 1, 1)  |  28833792 |  19968  |
|   14  | feature_extractor.feature_extractor.5.0.downsample.0 | Conv2d |  (512, 256, 1, 1) | 189267968 |  131072 |
|   15  |    feature_extractor.feature_extractor.5.1.conv1     | Conv2d |  (39, 512, 1, 1)  |  28833792 |  19968  |
|   16  |    feature_extractor.feature_extractor.5.1.conv2     | Conv2d |   (39, 39, 3, 3)  |  19766916 |  13689  |
|   17  |    feature_extractor.feature_extractor.5.1.conv3     | Conv2d |  (512, 39, 1, 1)  |  28833792 |  19968  |
|   18  |    feature_extractor.feature_extractor.5.2.conv1     | Conv2d |  (39, 512, 1, 1)  |  28833792 |  19968  |
|   19  |    feature_extractor.feature_extractor.5.2.conv2     | Conv2d |   (39, 39, 3, 3)  |  19766916 |  13689  |
|   20  |    feature_extractor.feature_extractor.5.2.conv3     | Conv2d |  (512, 39, 1, 1)  |  28833792 |  19968  |
|   21  |    feature_extractor.feature_extractor.5.3.conv1     | Conv2d |  (39, 512, 1, 1)  |  28833792 |  19968  |
|   22  |    feature_extractor.feature_extractor.5.3.conv2     | Conv2d |   (39, 39, 3, 3)  |  19766916 |  13689  |
|   23  |    feature_extractor.feature_extractor.5.3.conv3     | Conv2d |  (512, 128, 1, 1) |  94633984 |  65536  |
|   24  |    feature_extractor.feature_extractor.6.0.conv1     | Conv2d |  (256, 512, 1, 1) | 189267968 |  131072 |
|   25  |    feature_extractor.feature_extractor.6.0.conv2     | Conv2d |  (256, 256, 3, 3) | 851705856 |  589824 |
|   26  |    feature_extractor.feature_extractor.6.0.conv3     | Conv2d | (1024, 256, 1, 1) | 378535936 |  262144 |
|   27  | feature_extractor.feature_extractor.6.0.downsample.0 | Conv2d | (1024, 512, 1, 1) | 757071872 |  524288 |
|   28  |    feature_extractor.feature_extractor.6.1.conv1     | Conv2d | (256, 1024, 1, 1) | 378535936 |  262144 |
|   29  |    feature_extractor.feature_extractor.6.1.conv2     | Conv2d |  (256, 256, 3, 3) | 851705856 |  589824 |
|   30  |    feature_extractor.feature_extractor.6.1.conv3     | Conv2d | (1024, 256, 1, 1) | 378535936 |  262144 |
|   31  |    feature_extractor.feature_extractor.6.2.conv1     | Conv2d | (256, 1024, 1, 1) | 378535936 |  262144 |
|   32  |    feature_extractor.feature_extractor.6.2.conv2     | Conv2d |  (256, 256, 3, 3) | 851705856 |  589824 |
|   33  |    feature_extractor.feature_extractor.6.2.conv3     | Conv2d | (1024, 256, 1, 1) | 378535936 |  262144 |
|   34  |    feature_extractor.feature_extractor.6.3.conv1     | Conv2d | (256, 1024, 1, 1) | 378535936 |  262144 |
|   35  |    feature_extractor.feature_extractor.6.3.conv2     | Conv2d |  (256, 256, 3, 3) | 851705856 |  589824 |
|   36  |    feature_extractor.feature_extractor.6.3.conv3     | Conv2d | (1024, 256, 1, 1) | 378535936 |  262144 |
|   37  |    feature_extractor.feature_extractor.6.4.conv1     | Conv2d | (256, 1024, 1, 1) | 378535936 |  262144 |
|   38  |    feature_extractor.feature_extractor.6.4.conv2     | Conv2d |  (256, 256, 3, 3) | 851705856 |  589824 |
|   39  |    feature_extractor.feature_extractor.6.4.conv3     | Conv2d | (1024, 256, 1, 1) | 378535936 |  262144 |
|   40  |    feature_extractor.feature_extractor.6.5.conv1     | Conv2d | (256, 1024, 1, 1) | 378535936 |  262144 |
|   41  |    feature_extractor.feature_extractor.6.5.conv2     | Conv2d |  (256, 256, 3, 3) | 851705856 |  589824 |
|   42  |    feature_extractor.feature_extractor.6.5.conv3     | Conv2d | (1024, 256, 1, 1) | 378535936 |  262144 |
|   43  |                additional_blocks.0.0                 | Conv2d | (256, 1024, 1, 1) | 378535936 |  262144 |
|   44  |                additional_blocks.0.3                 | Conv2d |  (512, 256, 3, 3) | 425852928 | 1179648 |
|   45  |                additional_blocks.1.0                 | Conv2d |  (256, 512, 1, 1) |  47316992 |  131072 |
|   46  |                additional_blocks.1.3                 | Conv2d |  (512, 256, 3, 3) | 117964800 | 1179648 |
|   47  |                additional_blocks.2.0                 | Conv2d |  (128, 512, 1, 1) |  6553600  |  65536  |
|   48  |                additional_blocks.2.3                 | Conv2d |  (256, 128, 3, 3) |  7372800  |  294912 |
|   49  |                additional_blocks.3.0                 | Conv2d |  (128, 256, 1, 1) |   819200  |  32768  |
|   50  |                additional_blocks.3.3                 | Conv2d |  (256, 128, 3, 3) |  2654208  |  294912 |
|   51  |                additional_blocks.4.0                 | Conv2d |  (128, 256, 1, 1) |   294912  |  32768  |
|   52  |                additional_blocks.4.3                 | Conv2d |  (256, 128, 3, 3) |   294912  |  294912 |
|   53  |                        loc.0                         | Conv2d |  (16, 1024, 3, 3) | 212926464 |  147472 |
|   54  |                        conf.0                        | Conv2d |  (12, 1024, 3, 3) | 159694848 |  110604 |
|   55  |                        loc.1                         | Conv2d |  (24, 512, 3, 3)  |  39923712 |  110616 |
|   56  |                        conf.1                        | Conv2d |  (18, 512, 3, 3)  |  29942784 |  82962  |
|   57  |                        loc.2                         | Conv2d |  (24, 512, 3, 3)  |  11059200 |  110616 |
|   58  |                        conf.2                        | Conv2d |  (18, 512, 3, 3)  |  8294400  |  82962  |
|   59  |                        loc.3                         | Conv2d |  (24, 256, 3, 3)  |  1382400  |  55320  |
|   60  |                        conf.3                        | Conv2d |  (18, 256, 3, 3)  |  1036800  |  41490  |
|   61  |                        loc.4                         | Conv2d |  (16, 256, 3, 3)  |   331776  |  36880  |
|   62  |                        conf.4                        | Conv2d |  (12, 256, 3, 3)  |   248832  |  27660  |
|   63  |                        loc.5                         | Conv2d |  (16, 256, 3, 3)  |   36864   |  36880  |
|   64  |                        conf.5                        | Conv2d |  (12, 256, 3, 3)  |   27648   |  27660  |
+-------+------------------------------------------------------+--------+-------------------+-----------+---------+
FLOPs total: 14970528000
#Params total: 13152146
```

I tried to use dependency aware L2 Filter Pruner with the following configuration, (`op_types = 'Conv2d' sparsity = 0.8`). The L2Filter pruner is not able to compress using the one shot filter pruner giving the following error.
```
[07/12/2021 08:55:53 PM] Instantiating Pruner <nni.algorithms.compression.pytorch.pruning.L2FilterPruner>
[2021-07-12 20:55:53] INFO (src.prune/MainThread) Instantiating Pruner <nni.algorithms.compression.pytorch.pruning.L2FilterPruner>
[07/12/2021 08:55:57 PM] Pruning the dependent layers: feature_extractor.feature_extractor.5.1.conv1
[2021-07-12 20:55:57] INFO (nni.algorithms.compression.pytorch.pruning.dependency_aware_pruner/MainThread) Pruning the dependent layers: feature_extractor.feature_extractor.5.1.conv1
[07/12/2021 08:55:57 PM] Prune the 0,2,3,4,6,7,8,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,32,33,34,36,37,38,40,41,42,43,47,48,49,53,54,55,56,57,58,59,60,62,63,65,66,67,68,69,70,71,72,74,77,78,80,81,82,83,84,85,87,90,91,94,95,96,98,99,100,101,103,106,108,110,111,113,114,115,116,118,120,121,122,123,125,127 channels for all dependent
[2021-07-12 20:55:57] INFO (torch filter pruners/MainThread) Prune the 0,2,3,4,6,7,8,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,32,33,34,36,37,38,40,41,42,43,47,48,49,53,54,55,56,57,58,59,60,62,63,65,66,67,68,69,70,71,72,74,77,78,80,81,82,83,84,85,87,90,91,94,95,96,98,99,100,101,103,106,108,110,111,113,114,115,116,118,120,121,122,123,125,127 channels for all dependent
[07/12/2021 08:55:57 PM] Pruning the dependent layers: feature_extractor.feature_extractor.5.1.conv2
[2021-07-12 20:55:57] INFO (nni.algorithms.compression.pytorch.pruning.dependency_aware_pruner/MainThread) Pruning the dependent layers: feature_extractor.feature_extractor.5.1.conv2
[07/12/2021 08:55:57 PM] Prune the 0,1,4,5,6,7,8,9,10,11,13,14,16,17,18,20,23,26,27,28,29,30,32,34,35,36,38,40,42,44,45,46,47,48,50,54,55,56,57,58,59,61,62,65,66,67,68,70,71,72,74,75,76,77,81,82,83,84,85,86,88,90,91,93,94,96,97,98,99,100,101,102,105,107,108,109,111,112,113,114,115,117,119,120,121,122,123,126,127 channels for all dependent
[2021-07-12 20:55:57] INFO (torch filter pruners/MainThread) Prune the 0,1,4,5,6,7,8,9,10,11,13,14,16,17,18,20,23,26,27,28,29,30,32,34,35,36,38,40,42,44,45,46,47,48,50,54,55,56,57,58,59,61,62,65,66,67,68,70,71,72,74,75,76,77,81,82,83,84,85,86,88,90,91,93,94,96,97,98,99,100,101,102,105,107,108,109,111,112,113,114,115,117,119,120,121,122,123,126,127 channels for all dependent
[07/12/2021 08:55:57 PM] Pruning the dependent layers: feature_extractor.feature_extractor.5.2.conv3,feature_extractor.feature_extractor.5.0.downsample.0,feature_extractor.feature_extractor.5.0.conv3,feature_extractor.feature_extractor.5.1.conv3,feature_extractor.feature_extractor.5.3.conv3
[2021-07-12 20:55:57] INFO (nni.algorithms.compression.pytorch.pruning.dependency_aware_pruner/MainThread) Pruning the dependent layers: feature_extractor.feature_extractor.5.2.conv3,feature_extractor.feature_extractor.5.0.downsample.0,feature_extractor.feature_extractor.5.0.conv3,feature_extractor.feature_extractor.5.1.conv3,feature_extractor.feature_extractor.5.3.conv3
[07/12/2021 08:55:57 PM] Prune the  channels for all dependent
[2021-07-12 20:55:57] INFO (torch filter pruners/MainThread) Prune the  channels for all dependent
[07/12/2021 08:55:57 PM] Pruning the dependent layers: feature_extractor.feature_extractor.5.2.conv1
[2021-07-12 20:55:57] INFO (nni.algorithms.compression.pytorch.pruning.dependency_aware_pruner/MainThread) Pruning the dependent layers: feature_extractor.feature_extractor.5.2.conv1
[07/12/2021 08:55:57 PM] Prune the 0,1,2,4,5,6,7,8,10,11,12,14,17,18,19,21,22,24,25,27,28,29,31,32,33,35,36,40,42,43,45,47,49,50,51,52,53,54,57,59,60,61,65,66,67,68,69,70,74,75,76,77,78,79,82,83,85,86,88,89,90,92,93,95,96,97,99,100,101,103,107,108,109,110,111,112,113,114,115,117,118,119,120,121,122,123,125,126,127 channels for all dependent
[2021-07-12 20:55:57] INFO (torch filter pruners/MainThread) Prune the 0,1,2,4,5,6,7,8,10,11,12,14,17,18,19,21,22,24,25,27,28,29,31,32,33,35,36,40,42,43,45,47,49,50,51,52,53,54,57,59,60,61,65,66,67,68,69,70,74,75,76,77,78,79,82,83,85,86,88,89,90,92,93,95,96,97,99,100,101,103,107,108,109,110,111,112,113,114,115,117,118,119,120,121,122,123,125,126,127 channels for all dependent
[07/12/2021 08:55:57 PM] Pruning the dependent layers: feature_extractor.feature_extractor.5.2.conv2
[2021-07-12 20:55:57] INFO (nni.algorithms.compression.pytorch.pruning.dependency_aware_pruner/MainThread) Pruning the dependent layers: feature_extractor.feature_extractor.5.2.conv2
[07/12/2021 08:55:57 PM] Prune the 0,1,3,6,8,10,11,12,13,16,17,18,19,20,21,22,23,24,28,29,32,33,34,35,36,37,38,39,40,41,42,43,45,46,47,48,49,50,51,53,54,55,60,61,62,63,64,66,68,69,71,72,73,74,75,76,78,81,82,85,86,87,89,90,92,94,95,96,98,99,101,102,103,104,106,110,111,112,113,114,115,117,118,119,120,122,123,124,125 channels for all dependent
[2021-07-12 20:55:57] INFO (torch filter pruners/MainThread) Prune the 0,1,3,6,8,10,11,12,13,16,17,18,19,20,21,22,23,24,28,29,32,33,34,35,36,37,38,39,40,41,42,43,45,46,47,48,49,50,51,53,54,55,60,61,62,63,64,66,68,69,71,72,73,74,75,76,78,81,82,85,86,87,89,90,92,94,95,96,98,99,101,102,103,104,106,110,111,112,113,114,115,117,118,119,120,122,123,124,125 channels for all dependent
[07/12/2021 08:55:57 PM] Pruning the dependent layers: feature_extractor.feature_extractor.5.3.conv1
[2021-07-12 20:55:57] INFO (nni.algorithms.compression.pytorch.pruning.dependency_aware_pruner/MainThread) Pruning the dependent layers: feature_extractor.feature_extractor.5.3.conv1
[07/12/2021 08:55:57 PM] Prune the 0,1,3,4,5,6,7,8,10,11,12,15,16,17,19,20,21,23,25,26,27,28,29,30,31,32,34,35,36,38,39,40,41,42,45,46,48,51,52,53,54,55,59,60,61,67,69,70,71,73,74,75,77,78,80,81,83,84,85,87,88,90,91,93,94,95,96,97,99,100,101,102,103,104,105,106,107,108,109,111,112,113,117,118,121,122,123,124,126 channels for all dependent
[2021-07-12 20:55:57] INFO (torch filter pruners/MainThread) Prune the 0,1,3,4,5,6,7,8,10,11,12,15,16,17,19,20,21,23,25,26,27,28,29,30,31,32,34,35,36,38,39,40,41,42,45,46,48,51,52,53,54,55,59,60,61,67,69,70,71,73,74,75,77,78,80,81,83,84,85,87,88,90,91,93,94,95,96,97,99,100,101,102,103,104,105,106,107,108,109,111,112,113,117,118,121,122,123,124,126 channels for all dependent
[07/12/2021 08:55:57 PM] Pruning the dependent layers: feature_extractor.feature_extractor.5.3.conv2
[2021-07-12 20:55:57] INFO (nni.algorithms.compression.pytorch.pruning.dependency_aware_pruner/MainThread) Pruning the dependent layers: feature_extractor.feature_extractor.5.3.conv2
[07/12/2021 08:55:57 PM] Prune the 0,1,2,3,5,7,8,9,10,11,12,13,15,16,17,19,20,21,22,24,25,26,27,28,29,31,32,33,35,36,37,38,40,41,43,44,45,48,50,52,53,54,56,57,58,59,60,61,62,65,66,67,69,70,71,72,74,77,79,80,82,83,85,88,90,94,95,96,97,98,99,100,101,102,104,105,106,108,110,111,113,114,115,118,119,120,122,123,126 channels for all dependent
[2021-07-12 20:55:57] INFO (torch filter pruners/MainThread) Prune the 0,1,2,3,5,7,8,9,10,11,12,13,15,16,17,19,20,21,22,24,25,26,27,28,29,31,32,33,35,36,37,38,40,41,43,44,45,48,50,52,53,54,56,57,58,59,60,61,62,65,66,67,69,70,71,72,74,77,79,80,82,83,85,88,90,94,95,96,97,98,99,100,101,102,104,105,106,108,110,111,113,114,115,118,119,120,122,123,126 channels for all dependent
[07/12/2021 08:55:57 PM] Pruning the dependent layers: feature_extractor.feature_extractor.6.0.conv1
[2021-07-12 20:55:57] INFO (nni.algorithms.compression.pytorch.pruning.dependency_aware_pruner/MainThread) Pruning the dependent layers: feature_extractor.feature_extractor.6.0.conv1
[07/12/2021 08:55:57 PM] Prune the 0,1,3,4,5,7,9,10,11,14,15,16,17,18,19,21,23,24,26,27,29,31,32,33,36,37,38,39,40,41,42,44,45,48,49,50,52,53,54,55,56,57,58,61,63,64,66,67,68,69,70,72,74,76,78,79,80,81,82,83,84,87,88,89,90,92,93,94,95,96,97,98,99,100,104,105,106,108,109,110,111,113,114,115,117,119,121,122,123,124,125,126,128,129,132,134,135,136,138,139,141,142,143,144,145,150,151,152,153,154,155,156,157,158,159,161,162,163,164,165,166,167,168,169,170,171,173,175,178,180,182,183,186,188,190,191,194,195,197,198,199,200,202,203,205,206,207,208,212,215,217,218,220,221,222,223,224,225,226,229,230,232,233,234,235,236,237,238,239,241,242,243,244,246,247,248,249,251,252 channels for all dependent
[2021-07-12 20:55:57] INFO (torch filter pruners/MainThread) Prune the 0,1,3,4,5,7,9,10,11,14,15,16,17,18,19,21,23,24,26,27,29,31,32,33,36,37,38,39,40,41,42,44,45,48,49,50,52,53,54,55,56,57,58,61,63,64,66,67,68,69,70,72,74,76,78,79,80,81,82,83,84,87,88,89,90,92,93,94,95,96,97,98,99,100,104,105,106,108,109,110,111,113,114,115,117,119,121,122,123,124,125,126,128,129,132,134,135,136,138,139,141,142,143,144,145,150,151,152,153,154,155,156,157,158,159,161,162,163,164,165,166,167,168,169,170,171,173,175,178,180,182,183,186,188,190,191,194,195,197,198,199,200,202,203,205,206,207,208,212,215,217,218,220,221,222,223,224,225,226,229,230,232,233,234,235,236,237,238,239,241,242,243,244,246,247,248,249,251,252 channels for all dependent
[07/12/2021 08:55:57 PM] Pruning the dependent layers: feature_extractor.feature_extractor.6.0.conv2
[2021-07-12 20:55:57] INFO (nni.algorithms.compression.pytorch.pruning.dependency_aware_pruner/MainThread) Pruning the dependent layers: feature_extractor.feature_extractor.6.0.conv2
[07/12/2021 08:55:57 PM] Prune the 1,2,3,4,5,6,7,8,9,11,13,14,15,17,19,20,21,22,24,25,26,27,28,36,37,38,39,40,41,43,44,45,47,49,50,52,53,54,55,56,57,58,59,60,61,62,64,69,70,73,74,75,76,77,82,83,84,85,87,89,90,92,93,95,96,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,115,116,117,118,119,120,121,123,126,127,128,131,133,134,135,136,138,140,141,143,145,146,147,148,150,151,152,153,154,156,157,158,159,160,161,162,163,164,165,167,168,169,170,172,173,175,176,177,178,179,181,182,185,186,191,192,194,195,196,197,199,201,202,204,206,207,208,209,210,212,214,215,218,219,220,221,223,224,229,230,232,233,234,236,238,240,242,243,244,245,246,247,248,249,250,253,254,255 channels for all dependent
[2021-07-12 20:55:57] INFO (torch filter pruners/MainThread) Prune the 1,2,3,4,5,6,7,8,9,11,13,14,15,17,19,20,21,22,24,25,26,27,28,36,37,38,39,40,41,43,44,45,47,49,50,52,53,54,55,56,57,58,59,60,61,62,64,69,70,73,74,75,76,77,82,83,84,85,87,89,90,92,93,95,96,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,115,116,117,118,119,120,121,123,126,127,128,131,133,134,135,136,138,140,141,143,145,146,147,148,150,151,152,153,154,156,157,158,159,160,161,162,163,164,165,167,168,169,170,172,173,175,176,177,178,179,181,182,185,186,191,192,194,195,196,197,199,201,202,204,206,207,208,209,210,212,214,215,218,219,220,221,223,224,229,230,232,233,234,236,238,240,242,243,244,245,246,247,248,249,250,253,254,255 channels for all dependent
[07/12/2021 08:55:57 PM] Pruning the dependent layers: conf.1,feature_extractor.feature_extractor.6.5.conv3,loc.4,conf.4,additional_blocks.3.3,loc.0,feature_extractor.feature_extractor.6.4.conv3,loc.1,feature_extractor.feature_extractor.6.2.conv3,loc.3,additional_blocks.0.3,feature_extractor.feature_extractor.6.0.downsample.0,loc.5,loc.2,conf.3,additional_blocks.2.3,conf.2,additional_blocks.1.3,additional_blocks.4.3,feature_extractor.feature_extractor.6.0.conv3,feature_extractor.feature_extractor.6.1.conv3,feature_extractor.feature_extractor.6.3.conv3,conf.0,conf.5
[2021-07-12 20:55:57] INFO (nni.algorithms.compression.pytorch.pruning.dependency_aware_pruner/MainThread) Pruning the dependent layers: conf.1,feature_extractor.feature_extractor.6.5.conv3,loc.4,conf.4,additional_blocks.3.3,loc.0,feature_extractor.feature_extractor.6.4.conv3,loc.1,feature_extractor.feature_extractor.6.2.conv3,loc.3,additional_blocks.0.3,feature_extractor.feature_extractor.6.0.downsample.0,loc.5,loc.2,conf.3,additional_blocks.2.3,conf.2,additional_blocks.1.3,additional_blocks.4.3,feature_extractor.feature_extractor.6.0.conv3,feature_extractor.feature_extractor.6.1.conv3,feature_extractor.feature_extractor.6.3.conv3,conf.0,conf.5
Traceback (most recent call last):
  File "run.py", line 136, in <module>
    main(args)
  File "run.py", line 98, in main
    return fit_prune(config, ckpt_PATH, args.evaluate_test)
  File "/workspace/pest-monitoring-new/src/prune.py", line 124, in fit_prune
    model.network = pruner.compress()
  File "/usr/local/lib/python3.6/dist-packages/nni/compression/pytorch/compressor.py", line 334, in compress
    self.update_mask()
  File "/usr/local/lib/python3.6/dist-packages/nni/algorithms/compression/pytorch/pruning/dependency_aware_pruner.py", line 82, in update_mask
    self._dependency_update_mask()
  File "/usr/local/lib/python3.6/dist-packages/nni/algorithms/compression/pytorch/pruning/dependency_aware_pruner.py", line 156, in _dependency_update_mask
    _wrappers, _names, wrappers_idx=_wrapper_idxes)
  File "/usr/local/lib/python3.6/dist-packages/nni/algorithms/compression/pytorch/pruning/dependency_aware_pruner.py", line 125, in _dependency_calc_mask
    sparsities, wrappers, wrappers_idx, channel_dsets=channel_dsets, groups=groups)
  File "/usr/local/lib/python3.6/dist-packages/nni/algorithms/compression/pytorch/pruning/structured_pruning_masker.py", line 70, in calc_mask
    return self._dependency_calc_mask(sparsity, wrapper, wrapper_idx, **depen_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/nni/algorithms/compression/pytorch/pruning/structured_pruning_masker.py", line 264, in _dependency_calc_mask
    sparsities, wrappers, wrappers_idx, channel_dsets, groups)
  File "/usr/local/lib/python3.6/dist-packages/nni/algorithms/compression/pytorch/pruning/structured_pruning_masker.py", line 212, in _common_channel_to_prune
    channel_sum += c_sum
RuntimeError: The size of tensor a (18) must match the size of tensor b (16) at non-singleton dimension 0
```
What is the issue we are facing and why?

This issue does not arise if I simply mention conv2d modules (using op_names instead of op_types) that do not have any dependencies (using topological analysis). But isnt dependency aware mode supposed to handle these conv2d modules?

**Comment by zheng-ningxin** [comment]
Hi thanks for the valuable feedback. `Dependency-aware` indeed should handle these conv2d modules. At present, the tool for analyzing model topology in `dependency-aware` does not support the SSD model. We are expanding this tool to support more model structures.

**Comment by gkrisp98** [comment]
> Hi thanks for the valuable feedback. `Dependency-aware` indeed should handle these conv2d modules. At present, the tool for analyzing model topology in `dependency-aware` does not support the SSD model. We are expanding this tool to support more model structures.

Hi @zheng-ningxin , does 'dependency-aware' currently support SSD model ?
