### ISSUE TITLE
nnictl works but nni launch from python code is not working

### ISSUE THREAD

**Issue by mf-giwoong-lee** [microsoft/nni#3942]
**Describe the issue**:
I am using nni in recent days. I upgrade the version of nni from 1.9 to 2.3 to use nni code level launching.

But It is not working properly, It fails to run.

Also I set max_trial_number_per_gpu as 3 and I have 2 gpus. So in my expectation, 6 trials are running in parallel manner but in real, 12 trials are running in parallel because of trial_concurrency=12.
This is my code.
```
from nni.experiment import Experiment as Exp
from pathlib import Path
import json
import yaml

with open('config_bohb.yml') as f:
    config_bohb = yaml.load(f, Loader=yaml.FullLoader)

with open('search_space_deepAR.json') as f:
    search_space = json.load(f)

nni_exp = Exp('local')
nni_exp.config.experiment_name = "electrocity nni test"
nni_exp.config.search_space = search_space
nni_exp.config.use_annotation = config_bohb['useAnnotation']
nni_exp.config.trial_concurrency = 6 # config_bohb['trialConcurrency']
nni_exp.config.max_trial_number = config_bohb['maxTrialNum']
nni_exp.config.trial_command = "DISABLE_TQDM=1 python3 main.py --config default_config --exp_group nni_elec"
nni_exp.config.trial_code_directory = Path(__file__).parent
# nni_exp.config.tuner.name = 'TPE'
# nni_exp.config.tuner.class_args['optimize_mode'] = 'minimize'
nni_exp.config.advisor.name = config_bohb["advisor"]["builtinAdvisorName"]
for key in config_bohb["advisor"]["classArgs"].keys():
    nni_exp.config.advisor.class_args[key] = config_bohb["advisor"]["classArgs"][key]
nni_exp.config.training_service.use_active_gpu = True
nni_exp.config.trial_gpu_num=config_bohb["trial"]["gpuNum"]
nni_exp.config.training_service.max_trial_number_per_gpu = 3 #config_bohb["localConfig"]["maxTrialNumPerGpu"]
nni_exp.config.max_trial_duration = "1000h"
print(nni_exp.config.training_service)
print(nni_exp.config.advisor)

nni_exp.run(port=8888)
```

**Environment**:
- NNI version: 2.3
- Training service (local|remote|pai|aml|etc): local
- Client OS: ubuntu 18.04 LTS in docker container
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: 1.7.1
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: yes

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space: 

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 [2021-07-15 07:31:50] INFO (NNIDataStore) Datastore initialization done
[2021-07-15 07:31:50] INFO (RestServer) RestServer start
[2021-07-15 07:31:50] INFO (RestServer) RestServer base port is 8888
[2021-07-15 07:31:50] INFO (main) Rest server listening on: http://0.0.0.0:8888
[2021-07-15 07:31:51] INFO (NNIManager) Starting experiment: r9midpbq
[2021-07-15 07:31:51] INFO (NNIManager) Setup training service...
[2021-07-15 07:31:51] INFO (LocalTrainingService) Construct local machine training service.
[2021-07-15 07:31:51] INFO (NNIManager) Setup tuner...
[2021-07-15 07:31:51] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-07-15 07:31:51] INFO (NNIManager) Add event listeners
[2021-07-15 07:31:51] INFO (LocalTrainingService) Run local machine training service.
[2021-07-15 07:31:52] INFO (NNIManager) NNIManager received command from dispatcher: ID,
[2021-07-15 07:31:52] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": "2_0_0", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 8, "estimator/dropout_rate": 0.19624969224933644, "estimator/num_cells": 320, "estimator/num_layers": 2, "trainer/batch_size": 4, "trainer/learning_rate": 0.0009455489830095034, "trainer/weight_decay": 0.00016424188807956882, "TRIAL_BUDGET": 1}}
[2021-07-15 07:31:52] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": "2_0_1", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 12, "estimator/dropout_rate": 0.026774386047165578, "estimator/num_cells": 80, "estimator/num_layers": 4, "trainer/batch_size": 16, "trainer/learning_rate": 0.0007923073541206817, "trainer/weight_decay": 0.000815330916576722, "TRIAL_BUDGET": 1}}
[2021-07-15 07:31:52] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": "2_0_2", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 12, "estimator/dropout_rate": 0.13848003644422316, "estimator/num_cells": 80, "estimator/num_layers": 2, "trainer/batch_size": 64, "trainer/learning_rate": 0.0022388613407443667, "trainer/weight_decay": 0.0007210078996762262, "TRIAL_BUDGET": 1}}
[2021-07-15 07:31:52] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": "2_0_3", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 12, "estimator/dropout_rate": 0.2821601869245385, "estimator/num_cells": 160, "estimator/num_layers": 2, "trainer/batch_size": 4, "trainer/learning_rate": 0.0037207472264278664, "trainer/weight_decay": 0.0009041399100555868, "TRIAL_BUDGET": 1}}
[2021-07-15 07:31:52] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": "2_0_4", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 8, "estimator/dropout_rate": 0.05544362239418686, "estimator/num_cells": 320, "estimator/num_layers": 2, "trainer/batch_size": 16, "trainer/learning_rate": 0.000568484796327676, "trainer/weight_decay": 7.504033869326922e-05, "TRIAL_BUDGET": 1}}
[2021-07-15 07:31:52] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": "2_0_5", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 4, "estimator/dropout_rate": 0.22339963520198922, "estimator/num_cells": 320, "estimator/num_layers": 3, "trainer/batch_size": 4, "trainer/learning_rate": 0.0019813197613154855, "trainer/weight_decay": 0.000716395501532327, "TRIAL_BUDGET": 1}}
[2021-07-15 07:31:56] INFO (NNIManager) submitTrialJob: form: { sequenceId: 0,
  hyperParameters:
   { value:
      '{"parameter_id": "2_0_0", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 8, "estimator/dropout_rate": 0.19624969224933644, "estimator/num_cells": 320, "estimator/num_layers": 2, "trainer/batch_size": 4, "trainer/learning_rate": 0.0009455489830095034, "trainer/weight_decay": 0.00016424188807956882, "TRIAL_BUDGET": 1}}',
     index: 0 } }
[2021-07-15 07:31:56] INFO (NNIManager) submitTrialJob: form: { sequenceId: 1,
  hyperParameters:
   { value:
      '{"parameter_id": "2_0_1", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 12, "estimator/dropout_rate": 0.026774386047165578, "estimator/num_cells": 80, "estimator/num_layers": 4, "trainer/batch_size": 16, "trainer/learning_rate": 0.0007923073541206817, "trainer/weight_decay": 0.000815330916576722, "TRIAL_BUDGET": 1}}',
     index: 0 } }
[2021-07-15 07:31:57] INFO (NNIManager) submitTrialJob: form: { sequenceId: 2,
  hyperParameters:
   { value:
      '{"parameter_id": "2_0_2", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 12, "estimator/dropout_rate": 0.13848003644422316, "estimator/num_cells": 80, "estimator/num_layers": 2, "trainer/batch_size": 64, "trainer/learning_rate": 0.0022388613407443667, "trainer/weight_decay": 0.0007210078996762262, "TRIAL_BUDGET": 1}}',
     index: 0 } }
[2021-07-15 07:31:57] INFO (NNIManager) submitTrialJob: form: { sequenceId: 3,
  hyperParameters:
   { value:
      '{"parameter_id": "2_0_3", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 12, "estimator/dropout_rate": 0.2821601869245385, "estimator/num_cells": 160, "estimator/num_layers": 2, "trainer/batch_size": 4, "trainer/learning_rate": 0.0037207472264278664, "trainer/weight_decay": 0.0009041399100555868, "TRIAL_BUDGET": 1}}',
     index: 0 } }
[2021-07-15 07:31:57] INFO (NNIManager) submitTrialJob: form: { sequenceId: 4,
  hyperParameters:
   { value:
      '{"parameter_id": "2_0_1", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 12, "estimator/dropout_rate": 0.026774386047165578, "estimator/num_cells": 80, "estimator/num_layers": 4, "trainer/batch_size": 16, "trainer/learning_rate": 0.0007923073541206817, "trainer/weight_decay": 0.000815330916576722, "TRIAL_BUDGET": 1}}',
     index: 0 } }
[2021-07-15 07:31:57] INFO (NNIManager) submitTrialJob: form: { sequenceId: 2,
  hyperParameters:
   { value:
      '{"parameter_id": "2_0_2", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 12, "estimator/dropout_rate": 0.13848003644422316, "estimator/num_cells": 80, "estimator/num_layers": 2, "trainer/batch_size": 64, "trainer/learning_rate": 0.0022388613407443667, "trainer/weight_decay": 0.0007210078996762262, "TRIAL_BUDGET": 1}}',
     index: 0 } }
[2021-07-15 07:31:57] INFO (NNIManager) submitTrialJob: form: { sequenceId: 3,
  hyperParameters:
   { value:
      '{"parameter_id": "2_0_3", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 12, "estimator/dropout_rate": 0.2821601869245385, "estimator/num_cells": 160, "estimator/num_layers": 2, "trainer/batch_size": 4, "trainer/learning_rate": 0.0037207472264278664, "trainer/weight_decay": 0.0009041399100555868, "TRIAL_BUDGET": 1}}',
     index: 0 } }
[2021-07-15 07:31:57] INFO (NNIManager) submitTrialJob: form: { sequenceId: 4,
  hyperParameters:
   { value:
      '{"parameter_id": "2_0_4", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 8, "estimator/dropout_rate": 0.05544362239418686, "estimator/num_cells": 320, "estimator/num_layers": 2, "trainer/batch_size": 16, "trainer/learning_rate": 0.000568484796327676, "trainer/weight_decay": 7.504033869326922e-05, "TRIAL_BUDGET": 1}}',
     index: 0 } }
[2021-07-15 07:31:57] INFO (NNIManager) submitTrialJob: form: { sequenceId: 5,
  hyperParameters:
   { value:
      '{"parameter_id": "2_0_5", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 4, "estimator/dropout_rate": 0.22339963520198922, "estimator/num_cells": 320, "estimator/num_layers": 3, "trainer/batch_size": 4, "trainer/learning_rate": 0.0019813197613154855, "trainer/weight_decay": 0.000716395501532327, "TRIAL_BUDGET": 1}}',
     index: 0 } }
[2021-07-15 07:32:02] INFO (NNIManager) Trial job gwk4h status changed from WAITING to RUNNING
[2021-07-15 07:32:03] INFO (NNIManager) Trial job BIah3 status changed from WAITING to RUNNING
[2021-07-15 07:32:03] INFO (NNIManager) Trial job RjwCl status changed from WAITING to RUNNING
[2021-07-15 07:32:03] INFO (NNIManager) Trial job MLLza status changed from WAITING to RUNNING
[2021-07-15 07:32:03] INFO (NNIManager) Trial job VHKoh status changed from WAITING to RUNNING
[2021-07-15 07:32:03] INFO (NNIManager) Trial job MjqG7 status changed from WAITING to RUNNING
[2021-07-15 07:32:23] INFO (NNIManager) Trial job gwk4h status changed from RUNNING to FAILED
[2021-07-15 07:32:23] INFO (NNIManager) Trial job RjwCl status changed from RUNNING to FAILED
[2021-07-15 07:32:23] INFO (NNIManager) Trial job MLLza status changed from RUNNING to FAILED
[2021-07-15 07:32:24] INFO (NNIManager) Trial job VHKoh status changed from RUNNING to FAILED
[2021-07-15 07:32:24] INFO (NNIManager) Trial job MjqG7 status changed from RUNNING to FAILED
[2021-07-15 07:32:24] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": "2_0_6", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 4, "estimator/dropout_rate": 0.2652263550904129, "estimator/num_cells": 40, "estimator/num_layers": 5, "trainer/batch_size": 16, "trainer/learning_rate": 0.009327937146318976, "trainer/weight_decay": 0.00025431446199396116, "TRIAL_BUDGET": 1}}
[2021-07-15 07:32:24] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": "2_0_7", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 4, "estimator/dropout_rate": 0.10735596997591788, "estimator/num_cells": 160, "estimator/num_layers": 4, "trainer/batch_size": 16, "trainer/learning_rate": 0.006925862608815797, "trainer/weight_decay": 0.000554726515038542, "TRIAL_BUDGET": 1}}
[2021-07-15 07:32:24] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": "2_0_8", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 4, "estimator/dropout_rate": 0.2465977626243625, "estimator/num_cells": 40, "estimator/num_layers": 5, "trainer/batch_size": 16, "trainer/learning_rate": 0.008247385164415689, "trainer/weight_decay": 9.643601462181257e-05, "TRIAL_BUDGET": 1}}
[2021-07-15 07:32:24] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:24] INFO (NNIManager) Change NNIManager status from: RUNNING to: TUNER_NO_MORE_TRIAL
[2021-07-15 07:32:24] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:24] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:24] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:29] INFO (NNIManager) submitTrialJob: form: { sequenceId: 6,
  hyperParameters:
   { value:
      '{"parameter_id": "2_0_6", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 4, "estimator/dropout_rate": 0.2652263550904129, "estimator/num_cells": 40, "estimator/num_layers": 5, "trainer/batch_size": 16, "trainer/learning_rate": 0.009327937146318976, "trainer/weight_decay": 0.00025431446199396116, "TRIAL_BUDGET": 1}}',
     index: 0 } }
[2021-07-15 07:32:29] INFO (NNIManager) submitTrialJob: form: { sequenceId: 7,
  hyperParameters:
   { value:
      '{"parameter_id": "2_0_7", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 4, "estimator/dropout_rate": 0.10735596997591788, "estimator/num_cells": 160, "estimator/num_layers": 4, "trainer/batch_size": 16, "trainer/learning_rate": 0.006925862608815797, "trainer/weight_decay": 0.000554726515038542, "TRIAL_BUDGET": 1}}',
     index: 0 } }
[2021-07-15 07:32:29] INFO (NNIManager) submitTrialJob: form: { sequenceId: 8,
  hyperParameters:
   { value:
      '{"parameter_id": "2_0_8", "parameter_source": "algorithm", "parameters": {"estimator/context_length": 4, "estimator/dropout_rate": 0.2465977626243625, "estimator/num_cells": 40, "estimator/num_layers": 5, "trainer/batch_size": 16, "trainer/learning_rate": 0.008247385164415689, "trainer/weight_decay": 9.643601462181257e-05, "TRIAL_BUDGET": 1}}',
     index: 0 } }
[2021-07-15 07:32:34] INFO (NNIManager) Trial job YvTH4 status changed from WAITING to RUNNING
[2021-07-15 07:32:34] INFO (NNIManager) Trial job m8SZF status changed from WAITING to RUNNING
[2021-07-15 07:32:35] INFO (NNIManager) Trial job RUiI4 status changed from WAITING to RUNNING
[2021-07-15 07:32:50] INFO (NNIManager) Trial job YvTH4 status changed from RUNNING to FAILED
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) Trial job m8SZF status changed from RUNNING to FAILED
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) Trial job RUiI4 status changed from RUNNING to FAILED
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:32:50] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:45:25] INFO (NNIManager) Trial job BIah3 status changed from RUNNING to SUCCEEDED
[2021-07-15 07:45:26] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:45:26] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:45:26] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:45:26] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:45:26] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:45:26] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": "-1_0_0", "parameter_source": "algorithm", "parameters": ""}
[2021-07-15 07:45:31] ERROR (NNIManager) Dispatcher error: This socket has been ended by the other party
[2021-07-15 07:45:31] ERROR (NNIManager) Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.dispatcher.onError (/usr/local/lib/python3.8/dist-packages/nni_node/core/nnimanager.js:584:32)
    at EventEmitter.emit (events.js:198:13)
    at Socket.IpcInterface.outgoingStream.on (/usr/local/lib/python3.8/dist-packages/nni_node/core/ipcInterface.js:42:72)
    at Socket.emit (events.js:198:13)
    at Socket.writeAfterFIN [as write] (net.js:399:8)
    at IpcInterface.sendCommand (/usr/local/lib/python3.8/dist-packages/nni_node/core/ipcInterface.js:49:38)
    at NNIManager.pingDispatcher (/usr/local/lib/python3.8/dist-packages/nni_node/core/nnimanager.js:428:29)
[2021-07-15 07:45:31] INFO (NNIManager) Change NNIManager status from: TUNER_NO_MORE_TRIAL to: ERROR
[2021-07-15 07:45:31] WARNING (IpcInterface) Commands jammed in buffer!
[2021-07-15 07:45:32] INFO (NNIManager) Change NNIManager status from: ERROR to: STOPPING
[2021-07-15 07:45:32] INFO (NNIManager) Stopping experiment, cleaning up ...
[2021-07-15 07:45:32] ERROR (NNIManager) Dispatcher error: This socket has been ended by the other party

 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by QuanluZhang** [comment]
@skeletondyh please help follow up on this issue, thanks

**Comment by mf-giwoong-lee** [comment]
It was some problem in my environment. It was solved
