### ISSUE TITLE
[Question] Is it possible to set shared directory as working directory?

### ISSUE THREAD

**Issue by mf-giwoong-lee** [microsoft/nni#3961]
**Describe the issue**:
I am trying to set shared directory as working directory now. But it is not working properly. 

I am launching nni with python code so I use 

```
experiment.config.experiment_working_directory = Path("<my shared directory>")
```

However, I got this message.

```
[2021-07-20 03:53:21] Creating experiment, Experiment ID: nag5wjzs
[2021-07-20 03:53:21] Starting web server...
[2021-07-20 03:53:22] Timeout, retry...
[2021-07-20 03:53:23] Setting up...
[2021-07-20 03:53:23] rest request POST http://localhost:8000/api/v1/nni/experiment failed: 500 {"error":"Datastore error: SQLITE_ERROR: no such table: ExperimentProfile"}
[2021-07-20 03:53:23] Create experiment failed
Traceback (most recent call last):
  File "nni_exp.py", line 39, in <module>
    nni_exp.run(port=8000)
  File "/usr/local/lib/python3.8/dist-packages/nni/experiment/experiment.py", line 163, in run
    self.start(port, debug)
  File "/usr/local/lib/python3.8/dist-packages/nni/experiment/experiment.py", line 117, in start
    self._proc = launcher.start_experiment(self.id, self.config, port, debug, mode=self.mode)
  File "/usr/local/lib/python3.8/dist-packages/nni/experiment/launcher.py", line 56, in start_experiment
    raise e
  File "/usr/local/lib/python3.8/dist-packages/nni/experiment/launcher.py", line 48, in start_experiment
    rest.post(port, '/experiment', config.json())
  File "/usr/local/lib/python3.8/dist-packages/nni/experiment/rest.py", line 29, in post
    return request('post', port, api, data)
  File "/usr/local/lib/python3.8/dist-packages/nni/experiment/rest.py", line 21, in request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8000/api/v1/nni/experiment
```

My shared folder is mounted by using CIFS. But nni supports shared_storage but only support for Azure and NFS not CIFS...

When the working directory is set to local directory, it is fine. 

Is there any solution for this problem?

**Environment**:
- NNI version: 2.3
- Training service (local|remote|pai|aml|etc): local
- Client OS: ubuntu 18.04
- Server OS (for remote mode only):
- Python version: 3.9
- PyTorch/TensorFlow version: PyTorch
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: yes

**Comment by acured** [comment]
Exclusion is a problem of folder permissions, could you have a try to set directory permission as "755" or "777"?

**Comment by mf-giwoong-lee** [comment]
Thank you for replying. This issue might be the problem between CIFS and sqlite. I heard that nni utilizes sqlite internally. But sqlite is not compatible to CIFS(with samba). So our team rebuild shared folder from CIFS to NFS.

Anyway, the shared folder has permission as "755" itself, but folders in shared folder has "555". It was working finely in our various projects.

samba setting was like this
```
browseable = no
security = user
writable = yes
create mask = 0555
directory mask = 0555
guset ok = no
valid users = root
```

**Comment by acured** [comment]
Cool, Thanks @mf-giwoong-lee.

**Comment by scarlett2018** [comment]
> Thank you for replying. This issue might be the problem between CIFS and sqlite. I heard that nni utilizes sqlite internally. But sqlite is not compatible to CIFS(with samba). So our team rebuild shared folder from CIFS to NFS.
> 
> Anyway, the shared folder has permission as "755" itself, but folders in shared folder has "555". It was working finely in our various projects.
> 
> samba setting was like this
> 
> ```
> browseable = no
> security = user
> writable = yes
> create mask = 0555
> directory mask = 0555
> guset ok = no
> valid users = root
> ```

closing the issue as the question had been addressed, thanks for using NNI and interact with us.
