### ISSUE TITLE
Trial log can't be created. Error "ENOENT"

### ISSUE THREAD

**Issue by LxzGordon** [microsoft/nni#3971]
**Describe the issue**: all trials status  remain waiting after starting the experiment.  The trial log is:  
{"error":"ENOENT: no such file or directory, open '/home/lxz/tnn/src/experiments/l1iRAqVW/trials/cdWrJ/trial.log'"}  

 I checked previous issues and change 'logDir' in my config to an absolute path, but it won't help. I also reinstalled nni via both pip and source code, but nothing happens.

**Environment**:
- NNI version: 2.2
- Training service (local|remote|pai|aml|etc): local
- Client OS: ubuntu 18.04 LTS
- Python version: 3.7.3
- PyTorch/TensorFlow version: Pytorch 1.8.1
- Is conda/virtualenv/venv used?: yes, I use the conda base environment
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):
authorName: lxz
experimentName: AE 
trialConcurrency: 4
maxExecDuration: 240h
maxTrialNum: 300
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
logDir:  /home/lxz/tnn/src/experiments
tuner:
  builtinTunerName: TPE
trial:
  command: python main.py --config=coma --env-config=sc2 with env_args.map_name=3m use_nni=True
  codeDir: .
  gpuNum: 4
localConfig:
  useActiveGpu: true
  maxTrialNumPerGpu: 30

**Comment by LxzGordon** [comment]
if I upgrade nni to 2.3, the experiment will fail.
Dispatcher log:
[2021-07-21 16:56:17] INFO (hyperopt.utils/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2021-07-21 16:56:17] INFO (hyperopt.fmin/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2021-07-21 16:56:17] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2021-07-21 16:56:17] ERROR (nni.runtime.msg_dispatcher_base/Thread-1) ufunc 'log' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Traceback (most recent call last):
  File "/home/lxz/anaconda3/lib/python3.7/site-packages/nni/runtime/msg_dispatcher_base.py", line 88, in command_queue_worker
    self.process_command(command, data)
  File "/home/lxz/anaconda3/lib/python3.7/site-packages/nni/runtime/msg_dispatcher_base.py", line 147, in process_command
    command_handlers[command](data)
  File "/home/lxz/anaconda3/lib/python3.7/site-packages/nni/runtime/msg_dispatcher.py", line 89, in handle_initialize
    self.tuner.update_search_space(data)
  File "/home/lxz/anaconda3/lib/python3.7/site-packages/nni/algorithms/hpo/hyperopt_tuner.py", line 251, in update_search_space
    search_space_instance = json2space(self.json)
  File "/home/lxz/anaconda3/lib/python3.7/site-packages/nni/algorithms/hpo/hyperopt_tuner.py", line 49, in json2space
    out_y[key] = json2space(in_x[key], name + '[%s]' % str(key))
  File "/home/lxz/anaconda3/lib/python3.7/site-packages/nni/algorithms/hpo/hyperopt_tuner.py", line 44, in json2space
    _value[:2] = np.log(_value[:2])
TypeError: ufunc 'log' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
[2021-07-21 16:56:21] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2021-07-21 16:56:23] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated

NNImanager log:
[2021-07-21 16:56:15] INFO (NNIDataStore) Datastore initialization done
[2021-07-21 16:56:15] INFO (RestServer) RestServer start
[2021-07-21 16:56:15] INFO (RestServer) RestServer base port is 8080
[2021-07-21 16:56:15] INFO (main) Rest server listening on: http://0.0.0.0:8080
[2021-07-21 16:56:16] INFO (NNIManager) Starting experiment: UcBr5Yi2
[2021-07-21 16:56:16] INFO (NNIManager) Setup training service...
[2021-07-21 16:56:16] INFO (LocalTrainingService) Construct local machine training service.
[2021-07-21 16:56:16] INFO (NNIManager) Setup tuner...
[2021-07-21 16:56:16] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-07-21 16:56:16] INFO (NNIManager) Add event listeners
[2021-07-21 16:56:16] INFO (LocalTrainingService) Run local machine training service.
[2021-07-21 16:56:16] WARNING (GPUScheduler) gpu_metrics file does not exist!
[2021-07-21 16:56:26] ERROR (NNIManager) Dispatcher error: This socket has been ended by the other party
[2021-07-21 16:56:26] ERROR (NNIManager) Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.dispatcher.onError (/home/lxz/anaconda3/lib/python3.7/site-packages/nni_node/core/nnimanager.js:584:32)
    at EventEmitter.emit (events.js:198:13)
    at Socket.IpcInterface.outgoingStream.on (/home/lxz/anaconda3/lib/python3.7/site-packages/nni_node/core/ipcInterface.js:42:72)
    at Socket.emit (events.js:198:13)
    at Socket.writeAfterFIN [as write] (net.js:399:8)
    at IpcInterface.sendCommand (/home/lxz/anaconda3/lib/python3.7/site-packages/nni_node/core/ipcInterface.js:49:38)
    at NNIManager.pingDispatcher (/home/lxz/anaconda3/lib/python3.7/site-packages/nni_node/core/nnimanager.js:428:29)
[2021-07-21 16:56:26] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR
[2021-07-21 16:56:26] WARNING (IpcInterface) Commands jammed in buffer!

**Comment by LxzGordon** [comment]
NNIManager.log:
[2021-07-21 16:59:20] INFO [ 'Datastore initialization done' ]
[2021-07-21 16:59:20] INFO [ 'RestServer start' ]
[2021-07-21 16:59:20] INFO [ 'RestServer base port is 8080' ]
[2021-07-21 16:59:20] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[2021-07-21 16:59:21] INFO [ 'Starting experiment: 5264Gn9I' ]
[2021-07-21 16:59:21] INFO [ 'Setup training service...' ]
[2021-07-21 16:59:21] INFO [ 'Construct local machine training service.' ]
[2021-07-21 16:59:21] INFO [ 'Setup tuner...' ]
[2021-07-21 16:59:21] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[2021-07-21 16:59:21] INFO [ 'Add event listeners' ]
[2021-07-21 16:59:21] INFO [ 'Run local machine training service.' ]
[2021-07-21 16:59:21] WARNING [ 'gpu_metrics file does not exist!' ]
[2021-07-21 16:59:21] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[2021-07-21 16:59:21] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"alpha": 0.00016584027493347326, "lr": 0.0022738867940594117}, "parameter_index": 0}' ]
[2021-07-21 16:59:21] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"alpha": 0.0048704415270307095, "lr": 0.00014715478646449095}, "parameter_index": 0}' ]
[2021-07-21 16:59:21] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 2, "parameter_source": "algorithm", "parameters": {"alpha": 0.03475257665652463, "lr": 0.003269542299519269}, "parameter_index": 0}' ]
[2021-07-21 16:59:21] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 3, "parameter_source": "algorithm", "parameters": {"alpha": 0.7974152013428317, "lr": 0.0016902245018139844}, "parameter_index": 0}' ]
[2021-07-21 16:59:26] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"alpha\\": 0.00016584027493347326, \\"lr\\": 0.0022738867940594117}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-07-21 16:59:26] INFO [ 'submitTrialJob: form: {"sequenceId":1,"hyperParameters":{"value":"{\\"parameter_id\\": 1, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"alpha\\": 0.0048704415270307095, \\"lr\\": 0.00014715478646449095}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-07-21 16:59:26] INFO [ 'submitTrialJob: form: {"sequenceId":2,"hyperParameters":{"value":"{\\"parameter_id\\": 2, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"alpha\\": 0.03475257665652463, \\"lr\\": 0.003269542299519269}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-07-21 16:59:26] INFO [ 'submitTrialJob: form: {"sequenceId":3,"hyperParameters":{"value":"{\\"parameter_id\\": 3, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"alpha\\": 0.7974152013428317, \\"lr\\": 0.0016902245018139844}, \\"parameter_index\\": 0}","index":0}}' ]
[2021-07-21 16:59:35] ERROR [ { Error: ENOENT: no such file or directory, open '/home/lxz/tnn/src/experiments/5264Gn9I/trials/AaM9O/trial.log'
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path:
     '/home/lxz/tnn/src/experiments/5264Gn9I/trials/AaM9O/trial.log' } ]

Dispatcher.log:
[2021-07-21 16:59:21] INFO (hyperopt.utils/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2021-07-21 16:59:21] INFO (hyperopt.fmin/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2021-07-21 16:59:21] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2021-07-21 16:59:21] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000368 seconds
[2021-07-21 16:59:21] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[2021-07-21 16:59:21] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000334 seconds
[2021-07-21 16:59:21] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[2021-07-21 16:59:21] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000336 seconds
[2021-07-21 16:59:21] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[2021-07-21 16:59:21] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000334 seconds
[2021-07-21 16:59:21] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials

**Comment by LxzGordon** [comment]
I copied the config file from a 4-GPU server to local computer with only 1 GPU. After changing the gpuNum in config, the problem is solved. I will close the issue.
