### ISSUE TITLE
Training service error: NNIManager version is 9, TrialKeeper version is 2.3, NNI version does not match!

### ISSUE THREAD

**Issue by kruthikakr** [microsoft/nni#4003]
**Describe the issue**:
I am running the mnist-pytorch example in the kubeflow mode ,following is the config file 

authorName: default
experimentName: example_dist_pytorch
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 1
#choice: local, remote, pai, kubeflow
trainingServicePlatform: kubeflow
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  codeDir: .
  master:
    replicas: 1
    command: python3 dist_mnist.py
    gpuNum: 0
    cpuNum: 1
    memoryMB: 4096
    image: tensorflow/tensorflow
  worker:
    replicas: 1
    command: python3 dist_mnist.py
    gpuNum: 0
    cpuNum: 1
    memoryMB: 4096
    image: mapler/pytorch-cpu:latest
kubeflowConfig:
  operator: pytorch-operator
  apiVersion: v1
  storage: azureStorage
  keyVault:
    vaultName: keyautoml
    name: ExamplePassword
  azureStorage:
    accountName: automlstore
    azureShare: myshare

nniManagerIp: 192.168.1.23

**Environment**:
- NNI version:999.dev0
- Training service (local|remote|pai|aml|etc):kubeflow
- Client OS: ubuntu 18.04
- Is running in Docker?: yes 

nni dispatcher status :  Training service error: NNIManager version is 9, TrialKeeper version is 2.3, NNI version does not match!
log files 

[2021-08-02 06:48:18] INFO (NNIDataStore) Datastore initialization done
[2021-08-02 06:48:18] INFO (RestServer) RestServer start
[2021-08-02 06:48:18] WARNING (NNITensorboardManager) Tensorboard may not installed, if you want to use tensorboard, please check if tensorboard installed.
[2021-08-02 06:48:18] INFO (RestServer) RestServer base port is 5080
[2021-08-02 06:48:18] INFO (main) Rest server listening on: http://0.0.0.0:5080
[2021-08-02 06:48:18] INFO (NNIManager) Setup training service...
[2021-08-02 06:48:19] INFO (KubernetesTrainingService) Construct Kubeflow training service.
[2021-08-02 06:48:20] INFO (NNIManager) Starting experiment: 1Cmxe5ng
[2021-08-02 06:48:20] INFO (NNIManager) Setup tuner...
[2021-08-02 06:48:20] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-08-02 06:48:20] INFO (NNIManager) Add event listeners
[2021-08-02 06:48:20] INFO (KubernetesTrainingService) Run Kubeflow training service.
[2021-08-02 06:48:20] INFO (RestServer) RestServer start
[2021-08-02 06:48:20] INFO (RestServer) RestServer base port is 5081
[2021-08-02 06:48:20] INFO (KubernetesTrainingService) Kubeflow Training service rest server listening on: http://0.0.0.0:5081
[2021-08-02 06:48:21] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2021-08-02 06:48:21] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"lr": 1e-06}, "parameter_index": 0}
[2021-08-02 06:48:25] INFO (NNIManager) submitTrialJob: form: { sequenceId: 0,
  hyperParameters:
   { value:
      '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"lr": 1e-06}, "parameter_index": 0}',
     index: 0 } }
[2021-08-02 06:48:25] INFO (KubernetesTrainingService) Construct Kubeflow training service.
[2021-08-02 06:50:20] INFO (NNIManager) Trial job O41cy status changed from WAITING to RUNNING
[2021-08-02 06:50:47] INFO (RestServer) POST: /version/1Cmxe5ng/O41cy: body: { tag: 'VCFail',
  msg:
   'NNIManager version is 9, TrialKeeper version is 2.3, NNI version does not match!' }
[2021-08-02 06:50:47] INFO (RestServer) POST: /stdout/1Cmxe5ng/O41cy: body: { tag: 'trial_keeper',
  stdOutputType: 'Stdout',
  msg:
   '[2021-08-02 06:50:47.303442] INFO Trial keeper spawns a subprocess (pid 24) to run command: [\'python3\', \'train.py\']' }
[2021-08-02 06:50:48] ERROR (NNIManager) Error: NNIManager version is 9, TrialKeeper version is 2.3, NNI version does not match!
    at KubeflowTrainingService.run (/media/sladmin/nlp_disk/Kruthika/nni/ts/nni_manager/dist/training_service/kubernetes/kubeflow/kubeflowTrainingService.js:49:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2021-08-02 06:50:48] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR
[2021-08-02 06:50:59] INFO (RestServer) POST: /stdout/1Cmxe5ng/O41cy: body: { tag: 'trial_keeper',
  stdOutputType: 'Stdout',
  msg:
   '[2021-08-02 06:50:59.380902] INFO subprocess terminated. Exit code is 1. Quit' }
[2021-08-02 06:50:59] INFO (RestServer) POST: /stdout/1Cmxe5ng/O41cy: body: { tag: 'trial_keeper',
  stdOutputType: 'Stdout',
  msg:
   '[2021-08-02 06:50:59.447080] INFO NNI trial keeper exit with code 1' }
[2021-08-02 06:52:00] INFO (RestServer) POST: /version/1Cmxe5ng/O41cy: body: { tag: 'VCFail',
  msg:
   'NNIManager version is 9, TrialKeeper version is 2.3, NNI version does not match!' }
[2021-08-02 06:52:01] INFO (RestServer) POST: /stdout/1Cmxe5ng/O41cy: body: { tag: 'trial_keeper',
  stdOutputType: 'Stdout',
  msg:

**Comment by kruthikakr** [comment]
@SparkSnail  any solution to this error ?  the nni dashboard  status will be error due to this ?

**Comment by SparkSnail** [comment]
@kruthikakr because you install NNI from source code in local machine. 
There are two ways to solve this:    
1.  Uninstall NNI firstly, and reinstall NNI v2.3.
2.  Set `versionCheck: false` in your config yaml file, refer https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/ExperimentConfig.rst#versioncheck

**Comment by kruthikakr** [comment]
Yes it is solved. Thank you
