### ISSUE TITLE
Experiment's status is INITIALIZED all the time

### ISSUE THREAD

**Issue by xyy1991** [microsoft/nni#4006]
**Describe the issue**:
The Experiment status is INITIALIZED all the time and can not be deleted by nnictl experiment delete exp_id,
The error log is :
INFO: This action will delete experiment fPRu2qQ6, and it's not recoverable.
INFO: do you want to continue?[y/N]:y
Traceback (most recent call last):
  File "/mnt/lustre/xyy/.local/bin/nnictl", line 10, in <module>
    sys.exit(parse_args())
  File "/mnt/lustre/xyy/xyy2/nni/nni/tools/nnictl/nnictl.py", line 272, in parse_args
    args.func(args)
  File "/mnt/lustre/xyy/xyy2/nni/nni/tools/nnictl/nnictl_utils.py", line 546, in experiment_clean
    platform = nni_config.get_config('experimentConfig').get('trainingServicePlatform')
AttributeError: 'NoneType' object has no attribute 'get'

**Environment**:
- NNI version:2.0
- Training service (local|remote|pai|aml|etc):
- Client OS:Red Hat 4.8.5-4
- Server OS (for remote mode only):
- Python version:3.6.8
- PyTorch/TensorFlow version:1.3
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by acured** [comment]
hi @xyy1991, could you provide more messages(Configuration, Log) about this? or describe how to reproduce this issue?

**Comment by xyy1991** [comment]
Hi, I follow the steps to install nni and try to test the installation by “nnictl create --config nni/examples/trials/mnist-pytorch/config.yml”.
I cannot get the right result unless I change the port number.
When I cannot start nni sucessfully, those experiments remains INITIALIZED and cannot be delete.
I try to run this experiment with slurm。

**Comment by acured** [comment]
Hi, Can you provide logs in "nni-experiments\<experiment-id>\log" in debug mode?

**Comment by xyy1991** [comment]
dispatcher.log
[2021-08-04 21:29:25] INFO (hyperopt.utils/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2021-08-04 21:29:26] INFO (hyperopt.fmin/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2021-08-04 21:29:26] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2021-08-04 21:29:26] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.002007 seconds
[2021-08-04 21:29:26] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[2021-08-04 21:30:17] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2021-08-04 21:30:19] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated

nnimanger.log:

[2021-08-04 21:28:54] INFO (NNIDataStore) Datastore initialization done
[2021-08-04 21:28:55] INFO (RestServer) RestServer start
[2021-08-04 21:28:57] INFO (RestServer) RestServer base port is 8012
[2021-08-04 21:28:57] INFO (main) Rest server listening on: http://0.0.0.0:8012
[2021-08-04 21:28:57] INFO (NNIManager) Starting experiment: r3aL1TS7
[2021-08-04 21:28:57] INFO (NNIManager) Setup training service...
[2021-08-04 21:28:58] INFO (LocalTrainingService) Construct local machine training service.
[2021-08-04 21:28:58] INFO (NNIManager) Setup tuner...
[2021-08-04 21:28:58] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-08-04 21:28:58] INFO (NNIManager) Add event listeners
[2021-08-04 21:28:58] INFO (LocalTrainingService) Run local machine training service.
[2021-08-04 21:28:59] WARNING (GPUScheduler) gpu_metrics file does not exist!
[2021-08-04 21:29:04] WARNING (GPUScheduler) gpu_metrics file does not exist!
[2021-08-04 21:29:09] WARNING (GPUScheduler) gpu_metrics file does not exist!
[2021-08-04 21:29:26] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2021-08-04 21:29:26] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"front_scale1": 3.5, "front_ratio1": 0.6, "front_ratio2": 1, "front_ratio3": 1.3}, "parameter_index": 0}
[2021-08-04 21:29:28] INFO (NNIManager) submitTrialJob: form: { sequenceId: 0,
  hyperParameters:
   { value:
      '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"front_scale1": 3.5, "front_ratio1": 0.6, "front_ratio2": 1, "front_ratio3": 1.3}, "parameter_index": 0}',
     index: 0 } } 
[2021-08-04 21:29:34] INFO (NNIManager) Trial job pEkRt status changed from WAITING to RUNNING
[2021-08-04 21:30:17] INFO (NNIManager) Change NNIManager status from: RUNNING to: STOPPING
[2021-08-04 21:30:17] INFO (NNIManager) Stopping experiment, cleaning up ... 
[2021-08-04 21:30:21] INFO (NNIManager) cancelTrialJob: pEkRt
[2021-08-04 21:30:22] INFO (LocalTrainingService) Stopping local machine training service...
[2021-08-04 21:30:23] INFO (NNIManager) Change NNIManager status from: STOPPING to: STOPPED
[2021-08-04 21:30:23] INFO (NNIManager) Experiment stopped.
[2021-08-04 21:30:23] INFO (NNITensorboardManager) Forced stopping all tensorboard task.
[2021-08-04 21:30:23] INFO (NNITensorboardManager) All tensorboard task stopped.
[2021-08-04 21:30:23] INFO (NNITensorboardManager) Tensorboard manager stopped.

**Comment by xyy1991** [comment]
This is the content of nnictl_stderr.log

-----------------------------------------------------------------------
                Experiment start time 2021-08-05 14:44:37
-----------------------------------------------------------------------
(node:50406) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at NNIManager.setStatus (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:700:77)
    at NNIManager.stopExperimentTopHalf (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:223:14)
    at NNIManager.stopExperiment (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:219:20)
    at process.cleanUp (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/main.js:117:38)
    at process.emit (events.js:203:15)
(node:50406) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:50406) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by acured** [comment]
Thanks your "nnictl_stderr.log", seems there was something wrong when start experiment, that cause experiment id was not generated(Cannot read property 'id' of undefined), Could you paste "nnimanager.log" here to show more information about the start of the experiment?

And, with "dispatcher.log" is better.

**Comment by xyy1991** [comment]
Hi, the content in nnimanager.log is shown below.
[2021-08-05 14:44:55] INFO (NNIDataStore) Datastore initialization done
[2021-08-05 14:44:57] INFO (RestServer) RestServer start
[2021-08-05 14:44:59] INFO (RestServer) RestServer base port is 8012
[2021-08-05 14:44:59] INFO (main) Rest server listening on: http://0.0.0.0:8012
[2021-08-05 14:44:59] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: STOPPING
[2021-08-05 15:03:56] INFO (NNIManager) Stopping experiment, cleaning up ... 
[2021-08-05 15:03:57] ERROR (NNIManager) Tuner has not been setup
[2021-08-05 15:03:57] ERROR (NNIManager) TypeError: Cannot read property 'listTrialJobs' of undefined
    at NNIManager.stopExperimentBottomHalf (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:244:61)
    at NNIManager.stopExperiment (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:220:20)
[2021-08-05 15:09:09] INFO (NNIManager) Stopping experiment, cleaning up ... 
[2021-08-05 15:09:09] ERROR (NNIManager) Tuner has not been setup
[2021-08-05 15:09:09] ERROR (NNIManager) TypeError: Cannot read property 'listTrialJobs' of undefined
    at NNIManager.stopExperimentBottomHalf (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:244:61)
    at NNIManager.stopExperiment (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:220:20)
[2021-08-05 15:14:49] INFO (NNIManager) Stopping experiment, cleaning up ... 
[2021-08-05 15:14:49] ERROR (NNIManager) Tuner has not been setup
[2021-08-05 15:14:49] ERROR (NNIManager) TypeError: Cannot read property 'listTrialJobs' of undefined
    at NNIManager.stopExperimentBottomHalf (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:244:61)
    at NNIManager.stopExperiment (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:220:20)
[2021-08-05 15:22:17] INFO (NNIManager) Stopping experiment, cleaning up ... 
[2021-08-05 15:22:17] ERROR (NNIManager) Tuner has not been setup
[2021-08-05 15:22:17] ERROR (NNIManager) TypeError: Cannot read property 'listTrialJobs' of undefined
    at NNIManager.stopExperimentBottomHalf (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:244:61)
    at NNIManager.stopExperiment (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:220:20)
[2021-08-05 15:25:07] INFO (NNIManager) Stopping experiment, cleaning up ... 
[2021-08-05 15:25:07] ERROR (NNIManager) Tuner has not been setup
[2021-08-05 15:25:07] ERROR (NNIManager) TypeError: Cannot read property 'listTrialJobs' of undefined
    at NNIManager.stopExperimentBottomHalf (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:244:61)
    at NNIManager.stopExperiment (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:220:20)
[2021-08-05 15:32:09] INFO (NNIManager) Stopping experiment, cleaning up ... 
[2021-08-05 15:32:09] ERROR (NNIManager) Tuner has not been setup
[2021-08-05 15:32:09] ERROR (NNIManager) TypeError: Cannot read property 'listTrialJobs' of undefined
    at NNIManager.stopExperimentBottomHalf (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:244:61)
    at NNIManager.stopExperiment (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:220:20)
[2021-08-05 15:48:09] INFO (NNIManager) Stopping experiment, cleaning up ... 
[2021-08-05 15:48:10] ERROR (NNIManager) Tuner has not been setup
[2021-08-05 15:48:10] ERROR (NNIManager) TypeError: Cannot read property 'listTrialJobs' of undefined
    at NNIManager.stopExperimentBottomHalf (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:244:61)
    at NNIManager.stopExperiment (/mnt/lustre/xyy/.conda/envs/nni_test/lib/python3.6/site-packages/nni_node/core/nnimanager.js:220:20)

**Comment by xyy1991** [comment]
Hi,I find resolution at https://nni.readthedocs.io/zh/stable/Tutorial/FAQ.html. I just kill the exp violently.

**Comment by acured** [comment]
Cool, so now you can start the experiment normally after you kill the existing experiment process?

**Comment by xyy1991** [comment]
Yes,I can now.Thanks!
