### ISSUE TITLE
Can't run config_search in spos

### ISSUE THREAD

**Issue by twmht** [microsoft/nni#4032]
**Describe the issue**:

**Environment**:
- NNI version: v2,3
- Training service (local|remote|pai|aml|etc): local
- Client OS: ubuntu18.04
- Server OS (for remote mode only):
- Python version:  3.7
- PyTorch/TensorFlow version: 1.8
- Is conda/virtualenv/venv used?: pyenv
- Is running in Docker?: no

I just follow the document of https://nni.readthedocs.io/en/latest/NAS/SPOS.html.

After training my custom dataset, and running

```bash
nnictl create --config config_search.yml
```

it would threw 

```
INFO:  expand searchSpacePath: nni_auto_gen_search_space.json to /home/shared/nfs/acer-share/bushido/third_party/nni/examples/nas/oneshot/spos/nni_auto_gen_search_space.json 
INFO:  expand codeDir: . to /home/shared/nfs/acer-share/bushido/third_party/nni/examples/nas/oneshot/spos/. 
INFO:  expand codeDir: . to /home/shared/nfs/acer-share/bushido/third_party/nni/examples/nas/oneshot/spos/. 
Traceback (most recent call last):
  File "/home/acer/.pyenv/versions/pytorch/bin/nnictl", line 33, in <module>
    sys.exit(load_entry_point('nni', 'console_scripts', 'nnictl')())
  File "/home/shared/nfs/acer-share/bushido/third_party/nni/nni/tools/nnictl/nnictl.py", line 278, in parse_args
    args.func(args)
  File "/home/shared/nfs/acer-share/bushido/third_party/nni/nni/tools/nnictl/launcher.py", line 515, in create_experiment
    config_v2 = convert.to_v2(config_yml).json()
  File "/home/shared/nfs/acer-share/bushido/third_party/nni/nni/experiment/config/common.py", line 121, in json
    obj = super().json()
  File "/home/shared/nfs/acer-share/bushido/third_party/nni/nni/experiment/config/base.py", line 85, in json
    self.validate()
  File "/home/shared/nfs/acer-share/bushido/third_party/nni/nni/experiment/config/common.py", line 118, in validate
    raise ValueError('Please set "use_active_gpu"')
ValueError: Please set "use_active_gpu"
```

**How to reproduce it?**:

```bash
nnictl create --config config_search.yml
```

**Comment by ultmaster** [comment]
You should follow the instruction and set `use_active_gpu`.

I don't think the SPOS example is still end-to-end runnable in v2.3. If you want to run it, I'm afraid you need to revert to v1.9.

**Comment by twmht** [comment]
how to set `use_active_gpu`?

**Comment by ultmaster** [comment]
Please see this tutorial: https://nni.readthedocs.io/en/stable/Tutorial/HowToLaunchFromPython.html

**Comment by twmht** [comment]
@ultmaster 

so spos example is not ready in v2.3?

**Comment by twmht** [comment]
@ultmaster 

I switch to v1.9. 


But got 

```
nnictl no such file or directory
```

after running

```
nnictl ss_gen -t "python tester.py"
```

**Comment by ultmaster** [comment]
Looks like an environment issue. Could you try in a brand new python environment?
