### ISSUE TITLE
self signed certificate OpenPAI V1.7.0

### ISSUE THREAD

**Issue by DC-y** [microsoft/nni#4056]
**Describe the issue**:
 Hi, I have deployed a PAI platform, when I used NNI to create a task, it always fails. [closed issue #3227](https://github.com/microsoft/nni/issues/3227) , I have make sure the PAI host is valid and available, set `https:// `format
 My config content is as follow:
```yaml
searchSpaceFile: search_space.json                                                                                                                                                                          
trialCommand: python3 mnist.py
trialGpuNumber: 1
trialConcurrency: 1
maxTrialNumber: 10
nniManagerIp: x.x.x.x
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  virtual_cluster: default
  platform: openpai
  host: https://*.*.*.*
  username: guest
  token: eyJhbGciOiJIxxxxxXBwbGljYXRpxxxxxxxxxxxTcGVjaWZpYyI6ZmFsxxxxxxxxxxxxiwiaWF0IjoxNjI4NDgwMDcwLCJleHAiOjE2MjkwODQ4NzB9.E1v_l2LCrtdH8zzqbJ1vcijb5dGgf23G3-Z8AwlP_xg
  dockerImage: nni:test
  trialCpuNumber: 11
  trialMemorySize: 31961MB
  storageConfigName: test-storage
  localStorageMountPoint: /data1
  containerStorageMountPoint: /mnt/test-storage
```

**Environment**: 
- NNI version: 2.3 
- Training service (local|remote|pai|aml|etc): pai  
- Client OS: ubuntu 18.04
- Server OS (for remote mode only): ubuntu 18.04
- Python version: 3.8
- PyTorch/TensorFlow version: 1.8
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:  
 ```sh
[2021-08-11 10:46:53] INFO (NNIDataStore) Datastore initialization done
[2021-08-11 10:46:53] INFO (RestServer) RestServer start
[2021-08-11 10:46:53] INFO (RestServer) RestServer base port is 1500
[2021-08-11 10:46:53] INFO (main) Rest server listening on: http://0.0.0.0:1500
[2021-08-11 10:46:54] INFO (NNIManager) Starting experiment: 9AMPRYqL
[2021-08-11 10:46:54] INFO (NNIManager) Setup training service...
[2021-08-11 10:46:54] INFO (TrialDispatcher) TrialDispatcher: GPU scheduler is enabled.
[2021-08-11 10:46:54] INFO (NNIManager) Setup tuner...
[2021-08-11 10:46:54] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-08-11 10:46:54] INFO (NNIManager) Add event listeners
[2021-08-11 10:46:54] INFO (TrialDispatcher) TrialDispatcher: started channel: WebCommandChannel
[2021-08-11 10:46:54] INFO (TrialDispatcher) TrialDispatcher: copying code and settings.
[2021-08-11 10:46:54] INFO (TrialDispatcher) Initialize environments total number: 0
[2021-08-11 10:46:54] INFO (TrialDispatcher) TrialDispatcher: run loop started.
[2021-08-11 10:46:54] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2021-08-11 10:46:54] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"batch_size": 64, "hidden_size": 256, "lr": 0.0001, "momentum": 0.6971409546760857}, "parameter_index": 0}
[2021-08-11 10:46:59] INFO (NNIManager) submitTrialJob: form: { sequenceId: 0,
  hyperParameters:
   { value:
      '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"batch_size": 64, "hidden_size": 256, "lr": 0.0001, "momentum": 0.6971409546760857}, "parameter_index": 0}',
     index: 0 } }
[2021-08-11 10:46:59] INFO (TrialDispatcher) Assign environment service pai to environment ysqgq
[2021-08-11 10:46:59] ERROR (OpenPaiEnvironmentService) self signed certificate
[2021-08-11 10:46:59] ERROR (NNIManager) Training service error: self signed certificate
    at Function.FromError (/data/automl/nni/ts/nni_manager/dist/common/errors.js:27:20)
    at Promise.all.trainingService.run.catch (/data/automl/nni/ts/nni_manager/dist/core/nnimanager.js:564:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2021-08-11 10:46:59] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR
 ```
 - dispatcher.log:
 ```sh
[2021-08-11 10:46:54] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2021-08-11 10:46:54] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001153 seconds
[2021-08-11 10:46:54] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
 ```
 - nnictl stdout and stderr:
 ```sh
{ Training service error: self signed certificate
    at Function.FromError (/data/automl/nni/ts/nni_manager/dist/common/errors.js:27:20)
    at Promise.all.trainingService.run.catch (/data/automl/nni/ts/nni_manager/dist/core/nnimanager.js:564:41)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: '', cause: undefined }

```
 

**How to reproduce it?**:
```sh
nnictl create --config openpai.yml --port 1500
```

**Comment by SparkSnail** [comment]
Could you submit job successfully to the host without NNI?

**Comment by SparkSnail** [comment]
NNI use your host directly to submit job, this is not NNI's issue, please make sure you set correct pai host in config file and your pai service is healthy.

**Comment by DC-y** [comment]
Hi, if I have confirmed that the  pai servece and pai host is OK,  is there another possible cause of this ERROR happened?

**Comment by SparkSnail** [comment]
If so, use `--debug` to start NNI and get more log information.

**Comment by DC-y** [comment]
Hi, after add `--debug` to start NNI, but I still don't understand what happened,  the log is as follow:

dispatcher.log:
```shell
[2021-08-18 15:10:29] DEBUG (nni.main/MainThread) START
[2021-08-18 15:10:29] DEBUG (nni.main/MainThread) decoded exp_params: [{"trialCommand":"python3 mnist.py","trialCodeDirectory":"/data/automl/t_24/nni/examples/trials/mnist-pytorch","trialConcurrency":1,"trialGpuNumber":1,"maxTrialNumber":10,"nniManagerIp":"x.x.x.x","useAnnotation":false,"debug":false,"experimentWorkingDirectory":"/home/xxxxxx/nni-experiments","tuner":{"name":"TPE","classArgs":{"optimize_mode":"maximize"}},"trainingService":{"platform":"openpai","host":"https://x.x.x.x","username":"xxxxxx","token":"exuxuxuxuxuxuxuxuxuxuxuxuuiddw8AnId24Nw-wd2vA3s","trialCpuNumber":11,"trialMemorySize":"31961MB","storageConfigName":"test-storage","dockerImage":"msranni/nni","virtualCluster":"default","localStorageMountPoint":"/data1","containerStorageMountPoint":"/mnt/test-storage","reuseMode":true}}]
[2021-08-18 15:10:29] DEBUG (nni.main/MainThread) exp_params json obj: [{
    "trialCommand": "python3 mnist.py",
    "trialCodeDirectory": "/data/automl/t_24/nni/examples/trials/mnist-pytorch",
    "trialConcurrency": 1,
    "trialGpuNumber": 1,
    "maxTrialNumber": 10,
    "nniManagerIp": "x.x.x.x",
    "useAnnotation": false,
    "debug": false,
    "experimentWorkingDirectory": "/home/xxxxxxxxx/nni-experiments",
    "tuner": {
        "name": "TPE",
        "classArgs": {
            "optimize_mode": "maximize"
        }
    },
    "trainingService": {
        "platform": "openpai",
        "host": "https://x.x.x.x",
        "username": "xxxxxx",
        "token": "eyJhbGciOiJIUxiuxuxuxuxuxuxuxuxuxuxuxuxuxuxuxuxwd2vA3s",
        "trialCpuNumber": 11,
        "trialMemorySize": "31961MB",
        "storageConfigName": "test-storage",
        "dockerImage": "msranni/nni",
        "virtualCluster": "default",
        "localStorageMountPoint": "/data1",
        "containerStorageMountPoint": "/mnt/test-storage",
        "reuseMode": true
    }
}]
[2021-08-18 15:10:29] DEBUG (nni.runtime.msg_dispatcher/MainThread) Assessor is not configured
[2021-08-18 15:10:29] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2021-08-18 15:10:29] DEBUG (nni.runtime.protocol/MainThread) Received command, header: [b'IN00000000000221']
[2021-08-18 15:10:29] DEBUG (nni.runtime.protocol/MainThread) Received command, data: [{"batch_size":{"_type":"choice","_value":[16,32,64,128]},"hidden_size":{"_type":"choice","_value":[128,256,512,1024]},"lr":{"_type":"choice","_value":[0.0001,0.001,0.01,0.1]},"momentum":{"_type":"uniform","_value":[0,1]}}]
[2021-08-18 15:10:29] DEBUG (nni.runtime.protocol/MainThread) Received command, header: [b'PI00000000000000']
[2021-08-18 15:10:29] DEBUG (nni.runtime.protocol/MainThread) Received command, data: []
[2021-08-18 15:10:29] DEBUG (nni.runtime.msg_dispatcher_base/Thread-1) process_command: command: [CommandType.Initialize], data: [OrderedDict([('batch_size', OrderedDict([('_type', 'choice'), ('_value', [16, 32, 64, 128])])), ('hidden_size', OrderedDict([('_type', 'choice'), ('_value', [128, 256, 512, 1024])])), ('lr', OrderedDict([('_type', 'choice'), ('_value', [0.0001, 0.001, 0.01, 0.1])])), ('momentum', OrderedDict([('_type', 'uniform'), ('_value', [0, 1])]))])]
[2021-08-18 15:10:29] DEBUG (nni.runtime.protocol/Thread-1) Sending command, data: [b'ID00000000000000']
[2021-08-18 15:10:29] DEBUG (nni.runtime.msg_dispatcher_base/Thread-1) process_command: command: [CommandType.Ping], data: []
[2021-08-18 15:10:29] DEBUG (nni.runtime.protocol/MainThread) Received command, header: [b'GE00000000000001']
[2021-08-18 15:10:29] DEBUG (nni.runtime.protocol/MainThread) Received command, data: [1]
[2021-08-18 15:10:29] DEBUG (nni.runtime.msg_dispatcher_base/Thread-1) process_command: command: [CommandType.RequestTrialJobs], data: [1]
[2021-08-18 15:10:29] DEBUG (nni.runtime.msg_dispatcher/Thread-1) requesting for generating params of [0]
[2021-08-18 15:10:29] DEBUG (nni.tuner/Thread-1) generating param for 0
[2021-08-18 15:10:29] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.001192 seconds
[2021-08-18 15:10:29] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[2021-08-18 15:10:29] DEBUG (nni.runtime.protocol/Thread-1) Sending command, data: [b'TR00000000000172{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"batch_size": 64, "hidden_size": 128, "lr": 0.1, "momentum": 0.17987396224122032}, "parameter_index": 0}']
[2021-08-18 15:10:34] DEBUG (nni.runtime.protocol/MainThread) Received command, header: [b'PI00000000000000']
[2021-08-18 15:10:34] DEBUG (nni.runtime.protocol/MainThread) Received command, data: []
[2021-08-18 15:10:34] DEBUG (nni.runtime.msg_dispatcher_base/Thread-1) process_command: command: [CommandType.Ping], data: []

```

nnimanager.log:
```shell
[2021-08-18 15:10:27] DEBUG (SqlDB) Database directory: /home/xxx/nni-experiments/OCTI9ZPM/db
[2021-08-18 15:10:27] INFO (NNIDataStore) Datastore initialization done
[2021-08-18 15:10:27] INFO (RestServer) RestServer start
[2021-08-18 15:10:28] INFO (RestServer) RestServer base port is 8080
[2021-08-18 15:10:28] INFO (main) Rest server listening on: http://0.0.0.0:8080
[2021-08-18 15:10:28] DEBUG (NNIRestHandler) GET: /check-status: body: {}
[2021-08-18 15:10:28] DEBUG (NNIRestHandler) POST: /experiment: body: {
  trialCommand: 'python3 mnist.py',
  trialCodeDirectory: '/data/automl/t_24/nni/examples/trials/mnist-pytorch',
  trialConcurrency: 1,
  trialGpuNumber: 1,
  maxTrialNumber: 10,
  nniManagerIp: 'x.x.x.x',
  useAnnotation: false,
  debug: false,
  experimentWorkingDirectory: '/home/xxxxx/nni-experiments',
  tuner: { name: 'TPE', classArgs: { optimize_mode: 'maximize' } },
  trainingService: {
    platform: 'openpai',
    host: 'https://x.x.x.x',
    username: 'xxxxxxx',
    token: 'eyJuxuxuxuxuxuxuxuxuxuxuuxxuxuxuxuxuxuxuxuxuA3s',
    trialCpuNumber: 11,
    trialMemorySize: '31961MB',
    storageConfigName: 'test-storage',
    dockerImage: 'msranni/nni',
    virtualCluster: 'default',
    localStorageMountPoint: '/data1',
    containerStorageMountPoint: '/mnt/test-storage',
    reuseMode: true
  },
  searchSpace: {
    batch_size: { _type: 'choice', _value: [Array] },
    hidden_size: { _type: 'choice', _value: [Array] },
    lr: { _type: 'choice', _value: [Array] },
    momentum: { _type: 'uniform', _value: [Array] }
  }
}
[2021-08-18 15:10:28] INFO (NNIManager) Starting experiment: OCTI9ZPM
[2021-08-18 15:10:28] INFO (NNIManager) Setup training service...
[2021-08-18 15:10:29] DEBUG (TrialDispatcher) current folder /home/xxxxxxxx/miniconda3/lib/python3.8/site-packages/nni_node/training_service/reusable
[2021-08-18 15:10:29] INFO (TrialDispatcher) TrialDispatcher: GPU scheduler is enabled.
[2021-08-18 15:10:29] DEBUG (StorageService) Initializing storage to local: /data1 remote: /data1/OCTI9ZPM
[2021-08-18 15:10:29] INFO (NNIManager) Setup tuner...
[2021-08-18 15:10:29] DEBUG (NNIManager) dispatcher command: python3 -m nni --exp_params eyJ0cmlhbxxxxxlc3Qtc3RvcmFnZSIsImRvY2tlckltYWdlIjoibXNyYW5uaS9ubmkiLCJ2aXJ0dWFsQ2x1c3RlciI6ImRlZmF1bHQiLCJsb2NhbFN0b3JhZ2VNb3VudFBvaW50IjoiL2RhdGExIiwiY29udGxxxxpbnQiOiIvbW50L3Rlc3Qtc3RvcmFnZSIsInJldXNlTW9kZSI6dHJ1ZX19
[2021-08-18 15:10:29] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-08-18 15:10:29] INFO (NNIManager) Add event listeners
[2021-08-18 15:10:29] DEBUG (NNIManager) Send tuner command: INITIALIZE: [object Object]
[2021-08-18 15:10:29] DEBUG (IpcInterface) ipcInterface command type: [IN], content:[{"batch_size":{"_type":"choice","_value":[16,32,64,128]},"hidden_size":{"_type":"choice","_value":[128,256,512,1024]},"lr":{"_type":"choice","_value":[0.0001,0.001,0.01,0.1]},"momentum":{"_type":"uniform","_value":[0,1]}}]
[2021-08-18 15:10:29] DEBUG (IpcInterface) ipcInterface command type: [PI], content:[]
[2021-08-18 15:10:29] INFO (TrialDispatcher) TrialDispatcher: started channel: WebCommandChannel
[2021-08-18 15:10:29] INFO (TrialDispatcher) TrialDispatcher: copying code and settings.
[2021-08-18 15:10:29] DEBUG (TrialDispatcher) TrialDispatcher: use existing storage service.
[2021-08-18 15:10:29] DEBUG (StorageService) copy localPath: /data/automl/t_24/nni/examples/trials/mnist-pytorch to remotePath: /data1/OCTI9ZPM/envs, asGzip true
[2021-08-18 15:10:29] DEBUG (StorageService) copying /tmp/nni_tmp_mnist-pytorch_t4HTy.tar.gz to /data1/OCTI9ZPM/envs, dir false, isFromRemote false, isToRemote: true
[2021-08-18 15:10:29] DEBUG (StorageService) rename remotePath: /data1/OCTI9ZPM/envs/mnist-pytorch.tar.gz to: nni-code.tar.gz
[2021-08-18 15:10:29] DEBUG (StorageService) saving content to remotePath: /data1/OCTI9ZPM/envs/install_nni.sh, length: 177, isAttach: false
[2021-08-18 15:10:29] DEBUG (StorageService) copying /tmp/temp_Vwld_install_nni.sh to /data1/OCTI9ZPM/envs, dir false, isFromRemote false, isToRemote: true
[2021-08-18 15:10:29] DEBUG (StorageService) rename remotePath: /data1/OCTI9ZPM/envs/temp_Vwld_install_nni.sh to: install_nni.sh
[2021-08-18 15:10:29] DEBUG (StorageService) saving content to remotePath: /data1/OCTI9ZPM/envs/install_nni.ps1, length: 103, isAttach: false
[2021-08-18 15:10:29] DEBUG (StorageService) copying /tmp/temp_PCtk_install_nni.ps1 to /data1/OCTI9ZPM/envs, dir false, isFromRemote false, isToRemote: true
[2021-08-18 15:10:29] DEBUG (StorageService) rename remotePath: /data1/OCTI9ZPM/envs/temp_PCtk_install_nni.ps1 to: install_nni.ps1
[2021-08-18 15:10:29] DEBUG (StorageService) saving content to remotePath: /data1/OCTI9ZPM/envs/settings.json, length: 225, isAttach: false
[2021-08-18 15:10:29] DEBUG (StorageService) copying /tmp/temp_ZtPR_settings.json to /data1/OCTI9ZPM/envs, dir false, isFromRemote false, isToRemote: true
[2021-08-18 15:10:29] DEBUG (StorageService) rename remotePath: /data1/OCTI9ZPM/envs/temp_ZtPR_settings.json to: settings.json
[2021-08-18 15:10:29] INFO (TrialDispatcher) Initialize environments total number: 0
[2021-08-18 15:10:29] INFO (TrialDispatcher) TrialDispatcher: run loop started.
[2021-08-18 15:10:29] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2021-08-18 15:10:29] DEBUG (IpcInterface) ipcInterface command type: [GE], content:[1]
[2021-08-18 15:10:29] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"batch_size": 64, "hidden_size": 128, "lr": 0.1, "momentum": 0.17987396224122032}, "parameter_index": 0}
[2021-08-18 15:10:34] DEBUG (IpcInterface) ipcInterface command type: [PI], content:[]
[2021-08-18 15:10:34] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 0,
  hyperParameters: {
    value: '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"batch_size": 64, "hidden_size": 128, "lr": 0.1, "momentum": 0.17987396224122032}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2021-08-18 15:10:34] DEBUG (TrialDispatcher) TrialDispatcher: no live environment, so request one.
[2021-08-18 15:10:34] INFO (TrialDispatcher) Assign environment service pai to environment n6ZQo
[2021-08-18 15:10:34] DEBUG (OpenPaiEnvironmentService) generated paiJobConfig: protocolVersion: 2
name: nni_exp_OCTI9ZPM_env_n6ZQo
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: msranni/nni
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
      minSucceededInstances: -1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 11
      memoryMB: 31961
    commands:
      - >-
        cd /mnt/test-storage/OCTI9ZPM && mkdir -p envs/n6ZQo && cd envs/n6ZQo &&
        sh ../install_nni.sh && python3 -m nni.tools.trial_tool.trial_runner
extras:
  storages:
    - name: test-storage
  submitFrom: submit-job-v2
defaults:
  virtualCluster: default

[2021-08-18 15:10:34] ERROR (OpenPaiEnvironmentService) self signed certificate
[2021-08-18 15:10:34] ERROR (NNIManager) Training service error: self signed certificate
    at Function.FromError (/home/xxxxx/miniconda3/lib/python3.8/site-packages/nni_node/common/errors.js:29:20)
    at /home/xxxxxx/miniconda3/lib/python3.8/site-packages/nni_node/core/nnimanager.js:609:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 2)
    at async NNIManager.run (/home/xxxxxxxxx/miniconda3/lib/python3.8/site-packages/nni_node/core/nnimanager.js:603:9)
[2021-08-18 15:10:34] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR
[2021-08-18 15:10:34] DEBUG (NNIRestHandler) GET: /experiment-metadata: body: {}
[2021-08-18 15:10:34] DEBUG (NNIRestHandler) GET: /experiment: body: {}
[2021-08-18 15:10:34] DEBUG (NNIRestHandler) GET: /trial-jobs: body: {}
[2021-08-18 15:10:34] DEBUG (NNIRestHandler) GET: /metric-data: body: {}
[2021-08-18 15:10:34] DEBUG (NNIDataStore) getTrialJobsByReplayEvents begin
[2021-08-18 15:10:34] DEBUG (NNIDataStore) getTrialJobsByReplayEvents done
[2021-08-18 15:10:34] DEBUG (NNIRestHandler) GET: /check-status: body: {}
[2021-08-18 15:10:34] DEBUG (NNIRestHandler) GET: /trial-jobs: body: {}
[2021-08-18 15:10:34] DEBUG (NNIRestHandler) GET: /metric-data: body: {}
[2021-08-18 15:10:34] DEBUG (NNIDataStore) getTrialJobsByReplayEvents begin
[2021-08-18 15:10:34] DEBUG (NNIDataStore) getTrialJobsByReplayEvents done
[2021-08-18 15:10:34] DEBUG (NNIRestHandler) GET: /version: body: {}
[2021-08-18 15:10:35] DEBUG (NNIRestHandler) GET: /experiment: body: {}
[2021-08-18 15:10:35] DEBUG (NNIRestHandler) GET: /trial-jobs: body: {}
[2021-08-18 15:10:35] DEBUG (NNIRestHandler) GET: /metric-data: body: {}
[2021-08-18 15:10:35] DEBUG (NNIDataStore) getTrialJobsByReplayEvents begin
[2021-08-18 15:10:35] DEBUG (NNIDataStore) getTrialJobsByReplayEvents done
[2021-08-18 15:10:35] DEBUG (NNIRestHandler) GET: /experiment-metadata: body: {}
[2021-08-18 15:10:35] DEBUG (NNIRestHandler) GET: /check-status: body: {}

```

**Comment by SparkSnail** [comment]
You have a certificate which is self-signed, so it's non-trusted and will be rejected by nodejs request client by default.
Two ways to solve this: 
1. Install the certificate as a trusted server. If it's signed by a non-trusted CA, you'll have to install that CA's certificate as well.
2. set `rejectUnauthorized: false` in NNI's request source code, and build NNI from source code by yourself.

**Comment by DC-y** [comment]
@SparkSnail ,   Thanks your feedback, I will try it soon

**Comment by DC-y** [comment]
Set enviroment
`export NODE_TLS_REJECT_UNAUTHORIZED='0'`
Then install NNI from source work for me
`python setup.py develop`
