### ISSUE TITLE
Job management error: 404 page not found 

### ISSUE THREAD

**Issue by kruthikakr** [microsoft/nni#4156]
Hi i am facing issue , please guide me
**Describe the issue*

authorName: default
experimentName: example_dist_pytorch
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 1
trainingServicePlatform: kubeflow
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
trial:
  codeDir: .
  master:
    replicas: 1
    command: python3 dist_mnist.py
    gpuNum: 0
    cpuNum: 1
    memoryMB: 4096
    image: tensorflow/tensorflow
  worker:
    replicas: 1
    command: python3 dist_mnist.py
    gpuNum: 0
    cpuNum: 1
    memoryMB: 4096
    image: mapler/pytorch-cpu:latest
kubeflowConfig:
  operator: pytorch-operator
  apiVersion: v1
  storage: 
  keyVault:
    vaultName: 
    name: 
  azureStorage:
    accountName: 
    azureShare: 

NNI Log

[2021-09-06 09:57:09] INFO (NNIDataStore) Datastore initialization done
[2021-09-06 09:57:09] INFO (RestServer) RestServer start
[2021-09-06 09:57:09] INFO (RestServer) RestServer base port is 5000
[2021-09-06 09:57:09] INFO (main) Rest server listening on: http://0.0.0.0:5000
[2021-09-06 09:57:09] INFO (NNIManager) Setup training service...
[2021-09-06 09:57:10] INFO (KubernetesTrainingService) Construct Kubeflow training service.
[2021-09-06 09:57:12] INFO (NNIManager) Starting experiment: u1MHS9zi
[2021-09-06 09:57:12] INFO (NNIManager) Setup tuner...
[2021-09-06 09:57:12] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-09-06 09:57:12] INFO (NNIManager) Add event listeners
[2021-09-06 09:57:12] INFO (KubernetesTrainingService) Run Kubeflow training service.
[2021-09-06 09:57:12] INFO (RestServer) RestServer start
[2021-09-06 09:57:12] INFO (RestServer) RestServer base port is 5001
[2021-09-06 09:57:12] INFO (KubernetesTrainingService) Kubeflow Training service rest server listening on: http://0.0.0.0:5001
[2021-09-06 09:57:13] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2021-09-06 09:57:13] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"batch_size": 32, "hidden_size": 128, "lr": 0.0001}, "parameter_index": 0}
[2021-09-06 09:57:17] INFO (NNIManager) submitTrialJob: form: { sequenceId: 0,
  hyperParameters:
   { value:
      '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"batch_size": 32, "hidden_size": 128, "lr": 0.0001}, "parameter_index": 0}',
     index: 0 } }
[2021-09-06 09:57:17] INFO (KubernetesTrainingService) Construct Kubeflow training service.
[2021-09-06 09:57:20] ERROR (NNIManager) Error: 404 page not found

    at _request (/media/sladmin/nlp_disk/Kruthika/nni/venv/lib/python3.6/site-packages/nni_node/node_modules/kubernetes-client/lib/backends/request.js:189:25)
    at Request.request [as _callback] (/media/sladmin/nlp_disk/Kruthika/nni/venv/lib/python3.6/site-packages/nni_node/node_modules/kubernetes-client/lib/backends/request.js:148:14)
    at Request.self.callback (/media/sladmin/nlp_disk/Kruthika/nni/venv/lib/python3.6/site-packages/nni_node/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/media/sladmin/nlp_disk/Kruthika/nni/venv/lib/python3.6/site-packages/nni_node/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/media/sladmin/nlp_disk/Kruthika/nni/venv/lib/python3.6/site-packages/nni_node/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
[2021-09-06 09:57:20] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR

**Comment by kruthikakr** [comment]
Yes this is solved. thank you for the help.

**Comment by juniroc** [comment]
what was the problem? I got a same problem
