### ISSUE TITLE
assert len(set(num_channels_list)) == 1

### ISSUE THREAD

**Issue by jxncyym** [microsoft/nni#4160]
**Describe the issue**:
Traceback (most recent call last):
  File "/algdata02/yiming.yu/DDRNet.pytorch_pruner/tools/pruner_nni_L1filter.py", line 142, in <module>
    main()
  File "/algdata02/yiming.yu/DDRNet.pytorch_pruner/tools/pruner_nni_L1filter.py", line 130, in main
    m_speedup.speedup_model()
  File "/algdata02/yiming.yu/DDRNet.pytorch_pruner/envp_3/lib/python3.6/site-packages/nni/compression/pytorch/speedup/compressor.py", line 500, in speedup_model
    fix_mask_conflict(self.masks, self.bound_model, self.dummy_input)
  File "/algdata02/yiming.yu/DDRNet.pytorch_pruner/envp_3/lib/python3.6/site-packages/nni/compression/pytorch/utils/mask_conflict.py", line 50, in fix_mask_conflict
    masks = fix_channel_mask.fix_mask()
  File "/algdata02/yiming.yu/DDRNet.pytorch_pruner/envp_3/lib/python3.6/site-packages/nni/compression/pytorch/utils/mask_conflict.py", line 259, in fix_mask
    assert len(set(num_channels_list)) == 1
AssertionError

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:3.6
- PyTorch/TensorFlow version:pytorch 1.7.1
- Is conda/virtualenv/venv used?:virtualenv
- Is running in Docker?:no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by flyingmrwang** [comment]
the same for speedup pruned ghostnet, and the num channels are 16 and 1

**Comment by J-shang** [comment]
Hi @jxncyym @flyingmrwang ,
If possible, could you provide the model and pruning code for our reproduction?

**Comment by jxncyym** [comment]
the trained model :
https://pan.baidu.com/s/1l0bifkq6Z6Zs6rRXu7cNJw，    0nk0

code:
`import argparse
import os
import pprint
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.backends.cudnn as cudnn
import random
import _init_paths
import models
from models import ddrnet_23_slim as ddr_23_slim
from config import config
from config import update_config
import numpy as np
from utils.utils import create_logger

from nni.compression.pytorch.utils.counter import count_flops_params
import nni
from nni.compression.pytorch import ModelSpeedup
from nni.algorithms.compression.pytorch.pruning import L1FilterPruner, L2FilterPruner, LevelPruner

# os.environ['CUDA_VISIBLE_DEVICE']="2,3"

class onnx_net(nn.Module):
    def __init__(self, model):
        super(onnx_net, self).__init__()
        self.backone = model

    def forward(self, x):
        x1, x2 = self.backone(x)
        print(x1.shape)
        y = F.interpolate(x1, size=(960,1280), mode='bilinear')
        # y = F.softmax(y, dim=1)
        # y = torch.argmax(y, dim=1)

        return y

def parse_args():
    parser = argparse.ArgumentParser(description='Train segmentation network')
    
    parser.add_argument('--cfg',
                        help='experiment configure file name',
                        default="experiments/cityscapes/ddrnet23_slim.yaml",
                        type=str)
    parser.add_argument('opts',
                        help="Modify config options using the command-line",
                        default=None,
                        nargs=argparse.REMAINDER)

    args = parser.parse_args()
    update_config(config, args)

    return args


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    args = parse_args()

    logger, final_output_dir, _ = create_logger(
        config, args.cfg, 'test')
    final_output_dir = "/algdata02/yiming.yu/DDRNet.pytorch_pruner/output23_slim_model"

    logger.info(pprint.pformat(args))
    logger.info(pprint.pformat(config))

    # cudnn related setting
    cudnn.benchmark = config.CUDNN.BENCHMARK
    cudnn.deterministic = config.CUDNN.DETERMINISTIC
    cudnn.enabled = config.CUDNN.ENABLED

    # build model
    if torch.__version__.startswith('1'):
        module = eval('models.'+config.MODEL.NAME)
        module.BatchNorm2d_class = module.BatchNorm2d = torch.nn.BatchNorm2d
    model = eval('models.'+config.MODEL.NAME +
                 '.get_seg_model')(config)

    if config.TEST.MODEL_FILE:
        model_state_file = config.TEST.MODEL_FILE
    else:
        model_state_file = os.path.join(final_output_dir, 'best_20200903.pth')   
        # model_state_file = os.path.join(final_output_dir, 'final_state.pth')        
    logger.info('=> loading model from {}'.format(model_state_file))
        
    pretrained_dict = torch.load(model_state_file)
    if 'state_dict' in pretrained_dict:
        pretrained_dict = pretrained_dict['state_dict']
    model_dict = model.state_dict()
    pretrained_dict = {k[6:]: v for k, v in pretrained_dict.items()
                        if k[6:] in model_dict.keys()}
    for k, _ in pretrained_dict.items():
        logger.info(
            '=> loading {} from pretrained model'.format(k))
    model_dict.update(pretrained_dict)
    model.load_state_dict(model_dict)
    # model = onnx_net(model)
    # model.eval()
    # model.to(device)

    # params = sum([np.prod(p.size()) for p in model.parameters()])
    # print("Number of Parameters before pruner: %.1fM"%(params/1e6))
    dummy_input = torch.randn([3, 3, 512, 512]).to(device)
    flops, params, _ = count_flops_params(model, dummy_input)
    print(f"FLOPs: {flops}, params: {params/1e6}M")

    print("start pruning ......")
    model.to(device)
    config_list = [{ 'sparsity': 0.7, 'op_types': ['Conv2d'] }]
    # config_list = [{ 'sparsity': 0.8, 'op_types': ['default'] }]
    # pruner = L1FilterPruner(model, config_list, dependency_aware=True, dummy_input=dummy_input)
    pruner = L1FilterPruner(model, config_list)
    # pruner = L2FilterPruner(model, config_list)
    # pruner = LevelPruner(model, config_list)
    model = pruner.compress()
    pruner.get_pruned_weights()

    # export the pruned model masks for model speedup
    model_path = "/algdata02/yiming.yu/DDRNet.pytorch_pruner/nni_model/pruned_model_20210906.pth"
    mask_path = "/algdata02/yiming.yu/DDRNet.pytorch_pruner/nni_model/mask_model_20210906.pth"
    pruner.export_model(model_path=model_path, mask_path=mask_path)
    # print(model)

    pruner._unwrap_model()
    # print(model)

    # model = eval('models.'+config.MODEL.NAME +
    #              '.get_seg_model')(config)
    # model.to(device)
    # model.load_state_dict(torch.load(model_path))
    # masks_file = os.path.join(args.experiment_data_dir, 'mask.pth')          
    m_speedup = ModelSpeedup(model, dummy_input, mask_path, device)
    m_speedup.speedup_model()

    # print(model)

    params = sum([np.prod(p.size()) for p in model.parameters()])
    print("Number of Parameters after pruner: %.1fM"%(params/1e6))
    torch.save(model.state_dict(), '/algdata02/yiming.yu/DDRNet.pytorch_pruner/pruner_model/model_prunered_conv_0.8_20210903.pth')
    


if __name__ == '__main__':
    main()`
@J-shang

**Comment by jxncyym** [comment]
@ J-shang  the latest code refer to :https://pan.baidu.com/s/19xoJOC9yaD3E6-RkZkOf9Q，g4og

**Comment by J-shang** [comment]
This dependency set leads to error, but from the model structure, it seems that they should not be in the same group.

{'spp.scale2.3': 128, 'spp.scale4.3': 128, 'spp.scale0.2': 128, 'layer5.0.conv3': 512, 'spp.process1.2': 128, 'layer5.0.downsample.0': 512, 'spp.process2.2': 128, 'spp.scale1.3': 128, 'spp.scale3.3': 128, 'spp.process3.2': 128}

line 174 in ddrnet_23_slim.py
`out = self.compression(torch.cat(x_list, 1)) + self.shortcut(x)`

Seems the dependency is related to this line.

@zheng-ningxin please help to look into this issue.

**Comment by jxncyym** [comment]
Is there any progress @zheng-ningxin @J-shang

**Comment by zheng-ningxin** [comment]
The `size` operation on the graph misleads the model topology analysis.
![image](https://user-images.githubusercontent.com/49771382/133862794-2b265de2-14a8-4a50-b100-966547193599.png)

**Comment by jxncyym** [comment]
then how to solve this problem？@zheng-ningxin

**Comment by zheng-ningxin** [comment]
I'll submit a PR to fix this ASAP. I'll let you know when this pr merged. Thanks!

**Comment by vinhtq115** [comment]
> I'll submit a PR to fix this ASAP. I'll let you know when this pr merged. Thanks!

Have you been able to fix this? I have the same issue with [YOLOv5-Face](https://github.com/deepcam-cn/yolov5-face) yolov5n-0.5 model.

**Comment by HappyPeanuts** [comment]
I have meet the same problem:'assert len(set(num_channels_list)) == 1' when i try to prune my model DLASeg, i want to know how to resove it~  thanks a lot

**Comment by HappyPeanuts** [comment]
> I'll submit a PR to fix this ASAP. I'll let you know when this pr merged. Thanks!

Hi, have you resolved this problem? I have meet the same error and  I guess it was caused by the use of DCNv2. I want to now how to resolve this problem.  Thanks ~

**Comment by zheng-ningxin** [comment]
@HappyPeanuts Sincerely sorry for the late PR, already working on this pr and need some time. Thanks~

**Comment by HappyPeanuts** [comment]
thank you for your reply，I will try other methods，if convenient ，please notice me when you resolved this problem&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Ningxin Zheng ***@***.***&gt;
Date: Mon,Feb 28,2022 4:49 PM
To: microsoft/nni ***@***.***&gt;
Cc: 杨志伟 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [microsoft/nni] assert len(set(num_channels_list)) == 1 (#4160)





 
@HappyPeanuts Sincerely sorry for the late PR, already working on this pr and need some time. Thanks~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HK017** [comment]
@zheng-ningxin,hello, What does this code `assert len(set(num_channels_list)) == 1` mean for me to examine my own model structure? thanks

**Comment by dianxin556** [comment]
I also meet the same problem , so how to solve it?

**Comment by dreamlychina** [comment]
I also meet the same problem , so how to solve it?

**Comment by J-shang** [comment]
hello @dianxin556 @dreamlychina , could you show your model for us to reproduce your issue? This problem is highly related to the model structure.
