### ISSUE TITLE
Error while training in Kubeflow mode 

### ISSUE THREAD

**Issue by kruthikakr** [microsoft/nni#4166]
**Describe the issue**:
I am trying to train model for HPO , with 80 GB of data . It takes around 2 hrs to generate the log file , till then the trial status will be running .  But after some time it gave the error in the nni log . 
The same experiment works in the local. I am getting error in the kubeflow mode .

Can the azure kubernetes  and nni can  handle 80GB of data ?

Config file : 
authorName: default
experimentName: example_dist_pytorch
​
trialConcurrency: 1
maxTrialNum: 1
#choice: local, remote, pai, kubeflow
trainingServicePlatform: kubeflow
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  codeDir: .
  master:
    replicas: 1
    command : pip install pycocotools && pip install scikit-image && python3 train.py
    gpuNum: 1
    cpuNum: 1
    memoryMB: 24000
    image: msranni/nni:latest
versionCheck: false
kubeflowConfig:
  operator: pytorch-operator
  apiVersion: v1
  storage: 
  keyVault:
    vaultName: 
    name: key
  azureStorage:
    accountName: 
    azureShare: 
​
nniManagerIp: 40.124.46.4

[2021-09-09 10:41:17] INFO (NNIDataStore) Datastore initialization done
[2021-09-09 10:41:17] INFO (RestServer) RestServer start
[2021-09-09 10:41:17] INFO (RestServer) RestServer base port is 5000
[2021-09-09 10:41:17] INFO (main) Rest server listening on: http://0.0.0.0:5000
[2021-09-09 10:41:18] INFO (NNIManager) Setup training service...
[2021-09-09 10:41:20] INFO (KubernetesTrainingService) Construct Kubeflow training service.
[2021-09-09 10:41:24] INFO (NNIManager) Starting experiment: 18NfRHjG
[2021-09-09 10:41:24] INFO (NNIManager) Setup tuner...
[2021-09-09 10:41:24] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-09-09 10:41:24] INFO (NNIManager) Add event listeners
[2021-09-09 10:41:24] INFO (KubernetesTrainingService) Run Kubeflow training service.
[2021-09-09 10:41:24] INFO (RestServer) RestServer start
[2021-09-09 10:41:24] INFO (RestServer) RestServer base port is 5001
[2021-09-09 10:41:24] INFO (KubernetesTrainingService) Kubeflow Training service rest server listening on: http://0.0.0.0:5001
[2021-09-09 10:41:25] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2021-09-09 10:41:25] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"LEARNING_RATE": 1e-06}, "parameter_index": 0}
[2021-09-09 10:41:29] INFO (NNIManager) submitTrialJob: form: { sequenceId: 0,
  hyperParameters:
   { value:
      '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"LEARNING_RATE": 1e-06}, "parameter_index": 0}',
     index: 0 } }
[2021-09-09 10:41:29] INFO (KubernetesTrainingService) Construct Kubeflow training service.
[2021-09-09 10:41:29] INFO (NNIManager) Change NNIManager status from: RUNNING to: STOPPING
[2021-09-09 10:41:29] INFO (NNIManager) Stopping experiment, cleaning up ...
[2021-09-09 10:41:32] ERROR (KubernetesTrainingService) Unmount /home/sladmin/nni-experiments/18NfRHjG/trials-nfs-tmp failed, error is ChildProcessError: Command failed: sudo umount /home/sladmin/nni-experiments/18NfRHjG/trials-nfs-tmp
umount: /home/sladmin/nni-experiments/18NfRHjG/trials-nfs-tmp: no mount point specified.
 `sudo umount /home/sladmin/nni-experiments/18NfRHjG/trials-nfs-tmp` (exited with error code 32)
[2021-09-09 10:41:32] INFO (KubernetesTrainingService) Kubernetes Training service rest server stopped successfully.
[2021-09-09 10:41:32] INFO (RestServer) Rest server stopped.
[2021-09-09 10:41:32] INFO (NNIManager) Change NNIManager status from: STOPPING to: STOPPED
[2021-09-09 10:41:32] INFO (NNIManager) Experiment stopped.
[2021-09-09 10:41:32] INFO (NNITensorboardManager) Forced stopping all tensorboard task.
[2021-09-09 10:41:32] INFO (NNITensorboardManager) All tensorboard task stopped.
[2021-09-09 10:41:32] INFO (NNITensorboardManager) Tensorboard manager stopped.
[2021-09-09 11:01:30] INFO (NNIDataStore) Datastore initialization done
[2021-09-09 11:01:30] INFO (RestServer) RestServer start
[2021-09-09 11:01:30] INFO (RestServer) RestServer base port is 5000
[2021-09-09 11:01:30] INFO (main) Rest server listening on: http://0.0.0.0:5000
[2021-09-09 11:01:30] INFO (NNIManager) Setup training service...
[2021-09-09 11:01:31] INFO (KubernetesTrainingService) Construct Kubeflow training service.
[2021-09-09 11:01:34] INFO (NNIManager) Resuming experiment: 18NfRHjG
[2021-09-09 11:01:34] INFO (NNIManager) Setup tuner...
[2021-09-09 11:01:34] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-09-09 11:01:34] INFO (NNIManager) Add event listeners
[2021-09-09 11:01:34] INFO (KubernetesTrainingService) Run Kubeflow training service.
[2021-09-09 11:01:34] INFO (RestServer) RestServer start
[2021-09-09 11:01:34] INFO (RestServer) RestServer base port is 5001
[2021-09-09 11:01:34] INFO (KubernetesTrainingService) Kubeflow Training service rest server listening on: http://0.0.0.0:5001
[2021-09-09 11:01:35] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2021-09-09 11:01:35] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"LEARNING_RATE": 1e-06}, "parameter_index": 0}
[2021-09-09 11:01:39] INFO (NNIManager) submitTrialJob: form: { sequenceId: 1,
  hyperParameters:
   { value:
      '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"LEARNING_RATE": 1e-06}, "parameter_index": 0}',
     index: 0 } }
[2021-09-09 11:01:39] INFO (KubernetesTrainingService) Construct Kubeflow training service.
[2021-09-09 11:01:52] INFO (NNIManager) Trial job dNmr7 status changed from WAITING to RUNNING
[2021-09-09 11:01:52] INFO (NNIManager) Change NNIManager status from: RUNNING to: NO_MORE_TRIAL
[2021-09-09 12:26:54] INFO (RestServer) POST: /stdout/18NfRHjG/dNmr7: body: { tag: 'trial_keeper',
  stdOutputType: 'Stdout',
  msg:
   '[2021-09-09 12:26:54.036104] INFO Trial keeper spawns a subprocess (pid 24) to run command: [\'pip\', \'install\', \'pycocotools\', \'&&\', \'pip\', \'install\', \'scikit-image\', \'&&\', \'pip\', \'install\', \'tensorboard\', \'&&\', \'python3\', \'train.py\']' }
[2021-09-09 12:35:46] INFO (NNIManager) Change NNIManager status from: NO_MORE_TRIAL to: STOPPING
[2021-09-09 12:35:46] INFO (NNIManager) Stopping experiment, cleaning up ...
[2021-09-09 12:35:46] ERROR (NNIManager) Dispatcher error: write EPIPE
[2021-09-09 12:35:46] ERROR (NNIManager) Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.dispatcher.onError (/media/sladmin/nlp_disk/Kruthika/nni/venv/lib/python3.6/site-packages/nni_node/core/nnimanager.js:584:32)
    at EventEmitter.emit (events.js:198:13)
    at Socket.IpcInterface.outgoingStream.on (/media/sladmin/nlp_disk/Kruthika/nni/venv/lib/python3.6/site-packages/nni_node/core/ipcInterface.js:42:72)
    at Socket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:614:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
[2021-09-09 12:35:46] INFO (NNIManager) Change NNIManager status from: STOPPING to: ERROR
[2021-09-09 12:43:48] INFO (NNIDataStore) Datastore initialization done
[2021-09-09 12:43:48] INFO (RestServer) RestServer start
[2021-09-09 12:43:48] INFO (RestServer) RestServer base port is 5000
[2021-09-09 12:43:48] INFO (main) Rest server listening on: http://0.0.0.0:5000
[2021-09-09 12:43:49] INFO (NNIManager) Setup training service...
[2021-09-09 12:43:57] INFO (KubernetesTrainingService) Construct Kubeflow training service.
[2021-09-09 12:44:01] INFO (NNIManager) Resuming experiment: 18NfRHjG
[2021-09-09 12:44:01] INFO (NNIManager) Setup tuner...
[2021-09-09 12:44:01] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-09-09 12:44:01] INFO (NNIManager) Add event listeners
[2021-09-09 12:44:01] INFO (KubernetesTrainingService) Run Kubeflow training service.
[2021-09-09 12:44:01] INFO (RestServer) RestServer start
[2021-09-09 12:44:01] INFO (RestServer) RestServer base port is 5001
[2021-09-09 12:44:01] INFO (NNIManager) Change NNIManager status from: RUNNING to: NO_MORE_TRIAL
[2021-09-09 12:44:01] INFO (NNIManager) Change NNIManager status from: NO_MORE_TRIAL to: DONE
[2021-09-09 12:44:01] INFO (KubernetesTrainingService) Kubeflow Training service rest server listening on: http://0.0.0.0:5001
[2021-09-09 12:44:01] INFO (NNIManager) Experiment done.
[2021-09-09 12:44:02] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2021-09-09 12:44:02] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"LEARNING_RATE": 1e-06}, "parameter_index": 0}
[2021-09-09 12:44:52] INFO (NNIManager) Change NNIManager status from: DONE to: RUNNING
[2021-09-09 12:44:52] INFO (NNIManager) submitTrialJob: form: { sequenceId: 2,
  hyperParameters:
   { value:
      '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"LEARNING_RATE": 1e-06}, "parameter_index": 0}',
     index: 0 } }
[2021-09-09 12:44:52] INFO (KubernetesTrainingService) Construct Kubeflow training service.
[2021-09-09 12:44:58] INFO (NNIManager) Change NNIManager status from: RUNNING to: NO_MORE_TRIAL
[2021-09-09 12:54:23] INFO (NNIManager) Trial job QaZGQ status changed from WAITING to RUNNING
[2021-09-09 13:03:48] INFO (RestServer) POST: /stdout/18NfRHjG/dNmr7: body: { tag: 'trial',
  stdOutputType: 'Stdout',
  msg:
   'NNISDK_MEb\'{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 0, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}\'' }
[2021-09-09 13:03:48] WARNING (NNIManager) NNIManager received non-existent trial job metrics: { id: 'dNmr7',
  data:
   '{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 0, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}' }
[2021-09-09 13:03:54] INFO (RestServer) POST: /stdout/18NfRHjG/dNmr7: body: { tag: 'trial',
  stdOutputType: 'Stdout',
  msg:
   'NNISDK_MEb\'{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 1, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}\'' }
[2021-09-09 13:03:54] WARNING (NNIManager) NNIManager received non-existent trial job metrics: { id: 'dNmr7',
  data:
   '{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 1, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}' }
[2021-09-09 13:04:03] INFO (RestServer) POST: /stdout/18NfRHjG/dNmr7: body: { tag: 'trial',
  stdOutputType: 'Stdout',
  msg:
   'NNISDK_MEb\'{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 2, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}\'' }
[2021-09-09 13:04:03] WARNING (NNIManager) NNIManager received non-existent trial job metrics: { id: 'dNmr7',
  data:
   '{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 2, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}' }
[2021-09-09 13:04:25] INFO (RestServer) POST: /stdout/18NfRHjG/dNmr7: body: { tag: 'trial',
  stdOutputType: 'Stdout',
  msg:
   'NNISDK_MEb\'{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 3, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}\'' }
[2021-09-09 13:04:25] WARNING (NNIManager) NNIManager received non-existent trial job metrics: { id: 'dNmr7',
  data:
   '{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 3, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}' }
[2021-09-09 13:04:29] INFO (RestServer) POST: /stdout/18NfRHjG/dNmr7: body: { tag: 'trial',
  stdOutputType: 'Stdout',
  msg:
   'NNISDK_MEb\'{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 4, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}\'' }
[2021-09-09 13:04:29] WARNING (NNIManager) NNIManager received non-existent trial job metrics: { id: 'dNmr7',
  data:
   '{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 4, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}' }
[2021-09-09 13:04:55] INFO (RestServer) POST: /stdout/18NfRHjG/dNmr7: body: { tag: 'trial',
  stdOutputType: 'Stdout',
  msg:
   'NNISDK_MEb\'{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 5, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}\'' }
[2021-09-09 13:04:55] WARNING (NNIManager) NNIManager received non-existent trial job metrics: { id: 'dNmr7',
  data:
   '{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 5, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}' }
[2021-09-09 13:05:05] INFO (RestServer) POST: /stdout/18NfRHjG/dNmr7: body: { tag: 'trial',
  stdOutputType: 'Stdout',
  msg:
   'NNISDK_MEb\'{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 6, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}\'' }
[2021-09-09 13:05:05] WARNING (NNIManager) NNIManager received non-existent trial job metrics: { id: 'dNmr7',
  data:
   '{"parameter_id": 0, "trial_job_id": "dNmr7", "type": "PERIODICAL", "sequence": 6, "value": "{\\"__instance_type__\\": [\\"torch\\", \\"Tensor\\"], \\"attributes\\": {}}"}' }
[2021-09-09 13:06:12] INFO (RestServer) POST: /stdout/18NfRHjG/dNmr7: body: { tag: 'trial_keeper',
  stdOutputType: 'Stdout',
  msg:
   '[2021-09-09 13:06:12.461010] INFO subprocess terminated. Exit code is 1. Quit' }
[2021-09-09 13:06:12] INFO (RestServer) POST: /stdout/18NfRHjG/dNmr7: body: { tag: 'trial_keeper',
  stdOutputType: 'Stdout',
  msg:
   '[2021-09-09 13:06:12.580091] INFO NNI trial keeper exit with code 1' }

**Comment by acured** [comment]
Hi @kruthikakr, Azure kubernetes and nni can not handle 80GB of data...

**Comment by kruthikakr** [comment]
Thank you for response.
