### ISSUE TITLE
nni/examples/nas/multi-trial/mnasnet/search.py  cannot use gpu!

### ISSUE THREAD

**Issue by GeorgeW9527** [microsoft/nni#4207]
**Describe the issue**:
1.  nni/examples/nas/multi-trial/mnasnet/search.py  cannot use gpu!
2.  we can see gpu in the dispatcher's log, but not in trails's log
3.  if I only use pytorch_lightning and don't use nni to train a model, it works

**Environment**:
- NNI version:2.4
- Training service (local|remote|pai|aml|etc):local
- Client OS:ubuntu
- Server OS (for remote mode only):
- Python version:3.7
- PyTorch/TensorFlow version: pytorch1.9 
- Is conda/virtualenv/venv used?:conda
- Is running in Docker?:no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 **- dispatcher.log:**
```
[2021-09-23 12:19:34] INFO (nni.experiment/MainThread) Creating experiment, Experiment ID: [36mcgwd2hea[0m
[2021-09-23 12:19:34] INFO (nni.experiment/MainThread) Connecting IPC pipe...
[2021-09-23 12:19:35] INFO (nni.experiment/MainThread) Starting web server...
[2021-09-23 12:19:36] INFO (nni.experiment/MainThread) Setting up...
[2021-09-23 12:19:36] INFO (nni.runtime.msg_dispatcher_base/Thread-3) Dispatcher started
[2021-09-23 12:19:36] INFO (nni.retiarii.experiment.pytorch/MainThread) Web UI URLs: [36mhttp://127.0.0.1:8097 http://169.254.232.130:8097 http://10.38.232.130:8097[0m
[2021-09-23 12:19:36] INFO (nni.retiarii.experiment.pytorch/MainThread) Start strategy...
[2021-09-23 12:19:36] INFO (nni.retiarii.strategy.tpe_strategy/MainThread) TPE strategy has been started.
[2021-09-23 12:19:36] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002666 seconds
[2021-09-23 12:19:36] INFO (hyperopt.tpe/MainThread) TPE using 0 trials
[2021-09-23 12:19:36] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002566 seconds
[2021-09-23 12:19:36] INFO (hyperopt.tpe/MainThread) TPE using 0 trials
[2021-09-23 12:19:51] INFO (pytorch_lightning.utilities.distributed/Thread-2) GPU available: True, used: True
[2021-09-23 12:19:51] INFO (pytorch_lightning.utilities.distributed/Thread-2) TPU available: False, using: 0 TPU cores
[2021-09-23 12:19:51] INFO (pytorch_lightning.utilities.distributed/Thread-2) IPU available: False, using: 0 IPUs
[2021-09-23 12:19:52] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.008633 seconds
[2021-09-23 12:19:52] INFO (hyperopt.tpe/MainThread) TPE using 0 trials
[2021-09-23 12:19:52] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002604 seconds
[2021-09-23 12:19:52] INFO (hyperopt.tpe/MainThread) TPE using 0 trials
[2021-09-23 12:19:53] INFO (pytorch_lightning.utilities.distributed/Thread-2) GPU available: True, used: True
[2021-09-23 12:19:53] INFO (pytorch_lightning.utilities.distributed/Thread-2) TPU available: False, using: 0 TPU cores
[2021-09-23 12:19:53] INFO (pytorch_lightning.utilities.distributed/Thread-2) IPU available: False, using: 0 IPUs
[2021-09-23 12:20:06] INFO (pytorch_lightning.utilities.distributed/Thread-2) GPU available: True, used: True
[2021-09-23 12:20:06] INFO (pytorch_lightning.utilities.distributed/Thread-2) TPU available: False, using: 0 TPU cores
[2021-09-23 12:20:06] INFO (pytorch_lightning.utilities.distributed/Thread-2) IPU available: False, using: 0 IPUs
[2021-09-23 12:20:08] INFO (pytorch_lightning.utilities.distributed/Thread-2) GPU available: True, used: True
[2021-09-23 12:20:08] INFO (pytorch_lightning.utilities.distributed/Thread-2) TPU available: False, using: 0 TPU cores
[2021-09-23 12:20:08] INFO (pytorch_lightning.utilities.distributed/Thread-2) IPU available: False, using: 0 IPUs
[2021-09-23 12:20:08] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.005866 seconds
[2021-09-23 12:20:08] INFO (hyperopt.tpe/MainThread) TPE using 0 trials
[2021-09-23 12:20:08] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002999 seconds
[2021-09-23 12:20:08] INFO (hyperopt.tpe/MainThread) TPE using 0 trials
[2021-09-23 12:20:21] INFO (pytorch_lightning.utilities.distributed/Thread-2) GPU available: True, used: True
[2021-09-23 12:20:21] INFO (pytorch_lightning.utilities.distributed/Thread-2) TPU available: False, using: 0 TPU cores
[2021-09-23 12:20:21] INFO (pytorch_lightning.utilities.distributed/Thread-2) IPU available: False, using: 0 IPUs
[2021-09-23 12:20:22] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.009218 seconds
[2021-09-23 12:20:22] INFO (hyperopt.tpe/MainThread) TPE using 0 trials
[2021-09-23 12:20:22] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002645 seconds
[2021-09-23 12:20:22] INFO (hyperopt.tpe/MainThread) TPE using 0 trials
[2021-09-23 12:20:23] INFO (pytorch_lightning.utilities.distributed/Thread-2) GPU available: True, used: True
[2021-09-23 12:20:23] INFO (pytorch_lightning.utilities.distributed/Thread-2) TPU available: False, using: 0 TPU cores
[2021-09-23 12:20:23] INFO (pytorch_lightning.utilities.distributed/Thread-2) IPU available: False, using: 0 IPUs
[2021-09-23 12:20:36] INFO (pytorch_lightning.utilities.distributed/Thread-2) GPU available: True, used: True
[2021-09-23 12:20:36] INFO (pytorch_lightning.utilities.distributed/Thread-2) TPU available: False, using: 0 TPU cores
[2021-09-23 12:20:36] INFO (pytorch_lightning.utilities.distributed/Thread-2) IPU available: False, using: 0 IPUs
[2021-09-23 12:20:38] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.111468 seconds
[2021-09-23 12:20:38] INFO (hyperopt.tpe/MainThread) TPE using 0 trials
[2021-09-23 12:20:38] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002632 seconds
[2021-09-23 12:20:38] INFO (hyperopt.tpe/MainThread) TPE using 0 trials
[2021-09-23 12:20:38] INFO (pytorch_lightning.utilities.distributed/Thread-2) GPU available: True, used: True
[2021-09-23 12:20:38] INFO (pytorch_lightning.utilities.distributed/Thread-2) TPU available: False, using: 0 TPU cores
[2021-09-23 12:20:38] INFO (pytorch_lightning.utilities.distributed/Thread-2) IPU available: False, using: 0 IPUs
[2021-09-23 12:20:51] INFO (pytorch_lightning.utilities.distributed/Thread-2) GPU available: True, used: True
[2021-09-23 12:20:51] INFO (pytorch_lightning.utilities.distributed/Thread-2) TPU available: False, using: 0 TPU cores
[2021-09-23 12:20:51] INFO (pytorch_lightning.utilities.distributed/Thread-2) IPU available: False, using: 0 IPUs
[2021-09-23 12:20:53] INFO (pytorch_lightning.utilities.distributed/Thread-2) GPU available: True, used: True
[2021-09-23 12:20:53] INFO (pytorch_lightning.utilities.distributed/Thread-2) TPU available: False, using: 0 TPU cores
[2021-09-23 12:20:53] INFO (pytorch_lightning.utilities.distributed/Thread-2) IPU available: False, using: 0 IPUs
[2021-09-23 12:20:56] INFO (nni.retiarii.experiment.pytorch/Thread-4) Stopping experiment, please wait...
[2021-09-23 12:20:56] INFO (nni.retiarii.experiment.pytorch/MainThread) Strategy exit
[2021-09-23 12:20:56] INFO (nni.retiarii.experiment.pytorch/MainThread) Waiting for experiment to become DONE (you can ctrl+c if there is no running trial jobs)...
```
 **- nnictl stdout and stderr:**
```
/opt/conda/envs/pytorch1.9/lib/python3.7/site-packages/deprecate/deprecation.py:115: LightningDeprecationWarning: The `Accuracy` was deprecated since v1.3.0 in favor of `torchmetrics.classification.accuracy.Accuracy`. It will be removed in v1.5.0.
  stream(template_mgs % msg_args)
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/notebook/code/personal/gzh/compression_toolkit/nni_v24/nni/nni/retiarii/trial_entry.py", line 28, in <module>
    engine.trial_execute_graph()
  File "/home/notebook/code/personal/gzh/compression_toolkit/nni_v24/nni/nni/retiarii/execution/base.py", line 121, in trial_execute_graph
    graph_data = BaseGraphData.load(receive_trial_parameters())
  File "/home/notebook/code/personal/gzh/compression_toolkit/nni_v24/nni/nni/retiarii/integration_api.py", line 44, in receive_trial_parameters
    params = json_loads(json.dumps(params))
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/site-packages/json_tricks/nonp.py", line 236, in loads
    return json_loads(string, object_pairs_hook=hook, **jsonkwargs)
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/site-packages/json_tricks/decoders.py", line 44, in __call__
    map = hook(map, properties=self.properties)
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/site-packages/json_tricks/utils.py", line 66, in wrapper
    return encoder(*args, **{k: v for k, v in kwargs.items() if k in names})
  File "/home/notebook/code/personal/gzh/compression_toolkit/nni_v24/nni/nni/retiarii/serializer.py", line 46, in _serialize_class_instance_decode
    return import_(obj['__type__'])(**obj['arguments'])
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 40, in insert_env_defaults
    return fn(self, **kwargs)
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 346, in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1253, in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/site-packages/pytorch_lightning/utilities/device_parser.py", line 91, in parse_gpu_ids
    return _sanitize_gpu_ids(gpus)
  File "/opt/conda/envs/pytorch1.9/lib/python3.7/site-packages/pytorch_lightning/utilities/device_parser.py", line 170, in _sanitize_gpu_ids
    f"You requested GPUs: {gpus}\n But your machine only has: {all_available_gpus}"
pytorch_lightning.utilities.exceptions.MisconfigurationException:  You requested GPUs: [0]
 But your machine only has: []
```
 

**How to reproduce it?**:
use the following code to replace the original, i add the " gpus=1" and "exp_config.training_service.use_active_gpu = True"
 
```
import os
import sys
import torch
from pathlib import Path
import nni.retiarii.nn.pytorch as nn
import nni.retiarii.evaluator.pytorch.lightning as pl
from nni.retiarii import serialize
from base_mnasnet import MNASNet
from nni.retiarii.nn.pytorch import LayerChoice
from nni.retiarii.experiment.pytorch import RetiariiExperiment, RetiariiExeConfig
from nni.retiarii.strategy import TPEStrategy
from torchvision import transforms
from torchvision.datasets import CIFAR10
from mutator import BlockMutator

if __name__ == '__main__':
    _DEFAULT_DEPTHS = [16, 24, 40, 80, 96, 192, 320]
    _DEFAULT_CONVOPS = ["dconv", "mconv", "mconv", "mconv", "mconv", "mconv", "mconv"]
    _DEFAULT_SKIPS = [False, True, True, True, True, True, True]
    _DEFAULT_KERNEL_SIZES = [3, 3, 5, 5, 3, 5, 3]
    _DEFAULT_NUM_LAYERS = [1, 3, 3, 3, 2, 4, 1]

    base_model = MNASNet(0.5, _DEFAULT_DEPTHS, _DEFAULT_CONVOPS, _DEFAULT_KERNEL_SIZES,
                         _DEFAULT_NUM_LAYERS, _DEFAULT_SKIPS)

    train_transform = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
    ])
    valid_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
    ])
    data_root = "/home/notebook/code/personal/gzh/compression_toolkit/nni_new/nni/examples/nas/oneshot/enas/data"
    train_dataset = serialize(CIFAR10, root=data_root, train=True, download=True, transform=train_transform)
    test_dataset = serialize(CIFAR10, root=data_root, train=False, download=True, transform=valid_transform)
    trainer = pl.Classification(train_dataloader=pl.DataLoader(train_dataset, batch_size=100),
                                val_dataloaders=pl.DataLoader(test_dataset, batch_size=100),
                                max_epochs=1, limit_train_batches=0.2, gpus=1)
    applied_mutators = [
        BlockMutator('mutable_0'),
        BlockMutator('mutable_1')
    ]

    simple_strategy = TPEStrategy()

    exp = RetiariiExperiment(base_model, trainer, applied_mutators, simple_strategy)

    exp_config = RetiariiExeConfig('local')
    exp_config.experiment_name = 'mnasnet_search'
    exp_config.trial_concurrency = 2
    exp_config.max_trial_number = 10
    exp_config.training_service.use_active_gpu = True
    exp_config.execution_engine = 'base'

    exp.run(exp_config, 8097)
    print('Exported models:')
    for model in exp.export_top_models(formatter='dict'):
        print(model)


```

**Comment by ultmaster** [comment]
Could you try to set `trial_gpu_number`?

**Comment by GeorgeW9527** [comment]
> Could you try to set `trial_gpu_number`?

sorry, it's my mistake. 
if I add 'trial_gpu_number', it works!
