### ISSUE TITLE
Multi-trial NAS on custom dataset and model with tuple input

### ISSUE THREAD

**Issue by ding3820** [microsoft/nni#4237]
**Describe the issue**:
Hi,
I've tried to follow the instruction from [here](https://github.com/microsoft/nni/blob/9a4d0d67506f5e1197238344fed858305fbb4494/examples/notebooks/Retiarii_example_multi-trial_NAS.ipynb) with my custom dataset and model. The base model and dataset work well in regular training/testing way and also the NNI's one-shot Darts [trainer](https://github.com/microsoft/nni/blob/9a4d0d67506f5e1197238344fed858305fbb4494/examples/notebooks/Retiarii_example_one-shot_NAS.ipynb). Since one-shot NAS does not support **ValueChoice** so I turn to multi-trial NAS. From the documentation, I found a debugging function ```evaluator._execute(model)``` which works fine for my model and dataset. but after I execute ```exp.run()```, I got some error message showing that there's some problem in the tuple input. Here's the complete message:

```---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_16172/4265677498.py in <module>
----> 1 exp.run(exp_config, 8118)
      2 print('Final model:')
      3 for model_code in exp.export_top_models(formatter=export_formatter):
      4     print(model_code)

~/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/experiment/pytorch.py in run(self, config, port, debug)
    287             assert config is not None, 'You are using classic search mode, config cannot be None!'
    288             self.config = config
--> 289             self.start(port, debug)
    290 
    291     def _check_exp_status(self) -> bool:

~/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/experiment/pytorch.py in start(self, port, debug)
    258         exp_status_checker = Thread(target=self._check_exp_status)
    259         exp_status_checker.start()
--> 260         self._start_strategy()
    261         # TODO: the experiment should be completed, when strategy exits and there is no running job
    262         _logger.info('Waiting for experiment to become DONE (you can ctrl+c if there is no running trial jobs)...')

~/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/experiment/pytorch.py in _start_strategy(self)
    188         base_model_ir, self.applied_mutators = preprocess_model(
    189             self.base_model, self.trainer, self.applied_mutators, full_ir=self.config.execution_engine != 'py',
--> 190             dummy_input=self.config.dummy_input)
    191 
    192         _logger.info('Start strategy...')

~/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/experiment/pytorch.py in preprocess_model(base_model, trainer, applied_mutators, full_ir, dummy_input)
    122         except Exception as e:
    123             _logger.error('Your base model cannot be parsed by torch.jit.script, please fix the following error:')
--> 124             raise e
    125         if dummy_input is not None:
    126             # FIXME: this is a workaround as full tensor is not supported in configs

~/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/experiment/pytorch.py in preprocess_model(base_model, trainer, applied_mutators, full_ir, dummy_input)
    119     if full_ir:
    120         try:
--> 121             script_module = torch.jit.script(base_model)
    122         except Exception as e:
    123             _logger.error('Your base model cannot be parsed by torch.jit.script, please fix the following error:')

~/anaconda3/envs/nni/lib/python3.7/site-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb)
   1095         obj = call_prepare_scriptable_func(obj)
   1096         return torch.jit._recursive.create_script_module(
-> 1097             obj, torch.jit._recursive.infer_methods_to_compile
   1098         )
   1099 

~/anaconda3/envs/nni/lib/python3.7/site-packages/torch/jit/_recursive.py in create_script_module(nn_module, stubs_fn, share_types)
    410     concrete_type = get_module_concrete_type(nn_module, share_types)
    411     AttributeTypeIsSupportedChecker().check(nn_module)
--> 412     return create_script_module_impl(nn_module, concrete_type, stubs_fn)
    413 
    414 def create_script_module_impl(nn_module, concrete_type, stubs_fn):

~/anaconda3/envs/nni/lib/python3.7/site-packages/torch/jit/_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
    476     # Compile methods if necessary
    477     if concrete_type not in concrete_type_store.methods_compiled:
--> 478         create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    479         # Create hooks after methods to ensure no name collisions between hooks and methods.
    480         # If done before, hooks can overshadow methods that aren't exported.

~/anaconda3/envs/nni/lib/python3.7/site-packages/torch/jit/_recursive.py in create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    353     property_rcbs = [p.resolution_callback for p in property_stubs]
    354 
--> 355     concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
    356 
    357 def create_hooks_from_stubs(concrete_type, hook_stubs, pre_hook_stubs):

RuntimeError: 
Tensor (inferred) cannot be used as a tuple:
  File "/tmp/ipykernel_16172/2935404974.py", line 60
    def forward(self, x):
        x_non_serial, x_serial = x
                                 ~ <--- HERE
        batch_size = x_serial.size(0)
```

And how I construct my dataset Class is pretty naive. My dataset consists of two kinds of data which have different size. I just simply make these two input data as tuple in ```__getitem__```. The structure of the code looks like below:
```
 class MyDataset(data.Dataset):
    def __init__(self, mode="train"):
        skip...
    def __getitem__(self, idx):
        return (self.part1[idx], self.part2[idx]), self.target[idx]
```
As far as I know, the first object returned in ```__getitem__``` will be passed as the input to the model and the second one  will be the target to be evaluated with.
Beside that, my dataset class won't work with ```serialize``` with the error message below:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_16172/950271510.py in <module>
----> 1 serialize(MyDataset, model="train")

~/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/serializer.py in serialize(cls, *args, **kwargs)
    144         self.op = serialize(MyCustomOp, hidden_units=128)
    145     """
--> 146     return serialize_cls(cls)(*args, **kwargs)
    147 
    148 

~/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/serializer.py in serialize_cls(cls)
    126     To create an serializable class.
    127     """
--> 128     return _create_wrapper_cls(cls)
    129 
    130 

~/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/serializer.py in _create_wrapper_cls(cls, store_init_parameters, reset_mutation_uid, stop_parsing)
    114             super().__init__(*args, **kwargs)
    115 
--> 116     wrapper.__module__ = get_module_name(cls)
    117     wrapper.__name__ = cls.__name__
    118     wrapper.__qualname__ = cls.__qualname__

~/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/utils.py in get_module_name(cls_or_func)
     41         # infer the module name with inspect
     42         for frm in inspect.stack():
---> 43             if inspect.getmodule(frm[0]).__name__ == '__main__':
     44                 # main module found
     45                 main_file_path = Path(inspect.getsourcefile(frm[0]))

AttributeError: 'NoneType' object has no attribute '__name__'

```
I don't know if ```serialize``` function matters. ```@model_wrapper``` and ```@basic_unit``` also show the similar error. I not sure how nni parsing the data. Currently I have no clue where to fix this error. Could you plz give me some direction? Thx 
 

**Environment**:
- NNI version: 2.4
- Training service (local|remote|pai|aml|etc): local
- Client OS: Linux
- Server OS (for remote mode only):
- Python version: 3.7.11
- PyTorch/TensorFlow version: PyTorch 1.9.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: yes

**Comment by ultmaster** [comment]
> I also try with Random strategy which doesn't show any error message but it shows fail in the trial panel on WebUI. This is a bit confusing maybe I should share my implementation.

Maybe you should check the log of each trial?

> IndexError: list index out of range

This looks strange. If you check the implementation of TPE/Random strategy, there is actually one line that the strategy is trying to parse the search space via dry run. If you can provide that dried-runned search space, it will be much more helpful.

**Comment by ding3820** [comment]
Just find out there's stderr for each trial. It shows GPU not found. But apparently the GPU is available when execute the script. Not sure if I set the config correctly.
```
[2021-10-12 11:51:21] INFO (pytorch_lightning.utilities.distributed/MainThread)
GPU available: True, used: True
```
Here's the stderr for the trial:
```
/root/anaconda3/envs/nni/lib/python3.7/site-packages/deprecate/deprecation.py:115: LightningDeprecationWarning: The `Accuracy` was deprecated since v1.3.0 in favor of `torchmetrics.classification.accuracy.Accuracy`. It will be removed in v1.5.0.
  stream(template_mgs % msg_args)
Traceback (most recent call last):
  File "/root/anaconda3/envs/nni/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/nni/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/trial_entry.py", line 25, in <module>
    engine.trial_execute_graph()
  File "/root/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/execution/python.py", line 40, in trial_execute_graph
    graph_data = PythonGraphData.load(receive_trial_parameters())
  File "/root/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/integration_api.py", line 44, in receive_trial_parameters
    params = json_loads(json.dumps(params))
  File "/root/anaconda3/envs/nni/lib/python3.7/site-packages/json_tricks/nonp.py", line 236, in loads
    return json_loads(string, object_pairs_hook=hook, **jsonkwargs)
  File "/root/anaconda3/envs/nni/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/root/anaconda3/envs/nni/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/anaconda3/envs/nni/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/root/anaconda3/envs/nni/lib/python3.7/site-packages/json_tricks/decoders.py", line 44, in __call__
    map = hook(map, properties=self.properties)
  File "/root/anaconda3/envs/nni/lib/python3.7/site-packages/json_tricks/utils.py", line 66, in wrapper
    return encoder(*args, **{k: v for k, v in kwargs.items() if k in names})
  File "/root/anaconda3/envs/nni/lib/python3.7/site-packages/nni/retiarii/serializer.py", line 46, in _serialize_class_instance_decode
    return import_(obj['__type__'])(**obj['arguments'])
  File "/root/anaconda3/envs/nni/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 40, in insert_env_defaults
    return fn(self, **kwargs)
  File "/root/anaconda3/envs/nni/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 346, in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
  File "/root/anaconda3/envs/nni/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1262, in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
  File "/root/anaconda3/envs/nni/lib/python3.7/site-packages/pytorch_lightning/utilities/device_parser.py", line 91, in parse_gpu_ids
    return _sanitize_gpu_ids(gpus)
  File "/root/anaconda3/envs/nni/lib/python3.7/site-packages/pytorch_lightning/utilities/device_parser.py", line 164, in _sanitize_gpu_ids
    f"You requested GPUs: {gpus}\n But your machine only has: {all_available_gpus}"
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0]
 But your machine only has: []

```
