### ISSUE TITLE
 ERROR (NNIManager) AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

### ISSUE THREAD

**Issue by demeen68** [microsoft/nni#4253]
I get error in NNIManager log:

```
[2021-10-16 12:04:23] ERROR (NNIManager) AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(trialJobId === metrics.trial_job_id)

    at NNIDataStore.storeMetricData (/Users/xq/.conda/envs/baidu_news/lib/python3.6/site-packages/nni_node/core/nniDataStore.js:109:9)
    at NNIManager.onTrialJobMetrics (/Users/xq/.conda/envs/baidu_news/lib/python3.6/site-packages/nni_node/core/nnimanager.js:642:34)
    at EventEmitter.NNIManager.trialJobMetricListener (/Users/xq/.conda/envs/baidu_news/lib/python3.6/site-packages/nni_node/core/nnimanager.js:51:18)
    at EventEmitter.emit (node:events:394:28)
    at TailStream.<anonymous> (/Users/xq/.conda/envs/baidu_news/lib/python3.6/site-packages/nni_node/training_service/local/localTrainingService.js:388:35)
    at TailStream.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at TailStream.Readable.push (node:internal/streams/readable:226:10)
    at TailStream.<anonymous> (/Users/xq/.conda/envs/baidu_news/lib/python3.6/site-packages/nni_node/node_modules/tail-stream/index.js:282:18)
[2021-10-16 12:04:23] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR
```

It worked normally before, but suddenly this error occurred. I don't know what happened. There's no problem in dispatcher log.

**Environment**:
- NNI version: 2.4
- Training service (local|remote|pai|aml|etc): local
- OS: Mac os v11.2.3
- Python version: 3.6.12
- Is running in Docker?: no

<img width="715" alt="Screen Shot 2021-10-16 at 14 46 20" src="https://user-images.githubusercontent.com/29452295/137576949-f6641cb4-7470-4af4-a06a-55949f27431e.png">

**Comment by cruiseliu** [comment]
The stacktrace did not provide enough information. Please attach experiment config file (at least the tuner part) and full log.
If it can reproduce, please create experiment with `--debug` flag.

**Comment by scarlett2018** [comment]
Closing the issue as overdue as it has no responds for a while.
