### ISSUE TITLE
There is a problem with the "installation" section of the official documentation

### ISSUE THREAD

**Issue by FrostMiKu** [microsoft/nni#4254]
**Describe the issue**:

According to the "[Verify installation](https://nni.readthedocs.io/en/stable/Tutorial/InstallationLinux.html#verify-installation)"section of the official documentation, `NNI` does not work properly, `stderr` only outputs 

```
-----------------------------------------------------------------------
                Experiment start time 2021-10-18 14:03:57
-----------------------------------------------------------------------
```

Checking the `nnictl_stderr.log` file you can see 

```
TypeError: Cannot read property 'id' of undefined
    at NNIManager.setStatus (homepath/.local/lib/python3.6/site-packages/nni_node/core/nnimanager.js:748:77)
    at NNIManager.stopExperimentTopHalf (homepath/.local/lib/python3.6/site-packages/nni_node/core/nnimanager.js:240:14)
    at NNIManager.stopExperiment (homepath/.local/lib/python3.6/site-packages/nni_node/core/nnimanager.js:236:20)
    at process.cleanUp (homepath/.local/lib/python3.6/site-packages/nni_node/main.js:117:38)
    at process.emit (node:events:406:35)

```

`NNI` works properly after adding the `experimentName: MNIST` field to the `nni/examples/trials/mnist-pytorch/config.yml` file

**Environment**:
- NNI version: 2.4
- Training service (local|remote|pai|aml|etc): local
- Client OS: Linux
- Server OS (for remote mode only):
- Python version: 3.6
- PyTorch/TensorFlow version: PyTorch 1.9.1+cu102
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?: no

**How to reproduce it?**:
Follow the documentation step by step

**Comment by FrostMiKu** [comment]
I didn't press Ctrl-C, but I can't reproduce the problem now.
NNI is working well now. 
Strange...

May I should close this issue...
