### ISSUE TITLE
Remote server tensorboard not working.

### ISSUE THREAD

**Issue by sunshichen** [microsoft/nni#4293]
**Describe the issue**:
I'm using nnictl on remote server to do hyperparameter searching. I have set up the tensorboard as the latest documentation. 
Using ```ssh -N -f -L``` to forward webui so that I can open it on my local machine.  However, the tensorboard button keeps unavailable, I cannot open it. Is there anything I missed? How can I get it work
![1636019595(1)](https://user-images.githubusercontent.com/23454839/140293511-fc7bfda2-64b9-40aa-b083-5c6ce866f566.png)

**Environment**:
- NNI version: 2.5
- Training service (local|remote|pai|aml|etc): remote
- Client OS: win10
- Server OS (for remote mode only): 18.04.2-Ubuntu
- Python version: 3.7.10
- PyTorch/TensorFlow version: pytorch 1.9.0
- Is conda/virtualenv/venv used?: conda 
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!):
 ```yaml
experimentName: xxxx
searchSpaceFile: nni_search_space.json
trialCommand: CUDA_VISIBLE_DEVICES=1 python nni_trainer.py
trialGpuNumber: 1
trialConcurrency: 1
#maxTrialNumber: 10
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:  # For other platforms, check mnist-pytorch example
  platform: local
  # maxTrialNumberPerGpu: 2
  useActiveGpu: True  # NOTE: Use "true" if you are using an OS with graphical interface (e.g. Windows 10, Ubuntu desktop)
                       # Check the doc for details: https://nni.readthedocs.io/en/latest/reference/experiment_config.html#useactivegpu
  maxTrialNumberPerGpu: 1
  gpuIndices: 1
```
 - Search space:

**Log message**:
 - nnimanager.log:
 ```bash
[2021-11-04 17:42:48] INFO (NNIDataStore) Datastore initialization done
[2021-11-04 17:42:48] INFO (RestServer) RestServer start
[2021-11-04 17:42:48] INFO (RestServer) RestServer base port is xxx
[2021-11-04 17:42:48] INFO (main) Rest server listening on: http://0.0.0.0:xxx
[2021-11-04 17:42:49] INFO (NNIManager) Starting experiment: 0BM8klcm
[2021-11-04 17:42:49] INFO (NNIManager) Setup training service...
[2021-11-04 17:42:49] INFO (LocalTrainingService) Construct local machine training service.
[2021-11-04 17:42:49] INFO (NNIManager) Setup tuner...
[2021-11-04 17:42:49] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2021-11-04 17:42:49] INFO (NNIManager) Add event listeners
[2021-11-04 17:42:49] INFO (LocalTrainingService) Run local machine training service.
[2021-11-04 17:42:49] WARNING (GPUScheduler) gpu_metrics file does not exist!
[2021-11-04 17:42:50] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2021-11-04 17:42:50] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {xxx}
[2021-11-04 17:42:54] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 0,
  hyperParameters: {
    value: '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"train_data": "xxx}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2021-11-04 17:42:59] INFO (NNIManager) Trial job vi8FK status changed from WAITING to RUNNING
[2021-11-04 17:43:01] ERROR (NNIRestHandler) Error: File not found: /xxx/nni-experiments/0BM8klcm/trials/vi8FK/trial.log
    at LocalTrainingService.getTrialFile (/xxx/.local/lib/python3.7/site-packages/nni_node/training_service/local/localTrainingService.js:147:19)
    at NNIManager.getTrialFile (/xxx/.local/lib/python3.7/site-packages/nni_node/core/nnimanager.js:351:37)
    at /xxx/.local/lib/python3.7/site-packages/nni_node/rest_server/restHandler.js:287:29
    at Layer.handle [as handle_request] (/xxx/.local/lib/python3.7/site-packages/nni_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/xxx/.local/lib/python3.7/site-packages/nni_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/xxx/.local/lib/python3.7/site-packages/nni_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/xxx/.local/lib/python3.7/site-packages/nni_node/node_modules/express/lib/router/layer.js:95:5)
    at /xxx/.local/lib/python3.7/site-packages/nni_node/node_modules/express/lib/router/index.js:281:22
    at param (/dxxx/.local/lib/python3.7/site-packages/nni_node/node_modules/express/lib/router/index.js:354:14)
    at param (/xxx/.local/lib/python3.7/site-packages/nni_node/node_modules/express/lib/router/index.js:365:14)
```
 - dispatcher.log:

 - nnictl stdout and stderr:
 -nnictl_stderr.log:
 ```bash
-----------------------------------------------------------------------
                Experiment start time 2021-11-04 17:42:45
-----------------------------------------------------------------------
/xxx/.local/lib/python3.7/site-packages/json_tricks/nonp.py:225: JsonTricksDeprecation: `json_tricks.load(s)` stripped some comments, but `ignore_comments` was not passed; in the next major release, the behaviour when `ignore_comments` is not passed will change; it is recommended to explicitly pass `ignore_comments=True` if you want to strip comments; see https://github.com/mverleg/pyjson_tricks/issues/74
  JsonTricksDeprecation)

```

**How to reproduce it?**:

```shell
nnictl create --config nni_config.yml --port 8088
```

**Comment by Lijiaoa** [comment]
The `Tensorboard` button could be used when you choose the trials in the detail table.

![image](https://user-images.githubusercontent.com/61399850/140473559-ca064aae-49c3-4204-ae5c-904025ce6333.png)

**Comment by sunshichen** [comment]
Thanks greatly for your help for my silly question🤣. I didn't notice that part in documentation.
