### ISSUE TITLE
callback in multi_trial example

### ISSUE THREAD

**Issue by Annika10** [microsoft/nni#4329]
Is there a way to add callbacks in the multi_trial example? I just tried to add `callbacks=[EarlyStopping(monitor="val_loss")]` to the classification but it doesn't work. The error message is the following: 

```
Traceback (most recent call last):
  File "/home/nni/examples/nas/oneshot/spos/multi_trial.py", line 194, in <module>
    _main()
  File "/home/nni/venv/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/nni/venv/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/nni/venv/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nni/venv/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/nni/examples/nas/oneshot/spos/multi_trial.py", line 186, in _main
    exp.run(exp_config, port)
  File "/home/nni/nni/retiarii/experiment/pytorch.py", line 296, in run
    self.start(port, debug)
  File "/home/nni/nni/retiarii/experiment/pytorch.py", line 268, in start
    self._start_strategy()
  File "/home/nni/nni/retiarii/experiment/pytorch.py", line 196, in _start_strategy
    self.strategy.run(base_model_ir, self.applied_mutators)
  File "/home/nni/nni/retiarii/strategy/bruteforce.py", line 131, in run
    submit_models(model)
  File "/home/nni/nni/retiarii/execution/api.py", line 44, in submit_models
    engine.submit_models(*models)
  File "/home/nni/nni/retiarii/execution/base.py", line 64, in submit_models
    self._running_models[send_trial(data.dump())] = model
  File "/home/nni/nni/retiarii/integration_api.py", line 35, in send_trial
    return get_advisor().send_trial(parameters, placement_constraint)
  File "/home/nni/nni/retiarii/integration.py", line 124, in send_trial
    send(CommandType.NewTrialJob, json_dumps(new_trial))
  File "/home/nni/venv/lib/python3.6/site-packages/json_tricks-3.15.5-py3.6.egg/json_tricks/nonp.py", line 108, in dumps
    properties=properties, **jsonkwargs).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
```

Or do I have to write an own lightning module and self implement the early stopping?

**Comment by ultmaster** [comment]
Thanks for reporting this issue. This is a bug in our serializer. A workaround is to use FunctionalEvaluator: https://nni.readthedocs.io/en/stable/NAS/WriteTrainer.html#with-functionalevaluator
