### ISSUE TITLE
Exponential Notation is not allowed in search space

### ISSUE THREAD

**Issue by Lionelsy** [microsoft/nni#4450]
**Describe the issue**:
The Exponential Notation is not working in search space.
Similar to the [previous issue](https://github.com/microsoft/nni/issues/4080), I just found the expression of Exponential Notation in search space would lead to an error after I updated to nni2.5. 
{
    "lr": {"_type": "uniform", "_value": [1e-6, 1e-3]}
}
But it works normally when I set the search space in decimals
{
    "lr": {"_type": "uniform", "_value": [0.000001, 0.001]}
}

Considering the [previous issue](https://github.com/microsoft/nni/issues/4080), I test it on pyyaml== 6.0 and 5.4.1. The Exponential Notation expression is not working in both cases.

**Environment**:
- NNI version: 2.5
- Training service (local|remote|pai|aml|etc): local
- Client OS: ubuntu
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: PyTorch 1.9.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:
{
    "lr": {"_type": "uniform", "_value": [1e-6, 1e-3]}
}

**Log message**:
 - dispatcher.log:
 
[2022-01-06 15:00:37] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2022-01-06 15:00:37] ERROR (nni.common.hpo_utils.validation/Thread-1) search space "lr" (uniform) must have float values : OrderedDict([('_type', 'uniform'), ('_value', ['1e-6', '1e-3'])])
[2022-01-06 15:00:37] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000977 seconds
[2022-01-06 15:00:37] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[2022-01-06 15:00:37] ERROR (nni.runtime.msg_dispatcher_base/Thread-1) must be real number, not str
Traceback (most recent call last):
  File "/home/shuyu/anaconda3/envs/trajectory/lib/python3.8/site-packages/nni/runtime/msg_dispatcher_base.py", line 88, in command_queue_worker
    self.process_command(command, data)
  File "/home/shuyu/anaconda3/envs/trajectory/lib/python3.8/site-packages/nni/runtime/msg_dispatcher_base.py", line 147, in process_command
    command_handlers[command](data)
  File "/home/shuyu/anaconda3/envs/trajectory/lib/python3.8/site-packages/nni/runtime/msg_dispatcher.py", line 102, in handle_request_trial_jobs
    params_list = self.tuner.generate_multiple_parameters(ids, st_callback=self.send_trial_callback)
  File "/home/shuyu/anaconda3/envs/trajectory/lib/python3.8/site-packages/nni/tuner.py", line 132, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id, **kwargs)
  File "/home/shuyu/anaconda3/envs/trajectory/lib/python3.8/site-packages/nni/algorithms/hpo/hyperopt_tuner.py", line 280, in generate_parameters
    total_params = self.get_suggestion(random_search=False)
  File "/home/shuyu/anaconda3/envs/trajectory/lib/python3.8/site-packages/nni/algorithms/hpo/hyperopt_tuner.py", line 457, in get_suggestion
    new_trials = algorithm(new_ids, rval.domain, trials, random_state)
  File "/home/shuyu/anaconda3/envs/trajectory/lib/python3.8/site-packages/hyperopt/tpe.py", line 870, in suggest
    return rand.suggest(new_ids, domain, trials, seed)
  File "/home/shuyu/anaconda3/envs/trajectory/lib/python3.8/site-packages/hyperopt/rand.py", line 20, in suggest
    idxs, vals = pyll.rec_eval(
  File "/home/shuyu/anaconda3/envs/trajectory/lib/python3.8/site-packages/hyperopt/pyll/base.py", line 913, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "/home/shuyu/anaconda3/envs/trajectory/lib/python3.8/site-packages/hyperopt/pyll/stochastic.py", line 38, in uniform
    return rng.uniform(low, high, size=size)
  File "mtrand.pyx", line 1106, in numpy.random.mtrand.RandomState.uniform
TypeError: must be real number, not str
[2022-01-06 15:00:41] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2022-01-06 15:00:43] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminated

Thanks for your kindly reply!

**Comment by liuzhe-lz** [comment]
Please check your pyyaml version: `python3 -c 'import yaml ; print(yaml.__version__)'`.
It should no less than 5.4.

Then try to load the search space file directly:
```python
import yaml
space = yaml.safe_load(open('search_space.json'))
print(space)
```

**Comment by Lionelsy** [comment]
Thanks and Looking forward to the new NNI.
