### ISSUE TITLE
Doubts about NAS+TypeError: tuple is not a Module subclass

### ISSUE THREAD

**Issue by singagan** [microsoft/nni#4542]
**Describe the issue**:
I am using your framework to perform a NAS experiment on my use case. 
While using LayerChoice I get the below error.
**TypeError: tuple is not a Module subclass**

**Apart from the above issue, I have a few more questions:**
1) If I understood correctly, right now with one-shot NAS you only support LayerChoice and InputChoice, right? In my use case I would like to use input choice and also repeat. Is it possible to do that? 
I started to use DARTS for it because it is faster. Would you recommend switching to another NAS  approach to use other mutation options?

2)  If I understood correctly,  these are layerwise approaches. Would it be possible to extend it to a blockwise approach as well?

*Environment**: Remote Server
- NNI version: 2.6
- Training service (local|remote|pai|aml|etc):
- Client OS:Ubuntu 20.04.3 LTS
- Server OS (for remote mode only):Ubuntu 20.04.3 LTS
- Python version:Python 3.8.12
- PyTorch/TensorFlow version: Toch 1.10.0+cu111
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!): one-shot DARTS
```
  self.pointwise=LayerChoice([
               (nn.Conv1d(
                in_channels, out_channels, kernel_size=1, stride=1,
                dilation=dilation, bias=bias, padding=0
            ),
            nn.Conv1d(
               in_channels, out_channels, kernel_size=2, stride=1,
                dilation=dilation, bias=bias, padding=0
            ),
              nn.Identity()

            )],label='point')
        else:
            self.conv = Conv1d(
                in_channels, out_channels, kernel_size=kernel_size,
                stride=stride, padding=padding, dilation=dilation, bias=bias
            )

    def forward(self, x):
        if self.separable:
            x = self.depthwise(x)
            x = self.pointwise(x)
        else:
            x = self.conv(x)
        return x
```

ERROR:
```
File "mutatemodel.py", line 174, in __init__
    self.pointwise=LayerChoice([
  File "nni/nni/retiarii/nn/pytorch/api.py", line 95, in __init__
    self.add_module(str(i), module)
  File "python3.8/site-packages/torch/nn/modules/module.py", line 377, in add_module
    raise TypeError("{} is not a Module subclass".format(
TypeError: tuple is not a Module subclass
```

I look forward to your reply.

Thanks!

**Comment by singagan** [comment]
I was able to resolve the issue. I still have some questions. Please could you answer those?

1) If I understood correctly, right now with one-shot NAS you only support LayerChoice and InputChoice, right? In my use case I would like to use input choice and also repeat. Is it possible to do that? 
I started to use DARTS for it because it is faster. Would you recommend switching to another NAS  approach to use other mutation options?

2)  If I understood correctly,  these are layerwise approaches. Would it be possible to extend it to a blockwise approach as well?

**Comment by ultmaster** [comment]
1. Supporting repeat on DARTS is in our plan. (probably conv-with-ValueChoice, then repeat).
2. I might not be familiar with those glossaries. So may I ask what's the differences between layer-wise approach and block-wise approach?

**Comment by ultmaster** [comment]
1. You can try to add an Identity to LayerChoice.
2. Please refer to ProxylessNAS example.

**Comment by ultmaster** [comment]
For example, when you want "one to three" layers of conv:

```python
self.conv1 = nn.LayerChoice([nn.Conv2d(...), nn.Identity()])
self.conv2 = nn.LayerChoice([nn.Conv2d(...), nn.Identity()])
self.conv3 = nn.LayerChoice([nn.Conv2d(...), nn.Identity()])
```

**Comment by singagan** [comment]
@ultmaster Awesome! Indeed that seems to work! Thanks!

One last thing: regarding Value choice: How can I incorporate that in such a block-based design?

**Comment by ultmaster** [comment]
What you are trying to do is called nested LayerChoice. This is supported by most multi-trial strategies, but unfortunately hasn't been supported by one-shot yet.
One workaround is to build two search spaces. Search the inner one first then the outer one. Another workaround is to inherit the DartsTrainer and implement how to handle nested by yourself, which is not easy. I believe such usage is not even included in the original design of DARTS paper.

Export best model to onnx doesn't actually make any sense. After you get the best architecture, which is only a network structure, you have to "retrain" it to get the final model. Please refer to docs on how to do it.

**Comment by singagan** [comment]
**Regarding nested LayerChoice:** I guess two separate search spaces might not give the most optimum solution. I am rewriting the code to flatten the hierarchy, so there would be only one search space. If this does not work then I would try a multi-trial approach.

Thanks for the heads-up regarding retraining. I am implementing that.

Regarding the NAS search: One thing I noticed is that in my use case, the child network's loss saturates around 2.0x, which is quite high. I am trying to play around with the hyper-parameters but doesn't seem to help.  
Do you have a hunch about what could be the reason for it? Is it like I need to retrain to fix this? Otherwise, I am not sure if the search is generating the best architecture.

**Comment by ultmaster** [comment]
Flatten the nested LayerChoice into a un-nested one could be a valid workaround.

Hardware-aware DARTS: A straightforward idea is to implement a regularized term (normalized expected latency) to punish the architecture parameter so that it prefers light-weight operators. (Notably, this appears to exactly what have been done in ProxylessNAS.) Another one is to filter out the architectures exceeding latency limit when exporting. Or you can use ProxylessNAS, but bear in mind that there are other differences between ProxylessNAS and DARTS other than the "hardware" part.

**Comment by singagan** [comment]
Thanks for the input. I am trying to switch to ProxylessNAS. Finally, I was able to pass my model from torch.jit.script. While converting to the graph I get the below error message. torch.jit.script seems to work correctly. 
I tried to debug. It seems like in graph_gen.py [lc_node](https://github.com/microsoft/nni/blob/632df3ea2f99f3c8e4d2a16fab6ebe4303609da1/nni/retiarii/converter/graph_gen.py#L744) is None, so [get_node_by_name(](https://github.com/microsoft/nni/blob/632df3ea2f99f3c8e4d2a16fab6ebe4303609da1/nni/retiarii/graph.py#L203) in graph.py is returning None.  Not sure if there is some label mismatch happening over here?

```
Traceback (most recent call last):
  File "nas.py", line 165, in main
    trainer = ProxylessTrainer(
  File "nni/nni/retiarii/oneshot/pytorch/proxyless.py", line 267, in __init__
    self.latency_estimator = HardwareLatencyEstimator(applied_hardware, self.model, dummy_input)
  File "nni/nni/retiarii/oneshot/pytorch/proxyless.py", line 114, in __init__
    self.block_latency_table = self._form_latency_table(model, dummy_input, dump_lat_table=dump_lat_table)
  File "nni/nni/retiarii/oneshot/pytorch/proxyless.py", line 138, in _form_latency_table
    base_model_ir = convert_to_graph(script_module, model,
  File "nni/nni/retiarii/converter/graph_gen.py", line 845, in convert_to_graph
    converter.convert_module(script_module, module, module_name, model, **kwargs)
  File "nni/nni/retiarii/converter/graph_gen.py", line 715, in convert_module
    self._trace_module(module, module_name, ir_model, dummy_input)
  File "nni/nni/retiarii/converter/graph_gen.py", line 755, in _trace_module
    lc_inputs = [torch.randn(shape) for shape in lc_node.operation.attributes['input_shape']]
AttributeError: 'NoneType' object has no attribute 'operation'
```

**Comment by ultmaster** [comment]
Well... now the traceback comes to graph converter. I have to say, graph_gen is a delicate and fragile piece of code. I'll ask colleagues who's specialized in this part to take a look.

**Comment by singagan** [comment]
Thanks, @ultmaster! I would appreciate that!
I am trying to debug on my end as well.

**Comment by singagan** [comment]
Hi @JiahangXu, I see. Please see below. I use the below block 1) with different kernel sizes inside one LayerChoice 2) and stack it with other blocks

```
self.block1 = nn.LayerChoice([CustomBlock_kernelsize1(...), CustomBlock_kernelsize2(...), .........., nn.Identity()])
self.block2 = nn.LayerChoice([CustomBlock_kernelsize1(...), CustomBlock_kernelsize2(...), .........., nn.Identity()])

```

```
class CustomBlock(nn.Module):
    def __init__(self, in_channels, out_channels,activation, dropout, kernel_size=1, stride=1, dilation=1, padding=0, bias=False, separable=False):
        super(CustomBlock, self).__init__()

        self.depthwise = nn.Conv1d(
        in_channels, in_channels, kernel_size=kernel_size, stride=stride,
        padding=padding, dilation=dilation, bias=bias, groups=in_channels)

        self.point_linear = nn.Sequential(OrderedDict([
            ('conv', nn.Conv1d(
                in_channels, out_channels, kernel_size=1, stride=1,
                dilation=dilation, bias=False, padding=0)),
                ('bn', nn.BatchNorm1d(out_channels, eps=1e-3, momentum=0.1)),
                ('act',activation),
                ('drop',nn.Dropout(p=0.5))
                ]))

    def forward(self, x):
        x = self.depthwise(x)
        x = self.point_linear(x)
        return x
```

**Regarding non-edge devices:** So it wouldn't be possible to have our own device or model at all? I would like to make my NAS hardware aware for my platform.

**Comment by JiahangXu** [comment]
Got it. I will test your code. About enabled devices, nn-Meter provides builder tools to help users build the latency predictor for their own devices. I mean nn-Meter has no plan to provide fully completed latency predictors for non-edge devices. The nn-Meter version containing nn-Meter builder tools will be released in about one or two weeks. I hope this information could help.

**Comment by singagan** [comment]
Thanks, @JiahangXu! Please keep me posted.

**Regarding enabled devices:** that would be great if you will allow users to build their own latency predictors! I would certainly try to contribute there.

**Comment by singagan** [comment]
Hi, @JiahangXu and @ultmaster, update on this issue:
I was finally able to parse my model to run it with ProxylessNAS. 
I did the following two things to make it work:
1) Moved all the logic from `forward() `to` init()`
2) Updated [kernel_detector.py ](https://github.com/microsoft/nn-Meter/blob/76d7f881e18cb0012ee5887abe8baabd58e40f1b/nn_meter/kernel_detector/kernel_detector.py#L92) to support tensors with axis other than 4. (I guess you hard-coded it for imagenet).

Now I am debugging everything for functional correctness. Right now, I am using the cortexA76cpu_tflite21 device. I realized that the latency of my modules in latency_table.yaml seems a bit lower than what I would expect. Could it be because I am using 1D modules (conv1d, BatchNorm1d, etc) while the cortexA76cpu_tflite21 is built using 2D modules? or I need to name the module in a certain way so nn-meter can predict?

I guess the stationary_block in latency_table are non-layerchoice modules, right?
