### ISSUE TITLE
slim pruner for shufflenetV2 cannot speed up

### ISSUE THREAD

**Issue by bl6g6** [microsoft/nni#4556]
NNI version: 2.6

I was planning to use slim pruner to prune shufflenetV2. I used 
```
model = torchvision.models.shufflenet_v2_x0_5() 
```
as my model. 
Everything works fine except the model speed up part.
The error shows:
```
Traceback (most recent call last):
  File "train_lite.py", line 320, in <module>
    main(args)
  File "train_lite.py", line 262, in main
    m_speedup.speedup_model()
  File "/app/nni/nni-2.6/nni/compression/pytorch/speedup/compressor.py", line 509, in speedup_model
    self.infer_modules_masks()
  File "/app/nni/nni-2.6/nni/compression/pytorch/speedup/compressor.py", line 355, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/app/nni/nni-2.6/nni/compression/pytorch/speedup/compressor.py", line 217, in update_direct_sparsity
    func, dummy_input, in_masks, in_constants=in_constants, batch_dim=self.batch_dim)
  File "/app/nni/nni-2.6/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'
```
I tried another model like torchvision.models.mobilenet_v2(), and the speed up part works perfectly.
Any idea on how to fix it?

**Comment by syswyl** [comment]
@bl6g6 hi
https://github.com/microsoft/nni/issues/3453#issuecomment-800909476
NNI has not supported the pruning of the shufflenet structure
It seems that there is no official solution to this problem yet.

**Comment by bl6g6** [comment]
> @bl6g6 hi [#3453 (comment)](https://github.com/microsoft/nni/issues/3453#issuecomment-800909476) NNI has not supported the pruning of the shufflenet structure It seems that there is no official solution to this problem yet.

I see, thank you!
