### ISSUE TITLE
 Github link: examples/nas/multi-trial/mnist/search.py can't run in windows 11

### ISSUE THREAD

**Issue by y070504** [microsoft/nni#4631]
**Describe the issue**:
 Github link: examples/nas/multi-trial/mnist/search.py can't run in windows 11

[2022-03-10 16:29:21] INFO (numexpr.utils/MainThread) Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2022-03-10 16:29:21] INFO (numexpr.utils/MainThread) NumExpr defaulting to 8 threads.
[2022-03-10 16:29:25] INFO (nni.experiment/MainThread) Creating experiment, Experiment ID: bywqptka
[2022-03-10 16:29:25] INFO (nni.experiment/MainThread) Connecting IPC pipe...
[2022-03-10 16:29:26] INFO (nni.experiment/MainThread) Starting web server...
[2022-03-10 16:29:28] INFO (nni.experiment/MainThread) Setting up...
[2022-03-10 16:29:30] INFO (nni.runtime.msg_dispatcher_base/Thread-3) Dispatcher started
[2022-03-10 16:29:30] INFO (nni.retiarii.experiment.pytorch/MainThread) Web UI URLs: http://169.254.175.252:8162 http://192.168.56.1:8162 http://169.254.247.169:8162 http://169.254.47.97:8162 http://192.168.253.1:8162 http://192.168.88.1:8162 http://192.168.31.135:8162 http://169.254.74.92:8162 http://127.0.0.1:8162
[2022-03-10 16:29:30] INFO (nni.retiarii.experiment.pytorch/MainThread) Start strategy...
[2022-03-10 16:29:37] INFO (root/MainThread) Successfully update searchSpace.
[2022-03-10 16:29:37] INFO (nni.retiarii.strategy.bruteforce/MainThread) Random search running in fixed size mode. Dedup: on.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\nni\runtime\msg_dispatcher_base.py", line 51, in run
    command, data = receive()
  File "D:\ProgramData\Anaconda3\lib\site-packages\nni\runtime\protocol.py", line 61, in receive
    header = _in_file.read(16)
OSError: [Errno 22] Invalid argument

**Environment**:
- NNI version:2.6.1
- Training service (local|remote|pai|aml|etc):local
- Client OS: windows 11
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: pytorch 1.10.2+cu113
- Is conda/virtualenv/venv used?:
- Is running in Docker?: no

**How to reproduce it?**:

**Comment by cruiseliu** [comment]
We are refactoring underlying IPC mechanism.
For now you may try to run it inside WSL.

**Comment by lrlofgren** [comment]
I am running into a similar issue in windows 10

**Comment by saber00001** [comment]
Running the code on WSL solves this problem. You can enter "netstat -ano | findstr 8080" (8080 refers to the port number used in WSL) on cmd.exe to query the Web UI URLs that can be opened on win browsers.

**Comment by liuzhe-lz** [comment]
Close because the related part has been rewritten.
