### ISSUE TITLE
使用 nnictl stop --all 无法解决 RuntimeError: Port 8080 is not idle

### ISSUE THREAD

**Issue by FireDragon00** [microsoft/nni#4651]
## NNI 学生项目问题概述
我最近刚开始使用NNI。现在跟着教程没走完，就来问问。

我先运行

> nnictl create --config nni/examples/trials/mnist-pytorch/config.yml

验证安装步骤成功了，然后我运行下面的

> nnictl create --config nni/examples/trials/mnist-pytorch/config_detailed.yml

失败了。于是我删除了原先生成的nni-expriment文件，然后运行了nnictl stop --all，然后出现下面的INFO：

> INFO:  Experiment is not running...

但是我还能打开页面。

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version: 2.6
- nni mode(local|pai|remote): local
- OS: Linux
- python version: 3.7
- is conda or virtualenv used?: conda
- is running in docker?: No

**Log message / 日志信息 :**
(MAPP) xgl_2020@ubuntu:~$ nnictl create --config nni/examples/trials/mnist-pytorch/config_detailed.yml

Traceback (most recent call last):

  File "/home/xgl_2020/anaconda3/envs/MAPP/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())

  File "/home/xgl_2020/anaconda3/envs/MAPP/lib/python3.7/site-packages/nni/tools/nnictl/nnictl.py", line 286, in parse_args
    args.func(args)

  File "/home/xgl_2020/anaconda3/envs/MAPP/lib/python3.7/site-packages/nni/tools/nnictl/launcher.py", line 92, in create_experiment
    exp.start(port, debug, run_mode)

  File "/home/xgl_2020/anaconda3/envs/MAPP/lib/python3.7/site-packages/nni/experiment/experiment.py", line 130, in start
    self._proc = launcher.start_experiment(self.mode, self.id, config, port, debug, run_mode, self.url_prefix)

  File "/home/xgl_2020/anaconda3/envs/MAPP/lib/python3.7/site-packages/nni/experiment/launcher.py", line 82, in start_experiment
    _ensure_port_idle(port)

  File "/home/xgl_2020/anaconda3/envs/MAPP/lib/python3.7/site-packages/nni/experiment/launcher.py", line 191, in _ensure_port_idle

    raise RuntimeError(f'Port {port} is not idle {message}')

RuntimeError: Port 8080 is not idle

**Comment by FireDragon00** [comment]
我换个端口就好了，只是8080端口一直使用不了了

**Comment by Javion11** [comment]
因为端口被占用了，只要清空8080端口占用程序就好了

**Comment by xinlnix** [comment]
存在这种运行后停止了还一直占用端口的情况
