### ISSUE TITLE
Yolov2-tiny pruning problem

### ISSUE THREAD

**Issue by chengpr** [microsoft/nni#4665]
我在使用NNI进行剪枝过程中（L1FilterPruner策略），在m_speedup.speedup_model()这一步产生了报错
TypeError: forward() missing 1 required positional argument: 'x'

我在整个yolov2-tiny中仅对最后一层使用了yolo检测层,需要剪枝部分如下：
+-------+----------------------+--------+-------------------+----------+---------+
| Index |         Name         |  Type  |    Weight Shape   |  FLOPs   | #Params |
+-------+----------------------+--------+-------------------+----------+---------+
|   0   | model.0.conv.module  | Conv2d |   (16, 3, 3, 3)   | 12386304 |   448   |
|   1   | model.2.conv.module  | Conv2d |   (32, 16, 3, 3)  | 30670848 |   4640  |
|   2   | model.4.conv.module  | Conv2d |   (64, 32, 3, 3)  | 30670848 |  18496  |
|   3   | model.6.conv.module  | Conv2d |  (128, 64, 3, 3)  | 30670848 |  73856  |
|   4   | model.8.conv.module  | Conv2d |  (256, 128, 3, 3) | 30375936 |  295168 |
|   5   | model.10.conv.module | Conv2d |  (512, 256, 3, 3) | 30228480 | 1180160 |
|   6   | model.13.conv.module | Conv2d | (1024, 512, 1, 1) | 13434880 |  525312 |
|   7   | model.14.conv.module | Conv2d | (512, 1024, 1, 1) | 13434880 |  524800 |
|   8   |     model.15.m.0     | Conv2d |  (35, 512, 1, 1)  | 1146880  |  17955  |
+-------+----------------------+--------+-------------------+----------+---------+
通过其他ISSUE的查阅，我尝试了2种config_list修改方法：
（1）
config_list = [{
    'sparsity': 0.6,
    'op_names': ['model.0.conv', 'model.2.conv', 'model.4.conv', 'model.6.conv',
                 'model.8.conv', 'model.10.conv', 'model.13.conv', 'model.14.conv']
}, {
   # 'sparsity': 0.6,
    'op_names': ['model.15.m.0'],
    'exclude': True
}]
（2）
config_list = [{
    'sparsity': 0.6,
    #'op_types': ['Conv2d']
}, {
   # 'sparsity': 0.6,
    'op_names': ['model.15.m.0'],
    'exclude': True
}]

但是他们仍然有上述的错误：
[2022-03-21 19:02:46] INFO (nni.compression.pytorch.compressor/MainThread) Model state_dict saved to slim_pruned.pth
[2022-03-21 19:02:46] INFO (nni.compression.pytorch.compressor/MainThread) Mask dict saved to slim_pruned_mask.pth
E:\my project\yolov2\models\yolo.py:53: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.grid[i].shape[2:4] != x[i].shape[2:4]:
[2022-03-21 19:02:47] INFO (nni.compression.pytorch.speedup.compressor/MainThread) start to speed up the model
[2022-03-21 19:02:47] INFO (FixMaskConflict/MainThread) {'model.0.conv.module': 1, 'model.2.conv.module': 1, 'model.4.conv.module': 1, 'model.6.conv.module': 1, 'model.8.conv.module': 1, 'model.10.conv.module': 1, 'model.13.conv.module': 1, 'model.14.conv.module': 1, 'model.15.m.0': 1}
[2022-03-21 19:02:47] WARNING (FixMaskConflict/MainThread) no multi-dimension masks found.
[2022-03-21 19:02:47] INFO (FixMaskConflict/MainThread) Dectected conv prune dim" 0
[2022-03-21 19:02:47] INFO (nni.compression.pytorch.speedup.compressor/MainThread) infer module masks...
[2022-03-21 19:02:47] INFO (nni.compression.pytorch.speedup.compressor/MainThread) Update mask for model.0.conv.module
[2022-03-21 19:02:47] INFO (nni.compression.pytorch.speedup.compressor/MainThread) Update mask for model.15.aten::to.35
Traceback (most recent call last):
  File "E:/my project/yolov2/models/purn.py", line 67, in <module>
    m_speedup.speedup_model()
  File "D:\Anaconda\envs\pytorch\lib\site-packages\nni\compression\pytorch\speedup\compressor.py", line 509, in speedup_model
    self.infer_modules_masks()
  File "D:\Anaconda\envs\pytorch\lib\site-packages\nni\compression\pytorch\speedup\compressor.py", line 355, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\nni\compression\pytorch\speedup\compressor.py", line 217, in update_direct_sparsity
    func, dummy_input, in_masks, in_constants=in_constants, batch_dim=self.batch_dim)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\nni\compression\pytorch\speedup\infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'

（1）不知道是否有其他办法可以解决这个问题
（2）希望可以参考一下官方做的yolov3的demo,不知道在哪里可以获取

**Comment by chengpr** [comment]
我找到了这个问题的解决方法，我发现根据Darknet建立的yolo框架可以很好地进行NNI的剪枝。而官方新版的yolo代码中最后一层yoloceng则会将整个modelspeed_up卡住。
我并不知道为何会这样

**Comment by terriicon** [comment]
我跟你遇到了一样的问题，我大概知道是在构建最后一个检测层的时候，输入不知道为什么变成了空列表导致的，yolo系列都有这个问题，要改的话挺难的，我反正放弃了，等官方实现。

**Comment by chengpr** [comment]
如果你是使用只有一个检测层/标准的Yolo格式时，你可以尝试一下我说的这个方法。
官方提供了两种生成yolo的形式，一种是基于Darknet框架生成的（.cfg)另一种是通过（.yaml）文件实现的，我通过Darknet那个版本实现了剪枝。
在NNI官方demo中有一个yolo3的剪枝demo，其中最重要的一点是跳过没有在库中的函数，这里面就包括了yolo层



你可以尝试一下是否能够进行对应的剪枝实现
发件人:                                                                                                                        "microsoft/nni"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 上午9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/nni] Yolov2-tiny pruning problem (Issue #4665)





 
我跟你遇到了一样的问题，我大概知道是在构建最后一个检测层的时候，输入不知道为什么变成了空列表导致的，yolo系列都有这个问题，要改的话挺难的，我反正放弃了，等官方实现。
