### ISSUE TITLE
nni.retiarii.nn.pytorch error

### ISSUE THREAD

**Issue by bl6g6** [microsoft/nni#4723]
I was running exapmles/NAS/multi-trial/mnist/search.py, and it showed the following  error:
```
Traceback (most recent call last):
  File "trial1.py", line 4, in <module>
    import nni.retiarii.nn.pytorch as nn
  File "/app/nni/nni-2.6/nni/retiarii/nn/pytorch/__init__.py", line 1, in <module>
    from .api import *
  File "/app/nni/nni-2.6/nni/retiarii/nn/pytorch/api.py", line 361, in <module>
    class Placeholder(nn.Module):
  File "/app/nni/nni-2.6/nni/retiarii/serializer.py", line 81, in basic_unit
    cls.trace_symbol = torch.jit.unused(cls.trace_symbol)
  File "/usr/local/lib/python3.6/dist-packages/torch/_jit_internal.py", line 373, in unused
    fn._torchscript_modifier = FunctionModifiers.UNUSED
AttributeError: 'property' object has no attribute '_torchscript_modifier'
```
Has anyone met the same issue?

**Comment by ultmaster** [comment]
Maybe you should upgrade your PyTorch.

**Comment by bl6g6** [comment]
Yes, it works. Thank you.
