### ISSUE TITLE
Attribute error when using nnictl view [experiment ID] from terminal in WSL.

### ISSUE THREAD

**Issue by lrlofgren** [microsoft/nni#4743]
I cannot view old experiments. When I use the nnictl view command I get an attribute error:
raise AttributeError(f'{class_name} does not have field(s) {fields}')

Entire error pasted below. 

(.venv) root@anesth-lars:/algorithm_dev/NeuralNetV1# nnictl view k21rd3pf
Traceback (most recent call last):
  File "/algorithm_dev/NeuralNetV1/.venv/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
  File "/algorithm_dev/NeuralNetV1/.venv/lib/python3.8/site-packages/nni/tools/nnictl/nnictl.py", line 286, in parse_args
    args.func(args)
  File "/algorithm_dev/NeuralNetV1/.venv/lib/python3.8/site-packages/nni/tools/nnictl/launcher.py", line 129, in view_experiment
    exp = Experiment._view(exp_id, exp_dir)
  File "/algorithm_dev/NeuralNetV1/.venv/lib/python3.8/site-packages/nni/experiment/experiment.py", line 273, in _view
    exp.config = launcher.get_stopped_experiment_config(exp_id, exp_dir)
  File "/algorithm_dev/NeuralNetV1/.venv/lib/python3.8/site-packages/nni/experiment/launcher.py", line 257, in get_stopped_experiment_config
    config = ExperimentConfig(**config_json)
  File "/algorithm_dev/NeuralNetV1/.venv/lib/python3.8/site-packages/nni/experiment/config/experiment_config.py", line 86, in __init__
    super().__init__(**kwargs)
  File "/algorithm_dev/NeuralNetV1/.venv/lib/python3.8/site-packages/nni/experiment/config/base.py", line 93, in __init__
    raise AttributeError(f'{class_name} does not have field(s) {fields}')
AttributeError: ExperimentConfig does not have field(s) executionengine

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by lrlofgren** [comment]
I did notice that in the Config settings on the web UI it is listed as executionEngine (shown in the image), whereas the error says ExperimentConfig does not have field executionengine. not sure if the difference in capitlization matters. 
![image](https://user-images.githubusercontent.com/101950705/162530957-06565ff7-eba2-42c4-afa7-10f71d455207.png)

**Comment by matluster** [comment]
RetiariiExperiment can't be "viewed" with nnictl view.

What's your intention here? Do you want to inspect a stopped NAS experiment?

**Comment by lrlofgren** [comment]
yes, I am trying to view a stopped experiment

**Comment by cjrd** [comment]
Why can't RetiariiExperiment be viewed with nnictl view? The nnictl web UI seems to work just fine when the experiment is running -- how do I get back to the same view after the experiment has completed?

**Comment by RitwikGupta** [comment]
Echoing the views shared above. I want to inspect my completed experiments and dive into the visualizations presented on the screen. Currently I cannot navigate through the UI once experiments have concluded, making it almost useless.

**Comment by ultmaster** [comment]
Closing this as RetiariiExperiment.view is already supported in v2.9.
