### ISSUE TITLE
I have meet an unknown error when I try the mnist nas example.

### ISSUE THREAD

**Issue by sun-tao** [microsoft/nni#4766]
**Describe the issue**:

[2022-04-13 19:34:12] INFO (nni.experiment/MainThread) Creating experiment, Experiment ID: cau4bj2g
[2022-04-13 19:34:12] INFO (nni.experiment/MainThread) Connecting IPC pipe...
[2022-04-13 19:34:13] INFO (nni.experiment/MainThread) Starting web server...
[2022-04-13 19:34:15] INFO (nni.experiment/MainThread) Setting up...
[2022-04-13 19:34:17] INFO (nni.runtime.msg_dispatcher_base/Thread-3) Dispatcher started
[2022-04-13 19:34:17] INFO (nni.retiarii.experiment.pytorch/MainThread) Web UI URLs: http://169.254.240.252:8081 http://169.254.175.234:8081 http://169.254.108.7:8081 http://169.254.237.19:8081 http://192.168.195.1:8081 http://192.168.75.1:8081 http://192.168.160.7:8081 http://169.254.27.48:8081 http://127.0.0.1:8081
[2022-04-13 19:34:17] INFO (nni.retiarii.experiment.pytorch/MainThread) Start strategy...
[2022-04-13 19:34:21] INFO (root/MainThread) Successfully update searchSpace.
[2022-04-13 19:34:21] INFO (nni.retiarii.strategy.bruteforce/MainThread) Random search running in fixed size mode. Dedup: on.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\anaconda_home\envs\nni_test\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\anaconda_home\envs\nni_test\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\anaconda_home\envs\nni_test\lib\site-packages\nni\runtime\msg_dispatcher_base.py", line 51, in run
    command, data = receive()
  File "D:\anaconda_home\envs\nni_test\lib\site-packages\nni\runtime\protocol.py", line 61, in receive
    header = _in_file.read(16)
OSError: [Errno 22] Invalid argument

**Environment**:
- NNI version: 2.6.1
- Training service (local|remote|pai|aml|etc): local
- Client OS:windows
- Server OS (for remote mode only):
- Python version:3.6
- PyTorch/TensorFlow version:1.10
- Is conda/virtualenv/venv used?:is
- Is running in Docker?:

**<html>
<body>

absl-py | 1.0.0 |  
-- | -- | --
bzip2 | 1.0.8 |  
ca-certificates | 2021.10.8 |  
cachetools | 4.2.4 |  
certifi | 2021.10.8 |  
charset-normalizer | 2.0.12 |  
cloudpickle | 2.0.0 |  
colorama | 0.4.4 |  
contextlib2 | 21.6.0 |  
cudatoolkit | 9.2.148 |  
dill | 0.3.4 |  
filelock | 3.3.2 |  
google-auth | 2.6.2 |  
google-auth-oauthlib | 0.4.6 |  
grpcio | 1.45.0 |  
idna | 3.3 |  
importlib-resources | 5.4.0 |  
json-tricks | 3.15.5 |  
libffi | 3.4.2 |  
libzlib | 1.2.11 |  
markdown | 3.3.6 |  
networkx | 2.5.1 |  
nni | 2.6.1 |  
numpy | 1.19.3 |  
oauthlib | 3.2.0 |  
openssl | 3.0.2 |  
pandas | 1.1.5 |  
pillow | 8.4.0 |  
pip | 21.3.1 |  
protobuf | 3.19.4 |  
pyasn1 | 0.4.8 |  
pyasn1-modules | 0.2.8 |  
python | 3.6.15 |  
python-dateutil | 2.8.2 |  
pytz | 2022.1 |  
requests | 2.27.1 |  
requests-oauthlib | 1.3.1 |  
rsa | 4.8 |  
schema | 0.7.5 |  
scipy | 1.5.4 |  
setuptools | 59.6.0 |  
six | 1.16.0 |  
sqlite | 3.38.2 |  
tensorboard | 2.8.0 |  
tensorboard-data-server | 0.6.1 |  
tensorboard-plugin-wit | 1.8.1 |  
thop | 0.0.31-2005241907 |  
tk | 8.6.12 |  
torch | 1.10.0+cpu |  
torchaudio | 0.10.0+cu113 |  
torchvision | 0.11.0+cpu |  
tqdm | 4.63.0 |  
typeguard | 2.13.3 |  
typing-extensions | 4.1.1 |  
ucrt | 10.0.20348.0 |  
urllib3 | 1.26.9 |  
vc | 14.2 |  
vs2015_runtime | 14.29.30037 |  
wcwidth | 0.2.5 |  
werkzeug | 2.0.3 |  
wheel | 0.37.1 |  
xz | 5.2.5 |  
zipp | 3.6.0 |  

</body>
</html>**
**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
[2022-04-13 20:17:33] INFO (NNIManager) Trial job x70fi status changed from WAITING to RUNNING
[2022-04-13 20:17:41] INFO (NNIManager) Trial job x70fi status changed from RUNNING to FAILED

 - dispatcher.log:
 [2022-04-13 20:16:58] INFO (nni.experiment/MainThread) Creating experiment, Experiment ID: [36mbntk1sfo[0m
[2022-04-13 20:16:58] INFO (nni.experiment/MainThread) Connecting IPC pipe...
[2022-04-13 20:17:00] INFO (nni.experiment/MainThread) Starting web server...
[2022-04-13 20:17:02] INFO (nni.experiment/MainThread) Setting up...
[2022-04-13 20:17:04] INFO (nni.runtime.msg_dispatcher_base/Thread-3) Dispatcher started
[2022-04-13 20:17:04] INFO (nni.retiarii.experiment.pytorch/MainThread) Web UI URLs: [36mhttp://169.254.240.252:8081 http://169.254.175.234:8081 http://169.254.108.7:8081 http://169.254.237.19:8081 http://192.168.195.1:8081 http://192.168.75.1:8081 http://192.168.160.7:8081 http://169.254.27.48:8081 http://127.0.0.1:8081[0m
[2022-04-13 20:17:04] INFO (nni.retiarii.experiment.pytorch/MainThread) Start strategy...
[2022-04-13 20:17:08] INFO (root/MainThread) Successfully update searchSpace.
[2022-04-13 20:17:08] INFO (nni.retiarii.strategy.bruteforce/MainThread) Random search running in fixed size mode. Dedup: on.

 - nnictl stdout and stderr:
 stdout:
ERROR: C:\Users\suntao\nni-experiments\bntk1sfo\log\nnictl_stdout.log does not exist!
stderr:
ERROR: C:\Users\suntao\nni-experiments\bntk1sfo\log\nnictl_stderr.log does not exist!

**How to reproduce it?**:

**Comment by matluster** [comment]
Looks like named pipe doesn't work in your env.

To debug, please verify whether `examples/trials/mnist-pytorch` works in your environment. (You can launch the experiment with nnictl.)

Believe it or not, the easiest way out is to try another env:

* If you are using Conda, try pip.
* If you are using Windows, try WSL.
* If you are using Mac, try Linux.

**Comment by ultmaster** [comment]
Closing as the named pipe has been replaced with websocket since v2.8.
