### ISSUE TITLE
Retiarii Experiment running on remote training service

### ISSUE THREAD

**Issue by lrlofgren** [microsoft/nni#4791]
I am trying to configure a Retiarri experiment to run remotely. However, I am having a hard time understanding how to configure the experiment. I was wondering if there are any examples of how to specify the host, ssh key path, etc.? Thanks

**Comment by matluster** [comment]
It's same as HPO experiment. You should probably figure out how to configure an HPO experiment with `Experiment` API, and use that experience for remote.

We will note that there's a request for remote example in Retiarii.

**Comment by lrlofgren** [comment]
I also found this example from the documentation

experiment = Experiment('remote')
experiment.config.trial_command = 'python3 trial.py'
experiment.config.machines.append(RemoteMachineConfig(ip=..., user_name=...))
...
experiment.run(8080)

however, when I try to use this example I get the error - Traceback (most recent call last):
  File "D:\machine_learning\LinuxRemote_Windows\NAS_V2.py", line 335, in <module>
    experiment.config.machineList.append(RemoteMachineConfig(ip='155.98.111.50', user_name='lofgren', ssh_key_file='D:\machine_learning\.ssh\id_rsa'))
AttributeError: 'NoneType' object has no attribute 'machineList'

Thanks.

**Comment by lrlofgren** [comment]
Here is what I have so far... but I cannot figure out how/where to specify the machine list 

if __name__ == '__main__':

    base_model = Net()
    search_strategy = strategy.GridSearch()
    model_evaluator = FunctionalEvaluator(evaluate_model)

    exp = RetiariiExperiment(base_model, model_evaluator, [], search_strategy)
    exp_config = RetiariiExeConfig()
    exp_config.experiment_name = 'Remote - Trial 1'
    exp_config.trial_concurrency = 1
    exp_config.nni_manager_ip = '10.16.84.194'
    exp_config.trial_gpu_number = 1
    exp.run(exp_config, 8082)

any help would be appreciated.

**Comment by lrlofgren** [comment]
Have tried several different things... but it appears I am stuck. Any help or guidance would be appreciated. thanks,

**Comment by lrlofgren** [comment]
I apologize, I must have modified my code before adding it to the comment. I have done what you have included and still does not fix the problem.

**Comment by matluster** [comment]
I found that there is, actually, an example here:

https://github.com/microsoft/nni/blob/master/test/retiarii_test/cgo_mnasnet/test.py

**Comment by lrlofgren** [comment]
Thank you.. this was very helpful. 

When I run the experiment I am now getting a 500 server error (shown below) and I am trying to figure out where I am going wrong. Any help would be appreciated.

[2022-05-10 10:27:20] INFO (numexpr.utils/MainThread) NumExpr defaulting to 8 threads.
[2022-05-10 10:27:26] INFO (nni.experiment/MainThread) Creating experiment, Experiment ID: t2xhugv8
[2022-05-10 10:27:26] INFO (nni.experiment/MainThread) Connecting IPC pipe...
[2022-05-10 10:27:27] INFO (nni.experiment/MainThread) Starting web server...
[2022-05-10 10:27:29] INFO (nni.experiment/MainThread) Setting up...
[2022-05-10 10:27:33] ERROR (nni.experiment.rest/MainThread) rest request POST http://localhost:8081/api/v1/nni/experiment failed: 500 {"error":"Too many files and directories (2001 already scanned) in D:\\, please check if i[2022-05-10 10:27:33] ERROR (nni.experiment/MainThread) Create experiment failed
Traceback (most recent call last):
  File "d:\machine_learning\LinuxRemote_Windows\NAS_Remote.py", line 358, in <module>
    exp.run(exp_config, 8081)
  File "C:\Users\u0736288\.conda\envs\spyder\lib\site-packages\nni\retiarii\experiment\pytorch.py", line 309, in run
    self.start(port, debug)
  File "C:\Users\u0736288\.conda\envs\spyder\lib\site-packages\nni\retiarii\experiment\pytorch.py", line 258, in start
    self._proc, self._pipe = launcher.start_experiment_retiarii(self.id, self.config, port, debug)
  File "C:\Users\u0736288\.conda\envs\spyder\lib\site-packages\nni\experiment\launcher.py", line 184, in start_experiment_retiarii
    raise e
  File "C:\Users\u0736288\.conda\envs\spyder\lib\site-packages\nni\experiment\launcher.py", line 173, in start_experiment_retiarii
    rest.post(port, '/experiment', config.json())
  File "C:\Users\u0736288\.conda\envs\spyder\lib\site-packages\nni\experiment\rest.py", line 38, in post
    return request('post', port, api, data, prefix=prefix)
  File "C:\Users\u0736288\.conda\envs\spyder\lib\site-packages\nni\experiment\rest.py", line 29, in request
    resp.raise_for_status()
  File "C:\Users\u0736288\.conda\envs\spyder\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8081/api/v1/nni/experiment

**Comment by matluster** [comment]
Please be aware that there is an ignore file you can set to avoid too many files being uploaded.

Doc: https://nni.readthedocs.io/en/stable/experiment/training_service/remote.html

**Comment by lrlofgren** [comment]
Got it. that fixed that issue... now I am getting another error that I can't seem to understand. 


Traceback (most recent call last): 
  File "/usr/local/stow/python/amd64_linux26/python-3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/stow/python/amd64_linux26/python-3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lofgren/.local/lib/python3.9/site-packages/nni/retiarii/trial_entry.py", line 28, in <module>
    engine.trial_execute_graph()
  File "/home/lofgren/.local/lib/python3.9/site-packages/nni/retiarii/execution/python.py", line 57, in trial_execute_graph
    graph_data = PythonGraphData.load(receive_trial_parameters())
  File "/home/lofgren/.local/lib/python3.9/site-packages/nni/retiarii/integration_api.py", line 39, in receive_trial_parameters
    params = nni.get_next_parameter()
  File "/home/lofgren/.local/lib/python3.9/site-packages/nni/trial.py", line 40, in get_next_parameter
    _params = platform.get_next_parameter()
  File "/home/lofgren/.local/lib/python3.9/site-packages/nni/runtime/platform/local.py", line 56, in get_next_parameter
    params = load(fp=params_file)
  File "/home/lofgren/.local/lib/python3.9/site-packages/nni/common/serializer.py", line 352, in load
    return json_tricks.load(fp, obj_pairs_hooks=hooks, **json_tricks_kwargs)
  File "/home/lofgren/.local/lib/python3.9/site-packages/json_tricks/nonp.py", line 266, in load
    return loads(string, preserve_order=preserve_order, ignore_comments=ignore_comments, decompression=decompression,
  File "/home/lofgren/.local/lib/python3.9/site-packages/json_tricks/nonp.py", line 236, in loads
    return json_loads(string, object_pairs_hook=hook, **jsonkwargs)
  File "/usr/local/stow/python/amd64_linux26/python-3.9/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/local/stow/python/amd64_linux26/python-3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/stow/python/amd64_linux26/python-3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/lofgren/.local/lib/python3.9/site-packages/json_tricks/decoders.py", line 44, in __call__
    map = hook(map, properties=self.properties)
  File "/home/lofgren/.local/lib/python3.9/site-packages/json_tricks/utils.py", line 66, in wrapper
    return encoder(*args, **{k: v for k, v in kwargs.items() if k in names})
  File "/home/lofgren/.local/lib/python3.9/site-packages/nni/common/serializer.py", line 550, in _json_tricks_func_or_cls_decode
    return import_cls_or_func_from_hybrid_name(s)
  File "/home/lofgren/.local/lib/python3.9/site-packages/nni/common/serializer.py", line 531, in import_cls_or_func_from_hybrid_name
    return cloudpickle.loads(b)
  File "/home/lofgren/.local/lib/python3.9/site-packages/cloudpickle/cloudpickle.py", line 679, in subimport
    __import__(name)
ModuleNotFoundError: No module named 'torch.cpu'

I am able to run other NNI experiments on this machine so I know that I have pytorch installed...

**Comment by lrlofgren** [comment]
Well, I succesfully fixed the previous problem by updating pytorch.

However,  now when I start an experiment it will run the first trial succesfully but I get an error after the first trial is complete: 
[2022-05-10 16:24:48] INFO (root/MainThread) Successfully update searchSpace.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\u0736288\.conda\envs\spyder\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\u0736288\.conda\envs\spyder\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\u0736288\.conda\envs\spyder\lib\site-packages\nni\runtime\msg_dispatcher_base.py", line 51, in run
    command, data = receive()
  File "C:\Users\u0736288\.conda\envs\spyder\lib\site-packages\nni\runtime\protocol.py", line 61, in receive
    header = _in_file.read(16)
OSError: [Errno 22] Invalid argument

any ideas?

**Comment by matluster** [comment]
We've seen such reports of pipe error on Windows, e.g., #4766. Unfortunately, there has been no clue over what could have happened. The problem can't be reproduced on POSIX platform.

**Comment by lrlofgren** [comment]
Thanks for the feedback. Switched over to a linux system that seems to correct the problem. But I am now running into this error... 
[libprotobuf FATAL google/protobuf/stubs/common.cc87] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.3). Contact the program author for an update. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".) 

any ideas on what is causing this??

**Comment by ultmaster** [comment]
Maybe uninstall tensorflow could help?

**Comment by lrlofgren** [comment]
uninstalling tensorflow and changes versions of different packages solved the problem. 

thanks.
