### ISSUE TITLE
Error: Dispatcher stream error, tuner may have crashed.

### ISSUE THREAD

**Issue by redLinmumu** [microsoft/nni#4799]
**Describe the issue**: 
When I run in pycharm, it crashes all the time immediately. We do not know why.

- Log is 

```
[2022-04-24 19:49:06] Creating experiment, Experiment ID: mfk49db5
[2022-04-24 19:49:06] Starting web server...
[2022-04-24 19:49:06] (urllib3.connectionpool) Starting new HTTP connection (1): localhost:8080
[2022-04-24 19:49:07] (urllib3.connectionpool) Starting new HTTP connection (1): localhost:8080
[2022-04-24 19:49:07] (urllib3.connectionpool) http://localhost:8080 "GET /api/v1/nni/check-status HTTP/1.1" 200 36
[2022-04-24 19:49:07] Setting up...
[2022-04-24 19:49:07] (urllib3.connectionpool) Starting new HTTP connection (1): localhost:8080
[2022-04-24 19:49:08] (urllib3.connectionpool) http://localhost:8080 "POST /api/v1/nni/experiment HTTP/1.1" 200 28

/usr/bin/python3: No module named nni
Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.<anonymous> (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/core/nnimanager.js:651:32)
    at EventEmitter.emit (node:events:390:28)
    at Socket.<anonymous> (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/core/ipcInterface.js:70:72)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

- Our config is as follows:

```python
search_space = {"iters": {"_type": "choice", "_value": [4, 6, 8, 10, 12, 14]},
                "lr": {"_type": "loguniform", "_value": [1e-6, 2e-4]},
                "gamma": {"_type": "quniform", "_value": [800, 1400, 50]}}

experiment = Experiment('local')
experiment.config.experiment_name = "ot_orl"
experiment.config.trial_command = 'python main.py --loss_fn L2 --epochs 300 --alpha 0 --data orl'

experiment.config.trial_code_directory = '..'
experiment.config.experiment_working_directory = '../log'
experiment.config.search_space = search_space

experiment.config.tuner.name = 'TPE'
experiment.config.tuner.class_args['optimize_mode'] = 'maximize'

experiment.config.max_trial_number = 300
experiment.config.trial_concurrency = 1

experiment.run(8080,debug=True)
```

Environment:

NNI version: 2.7
NNI mode (local|remote|pai): local
Client OS: Ubuntu 18.04
Server OS (for remote mode only):
Python version: 3.9
PyTorch/TensorFlow version: Pytorch 1.9
Is conda/virtualenv/venv used?: Anaconda
Is running in Docker?: No
Log message:

**nnimanager.log:**
```
[2022-04-24 19:37:33] INFO (nni.experiment/MainThread) Creating experiment, Experiment ID: ^[[36mzailfnmp^[[0m
[2022-04-24 19:37:33] INFO (nni.experiment/MainThread) Starting web server...
[2022-04-24 19:37:33] DEBUG (urllib3.connectionpool/MainThread) Starting new HTTP connection (1): localhost:8080
[2022-04-24 19:37:34] DEBUG (urllib3.connectionpool/MainThread) Starting new HTTP connection (1): localhost:8080
[2022-04-24 19:37:34] DEBUG (urllib3.connectionpool/MainThread) http://localhost:8080 "GET /api/v1/nni/check-status HTTP/1.1" 200 36
[2022-04-24 19:37:34] INFO (nni.experiment/MainThread) Setting up...
[2022-04-24 19:37:34] DEBUG (urllib3.connectionpool/MainThread) Starting new HTTP connection (1): localhost:8080
[2022-04-24 19:37:34] DEBUG (urllib3.connectionpool/MainThread) http://localhost:8080 "POST /api/v1/nni/experiment HTTP/1.1" 200 28
[2022-04-24 19:37:34] INFO (nni.experiment/MainThread) Web portal URLs: ^[[36mhttp://127.0.0.1:8080 http://183.174.229.150:8080^[[0m
[2022-04-24 19:37:44] DEBUG (urllib3.connectionpool/MainThread) Starting new HTTP connection (1): localhost:8080
[2022-04-24 19:37:44] DEBUG (urllib3.connectionpool/MainThread) http://localhost:8080 "GET /api/v1/nni/check-status HTTP/1.1" 200 80
[2022-04-24 19:37:44] INFO (nni.experiment/MainThread) Stopping experiment, please wait...
```

**dispatcher.log:**
```
2022-04-24 19:37:33] DEBUG (main) start() returned.
[2022-04-24 19:37:34] DEBUG (NNIRestHandler) GET: /check-status: body: {}
[2022-04-24 19:37:34] DEBUG (NNIRestHandler) POST: /experiment: body: {
  experimentName: 'ot_orl',
  searchSpace: {
    iters: { _type: 'choice', _value: [Array] },
    lr: { _type: 'loguniform', _value: [Array] },
    gamma: { _type: 'quniform', _value: [Array] }
  },
  trialCommand: 'python main.py --loss_fn L2 --epochs 300 --alpha 0 --data orl',
  trialCodeDirectory: '/home/fengjiao_gong/code/mvc',
  trialConcurrency: 1,
  maxTrialNumber: 300,
  useAnnotation: false,
  debug: false,
  logLevel: 'info',
  experimentWorkingDirectory: '/home/fengjiao_gong/code/mvc/log',
  tuner: { name: 'TPE', classArgs: { optimize_mode: 'maximize' } },
  trainingService: {
    platform: 'local',
    trialCommand: 'python main.py --loss_fn L2 --epochs 300 --alpha 0 --data orl',
    trialCodeDirectory: '/home/fengjiao_gong/code/mvc',
    debug: false,
    maxTrialNumberPerGpu: 1,
    reuseMode: false
  }
}
[2022-04-24 19:37:34] INFO (NNIManager) Starting experiment: zailfnmp
[2022-04-24 19:37:34] INFO (NNIManager) Setup training service...
[2022-04-24 19:37:34] INFO (LocalTrainingService) Construct local machine training service.
[2022-04-24 19:37:34] INFO (NNIManager) Setup tuner...
[2022-04-24 19:37:34] DEBUG (NNIManager) dispatcher command: python3 -m nni --exp_params eyJleHBlcmltZW50TmFtZSI6Im90X29ybCIsInRyaWFsQ29tbWFuZCI6InB5dGhvbiBtYWluLnB5IC0tbG9zc19mbiBMMiAtLWVwb2NocyAzMDAgLS1hbHBoYSAwIC0tZGF0YSBvcmwiLCJ0cmlhbENvZGVEaXJlY3RvcnkiOiIvaG9tZS9mZW5namlhb19nb25nL2NvZGUvbXZjIiwidHJpYWxDb25jdXJyZW5jeSI6MSwibWF4VHJpYWxOdW1iZXIiOjMwMCwidXNlQW5ub3RhdGlvbiI6ZmFsc2UsImRlYnVnIjpmYWxzZSwibG9nTGV2ZWwiOiJpbmZvIiwiZXhwZXJpbWVudFdvcmtpbmdEaXJlY3RvcnkiOiIvaG9tZS9mZW5namlhb19nb25nL2NvZGUvbXZjL2xvZyIsInR1bmVyIjp7Im5hbWUiOiJUUEUiLCJjbGFzc0FyZ3MiOnsib3B0aW1pemVfbW9kZSI6Im1heGltaXplIn19LCJ0cmFpbmluZ1NlcnZpY2UiOnsicGxhdGZvcm0iOiJsb2NhbCIsInRyaWFsQ29tbWFuZCI6InB5dGhvbiBtYWluLnB5IC0tbG9zc19mbiBMMiAtLWVwb2NocyAzMDAgLS1hbHBoYSAwIC0tZGF0YSBvcmwiLCJ0cmlhbENvZGVEaXJlY3RvcnkiOiIvaG9tZS9mZW5namlhb19nb25nL2NvZGUvbXZjIiwiZGVidWciOmZhbHNlLCJtYXhUcmlhbE51bWJlclBlckdwdSI6MSwicmV1c2VNb2RlIjpmYWxzZX19
[2022-04-24 19:37:34] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2022-04-24 19:37:34] INFO (NNIManager) Add event listeners
[2022-04-24 19:37:34] DEBUG (NNIManager) Send tuner command: INITIALIZE: [object Object]
[2022-04-24 19:37:34] DEBUG (IpcInterface) ipcInterface command type: [IN], content:[{"iters":{"_type":"choice","_value":[4,6,8,10,12,14]},"lr":{"_type":"loguniform","_value":[0.000001,0.0002]},"gamma":{"_type":"quniform","_value":[800,1400,50]}}]
[2022-04-24 19:37:34] DEBUG (IpcInterface) ipcInterface command type: [PI], content:[]
[2022-04-24 19:37:34] INFO (LocalTrainingService) Run local machine training service.
[2022-04-24 19:37:34] ERROR (NNIManager) Dispatcher error: read ECONNRESET
[2022-04-24 19:37:34] ERROR (NNIManager) Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.<anonymous> (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/core/nnimanager.js:651:32)
    at EventEmitter.emit (node:events:390:28)
    at Socket.<anonymous> (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/core/ipcInterface.js:70:72)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-04-24 19:37:34] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR
[2022-04-24 19:37:44] DEBUG (NNIRestHandler) GET: /check-status: body: {}
[2022-04-24 19:37:44] DEBUG (NNIRestHandler) DELETE: /experiment: body: {}
[2022-04-24 19:37:44] INFO (NNIManager) Change NNIManager status from: ERROR to: STOPPING
[2022-04-24 19:37:44] INFO (NNIManager) Stopping experiment, cleaning up ...
[2022-04-24 19:37:44] DEBUG (IpcInterface) ipcInterface command type: [TE], content:[]
[2022-04-24 19:37:44] WARNING (IpcInterface) Commands jammed in buffer!
[2022-04-24 19:37:44] INFO (LocalTrainingService) Stopping local machine training service...
[2022-04-24 19:37:44] INFO (NNIManager) Change NNIManager status from: STOPPING to: STOPPED
[2022-04-24 19:37:44] INFO (NNIManager) Experiment stopped.
[2022-04-24 19:37:44] DEBUG (NNIExperimentsManager) Stopping experiment manager.
[2022-04-24 19:37:44] DEBUG (NNIExperimentsManager) Experiment manager: all clean up
[2022-04-24 19:37:44] DEBUG (NNIExperimentsManager) Experiment manager stopped.
[2022-04-24 19:37:44] INFO (NNITensorboardManager) Forced stopping all tensorboard task.
[2022-04-24 19:37:44] INFO (NNITensorboardManager) All tensorboard task stopped.
[2022-04-24 19:37:44] INFO (NNITensorboardManager) Tensorboard manager stopped.
[2022-04-24 19:37:44] ERROR (NNIManager) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at new RestServer (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/rest_server/index.js:50:37)
    at Object.get (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/node_modules/typescript-ioc/es5.js:202:108)
    at SingletonScope.resolve (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/node_modules/typescript-ioc/es5.js:290:33)
    at ConfigImpl.getInstance (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/node_modules/typescript-ioc/es5.js:252:30)
    at Function.IoCContainer.get (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/node_modules/typescript-ioc/es5.js:147:23)
    at Function.Container.get (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/node_modules/typescript-ioc/es5.js:93:29)
    at Object.get (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/common/component.js:33:26)
```
 

**How to reproduce it?**:
Everytime I press run button in Pycharm
So how I should solve this issue?

**Comment by liuzhe-lz** [comment]
The error is here:
```
/usr/bin/python3: No module named nni
```

Seems your `python` and `python3` link to different environments, and NNI incorrectly used `python3` to launch the tuner.
Can you link `python3` to `python` in your environment?

**Comment by redLinmumu** [comment]
I do not know how? Do you have the config option? I have not found it. At the same time, another machine that has this error message works just fine. So I kind of ignore this error at first time. Thank you for helping.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月25日 00:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [microsoft/nni] Error: Dispatcher stream error, tuner may have crashed. (Issue #4799) |

The error is here:

/usr/bin/python3: No module named nni


Seems your python and python3 link to different environments, and NNI incorrectly used python3 to launch the tuner.
Can you link python3 to python in your environment?

**Comment by redLinmumu** [comment]
> The error is here:
> 
> ```
> /usr/bin/python3: No module named nni
> ```
> 
> Seems your `python` and `python3` point to different environments, and NNI incorrectly used `python3` to launch the tuner. Can you link `python3` to `python` in your environment?

I have done the link in my environment, but still it crashed as before. Messages below:

rror: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.<anonymous> (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/core/nnimanager.js:651:32)
    at EventEmitter.emit (node:events:390:28)
    at Socket.<anonymous> (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/core/ipcInterface.js:70:72)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-04-25 09:59:06] (urllib3.connectionpool) Starting new HTTP connection (1): localhost:8080
[2022-04-25 09:59:06] (urllib3.connectionpool) http://localhost:8080 "GET /api/v1/nni/check-status HTTP/1.1" 200 80
[2022-04-25 09:59:06] Stopping experiment, please wait...
[2022-04-25 09:59:06] (urllib3.connectionpool) Starting new HTTP connection (1): localhost:8080
[2022-04-25 09:59:06] (urllib3.connectionpool) http://localhost:8080 "DELETE /api/v1/nni/experiment HTTP/1.1" 200 0
[2022-04-25 09:59:06] Experiment stopped

**Comment by redLinmumu** [comment]
> The error is here:
> 
> ```
> /usr/bin/python3: No module named nni
> ```
> 
> Seems your `python` and `python3` point to different environments, and NNI incorrectly used `python3` to launch the tuner. Can you link `python3` to `python` in your environment?

I have changed the link to python3 on the Linux server(since I use the python interpreter on the server), but nni still uses the old python and I do not know how to change the python version that nni actually uses. 


Here is the latest log just as before:

`/usr/bin/python3: No module named nni
Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.<anonymous> (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/core/nnimanager.js:651:32)
    at EventEmitter.emit (node:events:390:28)
    at Socket.<anonymous> (/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/core/ipcInterface.js:70:72)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-04-25 10:53:27] (urllib3.connectionpool) Starting new HTTP connection (1): localhost:8080
[2022-04-25 10:53:27] (urllib3.connectionpool) http://localhost:8080 "GET /api/v1/nni/check-status HTTP/1.1" 200 80
[2022-04-25 10:53:27] Stopping experiment, please wait...
[2022-04-25 10:53:27] (urllib3.connectionpool) Starting new HTTP connection (1): localhost:8080
[2022-04-25 10:53:27] (urllib3.connectionpool) http://localhost:8080 "DELETE /api/v1/nni/experiment HTTP/1.1" 200 0
[2022-04-25 10:53:27] Experiment stopped`



So could you tell me how to change the python version NNI uses? How should I config it? Thanks a lot!

**Comment by liuzhe-lz** [comment]
Or maybe you can install NNI in both environments.
```
python3 -m pip install nni
```

**Comment by liuzhe-lz** [comment]
The interpreter used by NNI is hard-coded in JavaScript code.
If you want to edit the code, it's in `/home/fengjiao_gong/anaconda3/envs/pytorch190_new/lib/python3.9/site-packages/nni_node/common/utils.js`, `getCmdPy()` function.

**Comment by redLinmumu** [comment]
> It works! I run the following in server's command line and the crash disappeared. I think in this case, nni uses specified default python to startup. And I only need to config my expected python in the config  `experiment.config.trial_command =` option. 

`/usr/bin/python3 -m pip install nni`

This helps a lot! Thank you very much!

**Comment by Wenuka** [comment]
For me the answer in[ this discussion](https://github.com/microsoft/nni/discussions/3797) worked. Just commenting here as it can be useful. 
In short I just had to update the`scikit-learn (`pip install scikit-learn  -U`). More info can be found [here](https://stackoverflow.com/questions/65682019/attributeerror-str-object-has-no-attribute-decode-in-fitting-logistic-regre).
