### ISSUE TITLE
TPE tuner failed to load old JSON results !

### ISSUE THREAD

**Issue by nico-zck** [microsoft/nni#4804]
**Describe the issue**:
When I try to import old results to new experiment with the same configuration. It will show the follow problem:
>[2022-04-22 13:55:57] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2022-04-25 18:59:12] ERROR (nni.runtime.msg_dispatcher_base/Thread-1) bad operand type for unary -: 'collections.OrderedDict'
Traceback (most recent call last):
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/nni/runtime/msg_dispatcher_base.py", line 88, in command_queue_worker
    self.process_command(command, data)
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/nni/runtime/msg_dispatcher_base.py", line 147, in process_command
    command_handlers[command](data)
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/nni/runtime/msg_dispatcher.py", line 120, in handle_import_data
    self.tuner.import_data(data)
  File "/home/xxx/anaconda3/lib/python3.9/site-packages/nni/algorithms/hpo/tpe_tuner.py", line 208, in import_data
    loss = -trial['value']
TypeError: bad operand type for unary -: 'collections.OrderedDict'
[2022-04-25 18:59:17] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2022-04-25 18:59:18] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated

**The Reason**

In official [docs](https://nni.readthedocs.io/en/stable/reference/nnictl.html#nnictl-experiment-import), there is a description:
>`value` should follow the same rule of the input in `nni.report_final_result`, that is, either a number or a dict with a key named `default`.

The exported JSON did show that value could be a dictionary like: `"value": "{\"acc\": 0.5, \"f1\": 0.5,  \"default\": 0.5}"`

However, codes of tpe_tuner in nni is [that](https://github.com/microsoft/nni/blob/refs/tags/v2.7/nni/algorithms/hpo/tpe_tuner.py#L208)
```python
    def import_data(self, data):  # for resuming experiment
        for trial in data:
            param = format_parameters(trial['parameter'], self.space)
            loss = trial['value']
            if self.optimize_mode is OptimizeMode.Maximize:
                loss = -trial['value']
            for key, value in param.items():
                self._history[key].append(Record(value, loss))
        _logger.info(f'Replayed {len(data)} trials')
```
It's apparently that a TPE tuner with maximum mode cannot process a dict "value"!

**Comment by liuzhe-lz** [comment]
For a quick fix you can use a script to reformat the exported JSON file:
```python
import json
metrics = json.load(open('metrics.json'))
for metric in metrics:
    metric['value'] = json.loads(metric['value'])['default']
json.dump(metrics, 'metrics-new.json')
```

Sorry for the inconvenience.
