### ISSUE TITLE
Alternative for using ValueChoice as a boolean

### ISSUE THREAD

**Issue by SimonHuesgen** [microsoft/nni#4819]
**Describe the issue**:
Hello there,

Here I am trying to define a search space using nni v2.7 and I came across a concern.
It happened multiple times that I wanted to define mutations using a ValueChoice object and followingly using it in an if-else-clause. This throws an error every time, saying this is not the intended use of ValueChoice.
One simplified example would be the choice of using BatchNormalization; I attempted:
'''
bn_choice = nn.ValueChoice([0,1], label="bn_choice")
if bn_choice==1:
     self.bn = nn.BatchNorm2d(128)
'''
in init
and
'''
if self.bn:
     x = self.bn(x)
'''
in forward

Is there an alternative way to define this?

Thanks in advance!

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by SimonHuesgen** [comment]
Thanks for the quick reply!
Using the condition to turn a ValueChoice Object to a bool object throws an error: keyword can't be an expression. 

Using LayerChoice works for one layer, but it does not seem to work as a decision for multiple layers. What I mean is, that I want a binary choice which decides for multiple layers in the network if it will use BatchNorm or Identity. So I thought to try using the same label:
self.layer3 = nn.LayerChoice([nn.BatchNorm2d(64),nn.Identity()], label="bn_choice")
self.layer6 = nn.LayerChoice([nn.BatchNorm2d(128),nn.Identity()], label="bn_choice")
but when test running experiments the trials fail immediately...

Any other ideas?

**Comment by matluster** [comment]
> keyword can't be an expression.

I need more traceback on this error.

> but when test running experiments the trials fail immediately...

I need stderr and trial's log for the failed trials.

**Comment by matluster** [comment]
> and later using bool_bn_choice in if-else still throws:

You should never use if-else branch. ValueChoice.condition works like [tf.cond](https://www.tensorflow.org/api_docs/python/tf/cond). You need to write something like:

```python
branch_a = nn.Sequential(..., ...)
branch_b = nn.Sequential(..., ..., BN)
self.block = nn.ValueChoice.condition(nn.ValueChoice([False, True], branch_a, branch_b)
```

I don't know whether putting modules into `nn.ValueChoice.condition` works, but you can try.

> RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of dimension: 1

Your output is a one-dimensional tensor, but you are trying to use `pl.Classification`, if my guess is correct. Classification doesn't work like this.

> Are there any larger examples (with more variety in possibilities of how to use different mutator functions) for search spaces than the example notebooks?

There is a [space hub](https://github.com/microsoft/nni/tree/master/nni/retiarii/hub) here. But it's in a preview state.

**Comment by SimonHuesgen** [comment]
Thanks for all the help.

Trying to use it like this:
branch_a = nn.Sequential(nn.Conv2d(64, 128, 3, stride=1,padding=1),nn.ReLU(),nn.MaxPool2d(2, 2))
branch_b = nn.Sequential(nn.Conv2d(64, 128, 3, stride=1,padding=1),nn.ReLU(),nn.BatchNorm2d(128),nn.MaxPool2d(2, 2))
self.block = nn.ValueChoice.condition(nn.ValueChoice([False, True], branch_a, branch_b))

throws:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-8cb293112ce7> in <module>
    119 
    120 
--> 121 model = Net()

~/opt/anaconda3/lib/python3.7/site-packages/nni/retiarii/serializer.py in __init__(self, *args, **kwargs)
    123             self._model_namespace = ModelNamespace()
    124             with self._model_namespace:
--> 125                 super().__init__(*args, **kwargs)
    126 
    127     _copy_class_wrapper_attributes(wrapper, reset_wrapper)

~/opt/anaconda3/lib/python3.7/site-packages/nni/common/serializer.py in new_init(self, *args, **kwargs)
    429                     self,
    430                     *[_argument_processor(arg) for arg in args],
--> 431                     **{kw: _argument_processor(arg) for kw, arg in kwargs.items()}
    432                 )
    433                 inject_trace_info(self, base, args, kwargs)

<ipython-input-6-8cb293112ce7> in __init__(self)
    104         branch_a = nn.Sequential(nn.Conv2d(64, 128, 3, stride=1,padding=1),nn.ReLU(),nn.MaxPool2d(2, 2))
    105         branch_b = nn.Sequential(nn.Conv2d(64, 128, 3, stride=1,padding=1),nn.ReLU(),nn.BatchNorm2d(128),nn.MaxPool2d(2, 2))
--> 106         self.block = nn.ValueChoice.condition(nn.ValueChoice([False, True], branch_a, branch_b))
    107         self.conv1 = nn.Conv2d(3, 64, 3, stride=1,padding=1)
    108         self.conv2 = nn.Conv2d(128, 256, 3, stride=1,padding=1)

~/opt/anaconda3/lib/python3.7/site-packages/nni/retiarii/nn/pytorch/mutation_utils.py in __new__(cls, *args, **kwargs)
     22 
     23         try:
---> 24             return cls.create_fixed_module(*args, **kwargs)
     25         except NoContextError:
     26             return super().__new__(cls)

TypeError: create_fixed_module() takes 2 positional arguments but 4 were given

Another related question:
I am aware that in the documentation for ValueChoice it is specified that you can not use it in a for i in range(ValueChoice) way because it is a 'syntax sugar'. Is there an alternative to this?
Specifically I want the search space to have a number of blocks to choose from (like in ResNets or NasNet) but use different number and sequences of them. A way I thought I could make that happen is by using for i in range(ValueChoice[1,2,3,4]) and then add blocks accordingly... Is there a way to achieve what I just described?

PS: Are there any large search spaces already defined for CIFAR-10 I could use (with the TPE strategy)?

**Comment by SimonHuesgen** [comment]
Also, do you have any idea why this model:
class ReLUConvBN(nn.Sequential):
    def __init__(self, in_size, out_size, kernel_size, stride, padding):
        super().__init__(
            nn.ReLU(),
            nn.Conv2d(in_size, out_size, kernel_size, stride=stride,padding=padding),
            nn.BatchNorm2d(out_size))
class ReLUConv(nn.Sequential):
    def __init__(self, in_size, out_size, kernel_size, stride, padding):
        super().__init__(
            nn.ReLU(),
            nn.Conv2d(in_size, out_size, kernel_size, stride=stride,padding=padding))

@model_wrapper
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.block = nn.LayerChoice([ReLUConvBN(64,128,3,1,1),ReLUConv(64,128,3,1,1)])
        self.conv1 = nn.Conv2d(3, 64, 3, stride=1,padding=1)
        self.conv2 = nn.Conv2d(128, 256, 3, stride=1,padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(256*8*8,120)
        self.fc2 = nn.Linear(120,10)
        
    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = self.pool(x)
        x = self.block(x)
        x = self.pool(x)
        x = F.relu(self.conv2(x))
        x = self.fc1(x)
        x = self.fc2(x)
        return x

    
model = Net()

throws this error in stderr:

/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py:133: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  f"The dataloader, {name}, does not have many workers which may be a bottleneck."
Traceback (most recent call last):
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/nni/retiarii/trial_entry.py", line 28, in <module>
    engine.trial_execute_graph()
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/nni/retiarii/execution/base.py", line 146, in trial_execute_graph
    graph_data.evaluator._execute(model_cls)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/nni/retiarii/evaluator/pytorch/lightning.py", line 119, in _execute
    return self.fit(model_cls)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/nni/retiarii/evaluator/pytorch/lightning.py", line 148, in fit
    return self.trainer.fit(self.module, self.train_dataloader, self.val_dataloaders)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1311, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1375, in _run_sanity_check
    self._evaluation_loop.run()
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 122, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 217, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 239, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 219, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/nni/retiarii/evaluator/pytorch/lightning.py", line 196, in validation_step
    y_hat = self(x)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/nni/retiarii/evaluator/pytorch/lightning.py", line 182, in forward
    y_hat = self.model(x)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/simonhuesgen/thesis/_generated_model/1HV7IN.py", line 73, in forward
    _fc1 = self._fc1(_relu15)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/simonhuesgen/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (262144x8 and 16384x120)

I checked multiple times and cannot find out why it should end in different matrix shapes...

**Comment by ultmaster** [comment]
Your traceback looks awful. I can barely read. Could you wrap it with markdown syntax?

**Comment by SimonHuesgen** [comment]
I'm sorry this is embarrassing. How do I do that?

**Comment by SimonHuesgen** [comment]
> Your traceback looks awful. I can barely read. Could you wrap it with markdown syntax?

Hope it is better now

**Comment by matluster** [comment]
> nn.ValueChoice.condition(nn.ValueChoice([False, True], branch_a, branch_b))

Probably it should be `nn.ValueChoice.condition(nn.ValueChoice([False, True]), branch_a, branch_b)`

```
if kernel_size==1:
            padding = 0
        elif kernel_size==3:
            padding = 1
```

This is equivalent to:

```python
kernel_size = nn.ValueChoice([1, 3])
padding = kernel_size // 2
```

> for i in range(ValueChoice) way because it is a 'syntax sugar'. Is there an alternative to this?

I think the documentation made it clear that you should use `nn.Repeat`.

> Are there any large search spaces already defined for CIFAR-10 I could use

Have you looked at space hub? Although I had almost no confidence in it...

> But it throws an AssertionError when running a test experiment:

It's probably related to the `layer_size` here. What's your `layer_size` here?

> Is there a way to access the chosen Layer from LayerChoice? e.g. if a future step of the model depends on which layer has been chosen

In the trial, when a layer choice is created, it's just the chosen layer. You can check the layer with `isinstance`.

**Comment by sevenactors** [comment]
maybe you can try "ModelParameterChoice" ,which according to the doc:
"It’s quite similar to [ValueChoice](https://nni.readthedocs.io/en/latest/reference/nas/search_space.html#nni.retiarii.nn.pytorch.ValueChoice), but unlike [ValueChoice](https://nni.readthedocs.io/en/latest/reference/nas/search_space.html#nni.retiarii.nn.pytorch.ValueChoice), it always returns a fixed value, even at the construction of base model.

This makes it highly flexible (e.g., can be used in for-loop, if-condition, as argument of any function)"
