### ISSUE TITLE
nni.compression.pytorch.speedup.error_code.UnBalancedGroupError: The number remained filters in each group is different

### ISSUE THREAD

**Issue by qi657** [microsoft/nni#4864]
**Describe the issue**:
**Cannot speed up depthwise separable convolutions**
[2022-05-16 11:22:40] INFO (nni.compression.pytorch.speedup.compressor/MainThread) replace module (name: _backbone._block2.1._dw_conv.0, op_type: Conv2d)
Traceback (most recent call last):
  File "D:/nni-master/examples/model_compress/pruning/FD_Prune/FD_simulated_prune.py", line 278, in <module>
    pruner.compress()
  File "D:\nni-master\nni\algorithms\compression\v2\pytorch\base\scheduler.py", line 194, in compress
    task_result = self.pruning_one_step(task)
  File "D:\nni-master\nni\algorithms\compression\v2\pytorch\pruning\basic_scheduler.py", line 154, in pruning_one_step
    result = self.pruning_one_step_normal(task)
  File "D:\nni-master\nni\algorithms\compression\v2\pytorch\pruning\basic_scheduler.py", line 77, in pruning_one_step_normal
    ModelSpeedup(compact_model, self.dummy_input, pruner_generated_masks).speedup_model()
  File "D:\nni-master\nni\compression\pytorch\speedup\compressor.py", line 519, in speedup_model
    self.replace_compressed_modules()
  File "D:\nni-master\nni\compression\pytorch\speedup\compressor.py", line 386, in replace_compressed_modules
    self.replace_submodule(unique_name)
  File "D:\nni-master\nni\compression\pytorch\speedup\compressor.py", line 450, in replace_submodule
    leaf_module, auto_infer.get_masks())
  File "D:\nni-master\nni\compression\pytorch\speedup\compress_modules.py", line 14, in <lambda>
    'Conv2d': lambda module, masks: replace_conv2d(module, masks),
  File "D:\nni-master\nni\compression\pytorch\speedup\compress_modules.py", line 376, in replace_conv2d
    raise UnBalancedGroupError()
nni.compression.pytorch.speedup.error_code.UnBalancedGroupError: The number remained filters in each group is different

**Environment**:
- NNI version: 2.7
- Training service (local|remote|pai|aml|etc):local
- Client OS:
- Server OS (for remote mode only):
- Python version:3.7
- PyTorch/TensorFlow version:pytorch 1.10.1
- Is conda/virtualenv/venv used?:yes
- Is running in Docker?:no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by J-shang** [comment]
Hello @qi657 , a pr for your issue is ready, #4873 , you could have a try on this pr.

**Comment by J-shang** [comment]
hello @qi657 ,  a pr will be submitted as soon to fix your issue, we will let you know when it's done.

**Comment by scarlett2018** [comment]
> hello @qi657 , a pr will be submitted as soon to fix your issue, we will let you know when it's done.

@J-shang the fix has released to 2.8, right? shall we close this issue?

**Comment by Triple-L** [comment]
using nni 2.8, still facing the same bug when pruning with SlimmerPruner

**Comment by nnzs9248** [comment]
using nni 2.10, still facing the same bug when pruning

**Comment by vladgo329** [comment]
2.10 the issue is still reproduced for all depthwise convolutions.
