### ISSUE TITLE
Pruning yolox model with [aten::arange/aten::meshgrid/aten::stack] is not Supported!

### ISSUE THREAD

**Issue by qyang1996** [microsoft/nni#4885]
**When I prune YOLOX model I get an error info.**

I need to prune yolox model using torch.arange/torch.meshgrid/torch.stack in yolox_head.

Triggered error during model speed-up phase:
``` 
ERROR (nni.compression.pytorch.speedup.jit_translate/MainThread) aten::arange is not Supported! Please report an issue at https://github.com/microsoft/nni. Thanks~
INFO (nni.compression.pytorch.speedup.compressor/MainThread) Update mask for head.aten::arange.288
ERROR (nni.compression.pytorch.speedup.jit_translate/MainThread) aten::arange is not Supported! Please report an issue at https://github.com/microsoft/nni. Thanks~
INFO (nni.compression.pytorch.speedup.compressor/MainThread) Update mask for backbone.C3_n3.conv3.conv
INFO (nni.compression.pytorch.speedup.compressor/MainThread) Update mask for head.aten::meshgrid.289
ERROR (nni.compression.pytorch.speedup.jit_translate/MainThread) aten::meshgrid is not Supported! Please report an issue at https://github.com/microsoft/nni. Thanks~
INFO (nni.compression.pytorch.speedup.compressor/MainThread) Update mask for backbone.C3_n3.conv3.bn
INFO (nni.compression.pytorch.speedup.compressor/MainThread) Update mask for head.prim::ListUnpack.290
INFO (nni.compression.pytorch.speedup.compressor/MainThread) Update mask for backbone.C3_n3.conv3.act
INFO (nni.compression.pytorch.speedup.compressor/MainThread) Update mask for head.aten::stack.291
ERROR (nni.compression.pytorch.speedup.jit_translate/MainThread) aten::stack is not Supported! Please report an issue at https://github.com/microsoft/nni. Thanks~
INFO (nni.compression.pytorch.speedup.compressor/MainThread) Update mask for backbone.bu_conv1.conv
``` 
**nni Environment :**
- nni version: 2.7
- nni mode(local|pai|remote): local
- OS: Ubuntu 18.04
- python version: 3.8
- is conda or virtualenv used?: YES
- is running in docker?: NO

**Try to modify in jit_translate.py:**
create a fun:
```
def arange_python(node, speedup):
    class arangeModule(torch.nn.Module):
        def forward(self, x):
            return torch.arange(int(x))
    return arangeModule
``` 
and add the maping `'aten::arange': arange_python` in `trans_from_jit_to_python`
but still error:
```
[2022-05-25 10:14:08] INFO (nni.compression.pytorch.speedup.compressor/MainThread) Update mask for head.aten::arange.287
2022-05-25 10:14:08 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (5735), thread 'MainThread' (140500556732224):
Traceback (most recent call last):

  File "/home/yq/pycharm_project/YOLOX-main/tools/prune.py", line 315, in <module>
    launch(
    └ <function launch at 0x7fc7fcfa4280>

> File "/home/yq/pycharm_project/YOLOX-main/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7fc7efe648b0>

  File "/home/yq/pycharm_project/YOLOX-main/tools/prune.py", line 154, in main
    model = prune_main(model, "cuda:0")
            │          └ YOLOX(
            │              (backbone): YOLOPAFPN(
            │                (backbone): CSPDarknet(
            │                  (stem): Focus(
            │                    (conv): BaseConv(
            │                      (conv): ...
            └ <function prune_main at 0x7fc7ef859e50>

  File "/home/yq/pycharm_project/YOLOX-main/tools/prune.py", line 298, in prune_main
    ModelSpeedup(model, torch.rand(1, 3, 640, 640), masks).speedup_model()
    │            │      │     │                     └ {'backbone.backbone.stem.conv.conv': {'weight': tensor([[[[1., 1., 1.],
    │            │      │     │                                 [1., 1., 1.],
    │            │      │     │                                 [1., 1., 1.]],
    │            │      │     │                       
    │            │      │     │                          ...
    │            │      │     └ <built-in method rand of type object at 0x7fc8accc4520>
    │            │      └ <module 'torch' from '/home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/torch/__init__.py'>
    │            └ YOLOX(
    │                (backbone): YOLOPAFPN(
    │                  (backbone): CSPDarknet(
    │                    (stem): Focus(
    │                      (conv): BaseConv(
    │                        (conv): ...
    └ <class 'nni.compression.pytorch.speedup.compressor.ModelSpeedup'>

  File "/home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 512, in speedup_model
    self.infer_modules_masks()
    │    └ <function ModelSpeedup.infer_modules_masks at 0x7fc7e0a6c700>
    └ <nni.compression.pytorch.speedup.compressor.ModelSpeedup object at 0x7fc7c71e93d0>
  File "/home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 355, in infer_modules_masks
    self.update_direct_sparsity(curnode)
    │    │                      └ name: head.aten::arange.287, type: func, op_type: aten::arange, sub_nodes: ['__module.head_aten::arange'], inputs: ['6522'], ...
    │    └ <function ModelSpeedup.update_direct_sparsity at 0x7fc7e0a6c550>
    └ <nni.compression.pytorch.speedup.compressor.ModelSpeedup object at 0x7fc7c71e93d0>
  File "/home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 216, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
                  └ <class 'nni.compression.pytorch.speedup.infer_mask.AutoMaskInference'>
  File "/home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 83, in __init__
    self.output = self.module(*dummy_input)
    │             │    │       └ [80]
    │             │    └ <class 'nni.compression.pytorch.speedup.jit_translate.arange_python.<locals>.arangeModule'>
    │             └ <nni.compression.pytorch.speedup.infer_mask.AutoMaskInference object at 0x7fc7c6decca0>
    └ <nni.compression.pytorch.speedup.infer_mask.AutoMaskInference object at 0x7fc7c6decca0>

TypeError: __init__() takes 1 positional argument but 2 were given

``` 
I don't know how to fix it, hope to get your help :beer:

**Comment by zheng-ningxin** [comment]
Or you can leave the model here, and I'll support the corresponding operators for you, but I still encourage you to have a try and contribute back to NNI, thanks.

**Comment by qyang1996** [comment]
**I'm very sorry, I found out that this is a bug created by me while modifying the nni source code.** 
I RE-installed the nni and only modified the `jit_translate.py`
define the arange_python:
```
def arange_python(node, speedup):
    class arangeModule(torch.nn.Module):
        def forward(self, x):
            print('current input is :', x)
            import pdb;
            pdb.set_trace()
            return torch.arange(int(x))
    return arangeModule()
```
add `'aten::arange': arange_python` in `trans_from_jit_to_python`

The real debug info is as follows:
```
[2022-05-27 16:37:03] INFO (nni.compression.pytorch.speedup.compressor/MainThread) Update mask for head.aten::arange.287
current input is : tensor([80])
> /home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/nni/compression/pytorch/speedup/jit_translate.py(121)forward()
-> return torch.arange(int(x))
(Pdb) x
tensor([80])
(Pdb) continue
current input is : tensor([0])
> /home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/nni/compression/pytorch/speedup/jit_translate.py(121)forward()
-> return torch.arange(int(x))
(Pdb) x
tensor([0])
(Pdb) continue
2022-05-27 16:37:46 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (13614), thread 'MainThread' (139982614955840):
Traceback (most recent call last):

  File "/home/yq/pycharm_project/YOLOX-main/tools/prune.py", line 249, in <module>
    launch(
    └ <function launch at 0x7f4f653dd160>

> File "/home/yq/pycharm_project/YOLOX-main/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f4f5829d790>

  File "/home/yq/pycharm_project/YOLOX-main/tools/prune.py", line 157, in main
    model = prune_main(model, "cuda:0")
            │          └ YOLOX(
            │              (backbone): YOLOPAFPN(
            │                (backbone): CSPDarknet(
            │                  (stem): Focus(
            │                    (conv): BaseConv(
            │                      (conv): ...
            └ <function prune_main at 0x7f4f57c94d30>

  File "/home/yq/pycharm_project/YOLOX-main/tools/prune.py", line 232, in prune_main
    ModelSpeedup(model, torch.rand(1, 3, 640, 640), masks).speedup_model()
    │            │      │     │                     └ {'backbone.backbone.stem.conv.conv': {'weight': tensor([[[[0., 0., 0.],
    │            │      │     │                                 [0., 0., 0.],
    │            │      │     │                                 [0., 0., 0.]],
    │            │      │     │                       
    │            │      │     │                          ...
    │            │      │     └ <built-in method rand of type object at 0x7f50150ff520>
    │            │      └ <module 'torch' from '/home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/torch/__init__.py'>
    │            └ YOLOX(
    │                (backbone): YOLOPAFPN(
    │                  (backbone): CSPDarknet(
    │                    (stem): Focus(
    │                      (conv): BaseConv(
    │                        (conv): ...
    └ <class 'nni.compression.pytorch.speedup.compressor.ModelSpeedup'>

  File "/home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 512, in speedup_model
    self.infer_modules_masks()
    │    └ <function ModelSpeedup.infer_modules_masks at 0x7f4f34ea3670>
    └ <nni.compression.pytorch.speedup.compressor.ModelSpeedup object at 0x7f4f2f685040>
  File "/home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 355, in infer_modules_masks
    self.update_direct_sparsity(curnode)
    │    │                      └ name: head.aten::arange.287, type: func, op_type: aten::arange, sub_nodes: ['__module.head_aten::arange'], inputs: ['6522'], ...
    │    └ <function ModelSpeedup.update_direct_sparsity at 0x7f4f34ea34c0>
    └ <nni.compression.pytorch.speedup.compressor.ModelSpeedup object at 0x7f4f2f685040>
  File "/home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 229, in update_direct_sparsity
    _auto_infer.update_direct_sparsity()
    │           └ <function AutoMaskInference.update_direct_sparsity at 0x7f4f34e8e9d0>
    └ <nni.compression.pytorch.speedup.infer_mask.AutoMaskInference object at 0x7f4f3ef476d0>
  File "/home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 331, in update_direct_sparsity
    out_mask, constant = self.isconstants(out.clone().detach())
    │                    │    │           │   └ <method 'clone' of 'torch._C._TensorBase' objects>
    │                    │    │           └ tensor([], dtype=torch.int64)
    │                    │    └ <function AutoMaskInference.isconstants at 0x7f4f34e8e8b0>
    │                    └ <nni.compression.pytorch.speedup.infer_mask.AutoMaskInference object at 0x7f4f3ef476d0>
    └ None
  File "/home/yq/anaconda3/envs/yolox-py38/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 227, in isconstants
    same = tout[:] == tout[0]
           │          └ tensor([], dtype=torch.int64)
           └ tensor([], dtype=torch.int64)

IndexError: index 0 is out of bounds for dimension 0 with size 0

Process finished with exit code 0
```

It seems to call `arange_python` twice in the `speedup/compressor.py`

Init class `AutoMaskInference` for the first time.
> _auto_infer = AutoMaskInference(func, dummy_input, in_masks, in_constants=in_constants, batch_dim=self.batch_dim)


dummy_input is assigned to `[tensor[0]]` and is called a second time in member function `update_direct_sparsity()`.
> _auto_infer.update_direct_sparsity()

Finally, `arange_python` returns an empty tensor which caused sebsequent errors.

I don't know how to fix it, please help.

**Comment by qyang1996** [comment]
> Or you can leave the model here, and I'll support the corresponding operators for you, but I still encourage you to have a try and contribute back to NNI, thanks.

thank u, I want to try it myself first. &#x270A;

**Comment by scarlett2018** [comment]
Closing the issue as it was discussed as a problem by user's own codes. feel free to reopen or submit a new issue if there are more things to discuss.

**Comment by bl6g6** [comment]
Hi, I met the same problem when I tried to prune YoloX model by L1FilterPruner. 
It reported the following error when it came to ModelSpeedup part.
```
[2022-07-05 03:36:46] ERROR: aten::arange is not Supported! Please report an issue at https://github.com/microsoft/nni. Thanks~
[2022-07-05 03:36:46] Update mask for head.aten::arange.288
[2022-07-05 03:36:46] ERROR: aten::arange is not Supported! Please report an issue at https://github.com/microsoft/nni. Thanks~
[2022-07-05 03:36:46] Update mask for backbone.C3_n3.conv3.conv
[2022-07-05 03:36:46] Update mask for head.aten::meshgrid.289
[2022-07-05 03:36:46] ERROR: aten::meshgrid is not Supported! Please report an issue at https://github.com/microsoft/nni. Thanks~
[2022-07-05 03:36:46] Update mask for backbone.C3_n3.conv3.bn
[2022-07-05 03:36:46] Update mask for head.prim::ListUnpack.290
[2022-07-05 03:36:46] Update mask for backbone.C3_n3.conv3.act
[2022-07-05 03:36:46] Update mask for head.aten::stack.291
[2022-07-05 03:36:46] ERROR: aten::stack is not Supported! Please report an issue at https://github.com/microsoft/nni. Thanks~
[2022-07-05 03:36:46] Update mask for backbone.bu_conv1.conv
[2022-07-05 03:36:46] Update mask for head.stems.1.conv
[2022-07-05 03:36:46] Update mask for head.aten::view.292
[2022-07-05 03:36:46] View Module output size: [1, -1, 2]
2022-07-05 03:36:46 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (31609), thread 'MainThread' (139745318388288):
Traceback (most recent call last):

  File "train.py", line 137, in <module>
    launch(
    └ <function launch at 0x7f17ef41c820>

> File "/AI/home/libing/projects/YOLOX/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7f17df8de790>

  File "train.py", line 122, in main
    trainer.train_pruner()
    │       └ <function Trainer.train_pruner at 0x7f16b015a040>
    └ <yolox.core.trainer.Trainer object at 0x7f16b0160b20>

  File "/AI/home/libing/projects/YOLOX/yolox/core/trainer.py", line 156, in train_pruner
    m_speedup.speedup_model()
    │         └ <function ModelSpeedup.speedup_model at 0x7f17dd0eae50>
    └ <nni.compression.pytorch.speedup.compressor.ModelSpeedup object at 0x7f179b7e6040>

  File "/opt/conda/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 536, in speedup_model
    self.infer_modules_masks()
    │    └ <function ModelSpeedup.infer_modules_masks at 0x7f17dd0eac10>
    └ <nni.compression.pytorch.speedup.compressor.ModelSpeedup object at 0x7f179b7e6040>
  File "/opt/conda/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 371, in infer_modules_masks
    self.update_direct_sparsity(curnode)
    │    │                      └ name: head.aten::view.292, type: func, op_type: aten::view, sub_nodes: ['__module.head_aten::view', '__module.head_prim::List...
    │    └ <function ModelSpeedup.update_direct_sparsity at 0x7f17dd0eaa60>
    └ <nni.compression.pytorch.speedup.compressor.ModelSpeedup object at 0x7f179b7e6040>
  File "/opt/conda/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 231, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
                  └ <class 'nni.compression.pytorch.speedup.infer_mask.AutoMaskInference'>
  File "/opt/conda/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
    │             │    │       └ []
    │             │    └ ViewModule()
    │             └ <nni.compression.pytorch.speedup.infer_mask.AutoMaskInference object at 0x7f178807e400>
    └ <nni.compression.pytorch.speedup.infer_mask.AutoMaskInference object at 0x7f178807e400>
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {}
           │             └ ()
           └ <bound method view_python.<locals>.ViewModule.forward of ViewModule()>
  File "/opt/conda/lib/python3.8/site-packages/nni/compression/pytorch/speedup/jit_translate.py", line 402, in forward
    return args[0].view(self.shape)
           │            │    └ [1, -1, 2]
           │            └ ViewModule()
           └ ()

IndexError: tuple index out of range
```
Have you fixd this issue?
