### ISSUE TITLE
Error: Dispatcher stream error, tuner may have crashed.

### ISSUE THREAD

**Issue by Sunny-Island** [microsoft/nni#4974]
**Describe the issue**:

I have searched previous issue. dispatcher.log reports that **one of the lower bounds is greater than an upper bound**, but my search sapce is:
```
search_space_xgboost = {    'max_depth': {'_type': 'quniform', '_value': [3, 10, 1]},    'gamma': {'_type': 'uniform', '_value': [0,0.2]},
    'min_child_weight': {'_type': 'quniform', '_value': [0,6,1]},    'eta': {'_type': 'uniform', '_value': [0.01,0.3]},}
```

nnimanager.log:
```
[2022-06-29 20:01:19] ERROR (tuner_command_channel.WebSocketChannel) Error: Error: tuner_command_channel: Tuner closed connection    at WebSocket.<anonymous> (/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:41:49)    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:246:10)
    at Socket.socketOnClose (/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:1127:15)    at Socket.emit (node:events:526:28)    at TCP.<anonymous> (node:net:687:12)
[2022-06-29 20:01:19] ERROR (NNIManager) Dispatcher error: tuner_command_channel: Tuner closed connection[2022-06-29 20:01:19] ERROR (NNIManager) Error: Dispatcher stream error, tuner may have crashed.    at EventEmitter.<anonymous> (/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni_node/core/nnimanager.js:647:32)
    at EventEmitter.emit (node:events:526:28)    at WebSocketChannelImpl.handleError (/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:107:22)
    at WebSocket.<anonymous> (/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:41:37)
    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:246:10)    at Socket.socketOnClose (/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:1127:15)
    at Socket.emit (node:events:526:28)
    at TCP.<anonymous> (node:net:687:12)
```

dispatcher.log

```
[2022-06-29 19:49:10] INFO (GP_Tuner_AutoML/Thread-1) Generate paramageters:
 {'eta': 0.12958230031801482, 'gamma': 0.11564555318631864, 'max_depth': 4.0, 'min_child_weight': 5.0}
[2022-06-29 19:59:19] INFO (GP_Tuner_AutoML/Thread-1) Received trial result.
[2022-06-29 19:59:19] INFO (GP_Tuner_AutoML/Thread-1) value :-5.8151080000000005e-05
[2022-06-29 19:59:19] INFO (GP_Tuner_AutoML/Thread-1) parameter : {'eta': 0.15309299834070259, 'gamma': 0.12090782568991532, 'max_depth': 7.0, 'min_child_weight': 2.0}
[2022-06-29 19:59:23] INFO (GP_Tuner_AutoML/Thread-1) Generate paramageters:
 {'eta': 0.1882388227153064, 'gamma': 0.08680526284049686, 'max_depth': 9.0, 'min_child_weight': 0.0}
[2022-06-29 19:59:27] INFO (GP_Tuner_AutoML/Thread-1) Received trial result.
[2022-06-29 19:59:27] INFO (GP_Tuner_AutoML/Thread-1) value :-6.450156e-05
[2022-06-29 19:59:27] INFO (GP_Tuner_AutoML/Thread-1) parameter : {'eta': 0.16262326617089295, 'gamma': 0.1426313405354991, 'max_depth': 3.0, 'min_child_weight': 4.0}
[2022-06-29 19:59:35] ERROR (nni.runtime.msg_dispatcher_base/Thread-1) LBFGSB - one of the lower bounds is greater than an upper bound.
Traceback (most recent call last):
  File "/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni/runtime/msg_dispatcher_base.py", line 97, in command_queue_worker
    self.process_command(command, data)
  File "/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni/runtime/msg_dispatcher_base.py", line 143, in process_command
    command_handlers[command](data)
  File "/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni/runtime/msg_dispatcher.py", line 102, in handle_request_trial_jobs
    params_list = self.tuner.generate_multiple_parameters(ids, st_callback=self.send_trial_callback)
  File "/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni/tuner.py", line 135, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id, **kwargs)
  File "/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni/algorithms/hpo/gp_tuner/gp_tuner.py", line 185, in generate_parameters
    num_starting_points=self._selection_num_starting_points
  File "/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni/algorithms/hpo/gp_tuner/util.py", line 99, in acq_max
    method="L-BFGS-B")
  File "/root/miniconda3/envs/automl/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 624, in minimize
    callback=callback, **options)
  File "/root/miniconda3/envs/automl/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 294, in _minimize_lbfgsb
    raise ValueError("LBFGSB - one of the lower bounds is greater than an upper bound.")
ValueError: LBFGSB - one of the lower bounds is greater than an upper bound.
[2022-06-29 20:01:19] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2022-06-29 20:01:19] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated
```

**Comment by Sunny-Island** [comment]
@liuzhe-lz @ultmaster @J-shang

**Comment by Sunny-Island** [comment]
@suiguoxin @leckie-chn

**Comment by Sunny-Island** [comment]
I have located the bug, I will close this issue via a PR.

**Comment by Sunny-Island** [comment]
Please review this [PR](https://github.com/microsoft/nni/pull/4977)
