### ISSUE TITLE
Error: tuner_command_channel: Tuner loses responsive

### ISSUE THREAD

**Issue by Sunny-Island** [microsoft/nni#4988]
**Describe the issue**:

`Error: tuner_command_channel: Tuner loses responsive` raised when training and then all processes exit.

**Environment**:
- NNI version:latest released
- Training service (local|remote|pai|aml|etc):Local
- Client OS:CentOS
- Python version:3.7.13
- PyTorch/TensorFlow version: No framework.
- Is conda/virtualenv/venv used?: Conda
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:
search_space_policy = {
    'evolutionary_search_mutation_prob': {'_type': 'quniform', '_value': [0.5, 0.95, 0.001]},
    'evolutionary_search_num_iters': {'_type': 'choice', '_value': [3, 4, 5, 6, 7, 8, 9, 10]},
    'eps_greedy': {'_type': 'quniform', '_value': [0.03, 0.1, 0.001]},
}

**Log message**:

 - nnimanager.log:
```
 [2022-07-05 22:23:12] INFO (NNIManager) Trial job KEY3D status changed from WAITING to RUNNING
[2022-07-05 22:26:32] INFO (NNIManager) Trial job yaHgu status changed from RUNNING to SUCCEEDED
[2022-07-05 22:26:37] INFO (NNIManager) Trial job RWfDm status changed from RUNNING to SUCCEEDED
[2022-07-05 22:26:38] ERROR (tuner_command_channel.WebSocketChannel) Error: Error: tuner_command_channel: Tuner loses responsive
    at WebSocketChannelImpl.heartbeat (/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:91:30)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-07-05 22:26:38] ERROR (NNIManager) Dispatcher error: tuner_command_channel: Tuner loses responsive
[2022-07-05 22:26:38] ERROR (NNIManager) Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.<anonymous> (/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni_node/core/nnimanager.js:647:32)
    at EventEmitter.emit (node:events:526:28)
    at WebSocketChannelImpl.handleError (/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:107:22)
    at WebSocketChannelImpl.heartbeat (/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:91:18)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-07-05 22:26:38] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR
[2022-07-05 22:26:47] INFO (ShutdownManager) Initiate shutdown: REST request
[2022-07-05 22:26:47] INFO (RestServer) Stopping REST server.
[2022-07-05 22:26:47] INFO (NNIManager) Change NNIManager status from: ERROR to: STOPPING
[2022-07-05 22:26:47] INFO (NNIManager) Stopping experiment, cleaning up ...
[2022-07-05 22:26:47] INFO (NNIManager) cancelTrialJob: ZOz7o
[2022-07-05 22:26:48] INFO (NNIManager) cancelTrialJob: KEY3D
[2022-07-05 22:26:49] INFO (LocalTrainingService) Stopping local machine training service...
[2022-07-05 22:26:49] INFO (NNIManager) Change NNIManager status from: STOPPING to: STOPPED
[2022-07-05 22:26:49] INFO (NNIManager) Experiment stopped.
[2022-07-05 22:26:49] INFO (NNITensorboardManager) Forced stopping all tensorboard task.
[2022-07-05 22:26:49] INFO (NNITensorboardManager) All tensorboard task stopped.
[2022-07-05 22:26:49] INFO (NNITensorboardManager) Tensorboard manager stopped.
[2022-07-05 22:26:49] INFO (LocalTrainingService) Local machine training service exit.
[2022-07-05 22:26:51] INFO (RestServer) REST server stopped.
[2022-07-05 22:26:51] INFO (ShutdownManager) Shutdown complete.
```

 - dispatcher.log:
```
[2022-07-05 22:26:29] INFO (GP_Tuner_AutoML/Thread-1) parameter : {'eps_greedy': 0.067, 'evolutionary_search_mutation_prob': 0.59, 'evolutionary_search_num_iters': 6}
[2022-07-05 22:26:38] ERROR (nni.main/MainThread) NNI manager closed connection
Traceback (most recent call last):
  File "/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni/__main__.py", line 83, in <module>
    main()
  File "/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni/__main__.py", line 60, in main
    dispatcher.run()
  File "/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni/runtime/msg_dispatcher_base.py", line 68, in run
    command, data = self._channel._receive()
  File "/root/miniconda3/envs/automl/lib/python3.7/site-packages/nni/runtime/tuner_command_channel/channel.py", line 59, in _receive
    raise RuntimeError('NNI manager closed connection')
RuntimeError: NNI manager closed connection
```
 - nnictl stdout and stderr:
 

**How to reproduce it?**:
Not sure.

**Comment by liuzhe-lz** [comment]
Can this bug be reproduced stably?

**Comment by Sunny-Island** [comment]
> Can this bug be reproduced stably?

Not sure. I will try later. What kind of problems can cause tuner loses responsive?

**Comment by Sunny-Island** [comment]
I noticed tuner heatbeat lost was reported in log. After many round, tuner must train several seconds to get new parameters, will the longer and longer training time will cause overtime?

**Comment by why-in-Shanghaitech** [comment]
Same problem. It only happens with the latest released version.

**Comment by Sunny-Island** [comment]
It happens again. This bug disturb long time job badly. @liuzhe-lz @ultmaster

**Comment by Sunny-Island** [comment]
> Same problem. It only happens with the latest released version.

Hey, I wanne which version can avoid this problem.

**Comment by why-in-Shanghaitech** [comment]
> > Same problem. It only happens with the latest released version.
> 
> Hey, I wanna which version can avoid this problem.

v2.7 is fine. However, sometimes I cannot stop an experiment by command line with v2.7. Nevertheless, it is much better than the latest v2.8.

Downgrade using `pip install nni==2.7`. Remember to stop all the running experiments before you downgrade.

**Comment by liuzhe-lz** [comment]
We will add auto-reconnect in v2.9 release.
