### ISSUE TITLE
tuner keeps crashing due to "too frequent intermediate result"

### ISSUE THREAD

**Issue by wwbs4564** [microsoft/nni#5015]
**Describe the issue**:

When I was using nni to tune my model, this error occur after the experiment started for a period of time:

`Dispatcher stream error, tuner may have crashed.`

At first, I thought my “trail concurrency” was too high, so I set it to 2 instead of 4. That didn’t work.

Then, I found the “reduce the frequency of intermediate results” log, so I tried pytorch(I used tensorflow at first), and I set the freq of reporting intermediate result from report after every 1 epoch to every 5 epoch. That didn’t work either.

Other than that,  after changing from tensorflow to pytorch, I noticed that the time it takes for tuner to crash significantly changed: in tensorflow, it crashes in about 2 hours after the experiment start; in pytorch,  it crashes in just 20min. I’m not sure what it means and what causes it, but maybe it’s related to training speed——in pytorch, every trail costs about 30s, but in tensorflow the time is 5min(same 500 epochs, maybe due to different batch-size).

And finally, I need to note that my PC is surface Pro7 i5 version, which has no positive heat dissipation system. So this might be a hardware problem too. 

Thank you and looking forward to a solution! 

**Environment**:

- NNI version: 2.8
- Training service: local
- Client OS: win10
- Python version: 3.9.12
- PyTorch/TensorFlow version: 1.12.0 for pytorch; 2.9.1 for tensorflow
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Configuration**:

 - Experiment config :

   ```
   trial_command: python model.py
   
   trial_concurrency: 2
   max_experiment_duration: 10h
   
   tuner:
     name: Evolution
     class_args:
       optimize_mode: minimize
       population_size: 50
   
   assessor:
     name: Medianstop
     class_args:
       optimize_mode: minimize
       start_step: 50
   
   training_service:
     platform: local
   ```

**Log message**:

 - nnimanager.log:

```[2022-07-23 22:03:54] ERROR (tuner_command_channel.WebSocketChannel) Error: Error: tuner_command_channel: Tuner closed connection
    at WebSocket.<anonymous> (C:\anaconda3\lib\site-packages\nni_node\core\tuner_command_channel\websocket_channel.js:41:49)
    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (C:\anaconda3\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:246:10)
    at Socket.socketOnClose (C:\anaconda3\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:1127:15)
    at Socket.emit (node:events:526:28)
    at TCP.<anonymous> (node:net:687:12)
[2022-07-23 22:03:54] ERROR (NNIManager) Dispatcher error: tuner_command_channel: Tuner closed connection
[2022-07-23 22:03:54] ERROR (NNIManager) Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.<anonymous> (C:\anaconda3\lib\site-packages\nni_node\core\nnimanager.js:647:32)
    at EventEmitter.emit (node:events:526:28)
    at WebSocketChannelImpl.handleError (C:\anaconda3\lib\site-packages\nni_node\core\tuner_command_channel\websocket_channel.js:107:22)
    at WebSocket.<anonymous> (C:\anaconda3\lib\site-packages\nni_node\core\tuner_command_channel\websocket_channel.js:41:37)
    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (C:\anaconda3\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:246:10)
    at Socket.socketOnClose (C:\anaconda3\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:1127:15)
    at Socket.emit (node:events:526:28)
    at TCP.<anonymous> (node:net:687:12)
[2022-07-23 22:03:54] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR
[2022-07-23 22:03:57] WARNING (tuner_command_channel.WebSocketChannel) Sending too fast! Try to reduce the frequency of intermediate results.
(followed by many same lines like this)
```

+  dispatcher.log:

```
[2022-07-23 22:03:45] INFO (nni.algorithms.hpo.evolution_tuner/Thread-2) trial (44) end
[2022-07-23 22:03:45] ERROR (nni.runtime.msg_dispatcher_base/Thread-2) 44
Traceback (most recent call last):
  File "C:\anaconda3\lib\site-packages\nni\runtime\msg_dispatcher_base.py", line 97, in command_queue_worker
    self.process_command(command, data)
  File "C:\anaconda3\lib\site-packages\nni\runtime\msg_dispatcher_base.py", line 143, in process_command
    command_handlers[command](data)
  File "C:\anaconda3\lib\site-packages\nni\runtime\msg_dispatcher.py", line 170, in handle_trial_end
    self.tuner.trial_end(load(data['hyper_params'])['parameter_id'], data['event'] == 'SUCCEEDED')
  File "C:\anaconda3\lib\site-packages\nni\algorithms\hpo\evolution_tuner.py", line 137, in trial_end
    self.running_trials.pop(parameter_id)
KeyError: 44
[2022-07-23 22:03:53] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2022-07-23 22:03:54] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated
```

**Comment by wwbs4564** [comment]
I run the same code on my desktop PC again, this time the experiment run for 670 trials and nearly 4 hours before the same error occur. 
However, this time I get different dispather log and nnimanager log:
```
dispather log:
[2022-07-24 04:06:52] ERROR (nni.runtime.msg_dispatcher_base/Thread-2) 684
Traceback (most recent call last):
  File "C:\anaconda3\lib\site-packages\nni\runtime\msg_dispatcher_base.py", line 97, in command_queue_worker
    self.process_command(command, data)
  File "C:\anaconda3\lib\site-packages\nni\runtime\msg_dispatcher_base.py", line 143, in process_command
    command_handlers[command](data)
  File "C:\anaconda3\lib\site-packages\nni\runtime\msg_dispatcher.py", line 170, in handle_trial_end
    self.tuner.trial_end(load(data['hyper_params'])['parameter_id'], data['event'] == 'SUCCEEDED')
  File "C:\anaconda3\lib\site-packages\nni\algorithms\hpo\evolution_tuner.py", line 137, in trial_end
    self.running_trials.pop(parameter_id)
KeyError: 684
[2022-07-24 04:06:52] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2022-07-24 04:06:52] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated

nimanager log:
[2022-07-24 04:06:53] ERROR (tuner_command_channel.WebSocketChannel) Error: Error: tuner_command_channel: Tuner closed connection
    at WebSocket.<anonymous> (C:\anaconda3\lib\site-packages\nni_node\core\tuner_command_channel\websocket_channel.js:41:49)
    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (C:\anaconda3\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:246:10)
    at Socket.socketOnClose (C:\anaconda3\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:1127:15)
    at Socket.emit (node:events:526:28)
    at TCP.<anonymous> (node:net:687:12)
[2022-07-24 04:06:53] ERROR (NNIManager) Dispatcher error: tuner_command_channel: Tuner closed connection
[2022-07-24 04:06:53] ERROR (NNIManager) Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.<anonymous> (C:\anaconda3\lib\site-packages\nni_node\core\nnimanager.js:647:32)
    at EventEmitter.emit (node:events:526:28)
    at WebSocketChannelImpl.handleError (C:\anaconda3\lib\site-packages\nni_node\core\tuner_command_channel\websocket_channel.js:107:22)
    at WebSocket.<anonymous> (C:\anaconda3\lib\site-packages\nni_node\core\tuner_command_channel\websocket_channel.js:41:37)
    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (C:\anaconda3\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:246:10)
    at Socket.socketOnClose (C\anaconda3\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:1127:15)
    at Socket.emit (node:events:526:28)
    at TCP.<anonymous> (node:net:687:12)
[2022-07-24 04:06:53] INFO (NNIManager) Change NNIManager status from: RUNNING to: ERROR

**Comment by nnnnnzy** [comment]
#5006 I have same problem.

**Comment by wwbs4564** [comment]
> #5006 I have same problem.

I solved the problem by setting the freq of report intermediate result to per 50 epochs. So maybe you need to set that even lower?
