### ISSUE TITLE
Error while using FeatureGradientSelector

### ISSUE THREAD

**Issue by liuyanyi** [microsoft/nni#5120]
**Describe the issue**:
While i'm trying use FeatureGradientSelector, i got an error that. Is there any suggestion to solve that?
```
Traceback (most recent call last):
  File "E:/project/projcect-new/nni_feature_selection.py", line 105, in <module>
    test()
  File "E:/project/projcect-new/nni_feature_selection.py", line 98, in test
    fgs.fit(X_train, y_train)
  File "D:\dev\miniconda\envs\deploy\lib\site-packages\nni\algorithms\feature_engineering\gradient_selector\gradient_selector.py", line 260, in fit
    self._fit(X, y, groups=groups)
  File "D:\dev\miniconda\envs\deploy\lib\site-packages\nni\algorithms\feature_engineering\gradient_selector\gradient_selector.py", line 290, in _fit
    data_train = self._prepare_data(X, y)
  File "D:\dev\miniconda\envs\deploy\lib\site-packages\nni\algorithms\feature_engineering\gradient_selector\gradient_selector.py", line 275, in _prepare_data
    return PrepareData(X=X.values if isinstance(X, pd.DataFrame) else X,
  File "D:\dev\miniconda\envs\deploy\lib\site-packages\nni\algorithms\feature_engineering\gradient_selector\fginitialize.py", line 221, in __init__
    Xmn, sv1, Xsd, ymn, ysd = self.compute_data_stats()
  File "D:\dev\miniconda\envs\deploy\lib\site-packages\nni\algorithms\feature_engineering\gradient_selector\fginitialize.py", line 432, in compute_data_stats
    sv1 = scipy.sparse.linalg.svds(Xc / (
  File "D:\dev\miniconda\envs\deploy\lib\site-packages\scipy\sparse\linalg\_eigen\_svds.py", line 252, in svds
    args = _iv(A, k, ncv, tol, which, v0, maxiter, return_singular_vectors,
  File "D:\dev\miniconda\envs\deploy\lib\site-packages\scipy\sparse\linalg\_eigen\_svds.py", line 36, in _iv
    A = aslinearoperator(A)  # this takes care of some input validation
  File "D:\dev\miniconda\envs\deploy\lib\site-packages\scipy\sparse\linalg\_interface.py", line 826, in aslinearoperator
    raise TypeError('type not understood')
TypeError: type not understood
```

**Environment**:
- NNI version: 2.8
- Training service (local|remote|pai|aml|etc): local
- Client OS: Windows
- Server OS (for remote mode only):
- Python version: 3.8.13
- PyTorch/TensorFlow version: 1.12.0+cu116
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

code is here:

```

from nni.algorithms.feature_engineering.gradient_selector import \
    FeatureGradientSelector
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split


def test():
    X, y = make_classification()
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,
                                                        random_state=42)
    fgs = FeatureGradientSelector()
    fgs.fit(X_train, y_train)
    print(fgs.get_selected_features())

if __name__ == "__main__":
    test()

```

**Comment by ultmaster** [comment]
The feature engineering tool in NNI has not been updated for a long time, and might only work for legacy dependency versions. You could check the tested dependency version [here](https://github.com/microsoft/nni/blob/master/nni/algorithms/feature_engineering/gradient_selector/requirements.txt), and see if they work for you.

**Comment by liuyanyi** [comment]
Thanks for your reply, I downgraded scipy, scikit-learn and python to make it work, but torch==1.1.0 lead to error too so i use the latest version, here is my working env on windows:
```
python == 3.6
scikit-learn == 0.23.2
scipy == 1.1.0
torch == 1.10.2
numpy == 1.19.3
nni == 2.6.1
```
