### ISSUE TITLE
error about the visulization website (http://127.0.0.1:ip)

### ISSUE THREAD

**Issue by xiangtaowong** [microsoft/nni#5128]
After I start the `nni` and I open the website`http://127.0.0.1:ip`, the website becomes un-reopened.
The detail is like `I can't reload the website ` and the website is always the interface I open it firstly.

I use remote: Ubuntu server 
And I want to see the details on my computer: Ubuntu server, too.

Looking for your reply.

**Comment by xiangtaowong** [comment]
I tried  almost all the `Web portal URLs`, none of them work.

**Comment by xiangtaowong** [comment]
the `dispatcher.log` is below:
```
[2022-09-15 19:21:35] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2022-09-15 19:21:45] ERROR (nni.main/MainThread) NNI manager closed connection
Traceback (most recent call last):
  File "/home/wangxiangtao/anaconda3/envs/mae/lib/python3.8/site-packages/nni/__main__.py", line 83, in <module>
    main()
  File "/home/wangxiangtao/anaconda3/envs/mae/lib/python3.8/site-packages/nni/__main__.py", line 60, in main
    dispatcher.run()
  File "/home/wangxiangtao/anaconda3/envs/mae/lib/python3.8/site-packages/nni/runtime/msg_dispatcher_base.py", line 68, in run
    command, data = self._channel._receive()
  File "/home/wangxiangtao/anaconda3/envs/mae/lib/python3.8/site-packages/nni/runtime/tuner_command_channel/channel.py", line 59, in _receive
    raise RuntimeError('NNI manager closed connection')
RuntimeError: NNI manager closed connection
****
```

**Comment by QuanluZhang** [comment]
what is the content of nnimanager.log?

**Comment by xiangtaowong** [comment]
When I re-run the project, the error disappear and it works successfully, but I changed nothing.

And I find another little question: 
Is there a max sending numbers? For after I re-run some times, i get the error again as in #5126. 
But it works again after a few times .

**Comment by QuanluZhang** [comment]
You can post the log here when the problem happens again:)

**Comment by xiangtaowong** [comment]
ok, thank u so much!
