### ISSUE TITLE
speedup_model() causes a error: “NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors)”

### ISSUE THREAD

**Issue by missu123** [microsoft/nni#5130]
**Describe the issue**:
[2022-09-16 15:20:07] start to speedup the model
[2022-09-16 15:20:09] infer module masks...
[2022-09-16 15:20:09] Update mask for net.conv1.conv1.0
[2022-09-16 15:20:09] Update mask for net.aten::cat.87
Traceback (most recent call last):
  File "network_prune.py", line 587, in <module>
    m_Speedup.speedup_model()
  File "/root/miniconda3/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 536, in speedup_model
    self.infer_modules_masks()
  File "/root/miniconda3/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 371, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/root/miniconda3/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 231, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
  File "/root/miniconda3/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/nni/compression/pytorch/speedup/jit_translate.py", line 561, in forward
    return torch.cat(args, dim=self.cat_dim)
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Python, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, AutocastCPU, Autocast, Batched, VmapMode, Functionalize].

**Environment**:
- NNI version: 2.8 and 2.9
- Training service (local|remote|pai|aml|etc): local and remote
- Client OS: ubuntu
- Server OS (for remote mode only): 
- Python version: python--3.8
- PyTorch/TensorFlow version: pytorch-1.11.0, cuda--11.3
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Comment by Louis-J** [comment]
Could you please offer the context codes around this 'torch.cat'? I think it's the same bug that can be fixed in #5107.

**Comment by scarlett2018** [comment]
> Could you please offer the context codes around this 'torch.cat'? I think it's the same bug that can be fixed in #5107.

@missu123 - may you share the context codes as @Louis-J asked? thanks.

**Comment by Lijiaoa** [comment]
feel free to reopen if you have any other question. @missu123
