### ISSUE TITLE
AttributeError in "Speedup Model with Mask" Tutorial Codes

### ISSUE THREAD

**Issue by hshwang88** [microsoft/nni#5131]
**Describe the issue**:
https://nni.readthedocs.io/en/stable/tutorials/pruning_speedup.html

```python
ModelSpeedup(model, torch.rand(10, 1, 28, 28).to(device), masks).speedup_model()
```

```
Traceback (most recent call last):
  File "e:\Projects\NNI\src\CompressionTuto.py", line 18, in <module>
    ModelSpeedup(model, torch.rand(10, 1, 28, 28).to(device), masks).speedup_model()
  File "d:\pt-env\lib\site-packages\nni\compression\pytorch\speedup\compressor.py", line 543, in speedup_model
    self.infer_modules_masks()
  File "d:\pt-env\lib\site-packages\nni\compression\pytorch\speedup\compressor.py", line 380, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "d:\pt-env\lib\site-packages\nni\compression\pytorch\speedup\compressor.py", line 228, in update_direct_sparsity
    func = jit_to_python_function(node, self)
  File "d:\pt-env\lib\site-packages\nni\compression\pytorch\speedup\jit_translate.py", line 555, in jit_to_python_function
    return trans_func_dict[node.op_type](node, speedup)
  File "d:\pt-env\lib\site-packages\nni\compression\pytorch\speedup\jit_translate.py", line 490, in generate_aten_to_python
    positional_num, keyword_list, special_treat = parse_aten_schema(schema)
  File "d:\pt-env\lib\site-packages\nni\compression\pytorch\speedup\jit_translate.py", line 411, in parse_aten_schema
    if not arg.kwarg_only:
AttributeError: 'torch._C.Argument' object has no attribute 'kwarg_only'
```

**Environment**:
- NNI version: 2.9
- Training service: local
- Client OS: Win10
- Python version: 3.9.8
- PyTorch version: 1.8.1+cu111
- Is conda/virtualenv/venv used?: venv
- Is running in Docker?: No

**How to reproduce it?**:
```python
import torch
import time
from nni.compression.pytorch import ModelSpeedup
from scripts.compression_mnist_model import TorchModel, device

model = TorchModel().to(device)

conv1_mask = torch.ones_like(model.conv1.weight.data)
conv1_mask[0:3] = 0

masks = {'conv1': {'weight': conv1_mask}}

start = time.time()
model(torch.rand(128, 1, 28, 28).to(device))

print('Original Model - Elapsed Time : ', time.time() - start)

ModelSpeedup(model, torch.rand(10, 1, 28, 28).to(device), masks).speedup_model()
print(model)
```

**Comment by Louis-J** [comment]
It's indeed a problem. The `torch._C.parse_schema` do not produce enough information in pytorch <1.9.0. I'm going to write a replacement of `torch._C.parse_schema` to bypass it.

**Comment by Lijiaoa** [comment]
looks like the fixed PR had been merged, so this issue could be closed? @Louis-J @hshwang88

**Comment by hshwang88** [comment]
Thanks a lot
