### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Lijiaoa** [microsoft/nni#5177]
**Describe the issue**:
I use the command `python3 -m pip install --user --no-cache-dir -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple nni==2.10a1` to install nni

Looks like the nni had been installed successfully, but have some error log, and couldn't start an experiment successfully.
![1](https://user-images.githubusercontent.com/61399850/197434896-c6accab7-9a55-47c2-a44e-1f7ff48e0225.png)
![2](https://user-images.githubusercontent.com/61399850/197435195-bc24051e-cbeb-4f05-90a6-3e134d9dd1f7.png)

![3](https://user-images.githubusercontent.com/61399850/197435203-36d5d80c-c949-4deb-9a93-13d5f5157db2.png)

**Environment**:
- NNI version: 2.10a1
- Training service (local|remote|pai|aml|etc): 
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 

> [2022-10-24 02:01:50] INFO (main) Start NNI manager
[2022-10-24 02:01:50] INFO (NNIDataStore) Datastore initialization done
[2022-10-24 02:01:50] INFO (RestServer) Starting REST server at port 8080, URL prefix: "/"
[2022-10-24 02:01:50] INFO (RestServer) REST server started.

 - dispatcher.log: none
 - nnictl stdout and stderr:
 

> --------------------------------------------------------------------------------
Experiment 3k56mily start: 2022-10-24 02:01:49.843080
--------------------------------------------------------------------------------

> --------------------------------------------------------------------------------
Experiment 3k56mily start: 2022-10-24 02:01:49.843080
--------------------------------------------------------------------------------

 

**How to reproduce it?**:
install the test package and run the experiment `nnictl create --config examples/trials/mnist-tfv2/config.yml`

**Comment by Lijiaoa** [comment]
> PS E:\work\dev\nni> python -m pip install --upgrade pip                                                                 WARNING: Ignoring invalid distribution -ip (d:\python\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\python\lib\site-packages)
Requirement already satisfied: pip in d:\python\lib\site-packages\pip-22.1-py3.10.egg (22.1)
Collecting pip
  Downloading pip-22.3-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 3.6 MB/s eta 0:00:00
WARNING: Ignoring invalid distribution -ip (d:\python\lib\site-packages)
Installing collected packages: pip
  Attempting uninstall: pip
    WARNING: Ignoring invalid distribution -ip (d:\python\lib\site-packages)
    Found existing installation: pip 22.1
    Uninstalling pip-22.1:
      Successfully uninstalled pip-22.1
  WARNING: No metadata found in d:\python\lib\site-packages\pip-22.1-py3.10.egg
  Rolling back uninstall of pip
  Moving to d:\python\lib\site-packages\pip-22.1-py3.10.egg
   from D:\Python\Lib\site-packages\~ip-22.1-py3.10.egg
  Moving to d:\python\scripts\pip-script.py
   from C:\Users\point\AppData\Local\Temp\pip-uninstall-he7chv6k\pip-script.py
  Moving to d:\python\scripts\pip.exe
   from C:\Users\point\AppData\Local\Temp\pip-uninstall-he7chv6k\pip.exe
  Moving to d:\python\scripts\pip3-script.py
   from C:\Users\point\AppData\Local\Temp\pip-uninstall-he7chv6k\pip3-script.py
  Moving to d:\python\scripts\pip3.10-script.py
   from C:\Users\point\AppData\Local\Temp\pip-uninstall-he7chv6k\pip3.10-script.py
  Moving to d:\python\scripts\pip3.10.exe
   from C:\Users\point\AppData\Local\Temp\pip-uninstall-he7chv6k\pip3.10.exe
  Moving to d:\python\scripts\pip3.exe
   from C:\Users\point\AppData\Local\Temp\pip-uninstall-he7chv6k\pip3.exe
ERROR: Exception:
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_internal\commands\install.py", line 406, in run
    installed = install_given_reqs(
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_internal\req\__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_internal\req\req_install.py", line 773, in install
    install_wheel(
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_internal\operations\install\wheel.py", line 730, in install_wheel
    _install_wheel(
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_internal\operations\install\wheel.py", line 647, in _install_wheel
    generated_console_scripts = maker.make_multiple(scripts_to_generate)
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_vendor\distlib\scripts.py", line 428, in make_multiple
    filenames.extend(self.make(specification, options))
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_internal\operations\install\wheel.py", line 428, in make
    return super().make(specification, options)
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_vendor\distlib\scripts.py", line 417, in make
    self._make_script(entry, filenames, options=options)
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_vendor\distlib\scripts.py", line 317, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_vendor\distlib\scripts.py", line 247, in _write_script
    launcher = self._get_launcher('t')
  File "D:\Python\lib\site-packages\pip-22.1-py3.10.egg\pip\_vendor\distlib\scripts.py", line 396, in _get_launcher
    raise ValueError(msg)
ValueError: Unable to find resource t64.exe in package pip._vendor.distlib
