### ISSUE TITLE
error in trial example

### ISSUE THREAD

**Issue by kingaza** [microsoft/nni#5180]
**Describe the issue**:
error happens when runing trial examples for pytorch/sklearn/...

Traceback (most recent call last):
  File "/home/hejiew/anaconda3/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
  File "/home/hejiew/anaconda3/lib/python3.9/site-packages/nni/tools/nnictl/nnictl.py", line 497, in parse_args
    args.func(args)
  File "/home/hejiew/anaconda3/lib/python3.9/site-packages/nni/tools/nnictl/launcher.py", line 122, in view_experiment
    if config_json.get('trainingServicePlatform'):
AttributeError: 'NoneType' object has no attribute 'get'

**Environment**:
- NNI version: 2.9
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu 20.04
- Server OS (for remote mode only):
- Python version: 3.9
- PyTorch/TensorFlow version: pytorch 1.12
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Configuration**:
default examples

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:
just run the examples

**Comment by Lijiaoa** [comment]
hi @kingaza Could you update the experiment `dispatcher log` and `nnimanager log`? You could find it in `nni-experiments/experimentID/log` folder.

**Comment by kingaza** [comment]
**dispatcher.log**
```
[2022-10-25 14:02:16] INFO (numexpr.utils/MainThread) Note: detected 152 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
[2022-10-25 14:02:16] INFO (numexpr.utils/MainThread) Note: NumExpr detected 152 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2022-10-25 14:02:16] INFO (numexpr.utils/MainThread) NumExpr defaulting to 8 threads.
[2022-10-25 14:02:16] INFO (nni.tuner.tpe/MainThread) Using random seed 650223786
[2022-10-25 14:02:16] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2022-10-25 14:02:41] INFO (nni.common.hpo_utils.dedup/Thread-1) Tuning algorithm generated duplicate parameter: {('model_name',): 3, ('normalize',): 0}
[2022-10-25 14:02:41] INFO (nni.common.hpo_utils.dedup/Thread-1) Use grid search for deduplication.
[2022-10-25 14:02:41] INFO (nni.tuner.gridsearch/Thread-1) Grid initialized, size: (4×2) = 8
[2022-10-25 14:03:42] INFO (nni.tuner.gridsearch/Thread-1) Search space has been fully explored
```

**Comment by kingaza** [comment]
**nnimanager.log**
```
[2022-10-25 14:02:15] INFO (main) Start NNI manager
[2022-10-25 14:02:15] INFO (NNIDataStore) Datastore initialization done
[2022-10-25 14:02:15] INFO (RestServer) Starting REST server at port 8080, URL prefix: "/"
[2022-10-25 14:02:15] INFO (RestServer) REST server started.
[2022-10-25 14:02:16] INFO (NNIManager) Starting experiment: tmqljnv2
[2022-10-25 14:02:16] INFO (NNIManager) Setup training service...
[2022-10-25 14:02:16] INFO (LocalTrainingService) Construct local machine training service.
[2022-10-25 14:02:16] INFO (NNIManager) Setup tuner...
[2022-10-25 14:02:16] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2022-10-25 14:02:16] INFO (NNIManager) Add event listeners
[2022-10-25 14:02:16] INFO (LocalTrainingService) Run local machine training service.
[2022-10-25 14:02:16] INFO (NNIManager) NNIManager received command from dispatcher: ID,
[2022-10-25 14:02:16] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"model_name": "ARDRegression", "normalize": "true"}, "parameter_index": 0}
[2022-10-25 14:02:21] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 0,
  hyperParameters: {
    value: '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"model_name": "ARDRegression", "normalize": "true"}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2022-10-25 14:02:31] INFO (NNIManager) Trial job ahKLB status changed from WAITING to SUCCEEDED
[2022-10-25 14:02:31] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"model_name": "Lars", "normalize": "true"}, "parameter_index": 0}
[2022-10-25 14:02:36] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 1,
  hyperParameters: {
    value: '{"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"model_name": "Lars", "normalize": "true"}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2022-10-25 14:02:41] INFO (NNIManager) Trial job n7kkG status changed from WAITING to SUCCEEDED
[2022-10-25 14:02:41] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 2, "parameter_source": "algorithm", "parameters": {"model_name": "LinearRegression", "normalize": "true"}, "parameter_index": 0}
[2022-10-25 14:02:46] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 2,
  hyperParameters: {
    value: '{"parameter_id": 2, "parameter_source": "algorithm", "parameters": {"model_name": "LinearRegression", "normalize": "true"}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2022-10-25 14:02:51] INFO (NNIManager) Trial job IOv4R status changed from WAITING to SUCCEEDED
[2022-10-25 14:02:52] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 3, "parameter_source": "algorithm", "parameters": {"model_name": "Ridge", "normalize": "true"}, "parameter_index": 0}
[2022-10-25 14:02:56] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 3,
  hyperParameters: {
    value: '{"parameter_id": 3, "parameter_source": "algorithm", "parameters": {"model_name": "Ridge", "normalize": "true"}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2022-10-25 14:03:02] INFO (NNIManager) Trial job nO39Z status changed from WAITING to SUCCEEDED
[2022-10-25 14:03:02] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 4, "parameter_source": "algorithm", "parameters": {"model_name": "LinearRegression", "normalize": "false"}, "parameter_index": 0}
[2022-10-25 14:03:07] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 4,
  hyperParameters: {
    value: '{"parameter_id": 4, "parameter_source": "algorithm", "parameters": {"model_name": "LinearRegression", "normalize": "false"}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2022-10-25 14:03:12] INFO (NNIManager) Trial job ZhRjy status changed from WAITING to SUCCEEDED
[2022-10-25 14:03:12] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 5, "parameter_source": "algorithm", "parameters": {"model_name": "Lars", "normalize": "false"}, "parameter_index": 0}
[2022-10-25 14:03:17] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 5,
  hyperParameters: {
    value: '{"parameter_id": 5, "parameter_source": "algorithm", "parameters": {"model_name": "Lars", "normalize": "false"}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2022-10-25 14:03:22] INFO (NNIManager) Trial job bOF0z status changed from WAITING to SUCCEEDED
[2022-10-25 14:03:22] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 6, "parameter_source": "algorithm", "parameters": {"model_name": "Ridge", "normalize": "false"}, "parameter_index": 0}
[2022-10-25 14:03:27] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 6,
  hyperParameters: {
    value: '{"parameter_id": 6, "parameter_source": "algorithm", "parameters": {"model_name": "Ridge", "normalize": "false"}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2022-10-25 14:03:32] INFO (NNIManager) Trial job gnAyQ status changed from WAITING to SUCCEEDED
[2022-10-25 14:03:32] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 7, "parameter_source": "algorithm", "parameters": {"model_name": "ARDRegression", "normalize": "false"}, "parameter_index": 0}
[2022-10-25 14:03:37] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 7,
  hyperParameters: {
    value: '{"parameter_id": 7, "parameter_source": "algorithm", "parameters": {"model_name": "ARDRegression", "normalize": "false"}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2022-10-25 14:03:42] INFO (NNIManager) Trial job sRLAQ status changed from WAITING to SUCCEEDED
[2022-10-25 14:03:42] INFO (NNIManager) NNIManager received command from dispatcher: NO, {"parameter_id": 8, "parameter_source": "algorithm", "parameters": "", "parameter_index": 0}
[2022-10-25 14:03:42] INFO (NNIManager) Change NNIManager status from: RUNNING to: TUNER_NO_MORE_TRIAL
[2022-10-25 15:02:22] INFO (NNIManager) Change NNIManager status from: TUNER_NO_MORE_TRIAL to: NO_MORE_TRIAL
[2022-10-25 15:02:22] INFO (NNIManager) Change NNIManager status from: NO_MORE_TRIAL to: DONE
[2022-10-25 15:02:22] INFO (NNIManager) Experiment done.

```

**Comment by liuzhe-lz** [comment]
You are trying to view a stopped a experiment, right? Is that experiment created with the NNI v2.9?

**Comment by kingaza** [comment]
you are right, I made a stupid mistake.
