### ISSUE TITLE
ValueError: high - low < 0

### ISSUE THREAD

**Issue by twei55** [microsoft/nni#5182]
Hi people,

I am getting the above stated error when starting my experiments. I have no idea what is going wrong here, any mistake in my search space?

I remember that the same experiment setup was running fine with a previous NNI version but don't know the exact version number any more.

I guess it is not related but I updated to poetry for dependency management lately, now I ran into this issue.

Would be really great to get some advise on this. 

Thanks

---
**Environment**:
- NNI version: 2.9
- Training service (local|remote|pai|aml|etc): local
- Client OS: osgeo/gdal:ubuntu-small
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: Pytorch 1.12.1
- Is conda/virtualenv/venv used?: poetry
- Is running in Docker?: Yes

---
**Configuration**:
 - Experiment config:
 ```
experimentName: "My Experiment"
searchSpaceFile: /usr/src/my-app/nni/search_space/training_05.json

maxExperimentDuration: 24h
maxTrialNumber: 200
experimentWorkingDirectory: /srv/docker/container/my-app/nni-experiments

tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize

trialCommand: poetry run python my-app/training/train.py --data-dir=/mnt/my-data/training_data/_zarr/20220118_training_05/visual --nni --aug-colorjitter --aug-rotate
trialCodeDirectory: /usr/src/app
trialConcurrency: 2

trainingService:
  platform: local
  useActiveGpu: false
```
---
 - Search space:
 ```
 {
    "num_classes": {
        "_type": "choice",
        "_value": [2]
    },
    "size": {
        "_type": "choice",
        "_value": [50]
    },
    "batch_size": {
        "_type": "quniform",
        "_value": [8, 128, 8]
    },
    "filters_conv1": {
        "_type": "quniform",
        "_value": [8, 128, 8]
    },
    "n_conv_layers": {
        "_type": "quniform",
        "_value": [1, 8, 1]
    },
    "double_filters_every": {
        "_type": "quniform",
        "_value": [2, 16, 2]
    },
    "pool_every": {
        "_type": "quniform",
        "_value": [2, 8, 2]
    },
    "units_dense1": {
        "_type": "quniform",
        "_value": [16, 128, 16]
    },
    "units_dense2": {
        "_type": "quniform",
        "_value": [0, 128, 16]
    },
    "dropout_dense1": {
        "_type": "quniform",
        "_value": [0.0, 0.5, 0.05]
    },
    "dropout_dense2": { 
        "_type": "quniform",
        "_value": [0.0, 0.5, 0.05]
    },
    "learning_rate": {
        "_type": "loguniform",
        "_value": [0.003, 0.00003]
    }
}
```
---
**Log message**:
 - nnimanager.log:
 ```
[2022-10-25 10:13:58] INFO (main) Start NNI manager
[2022-10-25 10:13:58] INFO (NNIDataStore) Datastore initialization done
[2022-10-25 10:13:58] INFO (RestServer) Starting REST server at port 8081, URL prefix: "/"
[2022-10-25 10:13:58] INFO (RestServer) REST server started.
[2022-10-25 10:13:59] INFO (NNIManager) Starting experiment: 9641t3du
[2022-10-25 10:13:59] INFO (NNIManager) Setup training service...
[2022-10-25 10:13:59] INFO (LocalTrainingService) Construct local machine training service.
[2022-10-25 10:13:59] INFO (NNIManager) Setup tuner...
[2022-10-25 10:13:59] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2022-10-25 10:14:00] INFO (NNIManager) Add event listeners
[2022-10-25 10:14:00] INFO (LocalTrainingService) Run local machine training service.
[2022-10-25 10:14:00] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
```

 - dispatcher.log:
 ```
[2022-10-25 10:14:00] INFO (nni.tuner.tpe/MainThread) Using random seed 240407015
[2022-10-25 10:14:00] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2022-10-25 10:14:00] ERROR (nni.runtime.msg_dispatcher_base/Thread-1) high - low < 0
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/my-app-VA82Wl8V-py3.8/lib/python3.8/site-packages/nni/runtime/msg_dispatcher_base.py", line 97, in command_queue_worker
    self.process_command(command, data)
  File "/root/.cache/pypoetry/virtualenvs/my-app-VA82Wl8V-py3.8/lib/python3.8/site-packages/nni/runtime/msg_dispatcher_base.py", line 143, in process_command
    command_handlers[command](data)
  File "/root/.cache/pypoetry/virtualenvs/my-app-VA82Wl8V-py3.8/lib/python3.8/site-packages/nni/runtime/msg_dispatcher.py", line 102, in handle_request_trial_jobs
    params_list = self.tuner.generate_multiple_parameters(ids, st_callback=self.send_trial_callback)
  File "/root/.cache/pypoetry/virtualenvs/my-app-VA82Wl8V-py3.8/lib/python3.8/site-packages/nni/tuner.py", line 135, in generate_multiple_parameters
    res = self.generate_parameters(parameter_id, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/my-app-VA82Wl8V-py3.8/lib/python3.8/site-packages/nni/algorithms/hpo/tpe_tuner.py", line 183, in generate_parameters
    params = suggest(self.args, self.rng, self.space, history)
  File "/root/.cache/pypoetry/virtualenvs/my-app-VA82Wl8V-py3.8/lib/python3.8/site-packages/nni/algorithms/hpo/tpe_tuner.py", line 224, in suggest
    params[key] = suggest_parameter(args, rng, spec, history[key])
  File "/root/.cache/pypoetry/virtualenvs/my-app-VA82Wl8V-py3.8/lib/python3.8/site-packages/nni/algorithms/hpo/tpe_tuner.py", line 229, in suggest_parameter
    return random_tuner.suggest_parameter(rng, spec)
  File "/root/.cache/pypoetry/virtualenvs/my-app-VA82Wl8V-py3.8/lib/python3.8/site-packages/nni/algorithms/hpo/random_tuner.py", line 87, in suggest_parameter
    return rng.uniform(spec.low, spec.high)
  File "_generator.pyx", line 949, in numpy.random._generator.Generator.uniform
  File "_common.pyx", line 610, in numpy.random._common.cont
  File "_common.pyx", line 419, in numpy.random._common.check_constraint
ValueError: high - low < 0
```

**Comment by twei55** [comment]
Ok, got it solved. I had to reverse the learning_rate range order.

```
"learning_rate": {
     "_type": "loguniform",
     "_value": [0.00003, 0.003]
 }
```
