### ISSUE TITLE
Problem about saving and loading nni pruned model

### ISSUE THREAD

**Issue by puyiwen** [microsoft/nni#5184]
**Describe the issue**:
Hi,I use a simple function to pruned my model and use `torch.save `to save pruned model.
But, when I load it I have a question like this.
```

Traceback (most recent call last):
  File "/home/puyiwen/fastdepth_org/torch2onnx.py", line 85, in <module>
    # device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
  File "/home/puyiwen/.conda/envs/puyiwen/lib/python3.9/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/puyiwen/.conda/envs/puyiwen/lib/python3.9/site-packages/torch/serialization.py", line 885, in _load
    result = unpickler.load()
  File "/home/puyiwen/.conda/envs/puyiwen/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv2d' object has no attribute 'accumulate_params'
```
I dont know why?Can you help me? Thank you very much!!

**Environment**:
- NNI version:
- 2.7
- Python version:
- 3.9.7
- PyTorch version:
- 1.10.0
- Is conda/virtualenv/venv used?:
- use conda
- Is running in Docker?:
- No

**Configuration**:
 my prune code is:
```
pruner = L1FilterPruner(model, config_list)
pruner.compress()
pruner.export_model(args.save_results + '/model_temp.pth', args.save_results + '/mask_temp.pth')
pruner._unwrap_model()
# pruner.show_pruned_weights()
ModelSpeedup(model, dummy_input=torch.rand([16, 3, 224, 224]).cuda(), masks_file=args.save_results + './mask_temp.pth').speedup_model()
torch.save(model,'/home/puyiwen/fastdepth_org/results/nyu_reduced.samples=0.modality=rgb.arch=litedepth_mixdata_2_correct.decoder=nnconv.criterion=l1.lr=0.01.bs=16.pretrained=True/model_best_nni.pth')
```
my load pruned model code is:
```
model = torch.load(input_file) #input_file is saved pruned model path 
model = model.cuda()
```
Thank you very much again!!

**Comment by Louis-J** [comment]
please offer your model. I tried a simple model with conv2d pruned but could not reproduce it.
