### ISSUE TITLE
Error reported when NNI was used to prune Albert-tiny

### ISSUE THREAD

**Issue by Smile-L-up** [microsoft/nni#5187]
**Describe the issue**:  
I'm just pruning the linear layer. Everything seemed fine, but the following problem occurred when I was about to use the ModelSpeedup module to speed up the model.

```
device = torch.device("cpu")
inputs =(torch.LongTensor([tokenizer_out['input_ids']]).to(device),torch.LongTensor([tokenizer_out['attention_mask']]).to(device))
ModelSpeedup(S_model, inputs, masks).speedup_model()
```

```
config_list = [{
        'sparsity_per_layer': 0.5,
        'op_types': ['Linear']
    }, {
        'exclude': True,
        'op_names': ['dense2']
    }]
```
```
bert_model.transformer.layer.0.attention.q_lin  sparsity :  0.5
bert_model.transformer.layer.0.attention.k_lin  sparsity :  0.5
bert_model.transformer.layer.0.attention.v_lin  sparsity :  0.5
bert_model.transformer.layer.0.attention.out_lin  sparsity :  0.5
bert_model.transformer.layer.0.ffn.lin1  sparsity :  0.5
bert_model.transformer.layer.0.ffn.lin2  sparsity :  0.5
bert_model.transformer.layer.1.attention.q_lin  sparsity :  0.5
bert_model.transformer.layer.1.attention.k_lin  sparsity :  0.5
bert_model.transformer.layer.1.attention.v_lin  sparsity :  0.5
bert_model.transformer.layer.1.attention.out_lin  sparsity :  0.5
bert_model.transformer.layer.1.ffn.lin1  sparsity :  0.5
bert_model.transformer.layer.1.ffn.lin2  sparsity :  0.5
bert_model.transformer.layer.2.attention.q_lin  sparsity :  0.5
bert_model.transformer.layer.2.attention.k_lin  sparsity :  0.5
bert_model.transformer.layer.2.attention.v_lin  sparsity :  0.5
bert_model.transformer.layer.2.attention.out_lin  sparsity :  0.5
bert_model.transformer.layer.2.ffn.lin1  sparsity :  0.5
bert_model.transformer.layer.2.ffn.lin2  sparsity :  0.5
bert_model.transformer.layer.3.attention.q_lin  sparsity :  0.5
bert_model.transformer.layer.3.attention.k_lin  sparsity :  0.5
bert_model.transformer.layer.3.attention.v_lin  sparsity :  0.5
bert_model.transformer.layer.3.attention.out_lin  sparsity :  0.5
bert_model.transformer.layer.3.ffn.lin1  sparsity :  0.5
bert_model.transformer.layer.3.ffn.lin2  sparsity :  0.5
cpu
[2022-10-26 08:50:04] start to speedup the model
no multi-dimension masks found.
[2022-10-26 08:50:05] infer module masks...
[2022-10-26 08:50:05] Update mask for bert_model.embeddings.word_embeddings
[2022-10-26 08:50:06] Update mask for bert_model.embeddings.aten::size.46
[2022-10-26 08:50:06] Update mask for bert_model.embeddings.aten::slice.47
[2022-10-26 08:50:06] Slice dim:0, Slice obj:slice(0, 9223372036854775807, 1)
[2022-10-26 08:50:06] Get attribute: bert_model
[2022-10-26 08:50:06] Get attribute: embeddings
[2022-10-26 08:50:06] Get attribute: position_ids
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.0.attention.aten::eq.61
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.1.attention.aten::eq.84
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.2.attention.aten::eq.107
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.3.attention.aten::eq.130
[2022-10-26 08:50:06] Update mask for bert_model.embeddings.aten::slice.48
[2022-10-26 08:50:06] Slice dim:1, Slice obj:slice(0, tensor([300]), 1)
[2022-10-26 08:50:06] Model has Slice operation, and the operand size=torch.Size([1, 512]), Slice object:(slice(None, None, None), slice(0, tensor([300]), 1))
[2022-10-26 08:50:06] Model has Slice operation, and the operand size=torch.Size([1, 512]), Slice object:(slice(None, None, None), slice(0, tensor([300]), 1))
[2022-10-26 08:50:06] Update mask for bert_model.embeddings.position_embeddings
[2022-10-26 08:50:06] Update mask for bert_model.embeddings.aten::add.49
[2022-10-26 08:50:06] Update mask for bert_model.embeddings.LayerNorm
[2022-10-26 08:50:06] Update mask for bert_model.embeddings.dropout
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.0.attention.q_lin
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.0.attention.k_lin
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.0.attention.v_lin
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.0.attention.aten::size.50
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.0.attention.aten::size.51
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.0.attention.aten::view.52
[2022-10-26 08:50:06] WARNING: throw some args away when calling the function "view"
[2022-10-26 08:50:06] WARNING: throw some args away when calling the function "view"
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.0.attention.aten::view.54
[2022-10-26 08:50:06] WARNING: throw some args away when calling the function "view"
[2022-10-26 08:50:06] WARNING: throw some args away when calling the function "view"
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.0.attention.aten::view.56
[2022-10-26 08:50:06] WARNING: throw some args away when calling the function "view"
[2022-10-26 08:50:06] WARNING: throw some args away when calling the function "view"
[2022-10-26 08:50:06] Update mask for bert_model.transformer.layer.0.attention.aten::view.62
[2022-10-26 08:50:06] WARNING: throw some args away when calling the function "view"
Traceback (most recent call last):
  File "/workspace/bert2distill_albert/prune_s2_main.py", line 67, in <module>
    prune_student_model(configs, dataManager, logger)
  File "/workspace/bert2distill_albert/engines/prune_distill_model.py", line 112, in prune_student_model
    ModelSpeedup(S_model, inputs, masks).speedup_model()
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 543, in speedup_model
    self.infer_modules_masks()
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 380, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 247, in update_direct_sparsity
    _auto_infer.update_direct_sparsity()
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 328, in update_direct_sparsity
    self.random_init()
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 138, in random_init
    randomize_tensor(tensor, start, end)
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/nni/compression/pytorch/utils/utils.py", line 72, in randomize_tensor
    torch.randint(int(start), int(end), tensor.size(),
RuntimeError: to - 1 is out of bounds for bool

```

**Environment**:
- NNI version:2.9
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:3.8
- PyTorch/TensorFlow version:1.12.1
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by J-shang** [comment]
hello @Smile-L-up,

in your file
```
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/nni/compression/pytorch/utils/utils.py"
```

please try change
```
def randomize_tensor(tensor, start=1, end=100):
    """
    Randomize the target tensor according to the given
    range.
    """
    assert isinstance(tensor, torch.Tensor)
    if tensor.dtype in torch_integer_dtype:
        # integer tensor can only be randomized by the torch.randint
        torch.randint(int(start), int(end), tensor.size(),
                      out=tensor.data, dtype=tensor.dtype)
        # pass
    else:
        # we can use nn.init.uniform_ to randomize this tensor
        # Note: the tensor that with integer type cannot be randomize
        # with nn.init.uniform_
        torch.nn.init.uniform_(tensor.data, start, end)
```
to
```
def randomize_tensor(tensor, start=1, end=100):
    """
    Randomize the target tensor according to the given
    range.
    """
    assert isinstance(tensor, torch.Tensor)
    if tensor.dtype in torch_integer_dtype:
        # integer tensor can only be randomized by the torch.randint
        if tensor.dtype is torch.bool:
            start, end = 0, 2
        torch.randint(int(start), int(end), tensor.size(),
                      out=tensor.data, dtype=tensor.dtype)
        # pass
    else:
        # we can use nn.init.uniform_ to randomize this tensor
        # Note: the tensor that with integer type cannot be randomize
        # with nn.init.uniform_
        torch.nn.init.uniform_(tensor.data, start, end)
```

we will fix this in nni 2.10

**Comment by Smile-L-up** [comment]
Wonderful ! That will work, but  need to duplicate that tensor, as shown in the following code.

```
def randomize_tensor(tensor, start=1, end=100):
    """
    Randomize the target tensor according to the given
    range.
    """
    assert isinstance(tensor, torch.Tensor)
    tensor = tensor.clone()
    if tensor.dtype in torch_integer_dtype:
        if tensor.dtype is torch.bool:
            start, end = 0, 2
        # integer tensor can only be randomized by the torch.randint
        torch.randint(int(start), int(end), tensor.size(),
                      out=tensor.data, dtype=tensor.dtype)
        # pass
    else:
        # we can use nn.init.uniform_ to randomize this tensor
        # Note: the tensor that with integer type cannot be randomize
        # with nn.init.uniform_
        torch.nn.init.uniform_(tensor.data, start, end)
```

Thanks again for your help!

**Comment by J-shang** [comment]
hello @Smile-L-up ,

why `tensor = tensor.clone()` is needed? in this case, the original tensor will not be randomized, and this function actually has no effect. Do you mean in your model, this bool tensor should not be randomized?

**Comment by Smile-L-up** [comment]
I just wanted it to run. I didn't think about it that much. If  not, the following problems will occur. So how do I handle this?

runtimeerror: unsupported operation: more than one element of the written-to tensor refers to a single memory location. please clone() the tensor before performing the operation.

**Comment by Smile-L-up** [comment]
In addition, when I try to make predictions after loading the accelerated model, the following problems occur.

Load the model
```
model = torch.load(model_path)
print(model)
model.eval()
print(model(torch.LongTensor([tokenizer_out['input_ids']]), torch.LongTensor([tokenizer_out['attention_mask']])))
```

The following error occurs:
```
Traceback (most recent call last):
  File "/workspace/bert2distill_albert/test_onnx.py", line 18, in <module>
    print(model(torch.LongTensor([tokenizer_out['input_ids']]), torch.LongTensor([tokenizer_out['attention_mask']])))
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/bert2distill_albert/engines/model.py", line 159, in forward
    bert_outputs = self.bert_model(inputs_ids_batch,att_mask_batch)[0]
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 549, in forward
    return self.transformer(
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 327, in forward
    layer_outputs = layer_module(
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 271, in forward
    sa_output = self.attention(
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 200, in forward
    q = shape(self.q_lin(query))  # (bs, n_heads, q_length, dim_per_head)
  File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 194, in shape
    return x.view(bs, -1, self.n_heads, dim_per_head).transpose(1, 2)
RuntimeError: shape '[1, -1, 12, 26]' is invalid for input of size 76200
```
This still seems to pass the original structure of transformers, leading to dimensional errors.

**Comment by J-shang** [comment]
> In addition, when I try to make predictions after loading the accelerated model, the following problems occur.
> 
> Load the model
> 
> ```
> model = torch.load(model_path)
> print(model)
> model.eval()
> print(model(torch.LongTensor([tokenizer_out['input_ids']]), torch.LongTensor([tokenizer_out['attention_mask']])))
> ```
> 
> The following error occurs:
> 
> ```
> Traceback (most recent call last):
>   File "/workspace/bert2distill_albert/test_onnx.py", line 18, in <module>
>     print(model(torch.LongTensor([tokenizer_out['input_ids']]), torch.LongTensor([tokenizer_out['attention_mask']])))
>   File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/workspace/bert2distill_albert/engines/model.py", line 159, in forward
>     bert_outputs = self.bert_model(inputs_ids_batch,att_mask_batch)[0]
>   File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 549, in forward
>     return self.transformer(
>   File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 327, in forward
>     layer_outputs = layer_module(
>   File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 271, in forward
>     sa_output = self.attention(
>   File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 200, in forward
>     q = shape(self.q_lin(query))  # (bs, n_heads, q_length, dim_per_head)
>   File "/root/miniconda3/envs/tf_nlp/lib/python3.8/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 194, in shape
>     return x.view(bs, -1, self.n_heads, dim_per_head).transpose(1, 2)
> RuntimeError: shape '[1, -1, 12, 26]' is invalid for input of size 76200
> ```
> 
> This still seems to pass the original structure of transformers, leading to dimensional errors.

Seems that you pruned the linear module in huggingface transformer attention, in fact, the linear in huggingface transformer attention has additional semantics (like multi-head), `ModelSpeedup` cannot perceive this.
For example, in your model has 12 heads for each layer, and each entire head should be pruned or kept, prune partial head should be forbidden.

So when you want to prune QKV in attention layer, please convert the masks to head index and use the `prune_heads`.

Here is a head convert and speedup with `prune_heads` example, (this is based on the log you gave, maybe you need to debug it):
```
model = ...
masks = ...
layers_num = 4

module_list = []
for i in range(0, layers_num):
    prefix = bert_model.transformer.layer.{i}.'
    # use the mask of linear V to indicate which head should be prune, you can also use other linear (Q, K, O)
    value_mask: torch.Tensor = attention_masks[prefix + 'attention.v_lin']['weight']
    head_mask = (value_mask.reshape(heads_num, -1).sum(-1) == 0.)
    # you can also use the following to ensure prune half of the heads
    # head_mask = (value_mask.reshape(heads_num, -1).sum(-1) < value_mask.reshape(heads_num, -1).sum(-1).topk(6)[0][-1])
    head_idxs = torch.arange(len(head_mask))[head_mask].long().tolist()
    print(f'layer {i} prune {len(head_idxs)} head: {head_idxs}')
    bert_model.transformer.layer[i].attention.prune_heads(head_idxs)
```

After prune heads, you can speedup ffn, in transformer, we found pruning ffn2 output dim will cause a serious loss of accuracy, but you can still try. Here we assume only prune ffn1 output dim (in fact, prune ffn1 output will also prune ffn2 input, so ffn2 will also be pruned):

```
head_pruned_model = ...
masks = ...
inputs = ...
ffn1_masks = {k, v for k, v in masks.items() if k.endswith('ffn.lin1')}
ModelSpeedup(head_pruned_model, inputs, ffn1_masks).speedup_model()
```

**Comment by Smile-L-up** [comment]
Hi, The first step looks a little confusing, so I just tried the second step, because it looked like i could just speed up ffn21 without doing the first step. ffn1_masks is filtered from masks. But similar mistakes still occur, can't I just prune the ffn1?

The config_list as follows:
```
    config_list = [{
        'sparsity_per_layer': 0.1,
        'op_types': ['Linear']
    }, {
        'exclude': True,
        'op_names': ['dense2']
    }]
```
The ffn1_masks as follows:
```
['bert_model.transformer.layer.0.ffn.lin1', 'bert_model.transformer.layer.1.ffn.lin1', 'bert_model.transformer.layer.2.ffn.lin1', 'bert_model.transformer.layer.3.ffn.lin1']
```
Also, for the first part, is there a complete example? [https://nni.readthedocs.io/en/stable/tutorials/pruning_bert_glue.html](url) 
is this one? or this one?[https://github.com/huggingface/transformers/blob/783d7d2629e97c5f0c5f9ef01b8c66410275c204/examples/research_projects/bertology/run_bertology.py](url)

**Comment by J-shang** [comment]
> Hi, The first step looks a little confusing, so I just tried the second step, because it looked like i could just speed up ffn1 without doing the first step. ffn1_masks is filtered from masks. But similar mistakes still occur, can't I just prune the ffn1?
> 
> The config_list as follows:
> 
> ```
>     config_list = [{
>         'sparsity_per_layer': 0.1,
>         'op_types': ['Linear']
>     }, {
>         'exclude': True,
>         'op_names': ['dense2']
>     }]
> ```
> 
> The ffn1_masks as follows:
> 
> ```
> ['bert_model.transformer.layer.0.ffn.lin1', 'bert_model.transformer.layer.1.ffn.lin1', 'bert_model.transformer.layer.2.ffn.lin1', 'bert_model.transformer.layer.3.ffn.lin1']
> ```
> 
> Also, for the first part, is there a complete example? [https://nni.readthedocs.io/en/stable/tutorials/pruning_bert_glue.html](url) is this one? or this one?[https://github.com/huggingface/transformers/blob/783d7d2629e97c5f0c5f9ef01b8c66410275c204/examples/research_projects/bertology/run_bertology.py](url)


yes. you can skip step 1, the first step is pruning the QKVO head. the following is an example, but it contains additional logic that you may not care.
[https://nni.readthedocs.io/en/stable/tutorials/pruning_bert_glue.html](https://github.com/microsoft/nni/issues/url)

Yes, you can only speedup ffn1, could you show your entire code for I could reproduce it to find the problem?
which model and pruner you used?

**Comment by Smile-L-up** [comment]
Hello, I tried to use prune_head for module pruning according to example [https://nni.readthedocs.io/en/stable/tutorials/pruning_bert_glue.html](url), but there was no pruning at all for attention heads. As I increased sparsity rate, there was a situation where all attention heads were pruned. Do you know the possible reason? Is it because there really is no attention heads to prune?  The model deals with the task of named entity recognition. Looking forward to your reply

**Comment by J-shang** [comment]
hello @Smile-L-up , if I understand correctly, the dim 0 of `out_lin` weight is not the head dim, but the dim 1 is. So if you want to use `out_lin` to denote which head should be pruned, different from using QKV mask, output linear mask should be transpose, here is an example you could have a try.

```
    for i in range(0, layers_num):
        prefix = f'bert_model.transformer.layer.{i}.'
        value_mask: torch.Tensor = attention_masks[prefix + 'attention.out_lin']['weight']
        ### only modify this line ###
        head_mask = (value_mask.transpose(0, 1).reshape(heads_num, -1).sum(-1) == 0.)
        head_idxs = torch.arange(len(head_mask))[head_mask].long().tolist()
        print(f'layer {i} prune {len(head_idxs)} head: {head_idxs}')
        if len(head_idxs) != heads_num:
            attention_pruned_model.bert_model.transformer.layer[i].attention.prune_heads(head_idxs)
            module_list.append(attention_pruned_model.bert_model.transformer.layer[i])
            # The final ffn weight remaining ratio is the half of the attention weight remaining ratio.
            # This is just an empirical configuration, you can use any other method to determine this sparsity.
            sparsity = 1 - (1 - len(head_idxs) / heads_num) * 0.5
            # here we use a simple sparsity schedule, we will prune ffn in 12 iterations, each iteration prune `sparsity_per_iter`.
            sparsity_per_iter = 1 - (1 - sparsity) ** (1 / 12)
            ffn_config_list.append({
                'op_names': [f'bert_model.transformer.layer.{len(layer_remained_idxs)}.ffn.lin1'],
                'sparsity': sparsity_per_iter
            })
            layer_remained_idxs.append(i)
```
