### ISSUE TITLE
prune pointpillar with mmdetection3d

### ISSUE THREAD

**Issue by qingzhouzhen** [microsoft/nni#5188]
I want to prune pointpillar on mmdetection3d framework, but the model has more than one input`def forward(self, img, img_metas, return_loss=True, **kwargs):`, which makes it not suitable for speedup: `ModelSpeedup(model, dummy_input=torch.rand([10, 3, 32, 32]).to(device), masks_file=masks).speedup_model()`
so I just prune and speedup the backbone: `model.backbone` follow steps:
step1 : load origin model
step2:  prune model, speedup model, save the speeduped model
step3 :   load speeduped model and finetune it
the reason I save model in step2 is I can not finetune it in mmdetection3d immediately if I prune the model in mmdetection3d.
the sparse ratio is 0.9(cut 10% weight with L1Norm), accuracy drops about 2%
**question is, am I right?**  
ps: finetune loss
![image-20221027120605758](https://user-images.githubusercontent.com/14066190/198223557-ca223120-d213-424f-9df3-9cd53d5cc277.png)

**Comment by Louis-J** [comment]
for many mmdetection3d models, there is a `forward_dummy` function in the model, so you can try to prune it by:
```python
    forward_orig = model.forward
    model.forward = model.forward_dummy
    # prune ... complete
    model.forward = forward_orig
```

or you can write a custom forward if the forward_dummy cannot use.

**Comment by qingzhouzhen** [comment]
> for many mmdetection3d models, there is a `forward_dummy` function in the model, so you can try to prune it by:
> 
> ```python
>     forward_orig = model.forward
>     model.forward = model.forward_dummy
>     # prune ... complete
>     model.forward = forward_orig
> ```
> 
> or you can write a custom forward if the forward_dummy cannot be used.

I follw your suggestion, but I got an error:
```
in the future. This means that the trace might not generalize to other inputs!
  batch_size = coors[-1, 0].item() + 1
Traceback (most recent call last):
  File "tools/pruner_train_dummpy2.py", line 296, in <module>
    main()
  File "tools/pruner_train_dummpy2.py", line 255, in main
    forward_orig = model.forward
  File "/opt/conda/lib/python3.7/site-packages/nni/compression/pytorch/speedup/compressor.py", line 73, in __init__
    self.torch_graph = build_module_graph(model, self.dummy_input)
  File "/opt/conda/lib/python3.7/site-packages/nni/common/graph_utils.py", line 25, in build_module_graph
    return TorchModuleGraph(model, dummy_input)
  File "/opt/conda/lib/python3.7/site-packages/nni/common/graph_utils.py", line 265, in __init__
    super().__init__(model, dummy_input, traced_model)
  File "/opt/conda/lib/python3.7/site-packages/nni/common/graph_utils.py", line 67, in __init__
    self._trace(model, dummy_input)
  File "/opt/conda/lib/python3.7/site-packages/nni/common/graph_utils.py", line 91, in _trace
    self.trace = torch.jit.trace(model, dummy_input, **kw_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/__init__.py", line 955, in trace
    check_tolerance, strict, _force_outplace, _module_class)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1109, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, strict, _force_outplace)
RuntimeError: 0 INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1595629403081/work/torch/csrc/jit/ir/alias_analysis.cpp":465, please report a bug to PyTorch. We don't have an op for aten::to but it isn't a special case.  Argument types: Tensor, None, int, Device, bool, bool, bool, None,
```
it seems op not support?

**Comment by Louis-J** [comment]
It seems that this model cannot be traced by torch.jit.trace to get a torchscript model. We can only do speedup on torchscript models.
there is a page https://mmclassification.readthedocs.io/en/latest/tools/pytorch2torchscript.html but I don't know whether it works.
In this case only, you can try another pytorch version or another python version. It may help.
