### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by Faye-XDU** [microsoft/nni#5190]
**Describe the issue**: When I finished the whole nni experiment successfully, NNIManager prompted an error: `ERROR (NNIManager) TypeError: Cannot read properties of undefined (reading 'startsWith')`. I don't know if this will have any effect on the completion of the experiment

**Environment**:
- NNI version: nni
- Training service (local|remote|pai|aml|etc): local
- Client OS: linux
- Python version: 3.8
- PyTorch/TensorFlow version: 1.11
- Is conda/virtualenv/venv used?:conda
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!): 
```
import http
import nni

search_space = {
    'g_epoch': {'_type': 'randint', '_value': [50, 1000]},
    'lr': {'_type': 'loguniform', '_value': [0.0001, 0.1]},
    'g_lr': {'_type': 'loguniform', '_value': [0.001, 1]},
    'momentum': {'_type': 'uniform', '_value': [0, 1]},
}

from nni.experiment import Experiment
experiment = Experiment('local')

experiment.config.trial_command = 'python nni.py'
experiment.config.trial_code_directory = '.'


experiment.config.search_space = search_space

experiment.config.tuner.name = 'TPE'
experiment.config.tuner.class_args['optimize_mode'] = 'maximize'

experiment.config.max_trial_number = 100
experiment.config.trial_concurrency = 2

experiment.run(8081)
input()
```

 - Search space: 
```
search_space = {
    'g_epoch': {'_type': 'randint', '_value': [50, 1000]},
    'lr': {'_type': 'loguniform', '_value': [0.0001, 0.1]},
    'g_lr': {'_type': 'loguniform', '_value': [0.001, 1]},
    'momentum': {'_type': 'uniform', '_value': [0, 1]},
} 
```

**Log message**:
 - nnimanager.log: (Clip)
```
[2022-10-28 07:35:08] INFO (NNIManager) Trial job XNkGA status changed from WAITING to RUNNING
[2022-10-28 07:35:08] INFO (NNIManager) Change NNIManager status from: RUNNING to: NO_MORE_TRIAL
[2022-10-28 07:38:13] INFO (NNIManager) Trial job XNkGA status changed from RUNNING to FAILED
[2022-10-28 07:59:44] INFO (NNIManager) Trial job Fh6uO status changed from RUNNING to SUCCEEDED
[2022-10-28 07:59:44] INFO (NNIManager) Change NNIManager status from: NO_MORE_TRIAL to: DONE
[2022-10-28 07:59:44] INFO (NNIManager) Experiment done.
[2022-10-28 07:59:54] INFO (NNIManager) Change NNIManager status from: DONE to: STOPPING
[2022-10-28 07:59:54] INFO (NNIManager) Stopping experiment, cleaning up ...
[2022-10-28 07:59:57] INFO (LocalTrainingService) Stopping local machine training service...
[2022-10-28 07:59:57] INFO (NNIManager) Change NNIManager status from: STOPPING to: STOPPED
[2022-10-28 07:59:57] INFO (NNIManager) Experiment stopped.
[2022-10-28 07:59:57] INFO (NNITensorboardManager) Forced stopping all tensorboard task.
[2022-10-28 07:59:57] INFO (NNITensorboardManager) All tensorboard task stopped.
[2022-10-28 07:59:57] INFO (NNITensorboardManager) Tensorboard manager stopped.
[2022-10-28 07:59:57] ERROR (NNIManager) TypeError: Cannot read properties of undefined (reading 'startsWith')
```

 - dispatcher.log: 
```
[2022-10-27 11:06:07] INFO (nni.experiment/MainThread) Creating experiment, Experiment ID: 
[2022-10-27 11:06:07] INFO (nni.experiment/MainThread) Starting web server...
[2022-10-27 11:06:08] INFO (nni.experiment/MainThread) Setting up...
[2022-10-27 11:06:08] INFO (nni.experiment/MainThread) Web portal URLs: [36mhttp://127.0.0.1:8081 http://172.16.3.140:8081 http://172.20.208.8:8081 http://172.17.0.1:8081[0m
[2022-10-27 11:06:09] INFO (numexpr.utils/MainThread) Note: detected 256 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
[2022-10-27 11:06:09] INFO (numexpr.utils/MainThread) Note: NumExpr detected 256 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2022-10-27 11:06:09] INFO (numexpr.utils/MainThread) NumExpr defaulting to 8 threads.
[2022-10-27 11:06:09] INFO (nni.tuner.tpe/MainThread) Using random seed 655874007
[2022-10-27 11:06:09] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2022-10-28 07:59:54] INFO (nni.experiment/MainThread) Stopping experiment, please wait...
[2022-10-28 07:59:54] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2022-10-28 07:59:56] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated
```
 

**How to reproduce it?**:  Just conducting normal experiments

**Comment by liuzhe-lz** [comment]
I guess it's just logging states and does not harm.
However please provide the full NNI manager log for us to debug it. Thanks.

**Comment by Faye-XDU** [comment]
> I guess it's just logging states and does not harm. However please provide the full NNI manager log for us to debug it. Thanks.

The full NNI manager log is too long to provide.
```
[2022-10-27 11:06:08] INFO (main) Start NNI manager
[2022-10-27 11:06:08] INFO (NNIDataStore) Datastore initialization done
[2022-10-27 11:06:08] INFO (RestServer) Starting REST server at port 8081, URL prefix: "/"
[2022-10-27 11:06:08] INFO (RestServer) REST server started.
[2022-10-27 11:06:08] INFO (NNIManager) Starting experiment: b8qdzmi2
[2022-10-27 11:06:08] INFO (NNIManager) Setup training service...
[2022-10-27 11:06:08] INFO (LocalTrainingService) Construct local machine training service.
[2022-10-27 11:06:08] INFO (NNIManager) Setup tuner...
[2022-10-27 11:06:08] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2022-10-27 11:06:08] INFO (NNIManager) Add event listeners
[2022-10-27 11:06:08] INFO (LocalTrainingService) Run local machine training service.
........
[2022-10-28 07:35:08] INFO (NNIManager) Trial job XNkGA status changed from WAITING to RUNNING
[2022-10-28 07:35:08] INFO (NNIManager) Change NNIManager status from: RUNNING to: NO_MORE_TRIAL
[2022-10-28 07:38:13] INFO (NNIManager) Trial job XNkGA status changed from RUNNING to FAILED
[2022-10-28 07:59:44] INFO (NNIManager) Trial job Fh6uO status changed from RUNNING to SUCCEEDED
[2022-10-28 07:59:44] INFO (NNIManager) Change NNIManager status from: NO_MORE_TRIAL to: DONE
[2022-10-28 07:59:44] INFO (NNIManager) Experiment done.
[2022-10-28 07:59:54] INFO (NNIManager) Change NNIManager status from: DONE to: STOPPING
[2022-10-28 07:59:54] INFO (NNIManager) Stopping experiment, cleaning up ...
[2022-10-28 07:59:57] INFO (LocalTrainingService) Stopping local machine training service...
[2022-10-28 07:59:57] INFO (NNIManager) Change NNIManager status from: STOPPING to: STOPPED
[2022-10-28 07:59:57] INFO (NNIManager) Experiment stopped.
[2022-10-28 07:59:57] INFO (NNITensorboardManager) Forced stopping all tensorboard task.
[2022-10-28 07:59:57] INFO (NNITensorboardManager) All tensorboard task stopped.
[2022-10-28 07:59:57] INFO (NNITensorboardManager) Tensorboard manager stopped.
[2022-10-28 07:59:57] ERROR (NNIManager) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at new RestServer (***/lib/python3.8/site-packages/nni_node/rest_server/index.js:50:37)
    at Object.get (***/lib/python3.8/site-packages/nni_node/node_modules/typescript-ioc/es5.js:202:108)
    at SingletonScope.resolve (***/lib/python3.8/site-packages/nni_node/node_modules/typescript-ioc/es5.js:290:33)
    at ConfigImpl.getInstance (***/lib/python3.8/site-packages/nni_node/node_modules/typescript-ioc/es5.js:252:30)
    at Function.IoCContainer.get (***/lib/python3.8/site-packages/nni_node/node_modules/typescript-ioc/es5.js:147:23)
    at Function.Container.get (***/lib/python3.8/site-packages/nni_node/node_modules/typescript-ioc/es5.js:93:29)
    at Object.get (***/lib/python3.8/site-packages/nni_node/common/component.js:33:26)
    at NNIManager.stopExperimentBottomHalf (***/lib/python3.8/site-packages/nni_node/core/nnimanager.js:312:29)
```

Also I would like to ask if I can't open the web page provided by nni, how should I get the right parameters that I end up with.

**Comment by Lijiaoa** [comment]
When the experiment status is `stopped`, the webui has also stopped. So you can use `nnictl resume your-experiment-ID` to get the experiment running again. @Faye-XDU

**Comment by Faye-XDU** [comment]
> When the experiment status is `stopped`, the webui has also stopped. So you can use `nnictl resume your-experiment-ID` to get the experiment running again. @Faye-XDU

But my biggest issue is that I can't access the URL when I'm running on a remote server.

**Comment by Lijiaoa** [comment]
> > When the experiment status is `stopped`, the webui has also stopped. So you can use `nnictl resume your-experiment-ID` to get the experiment running again. @Faye-XDU
> 
> But my biggest issue is that I can't access the URL when I'm running on a remote server.

I want to know your nni version you used.

**Comment by liuzhe-lz** [comment]
> Also I would like to ask if I can't open the web page provided by nni, how should I get the right parameters that I end up with.

You can use [`nnictl experiment export`](https://nni.readthedocs.io/en/stable/reference/nnictl.html#nnictl-experiment-export)

**Comment by Faye-XDU** [comment]
> > > When the experiment status is `stopped`, the webui has also stopped. So you can use `nnictl resume your-experiment-ID` to get the experiment running again. @Faye-XDU
> > 
> > 
> > But my biggest issue is that I can't access the URL when I'm running on a remote server.
> 
> I want to know your nni version you used.

`nni 2.7`

**Comment by Faye-XDU** [comment]
> > Also I would like to ask if I can't open the web page provided by nni, how should I get the right parameters that I end up with.
> 
> You can use [`nnictl experiment export`](https://nni.readthedocs.io/en/stable/reference/nnictl.html#nnictl-experiment-export)

Thanks for your reply! I will try it later.
