### ISSUE TITLE
ERROR: Graphs differed across invocations!

### ISSUE THREAD

**Issue by shihuiyu** [microsoft/nni#5193]
**Describe the issue**:

When i pruned yolov7 model, i met this error:

“
Traceback (most recent call last):
  File "/home/shihuiyu/yolov7-main/prune.py", line 750, in <module>
    train(hyp, opt, device, tb_writer)
  File "/home/shihuiyu/yolov7-main/prune.py", line 194, in train
    m_speedup = ModelSpeedup(model, dummy_input=torch.rand([1,3,640,640]).to(device), masks_file='/home/shihuiyu/yolov7-main/mask_temp_prune.pth')
  File "/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/nni/compression/pytorch/speedup/compressor.py", line 73, in __init__
    self.torch_graph = build_module_graph(model, self.dummy_input)
  File "/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/nni/common/graph_utils.py", line 25, in build_module_graph
    return TorchModuleGraph(model, dummy_input)
  File "/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/nni/common/graph_utils.py", line 265, in __init__
    super().__init__(model, dummy_input, traced_model)
  File "/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/nni/common/graph_utils.py", line 67, in __init__
    self._trace(model, dummy_input)
  File "/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/nni/common/graph_utils.py", line 91, in _trace
    self.trace = torch.jit.trace(model, dummy_input, **kw_args)
  File "/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/jit/_trace.py", line 741, in trace
    return trace_module(
  File "/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/jit/_trace.py", line 983, in trace_module
    _check_trace(
  File "/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/jit/_trace.py", line 526, in _check_trace
    raise TracingCheckError(*diag_info)
torch.jit._trace.TracingCheckError: Tracing failed sanity checks!
ERROR: Graphs differed across invocations!
	Graph diff:
		  graph(%self.1 : __torch__.models.yolo.Model,
		        %x.1 : Tensor):
		    %model : __torch__.torch.nn.modules.container.Sequential = prim::GetAttr[name="model"](%self.1)
		    %_77 : __torch__.models.yolo.IDetect = prim::GetAttr[name="77"](%model)
		    %model.153 : __torch__.torch.nn.modules.container.Sequential = prim::GetAttr[name="model"](%self.1)
		    %_76 : __torch__.models.common.Conv = prim::GetAttr[name="76"](%model.153)
		    %model.151 : __torch__.torch.nn.modules.container.Sequential = prim::GetAttr[name="model"](%self.1)
                     ………………
		    %1598 : float = prim::Constant[value=0.10000000000000001](), scope: __module.model.76/__module.model.76.act # /home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/functional.py:1473:0
		    %1599 : float = prim::Constant[value=0.029999999999999999](), scope: __module.model.76/__module.model.76.bn # /home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/functional.py:2282:0
		    %1600 : float = prim::Constant[value=0.001](), scope: __module.model.76/__module.model.76.bn # /home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/functional.py:2282:0
		    %1601 : NoneType = prim::Constant(), scope: __module.model.76/__module.model.76.conv
		    %1602 : int = prim::Constant[value=1](), scope: __module.model.76/__module.model.76.conv # /home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/modules/conv.py:442:0
		    %1603 : bool = prim::Constant[value=0](), scope: __module.model.76/__module.model.76.conv # /home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/modules/conv.py:442:0
		    %1604 : int = prim::Constant[value=0](), scope: __module.model.76/__module.model.76.conv # /home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/modules/conv.py:442:0
		    %1605 : bool = prim::Constant[value=1](), scope: __module.model.76/__module.model.76.conv # /home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/modules/conv.py:442:0
		    %act : __torch__.torch.nn.modules.activation.LeakyReLU = prim::GetAttr[name="act"](%_76)
		    %bn : __torch__.torch.nn.modules.batchnorm.BatchNorm2d = prim::GetAttr[name="bn"](%_76)
		    %conv : __torch__.torch.nn.modules.conv.Conv2d = prim::GetAttr[name="conv"](%_76)
		    %weight.443 : Tensor = prim::GetAttr[name="weight"](%conv)
		    %1610 : int[] = prim::ListConstruct(%1602, %1602), scope: __module.model.76/__module.model.76.conv
		    %1611 : int[] = prim::ListConstruct(%1602, %1602), scope: __module.model.76/__module.model.76.conv
		    %1612 : int[] = prim::ListConstruct(%1602, %1602), scope: __module.model.76/__module.model.76.conv
		    %1613 : int[] = prim::ListConstruct(%1604, %1604), scope: __module.model.76/__module.model.76.conv
		    %input.311 : Tensor = aten::_convolution(%input.309, %weight.443, %1601, %1610, %1611, %1612, %1603, %1613, %1602, %1605, %1603, %1605, %1605), scope: __module.model.76/__module.model.76.conv # /home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/modules/conv.py:442:0
		    %running_var : Tensor = prim::GetAttr[name="running_var"](%bn)
		    %running_mean : Tensor = prim::GetAttr[name="running_mean"](%bn)
		    %bias.225 : Tensor = prim::GetAttr[name="bias"](%bn)
		    %weight.445 : Tensor = prim::GetAttr[name="weight"](%bn)
		    %input.313 : Tensor = aten::batch_norm(%input.311, %weight.445, %bias.225, %running_mean, %running_var, %1603, %1599, %1600, %1605), scope: __module.model.76/__module.model.76.bn # /home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/functional.py:2282:0
		    %x.11 : Tensor = aten::leaky_relu_(%input.313, %1598), scope: __module.model.76/__module.model.76.act # /home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/functional.py:1473:0
		+   %1621 : Tensor = prim::Constant[value=<Tensor>](), scope: __module.model.77 # /home/shihuiyu/yolov7-main/models/yolo.py:107:0
		+   %1622 : Tensor = prim::Constant[value=<Tensor>](), scope: __module.model.77 # /home/shihuiyu/yolov7-main/models/yolo.py:107:0
		-   %1621 : int = prim::Constant[value=-1](), scope: __module.model.77 # /home/shihuiyu/yolov7-main/models/yolo.py:113:0
		?       ^
		+   %1623 : int = prim::Constant[value=-1](), scope: __module.model.77 # /home/shihuiyu/yolov7-main/models/yolo.py:113:0
		?       ^
                 …………
		+   %1769 : (Tensor, Tensor, Tensor, Tensor) = prim::TupleConstruct(%1674, %1711, %1748, %1768)
		?     ^^^                                                                     ^^     ^^    ++
		-   %236 : Tensor, %237 : Tensor, %238 : Tensor, %239 : Tensor = prim::TupleUnpack(%1805)
		?                                                                                    ^^^
		+   %236 : Tensor, %237 : Tensor, %238 : Tensor, %239 : Tensor = prim::TupleUnpack(%1769)
		?                                                                                    ^^^
		    %240 : Tensor[] = prim::ListConstruct(%236, %237, %238)
		    %241 : (Tensor, Tensor[]) = prim::TupleConstruct(%239, %240)
		    return (%241)
	First diverging operator:
	Node diff:
		- %model : __torch__.torch.nn.modules.container.Sequential = prim::GetAttr[name="model"](%self.1)
		+ %model : __torch__.torch.nn.modules.container.___torch_mangle_509.Sequential = prim::GetAttr[name="model"](%self.1)
		?                                               ++++++++++++++++++++
ERROR: Tensor-valued Constant nodes differed in value across invocations. This often indicates that the tracer has encountered untraceable code.
	Node:
		%1622 : Tensor = prim::Constant[value={2}](), scope: __module.model.77 # /home/shihuiyu/yolov7-main/models/yolo.py:112:0
	Source Location:
		/home/shihuiyu/yolov7-main/models/yolo.py(112): forward
		/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/modules/module.py(1090): _slow_forward
		/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/modules/module.py(1102): _call_impl
		/home/shihuiyu/yolov7-main/models/yolo.py(357): forward_once
		/home/shihuiyu/yolov7-main/models/yolo.py(331): forward
		/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/modules/module.py(1090): _slow_forward
		/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/nn/modules/module.py(1102): _call_impl
		/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/jit/_trace.py(958): trace_module
		/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/torch/jit/_trace.py(741): trace
		/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/nni/common/graph_utils.py(91): _trace
		/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/nni/common/graph_utils.py(67): __init__
		/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/nni/common/graph_utils.py(265): __init__
		/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/nni/common/graph_utils.py(25): build_module_graph
		/home/shihuiyu/.conda/envs/shihuiyu/lib/python3.9/site-packages/nni/compression/pytorch/speedup/compressor.py(73): __init__
		/home/shihuiyu/yolov7-main/prune.py(194): train
		/home/shihuiyu/yolov7-main/prune.py(750): <module>
	Comparison exception: 	The values for attribute 'shape' do not match: torch.Size([]) != torch.Size([1, 1, 40, 40, 2]).
”

I saw someone raise similar problems, but it seemed that his model was different.

Can you help me?

**Environment**:
- NNI version: 2.9
- Training service (local|remote|pai|aml|etc): A100
- Client OS: Linux
- Server OS (for remote mode only): Linux
- Python version: 3.9.7
- PyTorch/TensorFlow version: Pytorch 1.10.0
- Is conda/virtualenv/venv used?: Yes
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!):

“
config_list = [
        {'sparsity': 0.75, 'op_names':['model.0.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.1.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.2.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.3.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.4.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.5.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.7.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.9.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.10.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.11.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.12.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.14.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.16.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.17.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.18.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.19.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.21.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.23.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.24.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.25.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.26.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.28.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.29.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.30.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.35.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.37.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.40.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.42.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.43.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.44.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.45.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.47.conv'], 'op_types': ['Conv2d']},
        {'sparsity': 0.75, 'op_names':['model.50.conv'], 'op_types': ['Conv2d']},
      ]

    pruner = L1FilterPruner(model, config_list)
    pruner.compress()
    pruner.export_model('/home/shihuiyu/yolov7-main/model_temp_prune.pth', '/home/shihuiyu/yolov7-main/mask_temp_prune.pth')
    pruner._unwrap_model()
    m_speedup = ModelSpeedup(model, dummy_input=torch.rand([1,3,640,640]).to(device), masks_file='/home/shihuiyu/yolov7-main/mask_temp_prune.pth')
    m_speedup.speedup_model()
”

 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:
My git is “https://github.com/WongKinYiu/yolov7” and the model is "https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt”.

**Comment by Louis-J** [comment]
sorry i have no time to reproduce it now. i'll do after refactored the ModelSpeedup.

**Comment by sipie800** [comment]
the exact issue is happening at yolov8s.pt

**Comment by aidevmin** [comment]
@Louis-J 
I have same error when pruning yolov7 with APoz. Please update your status of this problem.
