### ISSUE TITLE
doesn't support lr scheduler while using pytorch lightning evaluator

### ISSUE THREAD

**Issue by xiadingZ** [microsoft/nni#5234]
**Describe the issue**:
When I use pytorch lightning evaluator,  I can't create lr scheduler in `configure_optimizers`
here is part of my  code
```python
    # will throw error
    def configure_optimizers(self) -> torch.optim.Optimizer:
        """
        Create the optimizer for the model.
        """
        optim = Adam(self.parameters(), lr=self.learning_rate)
        scheduler = lr_scheduler.ExponentialLR(optim, gamma=0.9)
        return [optim], [scheduler]

    # correct
    def configure_optimizers(self) -> torch.optim.Optimizer:
        """
        Create the optimizer for the model.
        """
        optim = Adam(self.parameters(), lr=self.learning_rate)
        #scheduler = lr_scheduler.ExponentialLR(optim, gamma=0.9)
        return optim
```

**Environment**:
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc): local
- Client OS: linux
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: 1.13.0
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Log message**:
 - nnimanager.log:
```
[2022-11-18 17:35:09] INFO (main) Start NNI manager
[2022-11-18 17:35:09] INFO (NNIDataStore) Datastore initialization done
[2022-11-18 17:35:09] INFO (RestServer) Starting REST server at port 33327, URL prefix: "/"
[2022-11-18 17:35:09] INFO (RestServer) REST server started.
[2022-11-18 17:35:10] INFO (NNIManager) Starting experiment: v71t6wqi
[2022-11-18 17:35:10] INFO (NNIManager) Setup training service...
[2022-11-18 17:35:10] INFO (LocalTrainingService) Construct local machine training service.
[2022-11-18 17:35:10] INFO (NNIManager) Setup tuner...
[2022-11-18 17:35:10] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2022-11-18 17:35:10] INFO (NNIManager) Add event listeners
[2022-11-18 17:35:10] INFO (LocalTrainingService) Run local machine training service.
[2022-11-18 17:35:10] WARNING (GPUScheduler) gpu_metrics file does not exist!
[2022-11-18 17:35:10] INFO (NNIManager) NNIManager received command from dispatcher: ID,
[2022-11-18 17:35:10] INFO (ShutdownManager) Initiate shutdown: REST request
[2022-11-18 17:35:10] INFO (RestServer) Stopping REST server.
[2022-11-18 17:35:10] INFO (NNIManager) Change NNIManager status from: RUNNING to: STOPPING
[2022-11-18 17:35:10] INFO (NNIManager) Stopping experiment, cleaning up ...
[2022-11-18 17:35:10] INFO (LocalTrainingService) Stopping local machine training service...
[2022-11-18 17:35:10] INFO (NNIManager) Change NNIManager status from: STOPPING to: STOPPED
[2022-11-18 17:35:10] INFO (NNIManager) Experiment stopped.
[2022-11-18 17:35:10] INFO (NNITensorboardManager) Forced stopping all tensorboard task.
[2022-11-18 17:35:10] INFO (NNITensorboardManager) All tensorboard task stopped.
[2022-11-18 17:35:10] INFO (NNITensorboardManager) Tensorboard manager stopped.
[2022-11-18 17:35:13] INFO (RestServer) REST server stopped.
[2022-11-18 17:35:13] INFO (ShutdownManager) Shutdown complete.
```

 - dispatcher.log:
```
➜  tactis-master bash train.sh
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[2022-11-18 17:35:09] Creating experiment, Experiment ID: v71t6wqi
[2022-11-18 17:35:09] Starting web server...
[2022-11-18 17:35:10] Setting up...
[2022-11-18 17:35:10] Web portal URLs: http://127.0.0.1:33327 http://10.99.48.30:33327 http://10.99.50.30:33327 http://10.99.49.30:33327 http://10.178.63.1:33327
[2022-11-18 17:35:10] Dispatcher started
Traceback (most recent call last):
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/common/serializer.py", line 791, in get_hybrid_cls_or_func_name
    name = _get_cls_or_func_name(cls_or_func)
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/common/serializer.py", line 770, in _get_cls_or_func_name
    raise ImportError('Cannot use a path to identify something from __main__.')
ImportError: Cannot use a path to identify something from __main__.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiading/tactis-master/main.py", line 254, in <module>
    main(
  File "/home/xiading/tactis-master/main.py", line 198, in main
    exp.run(exp_config, port)
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/nas/experiment/pytorch.py", line 298, in run
    self._save_experiment_checkpoint(base_model_ir, self.applied_mutators, self.strategy,
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/nas/experiment/pytorch.py", line 226, in _save_experiment_checkpoint
    dump(base_model_ir._dump(), fp, pickle_size_limit=int(os.getenv('PICKLE_SIZE_LIMIT', 64 * 1024)))
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/common/serializer.py", line 341, in dump
    result = _dump(
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/common/serializer.py", line 390, in _dump
    return json_tricks.dump(obj, fp, obj_encoders=encoders, **json_tricks_kwargs)
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/json_tricks/nonp.py", line 135, in dump
    txt = dumps(obj, sort_keys=sort_keys, cls=cls, obj_encoders=obj_encoders, extra_obj_encoders=extra_obj_encoders,
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/json_tricks/nonp.py", line 109, in dumps
    txt = combined_encoder.encode(obj)
  File "/home/xiading/miniconda3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/xiading/miniconda3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/json_tricks/encoders.py", line 77, in default
    obj = encoder(obj, primitives=self.primitives, is_changed=id(obj) != prev_id, properties=self.properties)
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/json_tricks/utils.py", line 66, in wrapper
    return encoder(*args, **{k: v for k, v in kwargs.items() if k in names})
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/common/serializer.py", line 839, in _json_tricks_serializable_object_encode
    ret = {'__symbol__': get_hybrid_cls_or_func_name(obj.trace_symbol)}
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/common/serializer.py", line 797, in get_hybrid_cls_or_func_name
    raise ValueError(f'Pickle too large when trying to dump {cls_or_func}. '
ValueError: Pickle too large when trying to dump <class '__main__.TACTiSModule'>. Please try to raise pickle_size_limit if you insist.
[2022-11-18 17:35:10] Stopping experiment, please wait...
[2022-11-18 17:35:10] Dispatcher exiting...
[2022-11-18 17:35:13] Dispatcher terminiated
[2022-11-18 17:35:13] Experiment stopped
```
 - nnictl stdout and stderr:

**Comment by ultmaster** [comment]
Could you try to raise the pickle size limit to 1MB by `export PICKLE_SIZE_LIMIT=1048576`?

**Comment by xiaoerqi** [comment]
Thank you for your advice ，but  after raise the pickle size limit to 1MB by export PICKLE_SIZE_LIMIT=1048576, it also have same error：
Traceback (most recent call last):
  File "NAS/grid_search.py", line 128, in <module>
    exp.run(exp_config)
  File "/meda_home/ai0400/miniconda3/envs/tf2-GPU/lib/python3.8/site-packages/nni/nas/experiment/pytorch.py", line 298, in run
    self._save_experiment_checkpoint(base_model_ir, self.applied_mutators, self.strategy,
  File "/meda_home/ai0400/miniconda3/envs/tf2-GPU/lib/python3.8/site-packages/nni/nas/experiment/pytorch.py", line 228, in _save_experiment_checkpoint
    dump(applied_mutators, fp)
  File "/meda_home/ai0400/miniconda3/envs/tf2-GPU/lib/python3.8/site-packages/nni/common/serializer.py", line 341, in dump
    result = _dump(
  File "/meda_home/ai0400/miniconda3/envs/tf2-GPU/lib/python3.8/site-packages/nni/common/serializer.py", line 390, in _dump
    return json_tricks.dump(obj, fp, obj_encoders=encoders, **json_tricks_kwargs)
  File "/meda_home/ai0400/.local/lib/python3.8/site-packages/json_tricks/nonp.py", line 134, in dump
    txt = dumps(obj, sort_keys=sort_keys, cls=cls, obj_encoders=obj_encoders, extra_obj_encoders=extra_obj_encoders,
  File "/meda_home/ai0400/.local/lib/python3.8/site-packages/json_tricks/nonp.py", line 106, in dumps
    txt = cls(sort_keys=sort_keys, obj_encoders=encoders, allow_nan=allow_nan,
  File "/meda_home/ai0400/miniconda3/envs/tf2-GPU/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/meda_home/ai0400/miniconda3/envs/tf2-GPU/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/meda_home/ai0400/.local/lib/python3.8/site-packages/json_tricks/encoders.py", line 76, in default
    obj = encoder(obj, primitives=self.primitives, is_changed=id(obj) != prev_id, properties=self.properties)
  File "/meda_home/ai0400/.local/lib/python3.8/site-packages/json_tricks/utils.py", line 66, in wrapper
    return encoder(*args, **{k: v for k, v in kwargs.items() if k in names})
  File "/meda_home/ai0400/miniconda3/envs/tf2-GPU/lib/python3.8/site-packages/nni/common/serializer.py", line 864, in _json_tricks_any_object_encode
    raise PayloadTooLarge(f'Pickle too large when trying to dump {obj}. This might be caused by classes that are '
nni.common.serializer.PayloadTooLarge: Pickle too large when trying to dump <nni.nas.nn.pytorch.mutator.ParameterChoiceMutator object at 0x7fe981440e80>. This might be caused by classes that are not decorated by @nni.trace. Another option is to force bytes pickling and try to raise pickle_size_limit.

**Comment by Lijiaoa** [comment]
@xiadingZ Any updates?
