### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'input'

### ISSUE THREAD

**Issue by dreamlychina** [microsoft/nni#5259]
**Describe the issue**:
[2022-12-02 16:25:47] start to speedup the model
[2022-12-02 16:25:48] infer module masks...
[2022-12-02 16:25:48] Update mask for .prim::TupleUnpack.162
[2022-12-02 16:25:48] Update mask for module.init_conv.0
Traceback (most recent call last):
  File "main.py", line 287, in <module>
    main()
  File "main.py", line 248, in main
    ModelSpeedup(model, torch.rand(1, 3, 224, 224).cuda(), masks).speedup_model()
  File "/meda_home/ai0446/thirdparty/miniconda3/envs/tf2-GPU/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 546, in speedup_model
    self.infer_modules_masks()
  File "/meda_home/ai0446/thirdparty/miniconda3/envs/tf2-GPU/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 383, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/meda_home/ai0446/thirdparty/miniconda3/envs/tf2-GPU/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 244, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
  File "/meda_home/ai0446/thirdparty/miniconda3/envs/tf2-GPU/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "/meda_home/ai0446/thirdparty/miniconda3/envs/tf2-GPU/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'input'

**Environment**: 
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc): remote
- Client OS: 
- Server OS (for remote mode only): 
- Python version:3.8
- PyTorch/TensorFlow version: pytorch
- Is conda/virtualenv/venv used?: virtualenv
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:

**How to reproduce it?**:

model = MobileNetV3(model_mode=args.model_mode, num_classes=num_classes, multiplier=args.multiplier, dropout_rate=args.dropout).to(device)
for epoch in range(epoch, args.epochs):
            if epoch==10:
                config_list = [{'sparsity_per_layer': 0.5,
                                'op_types': ['Conv2d']}]
                pruner = L1NormPruner(model, config_list)
                print(model)
                _, masks = pruner.compress()
                pruner._unwrap_model()
                ModelSpeedup(model, torch.rand(1, 3, 224, 224).cuda(), masks).speedup_model()
                print(net)
DataParallel(
  (module): MobileNetV3(
    (init_conv): Sequential(
      (0): PrunerModuleWrapper(
        (module): Conv2d(3, 16, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      )
      (1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): h_swish()
    )

Is the DDP cause the problem??

**Comment by Louis-J** [comment]
could you offer the code to help me reproducing it? it seems like a bug in `pruner._unwrap_model`.

**Comment by J-shang** [comment]
Closed due to no reply for a long time, please reopen if have any questions.
