### ISSUE TITLE
Error  Dispatcher stream error, tuner may have crashed.

### ISSUE THREAD

**Issue by chenmc1996** [microsoft/nni#5262]
**Describe the issue**:
encounter Error  Dispatcher stream error, tuner may have crashed.

**Environment**:
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc):local
- Client OS:Ubuntu
- Server OS (for remote mode only):
- Python version:3.9.15
- PyTorch/TensorFlow version:1.13
- Is conda/virtualenv/venv used?: yes
- Is running in Docker?: no
scipy.__version__
'1.9.3'c

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - search_space:
  lr:
    _type: choice
    _value: [1e-5,5e-4,1e-4,5e-3, 1e-3,5e-2,1e-2,1e-1]
  n_layers:
    _type: choice
    _value: [1,2,4,8]
  n_heads:
    _type: choice
    _value: [1,2,4,8]
  d_token:
    _type: choice
    _value: [16,32,64,128,256,192]
  dropout:
    _type: choice
    _value: [0.5,0.2,0.1,0]
  classifier_dropout:
    _type: choice
    _value: [0.5,0.2,0.1,0]
  warm_epoch:
    _type: choice
    _value: [0,1,2,5,10,20]
  dataaug:
    _type: choice
    _value: [0.5,0.2,0.1,0]
  emap:
    _type: choice
    _value: [0.5,0.6,0.7,0.8,0.9,0.95,0.98,0.99]
  eman:
    _type: choice
    _value: [0.5,0.6,0.7,0.8,0.9,0.95,0.98,0.99]

trial_command: python3 main.py
trial_code_directory: .

trial_concurrency: 2
max_trial_number: 200

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local

 - Search space:

**Log message**:
 - nnimanager.log:
 [2022-12-04 13:12:48] INFO (nni.experiment/MainThread) Creating experiment, Experiment ID: 98zkpb4r
[2022-12-04 13:12:48] INFO (nni.experiment/MainThread) Starting web server...
[2022-12-04 13:12:49] INFO (nni.experiment/MainThread) Setting up...
[2022-12-04 13:12:49] INFO (nni.experiment/MainThread) Web UI URLs: http://127.0.0.1:8888 http://114.212.86.240:8888 http://172.17.0.1:8888
[2022-12-04 13:12:49] INFO (nni.tools.nnictl.launcher/MainThread) To stop experiment run "nnictl stop 98zkpb4r" or "nnictl stop --all"
[2022-12-04 13:12:49] INFO (nni.tools.nnictl.launcher/MainThread) Reference: https://nni.readthedocs.io/en/stable/Tutorial/Nnictl.html
[2022-12-04 13:12:49] INFO (numexpr.utils/MainThread) Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2022-12-04 13:12:49] INFO (numexpr.utils/MainThread) NumExpr defaulting to 8 threads.
[2022-12-04 13:12:49] INFO (nni.tuner.tpe/MainThread) Using random seed 1897128137
[2022-12-04 13:12:49] ERROR (nni.main/MainThread) 'NNI_TUNER_COMMAND_CHANNEL'
Traceback (most recent call last):
  File "/home/cmc/anaconda3/envs/WSL/lib/python3.9/site-packages/nni/__main__.py", line 85, in <module>
    main()
  File "/home/cmc/anaconda3/envs/WSL/lib/python3.9/site-packages/nni/__main__.py", line 57, in main
    url = os.environ['NNI_TUNER_COMMAND_CHANNEL']
  File "/home/cmc/anaconda3/envs/WSL/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'NNI_TUNER_COMMAND_CHANNEL'

 - dispatcher.log:
 - nnictl stdout and stderr:
 Experiment 98zkpb4r start: 2022-12-04 13:12:48.637424
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cmc/anaconda3/envs/WSL/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cmc/anaconda3/envs/WSL/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cmc/anaconda3/envs/WSL/lib/python3.9/site-packages/nni/__main__.py", line 85, in <module>
    main()
  File "/home/cmc/anaconda3/envs/WSL/lib/python3.9/site-packages/nni/__main__.py", line 57, in main
    url = os.environ['NNI_TUNER_COMMAND_CHANNEL']
  File "/home/cmc/anaconda3/envs/WSL/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'NNI_TUNER_COMMAND_CHANNEL'
Error: Dispatcher stream error, tuner may have crashed.
    at EventEmitter.<anonymous> (/home/cmc/.local/lib/python3.6/site-packages/nni_node/core/nnimanager.js:651:32)
    at EventEmitter.emit (node:events:394:28)
    at Socket.<anonymous> (/home/cmc/.local/lib/python3.6/site-packages/nni_node/core/ipcInterface.js:70:72)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

 

**How to reproduce it?**:

**Comment by chenmc1996** [comment]
I can't run the official demo in here https://nni.readthedocs.io/en/stable/tutorials/hpo_nnictl/nnictl.html. 
It looks very much like package/dependencies/environment problem
