### ISSUE TITLE
BOHB/HyperBand TypeError in Python code

### ISSUE THREAD

**Issue by Kenny1235** [microsoft/nni#5263]
**Describe the issue**:
I tried to implement the HPO Quickstart with PyTorch tutorial from the NNI docs with the BOHB tuner. I replaced the TPE tuner from main.py with the example BOHB tuner config from the docs. When executing the python main.py command the experiment starts and after a few seconds the experiments shuts down. The dispatcher.log hints to a TypeError: '<=' not supported between instances of 'str' and 'int' in nni\recoverable.py", line 47, in is_created_in_previous_exp. This error occurs for me with HyperBand and BOHB tuner. Other tuners like TPE and DNGO worked fine for me. I converted the config in main.py to YAML config and used nnictl but the same error occured. I listed all config items from the .yml config below. This also was tested on two different Windows 10 machines. 

**Environment**:
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc): local
- Client OS: Windows 10
- Server OS (for remote mode only):
- Python version: 3.7.9
- PyTorch/TensorFlow version: Pytorch 1.13.0
- Is conda/virtualenv/venv used?: venv
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):

searchSpaceFile: search_space.json
trialCommand: python model.py
trialCodeDirectory: .
maxTrialNumber: 5
trialConcurrency: 1
experimentWorkingDirectory: ./experiments

tuner:
  name: BOHB
  classArgs: 
    optimize_mode: maximize
    min_budget: 1
    max_budget: 5
    eta: 3
    min_points_in_model: 7
    top_n_percent: 15
    num_samples: 64
    random_fraction: 0.33
    bandwidth_factor: 3.0
    min_bandwidth: 0.001

trainingService:
  platform: local

 - Search space:

{
    "features": {"_type": "choice", "_value": [128, 256, 512, 1024]},
    "lr": {"_type": "loguniform", "_value": [0.0001, 0.1]},
    "momentum": {"_type": "uniform", "_value": [0, 1]}
}

**Log message**:
 - nnimanager.log:
 
[2022-12-04 13:04:03] INFO (main) Start NNI manager
[2022-12-04 13:04:03] DEBUG (SqlDB) Database directory: C:\code\APPRAS\nni_test\experiments\jf3mdp2g\db
[2022-12-04 13:04:04] INFO (NNIDataStore) Datastore initialization done
[2022-12-04 13:04:04] INFO (RestServer) Starting REST server at port 8080, URL prefix: "/"
[2022-12-04 13:04:04] WARNING (NNITensorboardManager) Tensorboard may not installed, if you want to use tensorboard, please check if tensorboard installed.
[2022-12-04 13:04:04] INFO (RestServer) REST server started.
[2022-12-04 13:04:04] DEBUG (main) start() returned.
[2022-12-04 13:04:04] DEBUG (NNIRestHandler) GET: /check-status: body: {}
[2022-12-04 13:04:04] DEBUG (NNIRestHandler) POST: /experiment: body: {
  experimentType: 'hpo',
  searchSpaceFile: 'C:\\code\\APPRAS\\nni_test\\search_space.json',
  searchSpace: {
    features: { _type: 'choice', _value: [Array] },
    lr: { _type: 'loguniform', _value: [Array] },
    momentum: { _type: 'uniform', _value: [Array] }
  },
  trialCommand: 'python model.py',
  trialCodeDirectory: 'C:\\code\\APPRAS\\nni_test',
  trialConcurrency: 1,
  maxTrialNumber: 5,
  useAnnotation: false,
  debug: false,
  logLevel: 'info',
  experimentWorkingDirectory: 'C:\\code\\APPRAS\\nni_test\\experiments',
  tuner: {
    name: 'BOHB',
    classArgs: {
      optimize_mode: 'maximize',
      min_budget: 1,
      max_budget: 5,
      eta: 3,
      min_points_in_model: 7,
      top_n_percent: 15,
      num_samples: 64,
      random_fraction: 0.33,
      bandwidth_factor: 3,
      min_bandwidth: 0.001
    }
  },
  trainingService: {
    platform: 'local',
    trialCommand: 'python model.py',
    trialCodeDirectory: 'C:\\code\\APPRAS\\nni_test',
    debug: false,
    maxTrialNumberPerGpu: 1,
    reuseMode: false
  }
}
[2022-12-04 13:04:04] INFO (NNIManager) Starting experiment: jf3mdp2g
[2022-12-04 13:04:04] INFO (NNIManager) Setup training service...
[2022-12-04 13:04:04] INFO (LocalTrainingService) Construct local machine training service.
[2022-12-04 13:04:04] INFO (NNIManager) Setup tuner...
[2022-12-04 13:04:04] DEBUG (NNIManager) dispatcher command: c:\code\appras\venv_nni\scripts\python.exe,-m,nni,--exp_params,eyJleHBlcmltZW50VHlwZSI6ImhwbyIsInNlYXJjaFNwYWNlRmlsZSI6IkM6XFxjb2RlXFxBUFBSQVNcXG5uaV90ZXN0XFxzZWFyY2hfc3BhY2UuanNvbiIsInRyaWFsQ29tbWFuZCI6InB5dGhvbiBtb2RlbC5weSIsInRyaWFsQ29kZURpcmVjdG9yeSI6IkM6XFxjb2RlXFxBUFBSQVNcXG5uaV90ZXN0IiwidHJpYWxDb25jdXJyZW5jeSI6MSwibWF4VHJpYWxOdW1iZXIiOjUsInVzZUFubm90YXRpb24iOmZhbHNlLCJkZWJ1ZyI6ZmFsc2UsImxvZ0xldmVsIjoiaW5mbyIsImV4cGVyaW1lbnRXb3JraW5nRGlyZWN0b3J5IjoiQzpcXGNvZGVcXEFQUFJBU1xcbm5pX3Rlc3RcXGV4cGVyaW1lbnRzIiwidHVuZXIiOnsibmFtZSI6IkJPSEIiLCJjbGFzc0FyZ3MiOnsib3B0aW1pemVfbW9kZSI6Im1heGltaXplIiwibWluX2J1ZGdldCI6MSwibWF4X2J1ZGdldCI6NSwiZXRhIjozLCJtaW5fcG9pbnRzX2luX21vZGVsIjo3LCJ0b3Bfbl9wZXJjZW50IjoxNSwibnVtX3NhbXBsZXMiOjY0LCJyYW5kb21fZnJhY3Rpb24iOjAuMzMsImJhbmR3aWR0aF9mYWN0b3IiOjMsIm1pbl9iYW5kd2lkdGgiOjAuMDAxfX0sInRyYWluaW5nU2VydmljZSI6eyJwbGF0Zm9ybSI6ImxvY2FsIiwidHJpYWxDb21tYW5kIjoicHl0aG9uIG1vZGVsLnB5IiwidHJpYWxDb2RlRGlyZWN0b3J5IjoiQzpcXGNvZGVcXEFQUFJBU1xcbm5pX3Rlc3QiLCJkZWJ1ZyI6ZmFsc2UsIm1heFRyaWFsTnVtYmVyUGVyR3B1IjoxLCJyZXVzZU1vZGUiOmZhbHNlfX0=
[2022-12-04 13:04:04] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2022-12-04 13:04:04] DEBUG (tuner_command_channel.WebSocketChannel) Waiting connection...
[2022-12-04 13:04:06] DEBUG (tuner_command_channel.WebSocketChannel) Connected.
[2022-12-04 13:04:06] INFO (NNIManager) Add event listeners
[2022-12-04 13:04:06] DEBUG (NNIManager) Send tuner command: INITIALIZE: [object Object]
[2022-12-04 13:04:06] DEBUG (tuner_command_channel.WebSocketChannel) Sending IN{"features":{"_type":"choice","_value":[128,256,512,1024]},"lr":{"_type":"loguniform","_value":[0.0001,0.1]},"momentum":{"_type":"uniform","_value":[0,1]}}
[2022-12-04 13:04:06] INFO (LocalTrainingService) Run local machine training service.
[2022-12-04 13:04:06] DEBUG (tuner_command_channel.WebSocketChannel) Received ID
[2022-12-04 13:04:06] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2022-12-04 13:04:06] DEBUG (tuner_command_channel.WebSocketChannel) Sending GE1
[2022-12-04 13:04:06] DEBUG (tuner_command_channel.WebSocketChannel) Received TR{"parameter_id": "1_0_0", "parameter_source": "algorithm", "parameters": {"features": 512, "lr": 0.0017069241194784105, "momentum": 0.1801869884587789, "TRIAL_BUDGET": 1}}
[2022-12-04 13:04:06] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": "1_0_0", "parameter_source": "algorithm", "parameters": {"features": 512, "lr": 0.0017069241194784105, "momentum": 0.1801869884587789, "TRIAL_BUDGET": 1}}
[2022-12-04 13:04:11] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 0,
  hyperParameters: {
    value: '{"parameter_id": "1_0_0", "parameter_source": "algorithm", "parameters": {"features": 512, "lr": 0.0017069241194784105, "momentum": 0.1801869884587789, "TRIAL_BUDGET": 1}}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2022-12-04 13:04:11] DEBUG (LocalTrainingService) submitTrialJob: return: LocalTrialJobDetail {
  id: 'sEeSP',
  status: 'WAITING',
  submitTime: 1670155451664,
  startTime: undefined,
  endTime: undefined,
  tags: undefined,
  url: 'file://localhost:C:\\code\\APPRAS\\nni_test\\experiments\\jf3mdp2g\\trials\\sEeSP',
  workingDirectory: 'C:\\code\\APPRAS\\nni_test\\experiments\\jf3mdp2g\\trials\\sEeSP',
  form: {
    sequenceId: 0,
    hyperParameters: {
      value: '{"parameter_id": "1_0_0", "parameter_source": "algorithm", "parameters": {"features": 512, "lr": 0.0017069241194784105, "momentum": 0.1801869884587789, "TRIAL_BUDGET": 1}}',
      index: 0
    },
    placementConstraint: { type: 'None', gpus: [] }
  },
  pid: undefined,
  gpuIndices: []
}
[2022-12-04 13:04:18] DEBUG (NNIRestHandler) GET: /experiment: body: {}
[2022-12-04 13:04:18] DEBUG (NNIRestHandler) GET: /experiment-metadata: body: {}
[2022-12-04 13:04:18] DEBUG (NNIRestHandler) GET: /trial-jobs: body: {}
[2022-12-04 13:04:18] DEBUG (NNIRestHandler) GET: /metric-data: body: {}
[2022-12-04 13:04:18] DEBUG (NNIDataStore) getTrialJobsByReplayEvents begin
[2022-12-04 13:04:18] DEBUG (NNIDataStore) getTrialJobsByReplayEvents done
[2022-12-04 13:04:18] DEBUG (NNIRestHandler) GET: /check-status: body: {}
[2022-12-04 13:04:18] DEBUG (NNIRestHandler) GET: /trial-jobs: body: {}
[2022-12-04 13:04:18] DEBUG (NNIRestHandler) GET: /metric-data: body: {}
[2022-12-04 13:04:18] DEBUG (NNIDataStore) getTrialJobsByReplayEvents begin
[2022-12-04 13:04:18] DEBUG (NNIDataStore) getTrialJobsByReplayEvents done
[2022-12-04 13:04:18] DEBUG (NNIRestHandler) GET: /version: body: {}
[2022-12-04 13:04:22] INFO (NNIManager) Trial job sEeSP status changed from WAITING to RUNNING
[2022-12-04 13:04:28] DEBUG (NNIRestHandler) GET: /experiment: body: {}
[2022-12-04 13:04:28] DEBUG (NNIRestHandler) GET: /experiment-metadata: body: {}
[2022-12-04 13:04:29] DEBUG (NNIRestHandler) GET: /trial-jobs: body: {}
[2022-12-04 13:04:29] DEBUG (NNIRestHandler) GET: /metric-data: body: {}
[2022-12-04 13:04:29] DEBUG (NNIDataStore) getTrialJobsByReplayEvents begin
[2022-12-04 13:04:29] DEBUG (NNIDataStore) getTrialJobsByReplayEvents done
[2022-12-04 13:04:29] DEBUG (NNIRestHandler) GET: /check-status: body: {}
[2022-12-04 13:04:32] DEBUG (NNIManager) NNIManager received trial job metrics: {
  id: 'sEeSP',
  data: '{"parameter_id": "1_0_0", "trial_job_id": "sEeSP", "type": "PERIODICAL", "sequence": 0, "value": "0.5813"}\n'
}
[2022-12-04 13:04:32] DEBUG (LocalTrainingService) Sending metrics, job id: sEeSP, metrics: {"parameter_id": "1_0_0", "trial_job_id": "sEeSP", "type": "PERIODICAL", "sequence": 0, "value": "0.5813"}

[2022-12-04 13:04:32] DEBUG (tuner_command_channel.WebSocketChannel) Sending ME{"parameter_id": "1_0_0", "trial_job_id": "sEeSP", "type": "PERIODICAL", "sequence": 0, "value": "0.5813"}

[2022-12-04 13:04:39] DEBUG (NNIRestHandler) GET: /experiment: body: {}
[2022-12-04 13:04:39] DEBUG (NNIRestHandler) GET: /experiment-metadata: body: {}
[2022-12-04 13:04:39] DEBUG (NNIRestHandler) GET: /trial-jobs: body: {}
[2022-12-04 13:04:39] DEBUG (NNIRestHandler) GET: /metric-data: body: {}
[2022-12-04 13:04:39] DEBUG (NNIDataStore) getTrialJobsByReplayEvents begin
[2022-12-04 13:04:39] DEBUG (NNIDataStore) getTrialJobsByReplayEvents done
[2022-12-04 13:04:39] DEBUG (NNIRestHandler) GET: /check-status: body: {}
[2022-12-04 13:04:45] DEBUG (NNIManager) NNIManager received trial job metrics: {
  id: 'sEeSP',
  data: '{"parameter_id": "1_0_0", "trial_job_id": "sEeSP", "type": "PERIODICAL", "sequence": 1, "value": "0.6316"}\n'
}
[2022-12-04 13:04:45] DEBUG (LocalTrainingService) Sending metrics, job id: sEeSP, metrics: {"parameter_id": "1_0_0", "trial_job_id": "sEeSP", "type": "PERIODICAL", "sequence": 1, "value": "0.6316"}

[2022-12-04 13:04:45] DEBUG (tuner_command_channel.WebSocketChannel) Sending ME{"parameter_id": "1_0_0", "trial_job_id": "sEeSP", "type": "PERIODICAL", "sequence": 1, "value": "0.6316"}

[2022-12-04 13:04:45] ERROR (tuner_command_channel.WebSocketChannel) Error: Error: tuner_command_channel: Tuner closed connection
    at WebSocket.handleWsClose (c:\code\appras\venv_nni\lib\site-packages\nni_node\core\tuner_command_channel\websocket_channel.js:83:26)
    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (c:\code\appras\venv_nni\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:246:10)
    at Socket.socketOnClose (c:\code\appras\venv_nni\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:1127:15)
    at Socket.emit (node:events:526:28)
    at TCP.<anonymous> (node:net:687:12)

 - dispatcher.log:

[2022-12-04 13:04:06] DEBUG (asyncio/MainThread) Using selector: SelectSelector
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) = connection is CONNECTING
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) > GET /tuner HTTP/1.1
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) > Host: localhost:8080
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) > Upgrade: websocket
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) > Connection: Upgrade
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) > Sec-WebSocket-Key: gpVib78naDwChxnKcz0/tA==
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) > Sec-WebSocket-Version: 13
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) > Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) > User-Agent: Python/3.7 websockets/10.4
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) < HTTP/1.1 101 Switching Protocols
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) < Upgrade: websocket
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) < Connection: Upgrade
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) < Sec-WebSocket-Accept: wuE/NuZ6qKvVPioRKUxILPhONO8=
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) = connection is OPEN
[2022-12-04 13:04:06] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) < TEXT 'IN{"features":{"_type":"choice","_value":[128,2...iform","_value":[0,1]}}' [157 bytes]
[2022-12-04 13:04:06] INFO (BOHB_Advisor/Thread-1) start to handle_initialize
[2022-12-04 13:04:06] DEBUG (BOHB_Advisor/Thread-1) Received data: {'features': {'_type': 'choice', '_value': [128, 256, 512, 1024]}, 'lr': {'_type': 'loguniform', '_value': [0.0001, 0.1]}, 'momentum': {'_type': 'uniform', '_value': [0, 1]}}
[2022-12-04 13:04:06] DEBUG (BOHB_Advisor/Thread-1) start to create a new SuccessiveHalving iteration, self.curr_s=1
[2022-12-04 13:04:06] DEBUG (BOHB_Advisor/Thread-1) new SuccessiveHalving iteration, next_n=3, next_r=1
[2022-12-04 13:04:06] DEBUG (BOHB_Advisor/Thread-1) start sampling a new configuration.
[2022-12-04 13:04:06] DEBUG (BOHB_Advisor/Thread-1) done sampling a new configuration.
[2022-12-04 13:04:06] DEBUG (BOHB_Advisor/Thread-1) start sampling a new configuration.
[2022-12-04 13:04:06] DEBUG (BOHB_Advisor/Thread-1) done sampling a new configuration.
[2022-12-04 13:04:06] DEBUG (BOHB_Advisor/Thread-1) start sampling a new configuration.
[2022-12-04 13:04:06] DEBUG (BOHB_Advisor/Thread-1) done sampling a new configuration.
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) > TEXT 'ID' [2 bytes]
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) < TEXT 'GE1' [3 bytes]
[2022-12-04 13:04:06] DEBUG (websockets.client/NNI-WebSocketEventLoop) > TEXT 'TR{"parameter_id": "1_0_0", "parameter_source":...89, "TRIAL_BUDGET": 1}}' [173 bytes]
[2022-12-04 13:04:11] DEBUG (websockets.client/NNI-WebSocketEventLoop) < PING '' [0 bytes]
[2022-12-04 13:04:11] DEBUG (websockets.client/NNI-WebSocketEventLoop) > PONG '' [0 bytes]
[2022-12-04 13:04:16] DEBUG (websockets.client/NNI-WebSocketEventLoop) < PING '' [0 bytes]
[2022-12-04 13:04:16] DEBUG (websockets.client/NNI-WebSocketEventLoop) > PONG '' [0 bytes]
[2022-12-04 13:04:21] DEBUG (websockets.client/NNI-WebSocketEventLoop) < PING '' [0 bytes]
[2022-12-04 13:04:21] DEBUG (websockets.client/NNI-WebSocketEventLoop) > PONG '' [0 bytes]
[2022-12-04 13:04:26] DEBUG (websockets.client/NNI-WebSocketEventLoop) % sending keepalive ping
[2022-12-04 13:04:26] DEBUG (websockets.client/NNI-WebSocketEventLoop) > PING 28 c5 06 21 [binary, 4 bytes]
[2022-12-04 13:04:26] DEBUG (websockets.client/NNI-WebSocketEventLoop) < PONG 28 c5 06 21 [binary, 4 bytes]
[2022-12-04 13:04:26] DEBUG (websockets.client/NNI-WebSocketEventLoop) % received keepalive pong
[2022-12-04 13:04:26] DEBUG (websockets.client/NNI-WebSocketEventLoop) < PING '' [0 bytes]
[2022-12-04 13:04:26] DEBUG (websockets.client/NNI-WebSocketEventLoop) > PONG '' [0 bytes]
[2022-12-04 13:04:31] DEBUG (websockets.client/NNI-WebSocketEventLoop) < PING '' [0 bytes]
[2022-12-04 13:04:31] DEBUG (websockets.client/NNI-WebSocketEventLoop) > PONG '' [0 bytes]
[2022-12-04 13:04:32] DEBUG (websockets.client/NNI-WebSocketEventLoop) < TEXT 'ME{"parameter_id": "1_0_0", "trial_job_id": "sE...0, "value": "0.5813"}\n' [109 bytes]
[2022-12-04 13:04:32] ERROR (nni.runtime.msg_dispatcher_base/Thread-2) '<=' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "c:\code\appras\venv_nni\lib\site-packages\nni\runtime\msg_dispatcher_base.py", line 108, in command_queue_worker
    self.process_command(command, data)
  File "c:\code\appras\venv_nni\lib\site-packages\nni\runtime\msg_dispatcher_base.py", line 154, in process_command
    command_handlers[command](data)
  File "c:\code\appras\venv_nni\lib\site-packages\nni\algorithms\hpo\bohb_advisor\bohb_advisor.py", line 701, in handle_report_metric_data
    if self.is_created_in_previous_exp(data['parameter_id']):
  File "c:\code\appras\venv_nni\lib\site-packages\nni\recoverable.py", line 47, in is_created_in_previous_exp
    return param_id <= self.recovered_max_param_id
TypeError: '<=' not supported between instances of 'str' and 'int'
[2022-12-04 13:04:36] DEBUG (websockets.client/NNI-WebSocketEventLoop) < PING '' [0 bytes]
[2022-12-04 13:04:36] DEBUG (websockets.client/NNI-WebSocketEventLoop) > PONG '' [0 bytes]
[2022-12-04 13:04:41] DEBUG (websockets.client/NNI-WebSocketEventLoop) < PING '' [0 bytes]
[2022-12-04 13:04:41] DEBUG (websockets.client/NNI-WebSocketEventLoop) > PONG '' [0 bytes]
[2022-12-04 13:04:45] DEBUG (websockets.client/NNI-WebSocketEventLoop) < TEXT 'ME{"parameter_id": "1_0_0", "trial_job_id": "sE...1, "value": "0.6316"}\n' [109 bytes]
[2022-12-04 13:04:45] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2022-12-04 13:04:45] DEBUG (websockets.client/NNI-WebSocketEventLoop) = connection is CLOSING
[2022-12-04 13:04:45] DEBUG (websockets.client/NNI-WebSocketEventLoop) > CLOSE 1000 (OK) [2 bytes]
[2022-12-04 13:04:45] DEBUG (websockets.client/NNI-WebSocketEventLoop) < CLOSE 1000 (OK) [2 bytes]
[2022-12-04 13:04:45] DEBUG (websockets.client/NNI-WebSocketEventLoop) = connection is CLOSED
[2022-12-04 13:04:45] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated

 - nnictl stdout and stderr:

--------------------------------------------------------------------------------
Experiment jf3mdp2g start: 2022-12-04 13:04:03.464840
--------------------------------------------------------------------------------
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: tuner_command_channel: Tuner closed connection
    at WebSocket.handleWsClose (c:\code\appras\venv_nni\lib\site-packages\nni_node\core\tuner_command_channel\websocket_channel.js:83:26)
    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (c:\code\appras\venv_nni\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:246:10)
    at Socket.socketOnClose (c:\code\appras\venv_nni\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:1127:15)
    at Socket.emit (node:events:526:28)
    at TCP.<anonymous> (node:net:687:12)
Emitted 'error' event at:
    at WebSocketChannelImpl.handleError (c:\code\appras\venv_nni\lib\site-packages\nni_node\core\tuner_command_channel\websocket_channel.js:135:22)
    at WebSocket.handleWsClose (c:\code\appras\venv_nni\lib\site-packages\nni_node\core\tuner_command_channel\websocket_channel.js:83:14)
    at WebSocket.emit (node:events:538:35)
    [... lines matching original stack trace ...]
    at TCP.<anonymous> (node:net:687:12)
Thrown at:
    at handleWsClose (c:\code\appras\venv_nni\lib\site-packages\nni_node\core\tuner_command_channel\websocket_channel.js:83:26)
    at emit (node:events:538:35)
    at emitClose (c:\code\appras\venv_nni\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:246:10)
    at socketOnClose (c:\code\appras\venv_nni\lib\site-packages\nni_node\node_modules\express-ws\node_modules\ws\lib\websocket.js:1127:15)
    at emit (node:events:526:28)
    at node:net:687:12

 

**How to reproduce it?**:
Use HPO Quickstart for PyTorch tutorial with BOHB tuner

**Comment by jhj0411jhj** [comment]
same here

**Comment by cennn** [comment]
+1

**Comment by cennn** [comment]
nni==2.9 can solve the problem.
problem should be in the class: recoverable method: is_created_in_previous_exp
the bohb specific param ids, such as "1_0_0", are incompatible when judging "is_created_in_previous_exp", which added in nni 2.10, while other HPO algorithms use only numeric id seems ok

**Comment by QuanluZhang** [comment]
> 

Thanks for providing this information. The `is_created_in_previous_exp` issue is resolved in the upcoming v3.0

**Comment by Yuanyang-Zhu** [comment]
> > 
> 
> Thanks for providing this information. The `is_created_in_previous_exp` issue is resolved in the upcoming v3.0

V3.0 will still have the same problem

**Comment by kk19990709** [comment]
V3.0 will still have the same problem  （HyperBand）
