### ISSUE TITLE
KeyError: "Fixed context with layer_1 not found. Existing values are: {'activation_1': '0', 'dropout_1': 0.2, 'dropout_2': 0}"

### ISSUE THREAD

**Issue by xiadingZ** [microsoft/nni#5272]
**Describe the issue**:

When I change model parameter to nn.valuechoice, some parameter can use nn.valuechoice, but some can't.  How to debug this problem?
here is part of my code
```python
@model_wrapper
class Model(nn.Module):
    def __init__(self, configs, max_seq_len:Optional[int]=1024, d_k:Optional[int]=None, d_v:Optional[int]=None, norm:str='BatchNorm', attn_dropout:float=0., 
                 act:str="gelu", key_padding_mask:bool='auto',padding_var:Optional[int]=None, attn_mask:Optional[Tensor]=None, res_attention:bool=True, 
                 pre_norm:bool=False, store_attn:bool=False, pe:str='zeros', learn_pe:bool=True, pretrain_head:bool=False, head_type = 'flatten', verbose:bool=False, **kwargs):
        
        super().__init__()
        
        # load parameters
        c_in = configs.enc_in
        context_window = configs.seq_len
        target_window = configs.pred_len
        
        #n_layers = configs.e_layers
        n_layers = nn.ValueChoice([2,4,6], label='elayer')
        n_heads = configs.n_heads
        #n_heads = nn.ValueChoice([2, 3, 4], label='n_heads')
        #d_model = nn.ValueChoice([32, 64, 128], label='head_dropout')
        d_model = configs.d_model
        d_ff = configs.d_ff
        #d_ff = nn.ValueChoice([32, 64, 128], label='d_ff')
        dropout = nn.ValueChoice([0, 0.1, 0.2], label='dropout')
        #fc_dropout = nn.ValueChoice([0, 0.1, 0.2], label='fc_dropout')
        fc_dropout = configs.fc_dropout
        head_dropout = nn.ValueChoice([0, 0.1, 0.2], label='head_dropout')
        
        individual = configs.individual
```

error is
```
Traceback (most recent call last):
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/nas/nn/pytorch/mutation_utils.py", line 52, in get_fixed_value
    return ret[generate_new_label(label)]
KeyError: 'layer_1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiading/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xiading/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/retiarii/trial_entry.py", line 10, in <module>
    main()
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/nas/execution/trial_entry.py", line 29, in main
    engine.trial_execute_graph()
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/nas/execution/pytorch/simplified.py", line 72, in trial_execute_graph
    graph_data.evaluator._execute(_model)
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/nas/evaluator/functional.py", line 37, in _execute
    return self.function(model_cls, **self.arguments)
  File "/mnt/dl-storage/nj-cephfs-0/group/mmu/xiading/patchtst/main_nas.py", line 159, in ts_fit
    model = model_cls()
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/nas/execution/pytorch/simplified.py", line 69, in _model
    return graph_data.class_(**graph_data.init_parameters)
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/nas/utils/serializer.py", line 125, in __init__
    super().__init__(*args, **kwargs)
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/common/serializer.py", line 508, in __init__
    super().__init__(symbol=base, args=args, kwargs=kwargs, call_super=call_super)
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/common/serializer.py", line 133, in __init__
    super().__init__(
  File "/mnt/dl-storage/nj-cephfs-0/group/mmu/xiading/patchtst/models/PatchTST_nas.py", line 81, in __init__
    n_layers = nn.ValueChoice([2, 3, 4], label='layer_1')
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/nas/nn/pytorch/mutation_utils.py", line 29, in __new__
    return cls.create_fixed_module(*args, **kwargs)
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/nas/nn/pytorch/choice.py", line 870, in create_fixed_module
    value = get_fixed_value(label)
  File "/home/xiading/miniconda3/lib/python3.9/site-packages/nni/nas/nn/pytorch/mutation_utils.py", line 54, in get_fixed_value
    raise KeyError(f'Fixed context with {label} not found. Existing values are: {ret}')
KeyError: "Fixed context with layer_1 not found. Existing values are: {'activation_1': '0', 'dropout_1': 0.2, 'dropout_2': 0}"
```

**Environment**:
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc): local
- PyTorch/TensorFlow version: 1.13
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):

```
    exp = RetiariiExperiment(
        PatchTST.Model(opt),
        evaluator,
        [],
        strategy.RegularizedEvolution(optimize_mode="minimize"),
    )
    exp_config = RetiariiExeConfig("local")
    exp_config.experiment_name = "ts"
    exp_config.trial_concurrency = opt.trial_concurrency
    exp_config.trial_gpu_number = 1
    exp_config.training_service.use_active_gpu = True
    exp_config.training_service.max_trial_number_per_gpu = 1
    exp_config.training_service.gpu_indices = gpu_indices
    exp_config.max_trial_number = opt.max_trial_number
    
    exp_config.log_level = 'debug'
    #exp_config.experiment_working_directory = out_dir
    
    logger.info("NAS started")
    print("----------------- NAS started -------------")
    exp.run(exp_config, opt.port, debug=True)
```

**Comment by ultmaster** [comment]
Looks like you have a `layer_1` here:

```
models/PatchTST_nas.py", line 81, in __init__
    n_layers = nn.ValueChoice([2, 3, 4], label='layer_1')
```

But it's missing in your model code.

I don't know where that comes from.

**Comment by xiadingZ** [comment]
sorry I use the wrong code, I will close this issue
