### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'input'

### ISSUE THREAD

**Issue by nralka2007** [microsoft/nni#5273]
**Describe the issue**:

Facing this error in  ModelSpeedup(model, torch.rand(1, 2, 512, 512).to(device), masks).speedup_model()

This is a UNet model

**Environment**:
- NNI version:
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

022-12-07 21:08:58] [32minfer module masks...[0m
2022-12-07 21:08:58,875 infer module masks...
[2022-12-07 21:08:58] [32mUpdate mask for .prim::TupleUnpack.63[0m
2022-12-07 21:08:58,895 Update mask for .prim::TupleUnpack.63
[2022-12-07 21:08:58] [32mUpdate mask for module.down_convs.0.block_beforepool.0[0m
2022-12-07 21:08:58,895 Update mask for module.down_convs.0.block_beforepool.0
Traceback (most recent call last):
  File "prune_oneshot_nni.py", line 447, in <module>
    main()
  File "prune_oneshot_nni.py", line 414, in main
    ModelSpeedup(model, torch.rand(1, 2, 512, 512).to(device), masks).speedup_model()

**How to reproduce it?**:

**Comment by Louis-J** [comment]
could you offer the code to reproduce it?

**Comment by J-shang** [comment]
Closed due to no reply for a long time, please reopen if have any questions.
