### ISSUE TITLE
NetWork Error

### ISSUE THREAD

**Issue by accelerator1737** [microsoft/nni#5300]
**Describe the issue**:
When I use NNI, at most 10 minutes, I will be reminded of NetWork Error, and then the port connection will be disconnected. I want to know what the problem is. By the way, I am using Windows10 system

**Environment**:
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc):local
- Client OS:windows 10
- Server OS (for remote mode only):
- Python version:3.7
- PyTorch/TensorFlow version:torch==1.8.1
- Is conda/virtualenv/venv used?:conda
- Is running in Docker?:no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:websockets.exceptions.InvalidMessage: did not receive a valid HTTP response

**Log message**:
 - nnimanager.log:
 - dispatcher.log:[2022-12-26 10:35:12] INFO (nni.tuner.tpe/MainThread) Using random seed 175818551
[2022-12-26 10:35:12] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2022-12-26 10:41:26] WARNING (nni.runtime.tuner_command_channel.channel/MainThread) Exception on receiving: ConnectionClosedError(None, None, None)
[2022-12-26 10:41:26] WARNING (nni.runtime.tuner_command_channel.channel/MainThread) Connection lost. Trying to reconnect...
[2022-12-26 10:41:26] INFO (nni.runtime.tuner_command_channel.channel/MainThread) Attempt #0, wait 0 seconds...
[2022-12-26 10:41:26] INFO (nni.runtime.msg_dispatcher_base/MainThread) Report error to NNI manager: Traceback (most recent call last):
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\websockets\legacy\client.py", line 138, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\websockets\legacy\http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\websockets\legacy\http.py", line 194, in read_line
    line = await stream.readline()
  File "E:\Anaconda\install\envs\pytorch\lib\asyncio\streams.py", line 496, in readline
    line = await self.readuntil(sep)
  File "E:\Anaconda\install\envs\pytorch\lib\asyncio\streams.py", line 588, in readuntil
    await self._wait_for_data('readuntil')
  File "E:\Anaconda\install\envs\pytorch\lib\asyncio\streams.py", line 473, in _wait_for_data
    await self._waiter
  File "E:\Anaconda\install\envs\pytorch\lib\asyncio\selector_events.py", line 814, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\nni\__main__.py", line 61, in main
    dispatcher.run()
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\nni\runtime\msg_dispatcher_base.py", line 69, in run
    command, data = self._channel._receive()
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\nni\runtime\tuner_command_channel\channel.py", line 94, in _receive
    command = self._retry_receive()
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\nni\runtime\tuner_command_channel\channel.py", line 104, in _retry_receive
    self._channel.connect()
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\nni\runtime\tuner_command_channel\websocket.py", line 62, in connect
    self._ws = _wait(_connect_async(self._url))
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\nni\runtime\tuner_command_channel\websocket.py", line 111, in _wait
    return future.result()
  File "E:\Anaconda\install\envs\pytorch\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "E:\Anaconda\install\envs\pytorch\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\nni\runtime\tuner_command_channel\websocket.py", line 125, in _connect_async
    return await websockets.connect(url, max_size=None)  # type: ignore
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "E:\Anaconda\install\envs\pytorch\lib\asyncio\tasks.py", line 442, in wait_for
    return fut.result()
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\websockets\legacy\client.py", line 671, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\websockets\legacy\client.py", line 326, in handshake
    status_code, response_headers = await self.read_http_response()
  File "E:\Anaconda\install\envs\pytorch\lib\site-packages\websockets\legacy\client.py", line 144, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by liuzhe-lz** [comment]
We are working on a fix for next release. Thanks for your report.

**Comment by lukelu312** [comment]
Got the same issue in nni 2.10.1 version, does 3.0rc1 fix the issue ? Hope to hear your expertise. @liuzhe-lz

**Comment by xinlnix** [comment]
Got the same error. Could someone can tell how to avoid it?
