### ISSUE TITLE
Tuner loses responsive

### ISSUE THREAD

**Issue by Vaaaas** [microsoft/nni#5328]
**Describe the issue**:
`Error: tuner_command_channel: Tuner loses responsive` raised after 1553(/2000) trials.
Duration shown in the NNI portal is "7h 4m" but the exception raised at 8h30m.

**Environment**:
- NNI version: 2.9
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-58-generic x86_64)
- Server OS (for remote mode only): /
- Python version: 3.7.12
- PyTorch/TensorFlow version: /
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):
```
{
  "params": {
    "experimentType": "hpo",
    "trialCommand": "python main.py ...",
    "trialCodeDirectory": "/home/xxx/codes/yyy",
    "trialConcurrency": 10,
    "maxExperimentDuration": "24h",
    "maxTrialNumber": 2000,
    "useAnnotation": false,
    "debug": false,
    "logLevel": "info",
    "experimentWorkingDirectory": "/home/xxx/nni-experiments",
    "tuner": {
      "name": "Random",
      "classArgs": {
        "optimize_mode": "minimize",
        "seed": 42
      }
    },
    "trainingService": {
      "platform": "local",
      "trialCommand": "python main.py ...",
      "trialCodeDirectory": "/home/xxx/codes/yyy",
      "debug": false,
      "maxTrialNumberPerGpu": 1,
      "reuseMode": false
    }
  },
  "execDuration": "7h 4m ",
  "nextSequenceId": 1553,
  "revision": 4099
}
```
 - Search space:
```
{
  "aggr": {
    "_type": "choice",
    "_value": [0, 1]
  },
  "colsample_bylevel": {
    "_type": "uniform",
    "_value": [0.5, 1]
  },
  "colsample_bytree": {
    "_type": "uniform",
    "_value": [0.5, 1]
  },
  "cond_encode": {
    "_type": "choice",
    "_value": [
      "0",
      "1"
    ]
  },
  "fp_mode": {
    "_type": "choice",
    "_value": ["Morgan2", "Morgan3", "MACCS Keys"]
  },
  "gamma": {
    "_type": "uniform",
    "_value": [0, 1]
  },
  "learning_rate": {
    "_type": "loguniform",
    "_value": [0.001, 1]
  },
  "max_depth": {
    "_type": "randint",
    "_value": [3, 11]
  },
  "n_estimators": {
    "_type": "randint",
    "_value": [50, 351]
  },
  "pca": {
    "_type": "choice",
    "_value": [0, 0.5, 0.6, 0.7, 0.8, 0.9]
  },
  "subsample": {
    "_type": "uniform",
    "_value": [0.5, 1]
  }
}
```

**Log message**:
 - nnimanager.log:
```
[2023-01-30 17:16:42] INFO (NNIManager) Trial job Kxit2 status changed from WAITING to RUNNING
[2023-01-30 17:16:42] INFO (NNIManager) Trial job OTpq5 status changed from WAITING to RUNNING
[2023-01-30 17:16:42] INFO (NNIManager) Trial job IzlJv status changed from WAITING to RUNNING
[2023-01-30 17:17:42] ERROR (tuner_command_channel.WebSocketChannel) Error: Error: tuner_command_channel: Tuner loses responsive
    at WebSocketChannelImpl.heartbeat (/home/xxx/.conda/envs/molclr/lib/python3.7/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:119:30)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```
 - dispatcher.log:
```
[2023-01-30 17:17:42] WARNING (nni.runtime.tuner_command_channel.channel/MainThread) Exception on receiving: ConnectionClosedError(None, None, None)
[2023-01-30 17:17:42] WARNING (nni.runtime.tuner_command_channel.channel/MainThread) Connection lost. Trying to reconnect...
[2023-01-30 17:17:42] INFO (nni.runtime.tuner_command_channel.channel/MainThread) Attempt #0, wait 0 seconds...
[2023-01-30 17:17:43] INFO (nni.runtime.msg_dispatcher_base/MainThread) Report error to NNI manager: Traceback (most recent call last):
  File "/home/xxx/.conda/envs/molclr/lib/python3.7/site-packages/websockets/legacy/client.py", line 135, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/home/xxx/.conda/envs/molclr/lib/python3.7/site-packages/websockets/legacy/http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "/home/xxx/.conda/envs/molclr/lib/python3.7/site-packages/websockets/legacy/http.py", line 194, in read_line
    line = await stream.readline()
  File "/home/xxx/.conda/envs/molclr/lib/python3.7/asyncio/streams.py", line 496, in readline
    line = await self.readuntil(sep)
  File "/home/xxx/.conda/envs/molclr/lib/python3.7/asyncio/streams.py", line 588, in readuntil
    await self._wait_for_data('readuntil')
  File "/home/xxx/.conda/envs/molclr/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
  File "/home/xxx/.conda/envs/molclr/lib/python3.7/asyncio/selector_events.py", line 814, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
```
 - nnictl stdout and stderr:

**How to reproduce it?**:
Not sure.

**Comment by liuzhe-lz** [comment]
We are working on a fix. Thanks for your report.
