### ISSUE TITLE
Encounter ModuleNotFoundError when run Darts from Example

### ISSUE THREAD

**Issue by YatchiuLau** [microsoft/nni#5329]
**Describe the issue**:

Encounter ModuleNotFoundError when run Darts Demo code from Example folders
（/examples/nas/oneshot/darts/search.py）

**Environment**:
- NNI version: 2.10
- Training service: local
- Client OS: Linux
- Python version: 3.10.9
- PyTorch/TensorFlow version: 1.13.1
- CUDA: 11.6
- Is conda/virtualenv/venv used?: conda 
- Is running in Docker?: no

**Configuration**:
 - Experiment config: Using the original code
 - Search space: Using the original code

**Log message**:
```
root@Ubuntu:~/home/nni_repo/nni/examples/nas/oneshot/darts$ python search.py
Traceback (most recent call last):
  File "~/home/nni_repo/nni/examples/nas/oneshot/darts/search.py", line 14, in <module>
    from nni.nas.pytorch.callbacks import ArchitectureCheckpoint, LRSchedulerCallback
ModuleNotFoundError: No module named 'nni.nas.pytorch'
```

**How to reproduce it?**:
Run the original code without making any changes

**Comment by matluster** [comment]
Please use `nni/examples/tutorials/darts.py`. The examples in `nas/oneshot` should've been removed.

**Comment by YatchiuLau** [comment]
Thanks for your reply.

When I try to run the code in `nni/examples/tutorials/darts.py` , I encountered another issue. 

```
/home/root/anaconda3/envs/nas_dev/bin/python /home/root/nas_dev/nni_repo/nni/examples/tutorials/darts.py 
Files already downloaded and verified
[2023-02-01 18:40:22] "/home/root/.cache/nni/nashub/darts-v2-5465b0d2.pth" already exists. Checking hash.
Accuracy: 0.9737
Files already downloaded and verified
Traceback (most recent call last):
  File "/home/root/nas_dev/nni_repo/nni/examples/tutorials/darts.py", line 219, in <module>
    evaluator = Classification(
  File "/home/root/anaconda3/envs/nas_dev/lib/python3.10/site-packages/nni/nas/evaluator/pytorch/lightning.py", line 371, in __init__
    module = ClassificationModule(criterion=criterion, learning_rate=learning_rate,
  File "/home/root/anaconda3/envs/nas_dev/lib/python3.10/site-packages/nni/common/serializer.py", line 508, in __init__
    super().__init__(symbol=base, args=args, kwargs=kwargs, call_super=call_super)
  File "/home/root/anaconda3/envs/nas_dev/lib/python3.10/site-packages/nni/common/serializer.py", line 133, in __init__
    super().__init__(
  File "/home/root/anaconda3/envs/nas_dev/lib/python3.10/site-packages/nni/nas/evaluator/pytorch/lightning.py", line 308, in __init__
    super().__init__(criterion, {'acc': AccuracyWithLogits},
  File "/home/root/anaconda3/envs/nas_dev/lib/python3.10/site-packages/nni/nas/evaluator/pytorch/lightning.py", line 224, in __init__
    self.metrics = nn.ModuleDict({name: cls() for name, cls in metrics.items()})
  File "/home/root/anaconda3/envs/nas_dev/lib/python3.10/site-packages/nni/nas/evaluator/pytorch/lightning.py", line 224, in <dictcomp>
    self.metrics = nn.ModuleDict({name: cls() for name, cls in metrics.items()})
TypeError: Accuracy.__new__() missing 1 required positional argument: 'task'

Process finished with exit code 1
```
Which step is wrong?

**Comment by ultmaster** [comment]
Your torchmetrics is too new. Try to downgrade it.

**Comment by YatchiuLau** [comment]
I am using torchmetric version 0.11.0
Is there a recommended version of torchmetric?
And is there a recommended environment for running this code, such as a pytorch version, etc.?

**Comment by ultmaster** [comment]
0.10

Latest version is supported via #5256
