### ISSUE TITLE
Issue on Initital Install: "aliases"

### ISSUE THREAD

**Issue by SFlan27** [microsoft/nni#5355]
**Describe the issue**:

Trying to use NNI for the first time to optimize hyperparameters for an existing model. When I try to run the install test command `nnictl create --config nni/examples/trials/mnist-pytorch/config.yml` , I get back `TypeError: __init__() got an unexpected keyword argument 'aliases'`  when initializing argparse. I also tried my own YAML file for my model, and received the same error.

From what I could research, this type of issue comes up when using python2 and not python3, but I have confirmed I am running python3 on my venv. I first installed NNI using the basic pip install, but I currently have it installed 2.0 through source code and building a wheel following https://nni.readthedocs.io/en/v2.9/notes/build_from_source.html . Not sure what to do next.

**Environment**:
- NNI version: 2.0
- Training service (local|remote|pai|aml|etc): local
- Client OS: Bash
- Server OS (for remote mode only):
- Python version: 3.8.13
- PyTorch/TensorFlow version: 1.10.1
- Is conda/virtualenv/venv used?: Yes
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!): 
`authorName: default
experimentName: example_mnist_pytorch
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 mnist.py
  codeDir: .
  gpuNum: 0 `

 - Search space:

`{
    "batch_size": {"_type":"choice", "_value": [16, 32, 64, 128]},
    "hidden_size":{"_type":"choice","_value":[128, 256, 512, 1024]},
    "lr":{"_type":"choice","_value":[0.0001, 0.001, 0.01, 0.1]},
    "momentum":{"_type":"uniform","_value":[0, 1]}
}`

**How to reproduce it?**:

- SSH into cluster
- `module load anaconda`
- `conda activate [venv]`
- `nnictl create --config nni/examples/trials/mnist-pytorch/config.yml`

**Log message**:

`Traceback (most recent call last):
  File "/depot/cms/top/sflanary/conda_envs/SeanVenv/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
  File "/depot/cms/top/sflanary/conda_envs/SeanVenv/lib/python3.8/site-packages/nni/tools/nnictl/nnictl.py", line 222, in parse_args
    parser_algo_reg = parser_algo_subparsers.add_parser(
  File "/apps/cent7/xalt/libexec/argparse.py", line 1085, in add_parser
    parser = self._parser_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'aliases' `

**Comment by Lijiaoa** [comment]
@SFlan27 Could you use nni v2.10 to test it?

**Comment by SFlan27** [comment]
> @SFlan27 Could you use nni v2.10 to test it?

I just tried, same result.

`sflanary@cms-fe00:~ $ pip uninstall nniFound existing installation: nni 2.10
Uninstalling nni-2.10:
  Would remove:
    /home/sflanary/.local/bin/nnictl
    /home/sflanary/.local/lib/python3.8/site-packages/nni-2.10.dist-info/*
    /home/sflanary/.local/lib/python3.8/site-packages/nni/*
    /home/sflanary/.local/lib/python3.8/site-packages/nni_assets/*
    /home/sflanary/.local/lib/python3.8/site-packages/nni_node/*
Proceed (y/n)? y
  Successfully uninstalled nni-2.10
(/depot/cms/top/sflanary/conda_envs/SeanVenv) sflanary@cms-fe00:~ $ pip install nni
Defaulting to user installation because normal site-packages is not writeable
Collecting nni

[lines for installing packages]

Installing collected packages: nni
  WARNING: The script nnictl is installed in '/home/sflanary/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed nni-2.10
(/depot/cms/top/sflanary/conda_envs/SeanVenv) sflanary@cms-fe00:~ $ nnictl create --config nni/examples/trials/mnist-pytorch/config.yml
Traceback (most recent call last):
  File "/depot/cms/top/sflanary/conda_envs/SeanVenv/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
  File "/home/sflanary/.local/lib/python3.8/site-packages/nni/tools/nnictl/nnictl.py", line 501, in parse_args
    parser = get_parser()
  File "/home/sflanary/.local/lib/python3.8/site-packages/nni/tools/nnictl/nnictl.py", line 420, in get_parser
    parser_algo_reg = parser_algo_subparsers.add_parser(
  File "/apps/cent7/xalt/libexec/argparse.py", line 1085, in add_parser
    parser = self._parser_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'aliases' `

**Comment by SFlan27** [comment]
Update:

When looking at the argparse version found on the cluster I am using, the lines about aliases are missing. https://github.com/python/cpython/blob/f482ade4c7887c49dfd8bba3be76f839e562608d/Lib/argparse.py#L1146 

I used `pip install --upgrade --user argparse` to see if updating argparse solved the issue, but it persisted. The package would likely have to be upgraded by the cluster admins.

A solution that was suggested to me was commenting out the lines 416 and 424 referring to "aliases" in my venv's install of nni: https://github.com/microsoft/nni/blob/c4564ab5baefc10d4f83d234dcf9878e0e4d9f8e/nni/tools/nnictl/nnictl.py#L416
https://github.com/microsoft/nni/blob/c4564ab5baefc10d4f83d234dcf9878e0e4d9f8e/nni/tools/nnictl/nnictl.py#L424

I placed the comment hash directly before the 'a' in aliases. When I reran `nnictl create --config nni/examples/trials/mnist-pytorch/config.yml`, it now just produced the output `Please run ‘nnictl {positional argument} –help’ to see nnictl guidance.` Since this output did not give much info, I played around with the `nnictl create` to make sure the syntax was correct. If I wrote an incomplete command by not including the path, it produced the expected error. This is actually good progress, as before any command with `nnictl` would only produce the aliases error.

**Comment by liuzhe-lz** [comment]
Thanks for your help! We will fix it in next release.

**Comment by SFlan27** [comment]
> Thanks for your help! We will fix it in next release.

Hello, is this issue fixed in the new version  (v3.0rc1) ? If so, please reply so I can close this issue. Thanks! I will also install the new version and try myself.
