### ISSUE TITLE
ModelSpeedup cannot speed up FasterRCNN

### ISSUE THREAD

**Issue by gmlwns2000** [microsoft/nni#5356]
**Describe the bug**:
Hi,

`ModelSpeedUp` cannot speed up `FasterRCNN`'s `GeneralizedRCNNTrasnform`.
It returns `ImageList`, which is not supported currently.

Thank you!

Followings are debugging logs.

```
(torch) ainl@ainl-main-ubuntu:~/library/dummy$ python playground/nni_issue_faster_rcnn/main.py 
/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
2023-02-16 12:01:13.265568: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-16 12:01:13.381621: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-02-16 12:01:13.768699: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.8/lib64::/home/ainl/tensorrt/TensorRT-8.5.2.2/lib
2023-02-16 12:01:13.768758: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.8/lib64::/home/ainl/tensorrt/TensorRT-8.5.2.2/lib
2023-02-16 12:01:13.768765: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/torch/nn/functional.py:3896: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  (torch.floor((input.size(i + 2).float() * torch.tensor(scale_factors[i], dtype=torch.float32)).float()))
/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/torchvision/models/detection/anchor_utils.py:121: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  torch.empty((), dtype=torch.int64, device=device).fill_(image_size[0] // g[0]),
/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/torchvision/models/detection/anchor_utils.py:122: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  torch.empty((), dtype=torch.int64, device=device).fill_(image_size[1] // g[1]),
/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/torchvision/models/detection/rpn.py:99: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  A = Ax4 // 4
/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/torchvision/models/detection/rpn.py:100: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  C = AxC // A
/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/torchvision/ops/boxes.py:157: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  boxes_x = torch.min(boxes_x, torch.tensor(width, dtype=boxes.dtype, device=boxes.device))
/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/torchvision/ops/boxes.py:159: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  boxes_y = torch.min(boxes_y, torch.tensor(height, dtype=boxes.dtype, device=boxes.device))
/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/torch/__init__.py:833: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert condition, message
/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/torchvision/models/detection/transform.py:298: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(s, dtype=torch.float32, device=boxes.device)
/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/torchvision/models/detection/transform.py:299: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  / torch.tensor(s_orig, dtype=torch.float32, device=boxes.device)
[2023-02-16 12:01:46] start to speedup the model
[2023-02-16 12:02:15] infer module masks...
[2023-02-16 12:02:15] Update mask for model.transform
Traceback (most recent call last):
  File "/home/ainl/library/dummy/playground/nni_issue_faster_rcnn/main.py", line 66, in <module>
    speedup.speedup_model()
  File "/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/nni/compression/pytorch/speedup/compressor.py", line 546, in speedup_model
    self.infer_modules_masks()
  File "/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/nni/compression/pytorch/speedup/compressor.py", line 383, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/nni/compression/pytorch/speedup/compressor.py", line 250, in update_direct_sparsity
    _auto_infer.update_direct_sparsity()
  File "/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 349, in update_direct_sparsity
    raise ex
  File "/home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 346, in update_direct_sparsity
    _mask, _constant = self.isconstants(tout.clone().detach())
AttributeError: 'ImageList' object has no attribute 'clone'
```

```python
Output type:<torchvision.models.detection.image_list.ImageList object at 0x7fe6e119e6d0> 
Target module: GeneralizedRCNNTransform(
    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    Resize(min_size=(800,), max_size=1333, mode='bilinear')
)
```

**Environment**:
- Python version: `3.9`
- NNI/Torch version:
```
(torch) ainl@ainl-main-ubuntu:~/library/dummy$ pip show nni torch
Name: nni
Version: 2.10
Summary: Neural Network Intelligence project
Home-page: https://github.com/Microsoft/nni
Author: Microsoft NNI Team
Author-email: nni@microsoft.com
License: MIT
Location: /home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages
Requires: astor, cloudpickle, colorama, filelock, json-tricks, numpy, packaging, pandas, prettytable, psutil, PythonWebHDFS, pyyaml, requests, responses, schema, scikit-learn, scipy, tqdm, typeguard, typing-extensions, websockets
Required-by: 
---
Name: torch
Version: 1.12.1+cu116
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/ainl/anaconda3/envs/torch/lib/python3.9/site-packages
Requires: typing-extensions
Required-by: basicsr, deepspeed, facexlib, gfpgan, onnx2torch, realesrgan, thop, timm, torch-tensorrt, torchaudio, torchvision
```

**Reproduce the problem**
- Code|Example:
```python
import torch
import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor, TwoMLPHead
from torchvision.models.detection.rpn import AnchorGenerator
from torchvision.models.detection import FasterRCNN

# Define the model
num_classes = 13

#### vgg11
backbone = torchvision.models.vgg11(pretrained=False).features
backbone.out_channels = 512

anchor_generator = AnchorGenerator(sizes=((32, 64),), aspect_ratios=((0.5, 1.5),))
roi_pooler = torchvision.ops.MultiScaleRoIAlign(featmap_names=['0'], output_size=3, sampling_ratio=1)
resolution = roi_pooler.output_size[0]
representation_size = 384
box_head = TwoMLPHead(backbone.out_channels * resolution ** 2, representation_size)
box_head.fc7 = torch.nn.Linear(representation_size, 768)
representation_size = 768
box_predictor = FastRCNNPredictor(representation_size, num_classes)
model = FasterRCNN(
    backbone, 
    # num_classes=num_classes, 
    rpn_anchor_generator=anchor_generator, 
    box_roi_pool=roi_pooler,
    box_head=box_head,
    box_predictor=box_predictor,
)

class FasterRcnnWrapper(torch.nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model
        
    def forward(self, inputs, labels=None):
        output = self.model(inputs, labels)
        if labels is not None:
            return {
                'loss': sum(loss for loss in output.values())
            }
        else:
            return {
                'output_bbox': torch.stack([it['boxes'] for it in output], dim=0),
                'output_cls': torch.stack([it['labels'] for it in output], dim=0),
                'output_prob': torch.stack([it['scores'] for it in output], dim=0),
            }

model = FasterRcnnWrapper(model)

model_input = (torch.zeros((1, 3, 720, 1280), dtype=torch.float32, device='cpu'))

config_list = [{
    'sparsity_per_layer': 0.3,
    'op_types': ['Conv2d']
}, {
    'exclude': True,
    'op_names': ['model.rpn.head.bbox_pred','model.rpn.head.bbox_pred']
}]
from nni.compression.pytorch.pruning import L2NormPruner
pruner = L2NormPruner(model, config_list, mode='dependency_aware', dummy_input=model_input)
_, masks = pruner.compress()
pruner._unwrap_model()
from nni.compression.pytorch.speedup import ModelSpeedup
speedup = ModelSpeedup(model, model_input, masks, map_location='cpu')
speedup.speedup_model()
```

**Comment by zhiqwang** [comment]
`nni` didn't support `ImageList` I guess, and there is a similar ticket https://github.com/microsoft/nni/issues/5345 .

**Comment by J-shang** [comment]
hello @gmlwns2000 @zhiqwang , yes, `nni` didn't support `ImageList`, I will give a workaround soon

**Comment by vimarsh6739** [comment]
Hi @J-shang , is there any update on the workaround?
