### ISSUE TITLE
darts.py example not working in /nni/examples/tutorials/darts.py

### ISSUE THREAD

**Issue by Tyler-Jay-Stevahn** [microsoft/nni#5409]
**Describe the issue**:
darts.py is not working.

**Environment**: Windows 10
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc): local
- Client OS: Windows 10
- Server OS (for remote mode only): N/A
- Python version: 3.8.10
- PyTorch/TensorFlow version: torch==1.13.1+cu116, tensorflow==2.10.0
- Is conda/virtualenv/venv used?: No
- Is running in Docker?: No

**Configuration**:
 - Experiment config (remember to remove secrets!):

**Pip freeze **:

C:/Users/tstevahn/AppData/Local/Programs/Python/Python38/python.exe -m pip freeze;

about-time==4.2.1
absl-py==1.4.0
aiohttp==3.8.4
aiosignal==1.3.1
alive-progress==3.0.1
astor==0.8.1
asttokens==2.2.1
astunparse==1.6.3
async-timeout==4.0.2
attrs==22.2.0
autograd==1.5
backcall==0.2.0
cachetools==5.3.0
certifi==2022.12.7
charset-normalizer==3.0.1
clang==5.0
click==8.1.3
cloudpickle==2.2.1
cma==3.2.2
colorama==0.4.6
comm==0.1.2
contextlib2==21.6.0
contourpy==1.0.7
cycler==0.11.0
datasets==1.0.2
debugpy==1.6.6
decorator==5.1.1
Deprecated==1.2.13
dill==0.3.6
dm-tree==0.1.8
etils==1.0.0
executing==1.2.0
filelock==3.9.0
flatbuffers==23.1.21
fonttools==4.38.0
frozenlist==1.3.3
fsspec==2023.1.0
future==0.18.3
gast==0.4.0
google-auth==2.16.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googleapis-common-protos==1.58.0
grapheme==0.6.0
grpcio==1.51.1
h5py==3.8.0
huggingface-hub==0.12.1
idna==3.4
importlib-metadata==6.0.0
importlib-resources==5.10.2
ipykernel==6.21.1
ipython==8.10.0
ipywidgets==8.0.4
jedi==0.18.2
joblib==1.2.0
json-tricks==3.16.1
jupyter_client==8.0.2
jupyter_core==5.2.0
jupyterlab-widgets==3.0.5
keras==2.10.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.4
libclang==15.0.6.1
lightning-utilities==0.7.0
Markdown==3.4.1
MarkupSafe==2.1.2
matplotlib==3.6.3
matplotlib-inline==0.1.6
misc-utils-py==0.3.0
multidict==6.0.4
multiprocess==0.70.14
nest-asyncio==1.5.6
nni==2.10
numpy==1.24.2
oauthlib==3.2.2
opencv-python==4.7.0.68
opt-einsum==3.3.0
packaging==23.0
pandas==1.5.3
parso==0.8.3
pickleshare==0.7.5
Pillow==9.4.0
platformdirs==3.0.0
prettytable==3.6.0
promise==2.3
prompt-toolkit==3.0.36
protobuf==3.19.6
psutil==5.9.4
pure-eval==0.2.2
pyarrow==11.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments==2.14.0
pymoo==0.3.0
pymop==0.2.4
pyparsing==3.0.9
python-dateutil==2.8.2
python-json-logger==0.1.11
python-version==0.0.2
PythonWebHDFS==0.2.3
pytorch-lightning==1.9.3
pytz==2022.7.1
pywin32==305
PyYAML==6.0
pyzmq==25.0.0
regex==2022.10.31
requests==2.28.2
requests-oauthlib==1.3.1
responses==0.18.0
rsa==4.9
sacremoses==0.0.53
schema==0.7.5
scikit-learn==1.2.1
scikit-misc==0.1.4
scipy==1.10.1
sentencepiece==0.1.94
simplejson==3.18.3
six==1.16.0
stack-data==0.6.2
starlette==0.13.8
structlog==19.2.0
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.10.0
tensorflow-datasets==4.8.2
tensorflow-estimator==2.10.0
tensorflow-hub==0.12.0
tensorflow-io-gcs-filesystem==0.30.0
tensorflow-metadata==1.12.0
tensorflow-text==2.10.0
tensorflow_intel==2.10.0
termcolor==2.2.0
threadpoolctl==3.1.0
tokenizers==0.9.4
toml==0.10.2
torch==1.13.1+cu116
torchaudio==0.13.1+cu116
torchmetrics==0.11.0
torchtext==0.14.1
torchvision==0.14.1+cu116
tornado==6.2
tqdm==4.57.0
traitlets==5.9.0
transformers==4.1.1
typeguard==2.13.3
types-toml==0.10.8.4
typing_extensions==4.4.0
urllib3==1.26.14
utils==1.0.1
utils-misc==0.1.0
wcwidth==0.2.6
websockets==10.4
Werkzeug==2.2.2
widgetsnbextension==4.0.5
wrapt==1.14.1
xxhash==3.2.0
yarl==1.8.2
zipp==3.13.0

**Output**

C:\Users\tstevahn\To_Laptop\Server\Server_Code>C:/Users/tstevahn/AppData/Local/Programs/Python/Python38/python.exe c:/Users/tstevahn/To_Laptop/Server/Server_Code/nni/examples/tutorials/darts.py
Files already downloaded and verified
[2023-02-27 12:06:29] "C:\Users\tstevahn/.cache\nni\nashub\darts-v2-5465b0d2.pth" already exists. Checking hash.
Files already downloaded and verified
[2023-02-27 12:06:41] "C:\Users\tstevahn/.cache\nni\nashub\darts-v2-5465b0d2.pth" already exists. Checking hash.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\tstevahn\To_Laptop\Server\Server_Code\nni\examples\tutorials\darts.py", line 93, in <module>
    evaluate_model(darts_v2_model, cuda=True)  # Set this to false if there's no GPU.
  File "c:\Users\tstevahn\To_Laptop\Server\Server_Code\nni\examples\tutorials\darts.py", line 82, in evaluate_model
    for inputs, targets in valid_loader:
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 1034, in __init__
    w.start()
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\tstevahn\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by matluster** [comment]
What is your distributed strategy? `ddp`?

**Comment by Tyler-Jay-Stevahn** [comment]
I shouldn't have changed any lines, I don't have a way to run the file. I will be able to run it again in the next few days sometime. Is there a specific line I should be looking for?

**Comment by ultmaster** [comment]
I see. You should probably set num_workers of DataLoader to be 0.

**Comment by Tyler-Jay-Stevahn** [comment]
I changed the following lines and it seems to be working.

train_loader = DataLoader(train_data, batch_size=96, num_workers=0)  # Use the original training data  # 426
train_data, batch_size=64, num_workers=0,   # 210
train_data, batch_size=64, num_workers=0,   # 215
valid_loader = DataLoader(valid_data, batch_size=256, num_workers=0)  # 47

**Comment by Tyler-Jay-Stevahn** [comment]
I had to change batch_size=32 for # 210 and # 215 to get it to run on a 6Gb GPU, the file seems to loop on itself and eventually use up the gpu memory. But I'll make a separate issue when I know more about this issue. Feel free to close this one as finished.
