### ISSUE TITLE
RuntimeError: NNI manager closed connection

### ISSUE THREAD

**Issue by szhang963** [microsoft/nni#5418]
## NNI 学生项目问题概述 / General Question of Student Program

**请简要概述您的问题 / 观点 :**
**Short summary about the question / idea :**
在使用NNI的超参数调优功能时，总是遇到RuntimeError: NNI manager closed connection，然后experiment就自动被kill掉了。有时候开始就这样，有时候跑几个trial后出现。具体的报错信息如下（在nni-experiments/xxxxlog/nnictl_stderr.log）：
```
node:internal/fs/watchers:252
    throw error;
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/mnt/sdc/xxx/xxx/nni-experiments/y7xpc6ve/trials/AAhSD/.nni/metrics'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2251:34)
    at TailStream.waitForMoreData (/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni_node/node_modules/tail-stream/index.js:123:31)
    at TailStream.<anonymous> (/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni_node/node_modules/tail-stream/index.js:275:22)
    at FSReqCallback.wrapper [as oncomplete] (node:fs:660:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/mnt/sdc/xxx/xxx/nni-experiments/y7xpc6ve/trials/AAhSD/.nni/metrics',
  filename: '/mnt/sdc/xxx/xxx/nni-experiments/y7xpc6ve/trials/AAhSD/.nni/metrics'
}
Thrown at:
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_uvException (node:internal/errors:521:10)
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at watch (node:fs:2251:34)
    at TailStream.waitForMoreData (/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni_node/node_modules/tail-stream/index.js:123:31)
    at /home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni_node/node_modules/tail-stream/index.js:275:22
    at wrapper (node:fs:660:5)
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni/__main__.py", line 83, in <module>
    main()
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni/__main__.py", line 60, in main
    dispatcher.run()
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni/runtime/msg_dispatcher_base.py", line 68, in run
    command, data = self._channel._receive()
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni/runtime/tuner_command_channel/channel.py", line 59, in _receive
    raise RuntimeError('NNI manager closed connection')
RuntimeError: NNI manager closed connection
```
对于这个问题，我尝试使用修改系统监控文件数```fs.inotify.max_user_watches=131070```来解决，可以缓解，但是在nni运行中，仍然会出现这个问题，而且不同的机器也都出现这个问题。

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version:2.8 （事实上，任何版本都有这个问题）
- nni mode(local|pai|remote):local
- OS: Ubuntu 18
- python version: 3.7.6
- is conda or virtualenv used?: conda
- is running in docker?: no

## 其他建议 / Other Advice
这个问题非常影响使用，希望可以尽快给出一个解决方案。
**是否需要更新文档（是 / 否）:**
**Need to update document ( yes / no ) :**

**其他分享内容 :**
**Anything else we need to know :**

**Log message / 日志信息 :**
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 
```
[2023-03-03 00:01:45] ERROR (nni.main/MainThread) NNI manager closed connection
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni/__main__.py", line 83, in <module>
    main()
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni/__main__.py", line 60, in main
    dispatcher.run()
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni/runtime/msg_dispatcher_base.py", line 68, in run
    command, data = self._channel._receive()
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni/runtime/tuner_command_channel/channel.py", line 59, in _receive
    raise RuntimeError('NNI manager closed connection')
RuntimeError: NNI manager closed connection
```
 - [nnictl stdout and stderr](https://nni.readthedocs.io/en/stable/reference/nnictl.html#nnictl-log-stdout) : 

```
node:internal/fs/watchers:252
    throw error;
    ^
Error: ENOSPC: System limit for number of file watchers reached, watch '/mnt/sdc/xxx/xxx/nni-experiments/y7xpc6ve/trials/AAhSD/.nni/metrics'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2251:34)
    at TailStream.waitForMoreData (/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni_node/node_modules/tail-stream/index.js:123:31)
    at TailStream.<anonymous> (/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni_node/node_modules/tail-stream/index.js:275:22)
    at FSReqCallback.wrapper [as oncomplete] (node:fs:660:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/mnt/sdc/xxx/xxx/nni-experiments/y7xpc6ve/trials/AAhSD/.nni/metrics',
  filename: '/mnt/sdc/xxx/xxx/nni-experiments/y7xpc6ve/trials/AAhSD/.nni/metrics'
}
Thrown at:
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_uvException (node:internal/errors:521:10)
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at watch (node:fs:2251:34)
    at TailStream.waitForMoreData (/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni_node/node_modules/tail-stream/index.js:123:31)
    at /home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni_node/node_modules/tail-stream/index.js:275:22
    at wrapper (node:fs:660:5)
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni/__main__.py", line 83, in <module>
    main()
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni/__main__.py", line 60, in main
    dispatcher.run()
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni/runtime/msg_dispatcher_base.py", line 68, in run
    command, data = self._channel._receive()
  File "/home/xxx/anaconda3/envs/vtorch/lib/python3.7/site-packages/nni/runtime/tuner_command_channel/channel.py", line 59, in _receive
    raise RuntimeError('NNI manager closed connection')
RuntimeError: NNI manager closed connection
```

**Comment by liuzhe-lz** [comment]
This will be fixed in upcoming release. Thanks for your report.

**Comment by szhang963** [comment]
Thanks, are there some temporary solutions? I am eager to use it.

**Comment by Lijiaoa** [comment]
Please wait the latest release or using master to try it.

**Comment by liuzhe-lz** [comment]
You can try out the [alpha release](https://test.pypi.org/project/nni/3.0a0/).
