### ISSUE TITLE
Inception_v3 with FPGMPruner

### ISSUE THREAD

**Issue by moonlightian** [microsoft/nni#5424]
I got my compression config as below:
_compression_algo_cfg = [{
                'sparsity': self.sparsity,
                'op_types': ['Conv2d']
                #'op_names': pruned_list
            }, {
                'exclude': True,
                #'op_names': exclued_list#['fc']
                'op_types':['Linear']
            }]

and the inception_v3 model is loaded from torchvision with normal forat as:
from torchvision.models import inception_v3
input_model = inception_v3(pretrained=False).cuda()

when I tried to fintune the model after ModelSpeedup, we got:
Traceback (most recent call last):
  File "/tmp/codehub/juicer/juicer_slim/juicing/base_juicing.py", line 115, in run
    self.juice_slim()
  File "/tmp/codehub/juicer/juicer_slim/juicing/pytorch_prune_distill_juicing.py", line 571, in juice_slim
    self.model_wrapper.train(self._input_model, optimizer)
  File "/tmp/codehub/juicer/juicer_slim/pytorch_jobs/common/trainer.py", line 46, in train
    output, aux_output = model(data)#for inception_v3
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/inception.py", line 204, in forward
    x, aux = self._forward(x)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/inception.py", line 176, in _forward
    aux = self.AuxLogits(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/inception.py", line 449, in forward
    x = self.conv0(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/models/inception.py", line 476, in forward
    x = self.conv(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py", line 440, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [128, 768, 1, 1], expected input[16, 384, 5, 5] to have 768 channels, but got 384 channels instead

How can I get rid of these problem?

**Comment by J-shang** [comment]
hello @moonlightian , we are working on a new speedup version, please have a try on this branch https://github.com/microsoft/nni/pull/5403

```
import torch
from torchvision.models import inception_v3

from nni.contrib.compression.pruning import FPGMPruner
from nni.contrib.compression.utils import auto_set_denpendency_group_ids
from nni.compression.pytorch.speedup.v2 import ModelSpeedup

model = inception_v3(pretrained=False)

model(torch.rand([4, 3, 299, 299]))

config_list = [{
    'op_types': ['Conv2d'],
    'sparse_ratio': 0.5,
}]
config_list = auto_set_denpendency_group_ids(model, config_list, torch.rand([4, 3, 299, 299]))

pruner = FPGMPruner(model, config_list)
_, masks = pruner.compress()
pruner.unwrap_model()

ModelSpeedup(model, torch.rand([4, 3, 299, 299]), masks).speedup_model()

model(torch.rand([4, 3, 299, 299]))
```

**Comment by Lijiaoa** [comment]
Please close this issue if you don't have any other question by using latest master branch, thanks~ @moonlightian
