### ISSUE TITLE
Unknown error in  Pruner  aten::sum is not Supported!

### ISSUE THREAD

**Issue by YuxuanDuan** [microsoft/nni#5445]
**Describe the bug**:
I am working with GNN and want to prune it with L1NormPruner,but when I call ModelSpeedup(model, (example_inputs,), masks).speedup_model(), it gives me:
aten::sum is not Supported! Please report an issue at https://github.com/microsoft/nni. Thanks

and

Traceback (most recent call last):
  File "D:/学习/MU-MISO-prune/PYTHON/trial torchpruning/trailnni.py", line 82, in <module>
    ModelSpeedup(model, (example_inputs,), masks).speedup_model()
  File "D:\anaconda3\envs\pytorch-gpu\lib\site-packages\nni\compression\pytorch\speedup\compressor.py", line 509, in speedup_model
    self.infer_modules_masks()
  File "D:\anaconda3\envs\pytorch-gpu\lib\site-packages\nni\compression\pytorch\speedup\compressor.py", line 355, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "D:\anaconda3\envs\pytorch-gpu\lib\site-packages\nni\compression\pytorch\speedup\compressor.py", line 225, in update_direct_sparsity
    state_dict=copy.deepcopy(module.state_dict()), batch_dim=self.batch_dim)
  File "D:\anaconda3\envs\pytorch-gpu\lib\site-packages\nni\compression\pytorch\speedup\infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "D:\anaconda3\envs\pytorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'input'

**Environment**:
- NNI version: 2.6.1
- Training service (local|remote|pai|aml|etc): local
- Python version: 3.6
- PyTorch version:1.10.2
- Cpu or cuda version: cuda:

**Reproduce the problem**
- Code|Example:
As is attached 

- How to reproduce:
Run the code above

I don't know if this is because that NNI does not support torch.sum yet?
[trailnni.zip](https://github.com/microsoft/nni/files/10978026/trailnni.zip)

**Comment by J-shang** [comment]
If you have tried on nni 2.10 and still have this issue, please tell us.

**Comment by YuxuanDuan** [comment]
> If you have tried on nni 2.10 and still have this issue, please tell us.

Thank you for ur reply! After I update nni , it got right
