### ISSUE TITLE
NNI gets stuck in WAITING state after a random number of successful trials

### ISSUE THREAD

**Issue by Oxid1** [microsoft/nni#5493]
**Describe the issue**:
I am currently training an ML model (transformer) and I use NNI to tune the hyperparameters. The problem is that NNI gets stuck after a random number of successful trials. It seems to be unable to create the next upcoming trial (which would be the trial GPJNB). Rather, it throws an error because it can't find the trial it was unable to create in the first place (see figure with nnimanager.log).

**Environment**:
- NNI version: 2.9
- Training service (local|remote|pai|aml|etc): I think it's remote, see explanation below:
I am working with Windows Server 2019 in a virtual environment provided by my employer. But the model training is done on a computer cluster, not on my computer. I am using vpn connection to access this computer cluster. The operating system of the cluster is linux (CentOS Linux release 7.9.2009) and I use VSC as IDE (don't know if this is relevant). Submitting jobs works with slurm on this cluster.
- Python version: 3.8.3
- PyTorch/TensorFlow version: 2.9.1
- Is conda/virtualenv/venv used?: YES
- Is running in Docker?: No

**Log message**:
 - nnimanager.log:
 ```
[2023-03-24 16:15:29] INFO (main) Start NNI manager
[2023-03-24 16:15:29] INFO (NNIDataStore) Datastore initialization done
[2023-03-24 16:15:29] INFO (RestServer) Starting REST server at port 8080, URL prefix: "/"
[2023-03-24 16:15:29] INFO (RestServer) REST server started.
[2023-03-24 16:15:29] INFO (NNIManager) Starting experiment: wy3mjz54
[2023-03-24 16:15:29] INFO (NNIManager) Setup training service...
[2023-03-24 16:15:29] INFO (LocalTrainingService) Construct local machine training service.
[2023-03-24 16:15:29] INFO (NNIManager) Setup tuner...
[2023-03-24 16:15:29] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2023-03-24 16:15:30] INFO (NNIManager) Add event listeners
[2023-03-24 16:15:30] INFO (LocalTrainingService) Run local machine training service.
[2023-03-24 16:15:30] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2023-03-24 16:15:30] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 4, "hidden_size": 128}, "parameter_index": 0}
[2023-03-24 16:15:35] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 0,
  hyperParameters: {
    value: '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 4, "hidden_size": 128}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-03-24 16:15:45] INFO (NNIManager) Trial job qXJxV status changed from WAITING to RUNNING
[2023-03-24 16:15:55] INFO (main) Start NNI manager
[2023-03-24 16:15:55] INFO (NNIDataStore) Datastore initialization done
[2023-03-24 16:15:55] INFO (RestServer) Starting REST server at port 8111, URL prefix: "/"
[2023-03-24 16:15:55] INFO (RestServer) REST server started.
[2023-03-24 16:15:56] INFO (NNIManager) Resuming experiment: wy3mjz54
[2023-03-24 16:15:56] INFO (NNIManager) Setup training service...
[2023-03-24 16:15:56] INFO (LocalTrainingService) Construct local machine training service.
[2023-03-24 16:15:56] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: VIEWED
[2023-03-25 00:29:26] INFO (NNIManager) Trial job qXJxV status changed from RUNNING to SUCCEEDED
[2023-03-25 00:29:26] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 4, "hidden_size": 256}, "parameter_index": 0}
[2023-03-25 00:29:31] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 1,
  hyperParameters: {
    value: '{"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 4, "hidden_size": 256}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-03-25 00:29:36] INFO (NNIManager) Trial job W4vPm status changed from WAITING to RUNNING
[2023-03-25 08:46:49] INFO (NNIManager) Trial job W4vPm status changed from RUNNING to FAILED
[2023-03-25 08:46:49] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 2, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 4, "hidden_size": 512}, "parameter_index": 0}
[2023-03-25 08:46:54] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 2,
  hyperParameters: {
    value: '{"parameter_id": 2, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 4, "hidden_size": 512}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-03-25 08:46:59] INFO (NNIManager) Trial job eeLHB status changed from WAITING to RUNNING
[2023-03-25 17:13:02] INFO (NNIManager) Trial job eeLHB status changed from RUNNING to SUCCEEDED
[2023-03-25 17:13:02] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 3, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 8, "hidden_size": 128}, "parameter_index": 0}
[2023-03-25 17:13:07] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 3,
  hyperParameters: {
    value: '{"parameter_id": 3, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 8, "hidden_size": 128}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-03-25 17:13:12] INFO (NNIManager) Trial job pFpV9 status changed from WAITING to RUNNING
[2023-03-26 09:55:19] INFO (NNIManager) Trial job pFpV9 status changed from RUNNING to SUCCEEDED
[2023-03-26 09:55:19] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 4, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 8, "hidden_size": 256}, "parameter_index": 0}
[2023-03-26 09:55:24] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 4,
  hyperParameters: {
    value: '{"parameter_id": 4, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 8, "hidden_size": 256}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-03-26 09:55:29] INFO (NNIManager) Trial job YQvXf status changed from WAITING to RUNNING
[2023-03-27 02:07:54] INFO (NNIManager) Trial job YQvXf status changed from RUNNING to FAILED
[2023-03-27 02:07:54] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 5, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 8, "hidden_size": 512}, "parameter_index": 0}
[2023-03-27 02:07:59] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 5,
  hyperParameters: {
    value: '{"parameter_id": 5, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 8, "hidden_size": 512}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-03-27 02:08:04] INFO (NNIManager) Trial job OiNAq status changed from WAITING to RUNNING
[2023-03-27 18:10:52] INFO (NNIManager) Trial job OiNAq status changed from RUNNING to FAILED
[2023-03-27 18:10:52] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 6, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 16, "hidden_size": 128}, "parameter_index": 0}
[2023-03-27 18:10:57] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 6,
  hyperParameters: {
    value: '{"parameter_id": 6, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 16, "hidden_size": 128}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-03-27 18:11:03] INFO (NNIManager) Trial job DApPH status changed from WAITING to RUNNING
[2023-03-29 01:42:11] INFO (NNIManager) Trial job DApPH status changed from RUNNING to SUCCEEDED
[2023-03-29 01:42:11] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 7, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 16, "hidden_size": 256}, "parameter_index": 0}
[2023-03-29 01:42:16] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 7,
  hyperParameters: {
    value: '{"parameter_id": 7, "parameter_source": "algorithm", "parameters": {"lr": 0.0008, "dr": 0.15, "bs": 16, "n_block": 3, "n_head": 16, "hidden_size": 256}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-03-29 17:14:03] ERROR (NNIRestHandler) Error: File not found: /gpfs0/home/user/nni-experiments/wy3mjz54/trials/GPJNB/stderr
    at LocalTrainingService.getTrialFile (/gpfs0/home/user/.conda/envs/FOMO/lib/python3.10/site-packages/nni_node/training_service/local/localTrainingService.js:146:19)
    at NNIManager.getTrialFile (/gpfs0/home/user/.conda/envs/FOMO/lib/python3.10/site-packages/nni_node/core/nnimanager.js:333:37)
    at /gpfs0/home/user/.conda/envs/FOMO/lib/python3.10/site-packages/nni_node/rest_server/restHandler.js:284:29
    at Layer.handle [as handle_request] (/gpfs0/home/user/.conda/envs/FOMO/lib/python3.10/site-packages/nni_node/node_modules/express/lib/router/layer.js:95:5)
    at next (/gpfs0/home/user/.conda/envs/FOMO/lib/python3.10/site-packages/nni_node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/gpfs0/home/user/.conda/envs/FOMO/lib/python3.10/site-packages/nni_node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/gpfs0/home/user/.conda/envs/FOMO/lib/python3.10/site-packages/nni_node/node_modules/express/lib/router/layer.js:95:5)
    at /gpfs0/home/user/.conda/envs/FOMO/lib/python3.10/site-packages/nni_node/node_modules/express/lib/router/index.js:281:22
    at param (/gpfs0/home/user/.conda/envs/FOMO/lib/python3.10/site-packages/nni_node/node_modules/express/lib/router/index.js:360:14)
    at param (/gpfs0/home/user/.conda/envs/FOMO/lib/python3.10/site-packages/nni_node/node_modules/express/lib/router/index.js:371:14)

```
 - dispatcher.log:
 ```
[2023-03-24 16:15:30] INFO (nni.tuner.gridsearch/MainThread) Ignored optimize_mode "maximize"
[2023-03-24 16:15:30] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2023-03-24 16:15:30] INFO (nni.tuner.gridsearch/Thread-1 (command_queue_worker)) Grid initialized, size: (1×1×2×3×3×3) = 54

```
 - nnictl stdout and stderr:  For the respective trial (GPJNB), these files have not been created yet, as the status remains WAITING. 
 
![screenshot_1](https://user-images.githubusercontent.com/74355418/228607755-7e0749f5-f301-4883-b624-e67a01dcfed3.png)
![screenshot_2](https://user-images.githubusercontent.com/74355418/228607761-b61e2026-7e61-45b1-829f-53bba855beef.png)

**Comment by cruiseliu** [comment]
If it's reproducible, could you try out the [test package](https://test.pypi.org/project/nni/3.0a1/) of next release?

**Comment by Lijiaoa** [comment]
any updates? @Oxid1

**Comment by Oxid1** [comment]
> any updates? @Oxid1

No, I still have this problem. I installed the latest version of nni (my current version is 2.10), but the problem still occurs. Does anyone have any idea why?

**Comment by Lijiaoa** [comment]
@Oxid1 so have you tried this solution? https://github.com/microsoft/nni/issues/5493#issuecomment-1489768485
