### ISSUE TITLE
Node crash during NAS

### ISSUE THREAD

**Issue by heibaidaolx123** [microsoft/nni#5506]
Hi, when using NAS, node crashed:
```
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: tuner_command_channel: Tuner closed connection
    at WebSocket.handleWsClose (/home/xxx/miniconda3/envs/neautoml/lib/python3.8/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:83:26)
    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (/home/xxx/miniconda3/envs/neautoml/lib/python3.8/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:246:10)
    at Socket.socketOnClose (/home/xxx/miniconda3/envs/neautoml/lib/python3.8/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:1127:15)
    at Socket.emit (node:events:526:28)
    at TCP.<anonymous> (node:net:687:12)
Emitted 'error' event at:
    at WebSocketChannelImpl.handleError (/home/xxx/miniconda3/envs/neautoml/lib/python3.8/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:135:22)
    at WebSocket.handleWsClose (/home/xxx/miniconda3/envs/neautoml/lib/python3.8/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:83:14)
    at WebSocket.emit (node:events:538:35)
    [... lines matching original stack trace ...]
    at TCP.<anonymous> (node:net:687:12)
Thrown at:
    at handleWsClose (/home/xxx/miniconda3/envs/neautoml/lib/python3.8/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:83:26)
    at emit (node:events:538:35)
    at emitClose (/home/xxx/miniconda3/envs/neautoml/lib/python3.8/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:246:10)
    at socketOnClose (/home/xxx/miniconda3/envs/neautoml/lib/python3.8/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:1127:15)
    at emit (node:events:526:28)
    at node:net:687:12
```
Any idea?

**Comment by heibaidaolx123** [comment]
It's reproducible on my machine.
And it ran for around half an hour before node crashed.

**Comment by matluster** [comment]
Would you try 3.0a1? You need to use the new example: https://github.com/ultmaster/nni/blob/f7832cb099c2c5d0cf25d415db0729ea6267efa1/examples/tutorials/hello_nas.py

```
python -m pip install --extra-index-url https://test.pypi.org/simple/ --no-cache-dir nni==3.0a1
```

**Comment by Lijiaoa** [comment]
any updates? @heibaidaolx123

**Comment by heibaidaolx123** [comment]
Sorry for the late response.
The issue was not reproduced.
I'll close the issue.
Thanks a lot, guys.
