### ISSUE TITLE
Shape inference failed because no shape inference formula is found

### ISSUE THREAD

**Issue by singagan** [microsoft/nni#5508]
Hi, 
I am trying to setup my model with ProxylessNAS. While using `FlopsProfiler` as in [here](https://github.com/ultmaster/nni/blob/09617be1ddd6b2724057ded35b6f4658b763abc8/examples/nas/hub/proxyless_search.py#L396). I get the following error:

```
RuntimeError: Shape inference failed because no shape inference formula is found for ConvTranspose2d(1024, 512, kernel_size=(2, 2), stride=(2, 2)) of type ConvTranspose2d. Meanwhile the nested modules and functions inside failed to propagate
the shape information. Please provide a `_shape_forward` member function or register a formula using `register_shape_inference_formula`.

```

So I added a formula in  nni/nni/nas/profiler/pytorch/utils/shape_formula.py:

```
def convtranspose2d_formula(module: nn.ConvTranspose2d | nas_nn.MutableConvTranspose2d, input: ShapeTensor) -> MutableShape:
    shape = list(input.real_shape)  # type: ignore

    out_channels = _getattr(module, 'out_channels')
    padding, dilation, kernel_size, stride = map(
        lambda name: _getattr(module, name, expected_type=tuple_2_t),
        ['padding', 'dilation', 'kernel_size', 'stride']
    )

    # C_out
    shape[-3] = out_channels
    # H_out and W_out
    shape[-2] = (shape[-2] + 2 * padding[0] - dilation[0] * (kernel_size[0] - 1) - 1) // stride[0] + 1
    shape[-1] = (shape[-1] + 2 * padding[1] - dilation[1] * (kernel_size[1] - 1) - 1) // stride[1] + 1
    return MutableShape(*shape)

```

I get the following error:

```
[2023-04-06 16:04:45] WARNING: Shape information is not explicitly propagated when executing aten.constant_pad_nd.default, and and none of its parent modules have a shape inference formula. Shape inference is likely to fail. Module calling stack:
  - '' (type: net.cust_model.NASModel, NO shape formula)
  - 'up1' (type: net.cust_model.Up1, NO shape formula)
WARNING: Shape information is not explicitly propagated when executing aten.constant_pad_nd.default, and and none of its parent modules have a shape inference formula. Shape inference is likely to fail. Module calling stack:
  - '' (type: net.cust_model.NASModel, NO shape formula)
  - 'up1' (type: net.cust_model.Up1, NO shape formula)
[2023-04-06 16:04:45] WARNING: Shape inference of aten.cat.default failed though shape inference formula found: <function aten_cat_formula at 0x7f6648d85550>. Module calling stack:
  - '' (type: net.cust_model.NASModel, NO shape formula)
  - 'up1' (type: net.cust_model.Up1, NO shape formula)
This is either a bug in the shape inference formula, or something goes wrong earlier. To workaround this, you can explicitly write a formula for its parent modules.
Traceback (most recent call last):
  File "~/nni/nni/nas/profiler/pytorch/utils/shape.py", line 352, in __torch_dispatch__
    shapes = formula(func, *args, **kwargs)
  File "~/nni/nni/nas/profiler/pytorch/utils/shape_formula.py", line 357, in aten_cat_formula
    result[dim] = sum(t.real_shape[dim] for t in input)  # type: ignore
  File "~/nni/nni/nas/profiler/pytorch/utils/shape_formula.py", line 357, in <genexpr>
    result[dim] = sum(t.real_shape[dim] for t in input)  # type: ignore
TypeError: 'NoneType' object is not subscriptable

WARNING: Shape inference of aten.cat.default failed though shape inference formula found: <function aten_cat_formula at 0x7f6648d85550>. Module calling stack:
  - '' (type: net.cust_model.NASModel, NO shape formula)
  - 'up1' (type: net.cust_model.Up1, NO shape formula)
This is either a bug in the shape inference formula, or something goes wrong earlier. To workaround this, you can explicitly write a formula for its parent modules.
Traceback (most recent call last):
  File "~/nni/nni/nas/profiler/pytorch/utils/shape.py", line 352, in __torch_dispatch__
    shapes = formula(func, *args, **kwargs)
  File "~/nni/nni/nas/profiler/pytorch/utils/shape_formula.py", line 357, in aten_cat_formula
    result[dim] = sum(t.real_shape[dim] for t in input)  # type: ignore
  File "~/nni/nni/nas/profiler/pytorch/utils/shape_formula.py", line 357, in <genexpr>
    result[dim] = sum(t.real_shape[dim] for t in input)  # type: ignore
TypeError: 'NoneType' object is not subscriptable

Traceback (most recent call last):
  File "train_proxy.py", line 274, in <module>
    search()
  File "train_proxy.py", line 257, in search
    profiler = FlopsProfiler(model, torch.randn(64, 3, 64, 64), count_normalization=False, count_bias=False, count_activation=False)
  File "~/nni/nni/nas/profiler/pytorch/flops.py", line 187, in __init__
    self.profiler = FlopsParamsProfiler(model_space, args, **kwargs)
  File "~/nni/nni/nas/profiler/pytorch/flops.py", line 171, in __init__
    shapes = submodule_input_output_shapes(model_space, *args, **kwargs)
  File "~/nni/nni/nas/profiler/pytorch/utils/shape.py", line 466, in submodule_input_output_shapes
    model(*args, **kwargs)
  File "~/env/mlir/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "~/net_BACK/Pytorch-net/net/cust_model.py", line 68, in forward
    x = self.up1(x5, x4)
  File "~/env/mlir/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "~/net_BACK/Pytorch-net/net/cust_model.py", line 39, in forward
    return self.conv(x)
  File "~/env/mlir/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "~/net_BACK/Pytorch-net/net/net_parts_nas_quant.py", line 78, in forward
    return self.double_conv(x)
  File "~/env/mlir/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "~/env/mlir/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "~/env/mlir/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1547, in _call_impl
    hook_result = hook(self, args, result)
  File "~/nni/nni/nas/profiler/pytorch/utils/shape.py", line 514, in module_shape_inference_hook
    result = _module_shape_inference_impl(module, output, *input, is_leaf=is_leaf)
  File "~/nni/nni/nas/profiler/pytorch/utils/shape.py", line 628, in _module_shape_inference_impl
    output_shape = formula(module, *input_args, **formula_kwargs, **input_kwargs)
  File "~/nni/nni/nas/profiler/pytorch/utils/shape_formula.py", line 145, in conv2d_formula
    shape = list(input.real_shape)  # type: ignore
TypeError: 'NoneType' object is not iterable
```
I will appreciate any help.
Thanks.

**Comment by matluster** [comment]
Obviously you need to `register_shape_inference_formula` for `ConvTranspose2d`. Please refer to `shape_formula.py` for examples.

Sorry I don't currently have time to write a full documentation. Will do when I have time.

**Comment by singagan** [comment]
As mentioned above, I did add a formula for `ConvTranspose2d` but the issue persists as I get warning:

```
[2023-04-06 16:04:45] WARNING: Shape information is not explicitly propagated when executing aten.constant_pad_nd.default, and and none of its parent modules have a shape inference formula. Shape inference is likely to fail. Module calling stack:
  - '' (type: net.cust_model.NASModel, NO shape formula)
  - 'up1' (type: net.cust_model.Up1, NO shape formula)
```

**Comment by ultmaster** [comment]
It suggests you've used aten.constant_pad_nd in Up1. You need to either register formula for Up1 or constant_pad_nd.

**Comment by ultmaster** [comment]
It seems correct if the operation doesn't change the input shape.
