### ISSUE TITLE
TypeError: forward() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by dengdengde** [microsoft/nni#5518]
**Describe the bug**:
I compress my model with L1NormPruner and speedup it, then an error occurs. It seems the parameters of **torch.rand(3,3,32,15)** goes wrong. How can I solve this problem?

This is the code for the pruning part of my project:
```
config_list = [{
        'sparsity_per_layer': 0.5,
        'op_types': [ 'Conv2d']
    }, {
        'exclude': False,
        'op_names': ['bn1']
    }]

    pruner = L1NormPruner(Encrypted_model, config_list)
    print(Encrypted_model)
    _, masks = pruner.compress()
    pruner._unwrap_model()
    ModelSpeedup(Encrypted_model, torch.rand(3, 3, 32, 15).to(device), masks).speedup_model()

```
This is the structure and forward of my model：
```
class polynom_act(nn.Module):

    def __init__(self, alpha=None, beta=None, c=None):
        super(polynom_act, self).__init__()
        self.alpha = nn.Parameter(torch.randn(1), requires_grad=True)
        self.beta = nn.Parameter(torch.randn(1), requires_grad=True)
        self.c = nn.Parameter(torch.randn(1), requires_grad=True)

    def forward(self, x):
        return (self.alpha * (x ** 2) + self.beta * x + self.c)

# my model
class HENet2D(nn.Module):
    def __init__(self, num_classes, filters=128):
        super(HENet2D, self).__init__()
        first_f = filters
        second_f = filters * 2
        third_f = filters * 4
        self.conv1 = nn.Conv2d(3, first_f, kernel_size=(3, 3), stride=1, padding=1)
        nn.init.xavier_uniform(self.conv1.weight)
        self.bn1 = nn.BatchNorm2d(first_f)
        self.bn1.weight.data.fill_(1)
        self.bn1.bias.data.zero_()
        self.act1 = polynom_act()
        self.avg_pool1 = nn.AvgPool2d(kernel_size=2, stride=2)
        self.conv2 = nn.Conv2d(first_f, second_f, kernel_size=3, stride=1, padding=1)
        nn.init.xavier_uniform(self.conv2.weight)
        self.bn2 = nn.BatchNorm2d(second_f)
        self.bn2.weight.data.fill_(1)
        self.bn2.bias.data.zero_()
        self.act2 = polynom_act()
        self.avg_pool2 = nn.AvgPool2d(kernel_size=2, stride=2)
        self.conv3 = nn.Conv2d(second_f, third_f, kernel_size=3, stride=1, padding=1)
        nn.init.xavier_uniform(self.conv3.weight)
        self.bn3 = nn.BatchNorm2d(third_f)
        self.bn3.weight.data.fill_(1)
        self.bn3.bias.data.zero_()
        self.act3 = polynom_act()
        self.avg_pool = nn.AdaptiveAvgPool2d((1, 1))
        self.linear = nn.Linear(third_f, num_classes)

    def forward(self, x):
        out = self.act1(self.bn1(self.conv1(x)))
        out = self.avg_pool1(out)
        out = self.act2(self.bn2(self.conv2(out)))
        out = self.avg_pool2(out)
        out = self.act3(self.bn3(self.conv3(out)))
        out = self.avg_pool(out)
        out = out.view(out.size(0), -1)
        out = self.linear(out)
        return out

```

This is error:

```
(pytorch) keyesgheza@KeyesdeMacBook-Pro training-nni % python train.py --filters 64 --type 2d
Saving the model
Epoch: 0, Loss: 2.9199186978132827
Saving the model
Epoch: 1, Loss: 1.1922207526538684
Saving the model
Epoch: 2, Loss: 0.7090284396772799
Test set accuracy: 0.57
Saving the final model to saved_model/2d_model_64_final.torch
HENet2D(
  (conv1): PrunerModuleWrapper(
    (module): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act1): polynom_act()
  (avg_pool1): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (conv2): PrunerModuleWrapper(
    (module): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act2): polynom_act()
  (avg_pool2): AvgPool2d(kernel_size=2, stride=2, padding=0)
  (conv3): PrunerModuleWrapper(
    (module): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  )
  (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act3): polynom_act()
  (avg_pool): AdaptiveAvgPool2d(output_size=(1, 1))
  (linear): Linear(in_features=256, out_features=10, bias=True)
)
[2023-04-12 23:44:39] start to speedup the model
[2023-04-12 23:44:39] infer module masks...
[2023-04-12 23:44:39] Update mask for conv1
[2023-04-12 23:44:39] Update mask for bn1
[2023-04-12 23:44:39] Update mask for act1
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    main(filters=args.filters, use2d=True if args.type == '2d' else False, name=f"{args.type}_model_{args.filters}")
  File "train.py", line 139, in main
    ModelSpeedup(Encrypted_model, torch.rand(3, 3, 32, 15).to(device), masks)\
  File "/Users/keyesgheza/信息安全竞赛/training代码/NNI/nni/nni/compression/pytorch/speedup/compressor.py", line 488, in speedup_model
    self.infer_modules_masks()
  File "/Users/keyesgheza/信息安全竞赛/training代码/NNI/nni/nni/compression/pytorch/speedup/compressor.py", line 398, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/Users/keyesgheza/信息安全竞赛/training代码/NNI/nni/nni/compression/pytorch/speedup/compressor.py", line 259, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
  File "/Users/keyesgheza/信息安全竞赛/training代码/NNI/nni/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "/Users/keyesgheza/opt/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

```

**Environment**:
- NNI version: 2.0( build from source)
- Training service (local|remote|pai|aml|etc): local
- Python version: 3.8.16
- PyTorch version: 1.13.1
- Cpu or cuda version: cpu

**Comment by Lijiaoa** [comment]
just suggest to use nni master branch to test it.

**Comment by super-dainiu** [comment]
Hihi, would you please pull the latest NNI branch and use SpeedupV2 instead?
```python
classifier = HENet2D(10, filters=128)
config_list = [{
    'sparsity_per_layer': 0.5,
    'op_types': ['Conv2d']
}, {
    'exclude': False,
    'op_names': ['bn1']
}]

from nni.algorithms.compression.v2.pytorch.pruning import L1NormPruner
from nni.compression.pytorch.speedup.v2 import ModelSpeedup

pruner = L1NormPruner(classifier, config_list)
_, masks = pruner.compress()

pruner._unwrap_model()

ModelSpeedup(classifier, torch.rand(3, 3, 32, 15), masks).speedup_model()

classifier(torch.rand(3, 3, 32, 15))
```

A gentle reminder is that you might use ``nn.init.xavier_uniform_(self.conv1.weight)`` instead of ``nn.init.xavier_uniform(self.conv1.weight)``, since the later one is depreciated by PyTorch

**Comment by dengdengde** [comment]
> just suggest to use nni master branch to test it.

I tried the uni master branch these days, and I success! Thanks for your help!

**Comment by dengdengde** [comment]
> Hihi, would you please pull the latest NNI branch and use SpeedupV2 instead?
> 
> ```python
> classifier = HENet2D(10, filters=128)
> config_list = [{
>     'sparsity_per_layer': 0.5,
>     'op_types': ['Conv2d']
> }, {
>     'exclude': False,
>     'op_names': ['bn1']
> }]
> 
> from nni.algorithms.compression.v2.pytorch.pruning import L1NormPruner
> from nni.compression.pytorch.speedup.v2 import ModelSpeedup
> 
> pruner = L1NormPruner(classifier, config_list)
> _, masks = pruner.compress()
> 
> pruner._unwrap_model()
> 
> ModelSpeedup(classifier, torch.rand(3, 3, 32, 15), masks).speedup_model()
> 
> classifier(torch.rand(3, 3, 32, 15))
> ```
> 
> A gentle reminder is that you might use `nn.init.xavier_uniform_(self.conv1.weight)` instead of `nn.init.xavier_uniform(self.conv1.weight)`, since the later one is depreciated by PyTorch

Thanks for your help and code. Code run successfully!

**Comment by Lijiaoa** [comment]
I am very glad your problem has been solved, could you close this issue?

**Comment by dengdengde** [comment]
> I am very glad your problem has been solved, could you close this issue?

yes，sorry for that, I will close it right now!
