### ISSUE TITLE
Questions about speedup?

### ISSUE THREAD

**Issue by mawj111** [microsoft/nni#5521]
**Describe the issue**:
I have the same problem as #5518
I compress PP_LCNetV1_1.0x with L1NormPruner and speedup it, then an error occurs. How can I solve this problem？
Does speedupv1 not support HardSwish?In addition, the version of my NNI is 2.10, but why can't I import speedupv2？
![image](https://user-images.githubusercontent.com/65847115/232277641-42537576-ddf0-4f75-aa5a-0a31eb30ded2.png)

This is my error:
```
[2023-04-16 14:12:36] simulated prune body.first_conv.0 remain/total: 15/16
[2023-04-16 14:12:36] simulated prune body.stage1.0.conv.3 remain/total: 29/32
[2023-04-16 14:12:36] simulated prune body.stage1.1.conv.3 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune body.stage1.2.conv.3 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune body.stage1.3.conv.3 remain/total: 116/128
[2023-04-16 14:12:36] simulated prune body.stage1.4.conv.3 remain/total: 116/128
[2023-04-16 14:12:36] simulated prune body.stage2.0.conv.3 remain/total: 231/256
[2023-04-16 14:12:36] simulated prune body.stage2.1.conv.3 remain/total: 231/256
[2023-04-16 14:12:36] simulated prune body.stage2.2.conv.3 remain/total: 231/256
[2023-04-16 14:12:36] simulated prune body.stage2.3.conv.3 remain/total: 231/256
[2023-04-16 14:12:36] simulated prune body.stage2.4.conv.3 remain/total: 231/256
[2023-04-16 14:12:36] simulated prune body.stage2.5.conv.3 remain/total: 231/256
[2023-04-16 14:12:36] simulated prune body.stage3.0.conv.3.fc.0 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune body.stage3.0.conv.3.fc.2 remain/total: 231/256
[2023-04-16 14:12:36] simulated prune body.stage3.0.conv.4 remain/total: 461/512
[2023-04-16 14:12:36] simulated prune body.stage3.1.conv.3.fc.0 remain/total: 116/128
[2023-04-16 14:12:36] simulated prune body.stage3.1.conv.3.fc.2 remain/total: 461/512
[2023-04-16 14:12:36] simulated prune body.stage3.1.conv.4 remain/total: 461/512
[2023-04-16 14:12:36] simulated prune fpn.output1.0 remain/total: 231/256
[2023-04-16 14:12:36] simulated prune fpn.output2.0 remain/total: 231/256
[2023-04-16 14:12:36] simulated prune fpn.output3.0 remain/total: 231/256
[2023-04-16 14:12:36] simulated prune fpn.merge1.0 remain/total: 231/256
[2023-04-16 14:12:36] simulated prune fpn.merge2.0 remain/total: 231/256
[2023-04-16 14:12:36] simulated prune ssh1.conv3X3.0 remain/total: 116/128
[2023-04-16 14:12:36] simulated prune ssh1.conv5X5_1.0 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune ssh1.conv5X5_2.0 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune ssh1.conv7X7_2.0 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune ssh1.conv7x7_3.0 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune ssh2.conv3X3.0 remain/total: 116/128
[2023-04-16 14:12:36] simulated prune ssh2.conv5X5_1.0 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune ssh2.conv5X5_2.0 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune ssh2.conv7X7_2.0 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune ssh2.conv7x7_3.0 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune ssh3.conv3X3.0 remain/total: 116/128
[2023-04-16 14:12:36] simulated prune ssh3.conv5X5_1.0 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune ssh3.conv5X5_2.0 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune ssh3.conv7X7_2.0 remain/total: 58/64
[2023-04-16 14:12:36] simulated prune ssh3.conv7x7_3.0 remain/total: 58/64
[2023-04-16 14:12:40] start to speedup the model
[2023-04-16 14:12:45] infer module masks...
[2023-04-16 14:12:45] Update mask for body.first_conv.0
[2023-04-16 14:12:45] Update mask for body.first_conv.1
Traceback (most recent call last):
  File "prune_model.py", line 221, in <module>
    ModelSpeedup(net, torch.randn(1, 3, 640, 640).to(device), masks_file = masks).speedup_model()
  File "/home/mwj/anaconda3/envs/prune/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 546, in speedup_model
    self.infer_modules_masks()
  File "/home/mwj/anaconda3/envs/prune/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 383, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/home/mwj/anaconda3/envs/prune/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 244, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
  File "/home/mwj/anaconda3/envs/prune/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "/home/mwj/anaconda3/envs/prune/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
```

This is the model:
```
class PPLCNet(nn.Module):
    def __init__(self, scale = 1.0, num_classes = 1000, dropout_prob = 0.2):
        super(PPLCNet, self).__init__()
        self.cfgs = [
           # k,  c,   s, SE
            [3,  32,  1, 0],
            [3,  64,  2, 0],
            [3,  64,  1, 0],    
            [3,  128, 2, 0],
            [3,  128, 1, 0],
            [5,  256, 2, 0],
            [5,  256, 1, 0],
            [5,  256, 1, 0],
            [5,  256, 1, 0],
            [5,  256, 1, 0],
            [5,  256, 1, 0],
            [5,  512, 2, 1],
            [5,  512, 1, 1],
        ]
        self.scale = scale

        input_channel = _make_divisible(16 * scale)
        self.first_conv = nn.Sequential(
            nn.Conv2d(3, input_channel, 3, 2, 1, bias = False), 
            HardSwish()
        )

        block = DepSepConv
        self.stage1 = self._make_layers(block, cfg = self.cfgs[  : 5], in_channels = 16)
        self.stage2 = self._make_layers(block, cfg = self.cfgs[5 :11], in_channels = 128)
        self.stage3 = self._make_layers(block, cfg = self.cfgs[11:  ], in_channels = 256)

        # # building last several layers
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Conv2d(input_channel, 1280, 1, 1, 0)
        self.hwish = HardSwish()
        self.dropout = nn.Dropout(p = dropout_prob)
        self.classifier = nn.Linear(1280, num_classes)

        self._initialize_weights()

    def _make_layers(self, block, cfg, in_channels):
        layers = []
        in_channel = _make_divisible(in_channels * self.scale)
        for k, c, s, use_se in cfg:
            out_channel = _make_divisible(c * self.scale)
            layers.append(block(in_channel, out_channel, k, s, use_se))
            in_channel = out_channel
        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.first_conv(x)
        x = self.stage1(x)
        x = self.stage2(x)
        x = self.stage3(x)
        x = self.avgpool(x)
        x = self.fc(x)
        x = self.hwish(x)
        x = self.dropout(x)
        x = x.view(x.size(0), -1)
        x = self.classifier(x)
        return x

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                n = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
                m.weight.data.normal_(0, math.sqrt(2. / n))
                if m.bias is not None:
                    m.bias.data.zero_()
            elif isinstance(m, nn.BatchNorm2d):
                m.weight.data.fill_(1)
                m.bias.data.zero_()
            elif isinstance(m, nn.Linear):
                m.weight.data.normal_(0, 0.001)
                m.bias.data.zero_()
```

This is the code for the pruning part of my project:
```
from nni.compression.pytorch.pruning import L1NormPruner, L2NormPruner
from nni.compression.pytorch.speedup import ModelSpeedup

config_list = [
    { 'sparsity_per_layer': args.prune, 
      'op_types': ['Conv2d']
    },
    {'exclude': True, 'op_names': [
        'body.stage1.0.conv.0',
        'body.stage1.1.conv.0',
        'body.stage1.2.conv.0',
        'body.stage1.3.conv.0',
        'body.stage1.4.conv.0',
        'body.stage2.0.conv.0',
        'body.stage2.1.conv.0',
        'body.stage2.2.conv.0',
        'body.stage2.3.conv.0',
        'body.stage2.4.conv.0',
        'body.stage2.5.conv.0',
        'body.stage3.0.conv.0',
        'body.stage3.1.conv.0',
      
        'ClassHead.0.conv1x1',
        'ClassHead.1.conv1x1',
        'ClassHead.2.conv1x1',
        'BboxHead.0.conv1x1',
        'BboxHead.1.conv1x1',
        'BboxHead.2.conv1x1',
        'LandmarkHead.0.conv1x1',
        'LandmarkHead.1.conv1x1',
        'LandmarkHead.2.conv1x1'
    ]}
    ]
pruner = L1NormPruner(net, config_list)
_, masks = pruner.compress()
pruner.show_pruned_weights()
pruner._unwrap_model()
ModelSpeedup(net, torch.randn(1, 3, 640, 640).to(device), masks_file = masks).speedup_model()、
```

**Environment**:
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc): local
- Python version: 3.8.13
- PyTorch/TensorFlow version: Pytorch 1.8.1

**Comment by Lijiaoa** [comment]
Have you tried this solution yet? https://github.com/microsoft/nni/issues/5518#issuecomment-1507923507

**Comment by mawj111** [comment]
@Lijiaoa I'm sorry I haven't tried it yet. As I mentioned above, I can't import the library of speedupv2, can you give some advice on how to pull the latest NNI branch? Many thanks.

**Comment by Lijiaoa** [comment]
use this command `git pull upstream master` in your dev branch

**Comment by J-shang** [comment]
hello @mawj111, seems that you are using NNI 3.0 example, please install nni from the master branch, fyi, https://nni.readthedocs.io/en/stable/notes/build_from_source.html#notes-build-from-source--page-root

**Comment by mawj111** [comment]
Thanks，I will try it.

**Comment by Lijiaoa** [comment]
any updates? @mawj111

**Comment by mawj111** [comment]
@Lijiaoa No updates，thanks very much.
