### ISSUE TITLE
SimplePreemptiveLock' object has no attribute '_lock_file'

### ISSUE THREAD

**Issue by south-ocean** [microsoft/nni#5523]
**Describe the issue**:

i am build the nni whl with source code, then install it, but when i test the case in NNI/examples/trials/mnist-tfv2/config.yml, it report error
**Environment**:
- NNI version:2.9
- Training service (local|remote|pai|aml|etc): local
- Client OS: centos
- Server OS (for remote mode only):
- Python version:3.7
- PyTorch/TensorFlow version:2.9
- Is conda/virtualenv/venv used?: no
- Is running in Docker?: yes

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

[root@dcunode5 home]# nnictl create --config   NNI/examples/trials/mnist-tfv2/config.yml
[2023-04-19 06:25:21] Creating experiment, Experiment ID: 6kl8eicb
[2023-04-19 06:25:21] Starting web server...
[2023-04-19 06:25:22] WARNING: Timeout, retry...
[2023-04-19 06:25:23] WARNING: Timeout, retry...
[2023-04-19 06:25:24] ERROR: Create experiment failed
Traceback (most recent call last):
  File "/root/miniconda3/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
  File "/root/miniconda3/lib/python3.7/site-packages/nni/tools/nnictl/nnictl.py", line 497, in parse_args
    args.func(args)
  File "/root/miniconda3/lib/python3.7/site-packages/nni/tools/nnictl/launcher.py", line 91, in create_experiment
    exp.start(port, debug, RunMode.Detach)
  File "/root/miniconda3/lib/python3.7/site-packages/nni/experiment/experiment.py", line 135, in start
    self._start_impl(port, debug, run_mode, None, [])
  File "/root/miniconda3/lib/python3.7/site-packages/nni/experiment/experiment.py", line 104, in _start_impl
    self.url_prefix, tuner_command_channel, tags)
  File "/root/miniconda3/lib/python3.7/site-packages/nni/experiment/launcher.py", line 148, in start_experiment
    raise e
  File "/root/miniconda3/lib/python3.7/site-packages/nni/experiment/launcher.py", line 128, in start_experiment
    Experiments().add_experiment(
  File "/root/miniconda3/lib/python3.7/site-packages/nni/tools/nnictl/config_utils.py", line 109, in __init__
    self.lock = get_file_lock(self.experiment_file, stale=2)
  File "/root/miniconda3/lib/python3.7/site-packages/nni/tools/nnictl/common_utils.py", line 125, in get_file_lock
    return SimplePreemptiveLock(path + '.lock', stale=stale)
  File "/root/miniconda3/lib/python3.7/site-packages/nni/tools/nnictl/common_utils.py", line 98, in __init__
    self._lock_file_name = '{}.{}'.format(self._lock_file, os.getpid())
AttributeError: 'SimplePreemptiveLock' object has no attribute '_lock_file'

**How to reproduce it?**:

**Comment by jweihe** [comment]
I have same problem

**Comment by unicorn343** [comment]
I have same problem too

**Comment by tamas-bitraptors** [comment]
Same here

**Comment by tamas-bitraptors** [comment]
There was a [recent update](https://py-filelock.readthedocs.io/en/latest/changelog.html#v3-11-0-2023-04-06) to filelock package which causes the above mentioned error. 

Try to install the previous version, it should help. E.g. with pip:
`pip install filelock==3.10`

I hope it helps you, too!

**Comment by south-ocean** [comment]
> There was a [recent update](https://py-filelock.readthedocs.io/en/latest/changelog.html#v3-11-0-2023-04-06) to filelock package which causes the above mentioned error.
> 
> Try to install the previous version, it should help. E.g. with pip: `pip install filelock==3.10`
> 
> I hope it helps you, too!
thanks, solved it by this way.
![image](https://user-images.githubusercontent.com/30514703/233753324-762d831c-5e3c-4e66-84db-dea50f754eb8.png)

**Comment by jweihe** [comment]
> > There was a [recent update](https://py-filelock.readthedocs.io/en/latest/changelog.html#v3-11-0-2023-04-06) to filelock package which causes the above mentioned error.
> > Try to install the previous version, it should help. E.g. with pip: `pip install filelock==3.10`
> > I hope it helps you, too!
> > thanks, solved it by this way.
> > ![image](https://user-images.githubusercontent.com/30514703/233753324-762d831c-5e3c-4e66-84db-dea50f754eb8.png)

Thank you! this works well~
