### ISSUE TITLE
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument

### ISSUE THREAD

**Issue by kriteshg** [microsoft/nni#5533]
**Describe the bug**:

- scheduler: AGP
- pruner: TaylorFO 
- mode: global
- using evaluator (new api)
- torchvision resnet 18 model
- iterations: 10

**Environment**:
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc): local 
- Python version: Python 3.9.12
- PyTorch version: 1.12.0          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
- torchvision: 0.13.0               py39_cu113    pytorch
- Cpu or cuda version: cuda

**Reproduce the problem**
- Code|Example:

**Comment by kriteshg** [comment]
Because of AGP pruner on global mode, at iteration 0 as total_pruning_num is 0.
topk is returning an tensor of shape `torch.Size([0])` and max of the specified tensor is throwing the above error.

**Comment by J-shang** [comment]
Hello @kriteshg , your error msg is not uploaded, if you want to use `skip_first_iteration`, please add it after this line
https://github.com/microsoft/nni/blob/48c7426f8ed8ee39bd83f7576617e984c0986151/nni/compression/pytorch/pruning/iterative_pruner.py#L226
```
        task_generator = AGPTaskGenerator(total_iteration=total_iteration,
                                          origin_model=model,
                                          origin_config_list=config_list,
                                          log_dir=log_dir,
                                          keep_intermediate_result=keep_intermediate_result,
                                          skip_first_iteration=True)
```

**Comment by kriteshg** [comment]
I am trying to use AGP scheduler with TaylorFO with mode `global`

`Config List: [{'op_types': ['Conv2d'], 'total_sparsity': 0.98}]`



Please find below the Stack Trace for the error faced
`Traceback (most recent call last):
  File "/home/user/Documents/projects/lm/code/scene_speed_classification/scheduled_pruning.py", line 43, in <module>
    pruned_model = scheduled_pruner.prune()
  File "/home/user/Documents/projects/lm/code/scene_speed_classification/prune/scheduled_pruner.py", line 283, in prune
    scheduled_pruner.compress()
  File "/home/user/anaconda3/envs/scene_speed/lib/python3.9/site-packages/nni/algorithms/compression/v2/pytorch/base/scheduler.py", line 194, in compress
    task_result = self.pruning_one_step(task)
  File "/home/user/anaconda3/envs/scene_speed/lib/python3.9/site-packages/nni/algorithms/compression/v2/pytorch/pruning/basic_scheduler.py", line 283, in pruning_one_step
    result = self.pruning_one_step_normal(task)
  File "/home/user/anaconda3/envs/scene_speed/lib/python3.9/site-packages/nni/algorithms/compression/v2/pytorch/pruning/basic_scheduler.py", line 141, in pruning_one_step_normal
    compact_model, pruner_generated_masks = self.pruner.compress()
  File "/home/user/anaconda3/envs/scene_speed/lib/python3.9/site-packages/nni/algorithms/compression/v2/pytorch/pruning/basic_pruner.py", line 204, in compress
    result = super().compress()
  File "/home/user/anaconda3/envs/scene_speed/lib/python3.9/site-packages/nni/algorithms/compression/v2/pytorch/pruning/basic_pruner.py", line 143, in compress
    masks = self.sparsity_allocator.generate_sparsity(metrics)
  File "/home/user/anaconda3/envs/scene_speed/lib/python3.9/site-packages/nni/algorithms/compression/v2/pytorch/pruning/tools/base.py", line 470, in generate_sparsity
    masks = self.common_target_masks_generation(metrics)
  File "/home/user/anaconda3/envs/scene_speed/lib/python3.9/site-packages/nni/algorithms/compression/v2/pytorch/pruning/tools/sparsity_allocator.py", line 161, in common_target_masks_generation
    global_threshold = torch.topk(global_metric.reshape(-1), total_pruning_num, largest=False)[0].max()
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.
`

**Comment by kriteshg** [comment]
Is it a known bug ? 
Or Global mode should not be used with AGP or Linear schedulers ?

**Comment by kriteshg** [comment]
Hi @J-shang, Any update on this ?

**Comment by J-shang** [comment]
hello @kriteshg, have you tried this comment?
https://github.com/microsoft/nni/issues/5533#issuecomment-1526917482

**Comment by J-shang** [comment]
nni 3.0 preview version will release soon, maybe you could have a try, here is an example for new AGP,
https://github.com/microsoft/nni/blob/v3.0rc1/examples/compression/pruning/scheduled_pruning.py

and for your scene, please set `global_group_id` in config to apply global pruning, here is an new config list format example:
```
    config_list = [{
        'op_types': ['Conv2d'],
        'global_group_id': 'any_is_ok',
        'sparse_ratio': 0.98
    }]
```

**Comment by kriteshg** [comment]
Thank you @J-shang
