### ISSUE TITLE
problem in pruning and calculating flops of darts model

### ISSUE THREAD

**Issue by aaskk** [microsoft/nni#5547]
**Describe the bug**:    
i used fixed_arch(exported_arch) to get the final darts model, and used ptflops to calculate the model complexity, and got warnings like: Warning: module Conv2d is treated as a zero-op.  and the ptfops couldn't get the flops of the darts model. also, i tried to prun the darts model after retraining, but it failed.

**Environment**:
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc): local
- Python version: 3.8
- PyTorch version:  1.12
- Cpu or cuda version: cuda 11.6

**Reproduce the problem**
- Code|Example:

- How to reproduce:

**Comment by matluster** [comment]
Seems to be a dup of #5433

**Comment by aaskk** [comment]
by changing the nni to 2.8, using examples/nas/oneshot/darts/model.py, flops calculation goes well with the DARTS model type "CNN", however, the model speedup in pruning DARTS model failed in the sppedup of the "input_switch",     typeError: __call__() takes 2 positional arguments but 3 were given

**Comment by aaskk** [comment]
[2023-05-10 14:41:41] start to speedup the model
[2023-05-10 14:41:41] infer module masks...
[2023-05-10 14:41:41] Update mask for stem.0
[2023-05-10 14:41:41] Update mask for stem.1
[2023-05-10 14:41:41] Update mask for cells.0.preproc0.net.0
[2023-05-10 14:41:41] Update mask for cells.0.preproc1.net.0
[2023-05-10 14:41:41] Update mask for cells.0.preproc0.net.1
[2023-05-10 14:41:41] Update mask for cells.0.preproc1.net.1
[2023-05-10 14:41:41] Update mask for cells.0.preproc0.net.2.bn
[2023-05-10 14:41:41] Update mask for cells.0.preproc1.net.2.bn
[2023-05-10 14:41:41] Update mask for cells.0.mutable_ops.0.ops.0.pool
[2023-05-10 14:41:41] Update mask for cells.0.mutable_ops.0.ops.0.bn.bn
[2023-05-10 14:41:41] Update mask for cells.0.mutable_ops.0.input_switch
forward() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/home/Liang.jk/hpo/for_wdcnn/run_trial.py", line 629, in <module>
    main(params)
  File "/home/Liang.jk/hpo/for_wdcnn/run_trial.py", line 447, in main
    ModelSpeedup(net, torch.rand(1, 1, 2048,1).to(device), masks).speedup_model()
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 536, in speedup_model
    self.infer_modules_masks()
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 371, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 238, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/nas/pytorch/mutables.py", line 55, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/home/Liang.jk/hpo/for_wdcnn/run_trial.py", line 629, in <module>
    main(params)
  File "/home/Liang.jk/hpo/for_wdcnn/run_trial.py", line 447, in main
    ModelSpeedup(net, torch.rand(1, 1, 2048,1).to(device), masks).speedup_model()
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 536, in speedup_model
    self.infer_modules_masks()
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 371, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 238, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/nas/pytorch/mutables.py", line 55, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

**Comment by aaskk** [comment]
`[2023-05-10 14:41:41] start to speedup the model
[2023-05-10 14:41:41] infer module masks...
[2023-05-10 14:41:41] Update mask for stem.0
[2023-05-10 14:41:41] Update mask for stem.1
[2023-05-10 14:41:41] Update mask for cells.0.preproc0.net.0
[2023-05-10 14:41:41] Update mask for cells.0.preproc1.net.0
[2023-05-10 14:41:41] Update mask for cells.0.preproc0.net.1
[2023-05-10 14:41:41] Update mask for cells.0.preproc1.net.1
[2023-05-10 14:41:41] Update mask for cells.0.preproc0.net.2.bn
[2023-05-10 14:41:41] Update mask for cells.0.preproc1.net.2.bn
[2023-05-10 14:41:41] Update mask for cells.0.mutable_ops.0.ops.0.pool
[2023-05-10 14:41:41] Update mask for cells.0.mutable_ops.0.ops.0.bn.bn
[2023-05-10 14:41:41] Update mask for cells.0.mutable_ops.0.input_switch
forward() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/home/Liang.jk/hpo/for_wdcnn/run_trial.py", line 629, in <module>
    main(params)
  File "/home/Liang.jk/hpo/for_wdcnn/run_trial.py", line 447, in main
    ModelSpeedup(net, torch.rand(1, 1, 2048,1).to(device), masks).speedup_model()
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 536, in speedup_model
    self.infer_modules_masks()
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 371, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 238, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/nas/pytorch/mutables.py", line 55, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/home/Liang.jk/hpo/for_wdcnn/run_trial.py", line 629, in <module>
    main(params)
  File "/home/Liang.jk/hpo/for_wdcnn/run_trial.py", line 447, in main
    ModelSpeedup(net, torch.rand(1, 1, 2048,1).to(device), masks).speedup_model()
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 536, in speedup_model
    self.infer_modules_masks()
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 371, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 238, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/nas/pytorch/mutables.py", line 55, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given`

**Comment by aaskk** [comment]
>[2023-05-10 14:41:41] start to speedup the model
[2023-05-10 14:41:41] infer module masks...
[2023-05-10 14:41:41] Update mask for stem.0
[2023-05-10 14:41:41] Update mask for stem.1
[2023-05-10 14:41:41] Update mask for cells.0.preproc0.net.0
[2023-05-10 14:41:41] Update mask for cells.0.preproc1.net.0
[2023-05-10 14:41:41] Update mask for cells.0.preproc0.net.1
[2023-05-10 14:41:41] Update mask for cells.0.preproc1.net.1
[2023-05-10 14:41:41] Update mask for cells.0.preproc0.net.2.bn
[2023-05-10 14:41:41] Update mask for cells.0.preproc1.net.2.bn
[2023-05-10 14:41:41] Update mask for cells.0.mutable_ops.0.ops.0.pool
[2023-05-10 14:41:41] Update mask for cells.0.mutable_ops.0.ops.0.bn.bn
[2023-05-10 14:41:41] Update mask for cells.0.mutable_ops.0.input_switch
forward() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/home/Liang.jk/hpo/for_wdcnn/run_trial.py", line 629, in <module>
    main(params)
  File "/home/Liang.jk/hpo/for_wdcnn/run_trial.py", line 447, in main
    ModelSpeedup(net, torch.rand(1, 1, 2048,1).to(device), masks).speedup_model()
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 536, in speedup_model
    self.infer_modules_masks()
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 371, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 238, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/nas/pytorch/mutables.py", line 55, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/home/Liang.jk/hpo/for_wdcnn/run_trial.py", line 629, in <module>
    main(params)
  File "/home/Liang.jk/hpo/for_wdcnn/run_trial.py", line 447, in main
    ModelSpeedup(net, torch.rand(1, 1, 2048,1).to(device), masks).speedup_model()
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 536, in speedup_model
    self.infer_modules_masks()
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 371, in infer_modules_masks
    self.update_direct_sparsity(curnode)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 238, in update_direct_sparsity
    _auto_infer = AutoMaskInference(
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/compression/pytorch/speedup/infer_mask.py", line 80, in __init__
    self.output = self.module(*dummy_input)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/nni/nas/pytorch/mutables.py", line 55, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/amax/DATA_HHD/21-Liang.jk/anaconda3/envs/nni_new/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

**Comment by aaskk** [comment]
when the speedup goes to the "input_switch", error occurs

**Comment by matluster** [comment]
It's not recommended to use v2.8.

Would you try v3.0rc1 and use `nni.nas.profiler.pytorch.FlopsProfiler` to profile the FLOPs?

**Comment by aaskk** [comment]
> It's not recommended to use v2.8.
> 
> Would you try v3.0rc1 and use `nni.nas.profiler.pytorch.FlopsProfiler` to profile the FLOPs?

flops calculation is solved because i use the older version darts implementation, from `examples/nas/oneshot/darts/model.py` , however, i got another problem, that is in the pruning speedup process, the error will occur when speeding up the "input_ switch" layer of each node.

**Comment by matluster** [comment]
We can help supporting `input_switch` layers for the new version. But if you insist on using the older implementation, I think it's unlikely that we will deliver a patch for the old version, which means that you need to implement the support on your own.

**Comment by ultmaster** [comment]
Have you tried v3.0rc1?

**Comment by Lijiaoa** [comment]
any updates? @aaskk

**Comment by ultmaster** [comment]
Closing it for now.
