### ISSUE TITLE
Need shape format support for predefined one shot search space

### ISSUE THREAD

**Issue by dzk9528** [microsoft/nni#5558]
Describe the issue:
When I add the profiler as tutorial instructed below:
```python
dummy_input = torch.randn(1, 3, 32, 32)
profiler = NumParamsProfiler(model_space, dummy_input)
penalty = ExpectationProfilerPenalty(profiler, 500e3) 
strategy = DartsStrategy(gradient_clip_val=5.0, penalty=penalty)
```
This error appeared:
```bash
[2023-05-12 22:02:18] WARNING: Shape information is not explicitly propagated when executing aten.avg_pool2d.default, and and a recent module that needs shape information has no shape inference formula. Module calling stack:
  - '' (type: nni.nas.hub.pytorch.nasnet.DARTS, NO shape formula)                                                                             
  - 'stages.0' (type: nni.nas.hub.pytorch.nasnet.NDSStage, NO shape formula)
  - 'stages.0.blocks.0' (type: nni.nas.nn.pytorch.cell.Cell, NO shape formula)                                                    
  - 'stages.0.blocks.0.ops.0.0' (type: nni.nas.nn.pytorch.choice.LayerChoice, HAS shape formula)
  - 'stages.0.blocks.0.ops.0.0.avg_pool_3x3' (type: torch.nn.modules.pooling.AvgPool2d, NO shape formula)     
 Traceback (most recent call last):       
  File "/home/dzhang/Documents/ml-experimental/TinyNAS/nas_tutorial/darts.py", line 235, in <module> 
    profiler = NumParamsProfiler(model_space, dummy_input) 
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/profiler/pytorch/flops.py", line 197, in __init__                         
    self.profiler = FlopsParamsProfiler(model_space, args, **kwargs)                                                                          
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/profiler/pytorch/flops.py", line 171, in __init__                          
    shapes = submodule_input_output_shapes(model_space, *args, **kwargs)                                                                      
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/profiler/pytorch/utils/shape.py", line 466, in submodule_input_output_shapes                                                                                                                                                        
    model(*args, **kwargs)                                                                                                                    
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1212, in _call_impl                                                                                                                                                                                       
    result = forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/hub/pytorch/nasnet.py", line 613, in forward                                          
    s0, s1 = stage([s0, s1])               
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1212, in _call_impl                                         
    result = forward_call(*input, **kwargs)                                                                                                   
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/nn/pytorch/repeat.py", line 158, in forward                                
    x = block(x)                                                      
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)                                                                                                   
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/nn/pytorch/cell.py", line 385, in forward         
    current_state.append(op(inp(states)))                  
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1215, in _call_impl                                                                                                                                                                                       
    hook_result = hook(self, input, result)                      
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/profiler/pytorch/utils/shape.py", line 514, in module_shape_inference_hook                                                                                                                                                          
    result = _module_shape_inference_impl(module, output, *input, is_leaf=is_leaf)
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/profiler/pytorch/utils/shape.py", line 628, in _module_shape_inference_impl  
    output_shape = formula(module, *input_args, **formula_kwargs, **input_kwargs)                                                                                                                                                       
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/profiler/pytorch/utils/shape_formula.py", line 230, in layer_choice_formula
    expressions[val] = extract_shape_info(shape_inference(module[val], *args, is_leaf=is_leaf, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/profiler/pytorch/utils/shape.py", line 498, in shape_inference
    outputs = module(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1215, in _call_impl
    hook_result = hook(self, input, result)
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/profiler/pytorch/utils/shape.py", line 514, in module_shape_inference_hook
    result = _module_shape_inference_impl(module, output, *input, is_leaf=is_leaf)
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/profiler/pytorch/utils/shape.py", line 617, in _module_shape_inference_impl
    tree_map(_ensure_shape, outputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_pytree.py", line 192, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_pytree.py", line 192, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/usr/local/lib/python3.10/dist-packages/nni/nas/profiler/pytorch/utils/shape.py", line 609, in _ensure_shape
    raise RuntimeError(
RuntimeError: Shape inference failed because no shape inference formula is found for AvgPool2d(kernel_size=3, stride=1, padding=1) of type AvgPool2d. Meanwhile the nested modules and functions inside failed to propagate the shape information. Please provide a `_shape_forward` member 
function or register a formula using `register_shape_inference_formula`.                     
 ```

According to the previous issue in https://github.com/microsoft/nni/issues/5538, I think it is AvgPool2d does not have shape inference formula, since it is not customzied search space, so can you add the support on your side?
Environment:

NNI version: latest(Build from source and use Dockerfile in master branch)
Training service (local|remote|pai|aml|etc): local
Client OS: Unbuntu
Python version: 3.8
PyTorch/TensorFlow version: 1.10.2
Is conda/virtualenv/venv used?: No
Is running in Docker?: Yes
Configuration:

Experiment config (remember to remove secrets!): Same as Latest Version in Darts example
Search space: Darts

**Comment by matluster** [comment]
I think you can try to add a formula for `AvgPool2d` on your own. It's not that difficult.

If you have any problems, please contact us.

**Comment by dzk9528** [comment]
@matluster can tutorial for this kinds of development?

**Comment by avisinghal6** [comment]
Hi, I will take up this issue and create a PR. I have it working on my end

**Comment by matluster** [comment]
It appears that you need also add formula for `aten.stack.default` and `aten.sum.dim_IntList`.

It also appears that although `aten.cat.default` has a formula, but it did not succeed, which might be due to shape information is lost, caused by previous missing formulas.

If you don't care about what happens within the cell, you can just add a formula for `nni.nas.nn.pytorch.cell.Cell` instead. An example of doing such thing would be:

https://github.com/microsoft/nni/blob/f17385c0ac241ed58890dc6575b54789285abd3a/nni/nas/hub/pytorch/autoformer.py#L201

**Comment by matluster** [comment]
I'll try to document this process in next couple of weeks. Right now I'm a bit busy around other projects.

**Comment by avisinghal6** [comment]
I created a PR for nn.AvgPool2d which adds the shape format support. The PR #5565

**Comment by Lijiaoa** [comment]
Related PR had been merged, so could you close this issue? @dzk9528

**Comment by dzk9528** [comment]
@ultmaster Is your change is merged as @Lijiaoa Suggested? If so, I will close this issue.

**Comment by ultmaster** [comment]
No. Unfortunately I don't currently have the bandwidth to work on this issue.
