### ISSUE TITLE
Bug: imcompatability between save & load functions and configs.

### ISSUE THREAD

**Issue by zjowowen** [microsoft/nni#5587]
There is a imcompatability between standard config and code, as shown in functions save and load: 
https://github.com/microsoft/nni/blob/master/nni/tools/nnictl/nnictl_utils.py#L828
https://github.com/microsoft/nni/blob/master/nni/tools/nnictl/nnictl_utils.py#LL931C5-L931C22

It can be reproduced by saving and loading tutorial examples.

It's due to differences between "trialCodeDirectory" and "trial codeDir".

**Comment by busFred** [comment]
Facing the same error
```
(ace) fred@fred-ThinkPad-T480s:~/Documents/research/afa/exports$ nnictl experiment load --path nni_experiment_9y8foa01.zip --codeDir .
INFO:  Loading...
INFO:  Expand codeDir to /home/fred/Documents/research/afa/exports/.
Traceback (most recent call last):
  File "/home/fred/python_ws/ace/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
             ^^^^^^^^^^^^
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/tools/nnictl/nnictl.py", line 503, in parse_args
    args.func(args)
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/tools/nnictl/nnictl_utils.py", line 943, in load_experiment
    experiment_config['trial']['codeDir'] = codeDir
    ~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'trial'
```
