### ISSUE TITLE
Error: tuner_command_channel: Tuner closed connection

### ISSUE THREAD

**Issue by sunze992** [microsoft/nni#5604]
**Describe the issue**:
When I run the nni experiment, the webui gets stuck after a while, and the running and subsequent trials stop. I check the log file, and the contents of each log file are as follows. In 'dispatcher.log', it shows that 'AttributeError: module 'numpy' has no attribute 'float'.'. I would like to know how to solve this problem, thanks!

**Environment**:
- NNI version: 2.10.1
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu
- Python version: 3.10.10
- PyTorch/TensorFlow version: PyTorch 1.13.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: No
- **numpy: 1.24.3**

**Configuration**:
```
experimentName: xxx

searchSpace:
  batch_size:
    _type: choice
    _value: [128]
  xxx.....

trialCommand: python main.py
trialCodeDirectory: .
trialGpuNumber: 1
trialConcurrency: 4
maxExperimentDuration: 100h
maxTrialNumber: 1000

tuner:
  name: TPE  # or SMAC
  classArgs:
    optimize_mode: maximize

assessor:
  name: Curvefitting
  classArgs:
    epoch_num: xx
    start_step: xx
    threshold: xx
    gap: xx

trainingService:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 1
  gpuIndices: [4, 5, 6, 7]
```

**Log message**:
 - nnimanager.log:
```
[2023-06-09 12:57:11] INFO (main) Start NNI manager
[2023-06-09 12:57:11] INFO (NNIDataStore) Datastore initialization done
[2023-06-09 12:57:11] INFO (RestServer) Starting REST server at port 8080, URL prefix: "/"
[2023-06-09 12:57:11] WARNING (NNITensorboardManager) Tensorboard may not installed, if you want to use tensorboard, please check if tensorboard installed.
[2023-06-09 12:57:11] INFO (RestServer) REST server started.
[2023-06-09 12:57:12] INFO (NNIManager) Starting experiment: qa7ydetw
[2023-06-09 12:57:12] INFO (NNIManager) Setup training service...
[2023-06-09 12:57:12] INFO (LocalTrainingService) Construct local machine training service.
[2023-06-09 12:57:12] INFO (NNIManager) Setup tuner...
[2023-06-09 12:57:12] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2023-06-09 12:57:13] INFO (NNIManager) Add event listeners
[2023-06-09 12:57:13] INFO (LocalTrainingService) Run local machine training service.
[2023-06-09 12:57:13] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2023-06-09 12:57:13] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "lr": 0.01, "momentum": 0.9, "n_heads": 64, "n_layers": 1, "d_ff": 512, "ffn_dropout": 0.5687418247198174, "pe_dropout": 0.3795992922324143, "attn_dropout": 0.31940210733313745, "gru_dropout": 0.7501120836764036, "head_dropout": 0.9413345527713036, "label_smoothing": 0.2971732637510747, "pool": 0}, "parameter_index": 0}
[2023-06-09 12:57:13] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "lr": 0.01, "momentum": 0.9, "n_heads": 64, "n_layers": 1, "d_ff": 512, "ffn_dropout": 0.6106341933273577, "pe_dropout": 0.362797822930322, "attn_dropout": 0.3928725106416544, "gru_dropout": 0.3227819485793446, "head_dropout": 0.872189272426159, "label_smoothing": 0.350726674354764, "pool": 0}, "parameter_index": 0}
[2023-06-09 12:57:13] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 2, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "lr": 0.01, "momentum": 0.9, "n_heads": 64, "n_layers": 1, "d_ff": 512, "ffn_dropout": 0.5297279262160532, "pe_dropout": 0.40210539352497937, "attn_dropout": 0.368406504769002, "gru_dropout": 0.3530454310598614, "head_dropout": 0.8271236612115623, "label_smoothing": 0.2640100599154913, "pool": 0}, "parameter_index": 0}
[2023-06-09 12:57:13] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 3, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "lr": 0.01, "momentum": 0.9, "n_heads": 64, "n_layers": 1, "d_ff": 512, "ffn_dropout": 0.6816049034866344, "pe_dropout": 0.36311316138448635, "attn_dropout": 0.3026207961686919, "gru_dropout": 0.703280384754806, "head_dropout": 0.8660018580114488, "label_smoothing": 0.1821250821626217, "pool": 0}, "parameter_index": 0}
[2023-06-09 12:57:18] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 0,
  hyperParameters: {
    value: '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "lr": 0.01, "momentum": 0.9, "n_heads": 64, "n_layers": 1, "d_ff": 512, "ffn_dropout": 0.5687418247198174, "pe_dropout": 0.3795992922324143, "attn_dropout": 0.31940210733313745, "gru_dropout": 0.7501120836764036, "head_dropout": 0.9413345527713036, "label_smoothing": 0.2971732637510747, "pool": 0}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-06-09 12:57:18] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 1,
  hyperParameters: {
    value: '{"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "lr": 0.01, "momentum": 0.9, "n_heads": 64, "n_layers": 1, "d_ff": 512, "ffn_dropout": 0.6106341933273577, "pe_dropout": 0.362797822930322, "attn_dropout": 0.3928725106416544, "gru_dropout": 0.3227819485793446, "head_dropout": 0.872189272426159, "label_smoothing": 0.350726674354764, "pool": 0}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-06-09 12:57:18] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 2,
  hyperParameters: {
    value: '{"parameter_id": 2, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "lr": 0.01, "momentum": 0.9, "n_heads": 64, "n_layers": 1, "d_ff": 512, "ffn_dropout": 0.5297279262160532, "pe_dropout": 0.40210539352497937, "attn_dropout": 0.368406504769002, "gru_dropout": 0.3530454310598614, "head_dropout": 0.8271236612115623, "label_smoothing": 0.2640100599154913, "pool": 0}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-06-09 12:57:18] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 3,
  hyperParameters: {
    value: '{"parameter_id": 3, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "lr": 0.01, "momentum": 0.9, "n_heads": 64, "n_layers": 1, "d_ff": 512, "ffn_dropout": 0.6816049034866344, "pe_dropout": 0.36311316138448635, "attn_dropout": 0.3026207961686919, "gru_dropout": 0.703280384754806, "head_dropout": 0.8660018580114488, "label_smoothing": 0.1821250821626217, "pool": 0}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-06-09 12:57:23] INFO (NNIManager) Trial job wGF5H status changed from WAITING to RUNNING
[2023-06-09 12:57:23] INFO (NNIManager) Trial job l1qUb status changed from WAITING to RUNNING
[2023-06-09 12:57:23] INFO (NNIManager) Trial job TpSLZ status changed from WAITING to RUNNING
[2023-06-09 12:57:23] INFO (NNIManager) Trial job vJ6Yb status changed from WAITING to RUNNING
[2023-06-09 14:08:37] INFO (NNIManager) Trial job vJ6Yb status changed from RUNNING to SUCCEEDED
[2023-06-09 14:08:37] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 4, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "lr": 0.01, "momentum": 0.9, "n_heads": 64, "n_layers": 1, "d_ff": 1024, "ffn_dropout": 0.5147415801616881, "pe_dropout": 0.3754598540657963, "attn_dropout": 0.28474165110165683, "gru_dropout": 0.6126774117630752, "head_dropout": 0.904972479249912, "label_smoothing": 0.32764941826042104, "pool": 0}, "parameter_index": 0}
[2023-06-09 14:08:42] INFO (NNIManager) Trial job l1qUb status changed from RUNNING to SUCCEEDED
[2023-06-09 14:08:42] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 4,
  hyperParameters: {
    value: '{"parameter_id": 4, "parameter_source": "algorithm", "parameters": {"batch_size": 128, "lr": 0.01, "momentum": 0.9, "n_heads": 64, "n_layers": 1, "d_ff": 1024, "ffn_dropout": 0.5147415801616881, "pe_dropout": 0.3754598540657963, "attn_dropout": 0.28474165110165683, "gru_dropout": 0.6126774117630752, "head_dropout": 0.904972479249912, "label_smoothing": 0.32764941826042104, "pool": 0}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-06-09 14:08:44] ERROR (tuner_command_channel.WebSocketChannel) Error: Error: tuner_command_channel: Tuner closed connection
    at WebSocket.handleWsClose (/home/sunze/miniconda3/lib/python3.10/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:83:26)
    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (/home/sunze/miniconda3/lib/python3.10/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:246:10)
    at Socket.socketOnClose (/home/sunze/miniconda3/lib/python3.10/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:1127:15)
    at Socket.emit (node:events:526:28)
    at TCP.<anonymous> (node:net:687:12)
```

 - dispatcher.log:
```
[2023-06-09 20:57:12] INFO (nni.tuner.tpe/MainThread) Using random seed 829346290
[2023-06-09 20:57:12] INFO (curvefitting_Assessor/MainThread) Successfully initials the curvefitting assessor
[2023-06-09 20:57:12] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2023-06-09 22:08:37] INFO (curvefitting_Assessor/Thread-2 (command_queue_worker)) Updated completed best performance, trial job id: vJ6Yb
[2023-06-09 22:08:38] INFO (curvefitting_Assessor/Thread-2 (command_queue_worker)) List of effective model: ['vap', 'pow3', 'linear', 'logx_linear', 'dr_hill_zero_background', 'log_power', 'pow4', 'mmf', 'exp4', 'weibull', 'janoschek']
[2023-06-09 22:08:38] ERROR (curvefitting_Assessor/Thread-2 (command_queue_worker)) unrecognize exception in curvefitting_assessor module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Traceback (most recent call last):
  File "/home/sunze/miniconda3/lib/python3.10/site-packages/nni/algorithms/hpo/curvefitting_assessor/curvefitting_assessor.py", line 120, in assess_trial
    predict_y = curvemodel.predict(scalar_trial_history)
  File "/home/sunze/miniconda3/lib/python3.10/site-packages/nni/algorithms/hpo/curvefitting_assessor/model_factory.py", line 326, in predict
    self.mcmc_sampling()
  File "/home/sunze/miniconda3/lib/python3.10/site-packages/nni/algorithms/hpo/curvefitting_assessor/model_factory.py", line 290, in mcmc_sampling
    init_weight = np.ones((self.effective_model_num), dtype=np.float) / self.effective_model_num
  File "/home/sunze/miniconda3/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
[2023-06-09 22:08:38] ERROR (nni.runtime.msg_dispatcher_base/Thread-2 (command_queue_worker)) Result of Assessor.assess_trial must be an object of AssessResult, not <class 'NoneType'>
Traceback (most recent call last):
  File "/home/sunze/miniconda3/lib/python3.10/site-packages/nni/runtime/msg_dispatcher_base.py", line 108, in command_queue_worker
    self.process_command(command, data)
  File "/home/sunze/miniconda3/lib/python3.10/site-packages/nni/runtime/msg_dispatcher_base.py", line 154, in process_command
    command_handlers[command](data)
  File "/home/sunze/miniconda3/lib/python3.10/site-packages/nni/runtime/msg_dispatcher.py", line 149, in handle_report_metric_data
    self._handle_intermediate_metric_data(data)
  File "/home/sunze/miniconda3/lib/python3.10/site-packages/nni/runtime/msg_dispatcher.py", line 234, in _handle_intermediate_metric_data
    raise RuntimeError(msg % type(result))
RuntimeError: Result of Assessor.assess_trial must be an object of AssessResult, not <class 'NoneType'>
[2023-06-09 22:08:42] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2023-06-09 22:08:44] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated
```

 - nnictl stdout:
```
--------------------------------------------------------------------------------
Experiment qa7ydetw start: 2023-06-09 20:57:11.300714
--------------------------------------------------------------------------------
```

 - nnictl stderr:
```
--------------------------------------------------------------------------------
Experiment qa7ydetw start: 2023-06-09 20:57:11.300714
--------------------------------------------------------------------------------
/home/sunze/miniconda3/lib/python3.10/site-packages/nni/algorithms/hpo/curvefitting_assessor/curvefunctions.py:56: RuntimeWarning: overflow encountered in power
  return c - a * x**(-alpha)
/home/sunze/miniconda3/lib/python3.10/site-packages/nni/algorithms/hpo/curvefitting_assessor/curvefunctions.py:56: RuntimeWarning: overflow encountered in multiply
  return c - a * x**(-alpha)
/home/sunze/miniconda3/lib/python3.10/site-packages/nni/algorithms/hpo/curvefitting_assessor/curvefunctions.py:124: RuntimeWarning: invalid value encountered in scalar power
  return (theta * x**eta) / (kappa**eta + x**eta)
/home/sunze/miniconda3/lib/python3.10/site-packages/scipy/optimize/_minpack_py.py:906: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
/home/sunze/miniconda3/lib/python3.10/site-packages/nni/algorithms/hpo/curvefitting_assessor/curvefunctions.py:171: RuntimeWarning: invalid value encountered in power
  return c - (a*x+b)**-alpha
/home/sunze/miniconda3/lib/python3.10/site-packages/nni/algorithms/hpo/curvefitting_assessor/curvefunctions.py:196: RuntimeWarning: invalid value encountered in power
  return alpha - (alpha - beta) / (1. + (kappa * x)**delta)
/home/sunze/miniconda3/lib/python3.10/site-packages/nni/algorithms/hpo/curvefitting_assessor/curvefunctions.py:220: RuntimeWarning: overflow encountered in exp
  return c - np.exp(-a*(x**alpha)+b)
/home/sunze/miniconda3/lib/python3.10/site-packages/nni/algorithms/hpo/curvefitting_assessor/curvefunctions.py:242: RuntimeWarning: divide by zero encountered in divide
  return c - a / np.log(x)
/home/sunze/miniconda3/lib/python3.10/site-packages/nni/algorithms/hpo/curvefitting_assessor/curvefunctions.py:242: RuntimeWarning: divide by zero encountered in scalar divide
  return c - a / np.log(x)
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: tuner_command_channel: Tuner closed connection
    at WebSocket.handleWsClose (/home/sunze/miniconda3/lib/python3.10/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:83:26)
    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (/home/sunze/miniconda3/lib/python3.10/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:246:10)
    at Socket.socketOnClose (/home/sunze/miniconda3/lib/python3.10/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:1127:15)
    at Socket.emit (node:events:526:28)
    at TCP.<anonymous> (node:net:687:12)
Emitted 'error' event at:
    at WebSocketChannelImpl.handleError (/home/sunze/miniconda3/lib/python3.10/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:135:22)
    at WebSocket.handleWsClose (/home/sunze/miniconda3/lib/python3.10/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:83:14)
    at WebSocket.emit (node:events:538:35)
    [... lines matching original stack trace ...]
    at TCP.<anonymous> (node:net:687:12)
Thrown at:
    at handleWsClose (/home/sunze/miniconda3/lib/python3.10/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:83:26)
    at emit (node:events:538:35)
    at emitClose (/home/sunze/miniconda3/lib/python3.10/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:246:10)
    at socketOnClose (/home/sunze/miniconda3/lib/python3.10/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:1127:15)
    at emit (node:events:526:28)
    at node:net:687:12
```

**How to reproduce it?**:

**Comment by Lijiaoa** [comment]
So could you try nni `v3.0rc1` to test it? @sunze992

**Comment by sunze992** [comment]
> 

I tried this version, but ran into another problem: webui wouldn't start. I found out that glibc version is 2.27. It seems that glibc version is too low for webui to start. glibc is the underlying library of Ubuntu system, so I can't upgrade it easily to avoid all kinds of system problems. So now I have this new problem, do you know how to solve it? Thanks!

**Comment by Lijiaoa** [comment]
Seems that you indeed need an updated version for [Ubuntu](https://github.com/microsoft/nni/pull/5530)

**Comment by Hzbeta** [comment]
I've encountered the same issue while using v3.0rc1 on Ubuntu 22.04. It seems like the curve fitting assessor requires a version of numpy that is 1.1 or earlier?
