### ISSUE TITLE
Error on creating custom trial

### ISSUE THREAD

**Issue by ferqui** [microsoft/nni#5607]
**Describe the issue**:
Hi, I have a problem when I add a custom trial to the experiment from the webui. When pressing the button of "customized trial" in the trial jobs list, I create a new trial and start running, but suddenly the experiment gives an error because the trial doesn't have the parameter_id field. Is there any solution for it? Thank you.

**Environment**:
- NNI version: 2.10.1
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu 22.04.2 LTS
- Server OS (for remote mode only):
- Python version: 3.10.11
- PyTorch/TensorFlow version: PyTorch 1.13.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: No

**Configuration**:

```
search_space:
  n_rec:
    _type: choice
    _value: [ 64, 128, 256 ]
  lr:
    _type: loguniform
    _value: [ 0.000001, 0.1 ]
  thr:
    _type: uniform
    _value: [ 0.0, 10.0 ]
  n_ref:
    _type: loguniform
    _value: [ 0.0001, 0.5 ]
  tau_v:
    _type: loguniform
    _value: [ 3.0, 1000. ]
  tau_a:
    _type: loguniform
    _value: [ 3.0, 1000. ]
  tau_o:
    _type: loguniform
    _value: [ 3.0, 1000. ]
  theta:
    _type: uniform
    _value: [ 0.0, 10.0 ]
  sg_scale:
    _type: uniform
    _value: [ 0.03, 1.0 ]
  freq:
    _type: uniform
    _value: [ 10.0, 100.0 ]

trial_command: python nni_experiment.py
trial_code_directory: .

trial_concurrency: 1
max_trial_number: 100
assessor:
  name: Medianstop
  class_args:
    start_step: 50

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local
```

**Log message**:
 - nnimanager.log:
 
```
[2023-06-12 11:03:46] INFO (main) Start NNI manager
[2023-06-12 11:03:46] INFO (NNIDataStore) Datastore initialization done
[2023-06-12 11:03:46] INFO (RestServer) Starting REST server at port 8080, URL prefix: "/"
[2023-06-12 11:03:46] INFO (RestServer) REST server started.
[2023-06-12 11:03:46] INFO (NNIManager) Starting experiment: c1qxbaym
[2023-06-12 11:03:47] INFO (NNIManager) Setup training service...
[2023-06-12 11:03:47] INFO (LocalTrainingService) Construct local machine training service.
[2023-06-12 11:03:47] INFO (NNIManager) Setup tuner...
[2023-06-12 11:03:47] INFO (NNIManager) Change NNIManager status from: INITIALIZED to: RUNNING
[2023-06-12 11:03:48] INFO (NNIManager) Add event listeners
[2023-06-12 11:03:48] INFO (LocalTrainingService) Run local machine training service.
[2023-06-12 11:03:48] INFO (NNIManager) NNIManager received command from dispatcher: ID, 
[2023-06-12 11:03:48] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"n_rec": 256, "lr": 0.011448074517379067, "thr": 3.597306519090515, "n_ref": 0.008715046131089057, "tau_v": 7.573031603546667, "tau_a": 29.990669571487363, "tau_o": 128.18680794623737, "theta": 2.102562278413914, "sg_scale": 0.9624626013431545, "freq": 45.56603200372938}, "parameter_index": 0}
[2023-06-12 11:03:48] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"n_rec": 256, "lr": 3.3218768175937776e-05, "thr": 7.576678438876874, "n_ref": 0.4766486382392336, "tau_v": 4.566249658132258, "tau_a": 34.182390708234216, "tau_o": 3.093741894351405, "theta": 8.826553595697263, "sg_scale": 0.5791697231669481, "freq": 68.55767486427999}, "parameter_index": 0}
[2023-06-12 11:03:53] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 0,
  hyperParameters: {
    value: '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"n_rec": 256, "lr": 0.011448074517379067, "thr": 3.597306519090515, "n_ref": 0.008715046131089057, "tau_v": 7.573031603546667, "tau_a": 29.990669571487363, "tau_o": 128.18680794623737, "theta": 2.102562278413914, "sg_scale": 0.9624626013431545, "freq": 45.56603200372938}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-06-12 11:03:53] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 1,
  hyperParameters: {
    value: '{"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"n_rec": 256, "lr": 3.3218768175937776e-05, "thr": 7.576678438876874, "n_ref": 0.4766486382392336, "tau_v": 4.566249658132258, "tau_a": 34.182390708234216, "tau_o": 3.093741894351405, "theta": 8.826553595697263, "sg_scale": 0.5791697231669481, "freq": 68.55767486427999}, "parameter_index": 0}',
    index: 0
  },
  placementConstraint: { type: 'None', gpus: [] }
}
[2023-06-12 11:03:58] INFO (NNIManager) Trial job ExCBx status changed from WAITING to RUNNING
[2023-06-12 11:03:58] INFO (NNIManager) Trial job ciNRn status changed from WAITING to RUNNING
[2023-06-12 11:14:50] INFO (NNITensorboardManager) tensorboard: ExCBx,ciNRn /home/sic/nni-experiments/c1qxbaym/trials/ExCBx/tensorboard,/home/sic/nni-experiments/c1qxbaym/trials/ciNRn/tensorboard
[2023-06-12 11:14:50] INFO (NNITensorboardManager) tensorboard start command: tensorboard,--bind_all --logdir_spec=0-ExCBx:/home/sic/nni-experiments/c1qxbaym/trials/ExCBx/tensorboard,1-ciNRn:/home/sic/nni-experiments/c1qxbaym/trials/ciNRn/tensorboard,--port=6006
[2023-06-12 11:14:50] INFO (NNITensorboardManager) tensorboard task id: zSWdn
[2023-06-12 11:14:50] INFO (NNIRestHandler) TensorboardTaskDetail {
  id: 'zSWdn',
  status: 'RUNNING',
  trialJobIdList: [ 'ExCBx', 'ciNRn' ],
  trialLogDirectoryList: [
    '/home/sic/nni-experiments/c1qxbaym/trials/ExCBx/tensorboard',
    '/home/sic/nni-experiments/c1qxbaym/trials/ciNRn/tensorboard'
  ],
  pid: 2519812,
  port: '6006'
}
[2023-06-12 11:14:50] INFO (NNITensorboardManager) tensorboardTask zSWdn status update: RUNNING to DOWNLOADING_DATA
[2023-06-12 11:14:50] INFO (NNITensorboardManager) tensorboardTask zSWdn status update: DOWNLOADING_DATA to RUNNING
[2023-06-12 11:17:08] INFO (NNIManager) User cancelTrialJob: ExCBx
[2023-06-12 11:17:09] INFO (NNIManager) Trial job ExCBx status changed from RUNNING to USER_CANCELED
[2023-06-12 11:17:09] INFO (NNIManager) submitTrialJob: form: {
  sequenceId: 2,
  hyperParameters: {
    value: '{"parameter_id":null,"parameter_source":"customized","parameters":{"n_rec":256,"lr":0.0005,"thr":1,"n_ref":0.05,"tau_v":1000,"tau_a":1000,"tau_o":1000,"theta":5,"sg_scale":0.3,"freq":100}}',
    index: 0
  }
}
[2023-06-12 11:17:09] INFO (NNIManager) NNIManager received command from dispatcher: TR, {"parameter_id": 2, "parameter_source": "algorithm", "parameters": {"n_rec": 256, "lr": 2.228695710339134e-05, "thr": 2.6451070628903253, "n_ref": 0.002383796963784488, "tau_v": 21.571986754085653, "tau_a": 3.8068845699351344, "tau_o": 3.970901210844971, "theta": 5.8263479076965226, "sg_scale": 0.7507240392417996, "freq": 30.6873476711282}, "parameter_index": 0}
[2023-06-12 11:17:14] INFO (NNIManager) Trial job SjU2n status changed from WAITING to RUNNING
[2023-06-12 11:17:32] INFO (NNITensorboardManager) Forced stopping all tensorboard task.
[2023-06-12 11:17:32] INFO (NNITensorboardManager) tensorboardTask zSWdn status update: RUNNING to STOPPING
[2023-06-12 11:17:32] INFO (NNITensorboardManager) tensorboardTask zSWdn status update: STOPPING to STOPPED
[2023-06-12 11:17:32] INFO (NNITensorboardManager) All tensorboard task stopped.
[2023-06-12 11:19:15] ERROR (tuner_command_channel.WebSocketChannel) Error: Error: tuner_command_channel: Tuner closed connection
    at WebSocket.handleWsClose (/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:83:26)
    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:246:10)
    at Socket.socketOnClose (/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:1127:15)
    at Socket.emit (node:events:526:28)
    at TCP.<anonymous> (node:net:687:12)
```

 - dispatcher.log:
```
[2023-06-12 11:03:48] INFO (nni.tuner.tpe/MainThread) Using random seed 606063535
[2023-06-12 11:03:48] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher started
[2023-06-12 11:17:09] WARNING (medianstop_Assessor/Thread-2 (command_queue_worker)) trial_end: trial_job_id does not exist in running_history
[2023-06-12 11:18:34] ERROR (nni.runtime.msg_dispatcher_base/Thread-2 (command_queue_worker)) '<=' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni/runtime/msg_dispatcher_base.py", line 109, in command_queue_worker
    self.process_command(command, data)
  File "/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni/runtime/msg_dispatcher_base.py", line 155, in process_command
    command_handlers[command](data)
  File "/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni/runtime/msg_dispatcher.py", line 135, in handle_report_metric_data
    if self.is_created_in_previous_exp(data['parameter_id']):
  File "/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni/recoverable.py", line 47, in is_created_in_previous_exp
    return param_id <= self.recovered_max_param_id
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
[2023-06-12 11:19:15] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher exiting...
[2023-06-12 11:19:15] INFO (nni.runtime.msg_dispatcher_base/MainThread) Dispatcher terminiated
```
 - nnictl stdout and stderr:
nnictl_stderr.log
```
--------------------------------------------------------------------------------
Experiment c1qxbaym start: 2023-06-12 11:03:45.935189
--------------------------------------------------------------------------------
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: tuner_command_channel: Tuner closed connection
    at WebSocket.handleWsClose (/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:83:26)
    at WebSocket.emit (node:events:538:35)
    at WebSocket.emitClose (/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:246:10)
    at Socket.socketOnClose (/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:1127:15)
    at Socket.emit (node:events:526:28)
    at TCP.<anonymous> (node:net:687:12)
Emitted 'error' event at:
    at WebSocketChannelImpl.handleError (/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:135:22)
    at WebSocket.handleWsClose (/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:83:14)
    at WebSocket.emit (node:events:538:35)
    [... lines matching original stack trace ...]
    at TCP.<anonymous> (node:net:687:12)
Thrown at:
    at handleWsClose (/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni_node/core/tuner_command_channel/websocket_channel.js:83:26)
    at emit (node:events:538:35)
    at emitClose (/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:246:10)
    at socketOnClose (/home/sic/anaconda3/envs/ENV/lib/python3.10/site-packages/nni_node/node_modules/express-ws/node_modules/ws/lib/websocket.js:1127:15)
    at emit (node:events:526:28)
    at node:net:687:12
```

nnictl_stdout.log
```
--------------------------------------------------------------------------------
Experiment c1qxbaym start: 2023-06-12 11:03:45.935189
--------------------------------------------------------------------------------
{'n_rec': {'_type': 'choice', '_value': [64, 128, 256]}, 'lr': {'_type': 'loguniform', '_value': [1e-06, 0.1]}, 'thr': {'_type': 'uniform', '_value': [0, 10]}, 'n_ref': {'_type': 'loguniform', '_value': [0.0001, 0.5]}, 'tau_v': {'_type': 'loguniform', '_value': [3, 1000]}, 'tau_a': {'_type': 'loguniform', '_value': [3, 1000]}, 'tau_o': {'_type': 'loguniform', '_value': [3, 1000]}, 'theta': {'_type': 'uniform', '_value': [0, 10]}, 'sg_scale': {'_type': 'uniform', '_value': [0.03, 1]}, 'freq': {'_type': 'uniform', '_value': [10, 100]}}
2
{'parameter_id': 0, 'trial_job_id': 'ExCBx', 'type': 'PERIODICAL', 'sequence': 0, 'value': '0.04779411852359772'}
{'parameter_id': 1, 'trial_job_id': 'ciNRn', 'type': 'PERIODICAL', 'sequence': 0, 'value': '0.04779411852359772'}
{'parameter_id': 0, 'trial_job_id': 'ExCBx', 'type': 'PERIODICAL', 'sequence': 1, 'value': '0.048253677785396576'}
{'parameter_id': 1, 'trial_job_id': 'ciNRn', 'type': 'PERIODICAL', 'sequence': 1, 'value': '0.048253677785396576'}
{'parameter_id': 0, 'trial_job_id': 'ExCBx', 'type': 'PERIODICAL', 'sequence': 2, 'value': '0.04641544073820114'}
{'parameter_id': 1, 'trial_job_id': 'ciNRn', 'type': 'PERIODICAL', 'sequence': 2, 'value': '0.04641544073820114'}
{'parameter_id': 0, 'trial_job_id': 'ExCBx', 'type': 'PERIODICAL', 'sequence': 3, 'value': '0.048713237047195435'}
{'parameter_id': 1, 'trial_job_id': 'ciNRn', 'type': 'PERIODICAL', 'sequence': 3, 'value': '0.048713237047195435'}
{'parameter_id': 0, 'trial_job_id': 'ExCBx', 'type': 'PERIODICAL', 'sequence': 4, 'value': '0.048253677785396576'}
{'parameter_id': 1, 'trial_job_id': 'ciNRn', 'type': 'PERIODICAL', 'sequence': 4, 'value': '0.048253677785396576'}
{'parameter_id': 0, 'trial_job_id': 'ExCBx', 'type': 'PERIODICAL', 'sequence': 5, 'value': '0.049172792583703995'}
{'parameter_id': 1, 'trial_job_id': 'ciNRn', 'type': 'PERIODICAL', 'sequence': 5, 'value': '0.049172792583703995'}
{'parameter_id': 0, 'trial_job_id': 'ExCBx', 'type': 'PERIODICAL', 'sequence': 6, 'value': '0.04963235184550285'}
{'parameter_id': 1, 'trial_job_id': 'ciNRn', 'type': 'PERIODICAL', 'sequence': 6, 'value': '0.04963235184550285'}
{'parameter_id': 0, 'trial_job_id': 'ExCBx', 'type': 'PERIODICAL', 'sequence': 7, 'value': '0.046875'}
{'parameter_id': 1, 'trial_job_id': 'ciNRn', 'type': 'PERIODICAL', 'sequence': 7, 'value': '0.046875'}
{'parameter_id': 0, 'trial_job_id': 'ExCBx', 'type': 'PERIODICAL', 'sequence': 8, 'value': '0.04779411852359772'}
{'parameter_id': 1, 'trial_job_id': 'ciNRn', 'type': 'PERIODICAL', 'sequence': 8, 'value': '0.04779411852359772'}
{'parameter_id': 0, 'trial_job_id': 'ExCBx', 'type': 'PERIODICAL', 'sequence': 9, 'value': '0.048253677785396576'}
{'parameter_id': 1, 'trial_job_id': 'ciNRn', 'type': 'PERIODICAL', 'sequence': 9, 'value': '0.048253677785396576'}
{'parameter_id': 0, 'trial_job_id': 'ExCBx', 'type': 'PERIODICAL', 'sequence': 10, 'value': '0.046875'}
{'parameter_id': 1, 'trial_job_id': 'ciNRn', 'type': 'PERIODICAL', 'sequence': 10, 'value': '0.046875'}
{'trial_job_id': 'ExCBx', 'event': 'USER_CANCELED', 'hyper_params': '{"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"n_rec": 256, "lr": 0.011448074517379067, "thr": 3.597306519090515, "n_ref": 0.008715046131089057, "tau_v": 7.573031603546667, "tau_a": 29.990669571487363, "tau_o": 128.18680794623737, "theta": 2.102562278413914, "sg_scale": 0.9624626013431545, "freq": 45.56603200372938}, "parameter_index": 0}'}
1
{'parameter_id': 1, 'trial_job_id': 'ciNRn', 'type': 'PERIODICAL', 'sequence': 11, 'value': '0.048713237047195435'}
{'parameter_id': None, 'trial_job_id': 'SjU2n', 'type': 'PERIODICAL', 'sequence': 0, 'value': '0.04779411852359772'}
```

**Comment by Lijiaoa** [comment]
Could you use nni v3.0rc1?

**Comment by ferqui** [comment]
Hi, seems that on v3.0rc1 works thanks!
