### ISSUE TITLE
new trial created by nnictl does not have parameter_index property in hyperparameters.

### ISSUE THREAD

**Issue by weizhang25** [microsoft/nni#5611]
**Describe the issue**:
1. Use "nnictl trial ls my_exp_id" to get a list of trial jobs.
2. Pick a running trialJob, get its 'hyperParameters'][0])["parameters"] value. (say trial job id is x)
3. Get the trial jobs url by 
experiments_config = Experiments()
    experiments_dict = experiments_config.get_all_experiments()
    rest_port = experiments_dict.get(experiment_id).get('port')
    url = trial_jobs_url(port=rest_port)
4. rest_post the value obtained from step 2 to the url obtained from step 3, to start a new trial. (say the trial job id is y)
5. The trial y is listed in "nnictl trial ls my_exp_id". But it does have parameter_index attribute in its hyperparameters attribute.
6. Using Experiment.list_trial_jobs() on this experiment will cause exception below:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/hpo_tools/nni_manager/server.py", line 340, in _monitor_nni_experiment
    self._trials = self._experiment.list_trial_jobs()
  File "/usr/lib/python3.7/site-packages/nni/experiment/experiment.py", line 313, in list_trial_jobs
    return [TrialJob(**trial_job) for trial_job in resp]
  File "/usr/lib/python3.7/site-packages/nni/experiment/experiment.py", line 313, in <listcomp>
    return [TrialJob(**trial_job) for trial_job in resp]
  File "/usr/lib/python3.7/site-packages/nni/experiment/data.py", line 136, in __init__
    self.hyperParameters = [TrialHyperParameters(**json.loads(e)) for e in hyperParameters]
  File "/usr/lib/python3.7/site-packages/nni/experiment/data.py", line 136, in <listcomp>
    self.hyperParameters = [TrialHyperParameters(**json.loads(e)) for e in hyperParameters]
TypeError: __init__() missing 1 required positional argument: 'parameter_index'
WARNING:sys:failed to get nni trial job list
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/hpo_tools/nni_manager/server.py", line 340, in _monitor_nni_experiment
    self._trials = self._experiment.list_trial_jobs()
  File "/usr/lib/python3.7/site-packages/nni/experiment/experiment.py", line 313, in list_trial_jobs
    return [TrialJob(**trial_job) for trial_job in resp]
  File "/usr/lib/python3.7/site-packages/nni/experiment/experiment.py", line 313, in <listcomp>
    return [TrialJob(**trial_job) for trial_job in resp]
  File "/usr/lib/python3.7/site-packages/nni/experiment/data.py", line 136, in __init__
    self.hyperParameters = [TrialHyperParameters(**json.loads(e)) for e in hyperParameters]
  File "/usr/lib/python3.7/site-packages/nni/experiment/data.py", line 136, in <listcomp>
    self.hyperParameters = [TrialHyperParameters(**json.loads(e)) for e in hyperParameters]
TypeError: __init__() missing 1 required positional argument: 'parameter_index'收起

#########################
the trial job info of trial x and y. Note the 2nd one is missing parameter_index attribute.
[
    {
        "endTime":"2023/06/16 08:30:44",
        "finalMetricData":[
            {
                "data":"\"{\\\"default\\\": 1.0, \\\"auc\\\": 1.0, \\\"recall\\\": 1.0, \\\"precision\\\": 1.0}\"",
                "parameterId":"0",
                "sequence":0,
                "timestamp":1686875443530,
                "trialJobId":"Y9cHQ",
                "type":"FINAL"
            }
        ],
        "hyperParameters":[
            "{\"parameter_id\":0,\"parameter_source\":\"algorithm\",\"parameters\":{\"${tree_count}\":5,\"${max_depth}\":5},\"parameter_index\":0}"
        ],
        "logPath":"file://localhost:/hpo_user_experiments/expdir/zc5uery7/trials/Y9cHQ",
        "sequenceId":0,
        "startTime":"2023/06/16 08:24:31",
        "status":"SUCCEEDED",
        "trialJobId":"Y9cHQ"
    },
    {
        "endTime":"2023/06/16 08:36:31",
        "finalMetricData":[
            {
                "data":"\"{\\\"default\\\": 1.0, \\\"auc\\\": 1.0, \\\"recall\\\": 1.0, \\\"precision\\\": 1.0}\"",
                "parameterId":null,
                "sequence":0,
                "timestamp":1686875791063,
                "trialJobId":"J5HTr",
                "type":"FINAL"
            }
        ],
        "hyperParameters":[
            "{\"parameter_id\":null,\"parameter_source\":\"customized\",\"parameters\":{\"${tree_count}\":5,\"${max_depth}\":5}}"
        ],
        "logPath":"file://localhost:/hpo_user_experiments/expdir/zc5uery7/trials/J5HTr",
        "sequenceId":1,
        "startTime":"2023/06/16 08:30:51",
        "status":"SUCCEEDED",
        "trialJobId":"J5HTr"
    }
]
##################################################
**Environment**:
- NNI version: 2.9
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only):
- Python version: 3.7
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?: yes

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by Lijiaoa** [comment]
> "parameterId":null,

maybe it caused this error. Could you use nni v3.0rc1 to run your experiments? Also you need to upgrade python to 3.8
