### ISSUE TITLE
Torch version error when running ModelSpeedup?

### ISSUE THREAD

**Issue by aidevmin** [microsoft/nni#5616]
**Describe the issue**:

**Environment**:
- NNI version: 2.10.1
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu
- Server OS (for remote mode only):
- Python version: 3.8.10
- PyTorch/TensorFlow version: 1.10.0a0+3fd9dcf (Pytorch)
- Is conda/virtualenv/venv used?: 
- Is running in Docker?: Yes

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

When I running model speedup, this error is happen
```
model.0.conv  sparsity :  0.5
model.1.conv  sparsity :  0.5
model.2.conv  sparsity :  0.5
Traceback (most recent call last):
  File "pruning_nni.py", line 252, in <module>
    detect()
  File "pruning_nni.py", line 72, in detect
    ModelSpeedup(model, torch.rand(1, 3, 640, 640).to(device), masks).speedup_model()
  File "/opt/conda/lib/python3.8/site-packages/nni/compression/pytorch/speedup/compressor.py", line 73, in __init__
    self.torch_graph = build_module_graph(model, self.dummy_input)
  File "/opt/conda/lib/python3.8/site-packages/nni/common/graph_utils.py", line 25, in build_module_graph
    return TorchModuleGraph(model, dummy_input)
  File "/opt/conda/lib/python3.8/site-packages/nni/common/graph_utils.py", line 265, in __init__
    super().__init__(model, dummy_input, traced_model)
  File "/opt/conda/lib/python3.8/site-packages/nni/common/graph_utils.py", line 58, in __init__
    assert torch.__version__ >= '1.3.1'
AssertionError
```
I check Torch version is `1.10.0a0+3fd9dcf` and it seem meet the above condition. Please check again? Thanks.

**Comment by J-shang** [comment]
hello, could you have a try directly with `torch.__version__ >= '1.3.1'`
![image](https://github.com/microsoft/nni/assets/33053116/3094b76f-b45e-4d0e-bb9e-ab432f5087e6)

**Comment by Lijiaoa** [comment]
Did you have any updates to report? @aidevmin
