### ISSUE TITLE
`from nni.nas import model_context` not working + NasExperimentConfig `use_active_gpu=True` wierd behaviour

### ISSUE THREAD

**Issue by sw33zy** [microsoft/nni#5622]
**Describe the issue**:

I upgraded to the lastest NNI version and `from nni.nas import model_context` is not working. 

Additionally, regarding NasExperiment, should I use `start` or `run` to launch an experiment?

**Environment**:
- NNI version: 3.0rc1
- Training service (local|remote|pai|aml|etc): local
- Client OS: windows
- Python version: 3.9.13
- PyTorch/TensorFlow version: 1.13
- Is conda/virtualenv/venv used?: Poetry
- Is running in Docker?: no

**How to reproduce it?**:

`from nni.nas import model_context`

**Comment by ultmaster** [comment]
I think it might be `from nni.nas.space import model_context`. If you learned that from a tutorial, the doc might need a fix.

I think `config` can be still accessible via `self.config`. But try to do the modification before you pass it to the experiment.

**Comment by sw33zy** [comment]
I saw it here on the release notes for the newest version as `nni.nas.model_context`.

What do you mean by doing the modification before passing it to the experiment? Initializing the NasExperiment with the config? Is it not the same as changing its config after init?

I moved the config setup to the init as such:

```
        _model_space = ModelSelector.instanciate_model(model_class, input_shape, output_dim)
        _evaluator = evaluator()
        exp_config = NasExperimentConfig.default(_model_space, _evaluator, search_strategy)
        exp_config.max_experiment_duration = str(max_duration) + "s"
        exp_config.experiment_name = experiment_name
        exp_config.trial_gpu_number = DEVICE_COUNT
        exp_config.training_service.use_active_gpu = True
        super().__init__(_model_space, _evaluator, search_strategy, exp_config)
``` 
And it works fine without the last two config lines. `use_active_gpu = True` almost crashes my pc... I have the same issue even if I do.

```
        super().__init__(_model_space, _evaluator, search_strategy, exp_config)
        self.config.trial_gpu_number = DEVICE_COUNT
        self.config.training_service.use_active_gpu = True
```

Also, if you notice in my last reply, if a config file is given, I should load and use that config. With the previous version, I could use a config file like:

```
trialGpuNumber: 1
trialConcurrency: 1
trainingService:
  platform: local
  useActiveGpu: True
```

With the latest version, NasExperimentConfig requires an execution engine to be set, and even if I use a config file with `executionEngine: ts`, the corresponding ExecutionEngineConfig object is not created. `ValueError: NasExperimentConfig: type of execution_engine ('ts') is not <class 'nni.nas.experiment.config.engine.ExecutionEngineConfig'>`

How could I achieve something like only changing the attributes which differ from a default config and the loaded config?

**Comment by matluster** [comment]
> What do you mean by doing the modification before passing it to the experiment? Initializing the NasExperiment with the config? Is it not the same as changing its config after init?

Technically yes.

> And it works fine without the last two config lines. use_active_gpu = True almost crashes my pc...

Why is it crashing? What's the error message? Such usage looks fine to me.

> Also, if you notice in my last reply, if a config file is given, I should load and use that config.

I don't think NasExperimentConfig supports to be saved and reloaded. Chances are you can use `exp_config.json()` to dump a config and reload it via `__init__`, but I'm not sure whether it works.

> How could I achieve something like only changing the attributes which differ from a default config and the loaded config?

I don't really understand why changing the attributes directly is not working.

**Comment by sw33zy** [comment]
> Why is it crashing? What's the error message? Such usage looks fine to me.

These are the logs. Even my IDE crashes, bizarre; I'm not sure what I am doing wrong.

[experiment.log](https://github.com/microsoft/nni/files/11925255/experiment.log)
[nnimanager.log](https://github.com/microsoft/nni/files/11925256/nnimanager.log)

I outputted stdout to a file in another experiment and got a longer message

```
[2023-07-01 08:28:44] [32mConfig is not provided. Will try to infer.[0m
[2023-07-01 08:28:44] [32mUsing execution engine based on training service. Trial concurrency is set to 1.[0m
[2023-07-01 08:28:44] [32mUsing simplified model format.[0m
[2023-07-01 08:28:44] [32mUsing local training service.[0m
[2023-07-01 08:28:44] [33mWARNING: GPU found but will not be used. Please set `experiment.config.trial_gpu_number` to the number of GPUs you want to use for each trial.[0m
[2023-07-01 08:28:46] [32mCreating experiment, Experiment ID: [36m345ti2eo[0m
[2023-07-01 08:28:46] [32mStarting web server...[0m
[2023-07-01 08:28:57] [33mWARNING: Timeout, retry...[0m
[2023-07-01 08:29:00] [32mSetting up...[0m
[2023-07-01 08:29:07] [32mWeb portal URLs: [36mhttp://169.254.250.24:8081 http://10.0.0.1:8081 http://192.168.56.1:8081 http://169.254.81.199:8081 http://169.254.164.10:8081 http://169.254.20.238:8081 http://169.254.178.165:8081 http://192.168.1.68:8081 http://169.254.160.23:8081 http://10.0.4.52:8081 http://169.254.168.66:8081 http://127.0.0.1:8081[0m
[2023-07-01 08:29:07] [33mWARNING: Cannot convert CategoricalMultiple([0, 1], n_chosen=1, label='dnn/block_skip_connection0') to legacy format. It will not show on WebUI.[0m
[2023-07-01 08:29:07] [33mWARNING: Cannot convert CategoricalMultiple([0, 1], n_chosen=1, label='dnn/block_skip_connection1') to legacy format. It will not show on WebUI.[0m
[2023-07-01 08:29:07] [33mWARNING: Cannot convert CategoricalMultiple([0, 1], n_chosen=1, label='dnn/block_skip_connection2') to legacy format. It will not show on WebUI.[0m
[2023-07-01 08:29:07] [33mWARNING: Cannot convert CategoricalMultiple([0, 1], n_chosen=1, label='dnn/block_skip_connection3') to legacy format. It will not show on WebUI.[0m
[2023-07-01 08:29:07] [33mWARNING: Cannot convert CategoricalMultiple([0, 1], n_chosen=1, label='dnn/block_skip_connection4') to legacy format. It will not show on WebUI.[0m
[2023-07-01 08:29:07] [32mSuccessfully update searchSpace.[0m
[2023-07-01 08:29:07] [32mCheckpoint saved to C:\Users\Leonardo\nni-experiments\345ti2eo\checkpoint.[0m
[2023-07-01 08:29:07] [32mExperiment initialized successfully. Starting exploration strategy...[0m
[2023-07-01 08:29:50] [31mERROR: Strategy failed to execute.[0m
[2023-07-01 08:29:50] [32mStopping experiment, please wait...[0m
[2023-07-01 08:29:50] [32mCheckpoint saved to C:\Users\Leonardo\nni-experiments\345ti2eo\checkpoint.[0m
[2023-07-01 08:30:10] [31mERROR: HTTPConnectionPool(host='localhost', port=8081): Read timed out. (read timeout=20)[0m
Traceback (most recent call last):
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=8081): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\nni\experiment\experiment.py", line 171, in _stop_nni_manager
    rest.delete(self.port, '/experiment', self.url_prefix)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\nni\experiment\rest.py", line 52, in delete
    request('delete', port, api, prefix=prefix)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\nni\experiment\rest.py", line 31, in request
    resp = requests.request(method, url, timeout=timeout)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Leonardo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8081): Read timed out. (read timeout=20)
[2023-07-01 08:30:10] [33mWARNING: Cannot gracefully stop experiment, killing NNI process...[0m
```

> I don't think NasExperimentConfig supports to be saved and reloaded. Chances are you can use exp_config.json() to dump a config and reload it via __init__, but I'm not sure whether it works.

I don't think I explained myself correctly. In my project, I have two possible cases: no config file is provided -> a default NasExperimentConfig is used; a config file is provided -> use the attributes in this config. I have this to make the process easier if someone wants to execute an experiment remotely, for example, without having to change the code. Previously I could load a config file using `RetiariiExperiment.load('config_path')`, but that doesn't seem feasible now for the reasons I referred to before.

**Comment by ultmaster** [comment]
It looks like the 8081 port can't be connected. Have you successfully run any experiment before on NNI 3.0? including HPO and NAS?

> a config file is provided -> use the attributes in this config.

I guess you have two questions here:

1. How to write this config? -- you can use exp_config.json() to dump a config as a reference or starting point, as I mentioned above.
2. How to load a config? -- you can load config file with `yaml.safe_load` and put it into `__init__` of NasExperimentConfig. But as I mentioned above, no one has tested it and I'm unsure whether that works.

**Comment by sw33zy** [comment]
> It looks like the 8081 port can't be connected. Have you successfully run any experiment before on NNI 3.0? including HPO and NAS?

Yes, NAS runs fine if I don't set active GPU to True.

As for the other question, I managed to find a good workaround. I load the config and then set the execution engine and model format, which works fine.

```
self.config = NasExperimentConfig.load(self.config_file)
self.config.execution_engine = TrainingServiceEngineConfig()
self.config.model_format = SimplifiedModelFormatConfig()
```

**Comment by sw33zy** [comment]
#5628 related maybe?
