### ISSUE TITLE
experiment save on one machine cannot be loaded on another machine

### ISSUE THREAD

**Issue by busFred** [microsoft/nni#5641]
Facing an error with this line. Might be related #5587.
https://github.com/microsoft/nni/blame/fe29f48baa64692e52e32b13a0e2658d70a5d045/nni/tools/nnictl/nnictl_utils.py#L931

Here are some relevant information. I tuned the model on a remove machine under folder `/home/cc/afa` and the experiment was stored in the default `/home/cc/nni-experiments` folder. On my local machine, my user name is `fred` and `nnictl load` it to `/home/fred/nni-experiments`. Storing absolute path in the sqlite database seem to be causing all the issues here.

```
(ace) fred@fred-ThinkPad-T480s:~/Documents/research/afa/exports$ nnictl experiment load --path nni_experiment_9y8foa01.zip --codeDir .
INFO:  Loading...
INFO:  Expand codeDir to /home/fred/Documents/research/afa/exports/.
Traceback (most recent call last):
  File "/home/fred/python_ws/ace/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
             ^^^^^^^^^^^^
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/tools/nnictl/nnictl.py", line 503, in parse_args
    args.func(args)
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/tools/nnictl/nnictl_utils.py", line 943, in load_experiment
    experiment_config['trial']['codeDir'] = codeDir
    ~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'trial'
```

It load successfully after I changed `load_experiment` in `nni/tools/nnictl/nnictl_utils.py` to the following:
```python
    # Step4. Copy code dir
    codeDir = os.path.expanduser(args.codeDir)
    if not os.path.isabs(codeDir):
        codeDir = os.path.join(os.getcwd(), codeDir)
        print_normal('Expand codeDir to %s' % codeDir)
    # experiment_config['trial']['codeDir'] = codeDir
    experiment_config['trialcodeDirectory'] = codeDir
```
**However**, another error showed up upon using `nnictl view`:
```
Traceback (most recent call last):
  File "/home/fred/python_ws/ace/bin/nnictl", line 8, in <module>
    sys.exit(parse_args())
             ^^^^^^^^^^^^
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/tools/nnictl/nnictl.py", line 503, in parse_args
    args.func(args)
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/tools/nnictl/launcher.py", line 129, in view_experiment
    exp.start(port, run_mode=RunMode.Detach)
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/experiment/experiment.py", line 135, in start
    self._start_impl(port, debug, run_mode, None, [])
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/experiment/experiment.py", line 94, in _start_impl
    config = self.config.canonical_copy()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/experiment/config/base.py", line 167, in canonical_copy
    canon._validate_canonical()
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/experiment/config/experiment_config.py", line 155, in _validate_canonical
    super()._validate_canonical()
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/experiment/config/base.py", line 240, in _validate_canonical
    _recursive_validate_child(value)
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/experiment/config/base.py", line 276, in _recursive_validate_child
    child._validate_canonical()
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/experiment/config/training_services/local.py", line 41, in _validate_canonical
    super()._validate_canonical()
  File "/home/fred/python_ws/ace/lib/python3.11/site-packages/nni/experiment/config/training_service.py", line 56, in _validate_canonical
    raise ValueError(f'{cls.__name__}: trial_code_directory "{self.trial_code_directory}" is not a directory')
ValueError: LocalConfig: trial_code_directory "/home/cc/afa/scripts" is not a directory
```

**Comment by busFred** [comment]
here is a brute force, messy, unpleasant, and temporary fix. I just fake trial_code_directory using symbolink. still need quite amount of code refactorization in the library to truely resolve the problem though.

**Comment by CreatArIn** [comment]
Facing the same issue, when trying to load the experiment from another machine. Have someone solved this ( ValueError: LocalConfig: trial_code_directory is not a directory) problem. Or has someone a solution, that all of the relevant information get stored within the experimentWorkingDirectory/logDir path?
