### ISSUE TITLE
Mnist and mnist-annotation example download data failed in azure pipeline integration test env

### ISSUE THREAD

**Issue by chicm-ms** [Microsoft/nni#621]
This issue can be reproduced on azure pipeline, but can not be reproduced on local system.
Can be work around by change trial concurrency to 1:

run mnist or mnist-annotation on azure pipeline, set trial concurrency to 2,  the first trial is succeeded, but the second trial failed to download data.

2019-01-17T06:12:05.6277109Z [{'logPath': 'file://localhost:/home/nni/nni/experiments/ktqszK0E/trials/gxeVR', 'id': 'gxeVR', 'hyperParameters': ['{"parameter_id":0,"parameter_source":"algorithm","parameters":{"mnist/batch_size/choice":32,"mnist/self.learning_rate/loguniform":0.0415214413819498,"mnist/self.conv_size/choice":2,"mnist/max_pool/function_choice":"avg_pool(h_conv1, self.pool_size)","mnist/tf.nn.relu/function_choice":"tf.nn.tanh(conv2d(x_image, w_conv1) + b_conv1)","mnist/dropout_rate/choice":0.5,"mnist/self.hidden_size/choice":1024}}'], 'stderrPath': 'file:/localhost:/home/nni/nni/experiments/ktqszK0E/trials/gxeVR/stderr', 'sequenceId': 0, 'endTime': 1547705518000, 'status': 'FAILED', 'startTime': 1547705514513}, {'logPath': 'file://localhost:/home/nni/nni/experiments/ktqszK0E/trials/lCMVT', 'id': 'lCMVT', 'hyperParameters': ['{"parameter_id":1,"parameter_source":"algorithm","parameters":{"mnist/batch_size/choice":32,"mnist/self.learning_rate/loguniform":0.08640639537947405,"mnist/self.conv_size/choice":2,"mnist/max_pool/function_choice":"avg_pool(h_conv1, self.pool_size)","mnist/tf.nn.relu/function_choice":"tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1)","mnist/dropout_rate/choice":0.9,"mnist/self.hidden_size/choice":124}}'], 'finalMetricData': [{'parameterId': '1', 'timestamp': 1547705522099, 'data': '0.10320000350475311', 'sequence': 0, 'type': 'FINAL', 'trialJobId': 'lCMVT'}], 'sequenceId': 1, 'endTime': 1547705522000, 'status': 'SUCCEEDED', 'startTime': 1547705514527}]Traceback (most recent call last):
2019-01-17T06:12:05.6277553Z   File "mnist.py", line 201, in <module>
2019-01-17T06:12:05.6277591Z     main(vars(get_params()))
2019-01-17T06:12:05.6277643Z   File "mnist.py", line 140, in main
2019-01-17T06:12:05.6277892Z     mnist = input_data.read_data_sets(params['data_dir'], one_hot=True)
2019-01-17T06:12:05.6278148Z   File "/home/nni/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
2019-01-17T06:12:05.6278210Z     return func(*args, **kwargs)
2019-01-17T06:12:05.6278470Z   File "/home/nni/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 260, in read_data_sets
2019-01-17T06:12:05.6278519Z     source_url + TRAIN_IMAGES)
2019-01-17T06:12:05.6278773Z   File "/home/nni/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
2019-01-17T06:12:05.6278814Z     return func(*args, **kwargs)
2019-01-17T06:12:05.6279068Z   File "/home/nni/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 253, in maybe_download
2019-01-17T06:12:05.6279109Z     gfile.Copy(temp_file_name, filepath)
2019-01-17T06:12:05.6279358Z   File "/home/nni/.local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 397, in copy
2019-01-17T06:12:05.6279402Z     compat.as_bytes(oldpath), compat.as_bytes(newpath), overwrite, status)
2019-01-17T06:12:05.6279654Z   File "/home/nni/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
2019-01-17T06:12:05.6279711Z     c_api.TF_GetCode(self.status.status))
2019-01-17T06:12:05.6279755Z tensorflow.python.framework.errors_impl.AlreadyExistsError: file already exists
2019-01-17T06:12:05.9364580Z INFO: Stoping experiment ktqszK0E
2019-01-17T06:12:05.9364727Z INFO: Stop experiment success!
2019-01-17T06:12:05.9796148Z Traceback (most recent call last):
2019-01-17T06:12:05.9796414Z   File "config_test.py", line 105, in run
2019-01-17T06:12:05.9796454Z     run_test(config_file, args.ts, args.local_gpu)
2019-01-17T06:12:05.9796491Z   File "config_test.py", line 80, in run_test
2019-01-17T06:12:05.9797213Z     assert num_succeeded == max_trial_num, 'only %d succeeded trial jobs, there should be %d' % (num_succeeded, max_trial_num)
2019-01-17T06:12:05.9797294Z AssertionError: only 1 succeeded trial jobs, there should be 2

**Comment by xuehui1991** [comment]
I think the reason might be they download in the same folder and have conflict. How about changing their download path?

**Comment by leelaylay** [comment]
I think we can catch the error in the code.
```python
    try:
        mnist = input_data.read_data_sets(params['data_dir'], one_hot=True)
        print('Mnist download data done.')
        logger.debug('Mnist download data done.')
    except tf.errors.AlreadyExistsError:
        print('Mnist download data already done.')
        logger.debug('Mnist download data already done.')
```

**Comment by leelaylay** [comment]
The problem was that multiple trial processes were attempting to download the MNIST dataset at the same time (usually on the same machine), which causes an exception sometimes.
The fix solution can be found in ray-project/ray#1398 and ray-project/ray#1457.
```python
from tensorflow.examples.tutorials.mnist import input_data
import time


def download_mnist_retry(seed=0, max_num_retries=20):
    for _ in range(max_num_retries):
        try:
            return input_data.read_data_sets("MNIST_data", one_hot=True,
                                             seed=seed)
        except tf.errors.AlreadyExistsError:
            time.sleep(1)
    raise Exception("Failed to download MNIST.")
```

```diff
- mnist = input_data.read_data_sets("MNIST_data", one_hot=True)
+ mnist = model.download_mnist_retry(seed=worker_index)
```
