### ISSUE TITLE
cifar10-pytorch example failed on integration test

### ISSUE THREAD

**Issue by chicm-ms** [Microsoft/nni#646]
stty: 'standard input': Inappropriate ioctl for device
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fe41552c358>>
Traceback (most recent call last):
  File "/home/nni/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/nni/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 345, in get
    return ForkingPickler.loads(res)
  File "/home/nni/.local/lib/python3.5/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 181, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 152, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "main.py", line 190, in <module>
    train(epoch)
  File "main.py", line 130, in train
    % (train_loss/(batch_idx+1), 100.*correct/total, correct, total))
  File "/home/nni/myagent/_work/1/s/examples/trials/cifar10_pytorch/utils.py", line 84, in progress_bar
    sys.stdout.write(' ')
  File "/home/nni/myagent/_work/1/s/src/sdk/pynni/nni/common.py", line 53, in write
    self.orig_stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

**Comment by leelaylay** [comment]
It also occurs in the cifar10-keras example. It happens in the recent nni-version while version before 0.4.1 works well. 

1. One fix to cifar10-keras is to disable verbose in the keras api.
2. One fix to cifar10-keras is to repalce the progress_bar function.

**Comment by xuehui1991** [comment]
@leelaylay  Could you help us to test it now? I think it could be work now. Thank you.

**Comment by leelaylay** [comment]
@xuehui1991 @chicm-ms The bug is fixed now.

**Comment by chicm-ms** [comment]
Fixed.
