### ISSUE TITLE
error when runing mnist-annotation

### ISSUE THREAD

**Issue by AllenDun** [Microsoft/nni#664]
hi,
there is error when runing examples/mnist-annotation.

 32 [2019-01-26 16:49:37] DEBUG (mnist_AutoML/MainThread) Mnist download data done.
 33 [2019-01-26 16:49:37] ERROR (mnist_AutoML/MainThread) choice() got multiple values for argument 'name'
 34 Traceback (most recent call last):
 35   File "mnist.py", line 183, in <module>
 36     main(generate_default_params())
 37   File "mnist.py", line 137, in main
 38     learning_rate=params['learning_rate'])
 39   File "mnist.py", line 21, in __init__
 40     self.conv_size = nni.choice(2, 3, 5, 7, name='self.conv_size')
 41 TypeError: choice() got multiple values for argument 'name'

I also found that the generated search space is:

{
"mnist/self.conv_size/choice":{
      "_type": "choice",
     "_value":[
       0,
       1,
       2,
       3
]
}
}

all the nni.choice type were wrong but nni.loguniform type. My system is unbuntu16.04, python3.6. I did not modify the files in the examples/mnist-annotation

**Comment by AllenDun** [comment]
[nnimanager.txt](https://github.com/Microsoft/nni/files/2798863/nnimanager.txt)
[trial.txt](https://github.com/Microsoft/nni/files/2798865/trial.txt)
above are log files

**Comment by scarlett2018** [comment]
@AllenDun - thanks for submitting the issue, which NNI version are you using?

**Comment by AllenDun** [comment]
I tried both v0.4.1 and v0.5

**Comment by Crysple** [comment]
Hi, @AllenDun . Thanks for using NNI.
And because we have modified annotation during the upgrade of nni from 0.4.1 to 0.5, these two version are not compatible.
Currently nni have two package `nni`(or `nnictl`) and `nni-sdk` and I presume that there are some kind of mess. So you need to uninstall all packages about nni and install nni(0.5) again. You might type `python3 -m pip list | grep nni` to see packages you have install and use `uninstall` to uninstall them.

If you'd like to use different versions of nni, you can install in python virtual environment with `--user` flag. Note that this feature has only been supported in version after 0.5

**Comment by AllenDun** [comment]
oh, thanks a lot. I will try it

**Comment by scarlett2018** [comment]
@AllenDun - had you got a chance try @Crysple 's suggestion? how things going with it?

**Comment by AllenDun** [comment]
hi, I just tried and it works fine. Thanks @Crysple
