### ISSUE TITLE
`nnictl --version` does not work with `make dev-install`

### ISSUE THREAD

**Issue by QuanluZhang** [Microsoft/nni#709]
In `make dev-install`, nni python package is not installed (using sym link instead), thus, `nnictl --version` cannot find nni's version.

**Comment by leckie-chn** [comment]
new observation: after `make dev-install` using `nnictl --verison`:
```
nnictl --version

Traceback (most recent call last):

  File "/home/yann/.local/bin/nnictl", line 11, in <module>

    load_entry_point('nni', 'console_scripts', 'nnictl')()

  File "/home/yann/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point

    return get_distribution(dist).load_entry_point(group, name)

  File "/home/yann/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point

    return ep.load()

  File "/home/yann/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2322, in load

    return self.resolve()

  File "/home/yann/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2328, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)

ImportError: No module named 'nni_cmd'
```

**Comment by leckie-chn** [comment]
seems related to this pypi issue: https://github.com/pypa/pip/issues/3160

**Comment by leelaylay** [comment]
The master branch has not fixed it yet.

**Comment by QuanluZhang** [comment]
will resolve this issue in v0.7
