### ISSUE TITLE
Dispatcher error when utilizing SMAC Tuner

### ISSUE THREAD

**Issue by zehuichen123** [Microsoft/nni#715]
- NNI version: 0.5.1
I am running the example code under folder `mnist-annotation/`. I only modified `builtinTunerName` option in `config_gpu.yml` to check each Tuner peformance. When I tried with `SMAC` Tuner, it reported an error in the webpage:
<img src="https://user-images.githubusercontent.com/24351120/52429842-ce902d00-2b3f-11e9-926b-cfa8081b12a7.png" height="400">
However, the command line implies that the experiment was successfully started:
<img src="https://user-images.githubusercontent.com/24351120/52429940-f67f9080-2b3f-11e9-906f-9aa508f43853.png">
I also checked the log file in `dispatcher.log`:

```
[2019-02-08 00:46:02] DEBUG (nni.main/MainThread) START
[2019-02-08 00:46:02] DEBUG (nni.msg_dispatcher/MainThread) Assessor is not configured
[2019-02-08 00:46:02] DEBUG (nni.msg_dispatcher_base/MainThread) waiting receive_message
[2019-02-08 00:46:02] DEBUG (nni.protocol/MainThread) Received command, header: [b'IN000750']
[2019-02-08 00:46:02] DEBUG (nni.protocol/MainThread) Received command, data: [{"mnist/self.conv_size/choice": {"_type": "choice", "_value":[2, 3, 5, 7]}, "mnist/self.hidden_size/choice": {"_type": "choice", "_value": [124, 512, 1024]}, "mnist/self.learning_rate/loguniform": {"_type": "loguniform", "_value": [0.0001, 0.1]}, "mnist/tf.nn.relu/function_choice": {"_type": "choice", "_value": ["tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1)", "tf.nn.sigmoid(conv2d(x_image, w_conv1) + b_conv1)", "tf.nn.tanh(conv2d(x_image, w_conv1) + b_conv1)"]}, "mnist/max_pool/function_choice": {"_type": "choice", "_value": ["max_pool(h_conv1, self.pool_size)", "avg_pool(h_conv1, self.pool_size)"]}, "mnist/batch_size/choice": {"_type": "choice", "_value": [16, 32]}, "mnist/dropout_rate/choice": {"_type": "choice", "_value": [0.5, 0.9]}}]
[2019-02-08 00:46:02] DEBUG (nni.msg_dispatcher_base/MainThread) handle request: command: [CommandType.Initialize], data: [{"mnist/self.conv_size/choice": {"_type": "choice", "_value": [2, 3, 5, 7]}, "mnist/self.hidden_size/choice": {"_type": "choice", "_value": [124, 512, 1024]},"mnist/self.learning_rate/loguniform": {"_type": "loguniform", "_value": [0.0001, 0.1]}, "mnist/tf.nn.relu/function_choice": {"_type": "choice", "_value": ["tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1)", "tf.nn.sigmoid(conv2d(x_image, w_conv1) + b_conv1)", "tf.nn.tanh(conv2d(x_image, w_conv1) + b_conv1)"]}, "mnist/max_pool/function_choice": {"_type": "choice", "_value": ["max_pool(h_conv1, self.pool_size)", "avg_pool(h_conv1, self.pool_size)"]}, "mnist/batch_size/choice": {"_type": "choice", "_value": [16, 32]}, "mnist/dropout_rate/choice": {"_type": "choice", "_value": [0.5, 0.9]}}]
[2019-02-08 00:46:02] INFO (nni.smac_tuner.smac_tuner.SMACTuner/MainThread) SMAC call: /usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/__main__.py --tuner_class_name SMAC --tuner_args {"optimize_mode":"maximize"}
[2019-02-08 00:46:02] PRINT INFO:       Reading scenario file: scenario.txt
[2019-02-08 00:46:02] PRINT ERROR:      Could not parse: mnist/tf.nn.relu/function_choice categorical {tf.nn.relu(conv2d(x_image, w_conv1) +b_conv1), tf.nn.sigmoid(conv2d(x_image, w_conv1) + b_conv1), tf.nn.tanh(conv2d(x_image, w_conv1) + b_conv1)} [tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1)]
Traceback (most recent call last):
  File "/home/czh/.local/lib/python3.6/site-packages/smac/scenario/scenario.py", line 414, in _transform_arguments
    self.cs = pcs.read(pcs_str)
  File "/home/czh/.local/lib/python3.6/site-packages/ConfigSpace/read_and_write/pcs.py", line 245, in read
    raise NotImplementedError("Could not parse: %s" % line)
NotImplementedError: Could not parse: mnist/self.conv_size/choice categorical {2, 3, 5, 7} [2]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/__main__.py", line 189, in main
    dispatcher.run()
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/msg_dispatcher_base.py", line 63, in run
    self.handle_request((command, data))
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/msg_dispatcher_base.py", line 105, in handle_request
    return command_handlers[command](data)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/msg_dispatcher.py", line 93, in handle_initialize
    self.tuner.update_search_space(data)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/smac_tuner/smac_tuner.py", line 132, in update_search_space
    self.optimizer = self._main_cli()
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/smac_tuner/smac_tuner.py", line 94, in _main_cli
    scen = Scenario(args.scenario_file, [])
  File "/home/czh/.local/lib/python3.6/site-packages/smac/scenario/scenario.py", line 115, in __init__
    self._transform_arguments()
  File "/home/czh/.local/lib/python3.6/site-packages/smac/scenario/scenario.py", line 417, in _transform_arguments
    self.cs = pcs_new.read(pcs_str)
  File "/home/czh/.local/lib/python3.6/site-packages/ConfigSpace/read_and_write/pcs_new.py", line 357, in read
    raise NotImplementedError("Could not parse: %s" % line)
NotImplementedError: Could not parse: mnist/tf.nn.relu/function_choice categorical {tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1), tf.nn.sigmoid(conv2d(x_image, w_conv1) + b_conv1), tf.nn.tanh(conv2d(x_image, w_conv1) + b_conv1)} [tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1)]
[2019-02-08 00:46:02] PRINT ERROR:      Could not parse: mnist/tf.nn.relu/function_choice categorical {tf.nn.relu(conv2d(x_image, w_conv1) +b_conv1), tf.nn.sigmoid(conv2d(x_image, w_conv1) + b_conv1), tf.nn.tanh(conv2d(x_image, w_conv1) + b_conv1)} [tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1)]
Traceback (most recent call last):
  File "/home/czh/.local/lib/python3.6/site-packages/smac/scenario/scenario.py", line 414, in _transform_arguments
    self.cs = pcs.read(pcs_str)
  File "/home/czh/.local/lib/python3.6/site-packages/ConfigSpace/read_and_write/pcs.py", line 245, in read
    raise NotImplementedError("Could not parse: %s" % line)
NotImplementedError: Could not parse: mnist/self.conv_size/choice categorical {2, 3, 5, 7} [2]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/__main__.py", line 202, in <module>
    main()
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/__main__.py", line 189, in main
    dispatcher.run()
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/msg_dispatcher_base.py", line 63, in run
    self.handle_request((command, data))
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/msg_dispatcher_base.py", line 105, in handle_request
    return command_handlers[command](data)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/msg_dispatcher.py", line 93, in handle_initialize
    self.tuner.update_search_space(data)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/smac_tuner/smac_tuner.py", line 132, in update_search_space
    self.optimizer = self._main_cli()
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni/smac_tuner/smac_tuner.py", line 94, in _main_cli
    scen = Scenario(args.scenario_file, [])
  File "/home/czh/.local/lib/python3.6/site-packages/smac/scenario/scenario.py", line 115, in __init__
    self._transform_arguments()
  File "/home/czh/.local/lib/python3.6/site-packages/smac/scenario/scenario.py", line 417, in _transform_arguments
    self.cs = pcs_new.read(pcs_str)
  File "/home/czh/.local/lib/python3.6/site-packages/ConfigSpace/read_and_write/pcs_new.py", line 357, in read
    raise NotImplementedError("Could not parse: %s" % line)
NotImplementedError: Could not parse: mnist/tf.nn.relu/function_choice categorical {tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1), tf.nn.sigmoid(conv2d(x_image, w_conv1) + b_conv1), tf.nn.tanh(conv2d(x_image, w_conv1) + b_conv1)} [tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1)]
```

**Comment by QuanluZhang** [comment]
@zehuichen123 Please make sure you installed SMAC through the command `nnictl package install --name=SMAC`.
https://nni.readthedocs.io/en/latest/Builtin_Tuner.html#SMAC

**Comment by QuanluZhang** [comment]
@zehuichen123 thanks for raising this issue. This is a bug we introduced after annotation refactor. This only occurs in SMAC tuner. We will fix this bug very soon, and inform you after the bug is fixed.

**Comment by Dinghow** [comment]
I've met the same problem.

**Comment by QuanluZhang** [comment]
resolved by https://github.com/Microsoft/nni/pull/716. It will be included in the next release.
