### ISSUE TITLE
MNIST-annotation for dict type

### ISSUE THREAD

**Issue by zehuichen123** [Microsoft/nni#718]
- NNI version: v0.5.1

I comment the line in `examples/trials/mnist-annotation/mnist.py` line 33:
```
"""@nni.variable(nni.choice(124, 512, 1024), name=self.hidden_size)"""
```
and add some lines to function `get_params()` in line 214:
```python
args, _ = parser.parse_known_args()
"""@nni.variable(nni.choice(124, 512, 1024), name=args['hidden_size'])"""
args['hidden_size'] = 1024
```
But it reports an error:
```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 258, in parse
    transformer.visit(ast_tree)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 194, in visit
    return self._visit_children(node)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 240, in _visit_children
    self.generic_visit(node)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 211, in visit
    return self._visit_children(node)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 240, in _visit_children
    self.generic_visit(node)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 207, in visit
    return replace_variable_node(node, annotation)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 148, in replace_variable_node
    assert test_variable_equal(node.targets[0], name), 'Annotated variable has wrong name'
AssertionError: Annotated variable has wrong name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_annotation/__init__.py", line 104, in _expand_file_annotations
    annotated_code = code_generator.parse(src.read())
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_annotation/code_generator.py", line 260, in parse
    raise RuntimeError('%d: %s' % (ast_tree.last_line, exc.args[0]))
AttributeError: 'Module' object has no attribute 'last_line'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/czh/bin/nnictl", line 11, in <module>
    sys.exit(parse_args())
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_cmd/nnictl.py", line 182, in parse_args
    args.func(args)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_cmd/launcher.py", line 508, in create_experiment
    launch_experiment(args, experiment_config, 'new', config_file_name)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_cmd/launcher.py", line 337, in launch_experiment
    code_dir = expand_annotations(experiment_config['trial']['codeDir'], path)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_annotation/__init__.py", line 92, in expand_annotations
    annotated |= _expand_file_annotations(src_path, dst_path)
  File "/usr/local/anaconda3/envs/czh/lib/python3.6/site-packages/nni_annotation/__init__.py", line 113, in _expand_file_annotations
    raise RuntimeError(src_path + ' ' + '\n'.join(str(arg) for arg in exc.args))
RuntimeError: /home/czh/nni/examples/trials/mnist-annotation/./mnist.py 'Module' object has no attribute 'last_line'
```

**Comment by Crysple** [comment]
Thanks for reporting this. We found that it is due to a bug of annotation, which causes that currently annotation only support annotate an assign statement whose left value is a explicit variable (not dict type or any other complex type). We will fix it soon

**Comment by Dinghow** [comment]
I've met the samee problem.

**Comment by Crysple** [comment]
This bug has been fixed in the master branch. Refer to #720
