### ISSUE TITLE
SSH error when set multiple trial currency in remote trainingservice 

### ISSUE THREAD

**Issue by SparkSnail** [Microsoft/nni#785]
When set trialcurrency >= 8, there will be ssh error.
```
(node:7677) ExperimentalWarning: The fs.promises API is experimental
{ Error: (SSH) Channel open failure: open failed
    at SSH2Stream.onFailure (/home/t-shya/.local/nni/node_modules/ssh2/lib/client.js:1203:13)
    at Object.onceWrapper (events.js:273:13)
    at SSH2Stream.emit (events.js:182:13)
    at parsePacket (/home/t-shya/.local/nni/node_modules/ssh2-streams/lib/ssh.js:3709:10)
    at SSH2Stream._transform (/home/t-shya/.local/nni/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/home/t-shya/.local/nni/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
  name: 'Training service error',
  cause:
   { Error: (SSH) Channel open failure: open failed
       at SSH2Stream.onFailure (/home/t-shya/.local/nni/node_modules/ssh2/lib/client.js:1203:13)
       at Object.onceWrapper (events.js:273:13)
       at SSH2Stream.emit (events.js:182:13)
       at parsePacket (/home/t-shya/.local/nni/node_modules/ssh2-streams/lib/ssh.js:3709:10)
       at SSH2Stream._transform (/home/t-shya/.local/nni/node_modules/ssh2-streams/lib/ssh.js:671:13)
       at SSH2Stream.Transform._read (_stream_transform.js:190:10)
       at SSH2Stream._read (/home/t-shya/.local/nni/node_modules/ssh2-streams/lib/ssh.js:253:15)
       at SSH2Stream.Transform._write (_stream_transform.js:178:12)
       at doWrite (_stream_writable.js:410:12)
       at writeOrBuffer (_stream_writable.js:394:5) reason: 'ADMINISTRATIVELY_PROHIBITED', lang: '' } }

```

**Comment by SparkSnail** [comment]
https://github.com/Microsoft/nni/pull/829

**Comment by scarlett2018** [comment]
seems had fixed in PR 829, @sparksnail, please reopen it if there are still left work.

**Comment by SparkSnail** [comment]
This issue is fixed with PR 829.
