### ISSUE TITLE
Dispatcher error under any Tuner

### ISSUE THREAD

**Issue by sueerie** [Microsoft/nni#861]
I am running the example code under some mnist folders. I modified builtinTunerName option in config.yml to try to get result. And it kept reporting an error in the webpage:
![image](https://user-images.githubusercontent.com/27913116/54504062-feb3c280-496c-11e9-8e8a-9c44adc76652.png)
However, the command line implies that the experiment was successfully started.

I also checked the log file in `dispatcher.log`:
```
[2019-03-18 09:29:56] DEBUG (nni.main) START
[2019-03-18 09:29:57] INFO (hyperopt.utils) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2019-03-18 09:29:57] INFO (hyperopt.fmin) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[2019-03-18 09:29:57] DEBUG (nni.msg_dispatcher) Assessor is not configured
[2019-03-18 09:29:57] DEBUG (nni.msg_dispatcher_base) waiting receive_message
[2019-03-18 09:29:57] DEBUG (nni.protocol) Received command, header: [b'IN000759']
[2019-03-18 09:29:57] DEBUG (nni.protocol) Received command, data: [{"mnist/self.conv_size/choice": {"_type": "choice", "_value": [2, 3, 5, 7]}, "mnist/self.hidden_size/choice": {"_type": "choice", "_value": [124, 512, 1024]}, "mnist/self.learning_rate/loguniform": {"_type": "loguniform", "_value": [0.0001, 0.1]}, "mnist/tf.nn.relu/function_choice": {"_type": "choice", "_value": ["tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1)", "tf.nn.sigmoid(conv2d(x_image, w_conv1) + b_conv1)", "tf.nn.tanh(conv2d(x_image, w_conv1) + b_conv1)"]}, "mnist/max_pool/function_choice": {"_type": "choice", "_value": ["max_pool(h_conv1, self.pool_size)", "avg_pool(h_conv1, self.pool_size)"]}, "mnist/batch_size/choice": {"_type": "choice", "_value": [1, 4, 8, 16, 32]}, "mnist/dropout_rate/choice": {"_type": "choice", "_value": [0.5, 0.9]}}]
[2019-03-18 09:29:57] DEBUG (nni.msg_dispatcher_base) handle request: command: [CommandType.Initialize], data: [{"mnist/self.conv_size/choice": {"_type": "choice", "_value": [2, 3, 5, 7]}, "mnist/self.hidden_size/choice": {"_type": "choice", "_value": [124, 512, 1024]}, "mnist/self.learning_rate/loguniform": {"_type": "loguniform", "_value": [0.0001, 0.1]}, "mnist/tf.nn.relu/function_choice": {"_type": "choice", "_value": ["tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1)", "tf.nn.sigmoid(conv2d(x_image, w_conv1) + b_conv1)", "tf.nn.tanh(conv2d(x_image, w_conv1) + b_conv1)"]}, "mnist/max_pool/function_choice": {"_type": "choice", "_value": ["max_pool(h_conv1, self.pool_size)", "avg_pool(h_conv1, self.pool_size)"]}, "mnist/batch_size/choice": {"_type": "choice", "_value": [1, 4, 8, 16, 32]}, "mnist/dropout_rate/choice": {"_type": "choice", "_value": [0.5, 0.9]}}]
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 2
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 3
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 5
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 7
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 124
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 512
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 1024
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 0.0001
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 0.1
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction tf.nn.relu(conv2d(x_image, w_conv1) + b_conv1)
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction tf.nn.sigmoid(conv2d(x_image, w_conv1) + b_conv1)
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction tf.nn.tanh(conv2d(x_image, w_conv1) + b_conv1)
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction max_pool(h_conv1, self.pool_size)
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction avg_pool(h_conv1, self.pool_size)
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 1
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 4
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 8
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 16
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 32
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 0.5
[2019-03-18 09:29:57] INFO (hyperopt_AutoML) in_x is not a dict or a list in json2space fuinction 0.9
[2019-03-18 09:29:57] DEBUG (nni.protocol) Sending command, data: [b'ID000000']
[2019-03-18 09:29:57] DEBUG (nni.msg_dispatcher_base) waiting receive_message
[2019-03-18 09:29:57] DEBUG (nni.protocol) Received command, header: [b'PI000000']
[2019-03-18 09:29:57] ERROR (nni.main) b'PI' is not a valid CommandType
Traceback (most recent call last):
  File "/Users/sueee/Library/Python/3.6/lib/python/site-packages/nni/__main__.py", line 185, in main
    dispatcher.run()
  File "/Users/sueee/Library/Python/3.6/lib/python/site-packages/nni/msg_dispatcher_base.py", line 48, in run
    command, data = receive()
  File "/Users/sueee/Library/Python/3.6/lib/python/site-packages/nni/protocol.py", line 87, in receive
    command = CommandType(header[:2])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: b'PI' is not a valid CommandType
[2019-03-18 09:29:57] ERROR (nni.main) b'PI' is not a valid CommandType
Traceback (most recent call last):
  File "/Users/sueee/Library/Python/3.6/lib/python/site-packages/nni/__main__.py", line 198, in <module>
    main()
  File "/Users/sueee/Library/Python/3.6/lib/python/site-packages/nni/__main__.py", line 185, in main
    dispatcher.run()
  File "/Users/sueee/Library/Python/3.6/lib/python/site-packages/nni/msg_dispatcher_base.py", line 48, in run
    command, data = receive()
  File "/Users/sueee/Library/Python/3.6/lib/python/site-packages/nni/protocol.py", line 87, in receive
    command = CommandType(header[:2])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/enum.py", line 291, in __call__
    return cls.__new__(cls, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/enum.py", line 533, in __new__
    return cls._missing_(value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/enum.py", line 546, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: b'PI' is not a valid CommandType
```

**Comment by leelaylay** [comment]
@sueerie 
According to the commit history, the CommandType `Ping = b'PI'` was added since version 0.5.1. So I suppose that you used older NNI version before in your computer and have not uninstalled it clean yet.
I recommand you to reinstall the NNI in a clean way.
```shell
# if you install nni through pip
python3 -m pip uninstall nni-sdk 
python3 -m pip uninstall nni
python3 -m pip install nni

# if you install nni through source code 
cd nni
make clean
make uninstall
make easy-dev-install
```

**Comment by scarlett2018** [comment]
@leelaylay - can we auto detect whether the old version is cleaned up before install new versions?

**Comment by leelaylay** [comment]
> @leelaylay - can we auto detect whether the old version is cleaned up before install new versions?

I don't know whether there is any other elegant way to auto detect cleanup work. This is my solution below.
```shell
# check if nnictl exists
which nnictl
# check if nni-sdk exists
python3 -c "import nni"

# if nni older version exists and is older than 0.5
## do the cleanup work and install nni through pip or source code

# if nni older version doesn't exist or is newer than 0.5
## install (or upgrade) from pip
python3 -m pip install --upgrade nni

# or install(or upgrade) from source code 
make dev-easy-install
```

**Comment by sueerie** [comment]
Thanks~
